### ISSUE TITLE
panic in group by when not pushed down

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#100]
CHECK RESULT:
#datatype,string,string
#group,true,true
#default,,
,error,reference
,"panic: runtime error: index out of range
goroutine 15 [running]:
runtime/debug.Stack(0x1566300, 0x155e820, 0x1aa37f0)
    /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1.1(0xc0001a0f00)
    /Users/lyon/go/src/github.com/influxdata/flux/execute/dispatcher.go:73 +0xbc
panic(0x155e820, 0x1aa37f0)
    /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/influxdata/flux/execute.(*ColListTable).Strings(0xc0000d0aa0, 0xffffffffffffffff, 0xc00026626d, 0x7, 0x3)
    /Users/lyon/go/src/github.com/influxdata/flux/execute/table.go:725 +0xee
github.com/influxdata/flux/execute.AppendMappedRecord(0x1, 0x16acc00, 0xc0000d0aa0, 0x16b46a0, 0xc000263290, 0xc00003a2d0, 0xa, 0xa)
    /Users/lyon/go/src/github.com/influxdata/flux/execute/table.go:217 +0x2a4
github.com/influxdata/flux/functions/transformations.(*groupTransformation).Process.func1(0x16acc00, 0xc0000d0aa0, 0x1, 0xc000265350)
    /Users/lyon/go/src/github.com/influxdata/flux/functions/transformations/group.go:255 +0xd9
github.com/influxdata/flux/execute.(*ColListTable).Do(0xc0000d0aa0, 0xc000265350, 0x9, 0xc00003a280)
    /Users/lyon/go/src/github.com/influxdata/flux/execute/table.go:705 +0x3c
github.com/influxdata/flux/functions/transformations.(*groupTransformation).Process(0xc000530980, 0xda5d0f6b341b275a, 0x81a13ee6cc441081, 0x16a89e0, 0xc0000d0aa0, 0x1, 0x0)
    /Users/lyon/go/src/github.com/influxdata/flux/functions/transformations/group.go:246 +0x27b
github.com/influxdata/flux/execute.processMessage(0x16a90a0, 0xc000530980, 0x16a2ce0, 0xc00018b080, 0xc00046cf00, 0x0, 0x0)
    /Users/lyon/go/src/github.com/influxdata/flux/execute/transport.go:199 +0x1fc
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc0001a1560, 0xa)
    /Users/lyon/go/src/github.com/influxdata/flux/execute/transport.go:156 +0xa1
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages-fm(0xa)
    /Users/lyon/go/src/github.com/influxdata/flux/execute/transport.go:137 +0x34
github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc0001a0f00, 0x16a74e0, 0xc0002d8480)
    /Users/lyon/go/src/github.com/influxdata/flux/execute/dispatcher.go:126 +0x4b
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1(0xc0001a0f00, 0x16a74e0, 0xc0002d8480)
    /Users/lyon/go/src/github.com/influxdata/flux/execute/dispatcher.go:80 +0x95
created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
    /Users/lyon/go/src/github.com/influxdata/flux/execute/dispatcher.go:61 +0x7e
",

**Comment by aanthony1243** [comment]
copied from Slack: 

```#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,string,string,string,string,string,string,string
#group,false,false,true,true,false,true,true,true,true,false,false,false
#default,_result,,,,,,,,,,,
,result,table,_start,_stop,_time,taskID,orgID,status,_measurement,requestedAt,runID,scheduledFor
,,0,2018-10-02T17:55:11.520461Z,2018-10-03T17:55:11.520461Z,2018-10-03T17:55:11.01114Z,02bac3c8f0f37000,02bac3c8d6c5b000,started,records,1970-01-01T00:00:01Z,02bac3c908f37000,2018-10-03T17:55:12Z
,,0,2018-10-02T17:55:11.520461Z,2018-10-03T17:55:11.520461Z,2018-10-03T17:55:11.113222Z,02bac3c8f0f37000,02bac3c8d6c5b000,started,records,,02bac3c922737000,2018-10-03T17:55:13Z

#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,string,string,string,string,string,string
#group,false,false,true,true,false,true,true,true,true,false,false
#default,_result,,,,,,,,,,
,result,table,_start,_stop,_time,taskID,orgID,status,_measurement,runID,scheduledFor
,,1,2018-10-02T17:55:11.520461Z,2018-10-03T17:55:11.520461Z,2018-10-03T17:55:10.920529Z,02bac3c8f0f37000,02bac3c8d6c5b000,success,records,02bac3c8f1737000,2018-10-03T17:55:11Z
,,1,2018-10-02T17:55:11.520461Z,2018-10-03T17:55:11.520461Z,2018-10-03T17:55:11.01435Z,02bac3c8f0f37000,02bac3c8d6c5b000,success,records,02bac3c908f37000,2018-10-03T17:55:12Z
,,1,2018-10-02T17:55:11.520461Z,2018-10-03T17:55:11.520461Z,2018-10-03T17:55:11.115415Z,02bac3c8f0f37000,02bac3c8d6c5b000,success,records,02bac3c922737000,2018-10-03T17:55:13Z```
2 tables here, nearly the same schema except the second one has no column `requestedAt`
this occurs as a result of `pivot`  which is another point to discuss, but one thing at a time.
above, if we `group(by: ["runID"])`   we get a panic
the bug is easy to trace, it's basically because we only use a `GroupKey`  to index results.   Since `requestedAt`  is not part of the group key, we try to map the second table into a table builder with a schema that includes `requestedAt`
so the question is what the proper behavior is here:   `error`   or  `fill`  ?
OR...do we disallow a result like this from happening at all?

**Comment by aanthony1243** [comment]
proposal:  

1.  Write a helper function `Execute.AddNewTableCols(tbl, builder)`  that will modify the table builder column set to be a super set of the existing builder, plus any new columns in `tbl` but not in builder.  Throws an error if we find two columns with the same name but different types.  
2.  We have several functions of the form `execute.AppendMappedXX`.  these should be updated to accommodate unmapped columns from the incoming column set. That is, if a column mapping is unknown then we should substitute a default  (eventually NULL) value for that column value.  

I think this should cover most cases,  anything I'm missing?

**Comment by jsternberg** [comment]
I think we definitely need to get null support to do this properly, although default values in the interim is likely fine.

The proposal seems fine to me, although I would like a nicer way of dealing with conflicting types. I do have a question about the mapped columns. Should the table interface use mapped columns by default? We obviously need to keep the same internal structure, but it seems to me like the outward interface should allow you to specify the column name rather than searching through the column metadata to find it.

**Comment by aanthony1243** [comment]
all of the mapped column code is optional helper functions. That being said, they are used quite a bit.  The original design I think implicitly assumed that the mapping was always from a larger input table to a smaller output table.  The fix will be to make them robust to any column schema case.
