### ISSUE TITLE
generalize map functions to recognize all package functions (e.g. string)

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#1000]
fix this: 
```
from(bucket:"telegraf") |> range(start:-5m) |> filter(fn: (r) => r._field == "usage_user") |> map(fn: (r) => ({trimmed: strings.trim(v: r.cpu, cutset:"c")})
Error: type error 0:0-0:0: undefined identifier "strings"
```

This is a more involved fix than previously thought.  specifically: 
1.  Packages are referenced in, but not attached to, the incoming AST/Spec for a query.  
2.  At the top level, this is fine, we see an import statement and bring in the packages we need to run the query. 
3.  At the row-function level (e.g. `map` and `filter`), the scope of the larger script is not provided for the transformation phase.  
4.  ResolveFunction fails to resolve functions that reference a package because those functions are identified by name and parameters, and so the implementation is not found.  

Some hope: 
1.  At the op-spec level, we DO get an accurate scope object for the incoming function.  
2. We could encode all/part of that to  send down the execution path for planning + execution.  
3. probably our re-implementation of the IR layer will help us to rectify some of these problems.  Regardless, the core NEED is that the scope of a query is available for processing by internal transformations.

**Comment by wolffcm** [comment]
Moving forward, are we going to remove the `flux.Spec` from the public API?  If that happens, will clients continue to interpret the Flux script on the client-side at all?  This is a much easier problem to solve if interpretation/execution is not distributed.

I had some thoughts on this after a discussion with Adam yesterday...

In the current architecture, it seems like the Interpreter needs to produce a `Scope` object in addition to the `[]values.Value` it produces, and that this `Scope` could be made accessible from the `execute.Administration` object that is passed to the functions that create transformations, like `createMapTransformation`.

Transformations that need to call lambdas could then pass the Scope to the `fn.Prepare` method which would make the in-scope packages available to type inference.

But as Adam said, it seems like any solution in this space would be temporary before a new IR layer comes to fruition.

**Comment by aanthony1243** [comment]
@wolffcm  in fact, a scope object is attached to the values.Function that's given as an argument to the CreateOpSpec function.  so what we need seems to be there, it's just a matter of hooking it into the right places.

**Comment by affo** [comment]
After a call we added considerations for a client-server architecture:

The client compiles everything but the functions passed to `map` and `filter`. Those functions are compiled at runtime by the server.  
In order for them to have the correct scope, we should serialize it along with the the Spec in order for the server-side compilation step to succeed.
