### ISSUE TITLE
Expose parsing functions for individual AST nodes

### ISSUE THREAD

**Issue by juliusv** [influxdata/flux#1002]
For transpiling from other languages it'd be helpful to easily parse arbitrary AST nodes from Flux script snippets. Currently only `ParseSource()` is exposed, which returns an entire package. It could be a good idea to expose the parsing functions for the individual lower-level node types.

**Comment by juliusv** [comment]
Exposing parsing functionality for individual AST nodes does not yet solve the problem of then wanting to replace certain sub-nodes with variable values / types. Thus I'm going with full manual AST construction for now and this is less urgent / needed.

**Comment by nathanielc** [comment]
I am going to close this now as it seems it was not needed. We can reopen if it becomes relevant later.
