### ISSUE TITLE
Parser deadlock with 100% CPU usage when using incorrect quotes

### ISSUE THREAD

**Issue by juliusv** [influxdata/flux#1009]
With InfluxDB 2.0.0-alpha3, the following Flux query runs forever with 100% CPU usage for me:

```
from(bucket: "prometheus")
  |> range(start: 2019-02-21T16:58:40Z, stop: 2019-02-21T16:59:00Z)
  |> filter(fn: (r) => r._measurement == "demo_cpu_usage_seconds_total")
  |> last()
  |> group(columns: ['_stop'])
```

Judging by pprof, it looks hung somewhere in the Flux parser while parsing an expression list.

Without the `group...`, the query completes.

The test data set is the same as attached to this comment: https://github.com/influxdata/flux/issues/997#issuecomment-468373251

**Comment by jlapacik** [comment]
The issue is the single quoted string `'_stop'` in the call to `group`. In Flux strings are delimited by double quotes. Currently the parser just swallows the error and keeps going (in an invalid state). Instead it should report the error.

**Comment by jsternberg** [comment]
The deadlock is likely because single quotes aren't part of the grammar and so a single quote is seen as an illegal token. There's likely a bug where the parser in that section doesn't discard the illegal token.

I'll take a look. I'm surprised it wasn't caught during fuzzing, but it happens.

**Comment by jsternberg** [comment]
Just to clarify, @jlapacik is completely right about the solution for fixing the query. I understand this issue to solely be about fixing the deadlock so the parser correctly reports this is an error.

**Comment by juliusv** [comment]
Agreed. I updated the issue title to reflect that.
