### ISSUE TITLE
Add mode parameter to stddev function for population vs sample stddev

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1010]
There are two kinds of standard deviation, population and sample. Sample uses `n-1` in the denominator while population uses just `n`. We should add a `mode` parameter to the stddev function to specify which method to use.

**Comment by nathanielc** [comment]
Some relevant info 
https://www.khanacademy.org/math/statistics-probability/summarizing-quantitative-data/variance-standard-deviation-sample/a/population-and-sample-standard-deviation-review

https://www.khanacademy.org/math/ap-statistics/summarizing-quantitative-data-ap/more-standard-deviation/v/another-simulation-giving-evidence-that-n-1-gives-us-an-unbiased-estimate-of-variance

**Comment by juliusv** [comment]
On this.
