### ISSUE TITLE
Formatting AST loses parentheses and thus operator associativity

### ISSUE THREAD

**Issue by juliusv** [influxdata/flux#1012]
An AST that was parsed from `(1.0 * 2.0 + 4.0 / 6.0 - 10.0) * r._value` gets formatted out by `ast.Format()` as `1.0 * 2.0 + 4.0 / 6.0 - 10.0 * r._value`, losing parentheses and thus losing the original associativity.

Either parentheses should be explicitly preserved in the AST or the Formatter needs to add them back according to operator precedence, when needed.

**Comment by jsternberg** [comment]
Some pros and cons to the possible solutions for this.

## Add explicit parens

1. *For:* The ast parsing will be more accurate and it will be possible to output the same format without using format is you output the AST.
2. *For:* This may be needed for some error handling. I have suspected this, but haven't actually worked on it.
3. *Against:* This was a source of a lot of bugs in influxql when the parens weren't added correctly. If we rely on the parens for ensuring the AST is output correctly, we will likely run into these bugs again.

## Added as part of AST format

1. For: It is automatic. The in-memory representation is how it is output. No possibility of accidentally mutating the AST when outputting and reparsing.
2. For: It would automatically remove extraneous parens like `go/format` does.
3. Against: You can't accurately get what the original file looks like.

Thinking about it a bit more, I would say we can likely combine these methods.

1. Add parenthesis to the AST and modify the parser to use them.
2. Make `ast.Format` just not care. It will discard parenthesis when formatting and will add them as needed.

We can probably separate these tasks and just do the second one to fix this issue and continue punting on the first one.

**Comment by juliusv** [comment]
@affo Hmm, should this have fixed situations like this:

I have a function call that *should* be this (parentheses around the right-hand-side expression), according to the underlying AST:

    map(fn: (r) =>
        		({_value: r._value - (1.0 * 2.0 + 4.0 / 6.0 - 10.0), _stop: r._stop, _time: r._stop}))

...but instead the formatter outputs:

    map(fn: (r) =>
        		({_value: r._value - 1.0 * 2.0 + 4.0 / 6.0 - 10.0, _stop: r._stop, _time: r._stop}))

...which yields a different result.

The underlying AST node that doesn't get formatted correctly is:

```go
&ast.BinaryExpression{
	Operator: op,
	Left: &ast.MemberExpression{
		Object: &ast.Identifier{
			Name: "r",
		},
		Property: &ast.Identifier{
			Name: "_value",
		},
	},
	Right:    rhs, // The numeric calculation.
},
```

**Comment by juliusv** [comment]
Indeed, if I add this test case:

```go
		{
			name: "foo",
			script: `foo = (r) =>
	r._value - (1 * 2 + 4 / 6 - 10)`,
		},
```

I get:

```
    --- FAIL: TestFormat_Associativity/foo (0.00s)
        /home/julius/gosrc/src/github.com/influxdata/flux/ast/format_test.go:44: unexpected output: -want/+got:
             {string}:
            	-: "foo = (r) =>\n\tr._value - (1 * 2 + 4 / 6 - 10)"
            	+: "foo = (r) =>\n\t(r._value - 1 * 2 + 4 / 6 - 10)"
```
