### ISSUE TITLE
Investigate how to make many groups work efficiently

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1020]

**Comment by jsternberg** [comment]
This appears to happen with windowing too. Can we expand the description on what this issue means? Is this only about groups created with `group()` or about the specific function of `window()` or both? I think we'll likely need to split this out to address them separately, but that's currently just a hunch.

**Comment by jlapacik** [comment]
I am closing this issue now that #1035 has been fixed and #1053 has been merged.
