### ISSUE TITLE
Proposal: Modify GroupKey interface to make it more friendly to memory usage

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#1032]
At the moment, `GroupKey` is an interface. There's one implementation of it in the `execute` package.  The current interface is as follows:

```go
type GroupKey interface {
	Cols() []ColMeta
	Values() []values.Value

	HasCol(label string) bool
	LabelValue(label string) values.Value

	IsNull(j int) bool
	ValueBool(j int) bool
	ValueUInt(j int) uint64
	ValueInt(j int) int64
	ValueFloat(j int) float64
	ValueString(j int) string
	ValueDuration(j int) values.Duration
	ValueTime(j int) values.Time
	Value(j int) values.Value

	Equal(o GroupKey) bool
	Less(o GroupKey) bool
	String() string
}
```

Unfortunately, this interface is very difficult as an interface. The culprits are `Cols`, `Equal`, and `Less`.

For `Cols`, it is difficult as an interface because it assumes a certain implementation under the hood. To efficiently implement this method, you _must_ keep a cached copy of the column metadata or your implementation will be unusable. This method is assumed to be fast. That means that building a group key interface that wraps around another group key can never really work because it would require copying the columns anyway which basically means you are making a new group key and you might as well use the implementation in `execute`.

The `Equal` and `Less` methods are a problem because they aren't really implementable within an interface like this for a few reasons.

1. Group key columns are order preserving so we do not know if the columns are in the same order for comparisons.
2. We need to implement it while only accessing values within one group key from the public interface. This ends up having to be repeated from every implementation if we were to do that. It should be possible to compare a group key using only the public interface without assumptions about the internal structure.

I propose a slightly different implementation that should make the above much easier and allow extensibility as described below.

```go
type GroupKey interface {
	// Used for iteration and accessing columns instead.
	// This way, we do not need to care about the underlying representation
	// of the column metadata.
	NCols() int
	Col(idx int) ColMeta

	// The Values method isn't really needed so it is removed.

	// All of these are retained.
	HasCol(label string) bool
	LabelValue(label string) values.Value

	IsNull(j int) bool
	ValueBool(j int) bool
	ValueUInt(j int) uint64
	ValueInt(j int) int64
	ValueFloat(j int) float64
	ValueString(j int) string
	ValueDuration(j int) values.Duration
	ValueTime(j int) values.Time
	Value(j int) values.Value

        // Sorting functions are removed and replaced with the SortedGroupKey
        // interface which is defined below. The standard GroupKey implementation
        // will already implemented SortedGroupKey.

	String() string
}

// SortedGroupKey provides additional methods to access the group key in a sorted
// manner. The group key is still ordered with its original ordering, but the columns
// are more accessible.
type SortedGroupKey interface {
        GroupKey

        SortedCol(idx int) ColMeta
	SortedIsNull(j int) bool
	SortedValueBool(j int) bool
	SortedValueUInt(j int) uint64
	SortedValueInt(j int) int64
	SortedValueFloat(j int) float64
	SortedValueString(j int) string
	SortedValueDuration(j int) values.Duration
	SortedValueTime(j int) values.Time
	SortedValue(j int) values.Value
}

// SortGroupKey will return a sorted version of the group key.
// The original group key is still present, but you can now use
// the Sorted methods to access the data in a consistent pattern.
// If an interface already implements flux.SortedGroupKey,
// this just performs the typecast.
func SortGroupKey(key flux.GroupKey) flux.SortedGroupKey
```

Here are a few things that become possible.

### Efficiently appending a single value to the group key

We can easily attach a new value to the group key without reconstructing the group key. This is because we can wrap it like this:

```go
type groupKeyAppend struct {
	parent GroupKey
	colMeta ColMeta
	value values.Value
}
```

In this way, we do not have to copy the `[]ColMeta` slice to implement `Cols()` and we do not have to copy the values to implement `Values()`. We also do not have to implement the sorting methods. Making the sorted implementation work would be to just look at the parent and find which index it would belong in.

### Efficiently replacing a value within an existing group key

This may be useful for #1020 to lessen the amount of memory we use for windowing keys. We produce a lot of groups if we have something like `range(start: -1h) |> window(every: 1m)` and that would end up being 60 new group keys. If we already have `_start` and `_stop` within the parent group key, we can create an interface that shadows and intercepts these values so we do not have to copy the other columns and values which would produce a lot of duplicate data.

## Conclusion

I think this is a fairly low cost solution that would allow future optimizations. The current interface lends itself to only having one possible implementation so it would be better as a struct in its current incarnation. I do not think the two optimizations above are very easily done or worth it with the old interface.

**Comment by aanthony1243** [comment]
the groupKeyAppend seems a little clunky, but I really like the rest of this.  is the append because we enforce that GroupKeys are immutable?

**Comment by jsternberg** [comment]
It's mostly my idea to allow for the `GroupKeyBuilder` to be more useful. In all likelihood, most of the transformations I want to do can be done in the same underlying wrapping type, but I wanted to give a hard example of something that would make this easier.

And yes, it is because of the group key being immutable. But I would also like it to be shared. The window example is the most prominent one I can think of, but something similar happens with the influxql source. I think if the group key were mutable this kind of idea would still be necessary.

**Comment by aanthony1243** [comment]
`window` is a good enough argument for this design, actually.  good point. 

how can we improve this interface to make group key lookups more efficient in the table cache?

**Comment by jsternberg** [comment]
I experimented with the benchmark by isolating the group key code so I didn't have to change everything to test the performance change. It is on the [perf/group-key](https://github.com/influxdata/flux/tree/perf/group-key) branch. Here are some initial numbers:

```
jsternberg:[~/g/s/g/i/f/i/e/group] $ (master *+$=) go test -bench=.
goos: darwin
goarch: amd64
pkg: github.com/influxdata/flux/internal/experimental/group
BenchmarkGroupKey-12               10000            147695 ns/op
BenchmarkKey-12                    50000             20287 ns/op
PASS
ok      github.com/influxdata/flux/internal/experimental/group  2.780s
```

I'm not sure how using arrow would affect this, but this seems like it is promising.

**Comment by jsternberg** [comment]
One thing I have found when trying to implement this was the `Sorted()` method doesn't really work how I wish it worked. It ends up being kind of difficult to implement and, very commonly, you want to get the sorted key and sometimes go back to the unsorted one which this interface doesn't allow.

So I was thinking about changing the above interface to remove the `Sorted()` method and include this.

```go
func Sort(key GroupKey) SortedGroupKey

type SortedGroupKey interface {
	GroupKey

	SortedCol(idx int) ColMeta

	SortedIsNull(j int) bool
	SortedValueBool(j int) bool
	SortedValueUInt(j int) uint64
	SortedValueInt(j int) int64
	SortedValueFloat(j int) float64
	SortedValueString(j int) string
	SortedValueDuration(j int) values.Duration
	SortedValueTime(j int) values.Time
	SortedValue(j int) values.Value
}
```

This would allow an implementation to both keep track of itself sorted and the normal implementation and would allow us to have a special implementation that wrapped a `GroupKey` and kept track of the sorted columns when necessary.

**Comment by jsternberg** [comment]
Modified the above to include the `SortedGroupKey` method as described in the last comment.
