### ISSUE TITLE
Proposal: Modify the memory allocator into an interface

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#1033]
The memory allocator is currently a struct and it should be an interface. The current struct has this interface:

```go
type Allocator interface {
	Allocate(size int) error
	Free(size int)
}
```

This interface works well and I like it. The issues is that since the current implementation is a struct and not an interface, we can't inject it with any optional behavior.

One possible change would be to have an allocator that had custom logic with the controller to know whether it can raise the maximum limit for a query or if the query should be killed with our own equivalent of an OOM. Since this isn't an interface, that's not possible. I propose modifying this into an interface and renaming the existing allocator to `AllocationTracker`.

**Comment by jsternberg** [comment]
I was looking at this a bit more and I'm not sure the above interface works. Since we integrated arrow, this struct isn't used anywhere except for the controller.

It seems to me like since the primary location where this needs to be used is within the controller, we should move the limit code to the controller and make it not a public interface. Then we can just use the arrow memory allocator in the code wherever we need this.

One potential issue with that is then we won't be able to add allocation code to the non-arrow code, but that is already kind of difficult since we have no control over the allocator for go code. I'm not really sure if we have a plan to deal with that.

**Comment by nathanielc** [comment]
Is this still relevant? If not let's close the issue.

**Comment by jsternberg** [comment]
I think it is, but the above interface is unlikely to work. Likely, it would be better if we had our interface match the one arrow uses.

**Comment by jsternberg** [comment]
Closing this in favor of #1861.
