### ISSUE TITLE
Remove the implicit _value column behavior of map

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1037]
Currently this is possible `map(fn: (r) => r._value + 2)` and it equivalent to this:

```
map(fn: (r) => ({_value: r._value + 2}))
```

Allowing for the implicit column name is confusing and inconsistent. We should remove this special case.

As an added bonus this simplification will make mapping over non table types easier.

**Comment by affo** [comment]
Do we want the same behavior for `reduce`? I am touching a portion of code which is very similar.
