### ISSUE TITLE
Missing "timeShift"/"offset"/"timedelta" functionality in Flux

### ISSUE THREAD

**Issue by toinbis** [influxdata/flux#1038]
Paul's blog post "InfluxDB 2.0 Alpha Release and the Road Ahead" contained a sentence: "Long standing feature requests like <...> **time shift** <...> are all possible in this initial alpha release." This got me hooked. As my main use case for TSDB is to chart several weeks, same weekday/timerange, data on same graph for comparison. In graphite I can achieve it using `timeShift()` function, prometheus makes it easy with `offset` modifier. I expected to achieve same in flux/influx.

Appearantly flux went on a road of separating selecting past ranges/shifting time columns to separate parts - `range()` and `shift()` - instead of bundling them both into one function. I.e. shift only adds provided duration to timestamps, does not select values from the past. Bit more complication vs graphite's `timeShift()`, potentially more flexibility. Makes sense. After understanding what `shift()` actually does I even managed to get this week and last week on the same chart. But I had to manually calculate range's `start` and `stop` absolute values relative to my dashboard's timerange. And at this final step I am stuck and don't understand if it's me or it's really not possible to use some timedelta functionality to calculate the correct `range()` function's `start` and `stop` parameter values dynamically relative to dashboard's time range values?

For example, to draw yesterday line on today's dashboard panel I'd be willing to use such pseudocode:  
`from(bucket: "telegraf/autogen")`  
`|> range(start: dashboardTime - 24h, stop: upperDashboardTime - 24h)`  
`|> shift(shift: 24h)`  
  
How would I achieve that `dashboardTime - 24h` and `upperDashboardTime - 24h` ?
  
Thanks.

**Comment by juliusv** [comment]
You basically need binary arithmetic operators to be implemented between time and duration types, right? I had a similar lack of comparison operators for time types and filed https://github.com/influxdata/flux/pull/999 for that. I guess it would make sense to add all sensical combinations of those comparison and arithmetic operators to Flux that are still missing.

**Comment by toinbis** [comment]
Thanks for reply, Julius. Sorry for not explaining my needs clearly enough.

>You basically need binary arithmetic operators to be implemented between time and duration types, right?  

Shortly - yes. Having arithmetic operators implemented between time and duration types would surely solve my use case of flux.

Thanks for pointing to  #999 (and providing PR itself!). It seems to be addressing time comparison operations as of now, subtraction and addition not included, yes?

**Comment by juliusv** [comment]
@toinbis Correct. It's just an example of how to add operators to Flux in general, so it might serve as inspiration. I'm not an InfluxData / Flux person, but at least from what I know about Flux I don't see a reason why binary operations between time types shouldn't be implemented.

**Comment by toinbis** [comment]
Went through flux specification and found that this needed functionality - addition and subtraction of time / duration types - is specified there: https://github.com/influxdata/flux/blob/master/docs/SPEC.md#duration-literals . It has it's own issue - #413 . Will inquire in #413 comments if there is any (planned) progress.

**Comment by nathanielc** [comment]
Closing as a `timeShift` function now exists https://github.com/influxdata/flux/blob/master/docs/SPEC.md#timeshift and we can track #413 for more general time manipulation.
