### ISSUE TITLE
promql: How to handle scalar sub-expressions / function arguments that vary over time

### ISSUE THREAD

**Issue by juliusv** [influxdata/flux#1042]
Scalar function parameters in PromQL can be arbitrary expressions that may involve or depend on the current evaluation step timestamp.

Consider the following query in PromQL:

```
quantile(0.5, rate(node_cpu_seconds_total[5m]))
```

This calculates the 50th percentile CPU usage among the set of input series.

Instead of hard-coding `0.5` you could do something crazy like the following (not that it would be sensical):

```
quantile(scalar(avg(up)), rate(node_cpu_seconds_total[5m]))
```

At every resolution evaluation step of the range query, this would compute the average value of the `up` metric at that timestamp and use it as the quantile argument for `quantile()`.

Note that the scalar expression does not necessarily have to rely on persisted data, but it could be dynamically generated out of thin air (but still perhaps depend on the current timestamp) like:

```
quantile(time(), node_cpu_seconds_total)
```

It could also be the input to a binary operation, not necessarily a function argument:

```
time() - batch_job_last_successful_run_timestamp_seconds > 3600
```

Determine how this can be handled in Flux. We probably need to convert those varying scalars into Flux tables internally and join on time, so expressions containing them would work differently from normal (constant) scalar expressions.

**Comment by nathanielc** [comment]
I think this will be possible with #1090 and loop/iteration support.

**Comment by juliusv** [comment]
For binary operations, I am now handling non-const scalars via generated tables and joins on time columns. This is already starting to work.

So we now only need to figure out (with very low urgency, this is almost never needed in PromQL) how to handle non-const scalar function arguments.
