### ISSUE TITLE
promql: Add `%` and `^` binary arithmetic operators

### ISSUE THREAD

**Issue by juliusv** [influxdata/flux#1043]
PromQL has the `%` and `^` arithmetic operators, which are still missing in Flux. These should be added to Flux.

**Comment by juliusv** [comment]
I've worked around this limitation by using `math.mod()` and `math.pow()` Flux functions, so from the transpilation perspective this isn't strictly required anymore, though it'd be nice in general to also add these as operators.

**Comment by sauren-khosla** [comment]
#1027 covers %
