### ISSUE TITLE
promql: Make percentile() edge-case behavior match PromQL

### ISSUE THREAD

**Issue by juliusv** [influxdata/flux#1044]
PromQL's `quantile()` can be *almost* emulated using Flux's `percentile()`, except that PromQL returns `-Inf` / `+Inf` if one chooses quantile values below `0` or above `1`, whereas Flux doesn't.

We could either ignore this (unlikely to come up in real use cases), change the behavior in Flux, or additionally add a PromQL-compatible version into Flux.

**Comment by nathanielc** [comment]
Possible solution is to use conditional logic to check the quantile value before calling the quantile function to return these values. This way there can be a specific promql version of the function that doesn't change the normal Flux version.
