### ISSUE TITLE
promql: Support implicit joins

### ISSUE THREAD

**Issue by juliusv** [influxdata/flux#1045]
PromQL automatically joins two sets of time series (instant vectors) on identical label sets on the LHS and RHS. E.g. the following calculates the average response time for every label combination that is on the involved series without having to specify `on` labels:

```
  rate(prometheus_http_request_duration_seconds_sum[5m])
/
  rate(prometheus_http_request_duration_seconds_count[5m])
```

Flux's `join()` does not support an implicit `on` on all columns yet. Can something like this be added?

**Comment by juliusv** [comment]
In addition, PromQL allows an `ignoring` modifier with labels to ignore for matching. This would be like `join()` having the opposite of an `on` argument, a list of columns to ignore for joining.

**Comment by aanthony1243** [comment]
see #1219

**Comment by aanthony1243** [comment]
@juliusv something like this was also proposed during our all-hands meetup, and might be a closer match to what you want:   https://github.com/influxdata/flux/issues/1297

could you compare with #1219   and let us know if you'd prefer one over the other?

**Comment by jlapacik** [comment]
I'm unclear on what's being asked here. Is it just that we `join` on common tag columns when the `on` parameter is not specified?

**Comment by juliusv** [comment]
@jlapacik Yes, the request would be to have a way to join records from two tables that have the exact same set of tag columns. So `a=b,c=d` would match `a=b,c=d`, but `a=b` wouldn't (as that's just a subset).

**Comment by jlapacik** [comment]
@juliusv we've designed a join function that I believe covers all PromQL join cases https://github.com/influxdata/flux/pull/1886. Can you confirm that this is correct? I've added examples of compiling PromQL joins into equivalent Flux.

**Comment by juliusv** [comment]
@jlapacik Oh cool, thanks! I'm currently traveling for a training, but will analyse it in detail beginning of next week at the latest! I need to really make sure that all important cases are covered that can happen in PromQL.
