### ISSUE TITLE
Optimize window transformation

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1048]
Possible areas to optimize window:

1. Remove need to sort windows on output.
2. Assert data has special sort order on input that is efficient. This may not have large gains and may actually be negative cost to sort. 
3. Use narrow trigger or window specific variant to trigger tables more aggressively.

Basic tradeoffs:

1. Assume for a happy path that data is coming from influxdb source at the cost of making other paths more expensive.

**Comment by jlapacik** [comment]
Window's memory consumption optimized by #1053 . Closing issue.
