### ISSUE TITLE
Got from testing.inspect seems empty even though diff is correct

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1050]
As you can see from the image, I was able to get a result from `testing.inspect` that has an empty `got`, but a `diff` that says that I got something more than there was in `want`.

![Schermata 2019-03-12 alle 17 52 41](https://user-images.githubusercontent.com/4246582/54230059-e889aa80-4505-11e9-87fe-7fb4b9ce7ad8.png)

**Comment by nathanielc** [comment]
This is likely fixed along with all the flakiness we fixed in these tests. Can you confirm?

**Comment by affo** [comment]
Yep, thank you 🙏 . Closing issue.
