### ISSUE TITLE
Can't use object property within filter function

### ISSUE THREAD

**Issue by chnn** [influxdata/flux#1055]
I'm attempting to run a function similar to the following:

```
d = {
  my_bucket: "telegraf",
  my_tag_key: "cpu"
}

from(bucket: d.my_bucket)
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == d.my_tag_key)
```

I receive this error:
```
type error 7:42-7:43: undefined identifier "d"
```

The issue seems to be related to the use of an object property within the filter function, since I can run this query successfully:

```
d = {
  my_bucket: "telegraf"
}

from(bucket: d.my_bucket)
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == "cpu")
```

I can also run this query successfully:

```
my_tag_key = "cpu"

from(bucket: "telegraf")
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == my_tag_key)
```

I'm seeing this on Flux v0.21.4 via InfluxDB master.

**Comment by jlapacik** [comment]
This is due to the enclosing program scope not being passed into the function constructor:
https://github.com/influxdata/flux/blob/94851bd8c79c29fa53d253f5c899c341de094427/execute/row_fn.go#L31

**Comment by wolffcm** [comment]
This is another manifestation of this issue, yes?
https://github.com/influxdata/flux/issues/1000

**Comment by jlapacik** [comment]
@wolffcm yes that is the issue I was looking for.

**Comment by russorat** [comment]
this is a blocker for variables in the UI.

**Comment by aanthony1243** [comment]
@russorat we have a plan for a partial fix. should work for objects with basic types (strings, ints, etc.).

**Comment by chnn** [comment]
@aanthony1243 The set of possible types we use for properties in the object are:

- `BooleanLiteral`
- `UnsignedIntegerLiteral`
- `IntegerLiteral`
- `FloatLiteral`
- `StringLiteral`
- `DateTimeLiteral`
- `DurationLiteral`

Will it handle the `DateTimeLiteral` and `DurationLiteral` cases too?

**Comment by aanthony1243** [comment]
The feature is done but for testing.  I'll use your list as a set of cases.

**Comment by aanthony1243** [comment]
@chnn here's the PR, should be on flux master by morning, and we can cut a release if it's urgent.  https://github.com/influxdata/flux/pull/1069

technically there's support for duration literals, but I couldn't cook up a good use-case for a duration literal inside of a `map` call.  there aren't many places in flux syntax where durations work well, outside of the `range` function.

**Comment by chnn** [comment]
Awesome, thank you.

I can't think of a use for duration literals inside a `map` call either.

For a little background on how we use this: the UI now supports defining external variables, which have a name and a Flux query. We execute the Flux query to obtain a list of values (from the first `_value` column in the response). A user can select a value from the list, which will be used in define the variable assignment. We encode these assignments as the AST for an object that looks like:

```
v = {
  my_var_name: "some_value"
}
```

The type of the value can be anything that comes back in a column in the CSV response. I was going off of [this table](https://github.com/influxdata/flux/blob/master/docs/SPEC.md#annotations), which is why we have support for duration literals. I think the support is purely hypothetical—I don't know of any Flux query which returns a duration column.

**Comment by nathanielc** [comment]
> I don't know of any Flux query which returns a duration column.

Currently Flux does not support duration columns, but it will eventually. So its good we support them for now, less work to do when we go to add support for them later.
