### ISSUE TITLE
Panic when using * operator with no preceding token

### ISSUE THREAD

**Issue by 121watts** [influxdata/flux#1056]
User submitted [this](https://github.com/influxdata/chronograf/issues/5094) issue in the chronograf repo.  When reproducing I noticed a panic on influxdb master.

`from(bucket: "telegraf/autogen") |> range(start: -5m) |> drop(fn: (column) => column =~ /*/)`

**Comment by jsternberg** [comment]
There might be an error with multiplication too, but this appears to be an invalid regex and the parser is discarding it and then a nil panic is getting hit later.

**Comment by nathanielc** [comment]
@jsternberg What should the error behavior be here? Do we need to add a new Check to the ast logic?

**Comment by jsternberg** [comment]
A new check would probably resolve it. If we have some cycles for this next week, I have a few opinions about the AST stuff that I'd like to write down and discuss with you. The short way of saying things is I don't think our current method of parsing and constructing the AST is working that well for our objectives, but I would like to write down why I believe that before we talk about it further.
