### ISSUE TITLE
shift() should support additional units

### ISSUE THREAD

**Issue by robcowart** [influxdata/flux#1059]
While working with a user their calculations require a shift of a full month. It looks like the shift functions leverages ParseDuration function of Go's time package, which supports only these units... "ns", "us" (or "µs"), "ms", "s", "m", "h"

It would be valuable to either use a different package, or add a custom duration parser to facilitate month-over-month and year-over-year use-cases.

**Comment by nathanielc** [comment]
@robcowart yes, we plan to support calendar durations. See #413 we have a plan for how to implement them.

Closing this issue as a duplicate.
