### ISSUE TITLE
Errors with percentile (aggregate) function

### ISSUE THREAD

**Issue by ischolten** [influxdata/flux#1063]
I am trying to run the below example query from the example in the spec https://github.com/influxdata/flux/blob/master/docs/SPEC.md#percentile-aggregate

```
from(bucket: "telegraf/autogen")
  |> range(start: -5m)
  |> filter(fn: (r) => r._measurement == "cpu" and r._field == "usage_system")
  |> percentile(percentile: 0.99, method: "estimate_tdigest", compression: 1000)
```

When I run this query, I get the error:
```
{"error":"failed to compile query: type error 8:5-8:80: float != int"}
```

Additionally, when I add columns as a parameter in the percentile function like below
```
|> percentile(columns: ["_value"], percentile: 0.99, method: "estimate_tdigest", compression: 1000)
```
, I get this error: 
```
{"error":"failed to compile query: type error 8:5-8:101: function does not take a parameter \"columns\""}
```

According to the spec, `columns` should be a valid argument. So far the only way, I can get percentile to work is by removing the `columns` and `compression` arguments or by removing `compression` and replacing `columns` with `column`.
```
 |> percentile(percentile: 0.99, method: "estimate_tdigest")
```
```
 |> percentile(column: "_value", percentile: 0.99, method: "estimate_tdigest")
```

**Comment by docmerlin** [comment]
Use 99 not 0.99. 

https://en.wikipedia.org/wiki/Percentile

**Comment by jsternberg** [comment]
I'm labeling this as a bug until someone has time to look at it to confirm it.

**Comment by affo** [comment]
@ischolten for avoiding:

```
{"error":"failed to compile query: type error 8:5-8:80: float != int"}
```

Please enter the compression as a float:

```
from(bucket: "telegraf/autogen")
	|> range(start: -5m)
	|> filter(fn: (r) => r._measurement == "cpu" and r._field == "usage_system")
	|> percentile(percentile: 0.99, method: "estimate_tdigest", compression: 1000.0)
```
