### ISSUE TITLE
Allow literal constants to be polymorphic

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1073]
See for details on numeric types https://github.com/influxdata/flux/issues/476

For other types this is what is expected.

* A duration can be either a time or duration literal, where if it is a time its understood as `now - duration`.

**Comment by R-Studio** [comment]
Any news on this?

**Comment by nathanielc** [comment]
@R-Studio We are currently working on this feature. It requires some fundamental changes to how certain parts of our system interact and so its going to take a while to complete.  See for the parent issue https://github.com/influxdata/flux/issues/3348

**Comment by R-Studio** [comment]
@nathanielc thanks for the reply. Then I will wait for the feature and hope this is soon. 👍
