### ISSUE TITLE
Query doesn't get retried after tryRequeue()

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1074]
When this check fails: https://github.com/influxdata/flux/blob/f2ede3cf3a5d017022b7d928c0b8367be27f9c34/control/controller.go#L415, the controller requeues the query, but it seems that the query never gets popped from the stack and re-executed. So, the client that is iterating over results hangs forever.

**Comment by jsternberg** [comment]
I think the requeue functionality has been removed so I'm going to close this.
