### ISSUE TITLE
SQL and Elastic

### ISSUE THREAD

**Issue by OrangeFlag** [influxdata/flux#1075]
Hello, I want to add Elasticsearch as a source and wrote for this elementary code.
But I faced with problem: I cannot figure out how use `from` in flux to connect to a non-influxDB database. `From` now uses concept of bucket, which is not in others databases.

Correct me if i make mistake in concepts and give me some example of a request Postgres and MySQL from flux, please.

**Comment by pauldix** [comment]
If you want to build a connector to Elasticsearch, you'll have to build a new from function, likely in a new `elastic` namespace. You can see an example of another `from` function for `sql` here: https://github.com/influxdata/flux/tree/master/stdlib/sql

**Comment by OrangeFlag** [comment]
@pauldix Yes, thank you, i do so. Can you give an example of using the `from` function **from a flux** with an sql database (with ip, port, database name)?

**Comment by nathanielc** [comment]
@OrangeFlag The `from` function is in the `sql` namespace. So to use it in Flux it would like like this:
```
import "sql"

sql.from(driverName: "...", dataSourceName:"sql url with database info", query:"SELECT * FROM ...")
   |> // ...
```

**Comment by OrangeFlag** [comment]
@nathanielc Thank you :+1:
