### ISSUE TITLE
The AST generated for logical operations is wrong

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1077]
When parsing `a or b and c`, the parser produces:

![Schermata 2019-03-22 alle 18 26 25](https://user-images.githubusercontent.com/4246582/54842091-35713c00-4cd1-11e9-9631-7f0647119e84.png)

So:

```
            and
            /  \
          or    c
         /  \
        a   b
```

While it should produce:

```
    or
   /  \
 a    and
      /  \
     b    c
```

It is also weird that the SPEC says that `and` and `or` operators have the same precedence. `and` should have higher precedence than `or`.

**Comment by jsternberg** [comment]
We would have to change the spec. The current spec has them at the same precedence which means the parser currently follows the spec.

I'm fine if we decide to change the precedence though. It seems python gives `and` a higher precedence and ruby gives `and/or` the same precedence. Javascript doesn't have the words, but it has a similar precedence to python.

**Comment by affo** [comment]
Mmm 🤔 It seems to me that both Python and Ruby give the same precedence to boolean operators:

Python:

![Schermata 2019-03-25 alle 09 36 29](https://user-images.githubusercontent.com/4246582/54905614-bf8fef00-4ee1-11e9-8f2b-950996b437ff.png)

Ruby:

![Schermata 2019-03-25 alle 09 37 20](https://user-images.githubusercontent.com/4246582/54905619-c454a300-4ee1-11e9-9e0c-2c5e47b2e3f9.png)

Operator precedence in boolean algebra is not defined, but I think that precedence of `and` wrt `or` is a well established convention, so we should follow that.

**Comment by jsternberg** [comment]
I'm not disagreeing with the conclusion, but `and` and `or` have different connotations in programming languages. Ruby has distinct operators for those with different precedence and ours were originally based off of those.

If you notice, the Ruby operators for `&&` and `||` have much higher precedence in the precedence table than `and` and `or` and our precedence rules match this.

Now, I think we should go with the Python precedences and I think it is more common for people to believe what you stated in the top post. I just wanted to give some clarity about the different connotations of the words vs the symbols.

<img width="305" alt="Screen Shot 2019-03-25 at 2 46 08 PM" src="https://user-images.githubusercontent.com/1212129/54949313-c4b66380-4f0c-11e9-86b3-17b720b05052.png">

**Comment by affo** [comment]
Yeah, got your point. Thank you for the clarification 👍

**Comment by nathanielc** [comment]
:+1:  I looked into this a bit, the Ruby versions of `and` and `or` are special operators with intentionally lower precedence so that they can be used for control flow. See http://www.virtuouscode.com/2010/08/02/using-and-and-or-in-ruby/ That is not the intention of Flux's `and` and `or` operators, so we should follow the standard logical operator precedence.
