### ISSUE TITLE
spec: does mean() calculate weighed average?

### ISSUE THREAD

**Issue by andig** [influxdata/flux#1080]
If not that might be a good addition?

**Comment by nathanielc** [comment]
@andig Agreed it would be a good addition, how would you expect to pass in the weights? An example of some potential Flux code would be great to make sure we understand the use case.

**Comment by andig** [comment]
I'm coming from [volkszaehler.org](https://volkszaehler.org) which specializes in collecting and visualizing physical sensor data. We're aiming to support a variety of sensors, measurements and devices. 

Coming from this is the requirement to support non-aequidistant measurements/timestamps where the characteristics of the sensor are known, e.g. the sensor will only create a measurement when the sensor reading actually changes. For this case, the measurement weight is the timespan since last measurement.

Example for a full day measurement:

- 00:00 0% valve
- 01:00 100% valve
- 23:00 0% valve
- 24:00 100% valve

In this case the valve was open 22/24 hours which amounts to average opening of 22/24% >> 50%.

**Comment by russorat** [comment]
see also: https://github.com/influxdata/flux/issues/729

**Comment by nathanielc** [comment]
Closing in favor of issue #729
