### ISSUE TITLE
Bug: Duration parsing fails for negative durations.

### ISSUE THREAD

**Issue by docmerlin** [influxdata/flux#1081]
Duration parsing fails for negative durations.
This errors for  `-1m`.
```
func ParseDuration(lit string) ([]ast.Duration, error) {
	var values []ast.Duration
	for len(lit) > 0 {
		n := 0
		for n < len(lit) {
			ch, size := utf8.DecodeRuneInString(lit[n:])
			if size == 0 {
				panic("invalid rune in duration")
			}

			if !unicode.IsDigit(ch) { 
				break
			}
			n += size
		}

		magnitude, err := strconv.ParseInt(lit[:n], 10, 64)
		if err != nil {
			return nil, err
		}
		lit = lit[n:]

		n = 0
		for n < len(lit) {
			ch, size := utf8.DecodeRuneInString(lit[n:])
			if size == 0 {
				panic("invalid rune in duration")
			}

			if !unicode.IsLetter(ch) {
				break
			}
			n += size
		}
		unit := lit[:n]
		if unit == "µs" {
			unit = "us"
		}
		values = append(values, ast.Duration{
			Magnitude: magnitude,
			Unit:      unit,
		})
		lit = lit[n:]
	}
	return values, nil
}
```

I think the problem is at `if !unicode.IsDigit(ch) { `, it needs to check to allow negative signs.

**Comment by nathanielc** [comment]
@docmerlin The parser only parsers positive duration literals and then treats `-` as a unary operator preceding the duration literal. 

Obviously this doesn't work for your use case. Should we create a wrapper function like `ParseSignedDurationLiteral` that know how to check for a `-` before normal parsing?

**Comment by docmerlin** [comment]
Ah, then the spec needs to be fixed, right now it says it has an integer between units, should it say it is only a positive integer?
