### ISSUE TITLE
Make flux.Spec private

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1085]
This is a parent issue for all the tasks needed to make the flux.Spec and internal detail only.

Other issues will be linked to this issue.

**Comment by wolffcm** [comment]
Related issue to make the planner to provide a builder and convenient interface:
https://github.com/influxdata/flux/issues/1097

**Comment by wolffcm** [comment]
I created this issue to update all clients to use `ASTCompiler` instead of `SpecCompiler`:
https://github.com/influxdata/influxdb/issues/12928

**Comment by wolffcm** [comment]
Issue to deal with dependencies with new `Compiler` interface.
https://github.com/influxdata/flux/issues/1126

**Comment by jsternberg** [comment]
This is effectively private and we'll talk more about what should be done as we begin work on the IR language refactor in the future.
