### ISSUE TITLE
Change flux.Compiler interface to remove Spec

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1086]
The compiler interface should not expose the Spec.

The interface should look like:

```
type Compiler interface {
    Compile(context.Context, Request) (Program,error)
}
```

Where Program is:

```
type Program interface {
    // Starts execution of the program and returns immediately
    // As results are produced they arrive on the channel, the program is finished once the result channel is closed and all results have been consumed.
    Start(context) (<-chan flux.Result, error)
}
```

Previously the results returned from execution where a `map[string]flux.Result` but that is no longer a valid return value since an undetermined number of Results may be produced. A result knows it own name so the map is not needed. 

Also of note is that multiple results can be read off the channel before the results themselves are fully consumed. So while the retrieval of the results is serial the results can still be consumed concurrently. 

This is part of #1085

**Comment by wolffcm** [comment]
@nathanielc Some questions:
- What is `Request`?  The type that immediately comes to mind is in the `influxdb` repo which has an instance of `Compiler` as a member.
- What happens to the `Query` interface as a result of this change? It seems like it can go away entirely in favor of this simpler interface.

**Comment by wolffcm** [comment]
Also, how should query statistics be handled?  They could be implemented as a special meta-table that is guaranteed to be the last thing returned by the channel before it is closed.

**Comment by wolffcm** [comment]
I'm just putting my questions in a comment as the come up.  How should dependencies be handled?

Maybe, `Program.Start()` method should accept an instance of `Executor` as an argument.

**Comment by jsternberg** [comment]
It might be good to have this return the query interface instead of `<-chan flux.Result`. A big problem with returning channels is there's no way to tell the caller to stop without relying on the context that is passed in and you _have_ to read all of the results or you get a goroutine leak.

So I would recommend changing this to:

```
type Program interface {
    // Starts execution of the program and returns immediately
    // As results are produced they arrive on the channel, the program is finished once the result channel is closed and all results have been consumed.
    Start(context) (flux.Results, error)
}
```

And then having `flux.Results` be the same interface as `flux.Query`. Then we would have the `flux.ResultIterator` for synchronously reading from the results and nothing else has to change. The controller would then change to wrapping the query returned by the program with additional query management behavior.

**Comment by jsternberg** [comment]
@nathanielc can you clarify in the initial issue that this includes the plan spec too? I was initially confused when reading this as I thought it only related to `flux.Spec`, but then I realized it must also include `plan.PlanSpec`.

**Comment by nathanielc** [comment]
@wolffcm 

> What is Request? The type that immediately comes to mind is in the influxdb repo which has an instance of Compiler as a member.

That is a mistake on my part, the Request is not part of the interface.


> What happens to the Query interface as a result of this change? It seems like it can go away entirely in favor of this simpler interface.

Possibly, I hadn't thought of it that way but it does seem like it could go away. If so let's remove it, but maybe as a follow up change to keep changes small.

> Also, how should query statistics be handled? They could be implemented as a special meta-table that is guaranteed to be the last thing returned by the channel before it is closed.

I also like this idea, it keeps the stats inband so we don't have to rely on the transport to communicate them.  Should the addition of the statistics be explicitly requested? Again we should make this its own change.

> How should dependencies be handled? Maybe, Program.Start() method should accept an instance of Executor as an argument.

I was thinking of a Program as ready to execute having all its dependencies already. Meaning that a compiler is responsible for creating the Program instance with its dependencies. Sort of like static vs dynamic linking, I do not see a need to link in dependencies at runtime. 


@jsternberg 

> It might be good to have this return the query interface instead of <-chan flux.Result. 

Agreed, using an interface is likely better here, my point in using the channel is that we have an unknown number of results that may be produced, the best way to communicate that is to use a channel in Go. As for leaking a goroutine if the channel is not fully read that will likely happen no matter what the mechanism is for delivering results. Meaning that reading off the channel and reading the results themselves provides backpressure, the queries resources will not be freed until it is fully consumed. 

> can you clarify in the initial issue that this includes the plan spec too? I was initially confused when reading this as I thought it only related to flux.Spec, but then I realized it must also include plan.PlanSpec.

I do not expect anything to change with regard to planning. Planning will occur inside the compiler step but otherwise will remain unchanged.

**Comment by jsternberg** [comment]
@nathanielc I meant as it refers to the exposed interface. Because if we just wanted to remove `flux.Spec` from the public interface, we could have `Compile` return a plan spec instead.

I agree on the use of the channel part. I just think it should be hidden in an interface so it is easier to use and less likely to result in leaking the goroutine (like the `flux.Query` interface is built to do). I think we're on the same page in that regard.

**Comment by nathanielc** [comment]
@jsternberg Returning a PlanSpec instead of a flux.Spec does not solve the issue at hand. The intent is to make the execution opaque to the rest of the system instead of requiring that execution to be marshalled into any kind of spec. The specs we currently have flux.Spec or the plan specs cannot describe the dynamic behavior we are trying to enable. 

In other words the change is specifically about hiding all forms of serializing the execution of program and exposing a way to execute them only.
