### ISSUE TITLE
Support dynamic queries

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1090]
The use case is to be able to use the result of a query in part of another query.

The classic example of this is the top N use case:

```
// Gather the top 10 hosts by mem used_percent over the last day.
hosts = from(bucket:"telegraf/autogen")
    |> range(start: -1d)
    |> filter(fn: (r) => r._measurement == "mem" and r._field == "used_percent")
    |> max()
    |> group()
    |> top(n: 10)
    |> columnSlice(column: "host")

// Select the last 30d of cpu usage for only the top 10 hosts
from(bucket:"telegraf/autogen") 
     |> range(start: -30d)
     |> filter(fn: (r) => r._measurement == "cpu" and r.host in hosts)
```

This depends on #1085

**Comment by jsternberg** [comment]
We have the dependent issue mostly done so I'm going to start workshopping this.

**Comment by nathanielc** [comment]
FYI this issue depends first on #1089 Once those functions are complete then dynamic queries might "just work". This issue it here to track that they do in fact work by adding tests etc.

**Comment by jsternberg** [comment]
Unassigning myself from this temporarily. I'll look at #1089 first when I get back to this.
