### ISSUE TITLE
Query to count occurrences of distinct values

### ISSUE THREAD

**Issue by nanicpc** [influxdata/flux#1113]
Hello I just want to ask if FLUX solves a feature request that was posted to influxdb here:
https://community.influxdata.com/t/query-to-count-occurrences-of-distinct-values/3969

The idea is to be able to count the ocurrences of a field value ( that has not been choose as tag because of its high cardinality)

I was thinking in something like:

```
from(bucket: "db/rp")
  |> range(start)
  |> filter(fn: (r) => r._measurement == "measurement" and (r._field == "field") and r.filter_tag == "filter_tag_value")
  |> keep(columns: ["_value"])
  |> map(fn: (r) => ({new_column: r._value, _value:r._value}))
  |> group(columns: ["new_column"])
  |> count()
```

- The version of Flux you are running.
influxdb 1.7.4

**Comment by sanderson** [comment]
@nanicpc Yes, that query would do it, although I think it could be optimized a bit. You don't need to keep only the `_value` column and the `map()` function can be very resource-intensive (it's been optimized in newer versions of Flux). You would get the same results with the following:

```
from(bucket: "db/rp")
  |> range(start: -1d)
  |> filter(fn: (r) => r._measurement == "measurement" and r._field == "field" and r.filter_tag == "filter_tag_value")
  |> duplicate(column: "_value", as: "new_column")
  |> group(columns: ["new_column"])
  |> count()
```

**Comment by nanicpc** [comment]
thanks a lot, it is undeniably much faster with duplicate. Little additional question: it is possible in flux to concatenate to columns one string and the other numeric into one new string column? 

Ex:

column_1 | column_2 | new_column
------------ | ------------- | -------------
Toto | 658 | Toto_658
tata | 5 | tata_5

**Comment by nanicpc** [comment]
thanks!
