### ISSUE TITLE
promql: Support non-existent column names in keep()

### ISSUE THREAD

**Issue by juliusv** [influxdata/flux#1118]
PromQL binary expressions that do an explicit join on a number of labels restrict the output labels to the explicitly listed set of labels (which is actually a bug in PromQL which has always been there, see https://github.com/prometheus/prometheus/issues/5326).

In Flux I try to emulate this by adding a `keep()` after a `join()`, but `keep()` returns an error when a column to keep does not exist: `keep error: column "non_existent" doesn't exist`. Since I do not know the actually existing columns at PromQL->Flux transpilation time, would it be possible to (optionally?) just ignore non-existent column names in `keep()`?

**Comment by juliusv** [comment]
@nathanielc What do you think about adding an `allowNonexistent` option for both `drop()` and `keep()` that defaults to `true` for `drop()` and `false` for `keep()` to mirror the current behavior by default? Or is there a nicer way for me to achieve what I want?

**Comment by aanthony1243** [comment]
I propose quietly continuing past non-existing columns in both cases.  Here's my thinking: 

1.  They may have a set of potential columns they want to keep, but can't predict which ones will come up at any time (e.g. changing series id tags).   

2.  If they keep something that they REALLY NEED to exist, the error will manifest later.  That is, if they expect to always see that column, one way or another they will find out.   I don't think we need to kill their whole query over it.

**Comment by juliusv** [comment]
That sounds fine to me.

**Comment by nathanielc** [comment]
@aanthony1243 I agree skipping missing columns is fine.

**Comment by wolffcm** [comment]
If you say `keep(columns: ["non_existent_column"])`, do we end up with tables with no columns?  Should that be a runtime error?
