### ISSUE TITLE
Create a "label" type

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1122]
I propose that we add a `label` type to the Flux type system. A label type is a statically known string value. Label types are used to access keys of objects. In order for the type system to be sound and support inference we must statically know all object properties that are accessed statically. 

Using a label type allows for defining polymorphic functions that operate with different labels while still remaining sound.

Many transformations functions accept a `column` argument that defines which column they operate on. This is only possible if the value of `column` is known statically. Using a `label` type explicitly codifies this requirement.

For example:

```
builtin mean : (tables : <-stream, column : label) -> stream
```

The above means that `column` must be known statically, so this is valid:

```
from(bucket:"foo") 
    |> ...
    |> mean(column: "usage_idle")
```

but the following would not be allowed.

```

builtin bar : () -> string

from(bucket:"foo") 
    |> ...
    |> mean(column: bar() )
```

As string is not a label as a string value is not known until runtime.

This is a rough draft a proposal at this point and needs to be worked out before we know if it is possible.

**Comment by aanthony1243** [comment]
if label is a valid type, and can be returned by a function, then we run into the same issue.  

but if you are proposing that labels may only exist as literals, then this could work OK.  If we did this, I would prefer a different syntax for labels, maybe `<label>` ?

**Comment by nathanielc** [comment]
@aanthony1243 Are you suggesting that object keys always have `<>` surrounding them? Like:

```
foo =  {
   <mykey>: "some value",
   <another key>: 42
}
```

Or where do you expect the `<label>` syntax to come up? 


> if label is a valid type, and can be returned by a function, then we run into the same issue.

Label will be a valid type but it is required that its value be known statically. So we can decide how far the ocmpiler looks for static values but it is not unreasonable to inspect the body of a function and see that its value is static.

```
defaultValueColumn = () => "_value"

timeShift(column: defaultValueColumn()) // this could work as its value is known statically

```

I am not saying that we should do it this way but that it is possible.

**Comment by aanthony1243** [comment]
I was thinking something like `mean(column: <usage_idle>)`   I don't know that I really like this idea, but I do think that if they look like strings, and feel like strings, users will treat them like strings.

**Comment by pauldix** [comment]
What's the underlying reason for doing this? Why must the type be known statically? This feels like more syntax and harder for the user. What about the case where a `pivot` is done and string values become column names (like on `_field`)?

**Comment by mcassaniti** [comment]
I'd be conservative in using this. Say I wanted to build the equivalent of a Kapacitor template in my own library for handling alerts with Flux (even though that might be a while away). I'd want to specify a list of labels for the group key along with a measurement to make this possible.

If it's still possible to pass these in to my pre-built function then all good, but the type checking would need to stretch all that way back.
