### ISSUE TITLE
[pvt-spec] Make new Compiler assign dependencies to Programs it generates

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#1126]
On master, currently the controller gets its `execute.Dependencies` assigned from its config object and propagates them down to the `Executor`.

In the new architecture, the `Compiler` produces a `Program` that can be `Start`ed.  The call to `Start` instantiates a new `Executor`, which needs dependencies to know how to access the services that implement `from`, `to`, etc.

**Comment by jsternberg** [comment]
I think this is the same or related to #1140. The compiler design makes it difficult to inject stuff into the chain so, for example, these dependencies are needed when running the AST compiler, but shouldn't need to be passed down from the compilers that use AST compiler. We also need a way to be able to send in options to the compiler.

**Comment by jsternberg** [comment]
We're thinking that this already has a workaround and the proper solution to this can be done later so I'm throwing this back to planned. We are likely not going to do this before merging the private spec changes.
