### ISSUE TITLE
Feature request: ability to build a regex from a string

### ISSUE THREAD

**Issue by chnn** [influxdata/flux#1127]
It would be terrific to be able to create a regular expression from a string—essentially to have [`regexp.Compile`](https://golang.org/pkg/regexp/#Compile) available in Flux.

It would make the “variables” feature in the InfluxDB UI more powerful. We programmatically insert variable assignments into dashboard queries before executing them. The value of the assignment is based on what a user selects from a dropdown in the UI, and the query runs every time a new value is selected. We want to enable writing dashboard queries like this:

```
import "regexp"

data |> filter(fn: (r) => r.region =~ regexp.Compile(v.region + ".*"))
```

which after the substitution has taken place, might look something like this:

```
import "regexp"

option v = {
  region: "us-west-"
}

data |> filter(fn: (r) => r.region =~ regexp.Compile(v.region + ".*"))
```

**Comment by nathanielc** [comment]
@chnn Sounds good. Its a simple request. Do you want to try to add it? If so we can help you through the process. If not we can pick it up next week.
