### ISSUE TITLE
union() doesn't return results

### ISSUE THREAD

**Issue by sanderson** [influxdata/flux#1129]
I’m trying to use the value of the `cpu` tag to set a `cpu_int` on each row:

```
data = from(bucket: "default")
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == "cpu" and r._field == "usage_system")

setCPUInt = (cpuName, cpuInt, tables=<-) =>
  tables
    |> filter(fn: (r) => r.cpu == cpuName)
    |> map(fn: (r) => ({ _time: r._time, _value: r._value, cpu_int: cpuInt }))

cpu0 = data |> setCPUInt(cpuName: "cpu0", cpuInt: 0)
cpu1 = data |> setCPUInt(cpuName: "cpu1", cpuInt: 1)
cpu2 = data |> setCPUInt(cpuName: "cpu2", cpuInt: 2)

union(tables: [cpu0, cpu1, cpu2])
```

If I individually call `cpu0`, `cpu1`, and `cpu2`, they all return results and `cpu_int` is set correctly. However, the `union` of the three doesn't return any results. No errors; just no results. It looks as though `union` isn’t working.

If you have a Telegraf agent collecting CPU stats, you should only need to change the bucket in the query above to replicate the behavior.

**Comment by jlapacik** [comment]
https://github.com/influxdata/flux/pull/2624 should have fixed this too.
