### ISSUE TITLE
Make plan comparison go-cmp friendly

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1130]
We could create a `cmp.Comparer` out of methods in `plan/cmp.go`.
So that one can use `cmp.Equal` to compare plans.

E.g. (only some code I was up with):

```
// CreatePlanComparisonOptions returns a cmp.Option that compares two plan.Specs by consistently walking
// their DAG and comparing every Node ID, Spec, and Kind using the provided opts.
func CreatePlanComparisonOptions(procedureSpecCmpOpts ...cmp.Option) []cmp.Option {
	return []cmp.Option{
		cmp.Comparer(func(want, got *plan.Spec) bool {
			err := ComparePlans(want, got, cmpPlanNode)
			return err == nil
		}),
		cmp.Comparer(func(want, got plan.ProcedureSpec) bool {
			opts := append(semantictest.CmpOptions, procedureSpecCmpOpts...)
			return cmp.Equal(want, got, opts...)
		}),
	}
}
```

**Comment by affo** [comment]
@wolffcm PTAL ( => Please, Take A Look. Thanks @fntlnz for the nearly infinite list of acronyms 😎 )

**Comment by wolffcm** [comment]
This looks very nice.  Can we call the function something more concise like `plantest.CmpOptions`, so I assume it unit tests comparisons could look like this?
```go
want := ...
got := ...
if diff := cmp.Diff(want, got, plantest.CmpOptions()); diff != "" {
   t.Fatalf(...)
}
```
I guess we would want different options depending on if you want to compare logical or physical plans, as well as if you want to do a simple very shallow comparison.

**Comment by affo** [comment]
Yes, that would be great.

Using a `cmp.Comparer` its ok to make `cmp.Equal` fail/succeed.  
To get your nice error messages with `cmp.Diff` we would need a `cmp.Reporter` I think: https://godoc.org/github.com/google/go-cmp/cmp#Reporter.
