### ISSUE TITLE
Intermittent build failures in CI

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#1179]
The build seems to be failing, but only sometimes, since the compiler was upgraded:

https://circleci.com/gh/influxdata/workflows/flux/tree/master

I attempted to fix new errors reported by `staticcheck` and `go vet`, but there are still mysterious build failures when running tests.

At this time the most recent build passed, but the previous one failed `test-race` with only this:
```
...
ok  	github.com/influxdata/flux/stdlib/http	5.265s
FAIL	github.com/influxdata/flux/stdlib/influxdata/influxdb [build failed]
ok  	github.com/influxdata/flux/stdlib/influxdata/influxdb/v1	5.368s
...
```

**Comment by mark-rushakoff** [comment]
> /usr/local/go/pkg/tool/linux_amd64/link: signal: killed

See https://github.com/golang/go/issues/26186#issuecomment-435544512. Last I checked, CircleCI environment reports 36 CPUs available, but then the Docker environment only has 2 available. That makes Go try to do too much in parallel during `go test`.

Assuming you don't want to modify the Makefile, you can edit .circle/config.yml to set the environment variable `GOFLAGS=-p=8` (8 being an arbitrary guess at a value high enough to run and still pass).

**Comment by wolffcm** [comment]
Thanks for this tip, I'll try that.
