### ISSUE TITLE
CI requires particular version of ragel to pass checkgenerate

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#1183]
If you modify `internal/scanner/scanner.rl` and regenerate `scanner.gen.go` your changes may fail in CI if your local version of ragel is different than in CI.

I have ragel 6.10 installed via `brew`.  CI has 6.9, and this causes some small differences in the generated code between local development and CI.

The workaround is to build and install an earlier version, which is not that hard to do, as older versions are here:
http://www.colm.net/files/ragel/

**Comment by nathanielc** [comment]
@wolffcm Is it possible to upgrade CI to use the newer version? Here is the docker file CI uses https://github.com/influxdata/flux/blob/master/Dockerfile_build maybe we just need to specify the newer version there?

**Comment by wolffcm** [comment]
@nathanielc Hmm, unless I'm missing something it seems like ragel 6.9 is the newest version available on the version of Linux in the image (Debian Stretch).

**Comment by nathanielc** [comment]
Lame, maybe we should use a different base image, or add steps to compiler ragel from scratch in the docker image?

The point of the docker image is to document the specific version needed. Since ragel is our only real dependency I am fine switching base image etc to make it easier to work with. 6.10 was release in 2017, so I would expect it to be available in one of the main distros.

**Comment by wolffcm** [comment]
The image `golang:1.12-alpine` seems to have the version of ragel that we want.  I am no longer blocked on this, but I'll give it a shot when I have a moment.

**Comment by wolffcm** [comment]
We can't use an Alpine-based image for the CI docker build, since `go test -race` wouldn't work:
https://github.com/golang/go/issues/14481
I tried, and I hit the same linker errors from that issue.

Since the images in golang's docker hub are all either Debian Stretch-based (ragel too old) or Alpine-based (no `go test -race`), we'll need a different solution:
- Use a different image altogether
- Use the golang Stretch-based image, but download and build a more recent version of Ragel

I'm reaching the limit of my Docker abilities and will set this aside for now.

**Comment by wolffcm** [comment]
We are using Ragel 6.10 in CI now as part of #1455.
