### ISSUE TITLE
Omitting "on" in "join()" causes empty result

### ISSUE THREAD

**Issue by juliusv** [influxdata/flux#1190]
According to @aanthony1243, `join()` should default to matching on all grouping labels if the `on` argument is omitted. I would thus expect a stream joined onto itself to return the same stream. But I get an empty result for the following (had to fetch the identical data twice as otherwise `join()` errored about not having two parents):

```
cpu_usage1 = from(bucket: "prometheus")
       |> range(start: 2019-02-21T16:45:30Z, stop: 2019-02-21T16:51:40Z)
       |> filter(fn: (r) => r._measurement == ("demo_cpu_usage_seconds_total"))
       |> window(every: 10000000000ns, period: 5m)
       |> filter(fn: (r) => ((r._stop) >= (2019-02-21T16:50:30Z) and (r._start) <= (2019-02-21T16:46:40Z)))
       |> last()

cpu_usage2 = from(bucket: "prometheus")
       |> range(start: 2019-02-21T16:45:30Z, stop: 2019-02-21T16:51:40Z)
       |> filter(fn: (r) => r._measurement == ("demo_cpu_usage_seconds_total"))
       |> window(every: 10000000000ns, period: 5m)
       |> filter(fn: (r) => ((r._stop) >= (2019-02-21T16:50:30Z) and (r._start) <= (2019-02-21T16:46:40Z)))
       |> last()

join(tables: { lhs:cpu_usage1, rhs:cpu_usage2 })
```

But if I evaluate either of (identical) the input expressions, I get data (see attached CSV). Also attached is the data that's in my test InfluxDB in line protocol format.

Am I doing something wrong or is this a bug? I'm built InfluxDB from current master, but also pointing `go.mod` at the current master of Flux, to make sure I have the newest of everything.

[influx-data.txt.gz](https://github.com/influxdata/flux/files/3099902/influx-data.txt.gz)
[chronograf_data.csv.gz](https://github.com/influxdata/flux/files/3099899/chronograf_data.csv.gz)

**Comment by nathanielc** [comment]
The `on` parameter is now required. We will explore a new join behavior to join on the group columns instead of a default behavior of the `on` parameter.
