### ISSUE TITLE
map doesn't work with null values

### ISSUE THREAD

**Issue by andig** [influxdata/flux#1195]
Cannot run this query on Chronograf 1.7.10:

    import "math"
    from(bucket: "volkszaehler")
    |> range(start: dashboardTime)
    |> filter(fn: (r) => r._measurement == "data" and r.title == "HcStarts" and r._field == "value")
    |> aggregateWindow(every: 1d, fn: mean)
    |> difference(nonNegative: false, columns: ["_value"])
    //    |> fill(usePrevious: true)
    |> map(fn: (r) => (r._value), mergeKey: true)

    Error: failed to evaluate map function: null reference used in row function: skipping evaluation until null support is provided
  
Adding the `fill` which should take care of the null values also doesn't fix the problem.

**Comment by andig** [comment]
Could you explain why fill didn‘t help here? I‘m a little lost what those nulls are.

**Comment by aanthony1243** [comment]
if you fill with use previous, and the first element is null, you will still have nulls, until you find at least one non-null row.  probably the solution here is `fill(usePrevious:true) |> fill(value: 0)`  to fill in the nulls that remain.  

in the latest version of flux, you could also filter nulls with `filter(fn: (r) => exists r._value)`
