### ISSUE TITLE
map gives empty result set and swallows error

### ISSUE THREAD

**Issue by andig** [influxdata/flux#1196]
Running this on Chronograf 1.7.10:

from(bucket: "volkszaehler")
  |> range(start: dashboardTime)
  |> filter(fn: (r) => r._measurement == "data" and r.title == "HcStarts" and r._field == "value")
  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)
  |> difference(nonNegative: false, columns: ["_value"])
  |> map(fn: (r) => (r._value * r._value))

Query runs fine without the final `map`. Once the last line is added the result set is empty, no error message. Apparently something went wrong and the error is silently swallowed.

**Comment by jsternberg** [comment]
The behavior for an implicit `_value` column from map is being removed and it will now return an error: #1037.
