### ISSUE TITLE
histogram does not take buckets parameter

### ISSUE THREAD

**Issue by andig** [influxdata/flux#1197]
Chronograf 1.7.10 gives the following when adding the function to a query:

    |> histogram(column: "_value", upperBoundColumn: "le", countColumn: "_value", buckets: [50.0, 75.0, 90.0], normalize: false)

`buckets` must be `bins` as `buckets` is not a valid parameter.

It would be great if the online help were generated from the bundled flux library and not separately maintained. 

A similar issue exists with `aggregateWindow` which is missing documentation for `createEmpty`.

**Comment by nathanielc** [comment]
Agreed, see #52

**Comment by andig** [comment]
So- is it still worth reporting these or should I rather not as there‘s gonna be a catch all solution?

**Comment by russorat** [comment]
closing in favor of #52
