### ISSUE TITLE
Add function parameter passing shorthand?

### ISSUE THREAD

**Issue by pauldix** [influxdata/flux#12]
At the risk of opening up another stupid idea like influxdata/platform#702, here's another potential modification to function calling syntax. I got inspiration from [Rust's field init shorthand when variables and fields have the same name](https://doc.rust-lang.org/book/2018-edition/ch05-01-defining-structs.html#using-the-field-init-shorthand-when-variables-and-fields-have-the-same-name) and the [implicit keys object literal](https://github.com/influxdata/platform/issues/212) we're adding to the language.

Say we have a function like this:

```
fromStart = (bucket, start) => {
    from(bucket: bucket) |> range(start: start)
}
```

We end up getting stutter on the variables getting passed to the function. We'd have a similar situation when we're doing

```
bucket = "foo"

from(bucket: bucket) // ...
```

So the idea is that we give a shortcut in the case where the variable name is the same as the function parameter name. If the two are the same you can call it without.

```
bucket = "foo"
start = -24h

from(bucket)
  |> range(start)

// or if you're calling with an implicit and some explicit
from(bucket)
  |> range(start, end:-20h)
```

It reduces the stutter while still keeping the readability for a user looking at the code. Also, we're still enforcing named parameters.

Thoughts?

**Comment by nathanielc** [comment]
My initial thought is that the stutter doesn't seem like that big of an issue to add a special syntax. As such I'd like to default to not making this change. And then when we start seeing Flux code in the community we could reconsider adding it. In other words I am open to the syntax as it does read well but I am not convinced yet that its a problem that needs solving.

**Comment by aanthony1243** [comment]
I think this can be added to the language without creating any inconsistency or confusion.  Personally speaking, I find the stutter irritating when it comes up, which for basic queries is fairly often. 

my gut feeling is that I like it and I would use it frequently if it was available.   it's particularly helpful with 'helper' functions that may have 1 or more args that are merely 'passed through' to the internal function(s).

**Comment by nathanielc** [comment]
This has been added.
