### ISSUE TITLE
Track Allocations in TableBuilder

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1203]
The table builder needs to track allocations of the table as it is being built. We need to also add tests that ensure table allocations are tracked.

**Comment by jsternberg** [comment]
I am definitely wrong about this.

https://github.com/influxdata/flux/blob/56938315776b4747122880d2d261e10a6442bacb/execute/table.go#L1517
https://github.com/influxdata/flux/blob/56938315776b4747122880d2d261e10a6442bacb/execute/table.go#L705

I'm going to close this issue. We'll open a new one for investigating the allocations.
