### ISSUE TITLE
InfluxDB 2.0: range specified as an epoch time doesn't work [flux]

### ISSUE THREAD

**Issue by bednar** [influxdata/flux#1205]
When I trying get data by:

```
from(bucket: "my-bucket")
  |> range(start: 0)
  |> last()
```

the result is without records. But If i trying get data by:

```
from(bucket: "my-bucket")
  |> range(start: 1970-01-01T00:00:00.000000001Z)
  |> last()
```

the result contains records.

Is the syntax with an epoch time still supported?

**Comment by sanderson** [comment]
@bednar Currently, Flux only supports RFC3339 timestamps ([noted in the docs](https://v2.docs.influxdata.com/v2.0/reference/flux/language/types/#time-types)), but other formats may be supported in the future.

**Comment by bednar** [comment]
ok, thx @sanderson

**Comment by geoff-nunan** [comment]
Is it possible to define a custom flux function that converts epoch to RFC3339?
This issue is a problem because Grafana uses epoch for it's built-in time variables that can be passed into the flux query.

**Comment by sanderson** [comment]
@bednar @geoff-nunan You should now be able to do this using the `time()` function. It will convert an epoch nanosecond timestamp into an RFC3339 timestamp. It must be a nanosecond precision timestamp however.

```js
from(bucket: "example-bucket")
  |> range(start: time(v: 1566479392378544000))
  ...
```
