### ISSUE TITLE
Aggregate functions not returning results

### ISSUE THREAD

**Issue by sanderson** [influxdata/flux#122]
I've used the following query to test aggregate functions, but none of the aggregate functions have returned results:

```
from(bucket: "telegraf/autogen")
  |> range(start: -5m)
  |> filter(fn: (r) => r._measurement == "cpu")
  |> window(every: 1m)
  |> mean()
```

I get results all the way down to the `window()` function, but once I add an aggregate function, I no longer get results.

**Comment by nathanielc** [comment]
This is no longer an issue.
