### ISSUE TITLE
tag value missing in `to` function

### ISSUE THREAD

**Issue by lyondhill** [influxdata/flux#1238]
When running a down sampling task against a telegraf populated bucket
```

from(bucket: "default")
|> range(start: -5m)
|> filter(fn: (r) =>
       (r._measurement == "mem" or r._measurement == "cpu" or r._measurement == "diskio" or r._measurement == "net" or r._measurement == "processes" or r._measurement == "swap"))
|> aggregateWindow(every: 5m, fn: mean)
|> to(bucket: "default - 5m mean", org: "thall-org", timeColumn: "_stop")
```

The tag key "cpu-total" in the "cpu" tag column is is visible in the results of the to  function but missing when querying the "default - 5m mean"

**Comment by lyondhill** [comment]
found by @timhallinflux

**Comment by timhallinflux** [comment]
yeah, this is pretty consistent.  The disk usage has the same issue. 

```
from(bucket: v.bucket)
  |> range(start: v.timeRangeStart)
  |> filter(fn: (r) => r._measurement == "disk")
  |> filter(fn: (r) => r._field == "used_percent")
  |> window(period: v.windowPeriod)
  |> mean()
  |> group(columns: ["_value", "_time", "_start", "_stop"], mode: "except")
  |> yield(name: "mean")
```
switching between the raw bucket and the 5m mean bucket using the downsample task above yields:

Raw w/ tags
![Screen Shot 2019-05-06 at 5 16 50 PM](https://user-images.githubusercontent.com/23535264/57262868-e5e99400-7022-11e9-9560-961aede75143.png)

Downsampled...no tags
![Screen Shot 2019-05-06 at 5 17 06 PM](https://user-images.githubusercontent.com/23535264/57262872-ec780b80-7022-11e9-9c87-7fad4f427ce5.png)

**Comment by aanthony1243** [comment]
the `to` function is not acting properly when the schema changes between tables.  This will require a code change.  

as a temporary workaround, the filter should be restricted so that you only have tables with the same columns and group key.  This means it will take N queries to write the N measurements.  You can put all of the queries in a single request.
