### ISSUE TITLE
missing _time column after map

### ISSUE THREAD

**Issue by lyondhill** [influxdata/flux#1240]
When querying telegraf 'system' populated bucket.

```
from(bucket: "default")
        	|> range(start: -15m)
        	|> filter(fn: (r) =>
                    	(r._measurement == "system"))
        	|> filter(fn: (r) =>
                    	(r._field == "uptime"))
        	|> window(period: 15m)
        	|> last()
        	|> group(columns: ["_value", "_time", "_start", "_stop"], mode: "except")
        	|> map(fn: (r) =>
                    	(float(v: r._value) / 86400.0), mergeKey: true)
```
Map removes the time column.
found by @timhallinflux

**Comment by sanderson** [comment]
@timhallinflux Related to https://github.com/influxdata/flux/issues/205. Essentially, `map()` drops any columns that 1) Are not part of the group key or 2) Are not explicitly mapped in the map function.

**Comment by lyondhill** [comment]
@sanderson in this case the group key should have the time column because the `group(columns["_value", "_time", "_start", "_stop"], mode: "except")` right?

**Comment by sanderson** [comment]
No, the `mode` on `group()` is `except` so it’s excluding those columns from the group keys.

**Comment by lyondhill** [comment]
OO interesting. I learned something new!
