### ISSUE TITLE
aggregateWindow (or mean) doesn't handle string values.

### ISSUE THREAD

**Issue by lyondhill** [influxdata/flux#1241]
Some default behavior on how we handle string values may be useful. I understand the "mean"  of a string is a bit of a problem. but if I happen to have one column with a string value in a large aggregate query I don't think the query should fail because of a single column.

If I wanted to downsample all the data from telegraf in a system bucket we assumed we could do this:
```
from(bucket: "default")
	|> range(start: -5m)
     |> aggregateWindow(every: 5m, fn: mean)
```
found by @timhallinflux

**Comment by nathanielc** [comment]
This can be handled via explicit error handling. Current Flux only has the ability to kill an entire query or ignore errors completely, there is not intermediate behavior available. Once we have more flexible error handling these kinds of cases can be handled that way.
