### ISSUE TITLE
Add support for static or dynamic linking of libraries

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1250]
What if somebody wants to import a Flux library in its own script that an InfluxDB installation doesn't know of?

We should support linking of libraries so that one can execute a script that `import`s an external library.

We could simply doing this by letting users send multiple files when `influx query @script.flux`, or supporting FARs (Flux ARchive) --- this would require providing tools to create FARs.

**Comment by docmerlin** [comment]
Currently the query spec supports sending Externs which act as separate files, but there has to be a better option.

**Comment by affo** [comment]
@docmerlin Definitely right.

There should be a better option and better support for it. I think that you cannot use the CLI to specify multiple files. If you did that once, can you paste a snippet?
