### ISSUE TITLE
Using to function with remote influxdb instance fails

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#1259]
I was trying to write my OSS metrics into my cloud instance. When entering in the remote bucket, org, url, and token into the To function, i am unable to write data. My suspicion is that the query needs to use the token in the to function instead of the token that is used to run the query. 

I used an actual token generated from the cloud instance, not the word `TOKEN`.

```
from(bucket: "telegraf")
  |> range(start: -15m, stop: now())
  |> to(bucket: "oss_metrics", 
        org: "russ+cloud2's organization", 
        host: "https://us-west-2-1.aws.cloud2.influxdata.com", 
        token: "TOKEN")
```

![image](https://user-images.githubusercontent.com/4805997/57407441-0b4bde80-7198-11e9-9e8e-aab199a69bfa.png)

**Comment by nathanielc** [comment]
This was never implemented, only the parameters were added. 

As a first fix we should error if the parameters are used. We can implement the real feature later.
