### ISSUE TITLE
refactor `to` to be a fully remote operation

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#1268]
Currently, the `to` function for influxdb must be compiled into the influxdb storage engine in order for it to work.  `flux` should work independently of influxdb for reads and writes.  This issue involves decoupling the write path from the engine by implementing an API interface between flux and influxdb.  

Currently, there is a `/write` API on the HTTP service that we could utilize for writing points back.  There is also a `go` client for influxdb2.0 under development that we may make use of.  Finally, it may be more efficient and stable to open a direct channel with storage over which we could send a more compact representation of data, perhaps in arrow arrays.

**Comment by affo** [comment]
@aanthony1243 Do you also propose to re-implement a `from` using the go client (or else)?

**Comment by aanthony1243** [comment]
@affo in a perfect world, absolutely.  flux should see influxdb no differently from any other db.

**Comment by affo** [comment]
Agreed, I like that.

**Comment by russorat** [comment]
this functionality will be needed in order for OSS to send metrics to remote instances.

**Comment by jsternberg** [comment]
This is done. `to()` has a default http provider that allows remote operation and also allows the embedding environment to inject a different provider for local writes.
