### ISSUE TITLE
Schema Heterogeneity and its Consequences

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#1285]
In considering a variety of filter/transformation cases lately, I decided that we needed to enumerate the ways that a schema can change, and address them appropriately in our tests and implementations.  

The "unified  schema fallacy" is one where a designer assumes that the schema observed on the first table from a stream will not change for the duration of the stream.  That is, they make a wrong assumption that every table on a stream must have the same column labels, column types, and group key column sets.  

Also helpful in this discussion is the idea of a "group key data independence criteria".  This is the condition that a group key uniquely identifies a table and its contents such that this table may be processed independently of any other table.  Secondary to this criteria is that the emission of rows from one table must never depend on the group key columns or values from another table.  

Below, I outline 6 ways that the unified schema fallacy may occur, and discuss errors that may arise because of them: 

1.  The group key column set changes:  If the transformation assumes that the group key column set may never change, the following errors may occur: 
  - any "stateful" calculations based on the initially observed key may be inaccurate if a later table has key that is a super-set of the initial set.  
  - any "stateful" calculations that depend on group key values may be inaccurate or even result in an unrecoverable error if a later table lacks the same key columns.  
  -  A later table may possess the same columns, but not as part of the group key (so assuming the whole column has the same value will be wrong)

2.  Group key value changes:  This is a common occurrence, and not really a schema issue.  Most of our transformations expect this in any case with > 1 table.  

3.  Group key column type changes:  On the surface, this will appear to the engineer to be a value change.  However, column type collisions (panics!!!) will occur if both incoming tables are writing to the same output table.  

4.  Missing non-key column: If 2 incoming tables map to the same output table, this schema difference must be accounted for.  Either an error must be thrown or the missing column must be nil-extended by the length of the new (narrower) table.  

5.  Extra non-key column:  similar to 4 but more problematic.  In this case, if two incoming tables map to the same output table, it may be necessary to dynamically widen the table and back-fill it with nil values so that the columnar data table is properly aligned.  

6.  Non-key column type changes:  A column may have the same name but a different type.  This typically leads to a type conversion panic under a variety of conditions.  

What are some ways that these problems manifest?  First, even though I frame this problem as "the user looks at the first table then makes assumptions"  it may also be the case that "the user had prior assumptions about the data schema and was wrong".  For example: 

1.  #975 where a join will fail because of 1,3,4,5, and 6.  
2.  Filter assumes that any record referenced in the filter function must exist on all tables.  This will incorrectly error whenever  4 is a problem.  It will also type-error (though possibly correctly) if 6 occurs.  In general, filter is robust to 1,2,3 and 5.

**Comment by nathanielc** [comment]
@aanthony1243 Thanks! This is a great write up. The way this manifests on the user side is that they test their script using a subset of the data. Users tend to build there scripts incrementally, adding a new transformation once they are confident the previous ones are working. It is a frustrating user experience to find that you made a mistake at the beginning of a Flux query once you finish and run all the data through the query. 

I know @mark-rushakoff has expressed this a few times. 

Seems like we need an explicit way to manage this? Maybe make it easier to run all tables through a query while still limiting the data set size. As well as visibility into and clearly defined errors/behaviors when any of the above conditions occur.
