### ISSUE TITLE
Custom functions/source libraries

### ISSUE THREAD

**Issue by OrangeFlag** [influxdata/flux#1290]
It would be great, if the user could add a custom source and functions in flux.
Can you add this feature via [go plugin](https://golang.org/pkg/plugin/) or something like that?

**Comment by nathanielc** [comment]
@OrangeFlag That is an interesting idea. I saw you closed your PR for Elastic source https://github.com/influxdata/flux/pull/1165. I apologize for not getting to that sooner. Is that something you still want to contribute? Or did you close it for another reason?

**Comment by OrangeFlag** [comment]
> Is that something you still want to contribute?

@nathanielc I still want to contribute elastic source. And if you give me a couple of tips, I will continue to work.
For example, is it worth getting rid of [external dependencies](https://github.com/olivere/elastic/)?
Elastic has many types of queries, I implemented only [simple queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html). Will this be enough?
What else, besides tests, should be to merge PR in a master?

**Comment by nathanielc** [comment]
@OrangeFlag Glad to hear it. I am traveling next week so I won't be able to take a look for a while yet, but yes we will help out with tips/pointers where we can.

For now using the Elastic client is fine as well as supporting only simple queries. 

Do you want to reopen that PR?

**Comment by philomory** [comment]
I'd still love to see a feature like this. Even if it only worked for pure flux code and didn't support the use of custom Go code at all, just being able to define some custom flux code in one place and then re-use it via `import` rather than having to inline it into every query you write, would be an _enormous_ quality-of-life improvement.
