### ISSUE TITLE
Fix tableFind inlining in rowFn

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1307]
This is ok:

```
users = from(bucket: "b")
    |> range(start: 0)
    |> tableFind(fn: (key) => key._measurement == "cpu")
    |> getColumn(column: "user")

from(bucket: "c")
    |> range(start: 0)
    |> filter(fn: (r) => contains(value: r.user, set: users))
```

This is not:

```
from(bucket: "c")
    |> range(start: 0)
    |> filter(fn: (r) => {
        users = from(bucket: "b")
            |> range(start: 0)
            |> tableFind(fn: (key) => key._measurement == "cpu")
            |> getColumn(column: "user")
        return contains(value: r.user, set: users))
    }
```

This is obviously a performance nightmare, but it should behave as the first script.  
However, it wouldn't, because the `rowFn` evaluates its body without knowing dependencies.

**Comment by affo** [comment]
After some discussion, we should prevent users to make queries inside of lambdas (forbid `|>`), because most of the time that's not what they want. And we don't want to run 1000 queries in a query.

FYI @aanthony1243

**Comment by wolffcm** [comment]
It would be awesome if at some point we could fix this automatically, by moving the inner query out, kind of like how compilers perform loop-invariant code motion.

**Comment by affo** [comment]
@wolffcm yeah, that's pretty cool!

But, how do deal with time? 🤔 

```
...
 |> range(start: -1s)
...
```

If inlined, every query would run with a different start, otherwise not 🤔 
Maybe I am only overthinking 😅

**Comment by wolffcm** [comment]
Hmm, I'm not sure that we've discussed the semantics of time and Flux execution.  It seems to me that we could simplify things a lot if:
- The execution engine stores the value of `now` a the beginning of a query request
- That value of `now` is returned for each call to `now()` in the Flux code (including the implicit ones, like in `range(start: -1s)`.

It seems like this is really what the user wants, especially in the case of dynamic queries, where  queries should be performed over the exact same time range, not similar time ranges with some unknown delta that is the performance of the first query.

This allows for much more deterministic execution, and allows us to perform more aggressive optimizations as well.

**Comment by affo** [comment]
@wolffcm I think you are definitely right. Agreed 😎
