### ISSUE TITLE
Inconsistent return value for static interval

### ISSUE THREAD

**Issue by ischolten** [influxdata/flux#1322]
I am writing a flux query that has a range of one hour in the past (so no new data is getting added to it). I am doing a sum so it returns a single value. However when running this query, it sometimes returns a different value.

Query: 
```
from(bucket: "system_usage")
 |> range(start: 2019-06-03T12:00:00.182Z, stop: 2019-06-03T13:00:00.182Z)
 |> filter(fn: (r) =>
   r.org_id != ""
   and r.org_id == "03dcb44b578f0000"
   and r._measurement == "http_request"
   and r._field == "req_bytes"
   and r.endpoint == "/api/v2/write"
 )
 |> group()
 |> sum()
 |> rename(columns: {_value: "writes_b"})
```

The two responses I keep getting are 
```
#group,false,false,true,true,false
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,long
#default,_result,,,,
,result,table,_start,_stop,writes_b
,,0,2019-06-03T12:00:00.182Z,2019-06-03T13:00:00.182Z,172866
```
and 
```
#group,false,false,true,true,false
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,long
#default,_result,,,,
,result,table,_start,_stop,writes_b
,,0,2019-06-03T12:00:00.182Z,2019-06-03T13:00:00.182Z,185025
```

**Comment by OfTheDelmer** [comment]
Note sometimes this is also returning no results

**Comment by affo** [comment]
I retired your query and I am consistently getting no result 😅 . Can you double check?

**Comment by ischolten** [comment]
@affo Were you running that in acceptance? I'm still seeing this happen in acceptance.

**Comment by affo** [comment]
I was able to reproduce this bug now.

**Comment by jsternberg** [comment]
This does not seem to be reproducible anymore. We are not sure what fixed it. If we removed `r.org_id != ""` we got consistent results. If we included that, we got no results. That's probably a bug, but it was likely needed because of a lack of null support which has now been implemented.
