### ISSUE TITLE
Update filter to only return records that evaluate to true

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#1329]
The SPEC states that filter only returns records for which the predicate evaluates to `true`.

https://github.com/influxdata/flux/blob/15e15bd756e290d797de67afd90e44769db52404/docs/SPEC.md#L1995

Filter must be updated to understand _null_ values. Specifically it must not produce records when its predicate function returns _null_.

**Comment by jsternberg** [comment]
It appears like there are few if not tests for the compiled function. I think we're merging this with the normal query execution at some point, but I'm going to add tests to it in the interim to ensure I don't break anything since I am going to be making changes to it.

**Comment by jsternberg** [comment]
@jlapacik I think this issue needs to be split further. There's the parts of the `compiler` package that have to become compatible with null and there's also the values package needs to be updated to have the null type. Can you create the issue and I'll throw this one back in the planned column and start working on updating `values`?

**Comment by jsternberg** [comment]
We decided the easiest solution was to kill the `EvalXXX` functions at least temporarily. The current implementations are constantly using `values.Value` internally anyway so any benefit likely wouldn't exist anyway and then we'll benchmark in the future and bring the typed values back probably. But for the current iteration, they are causing problems and not really bringing any benefit.
