### ISSUE TITLE
generate.flux should accept relative dates as start and stop

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#1334]
this works:
`generate.from(start: 2019-06-04, stop: 2019-06-05, count: points, fn: (n) => n) |> yield(name: "count")`

but i would like to use:
`generate.from(start: now() - 1h, stop: now(), count: points, fn: (n) => n) |> yield(name: "count")`

Which gives the error:
`error in evaluating AST while starting program: type error 6:22-6:32: time != duration`

**Comment by aanthony1243** [comment]
`now() - 1h` should probably be a valid expression, and would be solved by  #1073

But it's also not needed.  `-1h`  has the same effect and is currently valid: 

`generate.from(start: -1h, stop: now(), count: 100, fn: (n) => n) |> yield(name: "count")`
