### ISSUE TITLE
flux strings package Assessment

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#1343]
we've already done some work implementing Go's functions.  This issue is to track discussion about whether this is the best way to do it or if we should have additional functionality.

**Comment by ewendai** [comment]
Ruby String Library Doc: https://ruby-doc.org/core-2.3.0/String.html

Ruby String Methods that Flux does not have and seems useful to have something similar: 
#=~ : Regex string matching – make count take in regex patterns? 
#[] : Substring/slicing strings
#[]= : String mutation
#casecmp : Case-insensitive version of `compare`
#chars : Returns an array of characters in str – might be helpful in making substring
#eql? : Looks convenient to have: easily implemented using `equal = (v, t) => compare(v, t) == 0`
#gsub : String substitution via regex
#insert : Insert string at desired index: can be implemented via `replace`? 
#match : Given Regex pattern of the given string return the match (optional: and can specify the position in the string to begin the search)
#partition : Having split taking in regex as sep might be useful. Also consider splitting on regex.
#reverse : Reverse string order. Interesting. Unsure if useful? 
#squeeze : Gets rid of repeated characters (`shoot` => `shot`). Looks somewhat dangerous if not used carefully but might be useful?

**Comment by aanthony1243** [comment]
this is great!  we do have regex support in `filter` using `=~`

string slicing is nice, but outside the scope of the strings package.    

the other regex parts---I like these a lot, but we should consider putting them in an all-new `regex` package.

**Comment by ewendai** [comment]
Some top languages/software that people use in data analysis include Python, RapidMiner, and R, according to the [2019 Software Poll](https://www.kdnuggets.com/2019/05/poll-top-data-science-machine-learning-platforms.html) by KDNuggets. 

Specifically with regards to data manipulation and data cleaning, KDNuggets had a [poll](https://www.kdnuggets.com/polls/2008/tools-languages-used-data-cleaning.htm) from 2008, which ranked SQL as the top choice; however, this ranking may be outdated. 

The overall consensus of popular tools for data cleaning seems to be that Python and R are the best. Many of the reasons are reflected in this [post](https://www.quora.com/What-are-the-best-languages-and-libraries-for-cleaning-data) and this [article](https://www.newgenapps.com/blog/6-reasons-why-choose-r-programming-for-data-science-projects). As a summary, Python is appreciated for the ease of use and multitude of libraries (numpy, pandas, scipy, etc.). R similarly has popular packages (dyplr, data.table, etc.).

**Comment by ewendai** [comment]
OpenRefine (previously known as Google Refine) 

OpenRefine [String Documentation](https://github.com/OpenRefine/OpenRefine/wiki/GREL-String-Functions)

Many of the functions that seem useful have also been mentioned above in the "Ruby String Library" comment

The following functions are worth considering:

splitByLengths(string s, number n1, number n2, ...)
Returns the array of strings obtained by splitting s into substrings with the given lengths. For example, `splitByLengths("internationalization", 5, 6, 3)` returns an array of 3 strings: `inter`, `nation`, and `ali`.



-

**Comment by ewendai** [comment]
**String Ideas from SQL**

Given an array of strings, return the array with no repeats? (similar to Java's set)
Can have a `difference` function that returns the array of indices where the strings are different OR return the edit distance. Might be useful if someone is trying to see which values are actually the same, just entered differently

Source: https://www.sqlshack.com/sql-string-functions-for-data-munging-wrangling/

SideNote: Was there any toString method?

**Comment by aanthony1243** [comment]
I really like the R cheat sheet above.  I think we should spend some time writing up integration tests that demonstrates we can do all of the things on that sheet. (at least the first page, maybe not the regex page).  

similarly for the pandas  series string handling:  can we demo the same capability in flux?  

also really like `splitByLengths`  let's make an issue to develop that one!

**Comment by aanthony1243** [comment]
definition of done:  let's write integration tests to cover as many of the cases as we can as  outlined in 

https://github.com/rstudio/cheatsheets/blob/master/strings.pdf

for cases we can't cover:  write new issues on github and reference this one.

**Comment by aanthony1243** [comment]
definition of done:  let's write integration tests to cover as many of the cases as we can as  outlined in 

https://github.com/rstudio/cheatsheets/blob/master/strings.pdf

for cases we can't cover:  write new issues on github and reference this one.

**Comment by aanthony1243** [comment]
definition of done:  let's write integration tests to cover as many of the cases as we can as  outlined in 

https://github.com/rstudio/cheatsheets/blob/master/strings.pdf

for cases we can't cover:  write new issues on github and reference this one.

**Comment by aanthony1243** [comment]
definition of done:  let's write integration tests to cover as many of the cases as we can as  outlined in 

https://github.com/rstudio/cheatsheets/blob/master/strings.pdf

for cases we can't cover:  write new issues on github and reference this one.

**Comment by aanthony1243** [comment]
definition of done:  let's write integration tests to cover as many of the cases as we can as  outlined in 

https://github.com/rstudio/cheatsheets/blob/master/strings.pdf

for cases we can't cover:  write new issues on github and reference this one.

**Comment by aanthony1243** [comment]
definition of done:  let's write integration tests to cover as many of the cases as we can as  outlined in 

https://github.com/rstudio/cheatsheets/blob/master/strings.pdf

for cases we can't cover:  write new issues on github and reference this one.

**Comment by aanthony1243** [comment]
definition of done:  let's write integration tests to cover as many of the cases as we can as  outlined in

https://github.com/rstudio/cheatsheets/blob/master/strings.pdf

for cases we can't cover:  write new issues on github and reference this one.
