### ISSUE TITLE
Clarify the order of types in the regex operators

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#1344]
The regex operator needs to be clarified that only one order works.

```
f = (v) => /^(c|g)pu)$/ =~ v
f = (v) => v =~ /^(c|g)pu$/
```

The second is the one that works and the first is an error. Ensure this is documented in the spec and potentially fix the error message to be more specific about this.

**Comment by nathanielc** [comment]
Additionally the code here supports both https://github.com/influxdata/flux/blob/master/values/binary.go#L492 which is miss leading if we do not intent to support it. That code should be updated to only support the `string op regex` syntax.
