### ISSUE TITLE
Make Rust AST produce correct JSON serialization

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1350]
Implement `serde::ser::Serialize` for all AST struct in the Rust parser. 

The JSON must match the JSON produced by the Go struct/swagger spec.

**Comment by nathanielc** [comment]
See  https://github.com/influxdata/flux/issues/1352#issuecomment-500465674 
For Rust setup details.

**Comment by affo** [comment]
@nathanielc how should we behave for `BaseNode`? In rust, it only contains errors. We can do 3 things:

1. always skip it;
2. skip it only when `errors` is empty;
3. always serialize it (even with empty errors);

Looking at our Go codebase, it seems to me that we don't even test serde for `BaseNode`, so I guess that the first option could be the way to go.

**Comment by affo** [comment]
Closed via #1362
