### ISSUE TITLE
Prioritize adding holt_winters as a flux function

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/flux#1365]
It would be great if the holt_winters() transformation could be added to flux. Thank you!!
https://github.com/influxdata/flux/tree/feat/holt-winters

**Comment by nathanielc** [comment]
See http://docs.influxdata.com/influxdb/v1.7/query_language/functions/#holt-winters for how holt winters should behave from a users perspective.

In short holt winter will take a table of data, use that table to predict future data and then output a table containing that future data.


Holt Winters has two parts:

1. The prediction method
2. The optimizer

Holt Winters is really just a prediction method, it is an iterative method, meaning that given a starting value and some parameters  the next value can be predicted. This is applied in a loop predicting as many values as desired using the previously predicted value as the new starting value.

Choosing correct parameters for the prediction is the key. This is the second part, the optimizer does a best fit of the holt winter parameters to the incoming data. It uses the nelder mead optimizer minimizing the sum squared errors (SSE) of predicted values. As a result the optimizer makes use of the prediction method, after all how could it minimize the errors of the predicted values if it doesn't have them?

So the entire transformation does this for each table

1. Pick some parameters
2. Predict as many values as we have input data starting with the first row
3. Compute the error of predicted values compared with the real input data
4. If the error is small enough go to step 7
5. Adjust the parameters according to the error and the nelder mead method
6. Go back to step 2.
7. Predict  as many future values as requested and place them in an output table.
