### ISSUE TITLE
Problem in building wasm for MacOS

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1376]
I encountered problems in building `wasm` from Rust in MacOS.

I can pair discuss the details so to fix that.

**Comment by wolffcm** [comment]
I've had success in building WASM on OS X from both LLVM IR and C source code using emcc from the emsdk:
https://github.com/emscripten-core/emsdk

**Comment by nathanielc** [comment]
This was fixed by using a Docker container for builds
