### ISSUE TITLE
Update type inference for generic support for "with"

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1378]
First create tests cases for `with` in generic objects. There are a few test cases we can 'unskip' to test this logic.

The `with` keyword is only working in the context of row functions currently.

**Comment by aanthony1243** [comment]
start by unskipping these:   https://github.com/influxdata/flux/pull/1303/files#diff-09eb5b98c6cfaee7b9ac6c9a1cdfccfcR1278

**Comment by affo** [comment]
Fixing the issue seem further from trivial. I am passing control to @jlapacik 

Yesterday we had a good  debugging session and we isolated two problems:
 - when the solver constrains new free variable is only checks the left part of existing constraints and not the right one;
 - when kinds get unified, the order matters. In `{j with a: 1}`, `j` must be unified before the outer expression. This is not so in the current implementation.
