### ISSUE TITLE
changelog generator missed on a commit header that should have been ok

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#1391]
got this message: 

`2019/06/18 16:02:42 invalid commit message 846c00a0d0627408ed353b89d5961323ca745070: invalid header "feat(stdlib/regexp-compile): add regexp.compile to flux using regexp.Compile from Go (#1360)"`

for this full commit: 
```
commit f3e351c8944d055ab7518f35616d4e1960355dae (HEAD -> master, tag: v0.33.0, origin/master, origin/maint, origin/HEAD)
Author: Ewen Dai <yiwendai99@berkeley.edu>
Date:   Tue Jun 18 11:35:03 2019 -0700

    feat(stdlib/regexp): add regexp functions from Go to Flux (#1367)

    * feat(stdlib/regexp): add regexp functions from Go to Flux

    * feat(stdlib/regexp): update SPEC.md for Regexp Operations

    * feat(stdlib/regexp): add FluxEndToEnd tests
```

**Comment by nathanielc** [comment]
The issue is this pattern here https://github.com/influxdata/flux/blob/master/internal/cmd/changelog/cmd/generate.go#L367
