### ISSUE TITLE
Update transpiler to explicitly handle _time with aggregates and selectors

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#14]

**Comment by jsternberg** [comment]
I have submitted a change for the transpiler spec in influxdata/platform#818 for this change and I'll make the change shortly.

Are we removing any time handling from the aggregates? I think I remember a conversation where we were going to remove the `_time` column from aggregates and leave `_start` and `_stop`, but I can't seem to find the issue. If we aren't, then aggregates already get normalized explicitly and if we are, then I think it just needs `duplicate(column: "_start", as: "_time")`.
