### ISSUE TITLE
Make it the default to query data with a homogeneous schema

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1411]
A significant cause of user confusing and frustration is dealing with data that has a heterogeneous schema. By heterogeneous schema we mean that tables in a stream do not all have the same schema. 

We want to make it the default behavior when querying data from InfluxDB that the data has a homogeneous schema. And make it explicitly opt in to query data with heterogeneous schema. This way users are aware when they are dealing with the more complex use cases of heterogeneous schemas, while the happy path is the easy to use path.

This is related to #1298

**Comment by affo** [comment]
This is also related to the typed stream proposal in https://github.com/influxdata/flux/issues/439
