### ISSUE TITLE
row functions can only refer to globally defined elements

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#1413]
row functions (e.g. for map, filter, reduce) are all limited to referring to elements in the global scope.  The elements they should be able to refer to include: 
1.  local values to the current script, but outside the function's scope
2.  package-level values for imported packages
3.  local variables inside the function body. 

the last one surprised me: 
```
intables |> map(fn: (r) => {  myVal = strings.split(v:r.host, t: "") return {host: myVal[0]}})
Error: error calling function "map": name "myVal" does not exist in scope
```

**Comment by andig** [comment]
Shouldn't the example actually be

    intables 
    |> map(fn: (r) => (
        myVal = strings.split(v:r.host, t: "") 
        return {host: myVal[0]}
    ))

Notice the different brackets. But I still feel I might be understanding flux totally wrong...
