### ISSUE TITLE
Queries with the same time range return different windows 

### ISSUE THREAD

**Issue by ischolten** [influxdata/flux#1427]
I have 5 queries apart of a single flux script that have the same time range and window. The results are getting windowed by the `aggregateWindow` function and the `every` is set to `1h` while the functions are either `mean` or `sum`. 
`|> aggregateWindow(every: 1h, fn: mean)`

I would expect the results in each of the tables to have the same number of rows since the empty rows should be getting filled in. However, one of the queries is returning with more rows than the others.

**Comment by rbetts** [comment]
This is blocking the billing epic.

**Comment by OfTheDelmer** [comment]
Confirmed that this looks fixed now and the yielded results each have one row each.
