### ISSUE TITLE
Add Go implementation of moving average

### ISSUE THREAD

**Issue by roshie548** [influxdata/flux#1436]
The current definition of `movingAverage` written in pure Flux produces in duplicate rows at the end of the result table. 

- Implement moving average in flux, and
- add a planner rules

The planner rules will look for the pattern of `window + mean + duplicate` and internally rewrite it to use the Go implementation of moving average, which will prevent the creation of duplicate rows.

**Comment by nathanielc** [comment]
Why are there duplicate rows? I would expect that if both _start and _stop are preserved that there would not be duplicates. This is because each _start/_stop should uniquely define each of the moving windows.

**Comment by nathanielc** [comment]
> The planner rules will look for the pattern of window + mean + duplicate and internally rewrite it to use the Go implementation of moving average, which will prevent the creation of duplicate rows.

The planner rule cannot change the result of the computation. So both pure flux and the Go implementation need to produce the exact same results, duplicates included. Hence my question about where the duplicates are coming from.

**Comment by roshie548** [comment]
The Go implementation of `movingAverage` follows InfluxQL's spec much more closely. Rather than taking a movie average over time windows, it averages an `n` number of points.

The pure flux implementation still exists has been refactored to `timedMovingAverage`
