### ISSUE TITLE
Describing planner options in Flux

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#1439]
Relevant to #106.

We want to be able to disable certain rules during planning to ensure that planner rules never change the semantics of the executed program.  

We currently have a few different options defined in Go for the logical and physical planners:
https://github.com/influxdata/flux/blob/master/plan/logical.go#L63-L76
https://github.com/influxdata/flux/blob/master/plan/physical.go#L118-L142
None of them allow for disabling a single rule and leaving the others intact.  Options that allow this should be added.

In addition to support for disabling rules in the Go API, we should also allow it from Flux code, e.g:
```
option logicalPlannerOptions = {
  disableRules: ["MergeFilterAnyRule"],
}
option physicalPlannerOptions = {
  disableRules: ["PushDownGroupRule"],
}
```
The `Compiler` implementations that invoke the planner can then peek at the options and create the appropriate Go planner options when invoking the planners.

Open question: should we maintain 1:1 parity with planner options that can be specified in Flux and the planner options that are part of the Go API?

Work to do for this issue:
- Add planner options to the planners' Go API to disable particular rules
- Add code to `Compiler` implementations to look for the planner options in Flux
- Add tests that verify specifying planner options in Flux works correctly

**Comment by nathanielc** [comment]
I think 1:1 is fine so long as we communicate that the API is not stable. I think planning the options in a "plan" package could help with that. Maybe even a "plan" package as a subpackage of an "experimental" package.

**Comment by jlapacik** [comment]
This is a pretty cool idea. I guess there's really no other way to test planner rules via end-to-end tests without exposing them using these options. It seems pretty powerful though, and I don't really see any downside.
