### ISSUE TITLE
Update README and CONTRIBUTING to mention Rust dependency

### ISSUE THREAD

**Issue by stormasm** [influxdata/flux#1487]
Just updated the master branch and tried running tests,
and it looks like I have to install rust ?

```
make test
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C internal/rust test
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ast test
cargo test
make[2]: cargo: No such file or directory
make[2]: *** [test] Error 1
make[1]: *** [ast] Error 2
make: *** [internal/rust] Error 2

```

**Comment by stormasm** [comment]
So here is my work around for now...
Which seems easy enough for me to change back and forth...

```
test:
	$(GO_TEST) $(GO_TEST_FLAGS) ./...
```

But other folks who run tests might not get it...

**Comment by stormasm** [comment]
So I broke down and installed Rust on my Macbook Pro.
Everything now works out of the box.
No need to use Docker (at all).
It just works.
All of the tests pass.
Welcome to the world of Rust !

**Comment by affo** [comment]
I think that Rust should be an explicit requirement. We are moving towards having only one parser written in Rust. Those tests must run in order to say that the codebase is intact.  

Not only tests should be affected by the update, but also the `build` process. We should update the README to include instructions to install Rust.

**Comment by nathanielc** [comment]
@stormasm Thanks for pointing this out, the tests will run fine with rust on macOS it is when you need to build the wasm module of the Flux parser that you will need to use Docker. In most cases you likely won't need to build the wasm module.

@affo I agree lets add something to the README and CONTRIBUTING docs to make it clear.
