### ISSUE TITLE
Flux incorrectly responds with 200 OK for an invalid query

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/flux#149]
Per [the spec](https://github.com/influxdata/flux/blob/master/docs/SPEC.md#errors):

> When an error occurs before any results are materialized then the HTTP status code will indicate an error and the error details will be encoded in the csv table.

The current encoder and results interfaces do not provide a means for distinguishing client vs server errors. For example, the following query:

```flux
from(bucket: "telegraf/autogen")
```

results in a client error with a `200 OK` response:

```csv
#datatype,string,string
#group,true,true
#default,,
,error,reference
,failed to create physical plan: invalid time bounds from procedure from: bounds contain zero time,
```

Upon examination of the implementation, as found in Platform

https://github.com/influxdata/platform/blob/11f869fb37fb44d2cf59c9e245c6f3821c933993/http/query_service.go#L91-L103

a client error is determined if `n == 0`, however, CSV data has already been written to encode the error. It is unclear how to distinguish client vs server query errors and respond accordingly.

**Comment by nathanielc** [comment]
Anything before the `execute` package should be a 400 error, i.e. plan errors etc should be client errors. Only execution runtime errors should be 200OK and then encoded in the CSV body.
