### ISSUE TITLE
Implement shorthand time literals

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#152]
The SPEC states that `2018-01-01` should parse as midnight on that date. And that `2009-10-15T09:00:00` should parse using the default location.

Currently we require both the time and the time offset to be specified.

**Comment by aanthony1243** [comment]
check with @nathanielc to see if we need to implement both rust + golang parsers or just rust

**Comment by nathanielc** [comment]
This was closed in error

**Comment by nathanielc** [comment]
This was implemented, short date without a time can be parsed assuming a time of UTC midnight.
