### ISSUE TITLE
Make TableBuilder use arrow arrays

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1520]
`TableBuilder` takes arrow arrays in and saves/manipulates slices.   
Those slices are later converted into arrow arrays when a `ColReader` is created.  

`TableBuilder` could better wrap `arrow.*Builder` and use it. In this way we can save the conversions when creating a `ColReader`.

**Comment by nathanielc** [comment]
Instead of changing the existing table builder we should introduce a new one and slowly migrate to it.
