### ISSUE TITLE
Map types cant have variable as a key

### ISSUE THREAD

**Issue by roshie548** [influxdata/flux#1535]
Currently, map can't use variables from the scope of the function in which they are used.

In my case, I'd like to define double exponential moving average completely in flux, which should be possible because it's computed using exponential moving average. The flux definition would look like:

```
doubleExponentialMovingAverage = (n, column="_value", tables=<-) =>
    tables
          |> exponentialMovingAverage(n:n)
          |> duplicate(column:column, as:"ema")
          |> exponentialMovingAverage(n:n)
          |> map(fn: (r) => ({r with column: 2.0*r.ema - r.column}))
          |> drop(columns: ["ema"])
```
Rather than replacing `column` with the `column` parameter value, `map` treats `column` as a string literal.

**Comment by nathanielc** [comment]
@roshie548 Have a look at #1122 that should fix this issue for this use case.

**Comment by ewendai** [comment]
`timeColumn` in the following example has the same issue:

```
truncateTimeColumn = (timeColumn, unit, tables=<-) =>
    tables
        |> map(fn:(r) => ({r with timeColumn: date.truncate(t: r.timeColumn, unit: unit)}))
```
