### ISSUE TITLE
Add new time operators in addition to Now()

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#1549]
We should give users the ability to query times using operators other than now(). These would be some good additions:

today() - sets time to now() rounded down to start of day
yesterday() - sets time to now() - 1d rounded down to start of day
monday() - the start of the previous monday(). Do this for every day of the week
week() - the start of this week. Could take an argument for what day the week starts on
month() - month boundaries

closes  https://github.com/influxdata/influxdb/issues/2071

**Comment by sauren-khosla** [comment]
much easier once #1533 is deployed

**Comment by wolffcm** [comment]
Some more notes:
- There is already a function `date.week` that returns the week number (0-51) of its argument.  So we would need to figure out names.  Same thing for `month`.  Maybe `thisWeek()` and `thisMonth()`?
- `today()` can be implemented in pure Flux using `universe.truncate`.  Maybe `yesterday()` can be pure Flux too?
- Seems like `monday()` etc would need to be written in Go?

**Comment by sanderson** [comment]
Some quick function signatures that could work for this:

```js
import `experimental`
import `date`

// Returns the timestamp for 12am today
today = () => date.truncate(t: now(), unit: 1d)

// Returns the timestamp for 12am or 11:59:59pm yesterday
yesterday = (boundary="start") => {
  timeValue = 
    if boundary == "end" then experimental.subDuration(d: 1ns, from: today())
    else experimental.subDuration(d: 24h, from: today())
  return timeValue
}

// Returns the timestamp for 12am on the first day of the current week
thisWeek = (weekStart=date.Sunday) => {
  todayWeekDay = date.weekDay(t: today())
  todayDifference = todayWeekDay - weekStart
  return time(v: int(v: today()) - (int(v: 24h) * todayDifference))
}

// Returns the timestamp for 12am on the first day of the current month
thisMonth = () => date.truncate(t: today(), unit: 1mo)

// In use
from(bucket: "example-bucket") |> range(start: today())
from(bucket: "example-bucket") |> range(start: yesterday(), stop: yesterday(boundary: "end"))
from(bucket: "example-bucket") |> range(start: thisWeek(weekStart: date.Monday))
from(bucket: "example-bucket") |> range(start: thisMonth())
```

**Comment by timhallinflux** [comment]
Yeah, there are other query requests too that folks have asked for which are possible today with Flux.  Here are two examples:
```
import "date"
// Select mean(value) from measurement where time>now()-30d and dayOfWeek(Monday)

from(bucket: "example-bucket")
  |> range(start: -30d)
  |> filter(fn: (r) => r._field == "value" and date.weekDay(t: r._time) == date.Monday)
  |> mean()
```
```
import "date"
// Select mean(value) from measurement where time>now()-30d and hours(8,17)

from(bucket: "example-bucket")
  |> range(start: -30d)
  |> filter(fn: (r) => r._field == "value")
  |> hourSelection(start: 8, stop: 17)
  |> mean()
```

**Comment by wolffcm** [comment]
@mr-manuel We don't have any updates unfortunately, but @sanderson's comment above provides some handy workarounds.

**Comment by github-ps1304** [comment]
> Some quick function signatures that could work for this:
> 
> ```js
> import `experimental`
> import `date`
> 
> // Returns the timestamp for 12am today
> today = () => date.truncate(t: now(), unit: 1d)
> 
> // Returns the timestamp for 12am or 11:59:59pm yesterday
> yesterday = (boundary="start") => {
>   timeValue = 
>     if boundary == "end" then experimental.subDuration(d: 1ns, from: today())
>     else experimental.subDuration(d: 24h, from: today())
>   return timeValue
> }
> 
> // Returns the timestamp for 12am on the first day of the current week
> thisWeek = (weekStart=date.Sunday) => {
>   todayWeekDay = date.weekDay(t: today())
>   todayDifference = todayWeekDay - weekStart
>   return time(v: int(v: today()) - (int(v: 24h) * todayDifference))
> }
> 
> // Returns the timestamp for 12am on the first day of the current month
> thisMonth = () => date.truncate(t: today(), unit: 1mo)
> 
> // In use
> from(bucket: "example-bucket") |> range(start: today())
> from(bucket: "example-bucket") |> range(start: yesterday(), stop: yesterday(boundary: "end"))
> from(bucket: "example-bucket") |> range(start: thisWeek(weekStart: date.Monday))
> from(bucket: "example-bucket") |> range(start: thisMonth())
> ```

great work - works pretty good - would you mind to share the code for:
last week, last month and last year? would be very helpful
Regards Peter
