### ISSUE TITLE
support disjoint time ranges

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#1552]
as described in  https://github.com/influxdata/influxdb/issues/7530

**Comment by aanthony1243** [comment]
related to #1557

**Comment by roshie548** [comment]
Some thoughts:
We could have a two different functions for this feature, depending on what the user wants.
- `disjointRange(unit, int, int)`
  - This will cover seconds, minutes, hours, months, years
  - Also allows for more flexibility. For example, if you want the first and last month of every year, you could `|> window(every:1y) |> disjointRange(mo, 1, 12)`
- `disjointDateRange(time, time)`
  - This allows for a more specific query: `|> disjointDateRange(2019-06-03, 2019-07-03)`

**Comment by nathanielc** [comment]
@roshie548 Can you take a look at the SPEC for the intervals function? https://github.com/influxdata/flux/blob/master/docs/SPEC.md#intervals I think it is capable of expressing disjoint time ranges.

For example the first and last month of each year would be

```
intervals(every: 1y, period: 2mo, offset: -1mo)
```

The `intervals` function is not yet implemented but it _should_ be able to express these kinds of intervals. Maybe it would be a good exercise to validate that the `intervals` function can express these disjoint intervals.

**Comment by roshie548** [comment]
Once implemented, the `interval` function would cover disjoint time ranges.

Adding to your example, it'd cover the `hourSelection` function (discussed in #1557).
Selecting data that occurred between the hours 02:00AM and 08:00AM on any day:
```
intervals(every: 1d, period: 6h, offset: 2h)
```
Selecting data that occurred before 9:00 AM or after 5:00 PM: 
```
intervals(every: 1d, period: 16 h, offset: -7h)

**Comment by one4many** [comment]
I would love to have this!!!
