### ISSUE TITLE
Implement FixedZone function

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#156]
From the SPEC:

FixedZone creates a location based on a fixed time offset from UTC.

FixedZone has the following parameters:

* offset duration
    Offset is the offset from UTC for the time zone.
    Offset must be less than 24h.
    Defaults to 0, which produces the UTC location.

Examples:

    fixedZone(offset:-5h) // time zone 5 hours west of UTC
    fixedZone(offset:4h30m) // time zone 4 and a half hours east of UTC

**Comment by russorat** [comment]
dupe of #406 ?
