### ISSUE TITLE
Out of range integer literals converted to max int

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#1560]
If I enter an integer literal that is larger than max int64, it silently evaluates to max int64:
```
> x = 100000000000000000000000000000
> x
9223372036854775807
> 100000000000000000000000000000
9223372036854775807
```
We should throw an error if we can't represent the value represented by a literal.

**Comment by nathanielc** [comment]
DOD:

Fix is to report an error on literals that cannot be represented.
Add test case for error
