### ISSUE TITLE
BigQuery from/to support

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/flux#1563]
As we move towards working with more data sources and data where it resides, BigQuery is being requested by a number of interested community members who are awaiting InfluxDB on GCP per: https://cloud.google.com/blog/products/open-source/bringing-the-best-of-open-source-to-google-cloud-customers

Landing support for BigQuery in line with the October beta for InfluxDB on GCP would be ideal.

Existing Go library is here:
https://godoc.org/cloud.google.com/go/bigquery

**Comment by bckeene** [comment]
@timhallinflux - should we close this with [sql.from](https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/sql/from/#query-a-bigquery-database) and [sql.to()](https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/sql/to/#write-to-a-bigquery-database) supporting BigQuery now?

**Comment by timhallinflux** [comment]
yes. 
https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/sql/from/#query-a-bigquery-database
and
https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/sql/to/#write-data-to-a-sql-server-database
