### ISSUE TITLE
Implement LoadLocation function

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#157]
From the SPEC:

LoadLoacation loads a locations from a time zone database.

LoadLocation has the following parameters:

* name string
    Name is the name of the location to load.
    The names correspond to names in the [IANA tzdb](https://www.iana.org/time-zones).

Examples:

    loadLocation(name:"America/Denver")
    loadLocation(name:"America/Chicago")
    loadLocation(name:"Africa/Tunis")

**Comment by russorat** [comment]
dupe of #406 ?
