### ISSUE TITLE
Create Alert/Notification Package

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1575]
We need a package for alerts and notifications. It needs to be able to do a few things:

1. Evaluate a `check`: Consume data from an arbitrary query with at least `_value` and `_time` columns and evaluate a level function on each table. The level result along with the grouped columns from the input data need to be stored into a system bucket called a `status bucket`.
2.  Evaluate a `notification rule`: Execute a query against the `status bucket` and evaluate a rule function against the statuses. Send messages to third party notification endpoints when the rule indicates.
3. Log the notification events into a `notification bucket`.

Here is a glossary of terms used: 
```
Query: A Flux script that returns time series data (*Tags* + *Timestamp*)

Check: Analyzes the results of a *Query* to determine the current *Status* and writes it to a *Status Bucket*

Status: The *Level* and *Tags* of a *Check* written to the *Status Bucket*

Level: One of OK, INFO, WARN, CRIT, or UNKNOWN

Status Bucket: A location where a *Check* stores the current *Status*

Status Graph: A graph of the *Statuses* of a *Check* over time.

Notification Rule: A *Query* of a *Status Bucket* that returns the *Status*. When warranted by the rules, sends a *Message* to a 3rd Party using the *Notification Endpoint* and stores a receipt in the *Notifications Bucket*.

Notifications Bucket: A location where a *Notification Rule* records the name of the *Notification Endpoint*, *Message*, and *Tags* used in the *Query*.

Message: A templatized payload sent to *Notification Endpoint*.

Notification Endpoint: The configuration describing how to call a 3rd party service. E.g. Slack, Pagerduty

Alert: When a *Check* results in a *Status* that triggers a *Notification Rule*. 

``` 
Internal source: https://github.com/influxdata/idpe/blob/master/docs/content/rfcs/alertandnotify/alerts_and_notifications.md#methods

**Comment by nathanielc** [comment]
DOD:

We have written out a design of these package(s). The design should include what functions the package exposes and the type signature of the functions with docs. Enough detail needs to be provided that someone could write Flux queries to consume this package. The implementations of the functions does not need to be completed as part of this issue.

**Comment by jsternberg** [comment]
How do we plan for the flux queries to run? Do we think it's going to be similar to Kapacitor where the flux scripts are constantly running and getting new data or is the script going to be executed as part of an interval with tasks?

**Comment by nathanielc** [comment]
@jsternberg The queries will be evaluated on an interval using tasks.
