### ISSUE TITLE
Catch end to end tests that will not work in influxdb

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#1577]
The end to end tests in the flux repository are also used in influxdb. This has caused a few problems when releasing a new version of flux that has additional end to end tests.

### csv.from()

The `csv.from()` call does not require a `range()`. It likely should continue to not require a call to `range()`. But, the influxdb source does require this which causes any end to end test that doesn't have that call to fail. This causes us to add the call to `range()` to any end to end tests. We need some way of catching this or making it so these tests can run in influxdb without adding the `range()` call.

### The input schema is not compatible

For influxdb, we will read the input from csv and write it to influxdb and then query it. The problem is some of the input tables that we use for tests aren't writeable to influxdb. The `_measurement`, `_field`, and `_time` attributes are required to write to influxdb and, if those aren't present, then the test case will fail.

Either the writing to storage in influxdb has to be fixed to map any arbitrary values to influxdb and read them back for the end to end tests, or we need to mandate that the end to end tests in flux match that pattern so they work.

These have caused issues where we need to make a patch release when attempting to deploy a new flux with no breaking changes. A flux release with no breaking changes should just be a simple matter that doesn't require fixing test cases in a patch release.

**Comment by aanthony1243** [comment]
to my knowledge the CSV decoder is ONLY used in `csv.from`  perhaps we can make it behave a little more like the influxdb write path?

**Comment by affo** [comment]
I did like the idea of @wolffcm to create a function `verifyInput` that fails if:
 - the input doesn't contain `_measurement`, `_field`, and `_time` column;
 - the input contains nulls.

We could have a separate testing folder for those tests that should work in InfluxDB and change the option `testing.loadStorage` in that package so that it performs the check.
That package could also use a different version of `csv.from` that requires a `range` call.

If somebody adds a test to that package that doesn't follow the requirements, it would fail CI and his/her PR couldn't be merged.

**Comment by jsternberg** [comment]
We've talked about this a bit and it seems we want a few things.

1. We want it to be possible to write end to end tests that are not compatible with influxdb.
2. We want tests that are supposed to be compatible to be marked that way.

I was thinking one possible way of doing this might be to add an additional function for verifying the schema and verifying that `range` was called and to make it so that function was only used if an option was set.

So imagine that there was a function for testing that acted as a pass through from CSV. It would have a planner rule for `range()` to verify that `range()` was used and it would error if range wasn't used. It would also verify the schema of tables that come through and error if something isn't writable.

Then we would have an option that could be set to disable this. Some potential pseudocode:

```
option influxdbSoureCompatible = true
loadStorage = (csv) => if influxdbSourceCompatible then csv.from(csv: csv) |> v1.verifySchema() else csv.from(csv: csv)
```

**Comment by fchikwekwe** [comment]
After discussing our current goals for this issue, we've decided to first focus on checking end to end tests for compatibility with InfluxDB (#2937). We've also split the range() call and the schema compatibility ideas into two separate issues that can be tackled in a future sprint (#2935, #2936).

**Comment by fchikwekwe** [comment]
This issue has been addressed as noted above. Closing.
