### ISSUE TITLE
Add every parameter for window to aggregateWindow

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1606]
`aggregateWindow` doesn't support every parameter in `window`.

For example, one cannot specify `offset`.

Make it so.

**Comment by mabnz** [comment]
Can anyone help me understand how I am meant to use offset when aggregateWindow is being used? 

I can't for life of me figure it out, and it's meant I can't migrate a query I've used in InfluxQL to Flux.

**Comment by affo** [comment]
@mabnz I think you are targeting the right issue.

`aggregateWindow` does not expose every `window` argument.

This needs to be done.

FYI @nathanielc

**Comment by Congyuwang** [comment]
So far, `offset` is still not added to `aggregateWindow`. So I have to use `window` instead of `aggregateWindow` when I need offset, but `window` is slower. Another question is why is `window` so much slower than `aggregateWindow` when they are doing the same task.

**Comment by nathanielc** [comment]
Offset has been added in https://github.com/influxdata/flux/pull/3580

**Comment by ArrEssJay** [comment]
This would also be useful in `timedMovingAverage()`. It would be useful to join the moving average to the table with samples producing it for thresholding, but without an offset parameter in the moving average, I can't join on the time field without additional work to time align the two tables.
