### ISSUE TITLE
TimeCounter function

### ISSUE THREAD

**Issue by roshie548** [influxdata/flux#1609]
### Function
`timeCounter(name: ...)` will add a new column to each table telling which row the data is on. The column will be of type time (1s, 2s, 3s, ...), allowing it to be `window`ed.

An alternate, equivalent series of functions would be a `counter(name: ...)` function that adds a column of ints, followed by `|> map(fn: (r) => {r with t: time(r.t)})`

### Uses
The ability to `window` based on row number can be used to write functions that rely on a sliding window being independent from time. For example, `movingAverage` can be defined in flux:
```
movingAverage = (n, tables=<-) (
    tables
        |> timeCounter(name: "t")
        |> window(every: duration(1), period: duration(n), timeColumn: t)
        |> mean()
        |> window(every: inf)
)
```
Other existing functions can be re-written using `timeCounter` as well:
- `difference`
- `elapsed`
- `derivative` (using `difference` and `elapsed`)

**Comment by aanthony1243** [comment]
for flexibility, add `start=0` and `step=1` parameters
