### ISSUE TITLE
canceling query request does not cancel the query execution

### ISSUE THREAD

**Issue by gshif** [influxdata/flux#1610]
While I was testing the `total duration` of query execution for billing metrics, I wanted to see if duration of query run was reported (partially reported) or not reported at all when query was canceled in the midst or its run. 
I have tried different ways of canceling query from the client side, but always was able to see the time for complete query execution that was being written to `system_usage`. For example, if complete query run would take `10 seconds` and query was canceled after `3 seconds`, I saw in the query log that looked like query did not stop running since the duration was `10 sec`. This is just my observation, not sure what is the right way of canceling the query.

The query I was using, used a `seep` function to control the duration of the query.
- Query
```
from(bucket:"b1") |> range(start: -5m)|>sleep(duration: 10s)
```
As I mentioned before, I used few different ways to cancel the query request.
1. python requests with `timeout`. If data would not be received by the client within `timeout` time, the request would be canceled/stopped and exception would be raised, but no response object would be returned. Based on what I was able to find, the connection between client and server would not be kept alive. (I also set 'Connection':'close' in the header of the request)
Example request:
```
requests.post('http://gateway.gs-cluster.svc.cluster.local:9999/api/v2/query?org=o7', timeout=3, data='{"query":%s}' % json.dumps(s), headers={'Connection':'close','Authorization': 'Token 7KMp6marD-gTM4i9sD0R63dW67GeCZ2x3zYdLVo-cwkFq5DikoWhJsrjriK-BD8tZTFFYd4FwFW1wN8lJMaWow=='})
```

ReadTimeout exception would be thrown after 3 sec:
```
 raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='gateway.gs-cluster.svc.cluster.local', port=9999): Read timed out. (read timeout=3)
```
but the query log shows:
```
ts=2019-07-25T20:03:01.634055Z lvl=debug msg=Request log_id=0GqYw3mG000 handler=queryd method=POST path=/queryproxysvc status=200 duration_ns=10581008439
```
and there is a record in the `system_usage` bucket with the same value : `10581008`
2. Use Advanced REST Client. Different Client tool where you can send a request and abort the request. I saw the same results as in previous step
3. Use of urllib3 (python requests is using this library) The same results.

**Comment by painhardcore** [comment]
Yeah, the execution of one function cannot be interrupted. But if you do intead
```
from(bucket:"b1") |> range(start: -5m)|>sleep(duration: 1s)|>sleep(duration: 1s)|>sleep(duration: 1s)|>sleep(duration: 1s)|>sleep(duration: 1s)|>sleep(duration: 1s)|>sleep(duration: 1s)|>sleep(duration: 1s)|>sleep(duration: 1s)|>sleep(duration: 1s)
```
You can have 1s precise duration.
It's the only way since flux functions are not aware when cancellation happens.
And that's can trouble with OOM i.e. you messed up with your query in one function and you can't do anything about it, just watch your server explodes. Even you already canceled the request.
