### ISSUE TITLE
Design Secrets Store package

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1615]
Notification endpoints will require credentials in order to communicate with the various external services.

We do not want users to include those credentials in plain text into Flux scripts. We need to provide a mechanism for users load secrets from a safe storage mechanism and provide those secrets to the endpoints.

Some design questions/notes:

- We need a backing store, this should be abstracted behind and API (Go interface) as we will likely have multiple different implementations of the store.

- We need to have fine grained authorization around secrets. Using basic read/write access patterns is probably not sufficient. As an example users should have the ability to consume the slack token secret in order to send message to slack, without having access to read the actual token.

- A possible solution to the above is we create the secret storage package and only let other builtin packages consume it, then users simply pass in the name of the slack token secret to the slack endpoint and the slack endpoint function as a builtin reads the secret directly.

**Comment by nathanielc** [comment]
Some notes:

* Using a package is not strucly necessary
* Investigate how WASM and other systems design sandboxes to understand the basic abstractions of how to sandbox code execution
* Investigate the HashiCorp Vault API to inform how to design our internal API.

**Comment by affo** [comment]
@nathanielc maybe I misunderstood, but why don't we create a package with functions to retrieve values from keys, let it be a csv file, Vault, Redis, Memcached, Etcd or whatever else?

So that one can:

```
import "kv"

tok = kv.redis.get("token")

from(...)
  |> // ...
  |> slack.to(token: tok, ...)
```

**Comment by nathanielc** [comment]
To answer the above question. Secrets are more than just a KV store, they need to be designed in such a way that users cannot actually read the value of the secret even after they load it. Otherwise user's could expose the secrets via query results.

A possible solution to this problem is to never read the secret into Flux memory (i.e. values.Value), instead we just use a string or an object to represent a pointer to a secret but only load its value inside of the Go implementation of functions. This design means that any function that wants to read secrets needs to be implemented in Go, but that seems like a good compromise for now as compared to building out a complete sandboxing mechanism inside Flux the language.

Example:

```
import "secret"
import "slack"

token = secret.get(name: "slack_token")

slack.message(token: token, message: "hi its me", channel: "#test")
```

The `slack.message` function will be implemented in Go and use the secret reference passed in as the `token` parameter to look up the real secret value.
