### ISSUE TITLE
Design how scanning string interpolation will work. 

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1620]
Look at other languages like Ruby and PHP for how their scanners treat tokens inside string interpolations.

**Comment by jsternberg** [comment]
Something to consider is it will likely be necessary to intersperse the parser and the scanner and this should be fine and should not cause a big problem.

The way you would do this is decently simple, but it involves a lot of tokens.

You would have one token for a quote. This would signify both the beginning and the end of the string. The parser would begin reading a string expression when it sees a quote. After you see the quote, you would enter into a new lexer whose sole job is to continue scanning until it sees an end quote, the expression start symbol, or end of file. It would emit a string literal token for that.

When it sees a string expression begin token, the parser would go back to using the normal lexer and it would parse an expression. It would keep going until it saw the `}` bracket.

I don't think this should be too difficult. @jlapacik have you found anything that might indicate a better way of doing this? I can start trying to put together an example of how you would modify the lexer and a change to the EBNF for what this would look like.
