### ISSUE TITLE
Conjunction in filter on tag returns inconsistent results

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1624]
The incriminated query is:

```
from(bucket: "system_usage")
    |> range(start: -1d)
    |> filter(fn: (r) =>
        r.org_id == "03d01b74c8e09000" and
        r.org_id != "" and
        r._measurement == "http_request" and
        (r._field == "req_bytes" or r._field == "resp_bytes")
      )
    |> group()
    |> count()
```

It produces 2 rows.

If we comment out `r.org_id != ""` it produces > 25k rows.

This is a non-sense, because if an org is `03d01b74c8e09000`, then it is `!= ""` for sure.

I tried to download the result from Chronograf, store in a local InfluxDB instance with:

```
import "csv"

data = "
// chronograf csv export
...
"

csv.from(csv: data) |> to(bucket: "test", org: "root")
```

And then tried to reproduce it locally, but I couldn't (i.e. results were consistent).

NOTES:
 - if I change `r.org_id != ""` to `r.org_id != " "` (note the space between quotes, but it could be any other string) the inconsistency disappears;
 - if I comment out `r.org_id == "03d01b74c8e09000"` and leave `r.org_id != ""`, I get > 40k rows;
 - if I comment out `r.org_id == "03d01b74c8e09000"` and leave `r.org_id != " "`, I get > 3M rows.

So, does InfluxDB interpret `!= ""` in some special  way?

**Comment by jlapacik** [comment]
@affo storage interprets `!= ""` as not null. In other words, the predicate `r.org_id != ""` is interpreted by storage as all series having an `org_id` tag. At least that's how storage is supposed to be interpreting it.

Similarly storage treats `r.org_id == ""` as all series that do **not** have an `org_id` tag.

There is an issue to not push predicates like these down to storage and instead push the equivalent expressions that use the `exists` operator. https://github.com/influxdata/influxdb/issues/14093. However it is clear that storage is either rewriting or evaluating predicates incorrectly.

One thing is for sure - any Flux query that makes comparisons against the empty string is most likely incorrect. Replacing such comparisons with their equivalents using the `exists` operator will have the intended semantics.

**Comment by affo** [comment]
I see your point @jlapacik 

Anyways, I think we all agree that `r.org_id == "03d01b74c8e09000" and r.org_id != ""` and `r.org_id == "03d01b74c8e09000"` should be equivalent in any predicate.

Still investigating the issue, although I have problems in reproducing it locally and so, I cannot debug the cause (should be in expression reduction I think) 🤔.

I am now trying more strategies and see if I can.

**Comment by affo** [comment]
With this query:

```
from(bucket: "system_usage")
    |> range(start:2019-07-31T15:23:00Z, stop: 2019-08-01T15:33:00Z)
    |> filter(fn: (r) =>
        r.org_id == "" and
        r._measurement == "http_request" and
        (r._field == "req_bytes" or r._field == "resp_bytes")
      )
    |> limit(n: 1)
    |> group()
    |> sort(columns: ["org_id"])
```

I get this result back:

![image](https://user-images.githubusercontent.com/4246582/62308717-39cf1200-b486-11e9-94a4-acaf4d072fe9.png)

Where some value is actually __not null__.

With this one:

```
from(bucket: "system_usage")
    |> range(start:2019-07-31T15:23:00Z, stop: 2019-08-01T15:33:00Z)
    |> filter(fn: (r) =>
        //r.org_id != "" and
        r._measurement == "http_request" and
        (r._field == "req_bytes" or r._field == "resp_bytes")
      )
    |> limit(n: 1)
    |> map(fn: (r) => r) // this ensures the rest is not pushed down to storage
    |> filter(fn: (r) => not exists r.org_id)
    |> group()
    |> sort(columns: ["org_id"])
```

I get a consistent result (Flux correctly keep null values).

This is more of a problem with storage than with Flux.

In Flux we shouldn't allow users to push down to storage predicates as `tag != ""` or `tag == ""`. But we should only allow `exists tag` or `not exists tag` and we should translate them accordingly to keep a unified framework for users.

Still, this bug affects storage. I couldn't reproduce it locally. I am filing a separate issue for this.

**Comment by affo** [comment]
After pairing with @benbjohnson we saw that the issue disappeared. Could it be related to some indexing problem in storage?

Push down  of `exists` is now merged, one can now use either `v != ""` or `exists v` and  get a consistent behavior.

Closing the issue.
