### ISSUE TITLE
Flux Inserts "null_" in Front of Text Making it Unsearchable

### ISSUE THREAD

**Issue by cmd-influx** [influxdata/flux#1626]
Jenkins Influxdata generates data (line protocol format unknown) which is treated differently by InfluxQL and Flux on the Chronograf Internal setup ([Acceptance](http://chronograf.internal/sources/3/dashboards/108?lower=2019-07-14T04%3A00%3A00.000Z&upper=2019-07-22T04%3A00%3A00.000Z) dashboard #108 "QA SLI").  The cell queries are below and can be seen or edited in the dashboard mentioned.  Use slightly bigger time ranges since there are only a dozen Jenkin runs an hour on a normal day.

Influxql query:
SELECT project_name FROM "kube-infra"."monthly"."jenkins_data" WHERE time > :dashboardTime: AND "build_result"='SUCCESS' FILL(null)

Returns timestamps and project_name with the typical project_name "PR_xxxx".

Flux query:
from(bucket: "kube-infra/monthly")
  |> range(start: dashboardTime,stop: upperDashboardTime)
  |> filter(fn: (r) => r._measurement == "jenkins_data")
  |> filter(fn: (r) => r._field == "build_result" and r._value == "SUCCESS")
  |> drop(columns: ["build_result","_value","_field","_measurement"])
  |> group()
  |> yield()

Returns timestamp and project_name with the typical project_name "null_PR-xxxx"

The true and likely project name is "PR-xxxx" with a dash, not an underscore or null **BUT** Jenkins Influx plugin does have a "change dash to underscore" so without looking at the raw data I cannot tell which format was given to Influx or if there are hidden characters at the beginning of the project_name.

The goal was to divide project_name into buckets using InfluxQL syntax 'AND "project_name"=~ /master/' or 'AND "project_name"=~ /PR.*/'.  I was unable to use Regex to get past the "null_" part of the project name in Flux.

**Comment by nathanielc** [comment]
@cmd-influx The above Flux query is a query of the raw data, no part of that query is modifying the data in anyway. I would look on the write side of things to figure out where the `null_` prefix is coming from.

**Comment by rbetts** [comment]
You can use `influx-inspect` against the raw TSM files perhaps?

**Comment by cmd-influx** [comment]
Dropping and deleting from Flux.  Moved elsewhere.
