### ISSUE TITLE
Update the SPEC for aggregateWindow

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1629]
AggregateWindow works with any function that accepts `column` as parameters.

I propose to change its name to `applyWindow` or similar.

Otherwise, it sounds weird to use a selector as input for `aggregateWindow`.

If we decide to keep the current name, the SPEC should be updated by saying that `aggregateWindow` can be used both with selectors and aggregates.

__UPDATE__:

The name will remain the same. The SPEC must be updated by saying that `aggregateWindow` can be used both with selectors and aggregates.

**Comment by nathanielc** [comment]
When you pass a selector function to the `aggregateWindow` function it makes the selector behave like an aggregator.

For example the `max` selector called by itself will find the max value and return the entire row. The `_time` for that row will be the time found. 

In contrast using `max` as part of `aggregateWindow` will replace the `_time` column with the `_stop` column in the output role. This way aggregate and selectors behave the same when using `aggregateWindow`. If you wish to use `max` as a pure selector then you should not use it as part of `aggregateWindow`.

**Comment by affo** [comment]
@nathanielc I see your point. Subtle, but a big difference!

Changing the title of the issue to update the SPEC
