### ISSUE TITLE
Remove bucketID and orgID parameters from to()

### ISSUE THREAD

**Issue by jpacik** [influxdata/flux#1660]
Currently `to()` takes parameters `bucket` and `bucketID` that are specified as mutually exclusive. That is, you cannot call `to()` with both parameters. This cannot be supported by the type system. Instead `to()` should take a single bucket parameter representing a bucket name, and there should be a separate function for converting a bucket ID to its associated name. Similarly for the parameters `org` and `orgID`.

See influxdata/influxdb#14594.

**Comment by nathanielc** [comment]
I like the idea that @jsternberg had in slack, use string type for bucket names and integer type for bucketIDs using the hex syntax of defining the bucket ID.

Examples:

```
from(bucket:"foo") // find bucket by name
from(bucket: 0x03cbbf8eb3a9e000) // find bucket by id
```

This means we need to allow for specialized functions which I don't we can support yet. Or we need to add a special kind to the type system which seems to specific a solution. But the user experience is good and so worth exploring how we could implement it.

**Comment by wolffcm** [comment]
There is a similar problem with the `host` and `token` parameters: if `host` is specified, then `token` must be also.  Maybe this is okay to catch at runtime though?

**Comment by wolffcm** [comment]
Also, a similar issue exists with `experimental.to()`.

**Comment by jlapacik** [comment]
`host` and `token` could also be specified together as an object `{host: string | token: string}`?
