### ISSUE TITLE
Adapt technical analysis functions to use the gota library

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#1677]
The technical analysis functions were implemented by someone outside of InfluxDB and it was ported into an internal package with a reference to the original package.

Since the technical analysis functions are written by someone outside of InfluxDB, they need to be kept in a separate library for copyright purposes. The copied over technical analysis functions will need to be adapted so that we copy over the library and use that library.

https://github.com/influxdata/influxdb/blob/1.7/query/internal/gota/README.md

**Comment by affo** [comment]
As @sauren-khosla pointed out, is this relevant for Holt Winters too?

I took the code of the Neldermead optimizer from here: https://github.com/influxdata/influxdb/tree/1.7/query/neldermead

And inspired to the Holt Winters code here: https://github.com/influxdata/influxdb/blob/1.7/query/functions.go#L1295

These doesn't leave in the `gota` package, so I suppose that is our code, and not a port from another library.

**Comment by affo** [comment]
@nathanielc great job then :)
