### ISSUE TITLE
Re-implement dependency injection as a pre-registration process, and thread the new model into both Execute and Interpreter

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#1679]
update:   

The ultimate goal is that interpreted function calls should be provided with a context and set of external dependencies needed to complete certain tasks: 
```
// Function represents a callable type
type Function interface {
    Value
    HasSideEffect() bool
    Call(ctx context.Context, deps dependencies.Interface, args Object) (Value, error)
}
```
with dependencies.Interface defined in `dependencies/depencies.go`: 
```
package dependencies

type Interface {
    HTTPClient() *http.Client
    SecretService() SecretService
}
```
_____________________________________________

per discussion:  the above design will work for all dependencies but for the time being, we will be implementing this as a separate service and will update existing dependency injections to this design at a later time. 

external dependencies will be pre-registered at `init` time, and then initialized at startup time.  

for example, `to`  requires these services
- BucketLookup
- OrgLookup
- PointsWriter

They will be pre-registered in the `init function: 
```
func init() {
  flux.RegisterDependency(FromKind, "bucketlookup", dependencies.BucketLookup)
  flux.RegisterDependency(FromKind, "organizationLookup", dependencies.OrganizationLookup)
  flux.RegisterDependency(FromKind, "pointsWriter", dependencies.PointsWriter)
}
```

type `execute.Dependencies` will be refactored to be: 
```
type Depedencies map[string]map[string]interface{}
```

and the RegisterDependency function will populate a dependency set (excluding error conditions):
```
func RegisterDependency(resourceKind,  dependencyKind string, dependency interface{})  {
    depsMap[resourceKind][dependencyKind] = dependency
}
```

Finally, at startup, `depsMap` will be iterated to produce a new map populated with instances of each required dependency.  

this new `depsMap` is similar to the existing depsMap and will be provided to tranformations via the `Administration` interface.   The interpreter will also now require dependencies.  A side effect of this refactor is that the dependency map will also be copied as a field into the runtime interpreter when a query is executed (the ideal point to do this copy is in compile.go/EvalAST where the interpreter is initialized).

**Comment by nathanielc** [comment]
Basic design skeleton, Create a dependencies package with a single interface:
```
package dependencies

type Interface {
    HTTPClient() *http.Client
    SecretService() SecretService
}
```

Update function Call method to consume those dependencies.
```
// Function represents a callable type
type Function interface {
	Value
	HasSideEffect() bool
	Call(ctx context.Context, deps dependencies.Interface, args Object) (Value, error)
}
```

**Comment by jsternberg** [comment]
I guess the part I'm wondering is if we can partially implement the proposed changes that @affo wrote up, we gave feedback on, and addresses this particular need. I think the work to create and thread the `ExecutionContext` would be the same as what is proposed here.

**Comment by sauren-khosla** [comment]
Merged PR: https://github.com/influxdata/flux/pull/1740
