### ISSUE TITLE
Group lookup slow for large number of groups

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#169]
The current implementation of the group lookup type is not performant. It has to maintain a sorted list of all groups and naively sorts on insert.

This performance issue arises when you have many groups which is most common when using `window`.

**Comment by nathanielc** [comment]
@nikolay-t Can you provide some details on the number of windows/groups you have? Also maybe share an example Flux script that demonstrates the blocking issue. That will help us understand the correct optimizations we can make.

**Comment by nikolay-t** [comment]
We see noticeable performance drop when number of table goes above 700-800. I think correct optimization would be not to sort everything on every table processing since obviously it is not required and sorting is expensive. Questions: what will happen if we just disable sorting in func (l *GroupLookup) Set? Do we have a contract to keep tables sorted? Or is it for performance of func (l *GroupLookup) findIdx?

**Comment by nathanielc** [comment]
@nikolay-t Thanks for the info. The sorting is required by the current implementation. The `findIdx` function performs a binary search over the list of groups. If it is not sorted it will not be able to find them. That said sorting the entire array on every insert is obviously very slow. We haven't spent much time optimizing that code path yet.

**Comment by nathanielc** [comment]
A side effect of the way we do grouping is that large amount of RAM can be consumed with high cardinality data combined with many windows.

**Comment by nikolay-t** [comment]
Yes, we noticed RAM consumption as well. What if we introduce some sort of "table id" and assign it to each table upon creation, when group keys/values are known. This "table id" can be made of concatenation of group key names and values (string conversion). It can cost some RAM (i.e. 200 bytes per table), but if created only once, further sorting will be cheaper, and findIdx won't require binary sort, just map lookup.

**Comment by nathanielc** [comment]
We made many performance improvements to groups and their management. At this point subsequent improvements will need their own issues. In most cases this should not come up as an issue.
