### ISSUE TITLE
Define update record semantics

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1710]
What semantics do we want for updating records?

For example the `experimental.set` function can both add new columns and override existing columns. This can cause issues with type inference. We need to explore the semantics we can employ in order to update records safely.

See https://github.com/influxdata/flux/pull/1702 for where this was first discussed.

**Comment by jlapacik** [comment]
Just to add some context, we cannot use the same operation to both update an existing object property as well as extend an object with a new property. We cannot infer a principal type for the object if we do this. See [here](https://github.com/influxdata/flux/pull/1613/files#r307932310) for an example.

We need a separate operation for explicitly updating an already existing property on an object.

Currently Flux values are immutable so this is not an issue in vanilla Flux as we have no way for updating an object. All we have is the `with` keyword for creating a completely new object by extending an old one. However functions like `set` implicitly operate on objects and so it's important that they preserve the correct semantics.

I propose we add a new function called `experimental.update` with much the same signature as `experimental.set`, the only difference being it updates columns that are assumed to already exist on its input. `set` would then be used to extend tables with columns that are assumed to not exist on its input.

**Comment by nathanielc** [comment]
@jlapacik The semantics of `with` allow it to both update and extend and object. Does that also need to change?

**Comment by jlapacik** [comment]
@nathanielc yes that will need to change. When we update the type system with [extensible record types](#1613) this won't be allowed anymore. However update can be defined entirely in terms of delete and extend and therefore is completely supported by the type system (just not as part of the same operation).
