### ISSUE TITLE
Remove  kafka.to 

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1711]
The `kafka.to` function doesn't follow the new design of how encoders and transports should work. Kafka is both its own encoding and transport and needs to be updated accordingly.

In the meantime the `kafka.to` function is unused and presents an API that we expect to change. It also represents a security concern as it allows talking directly to kafka from Flux.

As such I recommend we remove the function entirely and add it again using the safe and compossible patterns of encoders + transports. 

We could spend the effort to update it now, but its not a priority to be able to talk to kafka generically.

**Comment by timhallinflux** [comment]
we are getting a couple of folks interested in a `kafka.to()`
