### ISSUE TITLE
Semantic nodes should have type information

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#1715]
Every node in the semantic package that implements `semantic.Expression` should make its Flux type available after type checking/inference. Currently type inference creates a mapping of expressions to their corresponding types. Unfortunately after initial program evaluation by the interpreter, this mapping is lost.

Instead type inference should attach this type information to the semantic nodes themselves. This would allow the compiler the ability to grab the types off the actual nodes in order to perform fast type checking, removing the need to run an entirely new pass of type inference over the compiler function.

**Comment by nathanielc** [comment]
DOD:

* Semantic nodes use flatbuffer representation of their type information
* We do not expect any tests would apply to this change.
