### ISSUE TITLE
options.go not enough arguments

### ISSUE THREAD

**Issue by sfloam** [influxdata/flux#1747]
After pulling about an hour ago without changing any of my source code, I started receiving this error. Any idea what is going on here?

# github.com/influxdata/influxdb/task/options
src/github.com/influxdata/influxdb/task/options/options.go:206:31: not enough arguments in call to flux.EvalAST
	have (*ast.Package)
	want (context.Context, dependencies.Interface, *ast.Package, ...func(values.Scope))

**Comment by nathanielc** [comment]
@sfloam Yes, we just landed a large refactor, the EvalAST function now needs a context and a set of dependencies. See #1740 for details on the refactor if you are interested.

**Comment by sfloam** [comment]
@nathanielc this is triggered when attempting to run go get github.com/influxdata/influxdb.
