### ISSUE TITLE
Multiple yields 

### ISSUE THREAD

**Issue by chnn** [influxdata/flux#176]
Hello, I'm running the following query:
```
from(bucket: "telegraf/autogen")
  |> range(start: -1m)
  |> yield(name: "foo")

from(bucket: "telegraf/autogen")
  |> range(start: -2m, stop: -1m)
  |> yield(name: "bar")
```
I only see `result`s for `foo` coming back. Are multiple yields supported in Flux at the moment?

I'm using whatever Flux is bundled with InfluxDB at commit `691dfb8bc`.

**Comment by jlapacik** [comment]
Closing this issue. This has been fixed with the new planner integration. It has been tested and both results are returned.
