### ISSUE TITLE
Support equality between boolean values

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1780]
We noticed a few of these error in the wild:

```
unsupported binary expression bool == bool
```

The query was something like this:

``` 
  // ...
  |> filter(fn: (r) => r.remaining == true)
```

While this could be simplified to 

``` 
  // ...
  |> filter(fn: (r) => r.remaining)
```

it should work in the original form.

**Comment by yzhang1991** [comment]
Released in https://github.com/influxdata/flux/releases/tag/v0.42.0
