### ISSUE TITLE
Add planner option to enable rules by name

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1789]
We currently don't have the possibility to enable rules _by name_ into the planner.

This functionality would unlock enabling planner options directly from the flux code.

**Comment by nathanielc** [comment]
I don't follow the logic for having both enabled and disabled sets? Are not all rules enabled by default? If so then what is the use case for having an enabled list?

**Comment by affo** [comment]
The idea is to provide certain rules that are registered but not enabled by default.

The `injectYields` rule is an example: https://github.com/influxdata/flux/issues/1791.

Someway, they are like directives to the compiler, the user can decide to switch a flag to enable them.

**Comment by nathanielc** [comment]
This was implemented
