### ISSUE TITLE
createEmpty behaves unexpectedly with extern variables

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#1794]
I am creating a query to monitor disk percent across my hosts. Here is my process:

1. this is the query i created to look at a single host which gives me the expected result:
```
from(bucket: "telegraf")
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == "disk")
  |> filter(fn: (r) => r._field == "used_percent")
  |> filter(fn: (r) => r.host == "rsavage.prod")
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
  |> yield(name: "mean")
```

![image](https://user-images.githubusercontent.com/4805997/64209904-9ee7a000-ce56-11e9-810b-a5dc20cf798f.png)

2. I want to update the query to use an extern variable for host so i can switch between them, but when i update the query to use that variable in the host filter, all hosts are returned:
```
from(bucket: "telegraf")
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == "disk")
  |> filter(fn: (r) => r._field == "used_percent")
  |> filter(fn: (r) => r.host == v.host)
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
  |> yield(name: "mean")
```

![image](https://user-images.githubusercontent.com/4805997/64209970-d35b5c00-ce56-11e9-954c-5389179d8de8.png)

3. The only way to get back to the value i want is to now add a `createEmpty: false` to my aggregate window:
```
from(bucket: "telegraf")
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == "disk")
  |> filter(fn: (r) => r._field == "used_percent")
  |> filter(fn: (r) => r.host == v.host)
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")
```

![image](https://user-images.githubusercontent.com/4805997/64210051-14537080-ce57-11e9-9833-fbe17d9ecd55.png)

The documentation for the `aggregateWindow` function says that the `createEmpty` parameter: `For windows without data, this will create an empty window and fill it with a null aggregate value.`

It's not intuitive to me that this parameter would also create null values for hosts that should have been filtered out.

**Comment by jsternberg** [comment]
This is fixed by #2287.
