### ISSUE TITLE
Make the interpreter execute when a call produces a side effect

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1799]
It is reasonable that if a function call has a side-effect, the interpreter should execute it before proceeding, because it could affect the rest of the query.

If we make it so, then

```
... |> to(bucket: "test")
from(bucket: "test") |> ...
```

Would work as expected.

This would make the machinery we do now in OSS for e2e tests useless.

**Comment by yzhang1991** [comment]
Several geo tests in OSS are skipped for now because of this issue.
Remember to unskip them upon the completion of this issue.
See: https://github.com/influxdata/influxdb/blob/master/query/stdlib/testing/testing.go#L98
