### ISSUE TITLE
Character omitted from AST location data

### ISSUE THREAD

**Issue by chnn** [influxdata/flux#1801]
I parsed the following Flux program:

```
warn = (r) => 
    (r.used_percent > 10)

crit = (r) =>
    r.used_percent > 20
```

I expected that the `location.source` associated with the first `VariableAssignment` node in the body to be:
```
warn = (r) => \n    (r.used_percent > 10)
```
However, what I received instead was:
```
warn = (r) => \n    (r.used_percent > 10
```
Note that the right parenthesis is missing from the end. It doesn't seem to be present in other sibling AST nodes.

Here's the full AST response:

<details>
  <pre>
    <code>
{
  "ast": {
    "type": "Package",
    "package": "main",
    "files": [
      {
        "type": "File",
        "location": {
          "start": {
            "line": 1,
            "column": 1
          },
          "end": {
            "line": 5,
            "column": 24
          },
          "source": "warn = (r) => \n    (r.used_percent > 10)\n\ncrit = (r) =>\n    r.used_percent > 20"
        },
        "package": null,
        "imports": null,
        "body": [
          {
            "type": "VariableAssignment",
            "location": {
              "start": {
                "line": 1,
                "column": 1
              },
              "end": {
                "line": 2,
                "column": 25
              },
              "source": "warn = (r) => \n    (r.used_percent > 10"
            },
            "id": {
              "type": "Identifier",
              "location": {
                "start": {
                  "line": 1,
                  "column": 1
                },
                "end": {
                  "line": 1,
                  "column": 5
                },
                "source": "warn"
              },
              "name": "warn"
            },
            "init": {
              "type": "FunctionExpression",
              "location": {
                "start": {
                  "line": 1,
                  "column": 8
                },
                "end": {
                  "line": 2,
                  "column": 25
                },
                "source": "(r) => \n    (r.used_percent > 10"
              },
              "params": [
                {
                  "type": "Property",
                  "location": {
                    "start": {
                      "line": 1,
                      "column": 9
                    },
                    "end": {
                      "line": 1,
                      "column": 10
                    },
                    "source": "r"
                  },
                  "key": {
                    "type": "Identifier",
                    "location": {
                      "start": {
                        "line": 1,
                        "column": 9
                      },
                      "end": {
                        "line": 1,
                        "column": 10
                      },
                      "source": "r"
                    },
                    "name": "r"
                  },
                  "value": null
                }
              ],
              "body": {
                "type": "BinaryExpression",
                "location": {
                  "start": {
                    "line": 2,
                    "column": 6
                  },
                  "end": {
                    "line": 2,
                    "column": 25
                  },
                  "source": "r.used_percent > 10"
                },
                "operator": ">",
                "left": {
                  "type": "MemberExpression",
                  "location": {
                    "start": {
                      "line": 2,
                      "column": 6
                    },
                    "end": {
                      "line": 2,
                      "column": 20
                    },
                    "source": "r.used_percent"
                  },
                  "object": {
                    "type": "Identifier",
                    "location": {
                      "start": {
                        "line": 2,
                        "column": 6
                      },
                      "end": {
                        "line": 2,
                        "column": 7
                      },
                      "source": "r"
                    },
                    "name": "r"
                  },
                  "property": {
                    "type": "Identifier",
                    "location": {
                      "start": {
                        "line": 2,
                        "column": 8
                      },
                      "end": {
                        "line": 2,
                        "column": 20
                      },
                      "source": "used_percent"
                    },
                    "name": "used_percent"
                  }
                },
                "right": {
                  "type": "IntegerLiteral",
                  "location": {
                    "start": {
                      "line": 2,
                      "column": 23
                    },
                    "end": {
                      "line": 2,
                      "column": 25
                    },
                    "source": "10"
                  },
                  "value": "10"
                }
              }
            }
          },
          {
            "type": "VariableAssignment",
            "location": {
              "start": {
                "line": 4,
                "column": 1
              },
              "end": {
                "line": 5,
                "column": 24
              },
              "source": "crit = (r) =>\n    r.used_percent > 20"
            },
            "id": {
              "type": "Identifier",
              "location": {
                "start": {
                  "line": 4,
                  "column": 1
                },
                "end": {
                  "line": 4,
                  "column": 5
                },
                "source": "crit"
              },
              "name": "crit"
            },
            "init": {
              "type": "FunctionExpression",
              "location": {
                "start": {
                  "line": 4,
                  "column": 8
                },
                "end": {
                  "line": 5,
                  "column": 24
                },
                "source": "(r) =>\n    r.used_percent > 20"
              },
              "params": [
                {
                  "type": "Property",
                  "location": {
                    "start": {
                      "line": 4,
                      "column": 9
                    },
                    "end": {
                      "line": 4,
                      "column": 10
                    },
                    "source": "r"
                  },
                  "key": {
                    "type": "Identifier",
                    "location": {
                      "start": {
                        "line": 4,
                        "column": 9
                      },
                      "end": {
                        "line": 4,
                        "column": 10
                      },
                      "source": "r"
                    },
                    "name": "r"
                  },
                  "value": null
                }
              ],
              "body": {
                "type": "BinaryExpression",
                "location": {
                  "start": {
                    "line": 5,
                    "column": 5
                  },
                  "end": {
                    "line": 5,
                    "column": 24
                  },
                  "source": "r.used_percent > 20"
                },
                "operator": ">",
                "left": {
                  "type": "MemberExpression",
                  "location": {
                    "start": {
                      "line": 5,
                      "column": 5
                    },
                    "end": {
                      "line": 5,
                      "column": 19
                    },
                    "source": "r.used_percent"
                  },
                  "object": {
                    "type": "Identifier",
                    "location": {
                      "start": {
                        "line": 5,
                        "column": 5
                      },
                      "end": {
                        "line": 5,
                        "column": 6
                      },
                      "source": "r"
                    },
                    "name": "r"
                  },
                  "property": {
                    "type": "Identifier",
                    "location": {
                      "start": {
                        "line": 5,
                        "column": 7
                      },
                      "end": {
                        "line": 5,
                        "column": 19
                      },
                      "source": "used_percent"
                    },
                    "name": "used_percent"
                  }
                },
                "right": {
                  "type": "IntegerLiteral",
                  "location": {
                    "start": {
                      "line": 5,
                      "column": 22
                    },
                    "end": {
                      "line": 5,
                      "column": 24
                    },
                    "source": "20"
                  },
                  "value": "20"
                }
              }
            }
          }
        ]
      }
    ]
  }
}
    </code>
  </pre>
</details> 

I used the InfluxDB API to get the AST:

```
curl localhost:9999/api/v2/query/ast \
  -X POST \
  -H "Authorization: Token $INFLUX_TOKEN" \
  -d '{"query":"warn = (r) => \n    (r.used_percent > 10)\n\ncrit = (r) =>\n    r.used_percent > 20"}'
```

The Flux version is v0.43.0.

**Comment by affo** [comment]
This should involve updates both to the Rust parser and the Go parser.
