### ISSUE TITLE
Overriding options with a value of a different type should error

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1829]
I was able to:

```
now()
now = "wops"
now
```

And get

```
2019-09-09T08:20:32.536042000Z
wops
```

The interpreter should raise an error if one tries to override a function with a string.

Is this a problem with the type checker?

**Comment by jlapacik** [comment]
Yes the type checker should enforce that you can't reassign an option a new value with a different type.

**Comment by yzhang1991** [comment]
Type checker now can check this.
