### ISSUE TITLE
Add a dropNullRows() function

### ISSUE THREAD

**Issue by davidgs** [influxdata/flux#1847]
After joining tables I frequently find that the resulting table will have a row (or rows) that have `null` values in it. If I am then passing that table off to a function to do calculations on, it dies because there are `nulls` in it. I'd love to be able to call a `dropNullRows()` function and have it eliminate any rows that contain null values first.

**Comment by sanderson** [comment]
@davidgs You can filter out rows with `null` values with:

```
|> filter(fn: (r) => exists r._value
```

**Comment by sanderson** [comment]
FYI, documenting the `exists` operator is on my to-do list: https://github.com/influxdata/docs-v2/issues/428

**Comment by jsternberg** [comment]
I don't think this is an issue anymore because most functions have been updated to deal with null values and exists can be used to determine if it is null and filter the value out. If this is still an issue, please reopen.
