### ISSUE TITLE
interface conversion: interface {} is nil, not string 

### ISSUE THREAD

**Issue by davidgs** [influxdata/flux#1856]
Submitting the query:

`import "strings"
import "sql"

humidity = from(bucket: "telegraf")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "environment" and (r._field == "humidity"))
  |> last()
  |> map(fn: (r) => { return  {Sensor_ID: r.Sensor_id} })
  
  query = "SELECT * FROM Sensor_Data WHERE Sensor_ID is ${ humidity.Sensor_ID}"

sql.from(
  driverName: "mysql",
 dataSourceName: "foo:bar@tcp(localhost:3306)/IoTMeta",
 query: query
)`

Results in error: 

> interface conversion: interface {} is nil, not string

I've checked that `humidity.Sensor_ID` is not nil by adding a '|> yield()` before the `query` line, and it is there. (.csv of that attached). 

[2019-09-12-16-13_chronograf_data.csv.zip](https://github.com/influxdata/flux/files/3607280/2019-09-12-16-13_chronograf_data.csv.zip)

**Comment by russorat** [comment]
happening to me as well with the following query:

this query works with the attached data.
```
import "strings"
import "influxdata/influxdb/v1"

from(bucket: "telegraf")
  |> range(start: -365d)
  |> filter(fn: (r) => r._measurement == "usgs")
  |> filter(fn: (r) => r.type == "earthquake" and r.status == "reviewed")
  |> filter(fn: (r) => r._field == "mag" or r._field == "place" or r._field == "latitude" or r._field == "longitude")// or r._field == "tsunami" or r._field == "url")
  |> filter(fn: (r) => exists r.magType)
  |> drop(columns: ["sources","host","properties_alert"])
  |> v1.fieldsAsCols()
```

but adding the line: ` |> filter(fn: (r) => strings.containsStr(v: r.place, substr: "any string"))` produces the following error: `panic: interface conversion: interface {} is nil, not string`
```
import "strings"
import "influxdata/influxdb/v1"

from(bucket: "telegraf")
  |> range(start: -365d)
  |> filter(fn: (r) => r._measurement == "usgs")
  |> filter(fn: (r) => r.type == "earthquake" and r.status == "reviewed")
  |> filter(fn: (r) => r._field == "mag" or r._field == "place" or r._field == "latitude" or r._field == "longitude")// or r._field == "tsunami" or r._field == "url")
  |> filter(fn: (r) => exists r.magType)
  |> drop(columns: ["sources","host","properties_alert"])
  |> v1.fieldsAsCols()
  |> filter(fn: (r) => strings.containsStr(v: r.place, substr: "any string"))
```

[2019-10-21-11-39_chronograf_data.csv.zip](https://github.com/influxdata/flux/files/3752395/2019-10-21-11-39_chronograf_data.csv.zip)

**Comment by jlapacik** [comment]
Note in the first query the error comes from the line:
```
query = "SELECT * FROM Sensor_Data WHERE Sensor_ID is ${ humidity.Sensor_ID}"
```
Here `humidity` is used as a record but the real type is actually a stream, i.e a list of records. Type inference unfortunately doesn't catch this, and so we get a runtime panic with an indecipherable error message. The current type inference work as outlined [here](https://github.com/influxdata/flux/issues/1939) will make it so that this errors at compile time with an error message that describes exactly why it is invalid.

For the second query that @russorat submitted, I'm not exactly sure why it is throwing the same error. It appears the `strings.containsStr` function isn't handling null values correctly(or at all). This query should definitely compile.

**Comment by affo** [comment]
@russorat you should enforce in your filter `exists r.place and ...`. That should be a workaround.

**Comment by russorat** [comment]
@affo adding exists produces the same error:

![image](https://user-images.githubusercontent.com/4805997/67309226-53de2680-f4b0-11e9-9614-375d29d58414.png)

**Comment by affo** [comment]
@actually the error changed to be the one in https://github.com/influxdata/flux/issues/2036.

I guess that if you write it as `|> filter(fn: (r) => exists r.place and strings.containsStr(v: r.place, substr: "any string"))`, that doesn't change anything...

Ok, the workaround didn't work. I think we should check `strings` package for null handling and we should also check filtering with `exists`. Thanks for reporting this.

Another workaround can you use a regexp?:

`|> filter(fn: (r) => r.place =~ /any string/))`
