### ISSUE TITLE
Error handling on posts: need to be able to check error code as well as the response header + body for errors.  

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#1871]

**Comment by affo** [comment]
I'd say, put extra attention on accounting for the size of the `resp.Body` (maybe using `memory.Allocator`?).

Suppose we use `ioutil.ReadAll` and that somebody puts up a server that returns a 1TB response.

**Comment by nathanielc** [comment]
@affo Good point, we should create a utility method that is the same as `ioutil.ReadAll` but uses `memory.Allocator` for the internal buffer size.
