### ISSUE TITLE
Hook flux secrets up to BoltDB

### ISSUE THREAD

**Issue by nisley** [influxdata/flux#1885]
@nisley commented on [Thu Sep 12 2019](https://github.com/influxdata/influxdb/issues/15130)

I am able to put secrets into BoltDB in OSS via the API and list them out via the API.

When I query them via Flux with the same code I use in production cloud:
secrets.get(key: "mysecret")  
I get:
error in evaluating AST while starting program
{"code":"not found","message":"error in evaluating AST while starting program","error":{"code":"not found","message":"error calling function \"get\"","error":{"code":"not found","message":"secret not found"}}}

**Comment by russorat** [comment]
same as https://github.com/influxdata/influxdb/issues/15185

**Comment by nisley** [comment]
OSS add secret:
```
curl --data '{"mysqlpassword": "new_value"}' --request PATCH --url http://localhost:9999/api/v2/orgs/039346c3777a1000/secrets --header 'Authorization: Token zx-xrxmnD92Z6gUE-GSlIVqTV0KXxXJFO4_qPapWG-cxkVPaJJwg0A2nicJsNIrotwKPlDDnTbey1Piqof2fZQ=='
```

Query secret:
```
curl --request GET --url http://localhost:9999/api/v2/orgs/039346c3777a1000/secrets --header 'Authorization: Token zx-xrxmnD92Z6gUE-GSlIVqTV0KXxXJFO4_qPapWG-cxkVPaJJwg0A2nicJsNIrotwKPlDDnTbey1Piqof2fZQ=='

{"links":{"org":"/api/v2/orgs/039346c3777a1000","self":"/api/v2/orgs/039346c3777a1000/secrets"},"secrets":["local-postgres-connection","mysqlpassword"]}
```

Flux script (note- only errors when secrets.get line is uncommented):
```
import "sql"

import "influxdata/influxdb/secrets"

pagerduty_secret = secrets.get(key: "mysqlpassword")

from(bucket: "sqlguide")
    |> range(start: -1m)
    |> filter(fn: (r) =>
        (r._measurement == "airSensors" and r._field == "co"))
```

Error message:
```
{"code":"not found","message":"error in evaluating AST while starting program","error":{"code":"not found","message":"error calling function \"get\"","error":{"code":"not found","message":"secret not found"}}}
```

**Comment by nisley** [comment]
https://github.com/influxdata/influxdb/issues/15208

**Comment by jlapacik** [comment]
@nisley and I confirmed that flux can retrieve secrets from boltDB in OSS.
