### ISSUE TITLE
does flux support continuous query like InfluxQL?

### ISSUE THREAD

**Issue by ChenWenBrian** [influxdata/flux#1888]
I would like to do some down-sampling work, InfluxQL can do this with CQ, but what about flux? How can I achieve this with flux?

**Comment by sanderson** [comment]
@ChenWenBrian If you're using InfluxDB 1.x, no, you can't use Flux in a continuous query. If you're using the InfluxDB 2.0 alpha, CQs are replaced by tasks. Tasks are essentially scheduled Flux scripts. Here's some 2.0 documentation links:

- [Process Data with InfluxDB tasks](https://v2.docs.influxdata.com/v2.0/process-data/)
- [Downsample data with InfluxDB 2.0](https://v2.docs.influxdata.com/v2.0/process-data/common-tasks/downsample-data/)

**Comment by ChenWenBrian** [comment]
thanks for your replay, that's  really helpful.

**Comment by bugfix4u** [comment]
Would a down sampling task script work with InfluxDB 1.8.0?

**Comment by sanderson** [comment]
@bugfix4u Downsampling “tasks” are unique to InfluxDB 2.0. These tasks have an entire scheduling and processing engine behind them that doesn’t exist in InfluxDB 1.x. The 1.x equivalent is a continuous query (CQ). CQs do not support Flux and I don’t know if there are plans to add support in the future.
