### ISSUE TITLE
Add "extend" option to map

### ISSUE THREAD

**Issue by andig** [influxdata/flux#1890]
With the current implementation of map, you often end up replicating a number of columns just to keep them:

    |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r.title}))

To simplify this it would be nice if `r` could come pre-populated to allow only modifying the columns that need it. That might be done adding an `extend` parameter:

    |> map(fn: (r) => ({_field:r.title}), extend: true)

**Comment by sanderson** [comment]
@andig, this is accomplished using the `with` operator.

```
|> map(fn: (r) => ({ r with _field:r.title }))
```

The `with` operator was introduced in v0.33.0.
