### ISSUE TITLE
Fix WalkIR problems

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1896]
`WalkIR`  is used by OSS for `BucketAccessed`.

It compiles a Program from an  AST; evaluates; gets the Spec; and walks it.

The problem is that we need an evaluation to  be triggered  to get the Spec and walk it.

In the case of a dynamic query, WalkIR would trigger an execution with an unlimited allocator and we don't want that.

We should elaborate a strategy: either change `BucketAccessed` or extract a spec without evaluating functions.

**Comment by aanthony1243** [comment]
closed as this is no longer used
