### ISSUE TITLE
All errors in flux repo should be `flux` errors

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#1897]
Uses of Errors.New  and fmt.Errorf  should be replaced with flux.Error  types.

**Comment by jsternberg** [comment]
The standard way to convert errors is to use the `github.com/influxdata/flux/internal/errors` package which contains the utilities for this.

If you see the `errors.New` function being used from `import "errors"`, then the standard way to convert it is:

```go
- errors.New("my message")
+ errors.New(codes.Internal, "my message")
```

The code will not always be internal. If the message is meant for users, then `codes.Invalid` is usually more appropriate. You can look in the `codes` package at the root of the Flux repository for all of the available codes. An `Internal` code will get filtered the same way that the standard library codes will be filtered.

If you see `fmt.Errorf` then you would do:

```go
- fmt.Errorf("my message: %s", "hello")
+ errors.Newf(codes.Internal, "my message: %s", "hello")
```

Same as the above, `Internal` is only an example. If you are unsure of the code, then `Internal` will prevent the message from showing up to end users and is considered safe. But, be aware that an internal message is intended only for internal use and will not be seen by users. It corresponds to a 500 http error while invalid corresponds to 400.

I'm going to take on doing this for the `stdlib/universe` package.

**Comment by aanthony1243** [comment]
@nathanielc  I'm not sure how this is a `compute` job, as it involves modifying and annotating large portions of the flux runtime code.

**Comment by nathanielc** [comment]
@aanthony1243 Agreed, must have gotten lumped in with some other issues.

**Comment by lyondhill** [comment]
A patter is established for this kind of work here: https://github.com/influxdata/influxdb/blob/master/task_errors.go
