### ISSUE TITLE
Undefined identifier "intervals"

### ISSUE THREAD

**Issue by N3oXid** [influxdata/flux#1906]
**OS**: CentOS Linux release 7.6.1810
**InfluxDB**: 1.7.8
**Flux**: 0.36
**Installation**: With Yum from https://repos.influxdata.com/rhel/7/x86_64/stable

I got InfluxDB 1.7.8, with Flux enabled, but I'm not able to use intervals(). Each time I get the error "_undefined identifier "intervals"_".

Flux is enabled using the influxDB configuration file:
```
# grep -i flux-enabled /etc/influxdb/influxdb.conf
  flux-enabled = true
```

For instance, here is what I get using the CLI:
```
# influx -type=flux
Connected to http://localhost:8086 version 1.7.8
InfluxDB shell version: 1.7.8
> from(bucket: "librenms") |> range(start:-2d) |> filter(fn: (r) => r.hostname == "X.X.X.X" and r.ifName == "X" and r._measurement == "ports" and r._field == "ifInBits_rate") |> window(intervals: intervals(every: 1d, period: 8h, offset: 8h))
Error: type error 1:201-1:210: undefined identifier "intervals"
```

FYI, I also tested with a the InfluxDB v2.0.0-alpha Docker image and I got the same issue.

**Comment by nathanielc** [comment]
@N3oXid Thanks for the detailed report. The `intervals` function does not yet exist. You can follow our progress on it here https://github.com/influxdata/flux/issues/407

**Comment by N3oXid** [comment]
Thank you @nathanielc. Few more comments and questions:
- The link [](https://github.com/influxdata/platform/blob/master/query/docs/SPEC.md#intervals) in  [#407](https://github.com/influxdata/flux/issues/407) is broken.
- The `intervals()` function does not yet exist but it is documented: Does it mean it should be available in the next incoming version of Flux?

**Comment by nathanielc** [comment]
@N3oXid Thanks, I have fixed the link. Below the `intervals()` function in the SPEC is an `IMPL` tag that links to the issue #407 to indicate that it is not yet implemented. So it will not be part of the next Flux version (we cut those weekly) but it is on our roadmap as it is a popular and critical feature to add. Watch issue #407 to see when we start working on it and when its complete.
