### ISSUE TITLE
"unsupported aggregate column type int" when attempting to compute median

### ISSUE THREAD

**Issue by chnn** [influxdata/flux#191]
Hello, I tried to run the following query:

```
from(bucket: "telegraf/autogen")
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == "mem" and r._field == "active")
  |> window(every: 1m)
  |> percentile(percentile: 0.5)
  |> group(except: ["_value", "_start", "_stop"])
```

I received this error:

```
#datatype,string,string
#group,true,true
#default,,
,error,reference
,unsupported aggregate column type int,
```

Should I be able to run the `percentile` aggregation on an integer column? Or should integers be coerced to floats?

Also I noticed that this query seems to act the same:

```
from(bucket: "telegraf/autogen")
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == "mem" and r._field == "active")
  |> window(every: 1m)
  |> median()
  |> group(except: ["_value", "_start", "_stop"])
```

I believe `median` is currently undocumented in the SPEC.

**Comment by nathanielc** [comment]
@chnn, your summary is correct. The percentile function is not defined for ints, since it uses an approximation implementation by default that requires floats. You can convert your int column to a float column using the `toFloat` function.

```
from(bucket: "telegraf/autogen")
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == "mem" and r._field == "active")
  |> window(every: 1m)
  |> toFloat()
  |> percentile(percentile: 0.5)
  |> group(except: ["_value", "_start", "_stop"])
```

**Comment by chnn** [comment]
ok, thanks!

**Comment by ndrwrbgs** [comment]
Give the solution is programmatic, could we just update the program to do the toFloat (and support int)?
