### ISSUE TITLE
CSV serialization of Flux error should capture the error code as well as message

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#1916]
Currently our CSV error schema does not capture the nature of the error being serialized.  It might be a user error or an internal error.

We should enhance our CSV error schema to be able to programmatically determine the nature of a serialized error.

The serialization happens here:
https://github.com/influxdata/flux/blob/master/csv/result.go#L914

**Comment by jsternberg** [comment]
This is really important. My intention was always to update the reference column to code and start serializing the code in there. I think recent events have bumped it up the priority list.
