### ISSUE TITLE
toHTTP function seems to never execute

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/flux#192]
I have a query that returns results:

```
'from(bucket:"demo-bucket-in-1") |> range(start:-1h) |> last()'
Result: _result
Table: keys: [_start, _stop, _field, _measurement]
                   _start:time                      _stop:time           _field:string     _measurement:string                      _time:time                  _value:float
------------------------------  ------------------------------  ----------------------  ----------------------  ------------------------------  ----------------------------
2018-10-29T18:36:12.028749000Z  2018-10-29T19:36:12.028749000Z                       n                 counter  2018-10-29T19:15:50.616071000Z                          1148
```

But when I use `toHTTP`, no HTTP requests are made. 

```
'from(bucket:"demo-bucket-in-1") |> range(start:-1h) |> toHTTP(url:"http://localhost:12345")'
```

I'm trying to send the result to a simple HTTP server that just prints out whatever requests arrive.

Through printf debugging, I've determined that `(*ToHTTPTransformation).Process` is never being called. I don't understand enough of what else is going on in that part of the code, to make much further progress without doing a lot more learning first.

I'm using commit `39f39ce9135326d126c224b8b2b6c8f72a5600d6`, which is what is currently on platform master. I haven't tried bisecting other commits to find if there was some point where it did work.

**Comment by jlapacik** [comment]
@mark-rushakoff how are you running the above query? Through the repl? What happens if you put a `yield()` on the end of the query like so:

    from(bucket:"demo-bucket-in-1")
        |> range(start:-1h)
        |> toHTTP(url:"http://localhost:12345")
        |> yield()

**Comment by mark-rushakoff** [comment]
Using `influx query`, with influx build from platform master today.  `./influx  query -t ... --org-id 02dc43328ac01000 'from(bucket:"demo-bucket-in-1") |> range(start:-1h) |> toHTTP(url:"http://localhost:12345")'`.

Putting `|> yield()` on the end of that query appears to fix the issue so that the HTTP request is executed. But it's surprising to me that I would need to do that.

**Comment by jlapacik** [comment]
This is an issue with the Flux REPL. The REPL always looks for a call to `yield()` in order to execute a query:

https://github.com/influxdata/flux/blob/340b9f699992434e350508b98d756bd3a14ab9e7/repl/repl.go#L182

This is unnecessary since all queries will go through planning where any implicit yields will be made explicit. I will file an issue to modify this check by the REPL and link here.
