### ISSUE TITLE
Create Flux source for data generation

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1927]
It would be cool to have a source that generates data from some specification in Flux.

We should look at @stuartcarnie work for `influxd generate`: https://github.com/influxdata/influxdb/blob/dffca8f4fee67fd52571ba9cf19b22ba43a5b4f3/cmd/influxd/generate/command.go#L18

If we had such source, we could improve some of the e2e tests that have big input.

Not mentioning we could fuzz our transformations to see if the are broken in corner cases.

**Comment by jsternberg** [comment]
We have something similar to this that is being used in #1894. It would be good to combine Stuart's work on generate and the one we have in internal, but we can't at the moment because of the cyclical dependency it would create.
