### ISSUE TITLE
More advanced conditional math expressions in a map() function are failing

### ISSUE THREAD

**Issue by royemmerich** [influxdata/flux#1929]
OS: Ubuntu 18.04.1 LTS
Influx version: 1.7.8
Flux version: [0.36.2](https://docs.influxdata.com/influxdb/v1.7/about_the_project/releasenotes-changelog/#features)
Install: pre-built package [from here](https://dl.influxdata.com/influxdb/releases/influxdb_1.7.8_amd64.deb)

Reference: [community post here](https://community.influxdata.com/t/more-advanced-conditional-math-expressions-in-a-map-function/11402)

The query below is contrived, but it serves to illustrate the problem I'm having. I want to perform more complicated mathematical expressions in each condition of the if/else statement within the `map()` function, for which I need to use parenthesis.

If I run the following query it works:

```
from(bucket: "my_bucket")
  |> range(start: dashboardTime)
  |> filter(fn: (r) => r.controller_id == "304511028a28" and (r._field == "bms_batt_v" or r._field == "bms_batt_a" or r._field == "bms_soc" or r._field == "bms_soh" or r._field == "rectifier_1_v" or r._field == "rectifier_1_a" or r._field == "rectifier_2_v" or r._field == "rectifier_2_a"))
  |> last()
  |> keep(columns: ["_time", "_value", "_field"])
  |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
  |> map(fn: (r) => ({
      _time: r._time,
      _value:
        if r.bms_batt_a < 0 then
          1.0 * 2.0
        else
          3.0 + 4.0
     }))
```

However if I place parenthesis around each expression in the if/else statement then it fails in Chronograf with **[object Object]**:
```
from(bucket: "my_bucket")
  |> range(start: dashboardTime)
  |> filter(fn: (r) => r.controller_id == "304511028a28" and (r._field == "bms_batt_v" or r._field == "bms_batt_a" or r._field == "bms_soc" or r._field == "bms_soh" or r._field == "rectifier_1_v" or r._field == "rectifier_1_a" or r._field == "rectifier_2_v" or r._field == "rectifier_2_a"))
  |> last()
  |> keep(columns: ["_time", "_value", "_field"])
  |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
  |> map(fn: (r) => ({
      _time: r._time,
      _value:
        if r.bms_batt_a < 0 then
          (1.0 * 2.0)
        else
          (3.0 + 4.0)
     }))
```

The actual mathematical expressions I want to run in the `map()` function are are as follows:

```
  |> map(fn: (r) => ({
    _time: r._time,
    _value:
      if r.bms_batt_a < 0 then
        (100.0 * r.bms_soh/100.0 * r.bms_soc/100.0) / (r.bms_batt_a * 0.95 * -1.0)
      else
        (100.0 * r.bms_soh/100.0 * r.bms_soc/100.0) / ((r.rectifier_1_a*r.rectifier_1_v + r.rectifier_2_a*r.rectifier_2_v)/r.bms_batt_v * 0.95)
  }))

```

**Comment by nathanielc** [comment]
@royemmerich Thanks for the detailed report. You should be able to use parentheses in expressions to arbitrary complexity. There was a bug however that caused the UI to fail when parsing these kinds of expressions. It has since been fixed see https://github.com/influxdata/flux/issues/1801 and https://github.com/influxdata/flux/pull/1848
