### ISSUE TITLE
Implement Algorithm W

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1939]
Some resources for Algorithm W in general

OCaml Implementation and Description - https://github.com/tomprimozic/type-systems/tree/master/algorithm_w

Wikipedia Page https://en.wikipedia.org/wiki/Hindley%E2%80%93Milner_type_system#An_inference_algorithm - This one is hard to read so don't worry if it doesn't make much sense

**Comment by jlapacik** [comment]
![type-inf-issue-deps](https://user-images.githubusercontent.com/22945345/66514906-e6cf9780-ea92-11e9-8634-812f44761e21.png)

**Comment by nathanielc** [comment]
Closing, all algo w issues have been completed. Any new issues will be bugs or feature requests.
