### ISSUE TITLE
Update HistogramQuantile function to expect data in the form produced by prometheus scrape

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1940]
The promethesus.scrape function now produces a standard format for the table data. We should ensure that the histogramQuantile function works with that data format.

This will be a breaking change, so we should first introduce it in the experimental package. In other words do not change the existing function, rather make a modified copy.

**Comment by fchikwekwe** [comment]
@nathanielc I just want to clarify that I'm updating HistogramQuantile to be able to calculate any quantile value between 0.0 and 1.0 based on the values that are passed in from `prometheus.scrape`.

**Comment by fchikwekwe** [comment]
I also have some questions about the context in which this function will be called. Are these tables being read from InfluxDB? Is the user providing me a field name so I know which quantiles to use? 

Also, the range of quantiles varies by field (i.e. `prometheus_target_interval_length_seconds` provides quantile values `0.01`, `0.05`, `0.5`, `0.9` and `0.99`; `prometheus_engine_query_duration_seconds` provides `0.5`, `0.9` and `0.99`). I'm not yet sure if this matters for implementation.

**Comment by fchikwekwe** [comment]
After pairing with Chris, we realized that the modifications needed were far less extensive than we initially thought.
