### ISSUE TITLE
Define the main data types of the Flux type system

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#1951]
This issue is to define the 3 main data types used in the Flux type system. They are `MonoType`, `PolyType`, and `Kind`.

A monotype is a specific named type such as integer, float, or string. It should probably be represented using an enum like so:
```Rust
enum MonoType {
    Int,
    Flt,
    Str,
    Tvar,
    ...
}
```

A polytype is a parametric type. Parametric types are parametrized or quantified by zero or more free variables that can be replaced with arbitrary monotypes. This substitution of a polytype's free variables is what allows for polymorphism in Flux. Note that polytypes are a superset of monotypes. A monotype is a polytype with zero free variables, i.e. there's only one way to instantiate it. A polytype should be defined something like this:
```Rust
use std::collections::HashMap;

struct PolyType {
    freeVars: Vec<Tvar>,
    constraints: Option<HashMap<Tvar, Kind>>,
    expr: MonoType,
}
```

Note, every variable in Flux is assigned a parametric type, while every expression in Flux is given a monomorphic type.

The final concept of the Flux type system is that of kinds. A kind represents a class of types (think type classes in Haskell). Kinds are used to constrain the free variables of a polytype. For example, if we know that one of a polytype's free variables represents a type that can be used with the `+` operator, then we know that type is of kind `Addable`. In other words, it belongs to the class of types that `+` accepts. Note, kinds or type classes are what allow for fine grained operator overloading in Flux. The `Kind` data type should probably be defined as an enum as well.
```Rust
enum Kind {
    Addable,
    Divisible,
    Comparable,
    Nullable,
    ....
}
```

Note all 3 of the above data types should implement (not derive) custom equality and display methods corresponding to the `PartialEq` and `Display` traits respectively.

**Comment by nathanielc** [comment]
Note there are some naming changes here from the Go types:

Go -> Rust
* MonoType merges with PolyType -> MonoType
* Scheme -> PolyType
* Kind -> Kind

**Comment by nathanielc** [comment]
The Display methods should format the types according to the type grammar.
