### ISSUE TITLE
Parse type expressions

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#1952]
This issue is for creating a small parser for polytype and monotype expressions. Note this issue is for testing purposes. We need a way to succinctly express the types that we expect in test cases. Test cases should be easy to write as well as easy to read and understand. They should also be easy to debug if necessary.

Ex.
```
f = (x, y) => x + y
```
The polytype of `f` should be expressed as:
```
forall ['a] where 'a: Addable (x: 'a, y: 'a) -> 'a
```

See [here](https://github.com/jlapacik/influxible/blob/master/infer_test.go) for examples and [here](https://github.com/jlapacik/ftel/blob/master/antlr/flux.g4) for the grammar.

Note this issue does not require adding type expressions to the Flux grammar/parser. That can be done at a later date at which point type inference test cases will just use the Flux parser to parse their expected types.

Note, the above links (and example) are just examples. This issue will define the grammar used for type expressions.

**Comment by affo** [comment]
This solution _could be_ explored: https://github.com/goffrie/plex.

We could follow the ragel lexer + hand-made parser too

**Comment by jlapacik** [comment]
Some clarification: The output of parsing should be an AST that is distinct from the actual types defined as part of #1951. There should however be a 1-1 mapping between these AST nodes and the type structures defined in #1951. By having this parser generate its own AST, we can easily integrate it with the Flux parser when it comes time to add type expressions to the Flux grammar.

After this issue has been implemented, all that will be needed is a simple function to instantiate a type structure from the aforementioned AST.

**Comment by nathanielc** [comment]
As discussed in #1993 we are going simplify the grammar slightly for type variables.

Instead of parsing type variables as  `'a` we will expect the form `t0` and `t1` etc. The production rule will be:

```
tvr
    : 't' [0-9]+
    ;
```

**Comment by jlapacik** [comment]
Update: It turns out we will in fact need to support multiple kind constraints on type variables. Hence the grammar should be updated to support polytype expressions like:
```
forall [t0] where t0: SomeKind + AnotherKind + ... + LastKind (x: t0) -> t0
```
In particular you can constrain free type variables with multiple kinds using `+`.
