### ISSUE TITLE
Generate type constraints for semantic expressions and blocks

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#1956]
~~Each semantic expression node as well as block nodes should implement the trait defined in #1954.~~

#2061 defines unimplemented `infer` methods on expression nodes that are used for generating type constraints. This issue is for implementing those `infer` methods. Note constraints will also need to be generated for function blocks, however #2061 provides an implementation. That implementation will be used when generating the constraints for function expressions.

Note #1958 is required for generating constraints for semantic function blocks.

**Comment by nathanielc** [comment]
Notes:

 * Reference the Go code for which constraints each expression should generate
* @jlapacik Will add details about which expressions need kind constraints

DOD

* Tests exist using test harness in #2072 for all expressions and types except for the function and record types
