### ISSUE TITLE
sql.from() appears not to be able to handle JOINs

### ISSUE THREAD

**Issue by davidgs** [influxdata/flux#1965]
```
SELECT * FROM Customer_Data, Sensor_data WHERE Customer_Data.CustomerID = Sensor_data.CustomerID AND Sensor_data.Sensor_ID = 'THPL001' AND Sensor_data.measurement = 'temperature'
```

Fails with "An internal error has occurred"

If I remove the `Customer_Data.CustomerID = Sensor_data.CustomerID` part, it succeeds.

**Comment by davidgs** [comment]
The problem arises since the `Customer_Data.CustomerID` and `Sensor_data.CustomerID` fields have the same name name, so the table has 2 columns with the same name. If I rename a column in the MySQL database so they are not the same, the query succeeds.

**Comment by jsternberg** [comment]
I think the solution here is that the SQL driver needs to prefix the field name with the database when a join occurs. This may be a breaking change though because it changes the default naming.
