### ISSUE TITLE
Flux v0.36.2 type conversion functions don't seem to work when combined with a map command

### ISSUE THREAD

**Issue by trb237** [influxdata/flux#1979]
Setup: 

- Influx 1.7.3 with Flux 0.36.2

- Influx running in Docker container

I can get into the Influx Flux CLI and issue type conversion commands which work as documented [float(), int(), time()]. However, when I tried to either use toFloat() or toInt() or toTime(), I get Internal Server error crashes.

Here are things that I tried:

curl localhost:8086/api/v2/query?db=astat -unyy:syy -XPOST -sS -H 'accept:application/csv' -H  'content-type:application/vnd.flux' -d 'from(bucket:"astat") |> range(start: -1m) |> filter(fn:(r) => r._measurement == "fRuleSource" and r._field == "last_rule_update") |> toTime()'

RESULT: INTERNAL SERVER ERROR

curl localhost:8086/api/v2/query?db=astat -unyy:syy -XPOST -sS -H 'accept:application/csv' -H  'content-type:application/vnd.flux' -d 'from(bucket:"astat") |> range(start: -1m) |> filter(fn:(r) => r._measurement == "fRuleSource" and r._field == "request_count") |> map(fn:(r) => ({ r with request_count: float(v: r.request_count) }))'

RESULT: INTERNAL SERVER ERROR

curl localhost:8086/api/v2/query?db=astat -unyy:syy -XPOST -sS -H 'accept:application/csv' -H  'content-type:application/vnd.flux' -d 'from(bucket:"astat") |> range(start: -1m) |> filter(fn:(r) => r._measurement == "fRuleSource" and r._field == "last_rule_update") |> map(fn: (r) =>  ({ r with _value: time(v:_value) }))'

RESULT: UNKNOWN TYPE INVALID

curl localhost:8086/api/v2/query?db=astat -unyy:syy -XPOST -sS -H 'accept:application/csv' -H  'content-type:application/vnd.flux' -d 'from(bucket:"astat") |> range(start: -1m) |> filter(fn:(r) => r._measurement == "fRuleSource" and r._field == "last_rule_update") |> map(fn: (r) =>  time(v: r._value))'

RESULT: INTERNAL SERVER ERROR

curl localhost:8086/api/v2/query?db=astat -unyy:syy -XPOST -sS -H 'accept:application/csv' -H  'content-type:application/vnd.flux' -d 'from(bucket:"astat") |> range(start: -1m) |> filter(fn:(r) => r._measurement == "fRuleSource" and r._field == "last_rule_update") |> map(fn: (r) => ({_time: r.last_rule_update, last_rule_update: time(v: r.last_rule_update)}))'

RESULT: INTERNAL SERVER ERROR

We would really like to figure this out and see if we can use the type conversion functions. They are important to the business logic of what we are trying to do. Please advise.

**Comment by russorat** [comment]
@trb237 thanks for the report. i'm going to close this for now since this is opened against a very old version of flux. i haven't seen any other issues with type conversions and map functions.
