### ISSUE TITLE
panic: column _value:float is not of type string

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#1996]
Found in cloud2. this should be an error for sure, but not a panic: 
`{"code":"internal error","message":"panic: column _value:float is not of type string"}`
```
from(bucket: "telegraf")
  |> range(start: -1h)
  |> set(key: "_value", value: "my_field")
```

**Comment by sanderson** [comment]
@russorat this is a known issue. Right now, `set()` can only set string values. @nathanielc, does `experimental.set()` let you set values of any type or is that dependent on the type system refactor?
