### ISSUE TITLE
internal error: using fill on a tag or string column

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#2001]
found in cloud2. works if i change the column to "_value".
```
from(bucket: "telegraf")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> limit(n:2)
  |> fill(column: "_field", usePrevious: true)
```

**Comment by sanderson** [comment]
I don't think you're able to fill anything that's in the group key. You could test my theory by including `group(columns: ["_field", "_time", "_value"], mode: "except")` before the fill.

**Comment by aanthony1243** [comment]
yeah, logically, `group key` columns cannot have nulls.   I guess we could just quietly let it go, since it has no effect.

**Comment by nathanielc** [comment]
Group keys should allow null values, but I don't think we have tests for that. We should investigate as part of this issue.

**Comment by russorat** [comment]
no longer an issue: 
![image](https://user-images.githubusercontent.com/4805997/138367220-27592cb3-e8b3-4eb2-a9d4-7990cbc07e68.png)
