### ISSUE TITLE
Make flux.Duration use values.Duration instead of time.Duration

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2010]
The `flux.Duration` type is used by Flux as the serializable representation of a duration. It is currently implemented using `time.Duration`. It should be implemented using a `values.Duration` instead.

**Comment by wolffcm** [comment]
A `time.Duration` is implemented as `int64`. Are there a lot of places that treat a `flux.Duration` as a simple integer?  If there is a large number of such occurrences, this issue could be complicated.

**Comment by jsternberg** [comment]
There are some. It's the same work as turning `values.Duration` into a struct. This is mostly just about making sure that the two are linked instead of having to do one and then the other.

**Comment by jsternberg** [comment]
I ended up doing this as part of #2011.
