### ISSUE TITLE
Integrate libflux build into continuous integration

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2022]
The continuous integration system needs to have libflux integrated into it so `libflux` is built and used as part of the tests.

There is a small complication with this. Because the Makefiles are split up, it is a bit difficult at the moment to ensure that all of the steps run in the proper order. For details about why this happens, you can reference the paper [Recursive Makefiles considered harmful](http://aegis.sourceforge.net/auug97.pdf).

While recursive make is fine for simple workflows, it becomes impractical once a project starts needing to rely on dependencies that are produced by another Makefile. For integrating `libflux`, we are encountering that exact problem.

This issue is done when we are building `libflux` and running tests with `-tags libflux` inside of CircleCI.

**Comment by nathanielc** [comment]
Steps:

1. Refactor Makefiles to be a single top level file
2. Add New Circle CI job that runs tests with `-tags libflux`.
