### ISSUE TITLE
Integrate wasm build of libflux into continuous integration

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2023]
The wasm build needs to be done as part of continuous integration to ensure that it is working. This was broken recently and it wasn't found because continuous integration doesn't run this build.

**Comment by bthesorceror** [comment]
Currently getting this error

`cargo:warning=src/scanner/scanner.rl:2:10: fatal error: 'stdlib.h' file not found`

when trying to do a wasm build

**Comment by nathanielc** [comment]
Can we remove the dependency on the `stdlib.h` file? It seems likely we don't need for any too complex.

**Comment by jsternberg** [comment]
It looks like `stdlib.h` is used for `malloc`. While we can change to a different header file, it's unlikely that anything involving malloc will work. That will be part of the investigation of if we can just use a forward declaration for the function and it will work properly or if we have to remove the malloc stuff entirely.

**Comment by nathanielc** [comment]
Maybe we should look into something like this https://github.com/maxkl/wasm-malloc ? 

Seems like calling malloc would be a common think in WASM code that shouldn't require bringing in too much. 

Or maybe we can refactor the code to avoid any C side mallocs, not sure how feasible that is.

**Comment by jsternberg** [comment]
It looks like that implementation doesn't allow memory to be freed even though it offers a `free()` method. The `free()` method might be to just allow the memory to be used by the wasm pool again or it might just be a stub to allow code with `malloc()` to run. I think we should try to see if we can remove the need for malloc first.

I am wondering if it might be best to try refactoring the positioning stuff a bit. That might be going a bit too far for this issue, but it might be good to consider having the location information only be integer positions rather than containing an actual duplicate of the source code itself for each node.

**Comment by nathanielc** [comment]
Yeah, I think I remember that WASM doesn't support the concept of freeing memory, in that case we should probably look to refactor the position code to avoid the allocation, keeping the position info and the original string should be enough to know what the original source text was.

In that case what should we do in the short term about this issue? Is there a middle ground? Or should we just wait till we have refactored away the dependency.

**Comment by jsternberg** [comment]
If it's not needed, since it likely wasn't needed beforehand, we can just remove location information from the WASM build. I'm not sure if conditional compilation is possible, but it probably is.

It depends on how urgent the WASM build is.

**Comment by nathanielc** [comment]
We need the WASM and normal Rust builds to be consistent and the WASM build is not super urgent from my perspective so I say we just refactor it instead of using conditional compilation.

**Comment by jsternberg** [comment]
I agree on that. Since we clarified the work on this a bit more since the last time, I am going to ask the team to re-estimate the work for this since I know I want to change the estimate myself.

**Comment by affo** [comment]
I think `malloc` is required by the scanner for keeping the number of lines on a dynamic list. @wolffcm and I discussed a possible way of refactoring that out here: https://github.com/influxdata/flux/issues/1608.

After the refactor, there would be no need of `malloc`.

Should we prioritize that and set that as blocking?

**Comment by wolffcm** [comment]
I implemented the refactor that @affo mentions above, and the wasm build now succeeds on my mac laptop.

I will follow up with another PR to do the build in CI.
