### ISSUE TITLE
Design how time zones will look and function within Flux

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2024]
This issue covers designing how time zones will look and function within Flux. We know how it functions in InfluxQL and we need to determine how it will look in Flux as we may want to keep some things and do things differently in others.

This involves updating the spec with the decisions that we make upon review. Before updating the spec, it may be helpful to sketch out some ideas and post them to this issue before doing the actual write up.

TODO write up how they work in influxql for context.

**Comment by nathanielc** [comment]
DOD 

 * The SPEC is updated with the design

**Comment by jsternberg** [comment]
A short primer of how time zones work in InfluxQL just for comparison as part of prior art.

In influxql, a time zone can be specified for a query by adding `TZ('America/Chicago')` or any other time zone. This switches the windowing functionality so it will respect DST and other zone switches. DST isn't the only type of switch for offsets. Long story short, the easiest way to know what your current offset is is by using the `time.Time` class which implements all of the functionality for reading the standard time zone data files that are included on the system. Specifically, the [Zone](https://godoc.org/time#Time.Zone) method.

When a DST time switch happens, there are one of two methods that happen. When DST is started, the we lose an hour. That indicates that at 2 AM in your time zone, the hour from 2-3 AM is just skipped. This doesn't mean that there's one fewer hour in that day. The day is still composed of 24 hours. It's just that there is no 2-3 AM so there are no numbers that happen in that time period. The only time we really have to compute this difference is when the change in the zone offset is greater than the interval we are using.

The same is true going the opposite direction. When we switch from DST to normal time, it's not that there are 25 hours. It's just that 1-2 AM happens twice. Each day is still going from 12 AM to 12 AM. If you group by every 2 hours, you will still have 12-2 AM and 2-4 AM. It's just that there are 3 hours in that 12-2 AM interval because 1-2 AM happens twice.

Another aspect of InfluxQL is it is possible to specify a date with a specified offset using RFC3339 or you can write the date in `YYYY-mm-dd HH:MM:SS` and it will use the specified time zone. So you could write `2019-01-01 12:00:00` and it would use the correct offset based on the specified time zone. This is kind of a nice feature since it doesn't require any additional effort to determine the correct time and offset for a query within your own time zone. It might be nice to find a way to integrate that with Flux in some way.

That's the basic gist of it. I'm not sure how we should do it for Flux. It seems like time zones are only really needed for windowing so maybe it should just be a parameter to window. Maybe we should use an option. An option has the weakness that it's global and maybe someone wants to compute the hourly sum between values in two different time zones and compare them based on the hour. In that case, they would need to be able to use two different time zones. It seems like we should consider those in the solution.

**Comment by nathanielc** [comment]
Have you read this part of the SPEC recently https://github.com/influxdata/flux/blob/master/docs/SPEC.md#location ? It tries to answer some of these questions. 

> I am not sure if it should be an offset or the location information

It should be the location information, using just an offset is not sufficient as you have pointed out around time zone changes.

> The window function and potentially others would accept a tz parameter in addition to their current parameters to change the time zone they use.

What purpose does the `tz` parameter have on the window function specifically? Meaning why is it not sufficient to use times with timezones as part of the window boundaries?

**Comment by jsternberg** [comment]
Time zones have been implemented. Reference the documentation for how this ended up getting implemented.
