### ISSUE TITLE
Use BadExpression and BadStatement instead of BaseNode.errors

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2031]
For the Rust parser we want to simplify error reporting to use the BadExpression and BadStatement nodes instead of using the errors list on the BaseNode. This way there is a consistent way and place to check for errors on an AST.

The parser will be responsible for injecting the Bad* nodes when invalid syntax is discovered.

The ast.Check method will be responsible for producing a list of errors with their source locations from an AST.

This design change means that there is only one way to encode errors into an AST and that the AST can remain immutable when searching for errors.

**Comment by nathanielc** [comment]
This issue is specifically about how to encode errors in the AST. The current design has two methods for doing this:

1. Using BadExpression and BadStatement nodes
2. Each node has a list of errors

The point of this issue is to simplify the AST design to have a single clear way of encoding errors.

Why do we need to encode errors in the AST?

A few reasons:

* We want to be able to find multiple errors, not stop at the first error.
* We want to be able to find semantic errors in the face of syntactic errors.
* We want to provide hints/completions in the face of both semantic and syntactic errors

The design is to encode errors into the AST, this way a parser can produce a valid AST for the portions of the source code that are valid while still being able to report syntactic errors found during parsing. The AST can then be used to find multiple syntactic errors as well as perform semantic analysis to find potential semantic errors. Additionally semantic analysis can be leveraged to provide good hints/completions even in the face of syntactic errors.


Given that we want to encode errors in the AST we should have a single clearly defined mechanism for doing so.

The proposal in this issue is to remove the `errors` list from each of the nodes and make use of explicit Bad nodes that represent bad syntax. This means we need to be able to inject a Bad node in any location that a syntactic error can occur. Errors can occur at any node in an AST. So we need a corresponding Bad node for each _type_ of AST nodes.

Currently these are the _types_ of AST nodes:

* Statements - Code that can be executed but whose resulting value is unimportant
* Expressions - Code that evaluates to a value
* Assignment - Code that evaluates to a value and binds that value to a name in some context
* PropertyKey - Code that evaluates to  a key for an object property
* FunctionBody - Code that is a function's body (this is either an Expression or Statement so it may not need an explicit Bad node)
* StringExprPart - Code that evaluates to a string (this is either a string literal or an expression and likewise may not need an explicit Bad node)
* Identifier - A syntactic element that represents a valid name. Identifiers appear as both Expressions and as standalone nodes as such it will need an explicit Bad node.

Let me give a concrete example:

```
foo = () $ => 1
```

The above is obviously syntactically invalid. The proposal is to represent the above as an AST of this form:

```
     VarAssign
      /       \
 Identifier     FunctionExpr
                   /         \
            [Parameters]      BadExpr
                                    \ 
                                  IntegerLit
```

The `BadExpr` will contain the error message about the unexpected token `$`.

Here is another example that demonstrates how a bad identifier could exist:

```
import "foo"

foo.7kaa
```

The above is a `MemberExpr` because of the `.` after `foo`. But the `7kaa` isn't a valid identifier so we need to encode and capture that error. We could produce an AST like this:

```
  MemberExpr
 /        \
Identifier BadIdent
```

Then if the `BadIdent` contains the `7kaa` token we can include a helpful error message about `7kaa` not being a valid identifier. 

Thoughts?

**Comment by affo** [comment]
@nathanielc I like this approach.

I guess that's the only way to make it work with our data structure. We must have a `Bad*` for every node type, otherwise we cannot embed the bad things in our AST.

Maybe we can add a `Bad` interface, so that `ast.Check` can immediately understand if something is bad.

Anyways, I agree with your proposal. Thanks 🍾

**Comment by nathanielc** [comment]
> Unexpected behavior of invalid identifier

This makes sense now that I think about it and it has its roots in the lexer. The lexer  sees the text `a.7kaa` as the sequence of tokens `Ident, FloatLit, Ident` therefore the parser is restricted to reporting errors about the unexpected FloatLit token, and never see the `Dot` token since it was lexed as part of the float literal. 

If you change the example to something else:

```
a.#foo
```

The lexer produces tokens: `ident, dot, Illegal, ident`. In this case the parser tries to parse a member expression and can report an appropriate error as part of a member expression node.

I don't have a clear answer about how to handle the cases there the code lexes poorly such that the parser has no context as to what the user intended.
