### ISSUE TITLE
missing object properties (place)

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#2036]
I have attached the data for the following query which works:

```
import "strings"
import "influxdata/influxdb/v1"
from(bucket: "telegraf")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "usgs")
  |> filter(fn: (r) => r.type == "earthquake" and r.status == "reviewed")
  |> filter(fn: (r) => r._field == "mag" or r._field == "place")
  |> filter(fn: (r) => exists r.magType)
  |> drop(columns: ["sources","host","properties_alert"])
  |> v1.fieldsAsCols()
  |> filter(fn: (r) => exists r.place)
```

then i add the line `  |> map(fn: (r) => ({ r with start_index: strings.index(v: r.place, substr: " of ") }))` and i get the following error: `cannot add type constraint @ 12:14-12:88: type error 0:0-0:0: missing object properties (place)`
```
import "strings"
import "influxdata/influxdb/v1"
from(bucket: "telegraf")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "usgs")
  |> filter(fn: (r) => r.type == "earthquake" and r.status == "reviewed")
  |> filter(fn: (r) => r._field == "mag" or r._field == "place")
  |> filter(fn: (r) => exists r.magType)
  |> drop(columns: ["sources","host","properties_alert"])
  |> v1.fieldsAsCols()
  |> filter(fn: (r) => exists r.place)
  |> map(fn: (r) => ({ r with start_index: strings.index(v: r.place, substr: " of ") }))
```

[2019-10-21-11-32_chronograf_data.csv.zip](https://github.com/influxdata/flux/files/3752376/2019-10-21-11-32_chronograf_data.csv.zip)

**Comment by affo** [comment]
@russorat can you try adding a filter `exists r.place`? Does that fix your issue?

Sorry for the "meaningless" error message.

**Comment by russorat** [comment]
@affo it’s already there

**Comment by affo** [comment]
Yep, you are right. I am sorry.

@jlapacik this is definitely a bug in the `compiler`.

**Comment by sbengo** [comment]
Hi, I'm facing this issue aswell

I have a tag that is not required in all series and I need to do a `pivot` over field and by all available tags.

As the column is required to be in the table  in `pivot` function, I tried to use the `if exists r.mycolumn then r.mycolumn else ''` but it is giving the error ath `r.mycolumn` doesn't exist on the `then` statement

There are some plans to fix it in short term?

Thanks,
Regards!

**Comment by jgarciadelanoceda** [comment]
I think that I have the same issue as well I have the following query (Traffic in network interfaces):

> from(bucket: "SNMP/autogen")
	|> range(start: v.timeRangeStart, stop:v.timeRangeStop)
	|> filter(fn: (r) => r._measurement == "traffic" and (r._field == "ifHCInOctets" or r._field == "ifInDiscards" or r._field == "ifHCOutOctets" or r._field == "ifOutDiscards" or r._field == "ifInErrors" or r._field == "ifOutErrors") and r.host == "${host}" and r.interface == "${interface}")
	|> derivative(nonNegative:true)
	|> aggregateWindow(every:v.windowPeriod, fn:mean)
	|> pivot(rowKey:["_time","host","interface"], columnKey: ["_field"], valueColumn: "_value")
	|> map(fn: (r) => ({ _time: r._time,ifHCInOctets:r.ifHCInOctets,ifHCOutOctets:r.ifHCOutOctets,ifInErrors:if not exists r.ifInErrors or r.ifInErrors == 0.0 then 0.0 else r.ifInErrors,ifOutErrors:if not exists r.ifOutErrors or r.ifOutErrors == 0.0 then 0.0 else r.ifOutErrors,InDiscardPercentage:if not exists r.ifHCInOctets or r.ifHCInOctets == 0.0 or not exists r.ifInDiscards  then 0.0 else r.ifInDiscards/r.ifHCInOctets,OutDiscardPercentage:if not exists r.ifHCOutOctets or  r.ifHCOutOctets == 0.0 or not exists r.ifOutDiscards  then 0.0 else r.ifOutDiscards/r.ifHCOutOctets}))

Where host and interface are variables from Grafana. I found that the ifInDiscards/ifOutDiscards/ifInErrors/ifOutErrors only show in a query when the interface is a logic one (That can be filtered), but I would like to show the percentages when they are available. I am not capable of doing it and I do not found an easy workaround
