### ISSUE TITLE
Basic Syntax in README not matching results

### ISSUE THREAD

**Issue by nisley** [influxdata/flux#2039]
```
> math.pow(base: 5, exponent: 3)
Error: type error 1:1-1:31: function does not take a parameter "base", required params (x, y)
> math.pow(x: 5, y: 3)
Error: type error 1:1-1:21: float != int
> math.pow(x: 5.0, y: 3.0)
125
```

There's a good chance this error is expected given the note that the REPL cannot connect to InfluxDB yet:
```
> import "influxdb"
Error: type error 1:1-1:18: unknown import path: "influxdb"
```

**Comment by nathanielc** [comment]
Thanks, both are errors we should fix. The import should be `influxdata/influxdb` and the `pow` should be `math.pow(x: 5.0, y: 3.0)`

**Comment by jsternberg** [comment]
Should we remove the influxdb import? It isn't runnable within the `flux repl` right now, but it does seem important. I can also replace it with the sql one which does run in native flux.
