### ISSUE TITLE
Make duration add operation month-aware

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2044]
The duration add operation in `values/time.go` needs to be made month-aware. At the moment, any duration operation will treat a month as 30 days and the context of the time will not be used. This issue is about making the `(values.Time).Add(d values.Duration)` operation aware of which month it is in and following the spec for the rules regarding edge cases.

The easiest way to do this is likely to use `time.Time` values which are date-aware.

**Comment by jsternberg** [comment]
This will possibly require refactoring the `values.Time` so that it retains certain information. In particular, if the time is January 31 and we add a month, that becomes February 28. But then for window, we likely want it so adding another month goes back to March 31. It seems the spec is ambiguous on repeated addition of durations to a time so I think we might need to make that explicit as I was hoping to use the `Add` method for the intervals.

**Comment by nathanielc** [comment]
The `values.Time` does not need to change, we will not keep state on it from previous operations.

In order to implement the `window` `every` parameter we will need to use integer multiples of the `every` values to determine window boundaries.

Given a normal case:

`window(every: 1mo, period: 10d, offset: 1 Jan)`

We start at Jan 1st

Window boundaries are:
```
[Jan 1st, Jan 11th) = [Jan 1 + 0 * 1mo, Jan 1 1 0 * 1mo + 10d)
[Feb 1st, Feb 11th) =  [Jan 1 + 1 * 1mo, Jan 31 + 1 * 1mo + 10d)
[March 1st, March 11th)=  [Jan 1 + 2 * 1mo, Jan 1 + 2 * 1mo + 10d)
```


Given a edge case see how it behaves:

`window(every: 1mo, period: 10d, offset: 31 Jan)`

We start at Jan 31st

Window boundaries are:
```
[Jan 31st, Feb 10th) = [Jan 31 + 0 * 1mo, Jan 31 + 0 * 1mo + 10d)
[Feb 28th, Mar 10th) =  [Jan 31 + 1 * 1mo, Jan 31 + 1 * 1mo + 10d)
[March 31st, April 10th)=  [Jan 31 + 2 * 1mo, Jan 31 + 2 * 1mo + 10d)
```

**Comment by jsternberg** [comment]
I took a look and window only seems to require `Add` and `Mul` so I'm going to update the issue to just about `Add` and then we'll figure out what else we need to make window work by creating new issues.

The other functions need to support this same interface too, but they aren't nearly important. As an example, `Sub` is just very unlikely to be used for window and month support isn't frankly going to matter much. It seems to be only used when computing the `time.Duration` of an `execute.Bounds` structure which isn't going to be month-aware anyway.

**Comment by nathanielc** [comment]
DOD

* Both `Add` and the Window behavior follow the examples here https://github.com/influxdata/flux/issues/2044#issuecomment-546405385
* Unit tests for `Add` and `Mul`
* Unit tests for windows interval function behavior
* Flux end to end tests for windowing by calendar durations

**Comment by jsternberg** [comment]
I think the relevant functions to look at are here: https://github.com/influxdata/flux/blob/master/execute/window.go#L42
