### ISSUE TITLE
Enable  joins to operate on fuzzy time values 

### ISSUE THREAD

**Issue by sanderson** [influxdata/flux#2050]
Joining on time-typed columns often leaves out points because time values a within ns or ms of each other, but not exact matches. We should add a `tolerance` parameter to `join()` that defines how far apart time values can be and still be considered equal. This would align with the Kapacitor `join` node's [`tolerance` property](https://docs.influxdata.com/kapacitor/v1.5/nodes/join_node/#tolerance).

```
join(
  tables: {t1: table1, t2: table2},
  on: ["_time", "_field"],
  tolerance: 1s
)
```

**Comment by sanderson** [comment]
@nathanielc Actually, we already have `date.truncate()` in the date package, so this issue probably can be closed.

**Comment by nathanielc** [comment]
@sanderson Wonderful, I had forgotten :) Do you think a helper function is appropriate here?

**Comment by sanderson** [comment]
Looks like it already exists 😄: `truncateTimeColumn()`

https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/truncatetimecolumn/

**Comment by nathanielc** [comment]
Wonderful Glad you know Flux better than me!!

**Comment by mkarlesky** [comment]
@nathanielc & @sanderson I don't believe `truncateTimeColumn()` actually accomplishes the original intent of this issue. As I understand it, time truncation is not the same as Kapacitor's Join node's `.tolerance()` property. `.tolerance()` could work on any arbitrary duration. Relying on time truncation for a Flux `join()` limits the usefulness of the approach discussed here to only unitary millisecond, second, minute, hour, etc. boundaries.

All the examples in the Flux documentation or in InfluxData blog posts and articles I am aware of that demonstrate a `join()` on `_time` have the convenience of two streams of data having perfectly aligned timestamps. That makes `join()` on `_time` easy. However, I believe this breaks down with an entirely real world case of two data streams from un-synchronized sensors for which we want to perform cross-measurement math (e.g. combining air temperature and relative humidity into VPD). This was not a problem with `join().tolerance()` in a TICKScript. I don't see how a Flux developer could easily truncate time to produce cross-measurement calculation results on 30 second boundaries.

The only robust approach I can see is using `aggregateWindow(every: <duration>, fn:mean)` to resample the two streams to be joined before then `join()`ing on the resampled `_time`.

Am I mistaken?
