### ISSUE TITLE
Rust: checkfmt

### ISSUE THREAD

**Issue by affo** [influxdata/flux#2055]
Extend `etc/checkfmt.sh` to include an equivalent check for the rust codebase.

**Comment by nathanielc** [comment]
I found this when reading up on rustfmt https://github.com/rust-lang/rustfmt#checking-style-on-a-ci-server

**Comment by affo** [comment]
@nathanielc `cargo fmt --all -- --check` woah, even better! Thank you!

**Comment by nathanielc** [comment]
Heads up, we might need to ignore the flat buffers if they do not pass on their own.
