### ISSUE TITLE
Document Flux

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/flux#2058]
This is an epic to track adding and updating docs that focus on the process of writing Flux and adding to Flux. This epic can also include documenting concepts that will help developers understand how Flux works.

**Comment by fchikwekwe** [comment]
Feel free to suggest more needed guides below and we can update the issue as needed.

**Comment by nisley** [comment]
IMO, these are the short crib notes that might be good for the README:

Flux is currently available in InfluxDB 1.7 and 2.0 or through the REPL that can be compiled from this repository.

To compile the REPL, use the following command:

```
$ go build ./cmd/flux
$ ./flux repl
```

If you create or change any flux functions, you will need to rebuild the stdlib:
```
$ go generate ./stdlib
```

Your new Flux's code should be formatted to coexist nicely with the existing codebase with go fmt.  For example, if you add code to stdlib/universe:
```
$ go fmt ./stdlib/universe/
```

Don't forget to add your tests and make sure they work. Here is an example showing how to run the tests for the stdlib/universe package:
```
$ go test ./stdlib/universe/
```

**Comment by fchikwekwe** [comment]
Those are great additions Nate! Thanks.

**Comment by fchikwekwe** [comment]
I'm changing the scope of this epic to encompass all documents that we want to write for flux.
