### ISSUE TITLE
Make spec more explicit about what happens when adding a duration with months to a time multiple times

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2062]
Make the spec more explicit about what happens when a duration, such as a month, is added to a time multiple times.

> When months are added to a date times and the resulting date is past the end of the month, the day is rolled back to the last day of the month.

In particular, I was hoping that I would be able to use the `Add` method to generate the intervals for window. But the spec isn't explicit about what happens if I do a 1 month interval starting on January 31. Will the interval start on January 31, February 28, March 31, April 30, etc or will it be January 31, February 28, March 28, April 28, etc.

**Comment by jsternberg** [comment]
cc @nathanielc

**Comment by nathanielc** [comment]
We discusses this a bit in https://github.com/influxdata/flux/issues/2044 but I'll repeat here for clarity.

A `time + duration` operation is always deterministic and does not contain any history about any previous operations. This means that `Feb 28th + 1mo` is always `March 28th` 

Possible xxamples to add to the spec to make it clear.
```
2018-01-31T00:00:00Z + 1mo + 1mo   // 2018-03-28T00:00:00Z
2018-01-31T00:00:00Z + 2mo         // 2018-03-31T00:00:00Z
2018-01-31T00:00:00Z + (1mo + 1mo) // 2018-03-31T00:00:00Z
```

**Comment by fchikwekwe** [comment]
Is this issue just about making a change to how this behavior is documented in the SPEC? Or is implementing the behavior also part of the change?

**Comment by fchikwekwe** [comment]
And if there is implementation involved here, is this issue scoped to make changes to the `Add` function, or are there other changes necessary?

**Comment by jsternberg** [comment]
It looks like this is going to be done as part of #2067 so I'm just going to close this.

@fchikwekwe the original purpose of this was just to update the spec, but it ended up getting done as part of the actual issue.
