### ISSUE TITLE
Make the interpreter read in duration values with months

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2069]
The flux interpreter will read in duration values and translate them into a `time.Duration` before converting it into a `values.Duration`. This loses the special units such as months.

This issue is about making it so the duration units are part of the semantic node. This can be complicated because the `semantic` package cannot depend on the `values` package so there might need to be some refactoring involved with this.

**Comment by nathanielc** [comment]
A simple solution is to update the semantic Duration node to use the same structure as the AST. i.e. a list of ints with units. The semantic analysis doesn't need to know the value as a values.Duration nor a time.Duration.  So we would just have to update the semantic.Duration node and update the interpreter to understand the new semantic duration node format to create a values.Duration.

**Comment by jsternberg** [comment]
Yea, I agree. The only caveat is that, for whatever reason, there's a section of the code that turns a `values.Duration` into a `semantic.DurationLiteral`. But it's easy enough to just read it in as its components similar to what the `String()` method does. In fact, the `String()` method should likely be changed to share code with that.
