### ISSUE TITLE
RFC3339Nano parsing issue

### ISSUE THREAD

**Issue by kelwang** [influxdata/flux#2079]
according to 
https://github.com/influxdata/flux/blob/7ad7e2ba275c45e21a5109766b36c8848e9a4e0f/internal/scanner/scanner.rl#L24

`2006-01-02T15:04:05.999999999Z07:00` won't be parsed correctly

**Comment by nathanielc** [comment]
@kelwang That time format is invalid, the `Z` means that the offset is `0` so you can't specify both a `Z` and an offset. See https://play.golang.org/p/VMHfJSgua_c 

What offset do you expect that time to have?
