### ISSUE TITLE
Refactor position information from the AST

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2082]
The AST contains position information on each of the AST nodes. This includes a copy of the source that the AST node references. This causes us an issue with the Rust parser where it requires us to call `malloc()` to allocate a string so that we can copy the text into each of the base nodes. WASM doesn't have a functional malloc implementation so this isn't something that we can use.

Instead of our current position information, we should refactor the position information so that it only contains offsets for where the source starts and stops. The user who initiated the parsing will have the original source code anyway and we can ensure that the original source is part of the returned AST if we need to in one location instead of spread out between each AST node. If we use simple offsets for position information, then this is a simple copyable structure of only integers which means malloc wouldn't be needed and it also means the AST representation would be more compact.

**Comment by nathanielc** [comment]
The malloc has been removed from the Rust parser logic, closing
