### ISSUE TITLE
Update `make release` to check for local/remote consistency

### ISSUE THREAD

**Issue by affo** [influxdata/flux#2084]
I was able to do this:

 * Run `git pull origin master` not `git pull` nor `git fetch`
 * Run `make release`
 * `changelog` doesn't know the last tag because it wasn't fetched at all. Now, suppose that the last remote tag is vX, then `changelog` will create vX locally.
 * Remembered to fetch. Git now sees that I have vX locally and does not care about the remote/local inconsistency.
 * Run `make release` again. Now `changelog` create vY in the same place as vX producing an empty changelog (vY should be vX.1).

To solve this we should `make release` `git pull` before tagging to ensure that local is in sync with remote.

**Comment by affo** [comment]
@nathanielc erroring seems a better approach 👍

**Comment by fchikwekwe** [comment]
Trying to get more context on this: is there a way to know which commit we need to checkout and compare against remote?

**Comment by fchikwekwe** [comment]
I'm also not sure what checking if local and remote are in sync would look like. Right now I'm thinking that this would be a change to `release.sh` to compare the two commits before making the release and commiting it.
