### ISSUE TITLE
Provide static pre-checking without full eval

### ISSUE THREAD

**Issue by gavincabbage** [influxdata/flux#2085]
Provide functionality to run static checks on flux scripts without full evaluation for use during task creating, etc.

# Background

Originally, InfluxDB 2.0 used `EvalAST` to extract task options from a flux script when creating a new task. This evaluation was problematic for a number of reasons, including issues with dynamic queries and script dependencies (see [influxdb#15583](https://github.com/influxdata/influxdb/issues/15583) for example).

#2054 added the `EvalOptions` function, which strips any statement besides an option before evaluation. This solved the issues above, but resulted in a regression in the pre-checks performed on a flux script when a new task is created. These checks are important to provide fast feedback when creating a task, rather than waiting for an error during task execution.

The work on Algorithm W should allow more robust static pre-checks to be possible, without evaluating the AST. This functionality should be exposed after the Algorithm W work is complete to allow InfluxDB to perform these static checks on task creation.

**Comment by jlapacik** [comment]
This issue will be closed out as part of the follow on epic #1943 to algorithm W.

**Comment by gavincabbage** [comment]
A small update: The regression described in the original issue has been reverted for now. We will still want to consume the output of this issue in InfluxDB, however.
