### ISSUE TITLE
Use consistent language for Row/Records/Objects

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2088]
Currently the concept of a object (a value with a set of key value pairs) has several names:

* row - the name used because it represents a single row of a Flux table
* record - the name used in the literature to discuss a value of this type
* object - comes from javascript and other places

We should consolidate on a single name. My recommendation is to use record. It makes it a different name from the javascript object, which is good since it behaves differently in some ways. It is also a familiar name for an entity within a table as well as a common name when talking about data. 

We need to update the SPEC and code to all use the same name.

**Comment by nathanielc** [comment]
Since creating this issue I have also received feedback that `row` is also confusing as it implies to much similarity with SQL like systems. At this point I am convinced we should use `record` for the name.

**Comment by sanderson** [comment]
We will need to do this in all the user-facing documentation as well.

**Comment by nathanielc** [comment]
https://github.com/influxdata/flux/pull/3111 Does the work to rename the Rust parser and type system code to use Record.

That leaves the Go code, the Flux SPEC and the user-facing docs.

**Comment by nathanielc** [comment]
This PR updates the SPEC https://github.com/influxdata/flux/pull/3112
