### ISSUE TITLE
Write FlatBuffers schema for semantic graph

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#2089]
This is the analogous issue for the AST serialization, #2003.  Mostly this issue can follow the example there.

Definition of done:
- a `semantic.fbs` schema file lives somewhere in `flux/semantic/internal/`
- Generated code for Rust and Go is committed, with basic tests to ensure it compiles.
- Invocation of `flatc` should be driven from Makefile.

**Comment by wolffcm** [comment]
Note this does *not* include writing a FlatBuffers schema for the Flux types produced by Rust type inference, that will be done as a separate issue.

**Comment by fchikwekwe** [comment]
Should the `semantic.fbs` file actually live in `flux/semantic`? I'm not seeing a `flux/semantic/internal` directory. Or should I create that?

**Comment by wolffcm** [comment]
I put the `ast.fbs` in `flux/ast` and then created a directory `flux/ast/internal/fbast` for the generated code.  It probably makes sense to follow a similar pattern for the semantic graph too?

The reason we put `internal` in the package path is because it makes it so that package is not accessible from outside the module (e.g., it would not be possible to call the AST flatbuffers generated code from the `influxdb` repo)
