### ISSUE TITLE
stddev returns NaN when using millisecond duration in window

### ISSUE THREAD

**Issue by chnn** [influxdata/flux#209]
Every `_value` returned by the following query is `NaN`:

```
from(bucket: "telegraf/autogen")
  |> range(start: -30m)
  |> filter(fn: (r) => r._measurement == "mem" and (r._field == "active"))
  |> window(every: 6000ms)
  |> stddev()
```

However, if I used `1m` as the duration instead in the `window` function, it returns data OK:

```
from(bucket: "telegraf/autogen")
  |> range(start: -30m)
  |> filter(fn: (r) => r._measurement == "mem" and (r._field == "active"))
  |> window(every: 1m)
  |> stddev()
```

**Comment by nathanielc** [comment]
@chnn This is expected behavior, using such a small window means that not enough data existed within a window to compute a standard deviation. The standard deviation needs at least 2 records to produce a value, otherwise it returns NaN.
