### ISSUE TITLE
Translate Rust semantic graph into FlatBuffers representation

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#2090]
This is the analogous issue for #2004.  This can largely follow the example there.

DOD:
- There is a new module under `semantic` called `flatbuffers` that has a `serialize` method.
- Tests exist showing that each kind of semantic graph node is correctly translated into its FlatBuffers representation.

**Comment by nathanielc** [comment]
Note this does not include the monotype information on the semantic structs. See #2091 for the sequencing plan, this issue is part of Phase 1.
