### ISSUE TITLE
Proposal use epoch to define how windows align

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2093]
Users want to align their windows with various calendar concepts:

See this example of how we think this could work:

```
epoch  = findEpoch(
    month: January,
    monthDay: 1,
    weekday: Sunday
)


// quarters starting on Jan 1st,  April 1st, July 1st and Oct 1st
intervals(every: 3mo, period: 3mo, epoch: epoch, offset: 0) 

 // half years starting on Jan 1st and July 1st
intervals(every: 6mo, period: 6mo, epoch: epoch, offset: 0)

 // weeks starting on Sunday
intervals(every: 1w, period: 1w, epoch: epoch, offset: 0)
 // weeks starting on Monday, note the offset can be used to make adjustments to the epoch
intervals(every: 1w, period: 1w, epoch: epoch, offset: 1d)

// change the epoch
epoch  = findEpoch(
    month: March,
    monthDay: 3,
    weekday: Monday
)

 // quarters starting on March 3rd, June 3rd, Sep 3rd and Dec 3rd
intervals(every: 3mo, period: 3mo, epoch: epoch, offset: 0)
 // half years starting on March 3rd and Sep 3rd
intervals(every: 6mo, period: 6mo, epoch: epoch, offset: 0)

// change the epoch
epoch  = findEpoch(
    month: January,
    monthDay: 1,
    weekday: Sunday
)

 // weeks starting on Sunday
intervals(every: 1w, period: 1w, epoch: epoch, offset: 0)
 // weeks starting on Monday
intervals(every: 1w, period: 1w, epoch: epoch, offset: 1d)
 // weeks starting on Saturday
intervals(every: 1w, period: 1w, epoch: epoch, offset:  -1d)
```

The idea here is that users can define an `epoch` which has the characteristics they want, i.e the starting month, starting day of the month and starting week day.

We create an option named `epoch` which is the alignment date for intervals and use a helper function `findEpoch` to define it. Then we update the `interval` function to have four parameters:

* every - how often each interval starts
* period - how long each interval lasts
* epoch - the alignment date to use for the intervals, this defaults to the global `epoch` option.
* offset - optional extra offset from the epoch so alignment can easily be changed on a case be case bases.

The start of an interval is computed by finding the a date that is an `every` multiple of  the `epoch +offset`. This way if you set your epoch to be on a Monday, then all week intervals are aligned to start on Mondays. If you set your epoch to be June, then all year/month intervals are aligned to start on June.

The default epoch will be defined as:

```
option date.epoch = date.findEpoch(
    month: date.January,
    monthDay: 1,
    weekday: date.Monday, // according to ISO 8601
)
```

So a final complete example:

```
import "date"

// US federal government uses a fiscal year of Oct 1 to Sep 30th of the following year.
// In America Sunday is the start of the week
option date.epoch = date.findEpoch(
    month: date.October,
    monthDay: 1,
    weekday: date.Sunday
)

from(bucket: "expenses"
    |> range(start: -10y)
    |> filter(fn: (r) => ...)
    |> aggregateWindow(every: 1y, fn: sum) // sum up expenses by the fiscal year
```

The names of the arguments to findEpoch and the name of the function itself are up for debate.

**Comment by jsternberg** [comment]
I would say replace `findEpoch` with `defineEpoch`. I just like it more as I feel like you are defining what properties the epoch has rather than saying, "I want to find this specific date."

 But, I was thinking about it and I'm not certain if we can do this as it might hide the implementation too much. As a reason why it might be important, when you group by week, it might be harder to define why grouping by a week results in the interval starting on a certain day in a certain year if there isn't a clear date to point them at and say "here's the math". If we force the user to specify that the epoch is a specific date, then it's much more in your face. Automatically calculating the epoch works for if we just want weeks to start on a sunday or monday, but it doesn't explain why a specific day is the beginning of the window when grouping by weeks.

Although maybe this isn't a big deal. I haven't thought about it enough. I like `defineEpoch` better though.

**Comment by wolffcm** [comment]
I find the `weekday` parameter to be confusing...  Clearly the weekday named in the call to `findEpoch` might not match the given date.  So is the idea that we only apply the `weekday` part of the user-supplied epoch when defining intervals based on weeks?

**Comment by nathanielc** [comment]
@wolffcm  The parameters to `findEpoch` don't specify a given date, specifically the year is missing. The `findEpoch` function will search for a date with the specified properties. It will do this by searching for a year that has the correct weekday. That should be 7 years away from any date in a worst case scenario.  The point  is to hide this complexity from the user. 

The exact date chosen for the epoch dictates how intervals will align with it. This effects the day of the week as well as the month and day of the month. For example the unix epoch starts on a Thursday (https://play.golang.org/p/tDnW5UnYhn6) and so if we were to use that date as the epoch then weeks would start on Thursday which almost no one wants. 

These things are not immediately obvious when you pick a specific date. This is why we want to have a helper method to pick the date for you. Basically the user can think about the three properties they care about and then Flux takes care of the rest. 

Does that help make it more clear? 

>  So is the idea that we only apply the weekday part of the user-supplied epoch when defining intervals based on weeks?

No, the epoch is just a date. Once it is set the intervals function has no visibility into the values given to the `findEpoch` function. Meaning that this is perfectly valid.

```
option date.epoch = 1973-10-01T00:00:00Z // 1973 has a Monday on Oct 1st


from(bucket: "expenses"
    |> range(start: -10y)
    |> filter(fn: (r) => ...)
    |> aggregateWindow(every: 1y, fn: sum) // sum up expenses by the fiscal year
```

Simple search to find the right date manually https://play.golang.org/p/3D50ZJnWOKh. The `findEpoch` will be similar function.

Finally the way we plan on this working is be defining truncate time method in terms of an arbitrary epoch. Something like this for our values.Time type:

```
func (t Time) Truncate(d Duration, epoch Time) {
   // psuedo code
   remainder := (epoch - t) % duration
   return t - remainder
}
```

I probably have the above code wrong but the idea is that the `epoch` is an argument to the truncate method allowing for efficient computation of truncated times. Truncating a time is essentially the operation to find the beginning of an interval which contains the time. Note this is in contrast to the Go time library that always uses the hard-coded unix epoch time for truncation.

**Comment by wolffcm** [comment]
Ah, this makes sense to me.  Thanks for clarifying.

I wonder if it will be confusing to users when to use `offset` and when to specify the characteristics of the epoch they want to use.  I don't really see how it could be made simpler though.

**Comment by nathanielc** [comment]
@wolffcm My expectation is that most users will not change the `epoch`. With it being a global option and once we have packages, I expect it will become and org wide setting (i.e. an org creates a custom package with all of their specific option settings). As  a result most users will use offset, specially if we have a good default epoch.

FWIW I expect this to be the default:

```
option date.epoch = date.findEpoch(
    month: date.January,
    monthDay: 1,
    weekday: date.Monday, // according to ISO 8601
)
```
