### ISSUE TITLE
import packages for type inference

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#2095]
Flux has import statements of the form:

    import foo "path/to/package/foo"

for importing (making visible) and namespacing the identifiers defined in another package.

When inferring the types of a file or package with import statements, we need a way to retrieve these external types when they are referenced in a flux program. This means that the `infer` method for files and packages need to take some "importer" object as input. Since flux packages are modeled as records, this importer should associate package paths to record types. When we see an import statement, we should take the record type for that particular path and add it to the type environment.

This issue should also include a method for creating a package, i.e a record type, from a semantic package node.

DOD:
1. Tests that demonstrate type inference for programs with import statements.
2. Tests that create a record type from a semantic package node.

**Comment by nathanielc** [comment]
See the Go code for reference https://github.com/influxdata/flux/blob/master/semantic/package.go
https://github.com/influxdata/flux/blob/master/semantic/constraints.go#L34
