### ISSUE TITLE
Rust: follow guidelines for `rustdoc`

### ISSUE THREAD

**Issue by affo** [influxdata/flux#2099]
These are the guidelines: https://doc.rust-lang.org/1.30.0/book/first-edition/documentation.html#documenting-source-code.

DOD: every module has docs in the line with those principles.  
An initial step would be to simply use `///` instead of `//` for public-exposed objects.

In `semantic::walk` I also used examples. Those are run when you run `cargo test`. This is really useful to make sure your examples work and are up-to-date with the codebase.

This is the result of `cargo doc --open`:

![image.png](https://images.zenhubusercontent.com/5d14e0dd11232d5ce5b3f3a1/6717823e-e27d-4466-9082-e10352adafe3)

Cool, isn't it?

**Comment by nathanielc** [comment]
@affo Does rustfmt have a setting for validating types have comments ? Maybe something in here https://rust-lang.github.io/rustfmt/? Or maybe its another linter that would check that for us and not rustfmt?

**Comment by affo** [comment]
@nathanielc it seems we can even make it file on `build` with `#[deny(missing_docs)]` (https://doc.rust-lang.org/1.9.0/book/documentation.html#missing-documentation).

I put `#![deny(missing_docs)]` as the first line in the root `lib.rs` and compilation fails with (for example):

```
error: missing documentation for a struct field
   --> src/semantic/nodes.rs:455:5
    |
455 |     pub expression: Expression,
    |   
```

You can also manually skip some specific types by preceding them with `#[allow(missing_docs)]` or hide their doc with `#[doc(hidden)]`.

I found a rust project in which they were converting a non documented project to a documented one. They opted to gradually add `#![deny(missing_docs)]` on multiple modules and then gradually bring this to the root: https://github.com/diesel-rs/diesel/issues/563.

We could follow the same approach.

**Comment by nathanielc** [comment]
Decided strategy is to deny missing docs for the whole crate, then for each module allow missing docs until we have them all fixed up. 

DOD:

* Build will fail if docs are missing
* Make it so that it fails to build only in strict mode so that it only warns when developing

See `strict` feature added by @jsternberg for how to achieve the warn vs fail behavior.
