### ISSUE TITLE
Use Rust semantic analysis

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2116]
Once #2090 and #2091 are complete we will have the ability to use the Rust parser + analyzer to create semantic graph (without monotype information). Once those are complete we want to pass that semantic graph into the Go type inference logic and show that all integration tests are still passing.

This will  include updating the libflux C header file to expose the semantic flat buffers.

DOD:

 * The integration tests pass while using Rust bits to parse and analyze Flux source code

**Comment by fchikwekwe** [comment]
Go Type intereference logic has been removed, so this issue is no longer relevant.
