### ISSUE TITLE
Write FlatBuffers schema for Rust semantic MonoType

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2118]
The work in #2089 is ignoring the serialization of semantic::types::MonoType as FlatBuffers. This issue is to finish up that work.  We need to update the semantic FlatBuffer schema to include the monotype information.

**Comment by wolffcm** [comment]
If we plan on using flatbuffers types on their own for importing identifer type mappings into the type environment, and also to annotate expressions in the semantic graph, then it would be good to have a separate schema file for just the types.

Then we can use `include "types.fbs";` inside of `semantic.fbs` to use the type definitions.

**Comment by jlapacik** [comment]
@wolffcm agreed.
