### ISSUE TITLE
Refactor Interpreter to use the FlatBuffer representation of semantic graph

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2120]
Once #2117 is complete we can start to work of removing the old Go semantic nodes. This issue is about replacing the those types for the interpreter Go package.

This will likely leak a bit into the execute Spec and the compiler. In order to contain the refactor we should use the ability to translate flatbuffers into their Go types before handing off to those other packages. 

DOD:

* The interpreter test cases pass while using Rust for parsing, analyzing and type checking Flux source code

**Comment by jlapacik** [comment]
I propose we keep the Go semantic graph around until we have fully integrated Rust type inference. If we annotate the Go semantic nodes with their types, then the refactor to the interpreter is relatively simple.

First we can completely remove the `types` and `polytypes` field from the `Interpreter` struct: 
https://github.com/influxdata/flux/blob/master/interpreter/interpreter.go#L16-L22

Next we can remove the type inference calculation from the interpreter as implemented here:
https://github.com/influxdata/flux/blob/master/interpreter/interpreter.go#L40-L54

And finally we must update all the places in the interpreter where we use the old `MonoType` and `PolyType` interfaces.

**Comment by nathanielc** [comment]
This is complete inside the `use/feat-algo-w` branch which is now green. Work left on the branch has been broken out into its own issues. Closing.
