### ISSUE TITLE
Be able to run test against a flux file directly

### ISSUE THREAD

**Issue by kelwang** [influxdata/flux#2128]
Create a command to run flux test directly.  like `flux test ./...` to run tests against a package.

Create a way to run a test on a particular func. like `flux test ./... -run monitor_state_changes`

<img width="808" alt="Screen Shot 2019-11-11 at 11 51 23 AM" src="https://user-images.githubusercontent.com/8237958/68605168-f408e900-0479-11ea-9cac-81e5db2f63ad.png">

Ideally, a flux IDE should be able to run a test, like other languages.
 
<img width="561" alt="Screen Shot 2019-11-11 at 11 52 51 AM" src="https://user-images.githubusercontent.com/8237958/68605196-fc612400-0479-11ea-846a-37809c604d4c.png">

**Comment by jademcgough** [comment]
I'm skeptical of how useful unit testing would be for flux when the correctness of a script is entirely dependent on the environment it's run in. It's a query language, not a general purpose programming language.
