### ISSUE TITLE
Remove fieldFn and tagColumns parameters from to()

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#213]
Now that we have a concrete definition of how the Flux type system and type inference work we need to redefine how the fieldFn in the `to` function works since it uses an incompatible type.

The current signature is something like this:

    fieldFn: (r) => ({[r._field]: r._value})

But structural polymorphism does not allow for object keys to be expressions. Therefore we need to change the function return type to use static keys. Maybe something like this:

    fieldFn: (r) => [{field: r._field, value: r._value}]

Using a list allows for multiple fields like before.

There may be other type signatures as well, this was just a simple quick solution.

**Comment by jlapacik** [comment]
I think we should simplify the definition and type signature of the `to` function. I don't think `to` should be used to transform or shape the data in any way before writing it. That should not be the responsibility of `to`. Instead I think it should just write out data that it receives assuming that data satisfies some constraints. And those constraints should be expressed via the type signature. In particular I believe `to` should have the following type:

```
forall [a, r] where r:Rec (tables: [ {_time: time | _field: str | _value: a | r } ], ... ) -> [ {_time: time | _field: str | _value: a | r } ]
```
In words this means that `to` is a function with a `tables` parameter whose type is a list of records that must have fields `_time` of type _time_, `_field` of type _string_, and `_value` of any type. It returns a list of records of the same type.

Defining `to` in this way gives us the ability to catch more errors at compile time if we infer that the user is passing data of the wrong type into `to`.

**Comment by wolffcm** [comment]
To summarize what @nathanielc said on Slack and in addition to what @jlapacik said above:
- the `fieldFn` parameter goes away
- the `tagColumns` parameter goes away
- Any columns that are of type *string* that are not `_value`, or `_field` become tag keys
- Columns besides `_value` and `_field` that are not of type *string*... throw an error I guess?
- Users use the normal `drop`, `keep`, `rename`, etc schema functions preceding `to()` to get the tables into the shape they want.

**Comment by nathanielc** [comment]
> Columns besides _value and _field that are not of type string... throw an error I guess?

Yes, an error makes sense to me at first pass.

**Comment by jlapacik** [comment]
> Columns besides _value and _field that are not of type string... throw an error I guess?

These errors can be caught at compile time by updating the type signature of `to`:
```
forall [a, r] where r:StrRec (tables: [ {_time: time | _field: str | _value: a | r } ], ... ) -> [ {_time: time | _field: str | _value: a | r } ]
```

The only difference here is that the type variable `r` is of kind `StrRec`. The `StrRec` kind describes records whose properties are all of type `string`.

**Comment by wolffcm** [comment]
In addition to `_field`, there are also the columns `_measurement` and `_time`. The current implementation of `to()` also has `measurementColumn` and `timeColumn` parameters (although the former is not documented in the SPEC).

Following this design approach to its logical conclusion, those parameters should also be removed, and it will be up to the user to use keep/drop/rename/duplicate to create those columns as they need.

**Comment by nathanielc** [comment]
Closing this issue, We built an `experimental.to` function that has the API we want long term. The existing `to` function will be deprecated and eventually retired.
