### ISSUE TITLE
Optimize pivot for memory usage

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2133]
The pivot transformation, like most of the transformations, has a bad pattern of memory access. The reason for this is because it uses the default table builder which doesn't have a convenient way to reserve memory. It has a `GrowXXX` method for growing a column to a length, but there's no way to reserve a certain amount of memory when you know the potential size of the input.

This issue is to optimize pivot. This will likely involve a few things.

1. The table that is constructed should directly construct arrow array buffers. This means it should probably not use the default table builder.
2. It should perform the pivot when it has the available data. This likely means it buffers all of the data in memory and then performs a pivot.

**Comment by jlapacik** [comment]
To clarify, you are proposing that pivot consumes the entire stream, and then allocates memory for the table builder at once to avoid the constant reallocations that occur right now as pivot dynamically grows its columns?

**Comment by jsternberg** [comment]
Correct. Except that right now the pivot algorithm also uses random access so work will have to be done to allow pivot to construct the columns in a way where it doesn't need random access. I think this is possible in a pretty simple way if we do the following process.

1. Identify the columns that have to be merged associated with their row keys.
2. Ensure the row key for each of these is sorted.
3. Perform a join on these into a single table.

There's some additional complications to this. It becomes harder when the row key is multiple rows and it also becomes harder when multiple columns are specified. The algorithm will also likely require that the column key be part of the group key so we might have to ensure that the input is already grouped or have the planner verify that the input will be grouped through a schema aware procedure.
1. Identity the row key and ensure it is sorted

**Comment by jsternberg** [comment]
I think we can possibly constrain this issue to optimize pivot in cases where a single row key and a single column key are given. It will likely require rewriting the core algorithm.

**Comment by jsternberg** [comment]
Related: https://github.com/influxdata/influxdb/issues/14139

**Comment by jsternberg** [comment]
I have a beginning implementation of this done. It merges the row key columns to produce a single row key that can then be used for merging the values. I've implemented it for time values at the moment and the value columns are just completely null values, but I wanted to do a benchmark and test it out to see the difference.

```
jsternberg:[~/g/s/g/i/flux] $ (perf/optimize-pivot *$) benchcmp old.txt new.txt
benchmark                  old ns/op       new ns/op      delta
BenchmarkPivot/1000-12     33557264224     6604501459     -80.32%

benchmark                  old allocs     new allocs     delta
BenchmarkPivot/1000-12     136673348      3992899        -97.08%

benchmark                  old bytes      new bytes      delta
BenchmarkPivot/1000-12     9367265416     3709663208     -60.40%
```

The remaining part of the algorithm should be `O(n)` so I don't expect that to change too much. But the current algorithm doesn't deal with the row key being unsorted and it doesn't correctly deal with multiple column keys. I have pushed the current code and the benchmark to the [perf/optimize-pivot](https://github.com/influxdata/flux/tree/perf/optimize-pivot) branch.

**Comment by jsternberg** [comment]
The optimization is now merged. I am going to try to create a planner rule that initializes it.

Preferably, we would use #2131 as it would be the easiest way to integrate this, but that's still in the design phase so I'm going to see if we can hack this in for the influxdb source specifically.

**Comment by jsternberg** [comment]
Pivot is now used in influxdb specifically for the influxdb source. I am closing this since pivot is optimized.
