### ISSUE TITLE
Remove github actions

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2134]
On Nov 13th the InfluxData github org will loose access to Github Actions. We need to remove replace any actions with something equivalent.

**Comment by jsternberg** [comment]
It should be possible to migrate this to use CircleCI. It is only the release action at the moment.

**Comment by jsternberg** [comment]
It appears like they disabled it for the public actions. It is now emailing me about random workflows that don't exist failing so I'll take this one.
