### ISSUE TITLE
Implement semantic walk with mutability and without

### ISSUE THREAD

**Issue by affo** [influxdata/flux#2137]
Take the code by @bthesorceror here: https://github.com/influxdata/flux-lsp/blob/master/src/visitors/semantic/walk.rs, and move it to `libflux`.

We should end up with a "mutable" visitor and a "non-mutable" visitor.

**Comment by jlapacik** [comment]
Can this be split into two separate issues? Removing mutability from the current visitor in one issue, and then implementing the mutable visitor in another?

**Comment by affo** [comment]
Mmmm I think I am not following, we already have a mutable visitor.

So you mean that we can avoid `Rc` in the mutable one, so we should remove the current one and implement the mutable one following our requirements and the other one following @bthesorceror ones?

**Comment by jlapacik** [comment]
I misunderstood. I thought a refactor to the current walk was required. Please disregard my previous comment.

**Comment by nathanielc** [comment]
We need two walk implementations:

1. Walk that is not mutable but that allows for multiple ownership so visitors can keep references as needed (see for this version from the LSP repo https://github.com/influxdata/flux-lsp/blob/master/src/visitors/semantic/walk.rs we should move this code back to the Flux repo)
2. WalkMut that is mutable but does not need multiple ownership.
