### ISSUE TITLE
Add documents for builtin functions

### ISSUE THREAD

**Issue by kelwang** [influxdata/flux#2141]
When a user hover a function in an IDE, it's always nice to show instructions about that function.

for example: 
     influxdb.flux: from, to, buckets
     math.flux: sqrt2, sqrte

If we can generate comments along with the function, it's will be really nice

**Comment by jsternberg** [comment]
This is going to require us to change the AST to parse comments and we're likely going to need some way to define types for builtin functions within Flux.

I think these are scheduled to happen as part of some of the Algorithm W work. These will likely happen after we finish the libflux work in Rust.

cc @jlapacik
