### ISSUE TITLE
Add support for safely converting bytes to strings

### ISSUE THREAD

**Issue by nisley** [influxdata/flux#2142]
Add support for safely converting bytes to strings

**Comment by nathanielc** [comment]
The code for the conversion will live here https://github.com/influxdata/flux/blob/master/stdlib/universe/typeconv.go#L118 . Once its done the Flux code will work like this `string(v: bytes)`

The code should use a string builder and specifically its WriteRune method https://golang.org/pkg/strings/#Builder.WriteRune

To convert the bytes to valid utf8 use utf8.DecodeRune  https://golang.org/pkg/unicode/utf8/#DecodeRune in a loop to get all the utf8 runes from the bytes.
If an error occurs (RuneError, 1) is returned during decoding return an error from the function.

**Comment by nisley** [comment]
This support was added.
