### ISSUE TITLE
Write step-by-step guide for how to add a bits library to Flux

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/flux#2149]

**Comment by nathanielc** [comment]
@fchikwekwe What is a `bits` library? Is it a lib to do bit wise operations? The idea being that its a good example of how to add a new library to Flux?

**Comment by fchikwekwe** [comment]
This was actually a suggestion from @jsternberg. I was going to ask him for more details on what this is to fill out the issue a little bit more. Jonathan, do you mind explaining this a little bit?
