### ISSUE TITLE
EPIC: Be able to filter data based on type

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2159]
We want the ability to filter data based on the type of the data. This is useful when writing downsample like tasks that operate on a dynamic set of data. For example a user could write this task to downsample all fields in a measurement.

```
from(bucket:"foo")
    |> range(start: -5m)
    |> filter(fn: (r) => r._measurement == "mydata")
    |> mean()
    |> to(bucket:"foo_5m")
 ```
 
 This works well so long as all fields are numeric. As soon as one field is a string or some other numeric type the entire task will fail with an error an no data will be downsampled.
 
 Therefore we need the ability to filter and otherwise interact with the type of the data.
 
 
 ## Proposal 
 
 
This work will have two major parts:

* Add features to Flux to be able to express filters on the type of data
* Add support to the storage layers for filtering based on type of data

For the first part the proposal is to add a `typeof` function to the language that returns a value whose type is `type`. 

```
package types

builtin of : (v:A) => type

// float is the a type for floating point values.
builtin float : type
```

Where `type` is a new type added to Flux that represents a type. Values of type `type` will be equatable. This way users can express the above Flux script safely as:

```
import "types"

from(bucket:"foo")
    |> range(start: -5m)
    |> filter(fn: (r) => r._measurement == "mydata" and types.of(v:r._value) == types.float
    |> mean()
    |> to(bucket:"foo_5m")
 ```
 
### Some open design questions:
 
 * Should we use `types.of` as a function or an operator? Using an operator makes it easier for the compiler/static pass to optimize away any typeof expression that have a known type staticaly
 * Should we expose kind constraints via this type system? Perhaps with a set of functions that can query whether a type satisfies a constraint? For example `types.isNumeric(t: types.of(v: r._value))`, this will allow uint, int and float types to be selected in a filter expression.

**Comment by sanderson** [comment]
If I could upvote this 100 times, I would! Have wanted something like this for a while.

**Comment by nathanielc** [comment]
@sanderson Can you share some concrete use cases for why this would be so helpful? The one use case I can think of is filtering data based on its type. Is that the only one or are there others?

Also FWIW all the work we are doing on Algo W will directly enable this kind of feature in the future.

**Comment by sanderson** [comment]
Filtering by type for downsampling tasks. This way you can use a different aggregate for numeric types vs strings.

```
from(bucket: "telegraf")
  |> range(start: -24h)
  |> filter(fn: (r) => typeOf(v: r._value) != "string")
  |> aggregateWindow(every: 30m, fn: mean)
  |> to(...)

from(bucket: "telegraf")
  |> range(start: -24h)
  |> filter(fn: (r) => typeOf(v: r._value) == "string")
  |> aggregateWindow(every: 30m, fn: last)
  |> to(...)
```

**Comment by jsternberg** [comment]
@nathanielc I think this is separate from algorithm w. The type system would potentially reject these queries at planning time instead of execution once the type system is improved, but this is the case where you want to do something like run a task to aggregate the last minute of data within a specific measurement rather than for a specific field.

**Comment by jeremy-prater** [comment]
> Filtering by type for downsampling tasks. This way you can use a different aggregate for numeric types vs strings.
> 
> ```
> from(bucket: "telegraf")
>   |> range(start: -24h)
>   |> filter(fn: (r) => typeOf(v: r._value) != "string")
>   |> aggregateWindow(every: 30m, fn: mean)
>   |> to(...)
> 
> from(bucket: "telegraf")
>   |> range(start: -24h)
>   |> filter(fn: (r) => typeOf(v: r._value) == "string")
>   |> aggregateWindow(every: 30m, fn: last)
>   |> to(...)
> ```

This is the exact use case I talked about today on the Influx slack!!

**Comment by FixTestRepeat** [comment]
Is there any update regarding this ticket? Pretty fundamental for queries to be run at scale and still be robust

**Comment by gefaila** [comment]
This is exactly what I need and I've bumped into the lack of a typeOf function again and again.
https://community.influxdata.com/t/this-must-be-simple-how-do-you-return-a-table-of-datatypes-for-each-value/16708/6 
Please can we have this ?
