### ISSUE TITLE
Assign types to Flux builtins in Rust

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#2163]
The Flux standard library has many builtin identifiers that are implemented in Go (not pure Flux), and so we must explicitly assign them valid Flux types. Moreover, because type inference is done in Rust, this assignment must also be done in Rust in order to run type inference directly after parsing.

Q: Where should these Rust files live?
A: Most likely next to their corresponding Flux files in `stdlib`, but this is still TBD.

Note, some builtins like `from`, `filter`, and `map` can easily be assigned a valid type signature, however there are others like `keep`, `drop`, and `join` that cannot. Part of this issue is to classify all such builtins that cannot be typed.

For example, `keep` and `drop` are functions that could be expressed equivalently using `map`. This will require some sort of preprocessor to accomplish, and all functions that require this in order to be typed should be documented within the same issue. `join` on the other hand cannot use a preprocessor. It will need to be replaced with a function very similar to `promql.join` which can be assigned a valid type. And all other similar functions again should be documented in the same issue.

As a final note, any Flux transformation (that consumes tables and produces tables) that cannot be assigned a valid type should be given a temporary type similar to the following:

    forall [t0, t1] where t0: Record, t1: Record <id>(->tables: [t0], ...) -> [t1]

The important thing to notice about this function type, is that it is polymorphic in its return type. What this signature says, is that this function can consume a list of any record type and it returns a list of completely unrelated record types. Intuitively this means that anything we've inferred in a program will be lost as soon as we use such a function. In order to have proper type inference in Flux, we will have to replace all such signatures with valid ones that do not exhibit return type polymorphism.

Note, the `Record` kind does not exist currently. It was just used for illustration purposes, but may need to be added for this issue.

**Comment by jlapacik** [comment]
Below is a proposal for how to implement the above specification.

### Goal

We must be able to parse and fully type check a flux program no matter where that flux program is defined.

### Requirements

The code that parses and type checks a flux program is defined as a static library which will be linked to any binary that evaluates flux source.

### Problem - The Flux Standard Library

The flux standard library declares identifiers that are visible to all flux programs. Therefore in order to type check a flux program, we must know the type of every identifier declared in the standard library. How do we add this information to the aforementioned static library?

### Proposal - Code Generation

As part of the Flux build process, I propose we not only parse, but also type check each flux source file that makes up the Flux standard library. We should then generate Rust source files that together declare the types for all identifiers defined in the standard library. This generated Rust code will be part of the flux static library and therefore this type information will available to every Flux program no matter where it lives.

### Implementation

We will need to define an importer (in Rust) for any package defined as part of the standard library. Therefore in order to generate this Rust code, we will need the ability to take a `PolyType` struct or `MonoType` enum and generate its corresponding Rust definition.

I propose we define two new types `AbstractPolyType` and `AbstractMonoType` for the purpose of serializing into Rust source code. The Flux build process would then involve compiling a `PolyType` into an `AbstractPolyType` before generating the corresponding Rust code. Similarly type checking a flux program would involve compiling all of the `AbstractPolyType`s that make up the standard library into their equivalent `PolyType`s and then performing type inference over the flux source.

Note if this proposal is accepted, the implementation can be organized into the following items:

1. Define `AbstractPolyType` and `AbstractMonoType` types, their serialization methods, and methods for translating between `PolyType` and `AbstractPolyType` (same for `MonoType`).
2. Generate the Rust code that defines an importer for the packages in the standard library.
3. Use generated rust code to type check a flux program that uses the standard library.

**Comment by nathanielc** [comment]
@jlapacik Should we use the Flatbuffer representation of the poly types for this? Instead of creating new `Abstract*`  types?

**Comment by jlapacik** [comment]
@nathanielc the reason for defining new `Abstract*` types is to keep the code generation relatively isolated. Any changes to the `MonoType` or `PolyType` API should not require a refactor of the codegen.

Do FlatBuffers fit this description? From my understanding a lot of code on the Go side will be interfacing with the Flatbuffer representation. That makes me a little nervous about having it tied so closely with code generation.

That brings me to my next question which is how exactly would we add type information to the flux static library using Flatbuffers? Would we generate Flatbuffer schema source or can we serialize the Flatbuffer binary representation directly into the static lib? If the latter can be achieved then I would say yes we should use the Flatbuffer representation for this. Otherwise I think I would prefer a more isolated representation.

**Comment by nathanielc** [comment]
@jlapacik it looks like you have answered you own question. I agree Flatbuffers are a good use here because they are isolated and are a consistent way of serializing the type information.

My thinking is the process would look something like this:

1. Some hand written definitions in Rust that define the types of the builtin identifiers for each package (this will be removed once builtin statements can have their own type expressions)
2. Some logic that consumes the builtin types to parse and analyze the Flux stdlib source. This will be a per package process that understand the dependency tree between all of the stdlib packages.
3. Some logic to take the output of step 2 and generate Rust code that contains the flatbuffer encoded types of all identifies in the stdlib by package. The generated code will be an easily consumable implementation of the Importer.
4. The generated Rust code is then compiled as part of the stdlib and there is logic to create an importer from the generated code.
5. External consumers can depend on this new stdlib crate and get the stdlib::Importer type.

Does that sound about right?

**Comment by jlapacik** [comment]
@nathanielc yes that sounds right. Just to reiterate:

* The type for each builtin will be expressed as a `PolyType`.
* The flux source code for each stdlib package will be parsed and the types inferred.
* A flux record type will be created for each such package.
* A flatbuffer representation will be created for each of these record types.
* These binary representations will then be serialized to disk.
* An importer will be constructed from this binary encoding on disk, allowing any arbitrary flux program to be type checked.

**Comment by wolffcm** [comment]
This all sounds good to me.  Does it need to be on disk?  We could also generate Rust source files that contain byte arrays that represent the types.

**Comment by jlapacik** [comment]
@wolffcm sorry I wrong language. Yes that's what I had in mind. Generated Rust source files with byte arrays corresponding to flatbuffers.

**Comment by nathanielc** [comment]
@jlapacik @wolffcm This plan looks solid now, should we try and get a good estimate on it now?

**Comment by jlapacik** [comment]
I have organized the work for this proposal into the following issues:

* https://github.com/influxdata/flux/issues/2196
* https://github.com/influxdata/flux/issues/2197
* https://github.com/influxdata/flux/issues/2198
