### ISSUE TITLE
Implement semantic graph checks

### ISSUE THREAD

**Issue by affo** [influxdata/flux#2165]
In the Go codebase, after semantic analysis, we run some checks against the graph.

See https://github.com/influxdata/flux/blob/a84b0cb78a70df4afad187cf66d9b12e49558124/semantic/analyze.go#L19.

Port those in Rust and add them here https://github.com/influxdata/flux/blob/master/libflux/src/semantic/analyze.rs#L23.

Basically this issue is about implementing some visitors that check characteristics of the semantic graph and error if they are not met.

**Comment by nathanielc** [comment]
DOD

* Port of the Go  test cases exist that the checks work as expected 

Note:

Should likely use the non mutable version of semantic walk as its a readonly operation on the semantic graph.
