### ISSUE TITLE
[flux - window function]: incorrect grouping of points

### ISSUE THREAD

**Issue by gusakk** [influxdata/flux#2170]
## Environment Info
- System info: `Linux 4.15.0-65-generic x86_64`
- Flux version: `0.50.2` compatible with InfluxDB `v1.7.9`

## Config
Tested Flux queries on the InfluxDB launched with this config:
```
# ...
[http]
  # ...
  flux-enabled = true
  # ...
```

## Issue Description
`window()` produces incorrect windows for some border points. Details will be provided below.

## Steps to reproduce
1. Start `InfluxDB v1.7.9` and write these points into it:
```
curl -i -XPOST http://localhost:8086/query --data-urlencode "q=CREATE DATABASE monitoring_vdc"

curl -i -XPOST 'http://localhost:8086/write?db=monitoring_vdc' --data-binary 'cq_performance_transaction,storage_pool=sp3,vdc=vdcbeigec failed_request_counter=0.013322259136212626,succeed_request_counter=37.91211517165006 1568987400000000000'
curl -i -XPOST 'http://localhost:8086/write?db=monitoring_vdc' --data-binary 'cq_performance_transaction,storage_pool=sp3,vdc=vdcbeigec failed_request_counter=0.006666666666666667,succeed_request_counter=36.02333333333333 1568987700000000000'
curl -i -XPOST 'http://localhost:8086/write?db=monitoring_vdc' --data-binary 'cq_performance_transaction,storage_pool=sp3,vdc=vdcbeigec failed_request_counter=0.016666666666666666,succeed_request_counter=40.233333333333334 1568988000000000000'
```

Notice that the timestamps of the three series provided above differ on 5 minutes.
Timestamps in RFC3339 UTC format:
```
1568987400000000000 -> 2019-09-20T13:50:00Z
1568987700000000000 -> 2019-09-20T13:55:00Z
1568988000000000000 -> 2019-09-20T14:00:00Z
```

2. Execute this `Flux` query
```
from(bucket:"monitoring_vdc") |> range(start: 2019-09-20T13:50:00Z, stop: 2019-09-20T14:00:00Z) |> filter(fn: (r) => r._measurement == "cq_performance_transaction") |> keep(columns: ["_start", "_stop", "_time", "_value"]) |> window(every: 5m)
```

## Expected behaviour
From my point of view I expect to see this output:
```
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double
#group,false,false,true,true,false,false
#default,_result,,,,,
,result,table,_start,_stop,_time,_value
,,0,2019-09-20T13:50:00Z,2019-09-20T13:55:00Z,2019-09-20T13:50:00Z,0.013322259136212626
,,0,2019-09-20T13:50:00Z,2019-09-20T13:55:00Z,2019-09-20T13:50:00Z,37.91211517165006
,,1,2019-09-20T13:55:00Z,2019-09-20T14:00:00Z,2019-09-20T13:55:00Z,0.006666666666666667
,,1,2019-09-20T13:55:00Z,2019-09-20T14:00:00Z,2019-09-20T13:55:00Z,36.02333333333333
```
## Actual behaviour
```
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double
#group,false,false,true,true,false,false
#default,_result,,,,,
,result,table,_start,_stop,_time,_value
,,0,2019-09-20T13:50:00Z,2019-09-20T13:50:00Z,2019-09-20T14:00:00Z,0.016666666666666666
,,0,2019-09-20T13:50:00Z,2019-09-20T13:50:00Z,2019-09-20T14:00:00Z,40.233333333333334
,,1,2019-09-20T13:50:00Z,2019-09-20T13:55:00Z,2019-09-20T13:50:00Z,0.013322259136212626
,,1,2019-09-20T13:50:00Z,2019-09-20T13:55:00Z,2019-09-20T13:50:00Z,37.91211517165006
,,2,2019-09-20T13:55:00Z,2019-09-20T14:00:00Z,2019-09-20T13:55:00Z,0.006666666666666667
,,2,2019-09-20T13:55:00Z,2019-09-20T14:00:00Z,2019-09-20T13:55:00Z,36.02333333333333
```
First two lines with data looks very "strange":
```
,,0,2019-09-20T13:50:00Z,2019-09-20T13:50:00Z,2019-09-20T14:00:00Z,0.016666666666666666
,,0,2019-09-20T13:50:00Z,2019-09-20T13:50:00Z,2019-09-20T14:00:00Z,40.233333333333334
```

Here `_start` and `_stop` columns contain `range start` time:
```
2019-09-20T13:50:00Z,2019-09-20T13:50:00Z
```
However, `_time` column contains `range stop` time:
```
2019-09-20T14:00:00Z
```

which looks like a **bug**, as the point with `_time` `2019-09-20T14:00:00Z` should not be included in the `2019-09-20T13:50:00Z - 2019-09-20T13:50:00Z` window.

## Some notes
Maybe this issue is connected with incorrect `range` behaviour: `range(start: 2019-09-20T13:50:00Z, stop: 2019-09-20T14:00:00Z)`.

Are the points with `_time` which is equal to `range _stop` should be returned here (should be included in the response)? 

After reading the [SPEC](https://github.com/influxdata/flux/blob/master/docs/SPEC.md#range) I didn't understand whether the border points should be included or not:
```
stop
Stop specifies the exclusive newest time to be included in the results. Defaults to the value of the now option time.
```
`exclusive` or `to be included`?

By the way, if the border points are excluded from the `range` response, then the `window` result will be correct (as described in the expected behaviour section).

**Comment by wolffcm** [comment]
@gusakk Thanks for filing this issue.  There's a few things going on here. 

First, you're right that the SPEC is unclear.  The `stop` parameter specifies the exclusive upper bound by which to filter.  I'll update the SPEC to address that: https://github.com/influxdata/flux/pull/2171

Second, there was an issue with how we evaluate the `range` function, where the upper bound is sometimes treated as inclusive.  It's fixed in 2.0, but the fix needs to be ported back to 1.x.  The fix will be in the next 1.x release: https://github.com/influxdata/influxdb/pull/14262

Third, the `window` function produces confusing behavior when the points are not within the range `[_start, _stop)`.  In general this would not happen save for the aforementioned bug.  However, we should either omit the point or produce an error, so I filed an issue: https://github.com/influxdata/flux/issues/2172

In the meantime, as a workaround you can shorten the `range` to get the correct behavior:
```
range(start: 2019-09-20T13:50:00Z, stop: 2019-09-20T13:59:59.999999999Z)
```

**Comment by gusakk** [comment]
@wolffcm Thanks for the info.
I've already tried this workaround, however, it produces "ugly" `_stop` column's values with "999999" :)

**Comment by wolffcm** [comment]
@gusakk Ah, ok. In that case, you can fix the `_stop` column:
```
import "experimental"

// first part of your query goes here...
|> experimental.set(o: {_stop: 2019-09-20T14:00:00Z})
|> window(every: 5m)
```
(Note functions in the experimental package are subject to change)

**Comment by gusakk** [comment]
@wolffcm , thanks.

**Comment by wolffcm** [comment]
I'm closing this since the underlying issue is really this one: https://github.com/influxdata/influxdb/pull/14262
