### ISSUE TITLE
tagKeys predicate

### ISSUE THREAD

**Issue by asalem1** [influxdata/flux#2179]
### Problem

Passing a predicate to filter out the data we want to retrieve returns an invalid argument 500 error. 

```
import "influxdata/influxdb/v1"
    v1.tagKeys(bucket: "${bucketName}", predicate: (r) => r._value != "_start" and r._value != "_stop")
```

What I'm trying to achieve here is to filter the resulting keys so that the `_stop` and `_start` key values are not returned from the `tagKeys` method

### Why this is happening

As it is currently written, it seems like the `predicate` argument runs the filter before retrieving the actual keys that `tagKeys` returns. Source:

https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/influxdb-v1/tagkeys/#function-definition

### Potential Solution

Reordering the operation so that the predicate is run after the keys are returned rather than beforehand

**Comment by jlapacik** [comment]
@Asalem1 did an error message accompany the the 500 error? Your query looks syntactically correct, if not semantically correct. Semantically it seems you want to add a filter after `tagKeys`.

    v1.tagKeys(bucket: "${bucketName}") |> filter(fn: (r) => r._value != "_start" and ...)
