### ISSUE TITLE
Eliminate copies passing Rust AST FlatBuffer to Go

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#2194]
When PR #2162 lands, we can start using FlatBuffers as the serialization format to communicate between Rust and Go.

One complication is that in Rust, serialization returns a `(Vec<u8>, usize)`.  Because flatbuffers builds the serialization starting at the end of the buffer towards the beginning, the chunk of allocated memory is likely not the first byte of the actual serialization.  Go needs to keep track of both to ensure that memory is properly freed.

Also we want to try to:
- Minimize any copying (both of Flux source passed into Rust and of the buffer allocated by Rust for the serialization of the AST)
- ensure that we free memory allocated by Rust when we are done with it (and not before)

**Comment by wolffcm** [comment]
I don't think this needs to block using algo-w in production.  There are some issues with doing no-copy in Go, which a describe a bit here: https://github.com/influxdata/flux/pull/2285#issuecomment-594731100

The flatbuffers are generally only a few KB, so I don't think the performance/memory hit is enough to justify the added risk/complexity.

**Comment by jsternberg** [comment]
We're sending this back to the backlog at the moment as it isn't the most important at the moment and we want to discuss the design more thoroughly before continuing.

**Comment by wolffcm** [comment]
We decided that, while important, that this issue should not block releasing our algo-w work to production.

**Comment by wolffcm** [comment]
One of the challenges of this issue is that:
- We serialize the semantic graph from a FlatBuffer allocated by Rust into a Go native semantic graph
- However: the Go semantic graph contains pointers into the Rust flatbuffer, for the types of expressions
- Managing the lifetime of the Rust flatbuffer becomes tricky because we may decide to discard part of the semantic graph (allowing Go to garbage collect it), but hold on to others.  When do we de-allocate the Rust flatbuffer?  The answer is not obvious.
