### ISSUE TITLE
Declare types for flux builtin identifiers in Rust files

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#2196]
The types of Flux builtin identifiers must be encoded directly in the Flux binary as part of the build process. See https://github.com/influxdata/flux/issues/2163. This requires they be specified somewhere in Rust so that those types are available to the build process. This issue is about defining those Rust files.

I propose they be defined in a submodule of libflux called `builtins`.

Please note, the types themselves should be specified using Flux type expressions. For example, the polytype given to `filter` should be specified as:

    forall [t0] (<-tables: [t0], fn: (r: t0) -> bool) -> [t0]

Also note that some transformations cannot be assigned valid type signatures. Issues should be created for each such identifier. In addition a default type should be assigned to these identifiers. These defaults, while valid syntactically, will not represent valid types. As an example, `keep` cannot be typed in its current form, because the columns to keep are specified using an array of strings. Hence it should be given a type signature of:

    forall [t0, t1] (<-tables: [t0], columns: [string]) -> [t1]

Notice, the extra parameter `t1` that only shows up in the return type. Every default type will have this form.

Finally this work can be split up by package. The universe package is probably still quite large on its own and can probably be split up further.

**Comment by wolffcm** [comment]
Initial work for this is merged, but not all builtins are complete, I filed issues #2229 and #2230 for the remaining builtins.
