### ISSUE TITLE
Serialize flatbuffers for builtin types as part of build process

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#2197]
Flux has a number of builtin identifiers whose types must be encoded directly into the Flux binary. See https://github.com/influxdata/flux/issues/2163. This issue is about adding this work to the flux build process. This requires:

1. To parse and perform type inference on the Flux standard library (don't forget the builtin identifiers https://github.com/influxdata/flux/issues/2196)
2. To serialize the inferred types as flatbuffers.

I propose we add these steps to `build.rs`. Specifically we should use cargo's `OUT_DIR` environment variable to define the location of the binary data file that is the output of step 2.

**Comment by nathanielc** [comment]
NOTE: Its implied that all stdlib packages must be able to type check without error in order to serialize their poly type representation.

**Comment by jlapacik** [comment]
Closed via #2273
