### ISSUE TITLE
Add kind constraint for timeable types

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#220]
The type inference system has support for type classes. They can be implemented as kind constraints. 

* ~Numeric - uint, int and float will all be part of the type class. Also math operators will require this class~
*~Addable - uint, int, float and string will all be part of this class, the `+` operator will require it.~
* ~Comparable - This is for the `<` and `>` etc operatos and types.~
* Timeable - This one is for expressions like `2018-10-19` and `-5s` both resolving to a time value.

>EDIT: Numeric, Addable, and Comparable are already implemented.

**Comment by nathanielc** [comment]
We want the ability to accept either a time or a duration value as an argument to functions that need a time value. A duration value should be interpreted as a delta from the current time. Basically the expression `-5s` is really the expression `now() - 5s`, which produces a time value. 

See this issue for a few practical examples https://github.com/influxdata/influxdb/issues/18402 

Take the function `date.truncate` which can truncate a time to a duration. For example the time `2020-06-12T00:00:15Z` can be truncated to the `minute` using this code:

```
import "date"

date.truncate(t: 2020-06-12T00:00:15Z, unit: 1m) // 2020-06-12T00:00:00Z
```

In the current implementation you cannot do this:


```
import "date"

date.truncate(t: -5s, unit: 1s) // errors because a duration is not a time
```

The current type signature for `date.truncate` is this:

```
forall [] (t: time, unit: duration) -> time
```

This means that the `t` argument must always be a time value. Instead it would be better if we could accept both a time or a duration, where the duration is understood as `now() - <duration>` to produce a time.

The Flux type system allows for this behavior using `kind constraints`. If we add a new kind constraint called `Timeable` and we declare that both the `time` and `duration` types satisfy the `Timeable` constraint then we can change the `date.truncate` function type to this:

```
forall [t0] where t0 : Timeable (t: t0, unit: duration) -> time
```

This function signature says that the `date.truncate` function can take any type for the `t` argument so long as its a `Timeable` type. Since only `time` and `duration` are `Timeable` then only a time or a duration can be passed as the value to `t`. 

With the change this would be possible:

```
import "date"

date.truncate(t: -5s, unit: 1s) // returns the current time 5 seconds ago truncated to the second.
```


This issue is concerned with adding the `Timeable` constraint to the type system. It does not need to change the type signature of `date.truncate` or any other date functions. Those will be separate issues.


DOD
 - Timeable kind constraint has been added
 - Time and Duration satisfy the constraint
 - Units tests for the Timeable constraint and Time/Duration types
 - Does NOT include changing any existing functions to use Timeable, those will be separate issues.

**Comment by ChitlangeSahas** [comment]
I _think_ I have the solution. Attaching the screenshot here. 
<img width="971" alt="Screen Shot 2020-06-13 at 10 50 05 PM" src="https://user-images.githubusercontent.com/18511823/84585818-63f0a080-adc8-11ea-8016-714588417d41.png">

**Comment by ChitlangeSahas** [comment]
Completed. #2908
