### ISSUE TITLE
Using counters is hard

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2203]
Using counters is hard. Its very easy to get it wrong, we should create a complete user experience around this.

Here are some challenges using counters

1. Counters can reset, meaning that each series needs to be viewed in isolation to account for resets.
2. Counters can overflow if summed, basically counters cannot be aggregated until they are no longer counters. Summing counters before computing a difference can hide resets and risks integer overflow.
3. Counters are frequently aggregated across various dimensions.
3. Counters are frequently aggregated over time.

Its not clear how to write a Flux query that safely converts counters to diffs, aggregate them along some tag dimension for specific windows.

In InfluxQL the way this works is we use `last` from each window then compute a difference across each window and then use a `sum` aggregate as an outer query.
This works, but has some issues because the counter reset can be missed during the window.

Prometheus uses the `rate` function which computes the _per-second average rate of increase of the time series in the range vector_.

The Flux equivalent of the InfluxQL method is something like this:
```
from(bucket:"foo")
    |> range(start: -1h)
    |> filter(...)
    |> window(every: 1m)
    |> last()
    |> window(every: inf)
    |> derivative()
    |> group(columns:[<other tags here>])
    |> window(every: 1m)
    |> sum()
    |> group(columns:[<other tags here>])
```

The Flux equivalent of the Prometheus method is something like this:

```
from(bucket:"foo")
    |> range(start: -1h)
    |> filter(...)
    |> window(every: 1m)
    |> derivative()
    |> mean()
    |> group(columns:["_start","_stop", <other tags here>])
    |> sum()
    |> group(columns:[<other tags here>])
```

It seems like we should create a helper function for this kind of aggregation. Here are two proposed functions:

```
// Rate computes the average per unit rate of increase.
// Rate accounts for resets of the counter value and should only be used for counter data.
// When aggregating counter data always use rate first. See aggregateCounter for best practice in aggregating counter data.
rate = (tables=<-,unit=1s) =>
    tables
        |> derivative(unit:unit, nonNegative:true)
        |> mean()

// AggregateCounter performs an aggregate operation on counter data over windows of time.
// The counter is first converted to a rate and then the grouped and aggregated by the provided function.
aggregateCounter = (tables=<-, groupColumns, every, fn, unit=1s) =>
    tables
        |> window(every: every)
        |> rate(unit: unit)
        |> group(columns:["_start", "_stop"] + groupColumns)
        |> fn()
        |> duplicate(column:"_stop", as:"_time")
        |> group(columns: groupColumns)
```

Then it can be used like this:

```
from(bucket:"foo")
    |> range(start: -1h)
    |> filter(...)
    |> aggregateCounter(every: 1m, groupColumns: <other tags>, fn: sum)
```

This should work well for counters in any context including histograms:

Take this histogram data collected via telegraf:

```
// gather the raw histogram count data
// The data has tags host, role and env.
from(bucket: "foo")
	|> range(start: v.timeRangeStart, stop: v.timeRangeStop)
	|> filter(fn: (r) =>
          r._measurement == "http_api_request_duration_seconds" and 
          r._field != "count" and r._field != "sum"
       )
       |> aggregateCounter(
            every: v.windowPeriod,
            // we want to know the sum by role, env and each field. 
            // note: for histograms the _field is the `le` bucket
            groupColumns:["role", "env","_field"],
            fn: sum,
       )
        // Make "le", float copy of _field column
       |> map(fn: (r) => ({r with
           le: float(v: r._field),
        }))
       |> histogramQuantile(quantile: 0.9)
```

I am going to test this out, I'll report back how it works.

**Comment by jsternberg** [comment]
In my opinion, the best way to use counters is to put the `derivative` or `difference` first. I have begun using this in my influxql queries. The only downside is it is not a supported push down.

The reason for this is because flux automatically already has the values grouped and so if I do the `derivative` or `difference` first, it causes it to stop being a counter immediately and I do not have to worry about the shape of the data. It is my opinion that we should encourage this practice by making it easy to push down a derivative or difference to the storage engine where it should be possible and safe to implement it because it is not an unbounded operation.

**Comment by jsternberg** [comment]
To clarify, when I use influxql with counters, I do not use last with windowing. I use a subquery where the inner query will use `GROUP BY *` and `non_negative_difference` and then I will write the query I want as the outer query.

**Comment by nathanielc** [comment]
@jsternberg Agreed, we will likely need to optimize this case as it will be very common. Pushing down a derivative doesn't reduce the data set size much. I expect the largest performance boost will come from reducing the data set size vs just offloading the computation of the difference. Maybe we should push down a `rate` function that computes the difference and the mean? So it returns only a single point for the time range. 

> To clarify, when I use influxql with counters, I do not use last with windowing. I use a subquery where the inner query will use GROUP BY * and non_negative_difference and then I will write the query I want as the outer query.

I thought InfluxQL requires that you use an aggregate method as an argument to `non_negative_difference`. Can you share an example InfluxQL query?

**Comment by jsternberg** [comment]
InfluxQL doesn't require using an aggregate method with `non_negative_difference` if there is no group by time. So you can do this:

```
SELECT mean("gauge") FROM (
    SELECT non_negative_difference("counter") FROM ... WHERE time >= now() - 5m GROUP BY *
) GROUP BY host, time(1m)
```

I usually translate this to:

```
from(bucket: "...")
    |> range(start: -5m)
    |> filter(fn: (r) => r._measurement == "..." and r._field == "counter")
    |> difference(nonNegative: true)
    |> group(columns: ["host"])
    |> aggregateWindow(every: 1m, fn: mean)
```

I think that's roughly what it is.

I agree that pushing down only derivative or difference wouldn't do much. I think the thing that would probably do more is being able to push down derivative/difference with an aggregate or grouping as an extension of the current push downs. At the moment though, we don't push down aggregate windows and I think we don't have the aggregates by themselves.

**Comment by quentinmit** [comment]
I don't think the examples above are correct; `mean` can't be applied to `difference` if there are not a consistent number of input points in each window. Consider, for example, a counter that is monotonically increasing at 1/1, sampled at these times:

```
t=0s 0
t=20s 20
t=21s 21
t=50s 50
t=61s 61
```

and now imagine we want a graph of the difference with 30s windows. That graph "should" be (modulo aliasing if events get counted in the wrong window)

```
t=30s 30
t=60s 30
t=90s 1
```

but with the algorithm above, you would first compute the pairwise differences:

```
t=20s 20
t=21s 1
t=50s 29
t=61s 11
```

and then the `mean` windowing will emit averages at the end of the window:
```
t=30s 10.5
t=60s 29
t=90s 11
```

which is definitely not right (these only add to 50.5 - where did the other 8.5 go?).

I think the only way to properly handle this is to combine the difference/derivative and window into a single operation that splits points at window boundaries. i.e. the pairwise differences would have to be output as:

```
t=20s 20
t=21s 1
t=30s (9/29)*29=9
t=50s (20/29)*29=20
t=60s (10/11)*11=10
t=61s (1/11)*11=1
```

which you could then `aggregateWindow` with `sum` to get differences, and then divide by the window period to get rate.

This is complicated enough, and inefficient with the existing Flux functions, that I really think this needs to be its own optimized function. (I guess the ask would be that "output differences aligned to a given period" is a single function that can be pushed down.)
