### ISSUE TITLE
profiling support / explain analyze

### ISSUE THREAD

**Issue by alespour** [influxdata/flux#2215]
I would be great if there was EXPLAIN ANALYZE equivalent or some profiling supported by the Flux to help user identify which functions are slow in a script.

**Comment by nathanielc** [comment]
Agreed, this is something we have discuss internally. We don't have any concrete plans yet, but we expect to build something like this at some point.

Would a simple breakdown of the time spent in each step of the query be helpful starting point? We already track that time internally for tracing use cases, perhaps we could expose that meta data as part of the returned response on a query if requested.

**Comment by yzhang1991** [comment]
We can see how much time did each operation spend with opentracing, is this what are you referring to? @nathanielc

**Comment by alespour** [comment]
Simple breakdown of the time that would show how much time was spent in each step/operation would be very helpful.

**Comment by nathanielc** [comment]
@yzhang1991 Yes, I am thinking we could leverage the open tracing logic to expose some query execution times. Not sure exactly what that would look like. But at least we are collecting the stats currently.
