### ISSUE TITLE
Unexpected behaviour of Influx CLI in Flux Mode

### ISSUE THREAD

**Issue by Aga-Schwarz** [influxdata/flux#2226]
Hi,

My setup:
InfluxDB: 1.7.9-1
Windows 10 Enterprise

I tried to open the Influx-CLI in Flux Mode but this resulted in an unexpected output (screenshot). The InfluxDB config file has  flux-enabled = true. I can issue Flux queries with Chronograf.
Starting the influx CLI in normal mode works fine. Starting in Flux Mode results in output as in screenshot. I tried typing 1+1 which was followed by a lot of unexpected output.

![flux](https://user-images.githubusercontent.com/58482753/70147832-5c2ba300-16a5-11ea-8a0f-6c1d6f0afdb4.PNG)

**Comment by russorat** [comment]
@Aga-Schwarz thanks for reporting!

**Comment by nathanielc** [comment]
@Aga-Schwarz This looks like its a bug with the terminal drawing library we are using. Its trying to auto complete some values for you, but its not rendering correctly in your terminal. 

We will take a look at this.

**Comment by staff0rd** [comment]
@nathanielc is it possible to turn this autocomplete feature off? I'm also experiencing issues with it via a powershell > ssh > linux vm > docker container > influx tunnel
