### ISSUE TITLE
keyValues function has suspicious fn parameter

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#2235]
The `keyValues` function has a parameter named `fn` which is described like this in the SPEC:

       
(schema: schema) -> []string | Fn is a schema function that may by used instead of keyColumns to identify the set of columns.
-- | --

The `fn` parameter does not seem to be used anywhere in the actual code, and it seems like we want to just remove it.

**Comment by nathanielc** [comment]
Agreed lets just remove it.
