### ISSUE TITLE
uints should be subtractable in type inference

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#2242]
The `Subtractable` kind constraint does not apply to the `uint` type in our type inference.  Most languages allow unsigned ints to be subtracted, and I think Flux should as well.

Recently I tried to add this constraint, *but* my changes failed because of this test:
https://github.com/influxdata/flux/blob/11d59706f2991b4a3e8fa355aa749c42f3abd297/libflux/src/flux/semantic/tests.rs#L2330-L2335

It turns out that `Subtractable` applies to both unary and binary subtraction.  In the case of uints, we need to decide if unary subtraction is allowed.

My vote would be "no," however, it turns out that Go allows this: https://play.golang.org/p/xsy2c9sugS1
It would be good to check what other languages do as well.

If we decide that we don't want to allow unary subtraction of uints, then we should create a new kind constraint `UnarySubtractable` and have it only apply to the signed numeric types.

**Comment by yzhang1991** [comment]
C++ allows this: https://code.sololearn.com/cyxCXDA24jyT/#cpp

**Comment by nathanielc** [comment]
>  In the case of uints, we need to decide if unary subtraction is allowed.

We have decided to allow unary subtraction. The behavior of subtracting a uint that produces a negative number is that uint overflow occurs without error. Unary subtraction is semantically equivalent to `0-a` where `a` is a uint.
