### ISSUE TITLE
Create a time/duration kind constraint

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#2243]
The `range` function has `start` and `stop` parameters that allow for either `time` or `duration` values to be passed in.  Maybe there are other examples of this too.

In order to type check these more precisely we could create a `TimeOrDuration` kind constraint.

**Comment by yzhang1991** [comment]
If it is OK I wish to look into more of this so I can get my hands a little bit dirty on type inference.

**Comment by wolffcm** [comment]
@yzhang1991 This is totally fine with me.

**Comment by nathanielc** [comment]
This is related to https://github.com/influxdata/flux/issues/220

**Comment by nathanielc** [comment]
I have added details to #220 and so I am going to close this issue in favor of that issue.
