### ISSUE TITLE
Map function returns a Internal server error in influx version 1.7.9

### ISSUE THREAD

**Issue by rajsameer** [influxdata/flux#2261]
Hey,

I recently updated the influx to the latest version i.e. influx1.7.9. And I use flux the same query works in the previous version of flux but fails in the new version.

And it happens only with the map function. Using map anywhere in the query will result in an internal error.

**Comment by sanderson** [comment]
@rajsameer What does your map function look like?

**Comment by rajsameer** [comment]
@sanderson , Below is the query.
I am running it on centos 7 with influx 1.7.9 the query works fine when i reverted the version to 1.7.8.
RxPackets = from(bucket: "healthDB/1min")
  |> range($range)
  |> filter(fn: (r) => r._measurement == "m1" and r._field == "f1")
  |> keep(columns: ["_time","dimension","_value"])
  |> fill(column: "_value", value: 0.0)
  |> group(columns: ["time","dimension"],mode: "by")
  |> window(every: 1m)
  |> sum(column: "_value")
  |> duplicate(column: "_stop", as: "_time")
  |> keep(columns: ["_time","dimension","_value"])
  |> rename(columns :{_value: "Rx"})

  
TxPackets = from(bucket: "healthDB/1min")
  |> range($range)
  |> filter(fn: (r) => r._measurement == "m2" and r._field == "f2")
  |> fill(column: "_value", value: 0.0)
  |> keep(columns: ["_time","dimension","_value"])
  |> group(columns: ["time","dimension"],mode: "by")
  |> window(every: 1m)
  |> sum(column: "_value")
  |> duplicate(column: "_stop", as: "_time")
  |> keep(columns: ["_time","dimension","_value"])
  |> rename(columns :{_value: "Tx"})
  
  

join(tables: {Rx:RxPackets,Tx:TxPackets}, on: ["_time", "dimension"])
  |> map(fn: (r) => ({_time: r._time, dimension: r.dimension, _value:r.Rx - r.Tx}))

now I tried using map in simple queries to check if I was using it incorrectly. It still failed in 1.7.9

**Comment by sanderson** [comment]
Can you provide sample output from the `TxPackets` and `RxPackets` streams?

**Comment by rajsameer** [comment]
[Rx out stream.txt](https://github.com/influxdata/flux/files/3947102/Rx.out.stream.txt)
[Tx out stream.txt](https://github.com/influxdata/flux/files/3947103/Tx.out.stream.txt)

**Comment by rajsameer** [comment]
Hi ,
were you able to replicate the issue?
