### ISSUE TITLE
duration() takes in nsec, might choose differently

### ISSUE THREAD

**Issue by wz2b** [influxdata/flux#2268]
Playing with duration() the documentation didn't really tell me that the input value is in nanoseconds.  It would be good to either document that, or, since it's a pretty "alpha" feature, consider changing it.  I would think a more natural way to do it would be to have duration take a double-precision float as its argument, so that it can just take 'seconds' as the input.

I wasn't able to find the documentation for the Duration object.

It would also be really nice if there was some way to have the Duration object print a friendly string that automatically scales to higher units when the number gets big, the way that Joda does.  That way if you're displaying something like an uptime you can get a string out of it like:

59 seconds
1 minute
4 hours 1 minute
1 day 4 hours 3 minutes

something like that.  Joda has ways to do this, but they aren't the only ways.  The real goal is to be able to take a number (usually seconds or msec) and get to the kind of friendly string you'd put on a dashboard - "System has been up for four days" is a lot better than this:

`4d47m5s24ms`

which is what came out of:

`string(v: duration(v: r.value * 1000000))`

**Comment by jsternberg** [comment]
It should be possible for `string()` to do the pretty printing. We'll double check that as part of this issue. I think we'll implement this as adding a `unit` to the `duration()`. That way you could do `duration(v: r._value, unit: "s")`.

At the moment, I think you can use float as the argument. But, it's still in nanoseconds.
