### ISSUE TITLE
Build memory checker tool for CI

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#2289]
Since we are using `unsafe` in Rust and a C API to pass data structures between Rust and Go, we should be running some kind of memory checking tool (like `valgrind`) in CI.

One way to do this would be:
- Write a simple C app that exercises all of the C functions exposed by Rust
- Run that C app in `valgrind` and have it look for leaks, double frees, etc
- Make CI fail if `valgrind` finds any issues.

**Comment by mark-rushakoff** [comment]
As of Go 1.14, which is now in beta, [you can run tests with `-gcflags=all=-d=checkptr`](https://groups.google.com/d/msg/golang-dev/SzwDoqoRVJA/IvtnBW5oDwAJ) "to enable dynamic instrumentation for checking unsafe pointer arithmetic and conversions". That would be good to start running now, perhaps in its own CI stage, before Go 1.14 goes into rc or final. If we happen to stumble on any bugs in the Go runtime around this, they ought to be fixable more promptly during beta/rc than final release.

**Comment by wolffcm** [comment]
Maybe we need a two-pronged approach here:
- Have a CI stage for that uses `-gcflags=all=-d=checkptr` and runs our Go tests as Mark recommends
- Write a small binary crate that exercises the C API that our Rust code exposes to Go, and run that in `cargo-valgrind`: https://crates.io/crates/cargo-valgrind

Note that `checkptr` is only available in Go 1.14, but it will run in `-race` by default for non-Windows platforms, but the Flux repo CI is still on Go 1.12.  Maybe we can create a `flux-build-go-1.14` docker image for this purpose.  

It's unclear to me if `checkptr` will get us all the coverage that we need on the Go side, but I'm not sure what other automated tools are available for ensuring that the unsafe parts of Go code are correct in CI.

**Comment by nathanielc** [comment]
It seems like we should use `checkptr` when its available, Go 1.14 hasn't released yet. It seems to only validate that pointers are to real Go types if they are de-referenced to a Go type. The only pointers we cast from Rust to a Go type are for flatbuffers, so it will only catch that the pointer points to something that looks like a flatbuffer. It will not validate that we didn't leak any pointers on the Go side.

That said seems valuable and since it exists we should use it, also seems like it would be good to use because of the Arrow code that does some unsafe logic as well.

I really like the idea of a simple C program to validate the Rust side of things.

**Comment by mark-rushakoff** [comment]
The Go 1.14beta1 docker image is already available. https://hub.docker.com/_/golang. It should be straightforward to run tests with checkptr using that image in Circle.

That being said I ran the checkptr test very recently and noticed many failures deep in Arrow. If there were any Flux-specific errors, I missed them in the other noise of the output. Until the Arrow pointers are sorted out, it's hard to say how much value those tests will provide to Flux.

**Comment by rockstar** [comment]
> Write a small binary crate that exercises the C API that our Rust code exposes to Go, and run that in cargo-valgrind: https://crates.io/crates/cargo-valgrind

I think this is a really good idea, and it doesn't even have to be a crate, it can just be a binary in the library itself, and [exposed via `[[bin]]` in `Cargo.toml`](https://doc.rust-lang.org/cargo/reference/manifest.html#configuring-a-target)

I don't much about the go gc (and every time Jonathan says something about it, I realize I knew even less), so I can't really speak to the use of `checkptr` or whether that would work.

**Comment by mark-rushakoff** [comment]
Here are [the draft docs for checkptr](https://tip.golang.org/doc/go1.14#compiler):

> This release adds -d=checkptr as a compile-time option for adding instrumentation to check that Go code is following unsafe.Pointer safety rules dynamically. This option is enabled by default (except on Windows) with the -race or -msan flags, and can be disabled with -gcflags=all=-d=checkptr=0. Specifically, -d=checkptr checks the following:

> When converting unsafe.Pointer to *T, the resulting pointer must be aligned appropriately for T.
> If the result of pointer arithmetic points into a Go heap object, one of the unsafe.Pointer-typed operands must point into the same object.
> Using -d=checkptr is not currently recommended on Windows because it causes false alerts in the standard library.

As you can see, this provides some validation of Go's interaction with the pointers it receives or sends to Rust code. 

Running with Valgrind seems higher value overall, but it should be fairly low effort to run checkptr in CI.

**Comment by wolffcm** [comment]
I filed #2500 for the issue of using `checkptr` in CI.

For running valgrind on our Rust code, I see two ways to go:
- Install valgrind on our Flux build image and run a simple program written in C that exercises our C API
- Write a simple Rust program and use `cargo-valgrind` to do the same.  This might be a bit easier to implement, but I'd feel safer just using a C program, since that will force us to exercise the very same API that Go uses.

**Comment by nathanielc** [comment]
Lets go with this plan

>     Install valgrind on our Flux build image and run a simple program written in C that exercises our C API


DOD:

* C program exists that call all libflux.h exported functions
* Program runs via CI with valgrind to check for memory errors
