### ISSUE TITLE
Move the From function to platform

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#23]
In order to be able to move the From function to platform, and thus remove the last platform dependencies we need to update the planner. Specifically the PushDown rules that apply to From need to be defined in platform and not in Flux. Since the PushDown rules are methods on the procedures this is not possible.

When we go to rewrite the planner we should keep this pattern in mind. We need to support creating rules that apply across repo boundaries.

**Comment by stuartcarnie** [comment]
Sounds good. With respect to OSS, as I reimplement the storage reader, it appears I would be able to use a number of those same push down rules. It may change over time as we expose more physical operations that the in-process flux implementation can leverage that may not make sense via an RPC call
