### ISSUE TITLE
Implement Average True Range

### ISSUE THREAD

**Issue by darwayne** [influxdata/flux#2301]
I noticed that flux has some built in functions for common indicators such as RSI (Relative strength index) and AMA (Kauffman Adaptive Moving Average)

I'm very surprised that ATR (Average True Range) isn't in there yet. Is ATR on the roadmap to be added as a built in function?

**Comment by nathanielc** [comment]
@darwayne It is not currently on the roadmap. Is that something you could contribute? We can help you get started with the right bits in the code.

**Comment by darwayne** [comment]
Thanks for the info @nathanielc not sure I’ll have free time to contribute anytime soon, but would def love to.
