### ISSUE TITLE
Remove compilation cache

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2319]
We have a compilation cache were we only recompile functions for new input types. This previously used some Go pointer trickery, that is no longer possible using flatbuffers. We can implement the compilation cache by using a hash of the record property keys and basic type. In other words implement a cache using a hash function over a subset of type instead of all possible Flux types.

See https://github.com/influxdata/flux/blob/feat/use-algo-w/compiler/compiler.go#L483 for a starting point.

**Comment by nathanielc** [comment]
After discussion we have concluded that we no longer need the compilation cache. The changes to use the generic values.Value type and the change to no longer call type inference directly from the compile step has removed the need to compile row functions for each input type. A single compilation step is all that is needed. 

This issue is now about removing the CompilationCache entirely and changing call sites to use Compile directly. 

The validation of input types is still required.

**Comment by jsternberg** [comment]
This is going to involve fixing the compiler too. It doesn't really make sense to remove the compilation cache without fixing the compiler at the same time.
