### ISSUE TITLE
Remove type comparison Equal method

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2320]
Implementing an equals method on types is complicated and expensive operation. We should not need the method anymore as all type information was resolved via type inference. Remove the `Equal` method from the `MonoType` struct. 

See https://github.com/influxdata/flux/blob/feat/use-algo-w/semantic/monotype.go#L443

**Comment by jsternberg** [comment]
Do we need this method for test cases?

**Comment by jsternberg** [comment]
We might need this. In particular, object is weird. An object gets its type from usually an external source, but we have to provide the object with values that get their type from some different source.

Three possible solutions for constructing an object. The first is that we construct an object with its type and use set to set the values. This allows the object to be mutable.

```go
func NewObject(typ semantic.MonoType) *object

func (o *object) Set(key string, value values.Value) {
    // needs to check that the value's type matches with the
    // one that's in the object type.
}
```

An alternative is we make constructing an object efficient enough that it's trivial to create. Mostly by sharing the underlying buffers when constructing the actual object.

```go
func NewObject(typ semantic.MonoType, labels []string, values []Value) *object
```

I haven't thought through it the most, but it's probably possible to have the object use the passed in buffers so it avoids memory allocations or sorting. But this doesn't account for checking if the monotype for the value matches the property's monotype inside of the object type.

The third option is just not to do type checking. If we don't do type checking on `Set` then we can have the API do whatever.

If we want to ensure the API is used correctly, we likely need an `Equal` method to ensure that the value's monotype matches with the property value's type. If we are willing to just trust that the API is used correctly and something else caught it, we can remove the comparison method.

**Comment by nathanielc** [comment]
Needing to compare types for the object makes sense.  Maybe lets work the object issue first and see its uses, if its clear that type checking isn't important form the uses of the object we can skip it. But if its possible to introduce values of the wrong type then we should do type checking and just implement the equal method for MonoType.

**Comment by jsternberg** [comment]
That's the reason why I made the above comment. I was modifying the object to work and I figured I needed to do this since we will need to accept `values.Value` types as the property values.

**Comment by jsternberg** [comment]
I'm going to set it so `Equal` always returns true in my branch and then we'll figure out if we need it. When I began implementing comparing rows, it is not likely to perform well. We might not need type checking for setting values.

**Comment by nathanielc** [comment]
@jsternberg Is this complete? If so can we close it?
