### ISSUE TITLE
Graceful table building functions

### ISSUE THREAD

**Issue by sanderson** [influxdata/flux#2350]
Currently the only way to build a custom, ad hoc table in Flux is to use `csv.from()` to load in raw annotated CSV. Getting the annotated CSV syntax correct is an exercise in patience and doesn't always make for a very user-friendly experience.

What if we created a package of table building functions that would allow uses to build tables on the fly in Flux without having to know and use annotated CSV:

```js
import "table"

customTable = table.new(columns: {_time: time, _field: string, _value: int, foo: string})

customTable
  |> table.addRow(r: {_time: 2020-01-05T00:00:00Z, _field: someField, _value: 3, foo: bar})
  |> table.addRows(rows: [
        {_time: 2020-01-05T00:00:00Z, _field: someField, _value: 3, foo: bar},
        {_time: 2020-01-05T00:01:00Z, _field: someField, _value: 4, foo: bar},
        {_time: 2020-01-05T00:02:00Z, _field: someField, _value: 1, foo: bar}
    ]
  )
```

**Comment by nathanielc** [comment]
@sanderson Thanks! This is a really helpful example of how this could work. We started down this path a while back and decided that `csv.from` would work in the meantime. We do not plan for `csv.from` to be the long term solution. This is a helpful step towards creating a table literal syntax and/or helper methods for creating tables. This is something I expect we will tackle soon.

**Comment by nathanielc** [comment]
Linking  https://github.com/influxdata/flux/issues/1212 as related
