### ISSUE TITLE
Inference regression for exists operator

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#2353]
This works in Go type inference, but fails in Rust.

Go:
```javascript
> exists {foo: 30}.foo
true
> exists {foo: 30}.bar
false
```

Rust:
```Go
	{
		// TODO(cwolff): file issue
		name:    "exists operator",
		fluxSrc: `e = exists {foo: 30}.bar`,
		err:     errors.New("cannot unify {{}} with {bar:t0 | t1}"),
	},
```

**Comment by jlapacik** [comment]
If a field does not exist on a record at compile time, it is a type error in Rust. Go just says that it should be null, no type error.

**Comment by wolffcm** [comment]
I see. So if the record type has an "extends" type variable, then it works:
```
		name:    "exists operator with tvar",
		fluxSrc: `f = (r) => exists r.foo`,
		types: map[string]string{
			"f": "forall [t0, t1] (r: {foo: t0 | t1}) -> bool",
		},
```
That's really cool.

Should I close this issue then?

**Comment by wolffcm** [comment]
It seems like it is a regression, because we get an error where before we didn't, but for the usual case on using `exists` on rows from an InfluxDB source, it will still work right.

**Comment by jlapacik** [comment]
Yeah I think we should close it. This is a known area where the Go type inference and Rust type inference don't agree.
