### ISSUE TITLE
Type inference bug with records and call expressions

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#2355]
Rust type inference doesn't seem to get this right:
```javascript
f = (r) => exists r.foo
ff = (r) => f(r: {r with bar: 1})
```
type of `f` is `forall [t3771, t3782] (r: {foo: t3771 | t3782}) -> bool`
type of `ff` is `forall [t3785, t3786] (r: {foo: t3785 | t3787}) -> bool`

Note that `t3786` is universally quantified, but does not appear in the monotype at all, and `t3787` is in the monotype but not quantified.

**Comment by jlapacik** [comment]
Note, both `f` and `ff` are of the same type. That is both are equivalent to:

    forall [t0, t1] (r: {foo: t0 | t1}) -> bool

I ran type inference over the above flux declarations on the Rust side and I get the correct types.

**Comment by wolffcm** [comment]
Hmm, I reproduced this on the Go side, but it's just deserializing what it gets from Rust.  I wonder if it only happens when inference has the stdlib type environment?

**Comment by jlapacik** [comment]
I'll look into it. Most likely that's where it's coming from.

**Comment by wolffcm** [comment]
I just reproduced this with a query that would be somewhat typical of use with InfluxDB:
```Go
{
	name: "typical query",
	fluxSrc: `
              v = {
                  bucket: "telegraf",
                  windowPeriod: 15s,
                  timeRangeStart: -5m
              }
              q = from(bucket: v.bucket)
                 |> filter(fn: (r) => r._measurement == "disk")
                  |> filter(fn: (r) => r._field == "used_percent")
                  |> filter(fn: (r) => r.device == "disk1s1")`,
	types: map[string]string{
		"v": "forall [] {bucket: string | timeRangeStart: duration | windowPeriod: duration}",
		"q": "forall [t0, t1] [{_field: string | _measurement: string | _time: time | _value: t0 | device: string | t2}]",
	},
},
```

**Comment by jlapacik** [comment]
The following assertion unfortunately does not hold with extensible records:
https://github.com/influxdata/flux/blob/d1c3353fe339df82253c872ea1e19ba802c1d39c/libflux/src/flux/semantic/nodes.rs#L591

The reason for this is that new type variables are generated during record unification. Unification does not generate new type variables for any other types. Currently working on a fix.

**Comment by wolffcm** [comment]
This should *not* block landing the algo-w work.

**Comment by nathanielc** [comment]
@wolffcm Why doesn't this bug block the algo-w work?

**Comment by jlapacik** [comment]
This issue occurs after type inference has been run when we are annotating each expression with their inferred types. An inconsistency can arise where there is a type variable in a polytype's list of quantified variables, that is not present in the type itself. This does not cause any issues at the moment, because currently after type inference, we never reference a polytype's list of quantified variables. Hence the inconsistency is never observed.

So as it stands this should not block the release of algo-w, but I plan on fixing it as soon as all blocking issues have been resolved.

**Comment by nathanielc** [comment]
Great, thanks for the explanation. Going to move this out of the milestone and leave at the top of the backlog.
