### ISSUE TITLE
panic during program start on join perf

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/flux#2357]
Using InfluxDB-v2.0-Beta 
The following yields an internal error
```
y = table stream 
x = (y) => y |> more flux 
xy = (x,y) => join(tables: {x:x, y:y}, on: ["_time"])
xy (x:x(y:y),y:y)
```
But if I hard code x, it doesn't produce an error.
Error: 

> 2020-01-09T20:52:14.485788Z	info	panic during program start	{"log_id": "0KEt8UiG000", "service": "storage-reads", "error": "panic: Inconsistent plan graph: successor does not have edge back to predecessor"}
> goroutine 8133 [running]:
> runtime/debug.Stack(0xc000712d80, 0x0, 0x28880cd)
> 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
> github.com/influxdata/influxdb/query/control.(*Controller).executeQuery.func1(0xc00674e600, 0xc000458420)
> 	/go/src/github.com/influxdata/influxdb/query/control/controller.go:402 +0x150
> panic(0x24cb2a0, 0x36f9240)
> 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
> github.com/influxdata/flux/plan.updateSuccessors(0xc00e5cd480, 0x3794f00, 0xc00b451380, 0x3794f80, 0xc00c83afc0)
> 	/go/pkg/mod/github.com/influxdata/flux@v0.58.0/plan/heuristic_planner.go:159 +0x365
> github.com/influxdata/flux/plan.(*heuristicPlanner).Plan(0xc00e5bba00, 0xc00e5cd480, 0x0, 0x0, 0x0)
> 	/go/pkg/mod/github.com/influxdata/flux@v0.58.0/plan/heuristic_planner.go:107 +0x478
> github.com/influxdata/flux/plan.(*physicalPlanner).Plan(0xc0111f4d20, 0xc00e5cd480, 0xc00e5cd480, 0x0, 0x0)
> 	/go/pkg/mod/github.com/influxdata/flux@v0.58.0/plan/physical.go:43 +0x3c
> github.com/influxdata/flux/plan.(*planner).Plan(0xc0111f4d80, 0xc00c83a900, 0x0, 0x0, 0x0)
> 	/go/pkg/mod/github.com/influxdata/flux@v0.58.0/plan/builder.go:47 +0xa4
> github.com/influxdata/flux/lang.buildPlan(0x376c1a0, 0xc00e5f8390, 0xc00c83a900, 0xc0008a7b40, 0x0, 0x0, 0x0)
> 	/go/pkg/mod/github.com/influxdata/flux@v0.58.0/lang/compiler.go:153 +0x348
> github.com/influxdata/flux/lang.(*AstProgram).Start(0xc00c47a030, 0x376c1a0, 0xc00c47a120, 0xc0101becd0, 0x0, 0x0, 0x0, 0x0)
> 	/go/pkg/mod/github.com/influxdata/flux@v0.58.0/lang/compiler.go:352 +0x1c8
> github.com/influxdata/influxdb/query/control.(*Controller).executeQuery(0xc000458420, 0xc00674e600)
> 	/go/src/github.com/influxdata/influxdb/query/control/controller.go:422 +0x15c
> github.com/influxdata/influxdb/query/control.(*Controller).processQueryQueue(0xc000458420)
> 	/go/src/github.com/influxdata/influxdb/query/control/controller.go:383 +0x4c
> github.com/influxdata/influxdb/query/control.New.func1(0xc000458420)
> 	/go/src/github.com/influxdata/influxdb/query/control/controller.go:190 +0x61
> created by github.com/influxdata/influxdb/query/control.New
> 	/go/src/github.com/influxdata/influxdb/query/control/controller.go:188 +0x7af

Full flux code looks like: 
```
y = from(bucket: "default")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "cpu")
  |> filter(fn: (r) => r._field == "usage_system")
  |> filter(fn: (r) => r.cpu == "cpu-total")
 
x = (y) => y
	|> map(fn: (r) => ({_time: r._time, index: 1}))
	|> cumulativeSum(columns: ["index"])

xy = (x,y) => 
  join(tables: {x:x, y:y}, on: ["_time"])
  
xy_bar(x:x(y:y),y:y)
```

**Comment by Kungitoo** [comment]
Same error, similar problem. Can we get some feedback on this? What are we doing wrong?
