### ISSUE TITLE
Find and fix uses of equal operator for semantic.Type

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2358]
The semantic.Type used pointer tricks to make it valid to compare them by their pointer value and hence the `==` and `!=` operators worked as expected. With the changes to make `semantic.MonoType` a struct that points to flatbuffers the `==` and `!=` will no longer work. We need to find all instances where we used the operator and change it.

**Comment by nathanielc** [comment]
Once we have all tests passing we can for struct comparison to fail using a unique integer as a field to find any accidental equality comparisons.

**Comment by wolffcm** [comment]
DOD:
- Take a few hours and make sure we don't use `==` or `!=` with `semantic.MonoType` or `semantic.PolyType`.

**Comment by fchikwekwe** [comment]
I wasn't able to find any obvious uses of `==` or `!=` with `MonoType` or `PolyType`. Closing this issue.
