### ISSUE TITLE
Rework EvalAST API to avoid extra serialization steps

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2365]
The EvalAST API accepts Go structures that represent the Flux AST, it would be more efficient to use either  a raw []byte of JSON or Flatbuffers for that API so that we don't have to go through multiple serialization steps.

As it stands today it would look like this:

HTTP Request -> deserialize from JSON -> Go AST structs -> flatbuffers to Rust -> Rust deserialize to Rust AST structs 

It would be more efficient to do something more like this:

HTTP Request -> raw []byte to Rust -> Rust deserialize JSON to Rust AST structs

Future work will be to send the flatbuffers directly over the network instead of JSON

**Comment by wolffcm** [comment]
Fixed by
https://github.com/influxdata/flux/pull/2638
And
https://github.com/influxdata/influxdb/pull/17316
