### ISSUE TITLE
Get miscellaneous packages compiling and passing tests on feat/use-algo-w branch

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2366]
There are various packages that may not be passing tests or even building at this point due to the semantic package changes. This issue is about updating those packages. This issue does NOT include the following packages:

* interpreter
* compiler
* values
* semantic
* execute
* stdlib

This list likely includes the following packages:

* repl
* lang
* ...

**Comment by nathanielc** [comment]
NOTE: If any package looks like its going to be large and part of the critical path then we will create a new issue for just that package.

**Comment by jsternberg** [comment]
This issues has been broken up and the broken packages and tests have been fixed. The entirety of the branch compiles successfully and the other issues will cover fixing the code.
