### ISSUE TITLE
failed to initialize execute state: filesystem service uninitialized in dependencies

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#2382]
looks like calling `csv.from(file: "/path/to/csv")` throws the error: `failed to initialize execute state: filesystem service uninitialized in dependencies` no matter what file you send it.

flux v0.58.0
influxdb oss

**Comment by anthonysomerset** [comment]
I've also hit this bug in latest 1.7.x release from repo's in Ubuntu - i am testing via the beta grafana datasource which is using the HTTP API

**Comment by adriandt** [comment]
This typically means you're not running in the context that you think you're running in. For example, if you're passing queries to the server via the API and trying to access a file on your local file system. Or if you're running locally and trying to access data on the server ... though we are working solving that second problem.

**Comment by anthonysomerset** [comment]
so i should be passing via API requesting a file on the influx server filesystem i've also verified the file in question is readable by the influxdb user as well to be sure

**Comment by adriandt** [comment]
Hi Anthony, sorry I should have been more specific, I believe it isn't possible to access files from the server process.

**Comment by ashishkaransingh** [comment]
Hello,

Can we now load .csv files?
I am still getting error: 
`failed to initialize execute state: filesystem service uninitialized in dependencies`
Example here [cs.from()](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/csv/from/) describes how to do it but it does not work!
