### ISSUE TITLE
Analysis should return a semantic graph even if errors are found

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#2384]
Similar to how parsing works, we should be able return a semantic graph that contains errors after doing type inference.  This is especially important for LSP work, so that we can run inference on incomplete programs as the user is typing.

The current entry point for type inference is here:
https://github.com/influxdata/flux/blob/master/libflux/src/libstd/lib.rs#L49

Perhaps we could do it this way:
- `analyze` return type continues to be `Result<flux::semantic::nodes::Package, flux::Error>`
- If there is some kind of internal error (not a type error or other kind of user error), return `Err(...)`
- If we can run type inference, then return `Ok(semantic_pkg)` where `semantic_pkg` may be annotated with typing errors that were found, if any.  Perhaps we could store a list of errors in the `File` node, or something like that.

**Comment by nathanielc** [comment]
> If there is some kind of internal error (not a type error or other kind of user error), return Err(...)

Do we have any errors in the category already? If not maybe we simplify the API so its clear errors belong on the graph itself? Otherwise I really like this API as it mirrors what we have done with the AST.

**Comment by wolffcm** [comment]
I can't think of any internal errors that we produce (outside of serializing), but I feel like there should be a way to make the distinction of user vs. internal errors in what we return to Go.  This differs a bit from how we might write code in Go, since we can panic in Go, and then recover and we know it's an internal error.  In Rust, when a panic happens it sends a signal to stop the process.  (At least that's what I think happens.)

I think it's better to design our API with the assumption that internal errors will happen, since they certainly will.  Then the questions become:
- What action should we take?  If we decide just killing the process is okay, then maybe a simpler API is appropriate.
- If we decide we want to return internal errors to Go, then what's the best way to do that? (I feel like it should be outside of the semantic graph, but I'm open to alternatives)

**Comment by nathanielc** [comment]
I don't think we want to panic from inside Rust for any reason as the behavior across the Go/Cgo/Rust  boundary is probably undefined. Found this in a quick search https://github.com/rust-lang/rust/issues/52652 not sure if that is Rust calling out to FFI or being called from FFI but in either case I expect its undefined behavior. 

 I agree we should return explicit errors when they are internal to the processing of the code and not a user error. User errors belong on the semantic graph.

**Comment by jlapacik** [comment]
I see two strategies for continuing type inference even after an error is found:

1. When a constraint does not unify, record the error, i.e append it to a list, and continue. This method is the simplest but could possibly suffer from a cascade of errors that are all dependent on one another.

2. When a type constraint does not unify, record the error and also the type variables involved. Store the type variables in a set. Before unifying the next constraint, check to see if any of these type variables are referenced. If so, ignore and move to the next constraint. This method adds some extra overhead by having to track the type variables involved in contradicting constraints, but it should reduce the number of dependent errors.

**Comment by nathanielc** [comment]
@jlapacik I think we should start with approach 2 as it is by far the better user experience.

Also I had a chat with @bthesorceror and he confirmed that indeed there are two classes of errors we need to catch. 


1. Error where the input AST itself is broken (i.e. has Bad*) nodes
2. Errors in unification.
