### ISSUE TITLE
Use Tagged version for UUID package

### ISSUE THREAD

**Issue by lyondhill** [influxdata/flux#2392]
We needed to update the uuid package to use a non tagged version because a security fix was implemented after the latest tag. https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMSATORIGOUUID-72488 

It would be better practice to have a tagged version of the uuid package to use. Barring that we should fork their package and tag it in our copy.

**Comment by pierwill** [comment]
Can this be closed?
