### ISSUE TITLE
Add type environment parameter to Rust type inference

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#2402]
We should add the ability for clients to pass in an optional type environment to Rust type inference.  We already have the ability to serialize type environments to a flatbuffer, so we should make use of that.

I believe that we'll need this working so we can tell Rust inference about  any "extern" declarations (like `v = {bucket: "telegraf"}`, etc) coming from the web UI.

Also, this is needed so that the REPL will work right, so that each new statement that the user submits can include the type environment of previous statements.  This also allows more thorough testing of the interpreter.

This will require updating the Rust API for type inference to have an additional type environment parameter:
https://github.com/influxdata/flux/blob/master/libflux/src/libstd/lib.rs#L28-L64

**Comment by fchikwekwe** [comment]
I believe this issue is also affecting `ScopeMutator` args in calls to `flux.Eval`. We have a few tests that will be skipped until this issue is resolved.

**Comment by nathanielc** [comment]
NOTES:

* We need to write Go code to generate flatbuffers from a type environment
* We need to explicitly handle keeping the tvars from the extra type environment unique compared to the stdlib and AST expression. 

Possible ways to keep tvars fresh

1. Expose the concept of a Fresher through the libflux C API and use the Fresher when generating the type environment on the Go side
2. Inside of analyze use the max tvar from the extra type environment to initialize the fresher
3. Substitute the tvars in the type environment to be unique compared to the stdlib

**Comment by fchikwekwe** [comment]
UPDATE: This issue also affects `TestGetColumn_Call`, `TestGetRecord_Call` and `TestIndexFns_EndToEnd`

**Comment by jsternberg** [comment]
@wolffcm and I discussed this and we think exposing the type environment as part of the C API is likely the best solution. We were thinking something like this:

```c
struct flux_semantic_env_t;

struct flux_semantic_env_t *flux_new_semantic_env(struct flux_semantic_env_t *parent);

// flux_env_analyze analyzes the ast using the semantic environment.
// It will return the semantic package with the type information and include any
// changes to the type environment in the semantic environment.
struct flux_error_t *flux_env_analyze(struct flux_semantic_env_t *, struct flux_ast_pkg_t *, struct flux_semantic_pkg_t **);
```

This should allow semantic analysis to be reentrant so we can analyze parts of the package rather than the entire thing at the same time.

**Comment by wolffcm** [comment]
Here's a proposal for making this work, after some discussion with @jsternberg.

Preliminary work: update `semantic::env::Environment` so that its reference to its parent environment uses `Rc`, so that parent scopes (such as the standard library scope) can be shared across requests.

We would need to update the Rust API for semantic analysis.  The existing `analyze()` function can remain.  We would need to add two new functions that would allow the REPL to work:
```Rust
/// Return a new type environment containing only the standard library
fn new_env() -> TypeEnvironment;

/// Analyze the given AST and upon success, return:
///   - A type environment that contains an entry for each variable assignment in the input AST.
///     The output type environment will contain the input type environment as its parent.
///   - The semantic package, converted from the AST, with types
fn analyze_with_env(env: Rc<Environment>, ast: ast::Package) -> Result<(Environment, semantic::Package), Error>
```

For use cases like the REPL, we could call the new method like so (this is pseudocode):
```Rust
let env = new_env();
let line = read_line();
while let Some(line) = line {
    let ast = parse_line();
    match analyze_with_env(env, ast) {
        Ok((new_env, sem)) => {
            eval(sem);
            env = new_env;
        }
        Err(err) => {
            display_err(err);
        }
    }
    line = read_line();
}
```

For each statement processed, a new child type environment would be added to the environment chain.  For a long-lived REPL this could lead to a very long chain. Probably we would want to collapse intermediate environments into one to make lookups faster and use less memory.

This work might be broken down into issues like this (one issue per bullet):
- Change `Environment` to reference its parent environment with `Rc`
- Write and unit test new Rust API (`new_env()` and `analyze_with_env()`)
- Update `analyze_with_env()` to collapse environment chains (this is not critical path)
- Write a C wrapper API for the new Rust functions, and the Go wrapper for the C wrapper
- Integrate the new API into tests that need to use a type environment to work
- Integrate the new API into the REPL

**Comment by nathanielc** [comment]
@wolffcm Looks good some follow up questions:

 How would the Go side add new items to the env without any associated AST? For example the test cases that want to inject raw values into the scope?


 It seems that by forcing the mutation of the env to only be via AST you avoid the fresher challenges. Meaning you don't have to worry about creating/tracking fresh type vars because you can't mutate the env outside the context of semantic analyze. Inside the context of semantic analyze you can correctly create the fresher based off the max tvar in the env. 

So this goes back to the first question, do we loose that simplicity in the API if we allow for the env to be directly mutated outside the context of semantic analyze? Again for the test case examples.

**Comment by wolffcm** [comment]
@nathanielc 

> How would the Go side add new items to the env without any associated AST? For example the test cases that want to inject raw values into the scope?

I think the answer here is that here would lose the ability to add items to the type environment that cannot be expressed in Flux syntax, but that's not a big deal.  The upside is that type environments are only manipulated in Rust and are read-only, which are nice invariants to have.

I think for the vast majority of the tests that do this, we can rewrite the needed items in Flux.  There are a few cases that are tricky, e.g., the `fail()` function, which can be written in Flux as:
```
fail = () => [][0]
```
For most other cases, thing we want could be added to the standard library, into an `internal` or `experimental` package, but I think there will be very few of them.

**Comment by jsternberg** [comment]
I agree with @wolffcm on this. I think constructing the environment from semantic graphs is what we would end up doing anyway. I also think it ends up making sure we don't have tvars conflicting with each other since we can share the environment across multiple calls and can easily flatten the environment.
