### ISSUE TITLE
Validate AST Externs will work with Algo W

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2405]
There is a FluxCompiler and an ASTCompiler that both have a `Extern *ast.File` property. See the `lang` package.

In order to correctly type this Rust type inference needs to accept a ast.Package with multiple files.

The flow is:

1. Convert ast.File to flatbuffers
2. Call into libflux to get `flux_ast_package_t` struct pointer from flatbuffers
3. Call into libflux to merge two packages into one. See #2344
4. Pass merged package into libflux analyze call

**Comment by fchikwekwe** [comment]
Clarifying question: 

I'm only seeing an `Extern` Property on the `FluxCompiler` struct. Is the idea here that we fold the `Flux Compiler`'s file into the `ast.Package` on `ASTCompiler`?

**Comment by nathanielc** [comment]
The `Extern` property lives only on the `FluxCompiler` when the compiler goes to parse the query it will have two ast.Package instances (one from Extern and one from the parsed query). It will need to use the merge function combine those into a single ast.Package before going on the the semantic analyze step. 

The ASTCopmiler should not need to change. 

Does that help clarify?

**Comment by fchikwekwe** [comment]
Yeah, that helps. Another question -- the `Extern` property on the `FluxCompiler` is an `ast.File`. I'm guessing that I need to create an `ast.Package` with that, convert both to `libflux.ASTPkg`s and then go on to do the merge? Or is there a place where the extern gets made into a package and I just need to worry about converying and combining the parsed query `ast.Package` and the `Extern` `ast.Package`.

**Comment by nathanielc** [comment]
You will need to convert the file to a package, but that should be straightforward as the file has all the relevant info already.

**Comment by fchikwekwe** [comment]
Externs are currently working as tested within the Web UI. There is already testing to make sure that externs do not error here: https://github.com/influxdata/flux/blob/feat/use-algo-w/lang/compiler_test.go#L42-L164

The next step here is to refactor the current multifile merge (https://github.com/influxdata/flux/blob/feat/use-algo-w/lang/compiler.go#L306-L308) to avoid extra serialization steps as requested in this issue https://github.com/influxdata/flux/issues/2365.
