### ISSUE TITLE
Interpreter seems to ignore option assignments

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#2410]
This bug is specific to the `feat/use-algo-w` branch.

I'm seeing the interpreter test `TestInterpreter_SetNewOption` fail.  It's a very simple test case:
```js
package alert
option state = "Warning"
state
```
The error produced is `failed to evaluate package: undefined identifier "state"`.

Seems like there is an issue with evaluating `IdentifierExpression` in the interpreter.

**Comment by jsternberg** [comment]
This might be related to the package stuff. At the moment, all of the packages for the interpreter are constructed incorrectly.
