### ISSUE TITLE
monitor.check has a type error

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#2437]
When writing a check, I referenced `r._value` in the message fn  which in my data set was occasionally null (due to differently aligned windows).  This resulted in an unexpected type error in the stdlib code.  This was unexpected because my data does have a _value column.  

<img width="1462" alt="Screen Shot 2020-01-24 at 4 45 48 PM" src="https://user-images.githubusercontent.com/25036188/73106535-a113cf00-3ec9-11ea-908e-e85ea2f5fe4c.png">

**Comment by nathanielc** [comment]
@aanthony1243 The data does have the `_value` column, the data is pivoted on line 30, you should reference the name of the field you have instead of `_value`.
