### ISSUE TITLE
basic getRecord/tableFind fails

### ISSUE THREAD

**Issue by yossigartner** [influxdata/flux#2442]
I'm trying to use the 'getRecord' function as described in the documentation [here](https://docs.influxdata.com/flux/v0.50/stdlib/built-in/transformations/stream-table/getrecord/)

i'm using influxdb cloud Version 2.0.0 (8ff62ab), with flux 0.5v.

the code:
![image](https://user-images.githubusercontent.com/7220867/73436281-e5ccb980-4352-11ea-8c33-e210b328a87e.png)

when i try to 'save' the task, i get the following error:
![image](https://user-images.githubusercontent.com/7220867/73436346-05fc7880-4353-11ea-9f3e-118e6f0f08e1.png)

**Comment by sanderson** [comment]
Is this the full task script or is there more to it?

**Comment by Yossig** [comment]
the full script doesn't event use the r0 variable yet, that's what really bothers me.
(the full script runs OK without this code)

**Comment by sanderson** [comment]
I don't think this is an issue with Flux. I think this is an issue with the task validator that runs when you try to save the task. Can you run this query (line 3 on) successfully in the Data Explorer?

**Comment by Yossig** [comment]
These function are not available in the Data Explorer
![image](https://user-images.githubusercontent.com/7220867/73741373-ca96eb00-4752-11ea-9bcc-a14ea6793eb0.png)

**Comment by Yossig** [comment]
I get this error: "error in query specification while starting program: this Flux script returns no streaming data. Consider adding a "yield" or invoking streaming functions directly, without performing an assignment"

the query:
![image](https://user-images.githubusercontent.com/7220867/73742231-a0462d00-4754-11ea-8be0-a0e62132d941.png)

**Comment by sanderson** [comment]
The error is correct. A task requires a stream of tables as an input and a stream of tables as an output. By using `tableFind()`, you're extracting a single table out of the stream of tables and you no longer have "streaming" data in your task. `getRecord` returns an object literal that represents the first row in the extracted table. It does not return not a stream of tables. 

To get essentially the same result, but structured as a stream of tables, you could:

```js
from(bucket: "test")
  |> range(start: -5m)
  |> filter(fn: (r) => 
      r._measurement == "sample" and
      r.device_id == "999" and
      r._field == "value"
  )
  |> group()
  |> first()
```

**Comment by mcassaniti** [comment]
@sanderson What is the best way to get that into the documentation? I've been using the data explorer to do almost the same query and wondering why I got nothing in return.

As an aside, is it worth while extending the error output from the data explorer from: "`this Flux script returns no streaming data`" to something like "`this Flux script returns <this format> of data, but needs to return streaming data. See <URL>`". Of course if there's no data then it should say so too.

```
from(bucket: "ts")
  |> range(start: -15m)
  |> filter(fn: (r) => r._measurement == "cpu" and r._field == "usage_active")
  |> keep(columns: ["_time", "_value", "cpu", "host"])
  |> group()
  |> tableFind(fn: (key) => 1 == 1)
```

**Comment by sanderson** [comment]
@mcassaniti I think it could definitely be useful to extend the error messaging in the Data Explorer, but I have a feeling this would be dependent on the Flux typing system which is currently undergoing a major refactor. I think at some point, the Data Explorer and dashboards should support queries that return scalar values (@russorat).

I created an issue for the v2 documentation: https://github.com/influxdata/docs-v2/issues/735

**Comment by mcassaniti** [comment]
@sanderson Thank you very much. Is there a way to get non-stream data out anywhere?

**Comment by sanderson** [comment]
The REPL supports scalar values.

- [Execute queries with the InfluxDB 2.0 REPL](https://v2.docs.influxdata.com/v2.0/query-data/execute-queries/#influx-repl)

**Comment by Yossig** [comment]
> I don't think this is an issue with Flux. I think this is an issue with the task validator that runs when you try to save the task. Can you run this query (line 3 on) successfully in the Data Explorer?

I managed to run the query successfully in the Data Explorer, but i need to use it in a Task.
What can you tell me about this problem with the task validator? is it a known issue or something?

**Comment by sanderson** [comment]
@Yossig I'm not sure if it's a known issue. Go ahead and create an issue on the [InfluxDB repo](https://github.com/influxdata/influxdb) and include as much detail as you can (the query, the error message, the http response code, etc.).

**Comment by adrian-thurston** [comment]
As of #2759 it is possible to use tableFind and friends in the repl. I believe this also fixes the task validator -- this part needs validation.

**Comment by adrian-thurston** [comment]
Unassigning myself as we are now operating in sprints and it needs to get scheduled.

**Comment by timhallinflux** [comment]
This issue should be resolved.  Comment to reopen.
