### ISSUE TITLE
Improve error message when required parameter is missing

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/flux#247]
I have a query that resulted in this error: `failed to compile query: type error 5:6-5:69: missing required parameter "columnKey"`.

The positional information is somewhat helpful, but I never know whether row `5` is 0-based or 1-based. The error message, and developer/user experience, would be improved considerably if it said `missing required parameter "x" __in call to function "y"__`.

**Comment by andig** [comment]
I'd also like to suggest to make line numbers for error messages 1-based
