### ISSUE TITLE
Create influxdb.from() source in Flux repository

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2470]
The only way to communicate with InfluxDB is to use the built-in influxdb from that exists within the server. There's no current way to use the Flux binary to query InfluxDB through the public API.

This can make it harder to interact with InfluxDB from Flux itself.

This issue is about making a Flux-native influxdb source that uses the public HTTP API to retrieve results. We would implement a version that takes the `from() |> range() |> filter()` chain and serializes the query to an AST and uses the public API to execute the query and read the data into a local Flux table.

**Comment by nathanielc** [comment]
This seems like a tractable solution to the REPL problems. How would a query like this work in the REPL with this method?

```
x = "foo"
from(bucket:"b")
   |> range(start: -1m)
   |> filter(fn: (r) => r._measurement == x and r._field == "counter")
   // ...
```

How do we _resolve_ `x` as part of the filter? Could we encode values as literal AST for the basic column data types? Since tables can only contain (int,float,string, time, duration) filters will only contain types containing those values. Even if `x` where and object or a list it would still be possible to encode the value as an AST literal. Thoughts?

**Comment by jsternberg** [comment]
When we are constructing the AST from the semantic node, we should be able to resolve identifiers. This will work with simple examples like the one above, but it may present a problem for more complex ones like functions. For functions, we may just decide that those aren't serializable and so we don't push down those functions. To make this functional, we only need to allow simple filters such as the one above. So if a type refers to something we can resolve at the time we are constructing the AST, then we serialize it and send it over. If it involves something such as including `from() |> tableFind()` inside of the actual filter, we would just choose not to serialize it.

The minimum we need to make a request is `from |> range` and neither of those will have any problems with AST serialization.

**Comment by jsternberg** [comment]
I've been experimenting with this and `feat/influxdb-source` is a minimum viable product for reading from an influxdb server. I was able to execute a `from |> range` query, although it required some additional options. I think we can potentially expose those options as options within the `influxdb` module and potentially inject defaults for the `flux repl` so it is basically the same as the influxdb repl.

**Comment by jsternberg** [comment]
I have a copy of this working in the flux repository and I am able to make it work in the influxdb repl.

My issue is I need to hook it up with the in-process version so that the two are compatible with each other and so that someone can use `influxdb.from(host:)` inside of influxdb itself. I want to use the planner for that to decide when it should switch from using the remote version to the local version. I'll be working on that today.

**Comment by jsternberg** [comment]
This is now merged.
