### ISSUE TITLE
semantic.FunctionExpression does not have a MonoType

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/flux#2473]
Tests that include a semantic.FunctionExpression but lack a MonoType are failing with error message: `MonoType is not a function`. 

A MonoType needs to be added to these tests. 

DOD: 
-  Tests are unskipped and now pass

**Comment by fchikwekwe** [comment]
UPDATE: This is affecting `TestFilter_Process` and `TestMap_Process`

**Comment by jsternberg** [comment]
I have a work in progress for this at `refactor/function-expr-tests`. I need to work on something else more urgently so I'm unassigning myself and leaving my work in progress up.
