### ISSUE TITLE
Prop for `math.max` is missing in stdlib lookup

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/flux#2474]
When the `math.max` or `math.min` function's type information is looked up using `LookupBuiltinType` in the test TestMathFunctionsXY, the `Prop` is missing. 

(Issue requires more details)

DOD: 
-  Tests are unskipped and now pass

**Comment by jsternberg** [comment]
This is an error with the test only. The `stdlib/math` package itself is fine.

**Comment by wolffcm** [comment]
Do we just need to look up `mMax` instead?  I think we named it that to avoid a conflict with `universe.max` back when `math` was sort of in the prelude.

**Comment by jsternberg** [comment]
Yes that's all that's required. We do want to do that rename, but that is technically a breaking change and I don't know what we should do regarding that. I don't want to overly complicate getting algorithm w merged.
