### ISSUE TITLE
`option planner` cannot be reassigned

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/flux#2475]
Tests where the planner is reassigned are failing. Here is an example Flux script: 

```
import "planner"

option planner.disablePhysicalRules = [""]
option planner.disableLogicalRules = [""]
```
Error message is simply as follows: 
`failed to start program: @5:1-5:42: option "planner" reassigned`

Note that making the planner a user-defined object does not cause this issue even when two planner options are introduced: 

```
planner = {
	disablePhysicalRules: ["fromRangeRule"],
	disableLogicalRules: ["removeCountRule"]
}
```

**Comment by wolffcm** [comment]
Related issue: https://github.com/influxdata/flux/issues/2462

This will be fixed by this PR: https://github.com/influxdata/flux/pull/2477

**Comment by fchikwekwe** [comment]
PR #2477 is now merged, so I'm closing this issue.
