### ISSUE TITLE
`CompileFnParam` is not implemented and causes `generate` package to panic

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/flux#2476]
`CompileFnParam` is currently unimplemented. This is causing uses of the "generate" package to panic since the package registration (specifically the call to `createFromGeneratorSource`) refers to this function. 

We either need to get rid of this call to `CompileFnParam` or implement the function. 

DOD: 
-  Tests are unskipped and now pass

**Comment by jsternberg** [comment]
@nathanielc you talked about removing this package in favor of promoting `internal/gen`. Should we just do that? At the least, we can remove this and decide on promoting `internal/gen` later.

**Comment by nathanielc** [comment]
@jsternberg We can remove it if we can prove its not used in production.

**Comment by jsternberg** [comment]
@aanthony1243 tells me that there hasn't been a reference to the word `generate` in production in over 30 days. I'm going to remove this function.

**Comment by nathanielc** [comment]
@jsternberg @aanthony1243 How was that validated as we discovered that it is being used by @russorat ? I'd like to understand if we have a gap somewhere.
