### ISSUE TITLE
`UnexpectedKind()` error in `TestContains_NewQuery`

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/flux#2481]
Running into Go `UnexpectedKind()` panic when doing values comparisons in `TestContains_NewQuery` and in `TestLength_NewQuery`

Error message: `unexpected kind: got "int" expected "array"`

DOD: 
-  Tests are unskipped and now pass

**Comment by fchikwekwe** [comment]
@jsternberg this issue doesn't seem to have been resolved with the above PR. We need to leave it open until `TestContains_NewQuery` and in `TestLength_NewQuery` are passing tests.

**Comment by jsternberg** [comment]
I didn't see the `TestLength_NewQuery`. Can you make the same change to that one?

**Comment by jlapacik** [comment]
I didn't realize this was already assigned. Here's the fix https://github.com/influxdata/flux/pull/2504
