### ISSUE TITLE
`MonoType is not a function` error when testing FIlter or Map

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/flux#2489]
All tests in `TestFilter_Process` are erroring with the following message: 

`expected no error, got MonoType is not a function` 

DOD: 
-  Tests referring to this issue are unskipped and now pass

**Comment by fchikwekwe** [comment]
UPDATE: Same issue with `TestMap_Process`

**Comment by wolffcm** [comment]
Dupe of #2473 ?

**Comment by fchikwekwe** [comment]
Yeah, I'll move these details over there.
