### ISSUE TITLE
unification error in build bench test

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/flux#2496]
When running `Benchmark_FromScript` there is a unification error: 

`cannot unify {{}} with {_check_name:t4156 | _check_id:t4157 | _type:t4158 | t4188}`

NOTE: This is kind of a nonspecific "unification error". There's been bunch of errors that look like this all over the repo. Most were fixed in other PRs, but this one persists.

**Comment by jlapacik** [comment]
This error looks similar to another unification error that was a result of a function taking an empty record as a default argument. The fix was to make the argument required. It looks like it's coming from the `monitor` package.

**Comment by jlapacik** [comment]
Here's the offending line:
https://github.com/influxdata/flux/blob/901fdec832fe5fc0eb9685bc6b9effa5ad5b98a2/internal/spec/build_test.go#L24

From `monitor.check`:
https://github.com/influxdata/flux/blob/901fdec832fe5fc0eb9685bc6b9effa5ad5b98a2/stdlib/influxdata/influxdb/monitor/monitor.flux#L94-L111

we see that `data` must be a record with fields `tags`, `_type`, `_check_id`, and `_check_name`.
