### ISSUE TITLE
Design solution for REPL working with Algo-W

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2498]
We need a way to make the REPL work with Algo-W

There are two challenges that Algo-W has created for the repl.

1. The semantic graph types use flatbuffers and its no longer to serialize them as JSON. 
2. The Rust API doesn't accept an existing type environment. (see #2402)

The second issue will be fixed eventually, the first is likely not tractable.

The REPL relying on the serialization of the SPEC and by extension semantic graph via the API is an anti-pattern and should change. It seems like now is the time to reconsider the design of the REPL.

A few options:

1. Cache the AST as its entered in and  resubmit the entire REPL history
2. Write a source that can send `from |> range |> filter` requests to the InfluxDB API (see #2470)

Both options struggle to communicate the current scope to the InfluxDB server.
The first option has challenges with variable reassignment. 

DOD:

* Have a plan for fixing the REPL so that it works the same before we started Algo-W
* Bonus points if we can fix the dynamic issues with the REPL, but it is not required.

**Comment by jsternberg** [comment]
I think the two main sections to check on are type inference and the json serialization.

We can learn about the plan for type inference and if we can find another solution to it. I think the solution for type inference is to either encode the values (if possible) as externs when analyzing the sources or to open up some way to customize the environment for semantic analysis.

For json serialization, I think we just need to run some flux queries in the flux repl. Then we can see if those work in the influx repl. My theory is that they will work in the flux repl and not in the influx repl. If this is the case, the remote source of `from |> range |> filter` should work and we can experiment with seeing if that will work. In particular, we will need to serialize the semantic function back to AST.

**Comment by jsternberg** [comment]
#2402 #2470 should resolve this. We can likely remove the spec compiler if we do both of those.

**Comment by jsternberg** [comment]
We currently have a plan with the above two issues. I'm going to close this because this issue is specifically about a plan.
