### ISSUE TITLE
Support for specifying interpolation used by integral()

### ISSUE THREAD

**Issue by kimburgess** [influxdata/flux#2515]
The current `integral()` implementation appears to apply a linear interpolation between points. To enable uses with irregular series (transitions between values based on an event, rather than regularly timed sample) it would be extremely useful to be able to specify alternative interpolations.

As a base set:
1. linear (current impl)
2. previous (fill intermediate points used by riemann sum with the last value)
3. next (fill intermediate points with the next available event value)

This would enable usage for calculating time-weighted means when downsampling event data.

Note: for anyone stumbling across this - info on a work around using currently available functionality [here](https://community.influxdata.com/t/non-interpolated-integral/12911/2).

**Comment by russorat** [comment]
@KimBurgess thank you for the request!
