### ISSUE TITLE
Performance: Type Inference

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#2517]
Currently when types are generalized as part of type inference, the entire type environment up to that point must be walked in order to calculate the free variables of the type environment.

https://github.com/influxdata/flux/blob/92f87546b8c27459248589e5cb3a8cb51100e082/libflux/src/flux/semantic/env.rs#L28-L33

This means that for every variable assignment in a flux program, type inference walks the entire stdlib each time. This is not necessary as the top level of the type environment is guaranteed not to have any free variables.

This issue is for updating the type environment's implementation of `free_vars()` so that when at the top level, an empty list is returned. With this update, type inference will no longer be quadratic in the global number of variable assignment statments(including the stdlib).

**Comment by wolffcm** [comment]
Is this a blocking issue for landing the algo-w work?

**Comment by jlapacik** [comment]
Yes this should be a blocker.
