### ISSUE TITLE
Remove "flux" dependency on "libflux/go/libflux"

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#2521]
The root package `flux` should not depend on Rust code, since it makes almost any client that imports the root package require Rust to build.

Here's a picture of how the repo-root `flux` package depends on `libflux/go/libflux`:

![graph](https://user-images.githubusercontent.com/7902964/74381884-2f7cc180-4da1-11ea-9b1c-3fad87eb2d1b.png)

We should make the top-level `flux` package follow the "standard package layout":
https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1

In particular, only the Flux domain types should be in the root package, and nothing in the root package should depend on subpackages, perhaps with the exception of cross-cutting packages like `memory` and `codes`.

The packages `values` and `semantic` currently depend on Rust, but that will be addressed in #2520 and #2519.  The root package can continue to depend on them once those issues are fixed.

The `Eval*` methods that need to execute Flux, as well as `Register*` methods that register stdlib Flux functions should be moved into subpackages.

**Comment by jsternberg** [comment]
The registering methods are now mostly refactored to be contained to `runtime.go`. It should be possible to move that code, and the eval code, to a `runtime` package. So `github.com/influxdata/flux/runtime` and move the runtime and the eval and register functions into that package to break that place in the `flux` package.

**Comment by wolffcm** [comment]
DOD:
- Flux root package has no dependency on libflux

**Comment by jsternberg** [comment]
I'm going to work on the dependent packages first. I'm leaving myself assigned, but if you take this before I put it back in progress, assign yourself and I can give you my in progress work.

**Comment by jsternberg** [comment]
A PR for this is up now. It moves the runtime sections into a separate package which should isolate the parts that use libflux. It still depends on semantic though for the things like monotype.

**Comment by jsternberg** [comment]
The runtime has now been refactored into a separate package and so all of the functions that depended on libflux directly are now in there instead. I moved the parser to the `runtime` package too even though I'm not sure that completely belongs.

The package still depends on libflux through semantic, but it doesn't depend on it directly.
