### ISSUE TITLE
Diff from go-cmp very hard to read for semantic.MonoType

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#2524]
This only happens on the `feat/use-algo-w` branch.

In our tests that compare want vs. got semantic graphs, if there is a difference in one of the fields of type `semantic.MonoType`, the output from `cmp.Diff` is very hard to read:
```Go
Object: &semantic.IdentifierExpression{
     loc:  semantic.loc{Start: s"1:8", End: s"1:9", Source: "r"},
     Name: "r",
     typ: semantic.MonoType{
         mt: 0x04,
         tbl: &fbsemantic.Row{
             _tab: flatbuffers.Table{
             Bytes: []uint8{
                 0x10,
                 0x00,
                 0x00,
                 0x00,
                 0x00,
                 0x00,
// <... repeats for many lines>
```
I've tried numerous combinations of `cmp.Transformer` to no avail.

There is no problem detecting differences, so if the test passes, everything is fine.  But when the test fails, it's very difficult to see what's going on.

To reproduce, take an existing test, and tweak something to generate an extra semantic graph expression node.  Every expression node has a type, so this will trigger it for example:
```diff
diff --git a/stdlib/universe/map_test.go b/stdlib/universe/map_test.go
index 585276ce..b66d0ed2 100644
--- a/stdlib/universe/map_test.go
+++ b/stdlib/universe/map_test.go
@@ -34,7 +34,7 @@ func TestMap_NewQuery(t *testing.T) {
                                                        Fn: interpreter.ResolvedFunction{
-                                                               Fn:    executetest.FunctionExpression(t, "(r) => r._value + 1"),
+                                                               Fn:    executetest.FunctionExpression(t, "(r) => r._valuee * 1 - 17"),
                                                                Scope: valuestest.Scope(),
```

**Comment by jsternberg** [comment]
I thought we had a transformer added for `semantic.MonoType` that would call `.String()` on it. Maybe we're not using the semantic options?

It seems that test itself uses a query test helper that doesn't use the semantic comparison options. Maybe we can add the transformers from semantic to that test utility?

**Comment by wolffcm** [comment]
I believe that we are using the transformer, but I'm not sure why the diff output still shows the byte array instead of the String.

**Comment by jsternberg** [comment]
Ah yes. I see the semantic options are getting included in the list of comparison options. We will have to investigate why it is outputting the byte array instead of the transform.
