### ISSUE TITLE
keyValues incorrectly works with columns with same values

### ISSUE THREAD

**Issue by vazhem** [influxdata/flux#2528]
Version: Influxdb 1.7.6

keyValues() function incorrectly handles columns which have the same value and drop all except one.
Example of table which is handled incorrectly:
```
#datatype,string,long,string,long,long,long
#group,false,false,false,false,false,false
#default,_result,,,,,
,result,table,void,field_1,field_2,field_3
,,0,1,0,0,0
```
keyValues(keyColumns:["field_1","field_2","field_3"]) on it produces only field_1 key when it should produce field_1, field_2, field_3.

Function works correctly when columns have different values.

Repro:
```
curl localhost:8086/api/v2/query -XPOST -sS \
-H 'accept:application/csv' \
-H 'content-type:application/vnd.flux' \
-d 'import "csv"
csv.from(csv:"#datatype,string,long,string,long
#group,false,false,true,false
#default,_result,,,
,result,table,_field,_value
,,100,field_1,0
,,101,field_2,0
,,102,field_3,0")
|> set(key: "void", value: "1")
|> pivot(rowKey:["void"],columnKey: ["_field"],valueColumn: "_value")
|> keyValues(keyColumns:["field_1","field_2","field_3"])'
```
Output:
```
#datatype,string,long,string,long
#group,false,false,false,false
#default,_result,,,
,result,table,_key,_value
,,0,field_1,0
```
Expected output:
```
#datatype,string,long,string,long
#group,false,false,false,false
#default,_result,,,
,result,table,_key,_value
,,0,field_1,0
,,0,field_2,0
,,0,field_3,0
```

**Comment by russorat** [comment]
@vazhem thank you for the issue! we will take a look.

**Comment by vazhem** [comment]
Any plans to fix?

**Comment by nathanielc** [comment]
@vazhem Yes there are plans to fix this but I don't have a specific timeline yet.

**Comment by nikolay-t** [comment]
As a walk-around, it is possible to apply keyValues to each column separately, then union:

`import "csv"
zx = csv.from(csv:"#datatype,string,long,string,long
#group,false,false,true,false
#default,_result,,,
,result,table,_field,_value
,,100,field_1,0
,,101,field_2,0
,,102,field_3,0")
|> set(key: "void", value: "1")
|> pivot(rowKey:["void"],columnKey: ["_field"],valueColumn: "_value")
zx1 = zx |> keyValues(keyColumns:["field_1"])
zx2 = zx |> keyValues(keyColumns:["field_2"])
zx3 = zx |> keyValues(keyColumns:["field_3"])
union(tables:[zx1,zx2,zx3])`
