### ISSUE TITLE
Translate Semantic graph to AST for Filter functions

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2530]
The `influxdb.source` in vanilla Flux needs to ability to translate semantic graph back to an equivalent AST representation.

NOTE:

This process involves converting semantic to AST, so the round trip of semantic to AST back to semantic should produce the same semantic graph.
Conversely the round trip of AST to semantic to AST does NOT need to produce the same AST.

In other words we are not trying to reproduce the AST the user created, just something semantically equivalent.

**Comment by jsternberg** [comment]
For this issue, serializing function values or function calls doesn't need to be done. It may work in the future, but there are issues with scoping and serializing function calls is very complicated and we don't need it.

For our purposes, we do not need this:

```
from()
    |> range()
    |> filter(fn: (r) => {
        hosts = from() |> range() |> filter() |> tableFind() |> getColumn()
        return r.host in hosts
    })
```

The following needs to work:

```
field_name = "usage_user"
from()
    |> range()
    |> filter(fn: (r) => r._field == field_name)
```

The serialization may need a scope to work and it may need to resolve values. For now, avoid trying to serialize functions. There's a function `resolveValue` in one of the packages that does this in one place.
