### ISSUE TITLE
Implement record extension

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#2537]
Flux record types are extensible and have scoped labels. A record's properties are ordered, and a record may have multiple properties with the same label. This issue is for implementing these semantics in the interpreter, compiler, and execution engine.
```
r = {a: 1, b: 2} // r has type {a: int | b: int}
s = {r with a: 3.3} // s has type {a: float | a: int | b: int}
```
Currently the interpreter, compiler, and execution engine implement update semantics for record extensions, meaning records cannot have multiple properties with the same label. And tables cannot have multiple columns with the same name. This issue is for updating the semantics so that record types and the operations that act on them are consistent.

The `interpreter` and `compiler` packages will not require much work in order to update. However `ColListTableBuilder` in the `execute` package will need to be updated so that it supports adding already existing columns. 

Some questions that need to be answered:
1. Should users see duplicated columns when they `yield` tables?
2. Can we remove duplicated columns that are never referenced in order to reduce unnecessary data transfer during execution?

**Comment by nathanielc** [comment]
My thoughts:


>    Should users see duplicated columns when they yield tables?

No, the duplication/nesting of fields should be an implementation detail and should not be exposed to the user.

>     Can we remove duplicated columns that are never referenced in order to reduce unnecessary data transfer during execution?

How I am not sure on the details but yes we should remove the shadowed fields.

Going a step further I would like the behavior of `drop(columns:["foo"])` to drop all `foo` fields not just the first one. This likely won't be part of the pure algo w pass but as a post processing step where we mark an shadowed fields as such and remove them from all types. Then when `drop` gets called we can guratnee that all of them are dropped. This goes back to the first question where we want this to be an implementation detail not something the user is exposed to.

**Comment by jlapacik** [comment]
Why was this issue closed? This issue is about unifying the semantics surrounding extensible records in both the type system and runtime.

**Comment by nathanielc** [comment]
ok I misunderstood, thanks for catching that
