### ISSUE TITLE
Cannot unify list with semantic.Nature

### ISSUE THREAD

**Issue by mcassaniti** [influxdata/flux#2557]
When running the following query in Flux V0.59.5 I get the above error.

```
import "experimental"

data_table = from(bucket: "ts")
  |> range(start: -15m)
  |> filter(fn: (r) => r._measurement == "cpu" and r._field == "usage_active")
  |> last()
  |> group()

// Intentionally not providing suitable data for the next query
// This is an example after all
filtered = data_table |> drop(columns: ["host"])

// If there's data in filtered then return a list from it.
// If there's no data in filtered then fake up a result.
filtered_list = if exists filtered.host then filtered
  |> tableFind(fn: (key) => 1 == 1)
  |> getColumn(column: "cpu")
else data_table
  |> experimental.set(o: {"cpu": "!!!!!"})
  |> tableFind(fn: (key) => 1 == 1)
  |> getColumn(column: "cpu")

filtered_data = data_table
  |> filter(fn: (r) => not contains(value: r.cpu, set: filtered_list))
```

```
type error 24:28-24:70: cannot unify list with semantic.Nature
```

The weird if statement is there because:
  1. tableFind will return an error if it cannot find a table, and the variable filtered could have no results
  1. https://github.com/influxdata/flux/issues/1947#issuecomment-584449709

**Comment by jsternberg** [comment]
The error message is a bit opaque, but the reason why there is a type error is because `|> drop()` will return a list of tables and so `filtered.host`, which can only be used to access a single record, isn't a valid operation for a list of tables.

It seems like you are having some problems with using `tableFind` and are seeking a way to write your query with `if exists` to work around that problem. Can you expand on this part?

> tableFind will return an error if it cannot find a table, and the variable filtered could have no results

It seems to me that's the underlying problem.

**Comment by mcassaniti** [comment]
@jsternberg You're right, it's all to work around `tableFind`. We need an array from `getColumn` to use in the `not contains()` filter. This comes from a list of tables which only has one table in it (`filtered` in the example). That table might be empty, so `tableFind` will have an error. I'm after a way to return an empty array if that is the case.

**Comment by adriandt** [comment]
Hi @mcassaniti, to update on this, I attempted to find a solution with current flux but could not. Full disclosure, I'm a new member to the team, so this may not be definitive.

- My first attempt was to use union to add some default data for tableFind to spit out, but there is no control on the order of output of union so it isn’t possible to put the defaults last.
- My second attempt was to use `lets_count = data |> count` to count the input to `tableFind` and if not exists lets_count.count then return some default `[“foo”]`. This seemed like the right approach, but I’m getting some type unification errors.

```
filtered_list =
    if not exists lets_count.count then
        ["foo"]
    else
        data_table
            |> tableFind(fn: (key) => true)
            |> getColumn(column: "cpu")
```
This gives: `{"code":"invalid","message":"type error 24:3-29:32: cannot unify list with semantic.Nature"}`

So my next move was to test it on the `use-algo-w` branch, which represents a big move forward with the flux type system, but that did not allow the types to unify. Probably a more experienced flux developer could shed some more light on this.

FYI I'm off for a few days and will catch up with responses next week.

**Comment by mcassaniti** [comment]
@adriandt Thank you very much for the feedback. 

Is there some way for me to provide more feedback on other things we're doing with our Flux scripts to Influxdata? I'm on the Slack channel if that helps. I'd like to help out where I can but TBH the code scares me and there's currently no design information to understand why things are built a certain way, or how to use them best.

**Comment by adriandt** [comment]
@mcassaniti Hi, sorry I was off for a couple days. Let me put you in touch with a community manager.

**Comment by mcassaniti** [comment]
Any forward progress on this? It's the one section of code that is preventing me from deploying to production.

**Comment by adrian-thurston** [comment]
Hi @mcassaniti I'm hearing that the work on the use-algo-w branch will solve this particular problem. The testing I described above was supposed to check that, but I may have botched that due to some building errors I was experiencing earlier. That branch is expected to land in master soon.

**Comment by adrian-thurston** [comment]
@mcassaniti there are now two branches concerning this .. the first allows `tableFind` to return nil and `getRecord` and `getColumn` to return empty objects/arrays in that case. The second branch allows `contains` to work when the set is an empty array.

https://github.com/influxdata/flux/tree/feat/table-find-not-found
https://github.com/influxdata/flux/tree/feat/contains-empty-array

**Comment by adrian-thurston** [comment]
There are some more issues to solve though, as it introduces some new kinds of nil to the runtime and we need to figure out how that is handled throughout, so I can't push it through right away.

Note this is based off the `use-algo-w` branch.

**Comment by adrian-thurston** [comment]
See PR #2695 for resolution and issue #2730 for more discussion.

This still leaves open the type checker issue exposed by the workaround that uses `if`, however there is a solution for the original problem.
