### ISSUE TITLE
Add math.rand functions

### ISSUE THREAD

**Issue by sanderson** [influxdata/flux#2560]
I'm finding test cases where having a random number generator would be helpful. We could use the go `math/rand` package. In Flux the functions could look like:

```js
import "math"

math.randFloat(max: 1.0,  min: -1.0)
math.randInt(max: 9223372036854775807,  min: -9223372036854775807)
math.randUint(max: 18446744073709551615,  min: 0)
```

**Comment by jsternberg** [comment]
Can you expand on this? Like how you are using them. We are considering modifying the `generate` package to make multiple generators of different types and patterns and I am curious about your specific case. The prototype in `internal/gen` may work if you are looking for random numbers.
