### ISSUE TITLE
Tests in `stdlib/sql` for sql validation are failing 

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/flux#2572]
Tests `TestFromSocketUrlValidation` and `TestFromSqlUrlValidation` expect the error message "no such host", but are getting different failures. 

Failure message from `TestFromSocketUrlValidation`: 
```
        source.go:180: unexpected result -want/+got:
              string(
            - 	"error in creating socket source: dial unix notfound:12345: connect: no such file or directory",
            + 	"no such host",
              )
```

**Comment by jsternberg** [comment]
We think this might be a configuration issue with the computer, but we're not really sure and so we're going to investigate this and write down what we found to fix this issue just in case we run into it again in the future.

**Comment by fchikwekwe** [comment]
I think this was just an issue with me recompiling some of the code. Closing.

**Comment by adriandt** [comment]
FWIW, I just built and tested on algo-w branch, with go 1.14, and did not experience the issue.
