### ISSUE TITLE
Support building libflux with the musl-gcc compiler

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2582]
The libflux library should support building with the musl-gcc compiler if it is set. This involves using the musl target for rust.

**Comment by jsternberg** [comment]
The above works if you do the following:

```
$ rustup target add x86_64-unknown-linux-musl
$ cargo build --release --libs --target x86_64-unknown-linux-musl
```

`pkg-config` can be modified to do the above and to move the binaries into the appropriate locations. Once that is done, you do this on Linux.

```
$ apt-get update && apt-get install -y --no-install-recommends musl musl-tools
$ export CC=musl-gcc
$ go build -ldflags '-extldflags "-fno-PIC -static" -buildid=' -buildmode pie -tags 'osusergo netgo static_build' -o flux ./cmd/flux
```

This builds a fully static binary.

Additionally, `pkg-config` has to be modified to add `-lpthread`. It seems like cgo does this automatically, but when you are doing a static build like the above, go may decide not to add `-lpthread`.
```

**Comment by jsternberg** [comment]
This issue gave a good workaround for this: https://github.com/golang/go/issues/26492

We can update `pkg-config` to take the `--static` flag and pass it through. Then we can configure `pkg-config` to be invoked with the `--static` flag when the `static_build` tag is used as in this example here: https://github.com/kolyshkin/goploop/blob/master/ploop_link_static.go

It's not the most ideal, but I think this should work. That will take care of the Rust side. Then we just need to install the `musl-tools` package and set the `musl-gcc` compiler in any projects where we are using that.

**Comment by nathanielc** [comment]
Why should Flux support the `musl-gcc` compiler? Can you add some details to this issue for the motivation for the change?

**Comment by rockstar** [comment]
Building libflux and flux with `musl-gcc` allows us to build a static binary without a dependency on the system libc. For docker containers, this means simpler (and questionably smaller) images, and I _believe_ the need is driven by better support for CD.

**Comment by nathanielc** [comment]
Is this because of Rust? With Go you can force it to build a static binary that doesn't depend on libc.

**Comment by rockstar** [comment]
Exactly, and with rust by itself, you can do the same. It's the bridge between the two that brings with it some complexities (see also cross-compile).

**Comment by nathanielc** [comment]
OK, thanks for the explanation.
