### ISSUE TITLE
Support passing functions as arguments to compiled functions

### ISSUE THREAD

**Issue by jpacik** [influxdata/flux#2587]
Currently we cannot compile a function that has any functional arguments.

**Comment by adriandt** [comment]
@jlapacik I'm missing some background terminology to understand this. If we cannot do the thing we call "compile" on functions with functional arguments, what is the thing we can do called? Surely we execute them somehow?

**Comment by jlapacik** [comment]
Sorry for the confusion @adriandt. What we call "compile" is not actually compiling. When I say "compiled' functions, these are the anonymous functions that are evaluated during transformations like `map` and `filter`. In the specific case of `map` or `filter`, these functions take a single argument representing a record or row of a table.

```
map(fn: (r) => ...)
```
They support other argument types beside records, but they do not support other function types at the moment.
