### ISSUE TITLE
Expose pure-Go literal parsers

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2588]
The `internal/parser/strconv.go` literal parsers are used externally and are useful for external code. They should be exposed publicly so pure Go code does not have to go through the `parser` package to access these.

**Comment by fchikwekwe** [comment]
Right now as per [this PR](https://github.com/influxdata/influxdb/pull/17104) these parser methods are duplicated in InfluxDB repo. Perhaps once these methods have been exposed publicly in Flux, we can consider removing the duplicated functions.
