### ISSUE TITLE
Memory leak in libflux

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#2589]
We use a function `flux_free()` to release memory that has been allocated by Rust:
https://github.com/influxdata/flux/blob/master/libflux/src/flux/lib.rs#L207

This function accepts a `void*` which won't work here, because (for example) a pointer to `ast::Package` itself contains other references to other items that need to be freed. For this to work right, we need to cast the pointer to the precise thing being freed.

That means we need a separate `flux_free` function for each kind of thing that we need to free:
- `flux_free_ast_pkg`
- `flux_free_string`
- `flux_free_error`

**Comment by jsternberg** [comment]
We may be able to use `Box<dyn Any>` for this. I wonder if we have `Box<dyn Any>` it might cause the destructor to be virtual.

**Comment by wolffcm** [comment]
Fixed by #2603
