### ISSUE TITLE
feat (geo): Expose function to calculate the s2 cell Id

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/flux#2597]
It is possible that users may have already ingested large amounts of geo data within the platform.  We are already embedding the S2 library within Flux and it would be handy to expose a Flux function which allows for the calculation of the s2_cell_id using that library.  

This would allow users to write tasks which could then determine the s2_cell_id based on lat/lon data which is ingested through Tasks or other systems....and potentially re-write existing data.

**Comment by alespour** [comment]
It is already exposed, but the name is not very intuitive
```
import "experimental/geo"
geo.getParent(point: {lat: -73.80014, lon: -73.4630336}, level: 11)
```
returns `bb3e47c`

The function takes either `token` or `point` param and cell `level`. Should rename to eg. `s2CellIDToken`?
```
geo.s2CellIDToken(point: {lat: -73.80014, lon: -73.4630336}, level: 11)
```

**Comment by wolffcm** [comment]
I like option 2, renaming the existing function. I think it makes the functionality being exposed more clear.

Rather than extend it to return more than one thing, maybe as a separate issue we could add functions to translate between the numeric ID and the string token, if that's ever needed.
