### ISSUE TITLE
The following query does not work but should

### ISSUE THREAD

**Issue by rtucker-mozilla** [influxdata/flux#261]
from(bucket: "telegraf/autogen")
  |> range(start: dashboardTime)
  |> filter(fn: (r) => r._measurement == "syslog" and r._value =~ /.*pam.*/ and (r._field == "message"))

Works if you remove the r._value =~ /.*pam.*/ or if you use just r._value =~ /.*pam.*/

**Comment by jsternberg** [comment]
This appears to work now. I tested by writing a string value and attempting to use a regular expression against `_value`.
