### ISSUE TITLE
Enable Dynamic queries in the REPL

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2626]
Now that we have a true InfluxDB source for the REPL we should be able to execute dynamic queries from the REPL.

Trying to do so right now results in this error:

```
> csv.from(csv:inData) |> tableFind(fn:(key) => true) |> getRecord(idx:0)
Error: error calling function "getRecord": error calling function "tableFind": do not have an execution context for tableFind, if using the repl, try executing this code on the server using the InfluxDB API
```

It looks like we have explicit error checking for this behavior that we need to remove/revisit in order to enable dynamic queries.

**Comment by adrian-thurston** [comment]
closed by #2759 (last point in commit message)
