### ISSUE TITLE
end-to-end test fails on CI occasionally

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#263]
CI will catch the following error occasionally using `go test -race`.

    --- FAIL: Test_QueryEndToEnd (44.04s)
    --- FAIL: Test_QueryEndToEnd/selector_preserve_time.flux (0.01s)
        failed to run query: failed to compile query: type error 4:5-4:23: cannot unify object with semantic.Nature

It has only happened to me twice but both times it occurred on the above end-to-end test.

**Comment by mark-rushakoff** [comment]
Reproducible with `go test -count=100 -run=Test_QueryEndToEnd/selector_preserve_time.flux ./functions/transformations/` -- `-race` isn't necessary. Usually have to run it a few times to get it to fail.

I put a panic where the error was originating, and got this stack trace from master @ ab39f6de2c4df52e874cdb9f2463ff9cbde18ab7:

```
goroutine 259 [running]:
testing.tRunner.func1(0xc0049c4000)
	/Users/mr/gotip/src/github.com/golang/go/src/testing/testing.go:815 +0x387
panic(0x17b8d80, 0x19b6f00)
	/Users/mr/gotip/src/github.com/golang/go/src/runtime/panic.go:513 +0x1b7
github.com/influxdata/flux/semantic.object.unifyType(0xc003d1dad0, 0x1f53da8, 0x0, 0x0, 0xc003d245f0, 0x1, 0x1, 0xc0051780f0, 0x19ead00, 0xc005183ff0, ...)
	/Users/mr/go/src/github.com/influxdata/flux/semantic/poly_types.go:574 +0x2f0
github.com/influxdata/flux/semantic.unifyTypes(0xc0051780f0, 0x19eaee0, 0xc003d28900, 0x19ead00, 0xc005183ff0, 0x1, 0x0, 0x0)
	/Users/mr/go/src/github.com/influxdata/flux/semantic/solve.go:146 +0x4f
github.com/influxdata/flux/semantic.function.unifyType(0xc003d1daa0, 0x1f53da8, 0x0, 0x0, 0x19eaee0, 0xc003d28940, 0x18d85d5, 0x6, 0xc0051780f0, 0x19eae20, ...)
	/Users/mr/go/src/github.com/influxdata/flux/semantic/poly_types.go:384 +0x631
github.com/influxdata/flux/semantic.unifyTypes(0xc0051780f0, 0x19eae20, 0xc003d28980, 0x19eae20, 0xc003d28f00, 0xc003d1cbd0, 0x0, 0x0)
	/Users/mr/go/src/github.com/influxdata/flux/semantic/solve.go:146 +0x4f
github.com/influxdata/flux/semantic.(*Solution).solve(0xc005138680, 0xc005138680, 0xc0045692e0)
	/Users/mr/go/src/github.com/influxdata/flux/semantic/solve.go:84 +0x8a0
github.com/influxdata/flux/semantic.SolveConstraints(0xc00456e060, 0xc004543400, 0xc004d40bb0, 0xc004563fb0, 0xc00456e060)
	/Users/mr/go/src/github.com/influxdata/flux/semantic/solve.go:15 +0x55
github.com/influxdata/flux/semantic.InferTypes(0x19ddfa0, 0xc004543400, 0x57, 0xc000141080, 0xc000e567e0, 0x61)
	/Users/mr/go/src/github.com/influxdata/flux/semantic/inference.go:10 +0x8a
github.com/influxdata/flux/interpreter.(*Interpreter).Eval(0xc004523320, 0x19de3a0, 0xc004543090, 0x0, 0x0)
	/Users/mr/go/src/github.com/influxdata/flux/interpreter/interpreter.go:93 +0x154
github.com/influxdata/flux.Eval(0xc004523320, 0xc000e56690, 0x61, 0x3, 0xc000e05708)
	/Users/mr/go/src/github.com/influxdata/flux/compile.go:78 +0x9e
github.com/influxdata/flux.Compile(0x19db660, 0xc004523200, 0xc000e56690, 0x61, 0xbef164c8a1c87fa0, 0x2b508572, 0x1f359c0, 0x0, 0x0, 0x0, ...)
	/Users/mr/go/src/github.com/influxdata/flux/compile.go:50 +0x1f6
github.com/influxdata/flux/lang.FluxCompiler.Compile(0xc000e56690, 0x61, 0x19db660, 0xc004523200, 0xc000046a00, 0x19db660, 0xc004523200)
	/Users/mr/go/src/github.com/influxdata/flux/lang/compiler.go:34 +0x89
github.com/influxdata/flux/querytest.FromCSVCompiler.Compile(0x19d26a0, 0xc000e6b180, 0xc000e56540, 0x6c, 0x19db660, 0xc004523200, 0xc004542101, 0x0, 0xc0014fa9b8)
	/Users/mr/go/src/github.com/influxdata/flux/querytest/compiler.go:22 +0x49
github.com/influxdata/flux/control.(*Controller).compileQuery(0xc0001563c0, 0xc0014fa8c0, 0x19d26e0, 0xc000e23400, 0x4, 0xc0014fa8c0)
	/Users/mr/go/src/github.com/influxdata/flux/control/controller.go:172 +0x6b
github.com/influxdata/flux/control.(*Controller).Query(0xc0001563c0, 0x19db5e0, 0xc0000e0000, 0x19d26e0, 0xc000e23400, 0xc000064d40, 0xc000064d40, 0x100e4a8, 0x30)
	/Users/mr/go/src/github.com/influxdata/flux/control/controller.go:113 +0xa8
github.com/influxdata/flux/querytest.(*Querier).Query(0xc0000ca858, 0x19db5e0, 0xc0000e0000, 0x19c82c0, 0xc0045231a0, 0x19d26e0, 0xc000e23400, 0x19cf9a0, 0xc000e233e0, 0x0, ...)
	/Users/mr/go/src/github.com/influxdata/flux/querytest/execute.go:18 +0x7a
github.com/influxdata/flux/functions/transformations_test.QueryTestCheckSpec(0x19f0ae0, 0xc0049c4000, 0xc0000ca858, 0x19d26e0, 0xc000e23400, 0x19cf9a0, 0xc000e233e0, 0xc0055bb180, 0x275)
	/Users/mr/go/src/github.com/influxdata/flux/functions/transformations/transformations_test.go:116 +0xd4
github.com/influxdata/flux/functions/transformations_test.testFlux(0x19f0ae0, 0xc0049c4000, 0xc0000ca858, 0xc000e56000, 0x65, 0x18d77b9, 0x5)
	/Users/mr/go/src/github.com/influxdata/flux/functions/transformations/transformations_test.go:109 +0x4ca
github.com/influxdata/flux/functions/transformations_test.Test_QueryEndToEnd.func1.1(0xc0049c4000)
	/Users/mr/go/src/github.com/influxdata/flux/functions/transformations/transformations_test.go:63 +0x7c
testing.tRunner(0xc0049c4000, 0xc004523050)
	/Users/mr/gotip/src/github.com/golang/go/src/testing/testing.go:850 +0xbf
created by testing.(*T).Run
	/Users/mr/gotip/src/github.com/golang/go/src/testing/testing.go:901 +0x34d
```

My hunch, without digging into it, is something is unintentionally relying on map ordering and once in a few hundred times it picks a value that results in the error.

**Comment by mark-rushakoff** [comment]
I've been able to reliably reproduce the error with `go test -failfast -count=100 -run=Test_QueryEndToEnd/selector_preserve_time.flux ./functions/transformations/`.

The script in question is
```
from(bucket:"test")
    |> range(start:2018-05-22T19:53:26Z)
	|> top(n:3)
	|> group(by:["host"])
```

And I would say the test fails about once every 200-300 executions, so it's reasonably likely that this is a bug that would trigger under production load.

I threw some prints in to debug what's going on here, and I found that it seems to be related to this line:  https://github.com/influxdata/flux/blob/fa7d69e51ecde2e9aa094f87eb9c5b5229ccd233/semantic/poly_types.go#L443

In the code path of the intermittent error, `fmt.Printf("%#v", leftPipeType)` there always prints out `semantic.object{krecord:semantic.ObjectKind{properties:map[string]semantic.PolyType{"kind":2}, lower:semantic.LabelSet{}, upper:semantic.LabelSet{"kind"}}}`. 

When the test passes, `fmt.Printf("%v", rightPipeType)` prints `t84`. In the rare case when it fails, that prints out `int` instead.

I did notice that the line linked above is inside a range over a map, if that helps narrow down the root cause at all: https://github.com/influxdata/flux/blob/fa7d69e51ecde2e9aa094f87eb9c5b5229ccd233/semantic/poly_types.go#L409


/cc @nathanielc

**Comment by nathanielc** [comment]
@mark-rushakoff Thanks for the detailed exploration, I am looking into this now..

**Comment by jlapacik** [comment]
This error occurred again when running the unit tests for this PR https://github.com/influxdata/flux/pull/366 .

**Comment by jlapacik** [comment]
The error occurs in this bit of code when generating type constraints:
```go
case *ExternalVariableAssignment:
	// Do not trust external type variables,
	// substitute them with fresh vars.
	ftv := n.ExternType.freeVars(nil)
	subst := make(Substitution, len(ftv))
	for _, tv := range ftv {
		subst[tv] = v.cs.f.Fresh()
	}
	t := subst.ApplyType(n.ExternType)
	// Check if this type knows about its kind constraints
	if kt, ok := t.(KindConstrainter); ok {
		tv := v.cs.f.Fresh()
		v.cs.AddKindConst(tv, kt.KindConstraint())
		t = tv
	}
	existing, ok := v.env.LocalLookup(n.Identifier.Name)
	if ok {
		v.cs.AddTypeConst(t, existing.T, n.Location())
	}
	scheme := v.scheme(t)
	v.env.Set(n.Identifier.Name, scheme)
	return nil, nil
```

Each external variable assignment has zero or more free type variables. For each of these free type variables we generate a new "fresh" type variable and substitute the old one for the new one. The problem arises because every call to `Fresh()` generates a new type variable of the form `t<n>` starting with `t0`. However external variable assignments have type variables that were generated by a separate inference process, hence there could be **collisions** between the free type variables in the external assignments and the new type variables that were generated by the current inference process.

In particular, after performing type inference over the builtin functions and scripts, the `top` function has the following type scheme:

    (columns: [string], ^n: t30, ^tables: t32) -> t340

where the variables `t31`, `t32`, and `t340` are all free. We then run type inference on the following script:

    from(bucket:"test")
        |> range(start:2018-05-22T19:53:26Z)
        |> top(n:3)
        |> group(by:["host"])

When generating the new constraint set, we produced the following substitution for the `top` function:

    t340 = t30
    t30 = t32
    t32 = t31

And the substitution occurred in the following steps:

    STEP 1 [t340 = t30]: (columns: [string], ^n: t30, ^tables: t32) -> t30
    STEP 2 [t32 = t31]: (columns: [string], ^n: t30, ^tables: t31) -> t30
    STEP 3 [t30 = t31]: (columns: [string], ^n: t31, ^tables: t32) -> t31  // WRONG, return type should not have been overwritten

`n` was unified with type integer, but the return type of `top` is not an integer, and hence unification failed.

The solution is to generate fresh type variables in such a way that there are no name collisions with the type variables present in the external variable assignments.
