### ISSUE TITLE
Type error message is backwards

### ISSUE THREAD

**Issue by nisley** [influxdata/flux#2646]
Error message question:
>cannot add type constraint @ geo.flux|80:19-81:61: type error 0:0-0:0: invalid record access "lon": float != string

Since my "lon" was a string I would expect:

>invalid record access "lon": string != float

in other words, lon was a string, which isn't the expected float type.

**Comment by jcestibariz** [comment]
I had the same problem, the message should be explicit, something like: 

invalid record access "foo": found  string, expecting float

**Comment by rickspencer3** [comment]
@jcestibariz would you be up to a PR? If so, I can get someone to help you figure out where to look and help with a code review.

**Comment by jcestibariz** [comment]
@rickspencer3 sure I'll take a look. Thank you.

**Comment by jcestibariz** [comment]
Looks like this was fixed in #2850 I'm using influx 2 beta 10, I guess it hasn't landed in influx yet.
