### ISSUE TITLE
Quantile should require the `method` parameter or assume a valid default.

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2648]
A common mistake with the `quantile` function is to forget the `method` parameter. If you do you get this error message:

```
error calling function “quantile”: unknown method
```

That makes it sound like the `quantile` method does not exist. But what it is trying to say is that the `method` parameter was missing and therefore unknown.

We should update the error from `unknown method` to `invalid quantile method, please check your 
method" parameter` or something along those lines

Additionally it seems that the type signature of `quantile` does not require the `method` parameter but then will error if its not provided. We should either require it at the type level, or we should give it a default value so its not required.  I vote is to default to `estimate_tdigest` so you only need the `method` parameter if you are doing something more specific.

**Comment by metoule** [comment]
The 1.8 documention (I didn't try with Influx 2.0) states that the `method` parameter is optional: https://docs.influxdata.com/influxdb/v1.8/flux/guides/percentile-quantile/#find-the-value-representing-the-99th-percentile

**Comment by Anand25021998** [comment]
I tried this with v1.8.2 and the issue persists.
