### ISSUE TITLE
Remove ambiguities in the semantic graph

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2666]
The semantic graph's purpose is to represent the functional behavior of a Flux script. As such there should not be two ways to represent the same exact script. 

For example syntactically 

```
() => true
() => { return true}
```

these are different but semantically they are the same. We should have a single semantic representation of the above.

**Comment by jsternberg** [comment]
I'm halfway through this but I'm blocked on #2702 being merged. There's parts I have to fix that would be easier to fix with that merged. Since this is non-essential, I am going to work on something else while waiting for #2702 to be merged.
