### ISSUE TITLE
Function: day 0 time shift with threshold

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/flux#2669]
There are number of time series analysis use cases where there are multiple series which are each shifted in time.  In order to compare them, it is useful to determine what represents time 0 for each series and then normalizing the time dimension.  Having a convenience function within Flux which would perform this time shift would be incredibly powerful.

The current `timeShift()` function adds a fixed amount of time -- and I believe a variable amount of time by series is required.
https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/timeshift/

Here are two poignant examples given what's going on currently:
The spread of COVID-19 is occurring globally, but the start of the spread is occurring in different locations at different times.

Using a specific country tag as a way of defining a series (or even using more specific `s2_cell_id` based on `lat/lon` data) to define a series along with a way to shift each series to a normalized starting point.

Example 1:
The starting point of the series could be based on the first reported case...or first data point in the series.  Take the `first()` from a series, store that `_time` column as a variable, convert it to `ns`, subtract it from each `_time` column for all data points in that series.  This delivers a normalized `_time = 0` for all data points.  But, this needs to be repeated for each series within the data set.

Example 2:
The starting point of the series is based on evaluating a specific conditional.  In this case, we might suggest that there is a minimum threshold for cases which is required before we want to start the comparison.  Rather than taking the `first()` report, we want to evaluate the data with a conditional and use the `first()` data point which evaluates to `TRUE` as `_time = 0` for that series (repeating the process outlined in Example 1).

**Comment by sanderson** [comment]
@timhallinflux This has been in the back of my mind for a long time. I worked up a prototype this morning and it solves the 1st use case. The 2nd use case is a little more complicated. If there's a minimum threshold and once crossed, the data won't fall below that threshold, this could be done with a simple `filter()` call. However, if after the threshold is crossed, values may drop back below the threshold and we want to continue tracking it, we have to find a way to:

1. Identify the start of a new group/series
2. Optionally identify the end of a group/series
3. Increment a group/series ID that uniquely identifies each series.

**Comment by timhallinflux** [comment]
if the field value is a counter...it won't drop below. (i.e. only increases).

Perhaps, we start with the assumption that the value cannot/will not drop below?
