### ISSUE TITLE
flux validation for empty query returns valid.

### ISSUE THREAD

**Issue by docmerlin** [influxdata/flux#268]
Validation should return invalid for empty queries and for queries that just have options but no actual query body.  Right now it is returning valid for queries that have no query body but do have options.

**Comment by wolffcm** [comment]
Is this fixed already?  If I issue a query via `curl` I get an error:
```
curl -v -d '{"query": "option task = {name: \"mean\", every: 1h}"}' --header "Authorization: Token zzz" http://localhost:9999/api/v2/query
```
This produces a reasonable error:
```
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/csv; charset=utf-8
< X-Influx-Error: invalid query: query has no root nodes
```

**Comment by docmerlin** [comment]
Looks like it was fixed, maybe the new parser fixed it?  However shouldn't that be a 4xx not a 5xx?

**Comment by wolffcm** [comment]
I agree it should be a 4xx error code.

**Comment by docmerlin** [comment]
Looks like this was fixed.
