### ISSUE TITLE
select count(distinct(value)) from measurement in flux?

### ISSUE THREAD

**Issue by sboesebeck** [influxdata/flux#2698]
I thought this would be an easy one, but I actually can't get it to work. I have a query in normal QL that uses `select count(distinct(value))` and I need to use that in a join in order to calculate some percentage.
But it never works. I tried a ton of different wayis, none of which produced a useful result.

latest Version is this:
```
sm=from(bucket:"db/autogen")|>range($range)|> filter(fn: (r) =>r._measurement == "m" and  r._field == "tid") |>group(columns:["tid"]) |>aggregateWindow(every: 1h, fn: count)

op=from(bucket:"db/autogen")|>range($range)|> filter(fn: (r) =>r._measurement == "o" and r.env == "production" and r._field == "tid" )  |>duplicate(column:"_value",as:"tidv") |>group(columns:["tidv"]) |> aggregateWindow(every:1h,fn:count) |> duplicate(column:"_stop",as:"_time")|> group(columns:["tidv"],mode:"except") |> group(columns:["_time"]) |> aggregateWindow(every:1h,fn:sum)

join(
    tables: {d1:sm, d2:op},
    on: ["_time", "_stop", "_start"]
  )
  |> map(fn: (r) => ({
    _time: r._time,
    _value: (float(v:r._value_d2)/float(v:r._value_d1))
  })
)
```

the problem is the query with the name `op`- this does not work properly as expected. When using `distinct()` counting is not possible. Am I missing something or is flux not capable of doing such a thing?

I just want to have a graph in Grafana in the end, showing the percentage of those two values as a timeseries on 1hour time buckets. It seems quite simple... right?

**Comment by sanderson** [comment]
@sboesebeck This is better suited to discuss in the InfluxDB community and I know you already submitted a post there. Sorry for not getting to it sooner. I'm going to close this issue for now, but if we find that Flux isn't able to do what you need it to, we can open it back up.

https://community.influxdata.com/t/distinct-values-counting-in-a-join/13646/2
