### ISSUE TITLE
Modify drop implementation to not make copies of columns

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2703]
The `drop` implementation currently makes copies of the columns. Instead, it should copy how `group()` works by retaining the rows that it needs and constructing a multi-part buffer for the tables that end up grouped into the same group.

Similar to `group()`, this implementation of `drop()` will require it to read the entire stream so it can know the proper way to group the tables.

**Comment by yzhang1991** [comment]
I would like to pair with whoever is going to work on this issue. Please ping me, thank you!

**Comment by fchikwekwe** [comment]
Same. I'd like to learn on this one as well.

**Comment by jsternberg** [comment]
The `group()` implementation already uses some of these, but I started developing some alternative tooling for building tables as part of the original performance spike I was doing during winter break. The libraries are here: https://pkg.go.dev/github.com/influxdata/flux@v0.67.0/internal/execute/table?tab=doc

They enable building tables more efficiently. The `group()` implementation is also a reference.

**Comment by yzhang1991** [comment]
This is covered in #2879
