### ISSUE TITLE
type error when trying to access getColumn array record

### ISSUE THREAD

**Issue by AgrPriyank** [influxdata/flux#2713]
I've created a custom function which returns a list of column.
Whenever I try to use the result of above custom function in my map transformation (Ex- getId[0]), it returns an error saying, 'cannot unify array with semantic.array'.
What exactly does this error mean?

myseriesData
|> map(fn: (r) => ({ r with _value: getId(x: r._time)[0] }))

As I understand from above syntax, I will need to map '_value' with a single value and not a list, which I'm trying to do by accessing the first record of the list returned by getColumn function.
Why is this error occuring?

**Comment by sanderson** [comment]
@AgrPriyank What is your custom function?

**Comment by AgrPriyank** [comment]
getId = (x) => 
seriesData2 
|>  filter(fn: (r) => r._time >= x) 
|> sort(columns: ["_time"], desc: false) 
|> first()
|> tableFind(fn: (key) => key._field == "total")
|> getColumn(column: "_value")

The function basically filters out one record from the series, 'seriesData2', based on a conditional expression evaluated using time. Then it takes the first row and returns the value field.

**Comment by sanderson** [comment]
@AgrPriyank The core of the problem is that you can't query inside of a `map()` function. That's why you're getting the very vague error. See https://github.com/influxdata/flux/issues/2587. 

`getColumns` does returns an array of values, but you need the `getId` function to return a single scalar value. Use a `return` statement to return a specific index of the array:

```
getId = (x) => {
  valueArr = seriesData2
    |> filter(fn: (r) => r._time >= x)
    |> sort(columns: ["_time"], desc: false)
    |> first()
    |> tableFind(fn: (key) => key._field == "total")
    |> getColumn(column: "_value")
  return valueArr[0]
}
```

_But this will not fix the larger issue of not being able to query inside of map._

**Comment by AgrPriyank** [comment]
Does this mean I will not be able to call the custom function inside of map?
When I tried the above fix, I got a new error.
"cannot compile polymorphic function: type variable ""t79"" is not monomorphic"

**Comment by AgrPriyank** [comment]
Since it is not possible to use a function inside a map, is there any other way currently to iterate over a series and call a custom function on each of the item?

**Comment by sanderson** [comment]
Currently there is not a way to do that, but looping/iteration is high on the priority list. It's one of the last features to add to before Flux is a true Turing complete language.

**Comment by AgrPriyank** [comment]
Thanks for clarifying that! I'll close this issue and monitor the feature request.
