### ISSUE TITLE
Join query taking too long to finish

### ISSUE THREAD

**Issue by pinxtor** [influxdata/flux#2719]
I'm trying to join two series which have will have the order of data around 150k-200k in one of the series and around 2k-5k in the other one.
I'm running influx instance on a windows 10 docker machine with 4GB of RAM alloted to docker.
I have run the query multiple times but even after waiting for 40mins the query does not complete. 

Is it because of join query performance or would a powerful instance help reduce the query time to seconds?

**Comment by jlapacik** [comment]
@AgrPriyank yes this is most likely due to the performance of join. `promql.join` allocates much less memory and might be an option if you are joining on `_time`.

https://github.com/influxdata/flux/blob/master/stdlib/internal/promql/join.md
