### ISSUE TITLE
Support scientific notation for float values in flux.

### ISSUE THREAD

**Issue by yzhang1991** [influxdata/flux#2732]
Flux currently does not scientific notation like `1e-9`. Instead, one has to specify `0.000000001` which is hard to read.
I would like to have Flux support it.

**Comment by yzhang1991** [comment]
https://github.com/influxdata/docs-v2/pull/912#discussion_r404194425

**Comment by sanderson** [comment]
This issue likely can be closed. While Flux does not support scientific notation as float literals, you can cast a scientific notation string to a float:

```javascript
float(v: “1e-9”)
// Returns 0.000000001
```
