### ISSUE TITLE
Move existing universe Flux package API into its own package

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2740]
As part of #6707 we need to make room in the API for adding new functions. Currently most functions are inside the `universe` package and as the `universe` package is part of the prelude those functions are in the top scope. 

We need to create a new package to contain all existing functions that work with data using the `schema-less` approach. By `schema-less` approach we mean functions that work with a stream of tables instead of a single table. This applies to most functions in the universe package. 

What should we name this new package ? 
The current best names are `schemaless` or `streams` but both don't seem to be very good. So we need to figure out a good name.

The purpose of this move is so that we can add the new Flux function to a package named `table`. Then users can decide whether they want to work with function in a `schemaless` manner or in a single `table` manner.

**Comment by nathanielc** [comment]
NOTE:

* The `influxdata/influxdb` package is also part of the prelude and makes assumptions consistent with the "schemaless" paradigm. How do we want to manage that? I.e. what do we do about the `from` function in the prelude?

**Comment by jsternberg** [comment]
I was wondering if we could potentially implement this as part of #2741. Usually, the way preludes are implemented is the evaluation does something like this:

```
import . "prelude"
```

And then `prelude.flux` is something like:

```
import . "universe"
import . "influxdata/influxdb"
```

I think this might provide a more flexible option than moving the universe package to some other name. And then when we create the table flux, it would have a different prelude and possibly a different import path. I don't think there's a reason why we have to rename the package though for the current version of flux. It might be premature.
