### ISSUE TITLE
Moving Average example in flux

### ISSUE THREAD

**Issue by CalamariAce** [influxdata/flux#2745]
Flux provides a built-in function to calculate moving averages.

For my own understanding, can someone show me an example of how I would implement the same functionality manually in native flux language, without using the moving average built-in?

Appreciate any guidance. Thanks.

Edit: In particular, I was trying to find how I would take an existing "non-moving" function like stddev(), and make a "moving stddev", as this is not a built-in for flux like movingAverage() is for mean().

**Comment by seanlaff** [comment]
As far as I can tell- this is not possible in flux. At least trivially. I suspect we need some sort of "get prior n values as an array" function.
