### ISSUE TITLE
Design Public Rust API for ast and semantic packages

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2746]
The current Rust API exposed in the `flux` crate is not amenable to working with _broken_ graphs (i.e. graphs that encode errors as Bad* nodes).

We should revisit the API so we can cleanly communicate how consumers should use the API in the face of broken graphs.

**Comment by wolffcm** [comment]
One thing that I would really like to see coming out of this design is a way to differentiate internal errors (e.g., some invariant didn't hold in our Rust code, which should return a 5xx from an http API) from errors in the Flux source code (syntax error, type error, etc which would be a 4xx).

A couple of points here:
- Any call into Rust code should have a way to return an internal error. Personally I like using the return value for this.
- Any users errors must be fetched explicitly via a call to `get_errors(ast)` or something like that

It's really confusing when we return user errors as internal errors and it's super-easy to do at the moment.
