### ISSUE TITLE
Nested flux queries?

### ISSUE THREAD

**Issue by CalamariAce** [influxdata/flux#2748]
I'm searching for the best way of constructing nested flux queries, both in terms of DRY-friendliness and query efficiency.

For example, I have a single time-series which I want to put into several aggregation windows, and apply a further set transformations to each aggregation window:

```
                               base_query
                             /            \
           aggregateWindow(5m)             aggregateWindow(10m)
            /        \                          /        \
movingAverage(3)  movingAverage(7)   movingAverage(4)  exponentialMovingAverage(6)
```

What is the prescribed way of doing this?

Appreciate any insights. Thanks.

**Comment by nathanielc** [comment]
The typical way to do this is assign the parent data to a variable and reuse it each time you need it?

```
base = from() ....

left = base |> aggregateWindow(5m) 
right  = base |> aggregateWindow(10m)

left |> movingAverage(3)
left |> movingAverage(7)


right |> movingAverage(4)
right |> movingAverage(6)
```

Does that help?

**Comment by CalamariAce** [comment]
Ahh yes, that makes perfect sense. Thank you!

**Comment by CalamariAce** [comment]
One followup - do you know how I would display each of those results in the Data Explorer using the same/single query? I tried the following:

```
base = from() ...

left = base |> aggregateWindow(5m)

leftMA3 = left |> movingAverage(3)
leftMA7 = left |> movingAverage(7)

join(tables: {d1: leftMA3, d2: leftMA7}, on: ["_time"], method: "inner")
```

However, only the combined _value column is rendered in the data explorer. The moving average aggregations seem to be missing in the rendered output. I was trying to explore if this is possible to do without defining multiple queries.

Thanks again

**Comment by nathanielc** [comment]
Use a `yield` with a unique name for each result you want rendered.
