### ISSUE TITLE
Influx moved to a -f flag for files does it make sense for flux to do the same ?

### ISSUE THREAD

**Issue by stormasm** [influxdata/flux#2753]
Influx just moved to using -f flag for file input...
Flux is still using the @ sign
I like using the @ sign so just curious what
people think about adding in the -f flag as well...

**Comment by sanderson** [comment]
@stormasm In most shells the `@` breaks native tab-completion for directory/file paths.

**Comment by stormasm** [comment]
@sanderson so you are saying we should implement the -f flag in flux then ?

**Comment by sanderson** [comment]
@stormasm I'm not sure I understand what you mean when you say "in Flux." Only the InfluxDB 2.0 Beta's `influx` CLI uses `@` to prepend file paths. Flux (the language) doesn't use `@`.

**Comment by stormasm** [comment]
@sanderson sorry I was not being clear
https://github.com/influxdata/flux/blob/master/cmd/flux/cmd/execute.go#L18
This is what I am referring to...

**Comment by sanderson** [comment]
Ah, gotcha. My mistake.
