### ISSUE TITLE
add outer join

### ISSUE THREAD

**Issue by jacobmarble** [influxdata/flux#2756]
I need to join against a constant, possibly incomplete data set. If incomplete, then query results should indicate that. In this example, if `x` returns any `env` value that is unknown to `y`, then the row in `x` is omitted from the join output. `method: "outer"` would fix this by returning all data in `x`, with `null` or similar for the missing value in `y`.

```
import "csv"

alertThresholdByEnv = "
#datatype,string,long,string,long
#group,false,false,false,false
#default,,,,
,result,table,env,_value
,,0,acc,64
,,0,prod01-eu-central-1,24
,,0,prod01-us-central-1,24
,,0,prod01-us-west-2,24
,,0,stag01-us-east-4,64
,,0,stag02-us-east-1,64
,,0,stag03-us-east-1,64
,,0,toolsus1,43
"

y = csv.from(csv: alertThresholdByEnv)

x = from(bucket: "apps")
	...

join(tables: {left: x, right: y}, on: ["env"])
```

**Comment by russorat** [comment]
connect https://github.com/influxdata/flux/issues/84

**Comment by danatinflux** [comment]
@nathanielc @timhallinflux This seems to be a popular ask; is it going to be on the roadmap in the next 12 months or so?

**Comment by eriktar** [comment]
Such a join would solve some of my issues as well.  Up-vote, thumps up, ++ or what I need to say to get this feature. 👍

**Comment by danatinflux** [comment]
@jacobmarble Does 3.x do this using 'normal' SQL?
