### ISSUE TITLE
add `exists` operator to record type

### ISSUE THREAD

**Issue by jacobmarble** [influxdata/flux#2757]
I need to join against a constant, possibly incomplete dataset. If incomplete, then query results should indicate that. In this example, the record type is missing the key `accs`. Reading any unknown key found in a query result causes the entire query to fail.

```
alertThresholdbByEnv = {
    "acc": 64,
    "prod01-eu-central-1": 24,
    "prod01-us-central-1": 24,
    "prod01-us-west-2": 24,
    "stag01-us-east-4": 64,
    "stag02-us-east-1": 64,
    "stag03-us-east-1": 64,
    "toolsus1": 43,
}

// Fails every time
threshold = if exists alertThresholdbByEnv["accs"] then alertThresholdbByEnv["accs"] else 0

from(bucket: "apps")
	...
	// Fails when query results contain unexpected value in env column
	|> map(fn: (r) => ({ r with r.foo: alertThresholdbByEnv[r.env] }))
```

**Comment by adrian-thurston** [comment]
A reduced test case. This code works as expected on master, but not algo-w.
```
foo = { a: "a" }
if exists foo["b"] then 1 else 0
```

On the algo-w branch we get `type error @4:11-4:14: record is missing label b`

**Comment by jsternberg** [comment]
This is an intended change in behavior. `exists` is only meant to be used on unbounded records such as the ones returned from storage.
