### ISSUE TITLE
Feature request: elapsed() option to keep the first row

### ISSUE THREAD

**Issue by jlvaillant** [influxdata/flux#2763]
Would it be possible to add an option for elapsed() to NOT drop the first row but instead put a null in the duration column?

I'm using elapsed to filter short duration noise in a non regular state event stream but, by loosing the first event I also loose the initial state :-(

**Comment by russorat** [comment]
@jlvaillant thanks for the issue. I'll let the flux team comment on adding the option to the query. One way to work around it for now would be to use the first function https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/selectors/first/ and then union https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/union/ that to your `elapsed` results. not great, but it might unblock you for now.
