### ISSUE TITLE
How can I get a tag all values?

### ISSUE THREAD

**Issue by GF-Huang** [influxdata/flux#2780]

**Comment by adrian-thurston** [comment]
Hi @GF-Huang, wondering if you could provide a bit more information, perhaps an example as well?

**Comment by GF-Huang** [comment]
I want to get all values while `measurement=xxx and tag=value` in influxdb.

**Comment by sanderson** [comment]
@GF-Huang This question may be better suited for the [InfluxData community](https://community.influxdata.com/), but the answer to your question is [`v1.measurementTagValues()`](https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/influxdb-v1/measurementtagvalues/)

```js
import "influxdata/influxdb/v1"

v1.measurementTagValues(
  bucket: "finance_data",
  measurement: "ticket_changes,
  tag: "ticker"
)
```

**Comment by GF-Huang** [comment]
Thank you very much!

**Comment by sanderson** [comment]
@GF-Huang No problem! Happy to help.
