### ISSUE TITLE
Aggregate data in groups of N elements

### ISSUE THREAD

**Issue by JBuijgers** [influxdata/flux#2782]
This is actually a copy of https://github.com/influxdata/influxdb/issues/12478, but then for Flux. My use-case is focused on creating a tick-based candlestick chart (e.g. create a candlestick per 400 trades). So my first challenge would be to group a set of records based on my tick count, creating a candlestick (OHLC) from there should be quite easy. Is this possible in Flux or are there other ways to achieve this?

Advice is very much appreciated, thanks!

**Comment by russorat** [comment]
@JBuijgers thanks! Sounds like you should take a look at https://v2.docs.influxdata.com/v2.0/query-data/flux/group-data/ and https://v2.docs.influxdata.com/v2.0/query-data/flux/window-aggregate/ to get started. Also, have you tried posting in either the Community site (https://community.influxdata.com) or the Slack channels (https://influxdata.com/slack)?

**Comment by JBuijgers** [comment]
Thanks so much for the feedback! Got started in the Slack channel shortly after posting this issue, would seem like the better place to get some help. Will let you know how it goes, maybe someone else will stumble upon the same question in the future.

**Comment by JBuijgers** [comment]
Many thanks to @wolffcm , while this solution is temporary, and a future release will let the window function do the same, the below code did the trick for me.

```
  |> map(fn: (r) => ({r with
      row_num: 1,
  }))
  |> cumulativeSum(columns: ["row_num"])
  |> map(fn: (r) => ({r with
      group_num: (r.row_num - 1) / GROUP_SIZE
  }))
  |> group(columns: [<other group key columns...>, "group_num"])
```
