### ISSUE TITLE
Now function option does not propagate correctly into map function

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2784]
When the now option is set in some way from influxdb tasks, the option does not seem to get set for `now()` in the `map` call. For example, this does not work:

```
map(fn: (r) => ({r with _now_time: now()}))
```

But this does work:

```
now_time = now()
map(fn: (r) => ({r with _now_time: now_time}))
```

**Comment by adrian-thurston** [comment]
This might very well be #2795, which already caused a regression with `system.time` #2773

**Comment by jsternberg** [comment]
This got fixed by reverting the above referenced PR in #2785.
