### ISSUE TITLE
StoreReader implementation of the ReadWindowAggregate

### ISSUE THREAD

**Issue by yzhang1991** [influxdata/flux#2790]
Implement windowAggregateIterator.handleRead()

**Comment by wolffcm** [comment]
This issue should be in `influxdb` right?

If I understand correctly the work for this would be to write the `windowAggregateIterator.handleRead()` method similar to the other types like `FilterIterator`, etc.  These all appear to implement `flux.TableIterator`.

Are there other issues in this epic that are even lower in the stack, closer to the physical representation of data in storage? We are constantly discussing how these issues relate to one another, so it would help to have this context here.

**Comment by jlapacik** [comment]
Closed by https://github.com/influxdata/influxdb/pull/17952
