### ISSUE TITLE
Feature Flag Push Down Aggregates

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2795]
We want the ability to roll out the new push down of aggregates with a feature flag. It seems that the most straightforward way to do this is to feature flag the planner rule. 

A quick way to do this is to not register the planner rule from the InfluxDB repo, but instead create a new rule on the IDPE side that wraps the InfluxDB rule. The wrapper can check the feature flag before calling down to the contained rule.

This means we do not need to inject the feature flag into the context as the IDPE code can directly access the feature flag package on IDPE.

**Comment by adrian-thurston** [comment]
Feature flags have landed in OSS.

https://github.com/influxdata/influxdb/tree/feat/window-aggregate-flag

**Comment by adrian-thurston** [comment]
Work done, but no PR yet as this work depends on https://github.com/influxdata/influxdb/pull/17898 which itself has unmet dependencies as of time of writing.

**Comment by adrian-thurston** [comment]
Code now included in https://github.com/influxdata/influxdb/pull/17898

**Comment by adrian-thurston** [comment]
Closed by https://github.com/influxdata/influxdb/pull/17898
