### ISSUE TITLE
Support xth percentile in aggregateWindow()

### ISSUE THREAD

**Issue by alsargent** [influxdata/flux#2801]
The function `aggregateWindow()` lets us easily calculate min, max, and median. However, it doesn't provide an easy way to calculate percentiles: 99th, 98th, 90th, etc.

https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/aggregates/aggregatewindow/

Please allow us to easily calculate any percentile in `aggregateWindow()`, using syntax similar to the following:

```
  |> aggregateWindow(every: 5m, fn: 99) // 99th perentile
  |> aggregateWindow(every: 5m, fn: 90) // 90th perentile
```

... and so on.

Yes, I understand there's the quantile function: https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/aggregates/quantile/ . But this requires me to figure out computation method and compression level -- way too complex when all I want to do is find a certain percentile.

**Comment by sanderson** [comment]
@alsargent It can't work the way you propose. `99` would have to be a function and the typing system doesn't allow for number-based function names (to my knowledge). The functions would have to be named something like `p99`.

There used to be a `percentile` function, but it was calculating using a fractional float value `0.99` (quantile) vs an integer value `99` (percentile), so it was changed to `quantile`. Both the `method` and `compression` parameters have defaults, so you don't necessarily need to include them.

To use `quantile` with `aggregateWindow`, use the following syntax:

```js
// ...
  |> aggregateWindow( every: 5m, fn: (t=<-, column) => t |> quantile(q: 0.99))
```

As documented [here](https://v2.docs.influxdata.com/v2.0/query-data/flux/percentile-quantile/#use-quantile-with-aggregatewindow).

To do what you're proposing would require creating a custom package that includes each percentile functions. I could look something like:

```js
package percentile

p99 = (tables=<-, column) => tables |> quantile(q: 0.99, column: column)
p98 = (tables=<-, column) => tables |> quantile(q: 0.98, column: column)
p97 = (tables=<-, column) => tables |> quantile(q: 0.97, column: column)
// etc...
```

To then use those functions it a query, it would look like:

```js
import "percentile"

data
  |> aggregateWindow(every: 1m, fn: percentile.p99)
```
