### ISSUE TITLE
Switch fill transformation to use the ArrowBuilder

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2828]
The fill transformation should be switched to use the [ArrowBuilder](https://pkg.go.dev/github.com/influxdata/flux@v0.67.0/internal/execute/table?tab=doc#ArrowBuilder). This is the first step in #2823.

At the moment, the transformation uses the [TableBuilderCache](https://pkg.go.dev/github.com/influxdata/flux@v0.67.0/execute?tab=doc#TableBuilderCache) along with [execute.Dataset](https://pkg.go.dev/github.com/influxdata/flux@v0.67.0/execute?tab=doc#NewDataset) to provide the builder. This implementation is limited to only use the [ColListTableBuilder](https://pkg.go.dev/github.com/influxdata/flux@v0.67.0/execute?tab=doc#ColListTableBuilder) which has slow memory access patterns.

This issue is to convert the fill transformation to use this alternative [Dataset](https://pkg.go.dev/github.com/influxdata/flux@v0.67.0/internal/execute/table?tab=doc#NewDataset), use this alternative [BuilderCache](https://pkg.go.dev/github.com/influxdata/flux@v0.67.0/internal/execute/table?tab=doc#BuilderCache), and use the [ArrowBuilder](https://pkg.go.dev/github.com/influxdata/flux@v0.67.0/internal/execute/table?tab=doc#ArrowBuilder) and the [GetArrowBuilder](https://pkg.go.dev/github.com/influxdata/flux@v0.67.0/internal/execute/table?tab=doc#GetArrowBuilder) utility to retrieve the builder.

```go
// construct transformation and dataset
alloc := &memory.Allocator{}
cache := &table.BuilderCache{
    New: func(key flux.GroupKey) table.Builder {
        return table.NewArrowBuilder(key, alloc)
    },
}
dataset := table.NewDataset(id, cache)

// process individual table
var tbl flux.Table = /* incoming table */
b, created := table.GetArrowBuilder(tbl.Key(), cache)
// insert schema creation code
// use builders from the arrow builder to append values
```

**Comment by yzhang1991** [comment]
I would like to pair on this issue.
