### ISSUE TITLE
Switch the fill transformation to use table stream

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2830]
After #2829 is completed, the fill transformation should be updated to use [table.Stream](https://pkg.go.dev/github.com/influxdata/flux@v0.67.0/internal/execute/table?tab=doc#Stream) to produce the table. It can still construct a single buffer, but the call should be changed from using the [ArrowBuilder](https://pkg.go.dev/github.com/influxdata/flux@v0.67.0/internal/execute/table?tab=doc#ArrowBuilder) to constructing the array builders, constructing the arrays, and then writing them into the [StreamWriter](https://pkg.go.dev/github.com/influxdata/flux@v0.67.0/internal/execute/table?tab=doc#StreamWriter) with [Write](https://pkg.go.dev/github.com/influxdata/flux@v0.67.0/internal/execute/table?tab=doc#StreamWriter.Write).

**Comment by nathanielc** [comment]
Question when would we use  table.Stream  instead of  table.StreamWithContext? As I understand we always have a context provided via the Process method and so we should use that one.

**Comment by jsternberg** [comment]
The `Process` method doesn't get passed a context, but we do get a context when constructing the transformation. I think it would be preferred to use `StreamWithContext` with the context passed from the `execute.Administration` when creating the transformation.

**Comment by nathanielc** [comment]
OK yeah I have misremembered the API of the Process method. My point is that all queries execute under a context and so we should never use the background context for these streaming method.

In fact what do you think about removing the `table.Stream` method that defaults to using the background context from the API. That way its more explicit that callers need to provide a context.
