### ISSUE TITLE
Ability to limit number of series returned by a query

### ISSUE THREAD

**Issue by desa** [influxdata/flux#2854]
I'd like to be able to limit the number of series returned from a flux query. Since flux does `group by *` by default, it is common that users of the UI end up returning 1000s of series. It would be great to offer some facility to limit the series returned.

What would be great is to have a function like

```
seriesLimit = (tables=<-, n, fn) => {
  ...
}
```

where `n` is the number of series and `fn` is the selector used for specifying the heuristic for limiting the series.

```
from(bucket: "foo")
  |> range(...)
  ...
  |> seriesLimit(n: 10, fn: max)
```

**Comment by desa** [comment]
@russorat has mentioned that this might not be sufficient. We might need to think about this as a larger group.

**Comment by dpozinen** [comment]
> @russorat has mentioned that this might not be sufficient. We might need to think about this as a larger group.

any update on this? Thanks

**Comment by russorat** [comment]
I am no longer with InfluxData. cc @barbaranelson
