### ISSUE TITLE
Refactor WindowAggregateResultSet to reuse existing AggregateArrayCursors

### ISSUE THREAD

**Issue by yzhang1991** [influxdata/flux#2855]
1. The windowing.logic is now handled by `WindowCountArrayCursor`, make it WindowAggregateResultSet's work
2. Delete `WindowCountArrayCursor`, reuse `CountArrayCursor`

**Comment by yzhang1991** [comment]
Feel free to pair with me if you want to work on this issue.

**Comment by fchikwekwe** [comment]
Punting on this one for now while we wait for server side readWindowAggregate implementation to land.  If someone else ends up picking this issue up, I'd like to review the PR if possible.
