### ISSUE TITLE
Programmatically updating options in Flux source

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/flux#286]
To support an easier REST API and UI for tasks, there is a desire for taking an existing Flux script and a new option or set of options to produce a new Flux script.

For example, given a Flux script like:

```
option task = {
  every: 1m,
  delay: 5s, // Sometimes data comes in late, but never more than 5 seconds late.
  name: "mytask"
}

from(bucket: "x") |> range(start:-1h) |> max() |> to(bucket: "max_over_last_hour")
```

Then with a request to update the "every" option to "20m", the resulting Flux script would be:

```
option task = {
  every: 20m,
  delay: 5s, // Sometimes data comes in late, but never more than 5 seconds late.
  name: "mytask"
}

from(bucket: "x") |> range(start:-1h) |> max() |> to(bucket: "max_over_last_hour")
```

That is, the resultant script has identical comments and formatting, and the only change was the value of the `every` option was changed from 1m to 20m.

I'm not sure exactly what the flux API needs to be for this. Are options only overwritten? Should there be a way to delete options?

**Comment by nathanielc** [comment]
@mark-rushakoff The way I envision these kinds of workflows is to leverage the AST.

The process would look something like this:

```
sourceAST = parser.Parse(source)

// Walk the AST and edit its options
editor := new(OptionEditor)
ast.Walk(editor, sourceAST)

newSource := ast.Format(editor.AST)

// do what you need with the new source code
```

It is also possible to perform a similar work flow using the semantic graph, but that should only be needed if you need the type information in order to perform your edits.

NOTE: The ability to convert AST to text is not available yet.

**Comment by mark-rushakoff** [comment]
https://github.com/influxdata/platform/issues/1996 is the issue tracking the changes in platform's task code, which will use the related changes coming out of #323.  Once https://github.com/influxdata/platform/issues/1996 is done then I think we can close this issue. It's possible that there may be more Flux iterations needed, but currently anticipating that the existing changes will suffice.

**Comment by mark-rushakoff** [comment]
Looks like we were able to do what we needed to do in https://github.com/influxdata/influxdb/pull/10954, so closing this.
