### ISSUE TITLE
Update Rust in CircleCI with a specific version number 

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/flux#2873]
Right now when we update Rust in CircleCI, we just update to the latest stable version. 

Seen here: https://github.com/influxdata/flux/blob/c44255558220903625ce79df0c5c33ee63a3082e/Dockerfile_build#L68-L72

It would be preferable to update Rust to a specific version number in order to better control what version we're on.

**Comment by jlapacik** [comment]
Because we build the latest stable release of rustup in CI, there can/will be situations where code builds before a new release but doesn't afterwards. Note this will happen if a new lint is added to `clippy`.
