### ISSUE TITLE
Need time-weighted average function (TWA)

### ISSUE THREAD

**Issue by chobbs** [influxdata/flux#2891]
I very common function in industrial automatization is the average exposure to a condition which individuals may be exposed without adverse effect over a period such as in an 8-hour day or 40-hour week.

Attached is an implementation of time-weighted averages in Python with an accompanying Excel workbook for testing purposes.

[twa.xlsx](https://github.com/influxdata/flux/files/4743337/twa.xlsx)
[twa_py.txt](https://github.com/influxdata/flux/files/4743336/twa_py.txt)

**Comment by timhallinflux** [comment]
The following is an example implementation that assumes the data comes in a single table sorted by _time.
```
timeWeightedAvg = (table=<-) => table
    |> integral()
    |> map(fn: (r) => ({ r with _value: r.value / ( float(v: r._stop) - float(v: r._start) ) }))
```
And for an implementation that calculates the minimum spanning time range
```
timeWeightedAvg = (table=<-) => {
    // Sum time differences to get interval length
    range = table
        |> map(fn: (r) => ({ _value: int(v: r._time) }))
        |> difference()
        |> sum()

    table
        |> integral()
        |> map(fn: (r) => ({ r with _value: r.value / (range |> findRecord(idx: 0)._value) }))
}
```

**Comment by jlapacik** [comment]
Standard time weighted average should be defined like so:
```
timeWeightedAvg = (tables=<-, unit) => tables
  |> reduce(fn: (r, accumulator) => {
    t = (int(v: r._time) - accumulator._time) / unit
    v = r._value + accumulator.prev

    value = if accumulator.start then 0.0 else accumulator._value + 0.5 * v * float(v: t)
    total = if accumulator.start then 0 else accumulator.total + t

    return { start: false, _time: r._time, prev: r._value, total: total, _value: value }
  }, identity: { start: true, _time: 0, total: 0, prev: 0.0, _value: 0.0 })
  |> map(fn: (r) => ( { r with _value: if r.total == 0 then 0.0 else r._value / float(v: r.total)  } ))
```

Time weighted average with linear interpolation:
```
timeWeightedAvg = (table=<-, unit) => table
    |> integral(unit: unit, interpolate: true)
    |> map(fn: (r) => ({ r with _value: r.value / ( float(v: r._stop) - float(v: r._start) ) }))
```

Note the latter requires https://github.com/influxdata/flux/issues/3136. Both implementations can be combined into a single function like so:
```
timeWeightedAvg = (tables=<-, unit, interpolate) => if interpolate
    then tables |> twaInterpolate(unit: unit)
    else tables |> twaStandard(unit: unit)
```

**Comment by nathanielc** [comment]
DOD:

- Add TWA function that uses interpolation
- We do NOT need to build the _standard_ flavor of TWA as part of this issue
- Flux end to end tests for the new TWA function
- Test cases should include a case where interpolation is needed and a case where its not needed
