### ISSUE TITLE
flux build stucks

### ISSUE THREAD

**Issue by gehlsdorf** [influxdata/flux#2895]
I build flux under windows with this command: go build -i -v -x ./cmd/flux

build get stuck here:

"D:\\Tools\\Go\\pkg\\tool\\windows_amd64\\buildid.exe" -w "$WORK\\b398\\_pkg_.a" # internal
cp "$WORK\\b398\\_pkg_.a" "C:\\Users\\gehls\\AppData\\Local\\go-build\\07\\072fda1ea94f9724d0ac97ea1eb456f0c34c73a1203f99d8e312e9277631a122-d" # internal

**Comment by russorat** [comment]
@gehlsdorf thanks for opening!
