### ISSUE TITLE
nonNegative default value for derivative

### ISSUE THREAD

**Issue by lafrech** [influxdata/flux#2896]
Hi.

[The docs](https://v2.docs.influxdata.com/v2.0/query-data/flux/rate/) read

> By default, derivative() returns only positive derivative values and replaces negative values with null. 

But from a few tests I made with Influx 1.8, it seems that `nonNegative` defaults to `false`.

Here's the query I send using Python influxdb-client:

```python
query=f"""
from(bucket:"{BUCKET}")
|> range(start: -1000000m)
|> filter(fn: (r) => r._measurement == "{MEASUREMENT}")
|> group(columns: ["id"])
|> derivative(nonNegative: false)
"""
```

When removing the `nonNegative` parameter in the last line, I get negative values and the same result. When changing to `true`, I get `None` values.

Not that I complain. I find `false` a better default. To me, it is more of a doc issue.

**Comment by russorat** [comment]
@lafrech i think the docs are wrong. i still see nonNegative: false as the default.
