### ISSUE TITLE
Deno library to parse Annotated CSV to JSON

### ISSUE THREAD

**Issue by tiagostutz** [influxdata/flux#2904]
Hi people.!

I've just released a [simple library for Deno to parse the Annotated CSV](https://github.com/tiagostutz/annotated-csv-parser) return of Flux script execution and would like to know whether there are other libraries like that for NodeJS and Go.

Is there any better approach to handle the CSV result that I missed? I made a research, but couldn't find any.

Also, if there are no NodeJS implementation of such a parser I can easily port the Deno lib.

**Comment by russorat** [comment]
@tiagostutz this is great! I passed this over to our UI team. How would this work with https://github.com/influxdata/influxdb-client-js and/or https://github.com/influxdata/giraffe?

**Comment by tiagostutz** [comment]
Nice, @russorat!
I didn't know both of the projects... I'm taking a look at them right now to check what are the possibilities and will come back here to give a follow-up on this. Thanks for the tips.!
