### ISSUE TITLE
Flux Client or App

### ISSUE THREAD

**Issue by andyhuber** [influxdata/flux#292]
Hi Guys

Wasn't really sure where to post or ask. Are you planning on also building clients for Flux that are separate from Chronograf? Like an app or Visual studio code extension or similar. to easily write and run flux snippets? If not I'll look into building something.

**Comment by russorat** [comment]
@andyhuber if you haven't already, check out https://github.com/influxdata/vsflux

i'll close this issue and you can track progress there.
