### ISSUE TITLE
Spike on parallel testing failures due to high memory usage

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/flux#2933]
There are a small number of end to end tests that may be using a high amount of memory while running in parallel and causing the entire test harness to fail due to memory usage. 

Time box to 2-3 days.

**Comment by adrian-thurston** [comment]
As an example, the benchmark `BenchmarkFilter_Values` in `stdlib/universe/filter_test.go` requires 3.7 gigs of ram. Our CI systems are typically capped at 4 gigs. If this benchmark runs in parallel with any other benchmark or test that requires ram then it can cause the testing process to get killed. 

If we run each test and benchmark separately and record the amount of ram used we can potentially identify other tests that are periodically causing tests to fail. These tests should be forced to run serially.
