### ISSUE TITLE
Query to get types of fields

### ISSUE THREAD

**Issue by desa** [influxdata/flux#2938]
We're working through making the query builder experience more rich. We'd like to know the list of types for a field.

### Scenario: Notebooks Metric Selector
GIVEN I have selected bucket and I'm reviewing my schema in the dropdown
WHEN I see measurement, tag, or field
THEN I can see the [data type](https://docs.influxdata.com/influxdb/v2.0/reference/syntax/annotated-csv/#data-types) of the value

- bool
- uint
- int
- long	
- double
- string
- base
- time
- duration

![data type](https://user-images.githubusercontent.com/56005508/101535095-f96e8680-394c-11eb-9f6b-68bc5ee7d77f.png)

Technical Notes:
Can we use the [Flux InfluxDB schema] aka the Meta API (https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/influxdb-schema/) instead of querying every point to generate the schema?

Related to getting data type in the Flux InfluxDB schema: influxdata/flux#2938

**Comment by mnorriswalker** [comment]
Proposed for this epic (CC @alexpaxton @drdelambre @Asalem1) https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/ui/385

**Comment by forest-code42** [comment]
I have been using this query 

```
import "influxdata/influxdb/schema"

// one weird trick to coax influx to output its entire schema (measurements and fields, ignore/drop all tags)
// this is the only way I found to obtain the data types on the fields :X 
from(bucket: "default")
  |> range(start: duration(v: uint(v: 1970-01-01) - uint(v: now())))
  |> keep(columns: ["_time", "_measurement", "_field", "_value"])
  |> schema.fieldsAsCols()
  |> limit(n:1, offset: 0)
```

This should work as long as you are ok with manually parsing the field types out of the response and as long as each field on each measurement is always the same type.

**Comment by sanderson** [comment]
Here's a query that defines a custom `getType()` function and uses it to return all fields with their types:

```js
import "array"
import "influxdata/influxdb/schema"
import "types"

getType = (v) => {
    _types = [
        "string",
        "bytes",
        "int",
        "uint",
        "float",
        "bool",
        "time",
        "duration",
        "regexp",
    ]
    _eval = array.map(arr: _types, fn: (x) => ({type: x, is: types.isType(v: v, type: x)}))
    _type = array.filter(arr: _eval, fn: (x) => x.is == true)

    return _type[0].type
}

from(bucket: "example-bucket")
    |> range(start: 0)
    |> limit(n: 1)
    |> map(fn: (r) => ({_field: r._field, _value: getType(v: r._value)}))
    |> unique(column: "_field")
```
