### ISSUE TITLE
Performance issue on time aggregation

### ISSUE THREAD

**Issue by claudio-t** [influxdata/flux#2942]
Ciao

I am currently running influxdb v1.8 and I am seeing a huge difference in performance between InfluxQL and Flux queries when extracting the same values. 

For example, let `my_measurement` be a time series with one point per second. If I try to extract the daily mean for a one year time span I get the following results:

* Flux
```
from(bucket: "my_bucket")
|> range(start: 2019-01-01T00:00:00Z, stop: 2020-01-01T00:00:00Z)
|> filter(fn: (r) =>
    r._measurement == "my_measurement" and
    r._field == "my_field"
)
|> filter(fn: (r) => r.viz != "hide")
|> window(every: 1d, offset: 0ns)
|> mean()
|> duplicate(column: "_start", as: "_time")
|> window(every: inf)
|> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
|> keep(columns: ["_time", "myfield"])
```
elapsed time: 79s
* InfluxQL
```
SELECT mean(my_field) AS "my_field" FROM my_measurement 
WHERE "viz" <> 'hide' 
AND time >= 1546300800000ms 
AND time < 1577836800000ms 
GROUP BY time(1d, 0ns)
```
elapsed time: 1.6s

__Environment info:__

* System info: Win Server 2016
* InfluxDB version: 1.8.0-1

**Comment by russorat** [comment]
@claudio-t thank you for the report! we are very focused on improving the performance of Flux right now and those changes will make their way into influxdb 1.x line as well.

In the 1.8 line, if you can accomplish what you want to do in InfluxQL, there's no harm in using it. If you hit limitations and need Flux to do something not currently possible to do with InfluxQL, then it's there. Look for it to improve with every release.
