### ISSUE TITLE
TO-commandlet with unexpected results

### ISSUE THREAD

**Issue by herrJones** [influxdata/flux#2963]
Hi,

I'm using _influxdb beta 13._
I try to downsample my PLC data into min/mean/max value over 5min.

Output columns:
* source : sensor-source
* kind : min/mean/max
* name : name of the sensor
* of course: time, value and measure

I noticed the following strange behaviour:
* to(bucket: "demo", org:"home") --> everything is dumped in the new measure
* to(bucket: "demo", org;"home", tagColumns: ["source","kind"]) --> source+kind are tags, time and value are present but name is absent. I would have expected it to be present in the 'normal data'

Easy workaround: add the "name" column also to the tagColumns. But I can imagine there are circumstances where one wouldn't do that.

Kind regards,

   Jan

**Comment by russorat** [comment]
@herrJones thanks for the issue. I've recently added a downsampling template that might help you solve this: https://github.com/influxdata/community-templates/tree/master/downsampling

If you paste a sample of the data you are trying to downsample, and the code you are using to do it, that would help me better understand the issue you are seeing.

**Comment by herrJones** [comment]
Hey Russ,

Thanks for the reply. 
I added data for the last 6 hours of temperature in the zip.
The data itself is stored via the node-js/javascript plugin you provide via 'Client Libraries'
[2020-07-18-16-23_chronograf_data.zip](https://github.com/influxdata/flux/files/4941810/2020-07-18-16-23_chronograf_data.zip)

The code for the task is as below.
So as a workaround, I use 3 tags now.

```
option task = {name: "beckhoff - temperatures - tmp 2 db", every: 5m}

data = from(bucket: "telegraf")
	|> range(start: -30m)
	|> filter(fn: (r) =>
		(r["_measurement"] == "beckhoff" and r["category"] == "TEMP"))
	|> drop(columns: ["_start", "_stop", "category", "_measurement"])
mindata = data
	|> aggregateWindow(every: 5m, fn: min)
	|> group(columns: ["name"])
	|> fill(column: "_value", usePrevious: true)
	|> set(key: "action", value: "min")
avgdata = data
	|> aggregateWindow(every: 5m, fn: mean)
	|> group(columns: ["name"])
	|> fill(column: "_value", usePrevious: true)
	|> set(key: "action", value: "avg")
maxdata = data
	|> aggregateWindow(every: 5m, fn: max)
	|> group(columns: ["name"])
	|> fill(column: "_value", usePrevious: true)
	|> set(key: "action", value: "max")
mrgData = union(tables: [mindata, avgdata, maxdata])
	|> set(key: "_measurement", value: "temperature")
	|> set(key: "source", value: "beckhoff")

mrgData
	|> to(bucket: "demo", org: "home", tagColumns: ["source", "name", "action"])
```

Kind regards,

    Jan
