### ISSUE TITLE
group(except:[]) panic 

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/flux#297]
Influxdb v1.7.1 Chronograf v1.7.3 

Trying to use group(except:[]). 

When I run 
```
from(bucket: "telegraf/autogen")
    |> range(start: -30m)
    |> group(except: ["_time"])
```

I get the following:
<img width="1437" alt="screen shot 2018-11-16 at 4 26 42 pm" src="https://user-images.githubusercontent.com/30506042/48650671-cf8c4500-e9bc-11e8-9944-bfe3f4ab1556.png">

**Comment by nathanielc** [comment]
@stuartcarnie Can you take a look at this one? It seems that any group expect is causing a panic.

**Comment by wolffcm** [comment]
This is now fixed on flux master:
https://github.com/influxdata/flux/pull/299
