### ISSUE TITLE
Port end-to-end test runs to use the chain function

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/flux#2975]
Currently our end-to-end tests have to run three times when they fail in order to return a result. This is one potential source of flakiness. @rockstar [created this chain function](https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/experimental/chain) to help avert these multiple test runs. We should port our current end-to-end tests to use the chain function.

**Comment by adrian-thurston** [comment]
https://github.com/influxdata/influxdb/pull/18898
