### ISSUE TITLE
Optimize derivative call for memory usage

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2977]
The `derivative` function needs to have its memory usage optimized in the following ways.

1. [Reuse the columns](https://gist.github.com/jsternberg/c20e6b900baab8863c6693e633dc425f#-arrow-array-references) that aren't referred to by the `column` parameter. When `keepFirst` is used the entire column can be used. When the first row is dropped, a slice can be used.
2. [Stream each input table](https://gist.github.com/jsternberg/c20e6b900baab8863c6693e633dc425f#-stream-tables) to the next transformation because the group key is 1:1.
3. For the column that gets filled, [preallocate the array](https://gist.github.com/jsternberg/c20e6b900baab8863c6693e633dc425f#-preallocate-array-size) before constructing it.

**Comment by adrian-thurston** [comment]
I ran the flux-archiver pattern matcher to search for `derivative` and `difference`. The pattern simply checks for the existence of these two functions in a query.
```
2021/03/04 08:37:36 running pattern matching
2021/03/04 08:38:20 finishing up
2021/03/04 08:38:20 
        number of queries:                  887839
        query parse errors:                 151465
        number of executions:           1317043761
        execution parse errors:           19431013
        flux parse errors:                       0
        flux exec parse errors:                  0
        timed executions count:          650459314
        timed executions sum:   311475263949761066
2021/03/04 08:38:20 derivative
        query matches:                     5674
        execution matches:             23291610
        timed matches count:           10535202
        timed matches sum:     2388193818881990
        exec representation:        0.016196558
        time representation:        0.007667363
        time over-rep:              0.473394575
2021/03/04 08:38:20 difference
        query matches:                    43420
        execution matches:             24416132
        timed matches count:           14004034
        timed matches sum:    16503937629465321
        exec representation:        0.021529454
        time representation:        0.052986351
        time over-rep:              2.461109810
```
Some key points:

1. `derivative` appears in 1.6 percent of query executions and these query executions constitute 0.7 percent of total time. Under-represented in time by a factor of 0.47.
2. `difference` appears in 2.1 percent of query executions and consititute 5.3 percent of the time. Over-represented by a factor of 2.4

**Comment by jsternberg** [comment]
Closing in favor of #3941.
