### ISSUE TITLE
Parse types as part of builtin statement

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#2985]
Currently the flux `builtin` statement declares a single identifier:

    builtin filter

We would like the `builtin` statement to also include the type of the declared identifier like so:

    builtin filter : (<-tables: [T], fn: (r: T) -> bool) -> [T]

This issue is for parsing types as part of the flux `builtin` statement. Basic types are specified as follows:
```
int
uint
float
string
bool
time
duration
bytes
regexp
```

Type variables are given as capital letters `A-Z`.

An array of type `T` is given as:
```
[T]
```

Record types are specified as follows:
```
// a record type with labels 'a' of type T and 'b' of type S
{a: T, b: S}

// a polymorphic record having labels 'a' of type A and 'b' of type B
// and extending another record of type T
{T with a: A, b: B}
```

Function types are specified as follows:
```
// takes a required argument 'x' of type T with return type of T
(x: T) -> T

// takes an optional argument 'x' of type T with return type of T
(?x: T) -> T

// takes a pipe argument 'x' of type T with return type of T
(<-x: T) -> T

// takes an un-named pipe argument of type T with return type of T
(<-: T) -> T
```

Flux function always have a return type. Flux functions may take several input parameters separated by a `,`.

Type variables may be optionally constrained using a `where` clause that follows the type:

    builtin specialMapFn : (a: [T], f: (x: T) -> S) -> [S] where T: Addable + Divisible, S: Comparable + Equatable

**Comment by jlapacik** [comment]
Note the scanner will also need to be updated to recognize and tokenize `->`, `<-`, and `?`.

**Comment by nathanielc** [comment]
We split up this issue into smaller parts.
