### ISSUE TITLE
Parse type variables in builtin statement

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#2988]
This issue is for extending the flux parser so that it can parse type variables as part of the builtin statement. A new variant will need to be added to the AST node for types. It should look something like this:
```Rust
enum Type {
    ...,
    Tvar(char),
}
```

DOD:

* Tests exist for parsing type variables in builtin statements.
* The flatbuffer and json serialization code is updated to handle type variables

**Comment by ChitlangeSahas** [comment]
#3011
