### ISSUE TITLE
Parse record types in the builtin statement

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#2990]
This issue is for extending the flux parser so that it can parse record types as part of the builtin statement. A new variant will need to be added to the AST node for types. Record types can take the following flux forms:
```
{}
{a: int}
{a: int, b: string}
{T with a: int, b: string}
```

DOD:

* Tests exist for parsing record types in builtin statements.
* The flatbuffer and json serialization code is updated to handle record types

**Comment by ChitlangeSahas** [comment]
#3021
