### ISSUE TITLE
Flux REPL should push as much processing to InfluxDB API as possible

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#3001]
Currently the REPL will only send a very small subset of a query over the API to InfluxDB. This means that pushdowns and other optimizations that the Flux engine can perform are not possible to leverage from the REPL. Since the REPL is the primary way of querying InfluxDB via the CLI this has a large impact on users.

The REPL keeps some processing local, for example `csv.from` so it can read the local csv file etc. We should explore ways to make it so the REPL can send all aspects of a query via the API that do not require accessing local resources.

**Comment by rbetts** [comment]
Can we direct people who want a REPL experience to the flux repl and make this call influx directly? Is that confusing?  I'm much more interested in fast/reliable query of our products from the CLI than I am about keeping the REPL experience in the influx command itself. (At least for the short term.)

**Comment by jsternberg** [comment]
Created https://github.com/influxdata/influxdb/issues/19038 to update the `query` command and remove the repl from the influx CLI.

**Comment by nathanielc** [comment]
When we want to provide a REPL experience in the influx CLI again we will revisit this issue. Until then closing as it will likely not be directly applicable.
