### ISSUE TITLE
Range ignored if put after pivoting operation

### ISSUE THREAD

**Issue by affo** [influxdata/flux#302]
The query:

```
from(bucket: "telegraf")
    |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
    |> range(start: -1h)
```

raises the error:

```
failed to create physical plan: result 'from0' is unbounded. Add a 'range' call to bound the query,
```

While:

```
from(bucket: "telegraf")
    |> range(start: -1h)
    |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
```

Executes normally.

Could be related to https://github.com/influxdata/flux/issues/139.

**Comment by nathanielc** [comment]
The `fromRows` builtin use range last which causes this error. We need to change fromRows to do the range first.

**Comment by nathanielc** [comment]
Can a range push trhough a pivot? If so we need to add the rewrite rule for it. If not then we need to update the `fromRows` function to add its own range call.

**Comment by jlapacik** [comment]
I don't believe range can be pushed through a pivot according to the current pivot spec. The column schema that pivot produces depends on the number of unique values in pivot's `columnKey`. The more unique values, the more columns the output tables will have.

A range before a pivot will restrict the number of unique values for the `columnKey`. A range after pivot however could potentially produce null columns (columns with only null values) - something that cannot occur if range comes before pivot.

The only way I see that `range |> pivot` could be equivalent to `pivot |> range` is when pivot's `rowKey` contains the `_time` column **and** if pivot were to strip any null columns from its output by default.

@aanthony1243 do you agree? Am I leaving anything out?

**Comment by affo** [comment]
I see your point @jlapacik.

Just to be sure that I got the point with `null` values, let me provide an example. Please correct me if some assumption is wrong.

`null` values can happen only when some point is missing a value for a `rowKey`, `columnKey` pair.
So, for instance, suppose the `rowKey` is `_time` and the `columnKey` is `_field`, it could happen that a point with a new field causes `null`s in every previous point for that field. Ranging and excluding that point would cause a `null` column.

Correct?

Now, some considerations:

Given that `pivot` is very general, it could produce any kind of "weird" result (suppose you specify `_value` as `columnKey` or `rowKey`...). So, I agree with you, `pivot` is too general to be swapped a priori with `range`.

Now, given that dealing with `pivot` and `range` order should be a very specific operation that happens at the beginning of the pipeline of operations just after `from`, as discussed with @nathanielc, we could directly include the ranging in `fromRows`. Or, to favor composability, we could provide a `toRows` operator equivalent to the specific pivoting applied in `fromRows`:

```
toRows = (tables=<-) =>
    tables
        |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
```

With this operator we allow to place a `filter` before the pivoting: `from |> filter |> range |> toRows`. If we provide a `fromRows(bucket, start, stop)` then you cannot specify filtering before pivoting. 

`toRows` can be swapped with `range` at any time (supposing that no user intentionally writes `toRows |> range` because he/she wants to preserve `null` columns). Although if `toRows` is applied after a schema change in which `_time`, `_field`, and `_value` have been erased, it looses meaning and a proper error should be reported.

Finally, providing `toRows` over `fromRows(bucket, start, stop)` could be nice also because flux could express streaming queries in the future, for which a specific `range` has no meaning.

**Comment by jlapacik** [comment]
@affo yes you are correct, that is exactly how a null column could occur. I'm not sure I see how we can swap `range` and `toRows` though. Don't we have the same issue? That being, `toRows |> range` potentially produces entire columns with `null` values, whereas `range |> toRows` cannot.

**Comment by affo** [comment]
The current implementation of `fromRows` is `from |> toRows` that produces the bug above.
I discussed with @aanthony1243 and we decide to split the two operations and provide documentation to explain that `toRows` cannot precede `range`.

We opted to split to allow filtering in between.

**Comment by aanthony1243** [comment]
@affo  agree. this can close.

**Comment by aanthony1243** [comment]
sorry, if you want to keep open for the error message you can. or else close it yourself and we can open a new issue that's more specific.
