### ISSUE TITLE
Group should implicitly sort by time

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/flux#3023]
Since Flux is targeted towards time series data, most users expect the output of group to be sorted by time. Many users also forget or do not know that grouping in Flux does not produce ordered results, which leads to issues about graphs displaying out of order lines. This is [called out prominently](https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/group/) in the docs and is easy to address with:

```
data
  |> group()
  |> sort(columns: ["_time"])
```

However, we've seen users continue to stumble on this problem (https://github.com/influxdata/giraffe/issues/219 and https://github.com/influxdata/influxdb/issues/18642).

This is a two part proposal:

- Add an optional parameter `sortTime: bool`  option to `group` that implicitly does a `sort(columns: ["_time"])` if a `_time` column is present.
- Set the `sortTime` parameter to default to `true`.

**Comment by jacobmarble** [comment]
Is this a Flux bug? Maybe my client doesn't mind out-of-order timestamps, so I prefer low latency to server-side sorting.

I think of this as a UI bug. Perhaps detect out-of-order timestamps and pop up a notification bar "detected out-of-order timestamps; consider adding `|> sort(...)` to the end of your query".

**Comment by gunnaraasen** [comment]
I think most people querying time series data expect, assume, and want time-ordered results. That also applies when using Flux via the API or client libs. It doesn't feel user-friendly to address this with a UI notification that requires the user understand the issue and take an action.

There would still be an option to turn off the time sort when performance matters.

**Comment by nathanielc** [comment]
@gunnaraasen Thanks for the feedback on this issue. 

There are a few reasons why we cannot assume that clients want data sorted by time:

* Not all clients will want to make the trade off of query performance for time sorted data (this is what @jacobmarble mentions)
* Flux does not deal with time series data exclusively, users query their sql database are not going to expect data to get automatically sorted by time.
* Sorts are expensive and require we materialize all of the data in memory. 

For these reasons we do not want to make the default behavior of group to sort by time. That said there are other ways we can address this usability problem. For clients we control like the UI we can add workflows to guide the user to add sort when needed. For clients we do not control we can add documentation around this specific behavior the explains the Flux way of dealing with this kind of use case.  There are probably other clever ways as well.

Closing this issue. Feel free to open new issues around other ways we can address this usability challenge.

**Comment by gunnaraasen** [comment]
@nathanielc What do you think about adding an optional sort by time parameter to group but not making it the default (default value is false)? Then the option would show up in function definitions and autocomplete.

**Comment by nathanielc** [comment]
We don't want to merge the semantics of sorting with grouping. Its straightforward to add a `|> sort` after a group when its needed. I see the point of an argument making it more obvious that group result will not be sorted but that can be accomplished with docs on the group function itself that clearly state that data is not sorted. Using the editor its as easy to get the documentation on a function as it is on the arguments of a function.
