### ISSUE TITLE
Flux Community Questions

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/flux#3028]
Hello all, 
Here are some of the unanswered community questions for the past several weeks. Thank you so much for your help! Please let me know if I can add anything to these issues to help you. 
https://community.influxdata.com/t/optimize-query-with-pivot/15214
https://community.influxdata.com/t/flux-top-from-all-tables/15256
https://community.influxdata.com/t/as-of-operations-and-irregular-spacing-of-data-using-flux/14612
https://community.influxdata.com/t/pivoting-data-with-count/14569
https://community.influxdata.com/t/need-last-flux-0-65-histogram-bucket-to-be-inf/14493
https://community.influxdata.com/t/values-in-column-table-behave-differently-in-query-result-compared-to-using-it-after-insert-into-bucket/14489
https://community.influxdata.com/t/stateduration-error-exhausting-result-iterator-err-failed-to-evaluate-map-function-unsupported-binary-expression-invalid-int/14368
https://community.influxdata.com/t/how-can-i-pass-null-as-literal/14174/4

**Comment by jsternberg** [comment]
I'll follow along with them but I have responded to all of the above issues in some manner.
