### ISSUE TITLE
Ensure we have good coverage of csv and json encoders and decoders.

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#304]
Once we have confidence in our coverage of the encoders through the units tests remove the unnecessary use of the encoder/decoders in the end to end tests.

**Comment by aanthony1243** [comment]
ideas:  
1.  Wrap the CSV encoder to take a block of text to diff, then we can possibly run the existing CSV tests to cover the encoder.  These could run similarly to how we have it set up now:  input.csv -> flux query -> output.csv 
2.  Wrap the CSV encoder + decoder together to ensure that production/consumption between the two are precise.
