### ISSUE TITLE
Have builtins.rs file use new syntax for type expressions

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#3042]
[builtins.rs](https://github.com/influxdata/flux/blob/master/libflux/src/core/semantic/builtins.rs) should use the new syntax for expressing types. In order for this change to take effect without error, the bootstrap process will have to be updated. In particular, [this line](https://github.com/influxdata/flux/blob/master/libflux/src/core/semantic/bootstrap.rs#L125) will need to be changed.

Here, `parse` references the old parser for type expressions. It will need to be replaced with a method that calls the new parser and then converts the AST to a semantic PolyType struct.

DOD:
* builtins.rs uses the new syntax for type expressions and all flux tests pass.

**Comment by ChitlangeSahas** [comment]
#3096
