### ISSUE TITLE
Add test cases for using tableFind and family inside of a map call.

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#3057]
I saw a recent use case in the wild where a user was iterating over rows in a table and using table find to perform an aggregate query in a different bucket.

The general form of the query was like this:

```
// Read data about which aggregations to compute
from(bucket: "queue")
    |> range(start: -1h)
    |> filter(...)
    // For each interval produce a row that is the new aggregation result
    |> map(fn: (r) => {
        start = time(v: r._value)
        stop = experimental.addDuration(to: start, d: 1h)
        measurement = r.measurement
        tagX = r.tagX
        agg = from(bucket: "rawdata")
            |> range(start: start, stop: stop)
            |> filter(fn: (r) => r._measurement == measurement and r.tagX == tagX)
            |> // Aggregation function
            |> findRecord(idx:0) // get the aggregation row
        return { r with
            _value: agg._value,
            _time: agg._time,
            _field: "value",
        }
    })
    // Write the table that now contains the updated aggregation results to the aggregation bucket
    |> to(bucket: "aggdata")
```

We should ensure this particular use of tableFind and friends is tested so we do not regress this behavior.

**Comment by nathanielc** [comment]
Notes:

* Ensure that the resource management is the same between the parent execution context and the children execution contexts. I.e. the Allocator etc such that the query as a whole fits in normal constraints for a query

**Comment by wolffcm** [comment]
@nathanielc I'm curious, have you seen a query like this actually work, like with your own eyes?

When I wrote a test case for this there were a couple of issues:
- The `compiler` does not handle pipe arguments correctly, so the call to `findRecord` complains of its required `tables` argument being missing
- The `compiler` produces a `values.Function` that does not implement the `interpreter.Resolver` interface, so when we call `filter` from inside of `map`, I get an error `function is not resolvable`

I've managed to fix both of these on my branch, so I'll open some PRs to fix them.
