### ISSUE TITLE
Allow fill to accept multiple columns

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#3059]
This was prompted by this community issue: https://community.influxdata.com/t/how-can-i-pass-null-as-literal/14174/5

I think it would make it easier to use join or pivot if fill was able to operate on multiple columns. At the current moment, you have to write a separate fill function for each column you want filled. It might be useful to allow fill to operate on multiple columns or to accept a schema such as these:

```
|> fill(columns: ["bookie1", "bookie2"])
|> fill(fn: (col) => col.label =~ /bookie/)
```

This would prevent the need to write a new fill function for each column that you want to fill.

**Comment by jplitza** [comment]
Even more: It would make it possible to fill a variable list of columns. Consider a pivot table whose columns you don't know beforehand. Currently, it's impossible to fill it.

**Comment by Shellkan37** [comment]
Any update about this issue ?

**Comment by arturCwiklinsky** [comment]
Same! Any update for this?

**Comment by gjWeitzel** [comment]
Also interested in an update.

**Comment by edwardmbsmith-hrl** [comment]
Interested, can we re-open?
