### ISSUE TITLE
Allow inf bin for the histogram function

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#3061]
The histogram function should have either an `inf` parameter or a way to specify a bucket as infinite. Either one of the two is likely acceptable:

```
// inf as a polymorphic constant, my preference
histogram(bins: [0.0, 1.0, 5.0, 10.0, inf])

// as an extra parameter
histogram(bins: [0.0, 1.0, 5.0, 10.0], inf: true)
```

At the moment, the `histogram` function doesn't have a generic way to specify an infinite bin. Instead, it will return an error when a value that is greater than the largest bin occurs. This can be worked around by choosing a value for the highest bin that is suitably high so inf doesn't have to be used.

Community question: https://community.influxdata.com/t/need-last-flux-0-65-histogram-bucket-to-be-inf/14493

**Comment by aiv-wizata** [comment]
@Jsternberg 
for custom bins I used `bins = [0.0, 1.0, 5.0, 10.0, math.mInf(sign: 1)]` and it works well
also you can use helper functions:
`bins = linearBins(start: minValue, width: binWidth, count: int(v:binCount), infinity: isInfinity)
 bins = logarithmicBins(start: minValue, factor: factor, count: int(v:binCount), infinity: isInfinity)
`
more info in [docs page](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/histogram/#bin-helper-functions)
