### ISSUE TITLE
Fix Panic and provide Better error messaging when setting a column to an invalid type

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#3068]
The following query:
```
from(bucket: "telegraf")
  |> range(start: -1m)
  |> filter(fn:(r) => r._measurement == "system" )
  |> filter(fn:(r) => r._field == "uptime" )
  |> map(fn:(r) => ({ r with something: duration(v: r._value * 1000000000) }))
```

Fails with the message ` panic: unknown type invalid`

The issue comes from trying to set a column in a table to a duration type.

The following works:
```
from(bucket: "telegraf")
  |> range(start: -1m)
  |> filter(fn:(r) => r._measurement == "system" )
  |> filter(fn:(r) => r._field == "uptime" )
  |> map(fn:(r) => ({ r with something: string(v: duration(v: r._value * 1000000000)) }))
```

1. the code should not panic
2. the error message returned should indicate the problem with setting a column to an incompatible type

**Comment by adrian-thurston** [comment]
Looks like this got fixed by 4b4f767bee35e5da9e0d862a192b44f0e6e6f2ab (#3137)
