### ISSUE TITLE
StateChangesOnly() and stateChanges() UX

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/flux#3075]
It would be great if you could specify the column that you want to apply stateChangesOnly and stateChanges() on, as well as set custom levels. For example, if I'm monitoring the state of of a battery, then my states might be "charging" or "draining". And users might not keep this state data in a "_level" column but rather a "batterystate" column. Providing this type of flexibility to these functions allows users to take advantage of the functions without having to design their schema around the functions or use maps() and rename() to change their data to fit the monitoring functions. Thank you!

**Comment by nick-wellinghoff** [comment]
It would also be nice if the function could take multiple state changes as a list of pairs. So {["state1","state2"], ["state1","state3"]} etc. This way change times could be noted for multiple changes in state in one call to the function. Right now I end up making multiple table streams, multiple calls to statechanges() and then join them. 
Thanks for all your hard work!
