### ISSUE TITLE
Create a method to construct a table from an array of records

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#3077]
This issue is building off of the PR from a hack day [here](https://github.com/influxdata/flux/pull/2861). That PR should be used as a reference and, if possible and appropriate, be adapted to fit the below formal description.

We want to construct a table from an array of records using Flux syntax. As an example:

```
import "experimental/array"

array.table(rows: [
    {_time: 2020-08-04T12:00:00Z, t0: "a-0", _value: 2.0},
    {_time: 2020-08-04T12:00:10Z, t0: "a-0", _value: 4.0},
    {_time: 2020-08-04T12:00:20Z, t0: "a-0", _value: 1.0},
    {_time: 2020-08-04T12:00:00Z, t0: "a-1", _value: 6.0},
    {_time: 2020-08-04T12:00:10Z, t0: "a-1", _value: 4.0},
    {_time: 2020-08-04T12:00:20Z, t0: "a-1", _value: 8.0},
    {_time: 2020-08-04T12:00:00Z, t0: "a-2", _value: 7.0},
    {_time: 2020-08-04T12:00:10Z, t0: "a-2", _value: 9.0},
    {_time: 2020-08-04T12:00:20Z, t0: "a-2", _value: 4.0},
])
```

This would construct a single table with 3 columns using the various values. The type signature for this function would be: `forall [t0] where t0: Row (rows: [t0]) -> [t0]`.

All of the columns will be created as normal values and not part of the group key. To convert a column to be part of the group key, the `group()` function will be used. A test and example should be included when we add this function.

```
array.table(rows: ...)
    |> group(columns: ["t0"])
```

Additionally, the function should check the rows input and forbid `*flux.TableObject` from being used as the array. This is needed because the `from()` function returns a value that looks identical to an array of rows, but the runtime won't expect that.

For this issue to be done:

* Implement the above description as a function in the `experimental/array` package.
* Ensure there are flux e2e tests for this functionality. One test for the base usage and one that is used with `group()`.
* The flux file must contain a docstring similar to this one: https://github.com/influxdata/flux/blob/master/stdlib/contrib/jsternberg/aggregate/aggregate.flux#L5

**Comment by jlapacik** [comment]
I'm a bit partial to `array.toTable(rows: ...)`, but overall extremely happy to see this.

**Comment by jsternberg** [comment]
`toTable` is fine also so if you pick up that issue feel free to try them both out and see which one feels better and then choose that one. We may also want to try out `array.from(rows: ...)` since that matches with an existing convention.

**Comment by wolffcm** [comment]
I'm really stoked that we can represent the type of this function so concisely.
