### ISSUE TITLE
Create functions for canonically returning an error message during execution

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#3079]
We should provide canonical way to produce an error as a query is executing (or is about to execute). Most of the time, the error will be associated with a source or a transformation, and we should include the name of the source or transformation in the message.

The idea is that we want to make it very easy to produce good error messages. Often our error messages are missing crucial information like source location info, the name of the function that produced the error, etc.

Note that it is very difficult to get useful source location info for the general case, so we should defer this work to a later issue, but we should pave the way for making it possible.

Here is a possible example (whoever gets this issue, feel free to change it)
```
// This could live in a new package flux/execute/errors?

// FluxItem describes an element in a user's script that produced an error during execution
type FluxItem interface {
    // Name returns the name of the source, transformation, etc that produced the error.
    Name() string

    // Location returns the place in the user's script where the item was used.
    // This is optional, implementors may return nil here.
    Location() *SourceLocation

    // DocURL returns a URL to our docs that explains usage of the item.
    // This is optional, implementors may return the empty string here.
    DocURL() string
}

// These functions all mirror what we have in `internal/errors`
func New(fi FluxItem, code codes.Code, msg ...interface{}) error {...}
func Newf(fi FluxItem, code codes.Code, fmtStr string, args ...interface{}) error {...}
func Wrap(fi FluxItem, err error, code codes.Code, msg ...interface{}) error {...}
func Wrapf(fi FluxItem, err error, code codes.Code, format string, a ...interface{}) error {...}
```
Here's an example:
```
   ...
  |> window(every: 0m)
   ...
```
would produce something like
```
Error executing function "window": duration used for parameter "every" cannot be zero
For more information, see https://docs.influxdata.com/flux/v0.65/stdlib/built-in/transformations/window/
```

DOD:
- Define an interface and a set of functions for producing errors
- Choose one simple transformation and implement `FluxItem` for it, and update the errors it returns the new functions
- Write tests that lock down the beautifully informative error messages you've created

**Comment by jsternberg** [comment]
I like the idea but I think it might be more useful if these attributes were assigned to the errors instead of the transformation. When we annotate an error message with a doc url, the doc url should be specific to the error encountered and the error itself could determine if it were going to link to the transformation.

I'd like to extend the existing errors interface. Right now, errors are defined with this struct:

```go
type Error struct {
	// Code is the code of the error as defined in the codes package.
	// This describes the type and category of the error. It is required.
	Code codes.Code

	// Msg contains a human-readable description and additional information
	// about the error itself. This is optional.
	Msg string

	// Err contains the error that was the cause of this error.
	// This is optional.
	Err error
}
```

We can add doc url to this and so errors can be annotated on each error. Since it is possible to wrap errors, we could produce something like this:

```
{
    code: "inherit",
    msg: "window",
    doc_url: "https://docs.influxdata.com/flux/v0.65/stdlib/built-in/transformations/window/",
    error: {
        code: "invalid",
        msg: "duration used for parameter \"every\" cannot be zero"
        doc_url: "https://docs.influxdata.com/flux/v0.65/stdlib/built-in/transformations/window/#every-parameter",
    }
}
```

Then when we convert the error to influxdb, we can get the most specific docs url associated with the underlying error. The source location could be another attribute we add to this or it can be the message when wrapping an error.

**Comment by wolffcm** [comment]
@jsternberg I'm totally fine with the doc URL being specific to the actual error and being put inside of Flux's main error struct, that makes a lot of sense to me.

What I would like to have is an API we can use such that we can take something that looks like this now:
https://github.com/influxdata/flux/blob/a252523d8a861df576b497fd7ad788dc0154afe4/stdlib/universe/fill.go#L205

And make it look something like this:
```go
return errors.NewWithURLf(t, "https://docs.influxdata.com/...", codes.FailedPrecondition, "column %q not found", t.spec.Column)
```
Where `errors` is the `execute/errors` package, not the generic Flux one, and `t` is a transformation.  Then we can extract the function name into the message automatically. If/when we can get Flux source location info from transformations, we can make that just start to work with little effort.

With something like this in place, we can check that files in `stdlib/` generally import `execute/errors` instead of `internal/errors`, and thus be reasonably sure that errors generated at runtime will at least have some context.

Does that make sense?

**Comment by jsternberg** [comment]
That does make sense. I'm not sure about the transformation interface or passing the transformation. I think the source information could probably be added in a different way that is more automated and doesn't involve adding another function. The source information originates from the function call and not the transformation. I also think the source information would work better as a nested error.

For example, error happens in transformation. It then gets wrapped in such a way:

```
errors.Wrap(err, codes.Inherit, "%s: %s", transformationName, sourceLocation)
```

I like the idea of adding a docs url though to the main error struct and I wouldn't have a problem with adding source location to the struct too. And I do think we can create new error functions that are specialized for specific areas so I'm fine with adding an `execute/errors` for wrapping errors specialized to execution. It might be better left to the developer to figure out the best way to annotate the error though.

**Comment by wolffcm** [comment]
After some discussion with Jonathan, this issue would be more appropriate: https://github.com/influxdata/flux/issues/3092

Closing this issue in favor of that one. There are other mechanisms to get more context into error messages automatically that we can explore.
