### ISSUE TITLE
A filter on r._value truncates table results to 1000 rows

### ISSUE THREAD

**Issue by coussej** [influxdata/flux#3110]
When you add a filter `fn: (r) => r._value > 0`, results per table are trucated to 1000 rows.

In the screenshot below you can find a query on a time-series containing points every 1s, all values are > 0. In query A (green), we get 3601 points, as expected. In query two (blue), with a filter on r._value that doesn't eliminate any point, the result is truncated to 1000 points. In chronograph, we see the exact same thing.

System context: Flux on InfluxDB 1.8.1.

<img width="880" alt="image" src="https://user-images.githubusercontent.com/9944663/90044890-933f6300-dcce-11ea-813b-aa4a6b2f733e.png">

<img width="1356" alt="image" src="https://user-images.githubusercontent.com/9944663/90044995-b702a900-dcce-11ea-85d6-e2b74ae85a13.png">

**Comment by yves-bourgeois** [comment]
We have this problem as well..

**Comment by nathanielc** [comment]
@coussej Thanks for the report, we will take a look at this.

**Comment by nathanielc** [comment]
As a note to whoever picks this one up it seems very similar to this previous issue https://github.com/influxdata/influxdb/pull/16600 That issues was fixed and backported to 1.8 and 1.7 so this current issue is likely different but probably similar in solution.

**Comment by jlapacik** [comment]
I'm putting this back on the backlog in case someone else has any bandwidth.

**Comment by yzhang1991** [comment]
This is fixed in https://github.com/influxdata/influxdb/commit/abfe5a54a0b419d0231762574229caddf971bbfd but for some reasons that I don't know, we did not backport the fix.

**Comment by coussej** [comment]
@yzhang1991 does you closing the issue means that the fix has been backported? Or is there some other place we should follow up?
