### ISSUE TITLE
Select operator proposal

### ISSUE THREAD

**Issue by affo** [influxdata/flux#312]
While writing some queries I realized that there is no operator similar to the `SELECT` statement in IFQL.  
Yes, we do have `fromRows` (now migrating to `toRows`) that builds a table with every field as column, but we don't have any operator that lets the user specify specific fields and tags to be organized into rows.

Something like:

```
from(bucket: "telegraf")
    |> range(start: -5m)
    |> filter(fn: (r) => r._measurement == "system")
    |> select(fields: ["load1", "ncpus"], tags: ["host"])
```

that returns a table with a schema like:

```
_time | _measurement | load1 | ncpus | host
```

A `select()` should be equivalent to the current `toRows()` and to `SELECT *` in IFQL.

At the moment it seems to be impossible to implement it using Flux because it cannot manage the list of fields. Just to provide an example of how it could be:

```
select = (field1="", field2="", tables=<-) =>
	tables 
            |> filter(fn: (r) => r._field == field1 OR r._field == field2)
    	    |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
    
from(bucket: "telegraf")
    |> range(start: -5m)
    |> filter(fn: (r) => r._measurement == "system")
    |> select(field1: "load1", field2: "n_cpus")
```

**Comment by nathanielc** [comment]
There are good ideas here which are very similar to #1411 Closing this issue for now so that tracking can happen on the parent issue.
