### ISSUE TITLE
Add unit conversion capabilities for IoT and monitoring uses

### ISSUE THREAD

**Issue by alsargent** [influxdata/flux#3126]
Our user [SeaBits](https://seabits.com/), which provides engine and power monitoring dashboards for marine use, is asking for unit conversion built into Flux, specifically temperature conversions from Kelvin to Fahrenheit and Celcius. 

Extrapolating from this request, it seems that conversions would be useful for many of our users across IoT, monitoring, and scientific use cases. This would be especially useful when converting between Metric and Imperial (US) units, as well as between Imperial measurements.

So, here's a request for the following types of conversion functions:

- Duration (toMilliseconds, toSeconds, toHours, etc.)
- Temperature (toCelcius, toFahrenheit, toKelvin, etc.)
- Distance (toInches, toMiles, toKilometers, etc.)
- Area (toSquareFeet, toAcres, toSquareKilometers, etc.)
- Volume (toOunces, toGallons, toLiters, etc.)
- Storage (toMegabytes, toMebibytes, toGibibytes, etc.)
- Weight/Mass (toPounds, toOunces, toGrams)
- Speed (toMPH, toKPH, etc.)
- Energy (toJoule, toCalorie, toKilowattHour)

Anti-goal: Don't implement conversion functions for metric, at least in the first version, since they simply involve multiplication or division by a power of ten.

For specific examples on how these conversion funtions might be used, here's more on SeaBits from a recent presentation:

![image](https://user-images.githubusercontent.com/20701/90413833-de0d0200-e063-11ea-8dc5-7e7c7d48387e.png)

![image](https://user-images.githubusercontent.com/20701/90413653-99816680-e063-11ea-910a-b2dd859d880f.png)

![image](https://user-images.githubusercontent.com/20701/90413675-a1d9a180-e063-11ea-9800-3386a35d94d4.png)

**Comment by nathanielc** [comment]
@alsargent I love the idea, these are all quite easy to construct, for example here is the function `toCelsius`:

```
package temperature

// ToCelsius converts a temperature in Fahrenheit to Celsius
toCelsius = (tables=<-) => 
    tables 
        |> map(fn: (r) => ({r with _value: fahrenheitToCelsius(f:r._value)}))

// fahrenheitToCelsuis converts a value from Fahrenheit to Celsius
fahrenheitToCelsuis = (f) => (f - 32.0) * 5.0 / 9.0
```

We would readily accept a contribution of a whole suite of packages under and umbrella `units` package to perform these kinds of conversions. 

Users can then use the packages like so:

```
import "units/temperature"

from()
   |> range()
   |> filter()
   |> temperature.toCelsius()
```

And we can build these up over time.
