### ISSUE TITLE
Add transformation-level profiler

### ISSUE THREAD

**Issue by yzhang1991** [influxdata/flux#3130]
Create a `transformation` profiler to expose more granular statistics at the transformation level.
Previous work on query tracing via OpenTracing in #1992 and influxdata/influxdb#15459 are good references for this.

In contrast to creating many many spans, a proposed solution to do this is to maintain a map instantiated for each query before we start to run the `Source`. The map keeps the duration for each transformation in the query, for example:
```go
var stats = map[string]int64{
	"merged_ReadRange_filter2_filter3_filter4": 1234,
	"window5 ": 1023,
	"mean6", 138,
}
```

Every transformation should update this map as soon as they finish running the `Process()` method. We should properly handle the race condition in this update process.

Generate a profiling result table at the end of the execution, 1 transformation per row. The result should at least contain the execution time, preferably some memory stats as well.

This issue does not consider how to expose profilers in Flux.

**Comment by jlapacik** [comment]
Where will this update occur? Will the `Process` method of every single flux builtin need to be updated or can this logic live in one place like the execute package?

**Comment by yzhang1991** [comment]
@jlapacik No, there is one place where this update can be made.
