### ISSUE TITLE
vague "derivative found out-of-order times in time column" message

### ISSUE THREAD

**Issue by ssoroka** [influxdata/flux#3134]
Built query with data explorer. Breaks on adding derivative after group. I realized afterwards my problem was that I was first grouping the data, then applying the derivative. Better messaging would be nice?

![Screen Shot 2020-08-19 at 5 01 54 PM](https://user-images.githubusercontent.com/7130/90689228-b07bb080-e23d-11ea-9119-0ddf35d03952.png)

As a side issue, unchecking the grouping doesn't resolve the problem once you get it (because it keeps the `group()` function around and hidden?)

**Comment by thulle** [comment]
Was also confused by this.
