### ISSUE TITLE
Add linear interpolation to integral

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#3136]
We should add an optional parameter to the `integral` function for interpolating the values at both the range `_start` and the `_stop` times. Integration with linear interpolation would then be expressed as

    ... |> integral(unit: 1s, interpolate: "linear")

The motivation for adding this is [time weighted average](https://github.com/influxdata/flux/issues/2891). Ideally, time weighted average will be implemented in terms of `integral` like so:
```
timeWeightedAvg = (table=<-, unit) => table
    |> integral(unit: unit, interpolate: "linear")
    |> map(fn: (r) => ({ r with _value: r.value / ( float(v: r._stop) - float(v: r._start) ) }))
```

From this example one can see that time weighted average requires one to divide by the length of the interval over which one is integrating. By not interpolating both the start and the stop times of the range during integration, we are integrating over a strict subset of the range. Dividing by the length of the range after integration will then result in a possibly severely underestimated value.

Note that linear interpolation will require each table to have at least two data points. Also in the case that a table contains a data point whose timestamp falls on the `_start` time of the range, that data point should be used in place of an interpolated one.

**Comment by jlapacik** [comment]
DOD:

* Builtin type signature of `integral` is updated with new optional parameter
* Unit tests exist exercising new interpolation code path
* Flux end to end test is added using new optional parameter

**Comment by jsternberg** [comment]
Are `_start` and `_stop` added by integral and are they part of the group key or just normal values? I'm unfamiliar with how `integral` currently works and what the proposed change is. If we can get an example of current behavior and where it falls short along with proposed behavior that would help me to visualize what is being asked here.

**Comment by jlapacik** [comment]
`_start` and `_stop` are not currently used by `integral`, however after this change, `_start` and `_stop` will be required columns. Also the implicit assumption here is that they are part of the group key.

Right now `integral` approximates the area under the curve, where `_time` represents the x-axis and `_value` represents the y-axis. The boundaries however are the first and last data point in the interval - not the `_start` and `_stop` times. If you'd like to integrate over the entire range of your interval (regardless of whether you have data points that lie on the boundaries), you need to generate data points for the boundaries (`_start` and `_stop` times). A simple way to generate these points is to perform linear interpolation using the first two data points and the last two data points in the interval respectively. This way you can integrate over your entire time range instead of a strict subset.

```
| --A-------B---C----------D-------E------- |
```

If A thru E are points on the `_time` axis, the current behavior of `integral` is to approximate the area under the curve from time `A` to time `E`. With the new `interpolate` option, one can generate data points at the beginning and end of the interval to approximate the area under the curve for the entire range.
