### ISSUE TITLE
flux uses deprecated gonum library

### ISSUE THREAD

**Issue by aviau** [influxdata/flux#314]
Hello!

Flux uses a deprecated  version of the gonum library, it should switch to this import path:
 - gonum.org/v1/gonum/

See:
 - https://github.com/gonum/gonum

**Comment by nathanielc** [comment]
@aviau Thanks for the heads up!

**Comment by aviau** [comment]
Just so you know, this is a blocker for InfluxDB 1.7 in Debian.
