### ISSUE TITLE
SPEC.md would benefit from a TOC

### ISSUE THREAD

**Issue by rickspencer3** [influxdata/flux#3141]
It can be quite hard to find sections of: https://github.com/influxdata/flux/blob/master/docs/SPEC.md 

A TOC would make it a bit easier to navigate.

**Comment by rickspencer3** [comment]
@rbetts FYI

**Comment by pierwill** [comment]
I'm working on reviewing the spec as part of https://github.com/pierwill/flux-redex. I can take this on as well.
