### ISSUE TITLE
sort function not sorting after join

### ISSUE THREAD

**Issue by nanicpc** [influxdata/flux#3149]
I'm joining 2 tables generated from the same source. I want to get the bottom 5 values of the joined table sorted by _value.
For an unknown reason sort and limit are not working. Could you help me understand if this is a bug or I'm just using badly the functions. thanks 

Here my code:
````
total = from(bucket: "b1")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "last")
  |> filter(fn: (r) => r["_field"] == "q1" or r["_field"] == "q2")
  |> group(columns: ["key"])
  |> aggregateWindow(every: inf, fn: sum, createEmpty: false)


p1 = from(bucket: "b1")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "last")
  |> filter(fn: (r) => r["_field"] == "q1")
  |> group(columns: ["key"])
  |> aggregateWindow(every:inf, fn: sum, createEmpty: false)

join(tables: {t1: total, t2: p1}, on: ["_time","key"])
|> map(fn: (r) => ({ r with _value: float(v:r._value_t2) / float(v:r._value_t1) *100.0 }))
|> sort(columns:["_value"], desc: true)

**Comment by nathanielc** [comment]
@nanicpc The sort should work in this case? Can you add some details about the data you get back from the query?

**Comment by nanicpc** [comment]
Yes off course.

`#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,long,long,string
#default,_result,,,,,,,,,,

,result,table,_start_t1,_start_t2,_stop_t1,_stop_t2,_time,_value,_value_t1,_value_t2,key
,,0,2020-08-25T13:00:00Z,2020-08-25T13:00:00Z,2020-08-26T22:00:00Z,2020-08-26T22:00:00Z,2020-08-26T22:00:00Z,99.74811083123426,397,396,32230
,,1,2020-08-25T13:00:00Z,2020-08-25T13:00:00Z,2020-08-26T22:00:00Z,2020-08-26T22:00:00Z,2020-08-26T22:00:00Z,100,175,175,32232
,,2,2020-08-25T13:00:00Z,2020-08-25T13:00:00Z,2020-08-26T22:00:00Z,2020-08-26T22:00:00Z,2020-08-26T22:00:00Z,96.45669291338582,254,245,32242
,,3,2020-08-25T13:00:00Z,2020-08-25T13:00:00Z,2020-08-26T22:00:00Z,2020-08-26T22:00:00Z,2020-08-26T22:00:00Z,100,1830,1830,32264
,,4,2020-08-25T13:00:00Z,2020-08-25T13:00:00Z,2020-08-26T22:00:00Z,2020-08-26T22:00:00Z,2020-08-26T22:00:00Z,100,307,307,32271-01
,,5,2020-08-25T13:00:00Z,2020-08-25T13:00:00Z,2020-08-26T22:00:00Z,2020-08-26T22:00:00Z,2020-08-26T22:00:00Z,100,627,627,32272`

**Comment by nathanielc** [comment]
I see whats up now, the `sort` function will sort each table/group independently. The data being returned has 6 tables and tables and each table has a single row. 

If you change the query like this it will combine all the tables into a single table just before sorting.

```
total = from(bucket: "b1")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "last")
  |> filter(fn: (r) => r["_field"] == "q1" or r["_field"] == "q2")
  |> group(columns: ["key"])
  |> aggregateWindow(every: inf, fn: sum, createEmpty: false)


p1 = from(bucket: "b1")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "last")
  |> filter(fn: (r) => r["_field"] == "q1")
  |> group(columns: ["key"])
  |> aggregateWindow(every:inf, fn: sum, createEmpty: false)

join(tables: {t1: total, t2: p1}, on: ["_time","key"])
|> map(fn: (r) => ({ r with _value: float(v:r._value_t2) / float(v:r._value_t1) *100.0 }))
|> group() // combine all tables into a single table
|> sort(columns:["_value"], desc: true)
```

**Comment by nanicpc** [comment]
thanks a lot! I didn't get what the table column was doing and I wasn't able to find out using the docs.

**Comment by nanicpc** [comment]
This just leave me a question that I would leave here as comment. mergeKey is now deprecated since flux [0.35.0](https://v2.docs.influxdata.com/v2.0/reference/release-notes/flux/#v0-35-0-2019-07-02) How I'm I suppose to get the same result whitout mergeKey?

Thanks for the feedback

**Comment by nathanielc** [comment]
@nanicpc The use of the `with` syntax is what replaces the `mergeKey` behavior.

You are using it here in the `map` function:
```
|> map(fn: (r) => ({ r with _value: float(v:r._value_t2) / float(v:r._value_t1) *100.0 }))
```
Doing `{r with ...}` means you are keeping everything that was previously on `r` and adding/changing whatever you specify after the `with` keyword.
