### ISSUE TITLE
Update SPEC for "column" parameter of "first" and "last" selectors

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#3150]
The selectors `first` and `last` accept a `column` argument. It's not documented in either our SPEC or in the user-facing docs, and it's not obvious what this argument does. `first` and `last` will find the first or last row where there is a non-null value in the given column, which is `_value` by default.

We should update the SPEC to reflect this.

(I was mistaken about what this parameter does when I wrote this issue, the original description is below)

---

~~Recently I found a query in the wild:~~
```
...
  |> last(column: "column_name")
...
```
~~The `column` parameter is not documented nor does it appear to be used by the code for `last` in flux or in storage as a pushed-down operation. The fact that a user can supply this parameter and their query runs without error suggests that it will take the largest value in the column. I guess that is really the same as `max`.~~

~~Note that `last(column: "_value")`(explicitly supplying the default value for `column` here)  would suggest that it behaves the same as `max` but that is not in fact what it does. It just takes the last row in the table, regardless of any column values.~~

~~This is tricky because we want `last` and `first` to be accepted by `aggregateWindow(fn: ...)` so it needs to match the signature of other selectors like `max` and `min`.~~

~~One solution to this would be to produce an error if the `column` parameter gets a value other than `_value`. It would be nice to be able to also produce an error if the user explicitly provides `_value` as a value as well.~~

**Comment by nathanielc** [comment]
The spec states 

> Last is a selector operation. Last selects the last non null record from the input table.

Seems like this is a bug where the implementation of last needs to check the column value to determine if the value is null.

For pushdowns this isn't normally an issue because we don't represent null values inside of storage. But the Go implementation on the Flux side should be checking the column values for null and skipping them. 

That should also remove the confusion about the purpose of the column and we should document that its the only purpose of the column.

**Comment by wolffcm** [comment]
@nathanielc Ah, this makes sense. Yes, that is what it does. The work of this issue should be to update the documentation. I'll update the title and the description.

**Comment by R-Studio** [comment]
I think there is also an bug on the last() function:
https://github.com/influxdata/influxdb/issues/20486 
_I hope this helps_
