### ISSUE TITLE
Catch and handle all panics from Rust

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#3165]
This issue is to ensure that we never panic from Rust code:
https://github.com/influxdata/flux/issues/2706

However, we should be defensive and not assume that panics are truly impossible. We should attempt to unwind any panics that occur with `catch_unwind` or something similar:
https://doc.rust-lang.org/beta/std/panic/fn.catch_unwind.html

Note: the catch/unwind should be common code that is called from all our public libflux functions.

DOD:
- We use `catch_unwind` to catch panics from Rust code
- A test exists that shows Rust code invoked from Go panicking, and that an error is returned to Go, and the process exits normally:
  - Create a separate binary that is created from a Go program that uses the catch/unwind code to recover from a panic and return an error
  - It should have it's own build commands and a corresponding make target that is called from CI

**Comment by fchikwekwe** [comment]
I'm not familiar with this code, but I'd like to pair with whoever picks this up, or at least review the resulting PR.

**Comment by scbrickley** [comment]
[This panic](https://github.com/influxdata/flux/blob/master/libflux/src/core/scanner/mod.rs#L108) caused an incident recently. We should make sure we change it to report an error as part of this issue.

**Comment by scbrickley** [comment]
It's also worth noting that another panic was occurring [here](https://github.com/influxdata/flux/blob/c75d2b96fafc24ef0ea254937cfd5c2e4112c19c/libflux/src/core/scanner/mod.rs#L171), because `token_start` was out of bounds, but I believe it has been resolved by #3187
