### ISSUE TITLE
query should expose error when context is cancelled mid-execution

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#318]
See issue #306 .
See PR #317 .

Currently if a query's context is cancelled during execution of that query, execution is halted and the query returns, but no error is exposed. An error specifying that execution was ended early should be exposed via the query's `Err()` method:
https://github.com/influxdata/flux/blob/54f9e3facf8689f3d7d3a0c7069a6ffd7903fb19/control/controller.go#L634

**Comment by jsternberg** [comment]
I think the controller does this now and the controller is now in influxdb.
