### ISSUE TITLE
Should aggregateWindow with min and createEmpty: true create empty points?

### ISSUE THREAD

**Issue by bettse** [influxdata/flux#3181]
I'm not certain if this is my misunderstanding something, but when I use 'mean' with `aggregateWindow(createEmpty: true...)` I get the expected disconnected line, but this doesn't happen when I use min or max.  

<img width="1430" alt="Screen Shot 2020-09-04 at 9 12 17 PM" src="https://user-images.githubusercontent.com/115752/92297370-84c22100-eef3-11ea-9d1f-1ca80feaacd7.png">

**Comment by herrBez** [comment]
The same holds for the "last" function.

**Comment by salakhovilia** [comment]
The same holds for the max, first functions
