### ISSUE TITLE
Strange block appears if entering influxdb in Flux mode 

### ISSUE THREAD

**Issue by lchtbruno** [influxdata/flux#3185]
If I enter the influxdb in flux mode and want to perform a simple calculation I use the following commands

![image](https://user-images.githubusercontent.com/43037659/92746645-bcade600-f383-11ea-83a0-1442f5a073f1.png)

however, once I press enter, a strange block appears and cannot be removed without closing the terminal:
![image](https://user-images.githubusercontent.com/43037659/92746719-cafc0200-f383-11ea-97a0-2a49e8f088c5.png)

If I enter the influx in flux and want to perform a regular influx command, for example "show databases" a different block appears
![image](https://user-images.githubusercontent.com/43037659/92747473-858c0480-f384-11ea-9b79-6285e5773808.png)

How do I get rid of this bug?

**Comment by nathanielc** [comment]
This is a bug with the shell library we are using, it breaks on certain terminals. I do not have a workaround at the moment. We are open to using a different shell library or just removing it entirely and using a simple readline based approach. PRs are welcome for this change and I can help point you in the right direction in the code if that is something you would be interested in doing.
