### ISSUE TITLE
Community Questions 9/11

### ISSUE THREAD

**Issue by mhall119** [influxdata/flux#3188]
Can somebody help with the following questions from the community?

- [Trying to increment a value whenever success=True in a measurement](https://community.influxdata.com/t/mapping-a-table-with-increasing-values/15868)
- [Testing experimental.join](https://community.influxdata.com/t/join-big-measurements-together-error-bad-gateway/15543/10)
- [Using Flux to check field data type](https://community.influxdata.com/t/type-test-in-flux/15936)
- [Python client error failing with Flux query even though flux-enabled=true in config
](https://community.influxdata.com/t/http-response-body-bflux-query-service-disabled-verify-flux-enabled-true-in-the-http-section-of-the-influxdb-config-n/15867)

Thanks!

**Comment by jsternberg** [comment]
I've responded to the first one. I have not looked at the others. If someone has time, feel free to pick up this issue or a specific question above.
