### ISSUE TITLE
Make operator profiler result queryable

### ISSUE THREAD

**Issue by yzhang1991** [influxdata/flux#3199]
@yzhang1991 commented on [Tue Sep 08 2020](https://github.com/influxdata/idpe/issues/8509)

## Background
You can skip this section if you are already familiar with how profilers currently work.
### General framework and workflow
https://github.com/influxdata/idpe/issues/8134 set forth a profiler framework for Flux and idpe. The [`Profiler`](https://github.com/influxdata/flux/blob/master/execute/profiler.go#L12) interface is currently defined as follows:
```go
type Profiler interface {
	Name() string
	GetResult(q flux.Query, alloc *memory.Allocator) (flux.Table, error)
}
```
In https://github.com/influxdata/idpe/issues/8134, we introduced the first profiler called "query" profiler. Later in https://github.com/influxdata/flux/issues/3130, an "operator" profiler is introduced.

Profilers are registered globally like planner rules and they are all disabled by default. The `profiler.enabledProfilers` option can control which profiler is enabled. This option is handled in the same way as to how `planner.disablePhysicalRules` is currently handled. The process now is:
* Your query, after being parsed and semantically analyzed, becomes an `AstProgram` (Flux REPL does not use this path, so profilers currently do not work with the Flux REPL)
* Before we start an `AstProgram` (execute the query), we will examine the value of `profiler.enabledProfilers`([code](https://github.com/influxdata/flux/blob/master/lang/compiler.go#L444)).
* If any profiler is specified in the option, we will look it up in the registered profiler list then instantiate a corresponding profiler.
* The profiler instances will be attached to the `AstProgram`. They will be asked to give a profiling result table after a query finishes execution and result encoding by calling their `GetResult()` function.
* The profilers' behaviors vary and the only thing we care about is that they can correctly produce a profiling result table when they are asked to.

### The "query" profiler
We have been collecting statistics for queries we run for quite a while but they were just not quite user-visible. We store them in a [`flux.Statistics`](https://github.com/influxdata/flux/blob/master/query.go#L37) structure that exists in every [`flux.Query`](https://github.com/influxdata/flux/blob/master/query.go#L10) implementation. The `flux.Query` interface represents an active query and it provides a `Statistics()` method to retrieve the statistics. These statistics cover many things like the time we spent at various stages of query execution and some memory stats as well as other metadata. In Flux REPL, we only collect allocator stats and the query plan. In OSS and Cloud, we also collect duration stats and record the number of bytes and values that the engine has read.

`flux.Statistics` contains `TotalDuration` data, which by definition includes the time it took to encode the results: [link to code](https://github.com/influxdata/idpe/blob/master/influxdbv2/query/bridges.go#L147). To give users the complete statistics data, we decided in https://github.com/influxdata/idpe/issues/8134 that the profiling result tables are appended directly to the encoded results we send to users. This means those tables cannot go through any Flux transformations and so they are not queryable.

### The "operator" profiler
The "operator" profiler is by far the profiler that captures duration statistics at the finest granular level. It basically captures every `Source.Run()` and `Transformation.Process()` call and measure their execution time (potentially memory stats in the future as well). Therefore, unlike the "query" profiler that only returns 1 row of data in its table for the whole query being executed, the "operator" profiler can potentially return a lot of rows, depending on how many calls in total we made to transformations and data sources.

Below is an example to give readers some ideas about how big the row count could be:
```
import "internal/gen"
gen.tables(n: 10, tags: [{name: "tag1", cardinality: 2}, {name: "tag2", cardinality: 3}])
```
In the Flux query above we used a `gen.tables()` to generate tables that have two tags with different cardinality 2 and 3, respectively. By default the data is grouped by both tag1 and tag2, so we are getting in total `2 x 3 = 6` tables:
```
#group,false,false,true,true,false,false
#datatype,string,long,string,string,dateTime:RFC3339,double
#default,_result,,,,,
,result,table,tag1,tag2,_time,_value
,,0,xYZav,YqWJX,2020-09-11T07:48:50Z,-77.25649709016866
,,1,B5OK,rvEJS2,2020-09-11T07:48:50Z,-115.01876350958007
,,2,B5OK,oiKL6N,2020-09-11T07:48:50Z,44.151919179260176
,,3,B5OK,YqWJX,2020-09-11T07:48:50Z,-32.078881540559266
,,4,xYZav,rvEJS2,2020-09-11T07:48:50Z,123.05891396416939
,,5,xYZav,oiKL6N,2020-09-11T07:48:50Z,-18.84766444674421
```
During execution, after the data source generated those tables, each of them will be sent off to subsequent transformations:
[[link to code](https://github.com/influxdata/idpe/blob/master/influxdbv2/query/stdlib/influxdata/influxdb/source.go#L76)]
```go
func (s *Source) processTables(ctx context.Context, tables query.TableIterator, watermark execute.Time) error {
	err := tables.Do(func(tbl flux.Table) error {
		// each table will start its own journey in a chain of subsequent transformations
		return s.processTable(ctx, tbl)
	})
// code omitted
```
Consider the following query:
```
import "internal/gen"
gen.tables(n: 10, tags: [{name: "tag1", cardinality: 2}, {name: "tag2", cardinality: 3}])
|> sort()
|> limit(n: 2)
```
Both the `sort` and the `limit` transformation will be called 6 times, but their execution could be done in parallel through our [`PoolDispatcher`](https://github.com/influxdata/flux/blob/master/execute/dispatcher.go#L28).
If `group`, `join`, or even `map` is involved in the game and regrouping happens, the number of tables could change in the middle of the chain of transformations. For example, if after regrouping, the number of tables doubled to 12 from 6, then all subsequent transformations will be called 12 times instead of 6 as well. See [`dataset.Finish()`](https://github.com/influxdata/flux/blob/master/execute/dataset.go#L164) implementation:
```go
func (d *dataset) Finish(err error) {
	if err == nil {
		// Only trigger tables we if we not finishing because of an error.
		d.cache.ForEach(func(bk flux.GroupKey) { // <----- Here!!
			if err != nil {
				return
			}
			err = d.triggerTable(bk)
			d.cache.ExpireTable(bk)
		})
	}
	d.ts.Finish(d.id, err)
}
```

With all that, we now know the "operator" profiler's result could have many many rows depending on the complexity of the query and the grouping scheme of the data that the query is executed on. An example output of the "operator" profiler is given below:
```
#group,false,false,true,false,false,false,false,false
#datatype,string,long,string,dateTime:RFC3339,dateTime:RFC3339,string,string,long
#default,_profiler,,,,,,,
,result,table,_measurement,_start,_stop,Type,Label,Duration
,,1,profiler/operator,2020-09-08T06:49:09.399718Z,2020-09-08T06:49:09.399804Z,*gen.Source,internal/gen.tables0,85941
,,1,profiler/operator,2020-09-08T06:49:09.399728Z,2020-09-08T06:49:09.399836Z,*gen.Source,internal/gen.tables4,107912
,,1,profiler/operator,2020-09-08T06:49:09.399812Z,2020-09-08T06:49:09.399844Z,*universe.sortTransformation,sort1,31419
,,1,profiler/operator,2020-09-08T06:49:09.399847Z,2020-09-08T06:49:09.399856Z,*universe.sortTransformation,sort1,9627
,,1,profiler/operator,2020-09-08T06:49:09.399906Z,2020-09-08T06:49:09.399915Z,*universe.sortTransformation,sort5,8852
,,1,profiler/operator,2020-09-08T06:49:09.399915Z,2020-09-08T06:49:09.399923Z,*universe.sortTransformation,sort5,7706
,,1,profiler/operator,2020-09-08T06:49:09.399925Z,2020-09-08T06:49:09.399931Z,*universe.sortTransformation,sort5,6589
,,1,profiler/operator,2020-09-08T06:49:09.399932Z,2020-09-08T06:49:09.399938Z,*universe.sortTransformation,sort5,6567
,,1,profiler/operator,2020-09-08T06:49:09.399964Z,2020-09-08T06:49:09.399987Z,*universe.limitTransformation,limit2,23929
,,1,profiler/operator,2020-09-08T06:49:09.399988Z,2020-09-08T06:49:09.399996Z,*universe.limitTransformation,limit2,8463
,,1,profiler/operator,2020-09-08T06:49:09.400009Z,2020-09-08T06:49:09.400018Z,*universe.deprecatedFillTransformation,fill6,9493
,,1,profiler/operator,2020-09-08T06:49:09.400019Z,2020-09-08T06:49:09.400025Z,*universe.deprecatedFillTransformation,fill6,6623
,,1,profiler/operator,2020-09-08T06:49:09.400026Z,2020-09-08T06:49:09.400033Z,*universe.deprecatedFillTransformation,fill6,6288
,,1,profiler/operator,2020-09-08T06:49:09.400035Z,2020-09-08T06:49:09.400041Z,*universe.deprecatedFillTransformation,fill6,6315
,,1,profiler/operator,2020-09-08T06:49:09.400066Z,2020-09-08T06:49:09.400079Z,*universe.groupTransformation,group3,12638
,,1,profiler/operator,2020-09-08T06:49:09.400081Z,2020-09-08T06:49:09.400084Z,*universe.groupTransformation,group3,2491
,,1,profiler/operator,2020-09-08T06:49:09.400092Z,2020-09-08T06:49:09.400215Z,*universe.mapTransformation,map7,122453
,,1,profiler/operator,2020-09-08T06:49:09.400218Z,2020-09-08T06:49:09.4003Z,*universe.mapTransformation,map7,81980
,,1,profiler/operator,2020-09-08T06:49:09.400303Z,2020-09-08T06:49:09.400381Z,*universe.mapTransformation,map7,78400
,,1,profiler/operator,2020-09-08T06:49:09.400384Z,2020-09-08T06:49:09.400461Z,*universe.mapTransformation,map7,77567
,,1,profiler/operator,2020-09-08T06:49:09.400495Z,2020-09-08T06:49:09.400504Z,*universe.mergeJoinTransformation,join9,9100
,,1,profiler/operator,2020-09-08T06:49:09.400508Z,2020-09-08T06:49:09.400511Z,*universe.groupTransformation,group8,3614
,,1,profiler/operator,2020-09-08T06:49:09.400513Z,2020-09-08T06:49:09.400515Z,*universe.groupTransformation,group8,1943
,,1,profiler/operator,2020-09-08T06:49:09.400515Z,2020-09-08T06:49:09.400516Z,*universe.groupTransformation,group8,1383
,,1,profiler/operator,2020-09-08T06:49:09.400517Z,2020-09-08T06:49:09.400519Z,*universe.groupTransformation,group8,1390
,,1,profiler/operator,2020-09-08T06:49:09.400526Z,2020-09-08T06:49:09.40055Z,*universe.mergeJoinTransformation,join9,23929
```
With a profiling data table like this, a user may want to:
* Filter out the data from transformations they don't care
* Sort the data by execution duration to find the most time-consuming operator
* Aggregate the data by the operator type
* Filter the data by a time range to see what operators are running in parallel within the given period of time.
* ...

I think it would be really nice if we could make the profiler result queryable.

## Implementation Proposals

We can start by only allowing the "operator" profiling result to become queryable since we cannot get a complete "query" profiler result before the whole query finishes. However, we can also leave out the `TotalDuration` in the "query" profiler result and make the rest columns queryable. But I don't see much value in querying the "query" profiler result because it has only 1 row anyway.

### Approach 1: `profilingResult()` transformation
I propose a `profilingResult()` transformation. When added to a query, this transformation will read the profiling result up to the point where it is placed and forward it directly to the subsequent transformations.
For example, summing the duration in the profiling result group by "Type":
```
import "internal/gen"
import "profiler"
option profiler.enabledProfilers = ["operator"]

a = gen.tables(n: 10, tags: [{name: "tag1", cardinality: 2}])
|> sort()
|> limit(n: 2)
|> group()

b = gen.tables(n: 10, tags: [{name: "tag1", cardinality: 4}])
|> sort()
|> fill(usePrevious: true)
|> map(fn: (r) => ({r with x: 1}))
|> group()

join(tables: {a: a, b: b}, on: ["_time"])
|> profilingResult()
|> group(columns: ["Type"])
|> sum(column: "Duration")
```
In this case, the join result is discarded.

### Approach 2: `profilingResult()` data source
An alternative idea started by @nathanielc is that we could implement this as a data source. At the same time, we make a special case for this data source that the result derived from this data source will always yield a final result regardless of whether an explicit/implicit `yield()` exists on that query or not.

With this, summing the duration in the profiling result group by "Type" would become:
```
a = ...
b = ...

join(tables: {a: a, b: b}, on: ["_time"])

profilingResult()
|> group(columns: ["Type"])
|> sum(column: "Duration")
```
Running the above Flux script will yield a `_result` that contains the join result, as well as a `_profiler` that contains the processed profiling result.

---

@yzhang1991 commented on [Wed Sep 16 2020](https://github.com/influxdata/idpe/issues/8509#issuecomment-693780686)

After the working group meeting, we kind of converged on choosing the data source version of the implementation. A hypothetical definition is like:
```
builtin profile
operator = (by=[], fn=pass) => {
    p = profile(name: "operator")
    return if length(arr: by) == 0 then p else p |> group(columns: by) |> pass()
}
```
You can use it in the following way:
```
import "profiler"
profiler.operator()
|> ... whatever you want

or:
profiler.operator(fn: sum, by: ["Type"])
```

**Comment by yzhang1991** [comment]
Workflow:

1. The interpreter evaluates the AST, generates a bunch of side effects (table objects)
2. If we find a TableObject that is derived from a profiler data source, instantiate the profiler and move the TableObject to the profiler.
3. After the query finishes, plan the profiler query and execute it in a newly created execution state.
4. Append the result to the query result.

**Comment by nathanielc** [comment]
Closing this for now, as we have decided to go a difference direction with the profiler. We can reopen this issue if we come back to this design.
