### ISSUE TITLE
Group operator seems to drop records

### ISSUE THREAD

**Issue by affo** [influxdata/flux#320]
I am querying an InfluxDB nightly installation using the sandbox and chronograph. The bucket is `telegraf` and the measurement is `syslog` (populated using telegraf's plugin).

The schema is:

```
_start dateTime:RFC3339
_stop dateTime:RFC3339
_time dateTime:RFC3339
_value long
_field string
_measurement string
appname string
facility string
host string
hostname string
severity string
```

* `appname` has these values: `liblogging-stdlog`, `root`;
* `facility`: `local7`, `user`;
* `host`: `telegraf-getting-started`;
* `hostname`: `3572b3c13668`, `53c2b67abcd4`, `ef2cfc9e335f`
* `severity`: `err`, `info`, `notice`, `warning`

This is the query:

```
from(bucket: "telegraf")
    |> filter(fn: (r) => r._measurement == "syslog")
    |> range(start: -1y)
    |> group(by: ["facility"])
```

The result only contains one group with `facility` = `local7`. Shouldn't it contain another table with results for `user`?

Indeed, if I run this query:

```
from(bucket: "telegraf")
    |> filter(fn: (r) => r._measurement == "syslog" AND r.facility == "user")
    |> range(start: -1y)
```

I get a bunch of results for `facility` = `user`.

A similar behavior happens if I group by `appname`, `hostname`, or `severity`.

**Comment by affo** [comment]
Related to #321.  
The problem lies in grouping together records that have different types for some column, in this case `_value`.

This query:

```
from(bucket: "test")
    |> range(start: -1y)
    |> filter(fn: (r) => r._measurement == "syslog")
    |> group(by: ["facility"])
```

yields only a piece of the result and crashes silently (server side) with:

```
csv encoder error: expected integer cursor type, got *reads.stringMultiShardArrayCursor
```

This query:

```
from(bucket: "test")
    |> range(start: -1y)
    |> filter(fn: (r) => r._measurement == "syslog")
    |> drop(columns: ["_value"])
    |> group(by: ["facility"])
```

Runs smoothly (no `_value` column).

However, this is an expected result: the user is trying to group heterogenous schemas in the same table.

The error is silent because the query handler doesn't return an error in case something has been written in the response: https://github.com/influxdata/platform/blob/master/http/query_handler.go#L85.

Should we simply return a meaningful error message? @aanthony1243 

In this case, should we wrap these kind of errors (https://github.com/influxdata/platform/blob/master/storage/reads/table.gen.go#L227) in a custom error type in order to detect them and return something like:

```
You are trying to group tables with different schemas, try to remove some columns.
```

**Comment by stuartcarnie** [comment]
This is a duplicate of influxdata/platform#47. @nathanielc and I had a discussion and agree we need to define the expected behavior in the spec and then implement that solution.

**Comment by affo** [comment]
Duplicate of #321
