### ISSUE TITLE
Delete builtins.rs

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#3205]
`builtins.rs` is redundant. It should be deleted and type inference should use the types that are now a part of the builtin statement.

DOD:

* The generation of the serialized types in Rust will no longer consult the builtin.rs code but will instead consult the semantic graph and get the type from the builtin statement.
* `builtins.rs` no longer exists

**Comment by ChitlangeSahas** [comment]
✨✨✨ Great to see this happening! Thank you @jlapacik!!

**Comment by nathanielc** [comment]
Closed by #3222
