### ISSUE TITLE
Cursor type error when grouping causes schema collision

### ISSUE THREAD

**Issue by affo** [influxdata/flux#321]
I am querying an InfluxDB nightly installation using the sandbox and chronograph. The bucket is `telegraf` and the measurement is `syslog` (populated using telegraf's plugin).

The schema is:

```
_start dateTime:RFC3339
_stop dateTime:RFC3339
_time dateTime:RFC3339
_value long
_field string
_measurement string
appname string
facility string
host string
hostname string
severity string
```

This is the base query:

```
from(bucket: "telegraf")
    |> filter(fn: (r) => r._measurement == "syslog")
    |> range(start: <start>)
```

By grouping by some tag (e.g. `severity` or `facility`) and tuning the `start` of the range I am able to produce this error:

```
{"error":"csv encoder error: expected integer cursor type, got *reads.stringMultiShardArrayCursor"}
```

Even if the query without `group` runs fine.

**Comment by affo** [comment]
Again, with query:

```
from(bucket: "telegraf")
  |> filter(fn: (r) => r._measurement == "syslog")
  |> range(start: -3d)
  |> group(by: ["facility"])
  //|> distinct(column: "facility")
  |> keyValues(keyColumns: ["facility"])
```

got

```
expected integer cursor type, got *reads.stringMultiShardArrayCursor
```

The query with `distinct` works. Ideas?

**Comment by aanthony1243** [comment]
because you are not filtering by a `_field`, you will group different fields together into the same table by "facility".  A column must have a single type in the same table.  

This is another 'usability' issue.

**Comment by affo** [comment]
O ok, another error message that should be improved

**Comment by nathanielc** [comment]
This should be solved with #1411

**Comment by russorat** [comment]
closing in favor of https://github.com/influxdata/flux/issues/1411

**Comment by doivosevic** [comment]
The error message is still there and very confusing when trying to do a simple thing such as grouping in grafana. Could the error message be improved?
