### ISSUE TITLE
Optimize Regex that can be converted to equality

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#3218]
If a filter includes a regex that is of the form  `x =~ /^LITERAL$/` we should be able to change that to an equality expression `x == "LITERAL"`.

We want this optimization to be applied before passing the filter predicates down to storage implementations so that they do not also have to implement this optimization.

The influxql repos contains code for rewriting regexs to AST. This equality component of this code can be ported to flux and used to get an initial implementation.

**Comment by philjb** [comment]
Influxql implements a number of regex translation optimization. https://github.com/influxdata/influxql/blob/master/ast_test.go#L600

**Comment by nathanielc** [comment]
Commit adding limits to the InfluxQL implementation https://github.com/influxdata/influxql/commit/3af2fe034bb7208fba2544d62c5afe270893748b
