### ISSUE TITLE
Optimize Regex that can be converted to string searches

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#3219]
If a filter includes a regex that is of the form x =~ /^LITERAL/ we should be able to change that to an achored string search. Currently we do not have any implementation of a prefix check, but in theory a prefix check would be much faster than a regex evaluation. Other string search algorithms my be useful. For example unanchored regexes can be implemented faster with string search. This depends on the regex implementation, so it needs to be investigated if we can get speedups from using string searches.

**Comment by adrian-thurston** [comment]
Currently there does not exist any operation in storage to satisfy this kind of transformation.
