### ISSUE TITLE
Flux AST String Escaping

### ISSUE THREAD

**Issue by brettbuddin** [influxdata/flux#3221]
## Our Problem

We just uncovered over a bug in our Notification Rule Flux generation where we aren't properly escaping a string when composing a Flux script via AST. Here's an excerpt from that code generation:

```
flux.Property("text", flux.String(s.MessageTemplate))
```

Above you'll see the `s.MessageTemplate` is being applied directly to the script. By the default, the template text looks like this:

```
Notification Rule: ${ r._notification_rule_name } triggered by check: ${ r._check_name }: ${ r._message }
```

Now, if a user changes this message template and uses double quotes:

```
${ r._notification_rule_name } triggered by "${ r._check_name }" ${ r._message }
```

The generated Flux will now have a syntax error, because we haven't escaped `flux.String(s.MessageTemplate)` in our AST code.

##  Potential Solutions

I considered solving it with a naive string replacement:
```
strings.ReplaceAll(s.MessageTemplate, `"`, `\"`)
```

However, I can't decide if this is a fragile solution or not. String escaping is usually context-sensitive operation so it might be better to provide an API in `flux` that accounts for the idiosyncrasies of the Flux language (and/or safety) when escaping strings. Maybe something like:

```
flux.EscapeString(v string) string
```

Thoughts? Am I being too paranoid?

**Comment by brettbuddin** [comment]
This might be more complicated than I originally thought. It looks like if I compose a message template that contains double quotes *and* a variable substitution it isn't happy.


This works:
```
${ r._notification_rule_name }
```

This works:
```
He said, "I'm quoted."
```

This works:
```
He said, I'm quoted. ${ r._notification_rule_name }
```

This doesn't work:
```
He said, "I'm quoted." ${ r._notification_rule_name }
```

Looking into it further...

**Comment by brettbuddin** [comment]
It's worth posting the error we see on the client side when one of these erroneous cases gets saved:

```
{
    "code": "invalid",
    "message": "invalid options; Err: loc 0:0-0:0: unknown operator \"<INVALID_OP>\": loc 0:0-0:0: unknown operator \"<INVALID_OP>\""
}
```

**Comment by nathanielc** [comment]
:thinking: Here is the SPEC on escaping strings in Flux, https://github.com/influxdata/flux/blob/master/docs/SPEC.md#string-literals There is a limited set of escape sequences.

Can you link to the code behind this snippet?

```
flux.Property("text", flux.String(s.MessageTemplate))
```

I am not sure what `flux.String` is doing. 

The AST has both a StirngLiteral node and a StringExpression node. The literal node will treat its value as a literal and so any `${var}` bits will NOT be evaluated. The StringExpression has a list of StringExpressionParts that are either literals or expressions (i.e. the ${} bits). 

If `flux.String` is supposed to understand and support `${}` in the input string that implies that it is parsing the string and constructing StringExpressions as needed.

So this may be more complex than it first appears.

**Comment by brettbuddin** [comment]
Thanks for the considered response, @nathanielc. I'll dig in more tomorrow and let you know what I discover.

**Comment by brettbuddin** [comment]
Found the problem. I'll file another issue to detail it.
