### ISSUE TITLE
Escaping of StringExpression parts

### ISSUE THREAD

**Issue by brettbuddin** [influxdata/flux#3223]
After digging deeper into the strangeness I am seeing in Notification Rule Flux generation, I found an issue in how `StringExpression` is formatted back to Flux from AST.

Consider the following test case:

```go
runtime.FinalizeBuiltIns()

source := `
a = 1
hello = "hello \"world\": ${ a }"`

parser := fluxlang.DefaultService
pkg, err := parser.Parse(source)
if err != nil {
    panic(err)
}
fmt.Println(ast.Format(pkg))
```

Above I'm double quoting a word in the string and have it escaped properly. I would expect the program to yield the value of `source`. However, it yields:

```
package main
a = 1
hello = "hello "world": ${a}"
```

Seems to be a problem in how `ast.TextPart` is rendered, and is consistent with what I'm seeing here: https://github.com/influxdata/flux/issues/3221#issuecomment-701002233

For `ast.StringLiteral` we perform escaping while formatting it:

https://github.com/influxdata/flux/blob/7d461e73fc93f2531f9c934da6358ac885a883f4/ast/format.go#L615-L618

We don't do that for `ast.TextPart`:

https://github.com/influxdata/flux/blob/7d461e73fc93f2531f9c934da6358ac885a883f4/ast/format.go#L595-L597

**Comment by jlapacik** [comment]
@brettbuddin what do you expect the output to be? It looks right to me.

**Comment by brettbuddin** [comment]
@jlapacik I expect it to yield:

```
package main
a = 1
hello = "hello \"world\": ${a}"
```
