### ISSUE TITLE
Add Sigma helper function

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/flux#3226]
suggested helper function:
```
import "math"

sigma = (tables=<-, column="_value") => {
  mean = tables |> mean(column)
  stddev = tables |> stddev(column)
  joined = join(tables: {mean: mean, stddev: stddev}, on: ["_stop"])
    |> rename(columns: {_value_mean: "mean", _value_stddev: "stddev"})
    |> keep(columns: ["_start", "_stop", "mean", "stddev"])
  output = join(tables: {tmp: joined, data: tables}, on: ["_stop"])
    |> last()
    |> map(fn: (r) => ({ r with _value: math.abs(x: (r._value - r.mean)) / r.stddev}))
    |> drop(columns: ["mean", "stddev"])
  return output
}    
```

Example of the Sigma function in action:
```
from(bucket: "telegraf")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "mem" and r._field == "used_percent")
  |> aggregateWindow(every: 5m, fn: sigma)
```

**Comment by sanderson** [comment]
@timhallinflux I'm taking another stab at this function. I don't think the suggested solution actually matches the Kapacitor behavior. The sigma function in Kapacitor is used inside of lambda expressions as part of a `where` node. This only works with stream data and keeps a running mean and running standard deviation and uses those to calculate a sigma for each data point.

Flux only batches data and doesn't provide a mechanism for preserving "running" calculations between rows (at least in raw Flux it doesn't). So questions:

- Should `sigma` be a running calculation per input table that updates and outputs each row with a new sigma value based on  the mean and standard deviation of all previous rows in the table?
- Should `sigma` calculate the overall mean and stddev of each input table and use those to calculate the `sigma` for each row?

Sigma doesn't really make sense as an aggregate function (one that returns a single aggregate row/value for each input table). It's simple to calculate the mean and stddev, but as an aggregate function, what `_value` from the input table to you use to calculate the sigma?
