### ISSUE TITLE
Design official JSON encoding of results

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#3249]
CSV has the advantage that it can be streamed to a client and parsed in a streaming fashion, but csv parsers are not as easy to use as a JSON parser on the client side. As such it is beneficial to create a standard JSON response format for the Flux project and implement it as part of the project.

JSON responses will be limited in size where the limit is determined by the implementation. If a query returns more data than the limit the server can refuse to encode the data as JSON and can instead return an error. The limitations of the JSON response format will need to be well documented.

Design questions:

Q: What JSON structure should we use? 
I think a structure as close to the tabular form as possible is best, there are probably good examples out there of how to encode SQL tables as JSON structures, perhaps we can use those for inspiration.
Alternatively we could encode the data as list of objects, that would be inefficient but would also map well to how the data is modeled within Flux itself. 

Q: Should we specify a standard way to encode errors?
A: We did that for CSV but that was because errors could arise mid stream. That will not be possible with JSON and leaving the error response unspecified gives projects the freedom to choose an appropriate encoding for their project.

Q: What should the limit be?
A: Should it be based on bytes of data? Or should it be based on row/cols or values?

**Comment by nathanielc** [comment]
[Microsoft SQL](https://docs.microsoft.com/en-us/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server?view=sql-server-ver15) server will return result in JSON. It looks like they have two ways of doing that, 1. using json path to let the query itself determine the structure 2. using a simple list of objects

**Comment by Pupix** [comment]
Hello,

Are there any news or an ETA on this? Saw your other issue too https://github.com/influxdata/influxdb/issues/20034

I am currently using InfluxDB in an IoT project with a bunch of APIs, and currently I am forced and transform the resulting CSV in JSON. More or less what giraffe is doing here https://github.com/influxdata/giraffe/blob/master/giraffe/src/utils/fromFlux.ts

An upstream solution would be a much appreciated.
Thanks.
