### ISSUE TITLE
Log queries that are abandoned within the controller and ensure they are cleaned up

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#328]
The controller returns a query that must have `Done()` called on it to be properly cleaned up by the controller.

Unfortunately, coding error may cause a query to not have `Done()` called on it. In order to ensure the proper functioning of the server in this error situation, it would be good to add a finalizer to the returned query that would ensure that `Done()` gets called. This finalizer should also log a message to indicate that something is very wrong and needs to be addressed by the developers (us).

**Comment by nathanielc** [comment]
@jsternberg With the changes to the controller is this still relevant? If not please close.

**Comment by jsternberg** [comment]
I believe this is still relevant.
