### ISSUE TITLE
Dispatcher panic when pivoting data for monitoring

### ISSUE THREAD

**Issue by Kungitoo** [influxdata/flux#3283]
I don't have time te delve deeper into these issues but I would at least like to point out they happen. I don't think a syntax or semantic error in flux should result in a panic or throw on the backend
```

import "math"
import "strings"
import "date"
import "influxdata/influxdb/monitor"

my_aggregate = (tables=<-) =>
	tables
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "wqqweqwe")
  |> filter(fn: (r) => r["_field"] == "asdasd")
  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)

my_map = (tables=<-) =>
	tables
  |> map(fn: (r) => ({ r with wd: string(v: date.weekDay(t: r._time) + 4), h: string(v: date.hour(t: r._time)) }))
  |> map(fn: (r) => ({ r with mapped_time: r.wd + " " + r.h }))
  |> map(fn: (r) => ({ r with h: if strings.strlen(v: r.h) == 1 then "0" + r.h else r.h }))
  |> map(fn: (r) => ({ r with wd: if strings.strlen(v: r.wd) == 1 then "0" + r.wd else r.wd }))

my_group = (tables=<-) =>
	tables
  |> group(columns: ["h", "wd"], mode: "by")
  |> mean()
  |> group() 

tab1 = from(bucket: "asd")
  |> my_aggregate()
  |> my_map()
  |> my_group()

as_day = tab1
  |> map(fn: (r) => ({ r with _time: time(v: "2020-10-" + r.wd + "T" + r.h + ":43:50.1004002Z") }))
  |> sort(columns: ["_time"])

//  |> yield()


tab2 = from(bucket: "asd")
  |> my_aggregate()
  |> my_map()

tab3 = tab2
  |> filter(fn: (r) => r["_measurement"] == "qweqwe")
  |> filter(fn: (r) => r["_field"] == "asdasd")
  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)

joined = join(tables: {averages: tab1, actual: tab2}, on: ["h", "wd"], method: "inner")
  |> map(fn: (r) => ({ r with diff: math.abs(x: r._value_averages - r._value_actual) / (r._value_averages + r._value_actual)}))
  |> map(fn: (r) => ({ r with diff_percent: r.diff * 100.0 }))
  |> map(fn: (r) => ({ r with _result: r.diff * 100.0 }))
  |> sort(columns: ["diff"], desc: true)

//  |> yield()

ok2 = (r) => (r.diff < 0.3)
crit2 = (r) => (r.diff > 0.4)

messageFun = (r) =>
	("The task: ${r._time} has a difference from average hourly value of ${r.diff_percent}%")

check2 = {
	_check_id: "0000000000000001",      // 16 characters, alphanumeric
	_check_name: "Failed Tasks Check",  // string
	_type: "custom",                    // can also use "threashold" or "deadman"
	tags: {},
}

joined
  |> pivot(
      rowKey:["_time"],
      columnKey: ["_field"],
      valueColumn: "_value")
  |> monitor.check(
    crit: crit2,
    warn: crit2,
    info: crit2,
    ok:   ok2,
    messageFn: (r) => "ayayay",
    data: check2
    )
  |> columns()


```

2020-10-27T07:29:08.242304Z     info    Dispatcher panic        {"log_id": "0Q4yA2EG000", "service": "storage-reads", "component": "dispatcher", "error": "panic: unknown type invalid"}
goroutine 312557 [running]:
runtime/debug.Stack(0xc0040a30e0, 0x37c1e00, 0x26400e1)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1.1(0xc0040a3140)
        /go/pkg/mod/github.com/influxdata/flux@v0.83.1/execute/dispatcher.go:81 +0x1e5
panic(0x2256260, 0xc0056a1fd0)
        /usr/local/go/src/runtime/panic.go:969 +0x175
github.com/influxdata/flux/execute.PanicUnknownType(...)
        /go/pkg/mod/github.com/influxdata/flux@v0.83.1/execute/table.go:1216
github.com/influxdata/flux/execute.(*ColListTableBuilder).AddCol(0xc002043c20, 0xc001905000, 0x5, 0x0, 0x5d4c000, 0x0, 0x0)
        /go/pkg/mod/github.com/influxdata/flux@v0.83.1/execute/table.go:696 +0xd5c
github.com/influxdata/flux/stdlib/universe.(*pivotTransformation).Process.func1(0x3832900, 0xc002043860, 0xc0000000025635e0, 0xc000f89a80)     
        /go/pkg/mod/github.com/influxdata/flux@v0.83.1/stdlib/universe/pivot.go:312 +0xa52
github.com/influxdata/flux/execute.(*ColListTable).Do(0xc002043860, 0xc001417080, 0xc00186a200, 0x63)
        /go/pkg/mod/github.com/influxdata/flux@v0.83.1/execute/table.go:1410 +0x74
github.com/influxdata/flux/stdlib/universe.(*pivotTransformation).Process(0xc003ecf7a0, 0x945cf10071762b45, 0x44f39a117ad5c86, 0x3816d40, 0xc002043860, 0x7f808d1ce101, 0x0)
        /go/pkg/mod/github.com/influxdata/flux@v0.83.1/stdlib/universe/pivot.go:283 +0xa68
github.com/influxdata/flux/execute.processMessage(0x380f900, 0xc003ca13e0, 0x3818280, 0xc003ecf7a0, 0x37e7200, 0xc0039c2c40, 0xc0040a3020, 0x0, 0x0)
        /go/pkg/mod/github.com/influxdata/flux@v0.83.1/execute/transport.go:239 +0x302
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc001d5b420, 0x380f900, 0xc003ca13e0, 0xa)
        /go/pkg/mod/github.com/influxdata/flux@v0.83.1/execute/transport.go:192 +0xb8
github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc0040a3140, 0x380f900, 0xc003ca13e0)
        /go/pkg/mod/github.com/influxdata/flux@v0.83.1/execute/dispatcher.go:132 +0x65
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1(0xc0040a3140, 0x380f900, 0xc003ca13e0)
        /go/pkg/mod/github.com/influxdata/flux@v0.83.1/execute/dispatcher.go:86 +0x87
created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
        /go/pkg/mod/github.com/influxdata/flux@v0.83.1/execute/dispatcher.go:63 +0x7e

**Comment by nathanielc** [comment]
@Kungitoo Thanks for the report we will take a look.

**Comment by jsternberg** [comment]
We're going to fix the panic to give a meaningful error message after confirming this is the case, but it appears that this error might be because you called `pivot()` with the `valueColumn` as `_value` and that column doesn't exist.
