### ISSUE TITLE
Return more response info from http.post

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#3293]
If a call to `http.post` fails, the only information the user gets back from Flux is the status code, 404, 500, etc.  Often this is not enough to understand the problem. Even if the call to `http.post` is successful, the response may include useful information.

We should provide a way to get more information, such as the headers and the http response body. Perhaps the user could provide a callback function that would let them log the info, etc. This could be a new parameter to `http.post` that defaults to a no-op to avoid making a breaking change.

Also, in cases where the Go http client's call to `Do` does not succeed, we should consider returning the specific error to the user, provided we can do so in a secure way. Currently the error will be marked as internal in all cases.

The Go docs have [this](https://golang.org/pkg/net/http/#Client.Do) to say about when `Do` returns an error:
> An error is returned if caused by client policy (such as CheckRedirect), or failure to speak HTTP (such as a network connectivity problem). A non-2xx status code doesn't cause an error.

**Comment by philomory** [comment]
This would be generally useful not just for errors, but for actual responses as well. The experimental `http.get` can return the response body, but of course (as the name implies) it only works for GET requests.
