### ISSUE TITLE
Plans for custom local packages?

### ISSUE THREAD

**Issue by mkarlesky** [influxdata/flux#3310]
Flux package support seems to be evolving in good directions, and support for adding community contributions has been available for a while now.

What plans exist for local custom packages (i.e. not appropriate for sharing with the community)? Say Flux developers find themselves using the same custom functions in multiple Flux queries. Other than copy & paste, what is the best Flux-native way to prevent code duplication? On the surface, it seems that a mechanism for adding Flux packages locally to an InfluxDB instance is the sensible way to do this.

I'm not seeing anything in the documentation that explains how to create local packages, though the features and components all seem to exist. Alternatively, is there another mechanism that already exists or is planned that will allow Flux queries to reuse custom functions?

I've searched the repo issues and have not found discussion of this. I do see that a community member posted the [same essential question back in June](https://community.influxdata.com/t/flux-custom-functions-and-packages/14980).

**Comment by nathanielc** [comment]
@mkarlesky Thanks for the question. In short nothing exists right now. That said we have some plans in the works. Long terms we intend to build a sort of package registry for Flux, something analogous to Ruby's Gems, Rust's crates and Node's modules. We plan to enable private instances of the registry and to potentially embed one directly into the InfluxDB product. 

More medium term we are looking at a feature like stored procedures from relational databases that will allow you to store Flux snippets as an API resource and reference them when needed. 

Hope this sheds some light on our plans.

**Comment by mkarlesky** [comment]
@nathanielc Thank you for the prompt response and the explanation. Both of those options sound fantastic. I'm glad to know we weren't missing something. In the meantime we'll figure out a good way to manage our duplication needs.

**Comment by MzazM** [comment]
@nathanielc thanks for the update. Both options sound very interesting!

**Comment by organicveggie** [comment]
Could we get a brief status update? Has there been any progress on this in the past year?

**Comment by nward** [comment]
Am very keen for this also - even if it just imports a text file with an "include" type statement.

**Comment by poldown** [comment]
Seems like there's some design work going on recently around supporting [Flux Modules](https://github.com/influxdata/flux/issues/4296), which is exactly what we're all after..

**Comment by nward** [comment]
Classic
