### ISSUE TITLE
Add dictionary type to values package

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#3318]
In order to support the new flux dictionary type, we need to add a dictionary type to the `values` package. This dictionary type should be defined as follows
```Go
type Dictionary interface {
    Get(key Value, def Value) Value
    Insert(key Value, v Value) Dictionary
    Remove(key Value) Dictionary
}
```

The underlying implementation should use Ben Johnson's [sorted map](https://github.com/benbjohnson/immutable#sorted-map).
```Go
type dict struct {
    btree *immutable.SortedMap
}

func (d *dict) Get(key Value, def Value) Value {
    v, ok := d.btree.Get(key)
    if !ok {
        return def
    }
    return v.(Value)
}
func (d *dict) Insert(key Value, v Value) Dictionary {
    return &dict{
        btree: d.btree.Set(key, v),
    }
}
func (d *dict) Remove(key Value) Dictionary {
    return &dict{
        btree: d.btree.Delete(key),
    }
}

type intComparer struct {
}

func (intComparer) Compare(a, b interface{}) int {
    if a.(Value).Int() < b.(Value).Int() {
        return -1
    }
    if a.(Value).Int() > b.(Value).Int() {
        return 1
    }
    return 0
}

func NewDict(ty semantic.Nature) Dictionary {
    switch ty {
    case semantic.Int:
        return &dict{immutable.NewSortedMap(intComparer{})}
    ...
    default:
        panic("invalid type")
    }
}
```

We will need to implement comparison functions for the comparable types `int`, `uint`, `float`, `string`, `duration`, and `time`.

Note the `Dictionary` interface itself does not guarantee that all key values are of the same type, nor does it guarantee that all associated values are of the same type. It is assumed that type inference makes this guarantee and therefore the contract proposed by this interface can be a little lax. The simplicity we gain from only managing a single dictionary implementation outweighs the negligible reduction in overhead we would get with more specialized implementations and interfaces.

Also note that this will also require that we update the `Value` interface to include a new `Dict()` method
```Go
type Value interface {
    ...
    Dict() Dictionary
}
```

and that we add this method to all other `Value` implementations.

DOD:
* Function that instantiates a dictionary from a list of records of the form `{key: ..., value: ...}`
* Unit tests in the `values` package

**Comment by wolffcm** [comment]
Is the plan to use templates to do this, like we do for array cursors in storage, for example?

**Comment by jlapacik** [comment]
Yes I would definitely recommend we use templates for this.

**Comment by wolffcm** [comment]
So will all of `IntDictionary` etc implement the `values.Value` interface, as well as a new `values.Dict` interface?

I guess we'll need to add a corresponding method `Dict()` to `values.Value` as well.

I think I'm a bit unclear on what the new concrete types being added are and how they fit into the existing interfaces in the `values` package.

**Comment by wolffcm** [comment]
Also, do the interfaces described above also need a method for constructing a dict via an array?

**Comment by jlapacik** [comment]
@wolffcm I did not mention it but yes that's correct. We will need to update the `Value` interface with a new `Dict()` method
```Go
type Value interface {
    ...
    Dict() Dictionary
}
```

And the concrete types (such as `intDictionary`) will implement both the `Value` and the `Dictionary` interfaces.

> Also, do the interfaces described above also need a method for constructing a dict via an array?

This isn't required but highly recommended in order to simplify the implementations of the builtin functions defined in the `dict` package. Perhaps we should make it a requirement and add it to the DOD.

**Comment by jsternberg** [comment]
@jlapacik I don't believe that durations can be compared. Should that be excluded from the list of valid types for a dictionary key? If it being strictly sorted isn't important, I can do something like:

```
if a.months < b.months {
    return -1
} else if a.months > b.months {
    return 1
} else {
    if a.nsecs < b.nsecs {
        return -1
    } else if a.nsecs > b.nsecs {
        return 1
    }
}
return 0
```

But I wouldn't call this sorted.

**Comment by jlapacik** [comment]
@jsternberg the reason I added durations to the list is that they fall under the `Comparable` constraint. Can you not do

    1d < 5d

in flux?

**Comment by jsternberg** [comment]
@jlapacik it doesn't seem to presently be supported:

```
> 1d < 5d
Error: unsupported binary expression duration < duration
```

**Comment by jlapacik** [comment]
Ah ok, so durations are not comparable. We can remove them from this list then.

**Comment by jsternberg** [comment]
Do we have something about the dictionary that requires it to be sorted? I can imagine it would be helpful to be able to do:

```
period = [
    1d: 1h,
    7d: 1d,
]
```

We can still support durations in a dictionary, but they won't necessarily be sorted if we have any behavior that depends on it being sorted.

**Comment by jlapacik** [comment]
The underlying implementation is a sorted map that requires a compare function.
