### ISSUE TITLE
Add dict package to stdlib

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#3319]
The dict package should be defined as follows
```
package dict

builtin fromList : (pairs: [{ key: K, value: V }]) => [K: V] where K: Comparable
builtin get : (key: K, from: [K: V], default: V) => V where K: Comparable
builtin insert : (key: K, value: V, dict: [K: V]) => [K: V] where K: Comparable
builtin remove : (key: K, dict: [K: V]) => [K: V] where K: Comparable
```

The implementations should use the dictionary values defined in https://github.com/influxdata/flux/issues/3318. For example, `fromList` should be defined as follows
```Go
func (ctx context.Context, args values.Object) (values.Value, error) {
    pairs, err := args.GetRequiredArray("pairs")
    if err != nil {
        return nil, err
    }

    record, err := pairs.Type().ElemType()
    if err != nil {
        return nil, err
    }

    var keyType semantic.Nature

    for i := 0; i < 2; i++ {
        prop, err := record.RecordProperty(i)
        if err != nil {
            return nil, err
        }
        if prop.Name() != "key" {
            continue
        }
        ty, err := prop.TypeOf()
        if err != nil {
            return nil, err
        }
        keyType = ty.Nature()
    }

    return values.DictFromList(keyType, pairs), nil
}
```

DOD:
* Unit tests in the new `dict` package for the builtin implementations `fromList`, `get`, `insert`, `remove`
* Flux acceptance tests in the dict package showing usage of the dict type

**Comment by wolffcm** [comment]
It seems like we could include some Flux acceptance tests here in the DOD? Or is that a separate issue?

**Comment by wolffcm** [comment]
Is it the intent of this issue that once it's complete, we have a fully function dict type that is only missing the handy syntactic sugar for the literals?

**Comment by jlapacik** [comment]
@wolffcm yes that is the intent. I've updated the DOD to include flux acceptance tests.

**Comment by jlapacik** [comment]
This depends on https://github.com/influxdata/flux/issues/3318 and https://github.com/influxdata/flux/issues/3320

**Comment by jsternberg** [comment]
I'm going to start building on #3341 to do this, but it will require #3320 for me to formally finish this. But I can do most of it with just the contents of #3341.

**Comment by jsternberg** [comment]
I have this mostly done now. The main thing left is writing end to end tests, but it's not really possible to do that until the Rust components from #3320 are done. I'll push up a draft PR in the interim.
