### ISSUE TITLE
[Design] API for extending tests for specific environments

### ISSUE THREAD

**Issue by rockstar** [influxdata/flux#3335]
Once the work for executing flux acceptance tests in downstream consumers is complete in #3334, downstream consumers need an api to extend those tests and make extra assertions e.g. query plans, pushdowns, etc. That _could_ look like the following:

```
package my_test

import "testing"
import "influxdata/flux/my_test"

testcase keep_your_foot_off_the_blasted_samoflange_influxdb extends my_test.keep_your_foot_off_the_blasted_samoflange {
    testing.assertExpectedPlannerRules(want: ["PushdownWindowMean"])
}
```

The work required here is that `testcase $testname extends $othertest` takes the AST of the originating test case to make a new test with the extra logic in it.

DOD:
  - Issues for implementing the design have been created
  - ~ a test case can be extended by a downstream consumer with added logic~
  - ~ Each downstream consumer's test runner has the logic to calculate these extended tests~

**Comment by rockstar** [comment]
From planning discussion, there will be cases where we want to finely control the setup phase as well as the assertion phase additions, so we might need some sort of api like:

```
package my_test

import "testing"
import "influxdata/flux/my_test"

testcase keep_your_foot_off_the_blasted_samoflange_influxdb extends my_test.keep_your_foot_off_the_blasted_samoflange {
    testing.setFeatureFlag('my-feature-flag', true)
    my_test.keep_your_foot_off_the_blasted_samoflange()
    testing.assertExpectedPlannerRules(want: ["PushdownWindowMean"])
}
```

**Comment by nathanielc** [comment]
@rockstar Two questions:

1. How will the common statements for test cases work when extending a test case? For example say a test changes the `now` time via the option statement outside the testcase block. How do we ensure that gets carried over to the extending test case?


2. How will the imports work? Do the test packages need to become part of the stdlib or will the imports resolved against the filesystem somehow? If its the latter I think we need a separate issue to design and implement imports from files as its not a trivial solution. Specifically the Rust code can't call back into Go and it can't directly access the filesystem so we would not be able to lazily evaluate imports found in code rather have an explicit import dependency resolution step.

**Comment by jsternberg** [comment]
We think that the following syntax will be able to be a concise way to represent extending and using another test while also not expanding on the language. Most of the mechanisms for how to do this already exists and the syntax is very understandable.

```
testcase special_string_trim {
    import "strings/strings_test"
    strings_test.string_trim()
}
```

This would translate on the AST level so that the imports became:

```
package main

strings_test = {
    "string_trim": (ast for string trim),
    "other_variable": (ast for others),
}
strings_test.string_trim()
```

**Comment by rockstar** [comment]
Closing for #3447
