### ISSUE TITLE
Monomorphization

### ISSUE THREAD

**Issue by jpacik** [influxdata/flux#3337]
This issue is about implementing monomorphization for generic types. Monomorphization is the process of instantiating different versions of generic functions/expressions - one for each concrete type that is referenced. For example, given the following program
```
f = (x) => x + 1 // (x: T) => T where T: Addable + NumericDefaultInt
a = f(x: int(v: 1))
b = f(x: 1.1)
```

Because integer literals are (or soon to be) polymorphic, interpreted as either integers or floats, monomorphization would instantiate two versions of `f`, replacing all references with their respective concrete instantiations.
```
f_int = (x) => x + int(v: 1) // (x: int) => int
f_flt = (x) => x + 1.0 // (x: float) => float
a = f_int(x: int(v: 1))
b = f_flt(x: 1.1)
```

### Scope

This issue is very specific to integer literals since they are the first and only expression (other than function types) that are polymorphic.

### Why

Without monomorphization the interpreter as well as the rest of the runtime would need to know how to evaluate polymorphic values derived from the use of integer literals that can be used in different contexts (integer vs float). We have many builtin functions that inspect their inputs types directly - `array.from`, `map`, `filter`, etc. Updating all of these implementations to understand polymorphic values and data types would be quite ad hoc and very error prone. With monomorphization we have a method that is implemented in one place (directly after type inference) and is generalizable for all polymorphic types without any changes needed to the runtime.

### How

We only care about generic types that have the `NumericDefaultInt` constraint.
```
f = (x) => x + 1 // (x: T) => T where T: Addable + NumericDefaultInt
```

Because there are only two concrete types (integer and float) that are `NumericDefaultInt`, it is sufficient at this point to always instantiate an integer version and a float version for every generic expression with this constraint, regardless of whether both are needed (as a final semantic pass we can remove all unused variable declarations).

A basic algorithm is as follows
```
algorithm for creating an integer expression from a generic expression:
  1. If expression is a polymorphic literal whose type is a type variable, return an integer literal
  2. If expression is a polymorphic literal whose type is float, return a float literal
  3. If expression is an identifier whose type is a type variable, return integer version
  4. If expression is a function, recursively monomorphize variables assignments in body as needed
  5. Otherwise recurse into subexpressions
```

### Implications

By monomorphizing generic functions/expressions that are `NumericDefaultInt`, no changes have to made to the interpreter or builtin implementations. We don't have to update the interpreter to be able to evaluate binary expressions with mixed types. Binary operators will only will only ever take operands of the same type. From the interpreter's perspective, all types are concrete. It doesn't have to evaluate "typeless" generic values.

Also if an expression is inferred to be of type float, all numeric subexpressions will be evaluated as float types as well. This means
```
(2 / 5) * 5.0
```

is equivalent to
```
(2.0 / 5.0) * 5.0 // = 2.0 != 0.0
```

Without monomorphization, runtime polymorphism means that we would evaluate `2 / 5` as integer division in the expression `(2 / 5) * 5.0` resulting in `0.0`.

### Examples

1.
After monomorphization
```
array.from(rows: [{a: 1}, {a: 2.0}])
```

becomes
```
array.from(rows: [{a: 1.0}, {a: 2.0}])
```

2.
After monomorphization
```
f = (x) => {
  a = 1
  return x + a
}
a = f(x: int(v: 1))
b = f(x: 1.0)
```

becomes
```
f_int = (x) => {
  a_int = int(v: 1)
  return x + a_int
}
f_flt = (x) => {
  a_flt = 1.0
  return x + a_flt
}
a = f_int(x: int(v: 1))
b = f_flt(x: 1.0)
```

This example assumes we've removed unused variables after monomorphization.

3.
After monomorphization
```
a = 1 / 2
f = (x) => a * x
x = f(x: int(v: 1))
y = f(x: 1.0)
```

becomes
```
a_int = int(v: 1) / int(v: 2) // = 0
a_flt = 1.0 / 2.0 // = 0.5
f_int = (x) => a_int * x
f_flt = (x) => a_flt * x
x = f_int(x: int(v: 1)) // 0
y = f_flt(x: 1.0) // 0.5
```

### DOD

There needs to be interpreter tests showing evaluation of binary expressions with operands of different types. There should also be a flux acceptance test that shows `array.from` being called with a heterogeneous array.

**Comment by wolffcm** [comment]
Are there any case where we could have an exponential explosion in the number of new functions generated?
```
f = (a, b) => ({a: a + 1, b: b + 1})
```
You would need to create `f_flt_flt`, `f_int_flt`, `f_flt_int` and `f_int_int`, yes? Or do you only create monomorphic functions where there is a call that requires it?

**Comment by jlapacik** [comment]
@wolffcm in what I've described above yes there would be 4 different instantiations generated for `f` even if we didn't need all of them. My hope was to keep the initial algorithm simple but that might not be feasible. We might need to compute the exact instantiations that are needed beforehand.
