### ISSUE TITLE
convert cumulative histograms to regular histograms

### ISSUE THREAD

**Issue by ykuksenko** [influxdata/flux#3351]
Could a function to convert cumulative histograms to regular histograms be provided?

With this function:
- data ingested from a prometheus endpoint in telegraf could easily be converted to be viewed in grafana.
- the existing [histogram()](https://docs.influxdata.com/influxdb/cloud/query-data/flux/histograms/) function could also be used in grafana
- telegrafs [histogram aggregator](https://docs.influxdata.com/telegraf/v1.16/plugins/#histogram) could also be used

**Comment by wnasich** [comment]
A regular histogram can be reached by adding a `|> difference()`  after the `histogram()`

**Comment by ykuksenko** [comment]
`|> difference()` operates over time instead of over the `le` label

What `|> difference()` does:
```
t1 = timestamp1, t2 = timestamp2 etc.
           (CUMULATIVE)        (|> difference())
           t1  t2  t3    =>    t1    t2   t3
le=10      10  10  0     =>    null  0    -10
le=20      20  10  30    =>    null  -10  20
le=+Inf    30  10  35    =>    null  -20  25
```

What I want to happen:
```
t1 = timestamp1, t2 = timestamp2 etc.
           (CUMULATIVE)        (ORDINARY)
           t1  t2  t3          t1  t2  t3
le=10      10  10  0     =>    10  10  0
le=20      20  10  30    =>    10  0   30
le=+Inf    30  10  35    =>    10  0   5
```
Steps to produce what I am seeking: (The code describes this better but here is a summary)
1. Take one vertical row (by time stamp)
2. Sort the data by a labels value. By default it should be the `le` label.
3. Print the first value as is (`le=10`@`t1` => `10`)
4. Calculate the next value (`le=20`@`t1` - `le=10`@`t1` => `10`)
5. Repeat step 4 until +Inf (`le=+Inf`@`t1` - `le=20`@`t1` => `10`)
6. Repeat all above steps for all following time stamps

The examples above come from [here](https://github.com/grafana/grafana/blob/9155f46315e1a61e5ec62f912cd21e8b808c9284/public/app/plugins/datasource/prometheus/result_transformer.ts#L280). I slightly modified them to show the `+Inf` label which is handled in the linked example code.

**Comment by quentinmit** [comment]
You can group by `_time` and then use `difference()` but that seems to significantly slow down the query. You also need to insert an extra zero row at the start for `difference()` to consume.
