### ISSUE TITLE
Should be able to use selector functions with the aggregateWindow function

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#336]
Selectors are different from aggregators and as such the aggregateWindow function does not allow selectors functions to be passed in.

Maybe we should update the function signatures to make it possible to do so.

This way a user can easily switch from `aggregateWindow(fn:mean)` to `aggregateWindow(fn:max)`.

**Comment by wetterfrosch** [comment]
Yep, just found this issue while travelling around to find a way to get the maximum value of a single day. Is there so far some workaround for this possible?

**Comment by wetterfrosch** [comment]
> Is there so far some workaround for this possible?

Sorry for the buzz, but obviously
```
  |> window(every: 1d)
  |> max()
```
and probably adding
```
  |> aggregateWindow(every: 1d, fn: mean)
```
for "per day"-DateTime stamps seems to get what wanted.

**Comment by andig** [comment]
Has there been any progress in allowing selectors in `aggregateWindow`? Seems this issue is still open?

**Comment by affo** [comment]
@andig the issue is closed.

Aggregate now accept `column` instead of `columns` so that, to the eyes of `aggregateWindow`, they are the same.

In general, any function that accepts a `column` parameter is accepted by `aggregateWindow`

**Comment by andig** [comment]
> Aggregate transformations now accept column instead of columns so that, to the eyes of aggregateWindow, they are the same as selectors.
> In general, any function that accepts a column parameter is accepted by aggregateWindow.

Ahhh, I see (and need to test). It would be nice then to mention then that also selectors are acceptable in the docs- sofar only the agrgegates are mentioned.

**Comment by affo** [comment]
Do you mean in the SPEC or in the v2 docs?

Anyways, you are right. Maybe, we should simply `aggregateWindow -> windowApply`. So that it doesn't sound aggregate-only.

**Comment by andig** [comment]
I've meant here specifically: https://docs.influxdata.com/flux/v0.24/functions/built-in/transformations/aggregates/aggregatewindow/

> The aggregateWindow() function applies an aggregate function to fixed windows of time.

It could be an aggregate or selector (or other?) function. The `aggregateWindow` name seems fine for me.

**Comment by affo** [comment]
Ok 👍 

I know we are developing a v2 for docs. I don't know which one should be updates. I will contact somebody from the docs and see what we need to do.

For the name, I don't know, it seems to me that `aggregateWindow` aggregates and doesn't select. We were precise in distinguishing the different types of transformations in our SPEC. We should be precise also for that function.

Anyways, thank you for your feedback!

**Comment by affo** [comment]
Issue created: https://github.com/influxdata/flux/issues/1629

**Comment by andig** [comment]
@affo I have just tried this on InfluxDB 1.7.7 which should be recent enough as 1.7.6 upgraded to flux 0.24 and PRs were merged in April:

````
from(bucket: "volkszaehler")
  |> range(start: dashboardTime, stop: upperDashboardTime)
  |> filter(fn: (r) => r.title == "HcStarts")
  |> aggregateWindow(every: 1d, fn: max)
  |> derivative(unit: 1d, nonNegative: true, columns: ["_value"])
````

Gives:

    Error: failed to compile query: type error 8:6-8:41: missing required parameter "columns"

**Comment by affo** [comment]
@andig 
Exactly, next version of InfluxDB will include the changes.

If you download 2.0, then you won't have that problem.

We have already updated Flux in 1.x to v0.36 (I think 🤔 ). Once the next version of OSS 1.x will be released, everything will work correctly.

**Comment by affo** [comment]
For now, your workaround can be to paste the content of aggregate window  and change the parameters at your will. Here's its definition:

```
aggregateWindow = (every, fn, column="_value", timeSrc="_stop",timeDst="_time", createEmpty=true, tables=<-) =>
    tables
        |> window(every:every, createEmpty: createEmpty)
        |> fn(column:column)
        |> duplicate(column:timeSrc,as:timeDst)
        |> window(every:inf, timeColumn:timeDst)
```
