### ISSUE TITLE
Error on using tableFind on HTTP API 1.8.3 - do not have an execution context for tableFind

### ISSUE THREAD

**Issue by sbengo** [influxdata/flux#3363]
Hi,

First of all, sorry if its not the place to open the issue, but I'm totally lost.

My goal is merge SQL results and map the value according to different thresholds to finally set up a dynamic value. I'm trying to use, inside a map, a function that calls `tableFind()` function to retrieve desired record in order to create this dynamic value.

On compiled and working flux, the script is working perfectly, but tried against InfluxDB 1.8.3 (directly from cli or url) and the following message appears:

```
Error: error calling function "getColumn": error calling function "tableFind": do not have an execution context for tableFind, if using the repl, try executing this code on the server using the InfluxDB API
```

So:
- Why I can't use tableFind when I use the HTTP API 
- Is there some limitations of flux 0.65.1 (actual version on 1.8.3)?
- Is there any workarount in order to use the `tableFind()` function?

Thanks,
Regards!

A dummy flux to repro it with results:

Test | Result | Message
--- | --- | ---
REPL | OK | ---
Influx CLI | KO |  `error "failed to evaluate map function: error calling function ""getRecord"": error calling function ""tableFind"": do not have an execution context for tableFind, if using the repl, try executing this code on the server using the InfluxDB API" "`

```
import "csv"

sampleData = csv.from(csv: "
#datatype,string,long,dateTime:RFC3339,string,string,double
#group,false,true,false,true,true,false
#default,,,,,,
,result,table,_time,location,_field,_value
,,0,2019-11-01T12:00:00Z,sfo,temp,65.1
,,0,2019-11-01T13:00:00Z,sfo,temp,66.2
,,0,2019-11-01T14:00:00Z,sfo,temp,66.3
,,0,2019-11-01T15:00:00Z,sfo,temp,66.8
,,1,2019-11-01T12:00:00Z,kjfk,temp,69.4
,,1,2019-11-01T13:00:00Z,kjfk,temp,69.9
,,1,2019-11-01T14:00:00Z,kjfk,temp,71.0
,,1,2019-11-01T15:00:00Z,kjfk,temp,71.2
,,2,2019-11-01T12:00:00Z,kord,temp,46.4
,,2,2019-11-01T13:00:00Z,kord,temp,46.3
,,2,2019-11-01T14:00:00Z,kord,temp,42.7
,,2,2019-11-01T15:00:00Z,kord,temp,38.9
")

getCustomRecord = (x) => {
    ll = sampleData
        |> tableFind(fn: (key) => key.location == "sfo")
        |> getRecord(idx: 0)
    return ll.location
    }

sampleData
  |> map(fn: (r) => ({
    test_value: r._value,
    mylocation: string(v: getCustomRecord(x: "empty"))
    }))
 |> yield()
```

**Comment by sbengo** [comment]
Hi guys,

Any clue why I can't use the tableFind on InfluxBD?

Thanks,
Regards!

**Comment by sanderson** [comment]
@sbengo In the version of Flux packaged with InfluxDB 1.8.3, you can't execute another query inside of a `map()` call. This has is been fixed in a newer version of Flux, but won't be available until Flux in the InfluxDB 1.x line is updated. This query would work in InfluxDB 2.0 or Cloud, with the one caveat that you may need to cast `ll.location` to a string in your `getCustomRecord` definition.

```js
// ...
  return string(v: ll.location)
```

**Comment by sbengo** [comment]
Thanks @sanderson !!

We keep working with 1.8.3 and we have no plant to migrate to 2.0 on short plan, maybe this can be considered to upgrade Flux on 1.8.4 - asked on https://github.com/influxdata/influxdb/issues/20175

Thanks,
Regards!
