### ISSUE TITLE
hourSelection does not allow for selecting overnight time ranges

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#3372]
If a person wants to use `hourSelection` to select data from a nighttime range, such as 10 pm to 6 am, this isn't presently possible.

Reasonably, a user would expect to be able to do `hourSelection(start: 22, stop: 6)` and to have the function realize that the night hours are desired or at least an error indicating that this range isn't allowed. Instead, the function is naively implemented as `hour >= start && hour < stop`.

See this [community topic](https://community.influxdata.com/t/hourselection-not-working-in-grafana/16477) about this issue.

**Comment by ASaiAnudeep** [comment]
Any updates on this!
