### ISSUE TITLE
test rust scanner against queries collected from query log

### ISSUE THREAD

**Issue by adrian-thurston** [influxdata/flux#3381]
Write a standalone program that invokes the parser twice, once using the existing C based scanner, and again using the new rust-based scanner, and then compares the parse trees for equality. Run this against the current archive of queries collected from the query log to look for discrepancies. The archive is not currently accessible by the team, for the time being, get it from Adrian.

Doing this requires adding an option to the parser for selecting which scanner to use. Such an option would also be used by a feature flagging framework for incrementally enabling the scanner.

**Comment by nathanielc** [comment]
Notes:

* Use Rust's assert_eq! macro to compare the produced ASTs
* Compare AST from old scanner with new scanner
* Add new unit test to parser if a discrepancy is found
* Commit program source to archiver repo (understanding its run once code)
