### ISSUE TITLE
Constrained types

### ISSUE THREAD

**Issue by jpacik** [influxdata/flux#3389]
This is a proposal to represent constrained types using records. Specifically

1. Each primitive type should be modeled as a record where each label corresponds to a valid builtin operator for that type
2. Builtin operators should constrain each operand to be a record with the corresponding label

Let's take booleans for example. The only builtin operators that are well defined for booleans are `==` and `!=`. So we would model the boolean type as
```
{==: Bool, !=: Bool}
```

And given `a == b`, we would generate the following type constraints
```
typeof(a) = {==: t0 | t1}
typeof(b) = {==: t0 | t1}
```

As a result we can see exactly which operators are valid for a particular expression just by looking at the monotype for that expression. This is exactly what is required for https://github.com/influxdata/flux/issues/3347. No changes are required to the Hindley-Milner type inference algorithm. And we can remove type constraints from polytypes and revert to the original Hindley-Milner definition
```Rust
struct PolyType(Vec<Tvar>, MonoType)
```

Note that because these will be internal types, and the labels are not valid flux record labels, we can model these primitive types using the current record type. We don't need to add a new type to the type system, and we don't have to define new unification rules.

**Comment by jlapacik** [comment]
The `convert_polytype` method will take a polytype like (not true Rust code)
```
PolyType {
    vars: [t0, t1]
    cons: {t0: [Addable, Subtractable], t1: [Addable, Divisible]},
    expr: (x: t0) => t1,
}
```
and transform it into
```
PolyType {
    vars: [v0, v1, v2, v3]
    expr: (x: {+: v0 | -: v0 | v1}) => {+: v2 | /: v2 | v3},
}
```

Note that `{+: v0 | -: v0 | v1}` represents a type that is both `Addable` and `Subtractable`. Similary `{+: v0 | /: v0 | v1}` represents a type that is both `Addable` and `Divisible`.

**Comment by jlapacik** [comment]
The following polytype
```
(a: T, b: T) => T where T: Addable
```

is equivalent to the following Rust struct
```Rust
PolyType {
    vars: vec![Tvar(0)],
    cons: map! {Tvar(0) => Kind::Addable},
    expr: MonoType::Fun(Box::new(Function {
        req: map! {"a" => MonoType::Var(Tvar(0)), "b" => MonoType::Var(Tvar(0))},
        retn: MonoType::Var(Tvar(0)),
    },
}
```

After converting the polytype to the new form, it will look like
```Rust
PolyType {
    vars: vec![Tvar(0), Tvar(1)],
    expr: MonoType::Fun(Box::new(Function {
        req: map! {
            "a" => MonoType::Record(Box::new(Record::Extension {
                head: Property { k: "+", v: MonoType::Var(Tvar(0)) },
                tail: MonoType::Var(Tvar(1)),
            })),
            "b" => MonoType::Record(Box::new(Record::Extension {
                head: Property { k: "+", v: MonoType::Var(Tvar(0)) },
                tail: MonoType::Var(Tvar(1)),
            })),
        },
        retn: MonoType::Record(Box::new(Record::Extension {
            head: Property { k: "+", v: MonoType::Var(Tvar(0)) },
            tail: MonoType::Var(Tvar(1)),
        })),
    },
}
```
