### ISSUE TITLE
influxdb 2.0.2 osx build issue

### ISSUE THREAD

**Issue by chenrui333** [influxdata/flux#3396]
👋  I am trying to build influxdb 2.0.2 and rollout the change for homebrew (https://github.com/Homebrew/homebrew-core/pull/66837), but running into some issue as below in my local and need some help/guidance on the build process.

```
==> go build -o /usr/local/Cellar/influxdb/2.0.2/bin/flux ./cmd/flux
go: downloading github.com/mattn/go-sqlite3 v1.11.0
go: downloading github.com/benbjohnson/immutable v0.2.1
go: downloading github.com/spf13/cobra v0.0.3
go: downloading github.com/c-bata/go-prompt v0.2.2
go: downloading github.com/opentracing/opentracing-go v1.0.2
go: downloading go.uber.org/zap v1.14.0
go: downloading github.com/google/go-cmp v0.4.0
go: downloading github.com/prometheus/client_model v0.0.0-20190812154241-14fe0d1b01d4
go: downloading github.com/lib/pq v1.0.0
go: downloading github.com/prometheus/common v0.6.0
go: downloading github.com/mattn/go-runewidth v0.0.3
go: downloading github.com/pkg/term v0.0.0-20180730021639-bffc007b7fd5
# pkg-config --cflags  -- flux
Package flux was not found in the pkg-config search path.
Perhaps you should add the directory containing `flux.pc'
to the PKG_CONFIG_PATH environment variable
No package 'flux' found
pkg-config: exit status 1
```

Let me know if you need more info on this.

**Comment by danxmoran** [comment]
@chenrui333 you'll need to install our custom `pkg-config` wrapper in addition to the version available from Homebrew, see the 1st block in the Getting Started section [here](https://github.com/influxdata/flux#getting-started).

**Comment by chenrui333** [comment]
yeah, I did build pkg-config and add flux as well in [this commit](https://github.com/Homebrew/homebrew-core/pull/66837/commits/bc0a5c14cdf052849cd7a4b32237bbeceb9bf08c), but still not quite working.

**Comment by danxmoran** [comment]
I have some thoughts, but I'll just comment on your PR 😄
