### ISSUE TITLE
allow difference to assume zero start

### ISSUE THREAD

**Issue by rogpeppe** [influxdata/flux#3400]
When `difference` is used, the first value is always dropped (either by setting it to null or by dropping the row that it's in).

When using `difference` for calculating total counts as reported by prometheus, the first value is actually significant - it's the total count up until that stage.

How about adding another parameter to `difference`, say `firstZero: bool`? When `firstZero` is true, the current value would start as zero - the first row would always be included and have an unchanged value (`keepFirst` would be ignored), and other values would take the difference from then.
When used in conjunction with `nonNegative: true`, a negative difference would likewise assume a zero start.

Examples:
`difference(firstZero: true)` of `[5, 7, 6, 10]` would produce: `[5, 2, -1, 4]`.

`difference(firstZero: true, nonNegative: true)` of `[5, 7, 6, 10]` would produce: `[5, 2, 6, 4]`.

**Comment by jlapacik** [comment]
I like this proposal, but it seems that `firstZero` should replace `keepFirst` entirely. From my perspective this was the intended behavior of `keepFirst` all along. Perhaps @nathanielc can weigh in here.

**Comment by nathanielc** [comment]
I don't recall the exact reasoning behind `keepFirst` it was introduced in this PR https://github.com/influxdata/flux/pull/1603 maybe we can gain context from there.

**Comment by rogpeppe** [comment]
Aside from backward compatibility considerations, I can still see a use for `keepFirst` - sometimes one might wish to keep some columns around regardless of the status of the resulting difference column.

**Comment by jlapacik** [comment]
My concern is mainly that we'll have two parameters `keepFirst` and `firstZero` that look very similar and so it might be confusing. Also they seem to be mutually exclusive which also isn't very user friendly. It appears that `keepFirst` was added so that `tripleExponentialDerivative` could be expressed in pure flux, but apparently it never was. So it might make more sense to just update the behavior of `keepFirst` since updating the first value from null to non-null likely isn't going to break any queries.

**Comment by rogpeppe** [comment]
> So it might make more sense to just update the behavior of keepFirst since updating the first value from null to non-null likely isn't going to break any queries.

AFAICS that could easily break queries because it would change the numbers in the results - the first value would now appear in the results where before it wouldn't, so the results of a `sum` on the result could be wildly different.

I've been thinking a bit more about my proposal for `firstZero` here and although the proposed semantics fit my current use case well, I'm not sure that they're a good idea in general.

ISTM that the canonical use case for this operation is to use in conjunction with `nonNegative` to process sampled incrementing counters that can reset.

Let's think a bit more about sampled incrementing counters. There are two main operations that I could see being useful: we might want to observe the rate of change or we might want to obtain the total count.

For observing the rate of change, the current `nonNegative` parameter will work fine. It wouldn't make sense to use `firstZero` in that context, as then the first value in the stream has a different unit from the others (the first value is absolute, the others are relative).

AFAICS if we want to obtain the total count, we are _always_ going to feed the results into the `sum` operator. But if we're always going to do that, why not add a new aggregation operator that does what we need? `sumMaxMonotonic` is a possible, though rather clunky, name. Something like this, perhaps:

> The `sumMaxMonotonic() function computes the sum of the maximum values in each monotonically
> increasing sequence of values in the chosen column, ignoring `null` values. For example, given the sequence
> [5, 6, 3, null, 10, 2, 20] it would evaluate to 6+10+20 = 26.
>
> This is useful for operating on sampled counters that increment over time but can be reset to zero.

As an aggregation operator, `sumMaxMonotonic` could easily be pushed down to the storage layer, without the need for more complex rules, and it avoids the need for a new niche-use-case parameter to `difference` that doesn't really make much sense for other use cases AFAICS.

**Comment by rogpeppe** [comment]
I've remembered another use case I had for `firstZero`, which I encountered when processing Prometheus histograms with cumulative bucket counts.

In this scenario, the value associated bucket in the histogram also includes the counts for all the buckets beneath it.
Here's an example table:

```
import "experimental/array"

table=array.from(rows: [
    {kind: "first", bucket: 1, _value: 3},
    {kind: "first", bucket: 4, _value: 10},
    {kind: "first", bucket: 8, _value: 10},
    {kind: "second", bucket: 1, _value: 1},
    {kind: "second", bucket: 4, _value: 100},
    {kind: "second", bucket: 8, _value: 150},
    ])
```

I wanted to display the counts unique to each bucket, rather than cumulatively, so I tried this:

```
table |> group(columns: ["kind"]) |> sort(columns: ["bucket"]) |> difference()
```

Unfortunately, this approach means that we won't see the count for the first bucket in the histogram.

The `firstZero` parameter to `difference` would work well here as a fix, but there's also a way of working around the issue, albeit a bit awkwardly, by including an extra initial row in each table so that there's always at least one initial row with a zero value:

```
grouped = table |> group(columns: ["kind"])
initial = grouped |> first() |> map(fn: (r) => ({r with bucket: -1, _value: 0}))
union(tables: [grouped, initial])
|> sort(columns: ["bucket", "value"])
|> difference()
```

At least... that approach has worked in one place, but when trying it in the Data Explorer with an array table, it gives me a type error! I was trying to demonstrate that perhaps the `firstZero` parameter wasn't really needed (perhaps this is a very niche use-case), but I'm not sure any more...

**Comment by fetzerch** [comment]
This seems to be implemented by the `initialZero` parameter added in https://github.com/influxdata/flux/pull/4168.

**Comment by Marwes** [comment]
Yep, thanks @fetzerch
