### ISSUE TITLE
null isn't declared as an identifier

### ISSUE THREAD

**Issue by rogpeppe** [influxdata/flux#3401]
From the [language specification](https://docs.influxdata.com/influxdb/v2.0/reference/flux/language/data-model/):

> `null` is a predeclared identifier representing a missing or unknown value. 

However, when I try to use `null` in a Flux expression, I get the error "undefined identifier null".

I think that `null` should be declared as specified.

**Comment by rogpeppe** [comment]
FWIW one workaround for this lack is:

```
import "experimental/json"
null=json.parse(data: bytes(v: "null"))
```

**Comment by cranphin** [comment]
Yup, ran into this as well

**Comment by nathanielc** [comment]
@rogpeppe or @cranphin can either you share how you use `null` in your script? Is it as a default value or something else?

**Comment by cranphin** [comment]
In my case I was trying to do something like:
```
  |> pivot(rowKey:["_time"], columnKey: ["_measurement", "_field"], valueColumn: "_value")
  |> map(fn: (r) => ({ r with 
       solar_power_power :
       (if exists(r.solar_power_power) then r.solar_power_power else null),
       solar_power2_power :
       (if exists(r.solar_power2_power) then r.solar_power2_power else null),
       solar_power3_power :
       (if exists(r.solar_power3_power) then r.solar_power3_power else null) }))
  |>
```
So that if there are no data points for a measurement/field in the selected time range, the column is still there.
Otherwise Grafana doesn't show it in the legend for example (other reasons too).

**Comment by nathanielc** [comment]
Thanks for sharing, when you do a look up of a property on a record if the property does not exist a null is returned by default. Therefore I would expect this to work:

```
  |> pivot(rowKey:["_time"], columnKey: ["_measurement", "_field"], valueColumn: "_value")
  |> map(fn: (r) => ({ r with 
       solar_power_power :   r.solar_power_power,
       solar_power2_power : r.solar_power2_power,
       solar_power3_power : r.solar_power3_power}))
  |>
  ```
  
  Did you try something like this already and run into a different problem?

**Comment by rogpeppe** [comment]
in my case, I was using `experimental/array` to construct input cases that contained `null` for testing.

**Comment by nathanielc** [comment]
> in my case, I was using experimental/array to construct input cases that contained null for testing.

This case is coming up a lot, we should add a null identifier so we can easily construct data with nulls.

**Comment by ArchGryphon9362** [comment]
Second this! Useful for things like Grafana.

**Comment by ThiefMaster** [comment]
> in my case, I was using experimental/array to construct input cases that contained null for testing.

You know how useful it would have been had you included the code to do so? ;)
