### ISSUE TITLE
build stuck at  /home/qqqq/.gvm/pkgsets/go1.15.6/global/bin/pkg-config --cflags -- flux

### ISSUE THREAD

**Issue by doivosevic** [influxdata/flux#3412]
Hey,
I'm using gvm to manage go versions and I'm trying to build flux from master.
I've followed the steps as mentioned in the readme.

This is where I get stuck

```

qqqq@kraken:~/git/flux$ go build -v -x ./cmd/flux
WORK=/tmp/go-build925728641
github.com/influxdata/flux/libflux/go/libflux
mkdir -p $WORK/b177/
cd /home/qqqq/git/flux/libflux/go/libflux
/home/qqqq/.gvm/pkgsets/go1.15.6/global/bin/pkg-config --cflags -- flux

```

What gives?

**Comment by jsternberg** [comment]
Can you check your path using `which -a pkg-config`? There might be a bug where it recursively calls the same binary. If this is the case, you should see a lot of invocations of `pkg-config` using `top` or `ps -e`.

A good way to remove this possibility is to rename the binary to something like `cgo-pkgbuild` (or any name) and then set `PKG_CONFIG` explicitly.

```bash
$ export PKG_CONFIG=/home/qqqq/.gvm/pkgsets/go1.15.6/global/bin/cgo-pkgbuild
$ go build -v -x ./cmd/flux
```

That environment variable will cause `go` to invoke that binary for `pkg-config` but it will prevent any recursive calls on the path. The `pkg-config` shim that we use makes an active effort to remove previously called paths from the path to prevent recursive calls, but there seem to be some scenarios where it doesn't work properly.
