### ISSUE TITLE
Extract a table as a usable array

### ISSUE THREAD

**Issue by sanderson** [influxdata/flux#3424]
Currently, the `tableFind()` function extracts a table from a stream of tables, but the only way to interact with the extracted table is by using `getColumn()` or `getRecord()`. It would be nice if the extracted table was a usable array of records or if we provided a way to convert it to a usable array of records. Something like:

```js
import "experimental/array"

// ...
  |> tableFind(fn: (key) => true)
  |> array.to()
```

**Comment by 101100** [comment]
I would find this helpful as well.  I was trying to create a dictionary of initial values (to compute the percentage change relative to the start of the window) like this:

```
firsts = from(bucket: "crypto")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._field == "cad_rate")
  |> group(columns: ["type"])
  |> sort(columns: ["_time"])
  |> first()
  |> group()
  |> map(fn: (r) => ({ key: r["type"], value: r["_value"] }))

firstDict = dict.fromList(pairs: firsts)
```

Instead, I had to do this:

```
firsts = from(bucket: "crypto")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._field == "cad_rate")
  |> group(columns: ["type"])
  |> sort(columns: ["_time"])
  |> first()

getFirst = (type) => (firsts |> findColumn(
    fn: (key) => key.type == type,
    column: "_value"
  ))[0]

firstDict = [
   "algorand": getFirst(type: "algorand"),
   "cardano": getFirst(type: "cardano"),
   "stellar": getFirst(type: "stellar"),
   "tezos": getFirst(type: "tezos")
]
```

That query won't work if a new type is ever added in the future, though.

**Comment by JoemonChittilapilly** [comment]
@sanderson where do I run this query

**Comment by sanderson** [comment]
@JoemonChittilapilly `array.to` isn’t available yet. This issue just proposes the functionality.

**Comment by JoemonChittilapilly** [comment]
Actually i wanted to get the fetch data from influxdb. And i want the data in form json or dictionary. If you know how to do it please comment here.
Thanks

**Comment by sanderson** [comment]
@JoemonChittilapilly, that currently isn't possible, but is one of the use cases adding `array.to()` would help facilitate.

**Comment by annlumia** [comment]
I want fetch data from SQL and use it as filter condition... how to do it?
thanks

**Comment by sanderson** [comment]
@annlumia Your question is a little different than what this issue addresses and is better suited for a forum post. I just created a post that answers it: [How to fetch data from SQL and use it as filter condition](https://community.influxdata.com/t/how-to-fetch-data-from-sql-and-use-it-as-filter-condition/26241).

**Comment by annlumia** [comment]
sorry for the wrong address, before i thought to use `contains()` so i have to convert the data into an array first. But thanks for providing a better solution.

**Comment by valdemartti** [comment]
This feature would be great. I can't seem to find any way to `http.post` a stream of data from e.g. a task to a caching endpoint.

**Comment by michaelo** [comment]
I'm interested as well in this, looking for a way to JSONify an aggregated set of records to http.post() in one go to reduce overhead on remote HTTP endpoint.

**Comment by flacohenao** [comment]
I know flux is under maintenance mode now! but PLEASE.. develop this feature!

**Comment by flacohenao** [comment]
> Another use case here would be to extract a table, encode it as JSON, and then POST the JSON to an HTTP endpoint:

This is the most important feature and currently there is no way to do it!

anyone knows a workaround?
