### ISSUE TITLE
Union doesn't let you union different shaped tables

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#3425]
I get an error when I do this:
```
import "experimental/array"

one = array.from(rows: [{"hello": "world!"}])
two = array.from(rows: [{"nice to meet you": "world!"}])
union(tables: [one, two])
```

```
type error @5:21-5:24: found unexpected label nice to meet you
```

The reason is that the type signature for `union` is `(tables: [[A]]) => [A]`. Since the whole point of `union` is to merge two or more table streams, this seems unfortunate.

This isn't a problem when we don't have complete type information, since type checking doesn't know enough to complain, as with `influxdb.from`. But using `array.from` and also as we fix our builtins to allow for more static checking, this will be more frequent.

How should we think of heterogenous schemas within a stream? Are they only grudgingly tolerated, and so maybe we don't want to facilitate their creation? Or are they wholeheartedly supported, in which case this behavior from `union` makes it impossible to do something totally reasonable?

Related to this: https://github.com/influxdata/flux/issues/3408

**Comment by ryo0ka** [comment]
Hi, is this getting addressed?
