### ISSUE TITLE
aggregateWindow with create empty inconsistent behavior

### ISSUE THREAD

**Issue by konstk1** [influxdata/flux#3428]
`aggregateWindow` with create empty seems to behave differently based on the aggregate function.

For example, I have a measurement with one data point on 12/15. And I would like a flux query that would aggregate by day and if there is no data for that day, to fill with null. If I use `mean` as aggregate function, it behaves as expected, and I get empty windows after 12/15 to present.

`|> aggregateWindow(every: 1d, fn: mean, createEmpty: true)`

However, if I use `last` as aggregate, I do not get any empty windows. Only the window with the data point. Same behavior is observed for `min` and `max` aggregate.

`|> aggregateWindow(every: 1d, fn: last, createEmpty: true)`

This is unexpected. Is this a bug or is there a reason for this?

**Comment by AntonBiryukovUofC** [comment]
@kostyan5 I would second that:
` |> aggregateWindow(every: 15m, fn: last, createEmpty: false)` works just fine on a string-valued `_value` column.
` |> aggregateWindow(every: 15m, fn: mode, createEmpty: false)` returns empty values. Why ?

**Comment by jlapacik** [comment]
@kostyan5 this is due to differences between aggregators and selectors. Selectors are functions that select a single data point from a table. These are functions like `first`, `last`, `min`, `max`, etc. In flux, selectors always remove empty tables, whereas aggregators (`sum`, `count`, `mean`, etc) do not. So even though `createEmpty` is set to `true` in `aggregateWindow`, if used with a selector, any empty tables will be removed automatically.

For clarity, `aggregateWindow` is defined as follows
```
aggregateWindow = (every, fn, column="_value", timeSrc="_stop", timeDst="_time", tables=<-) =>
    tables
        |> window(every:every)
	|> fn(column:column)
	|> duplicate(column:timeSrc, as:timeDst)
	|> window(every:inf, timeColumn:timeDst)

```

**Comment by kostyan5** [comment]
@jlapacik Thanks for the explanation. While that's understandable, I think it would be very helpful to have selectors behave in a similar manner. Otherwise, it makes it hard to fill in missing values with some defaults.

**Comment by wolffcm** [comment]
It's possible to get the desired behavior by creating a special function  to do it. In this example `nullPreservingLast` will create a null value for empty windows by using `sum()`.
```js
nullPreservingLast = (tables=<-, column="_value") => 
  tables |> last(column) |> sum(column)

from(bucket: v.bucket)
  |> range(start: -24h)
  |> filter(fn: (r) => r._measurement == "cpu")
  |> filter(fn: (r) => r._field == "usage_idle")
  |> filter(fn: (r) => r.cpu == "cpu-total")
  |> aggregateWindow(fn: nullPreservingLast, every: 1h, createEmpty: true)
```

I agree that the difference in behaviors of aggregates and selectors is confusing. We will need to think on how to make dealing with these differences more intuitive.

**Comment by kostyan5** [comment]
Thanks, @wolffcm. Is there a way to save the function for global use in queries (as opposed to redefining it in every query)?

**Comment by wolffcm** [comment]
@kostyan5 At the moment the way to do what you're asking about is by adding a new package to the Flux stdlib under the `stdlib/contrib` directory. There's some directions on that in the README here:
https://github.com/influxdata/flux/tree/master/stdlib/contrib

For this particular case, it seems like it's a frequent need to downsample and/or fill data with `last()` so I'd also like to explore adding the above to the stdlib.

**Comment by wolffcm** [comment]
Potential solutions:

1. Make `aggregateWindow` a builtin with the semantics we want.

2. Make a special builtin function that does will translate empty tables to have a single row with `null`s for value columns. Add this new builtin to the definition of `aggregateWindow`. Update planner logic and sources to be able to push this down and have the right semantics. (It may be a net loss of code to implement these semantics in sources since they will be closer to aggregates)

**Comment by Simoneram** [comment]
> 
> 
> It's possible to get the desired behavior by creating a special function to do it. In this example `nullPreservingLast` will behave like `last` except that it will create a null value for empty windows by using `sum()`.
> 
> ```js
> nullPreservingLast = (tables=<-, column="_value") => 
>   tables |> last(column) |> sum(column)
> 
> from(bucket: v.bucket)
>   |> range(start: -24h)
>   |> filter(fn: (r) => r._measurement == "cpu")
>   |> filter(fn: (r) => r._field == "usage_idle")
>   |> filter(fn: (r) => r.cpu == "cpu-total")
>   |> aggregateWindow(fn: nullPreservingLast, every: 1h, createEmpty: true)
> ```
> 
> I agree that the difference in behaviors of aggregates and selectors is confusing. We will need to think on how to make dealing with these differences more intuitive.

@wolffcm such function is helpful when aggregating double or integer datatypes. How would you do in case of booleans? I am currently looking for aggregators that work with bool (sum does not). For efficiency reason, converting the booleans into integers and then applying nullPreservingLast is not feasible.

**Comment by jsternberg** [comment]
Closing in favor of #3681.
