### ISSUE TITLE
Task.lastSuccess does not return last successful task run time

### ISSUE THREAD

**Issue by hardincm2** [influxdata/flux#3430]
`tasks.lastSuccess` appears to always return the `orTime` value regardless as to whether the task has successfully run in the past or not. As a simple test, I wrote a Flux script that just writes the returned value of this function call to bucket and I can observe that the orTime value is always used.

```
import "experimental/array"
import "influxdata/influxdb/tasks"

option task = {name: "chardinTest", every: 10s}

array.from(rows: [{
	_time: now(),
	_field: "test",
	_value: 0,
	start: string(v: tasks.lastSuccess(orTime: 2021-01-01T00:00:00Z)),
	stop: string(v: now()),
	_measurement: "chardin-task-test",
}])
	|> to(bucket: "test-bucket", org: "test")
```

Every single metric produced by this task has the value **2021-01-01T00:00:00Z** set for the `start` column.

Any ideas as to why I may be experiencing this issue? This feature is invaluable for me to ensure I'm not having holes in my data - especially when deploying influx and the app goes offline for a minute or so.

Thanks a ton!
- Cam

**Comment by gorkem2020** [comment]
having the same issue here. this function is not working. Any updates on this?

**Comment by aortuno-liberty** [comment]
Having the same issue here, lastSuccess defaults to orTime

Anyone has been able to resolve it?

**Comment by sdmueller** [comment]
Experiencing the same problem.\
This always returns `orTime` even when there already is a successful task run.

**Comment by rkleivel** [comment]
Experiencing the same issue on InfluxDB 2.6.1
tasks.lastSuccess() seems to return orTime regardless when task was successfully run

**Comment by DuongDiep2612** [comment]
With InfluxDB 2.6.1 installed on windows server 2016 (run influxd.exe). I also have the same problem.

**Comment by virtualdj** [comment]
Please let us know if/when this is fixed, because this could be useful in tasks to downsample the data without missing points in case the task fails (some scripts [here](https://thenewstack.io/influxdb-as-an-iot-edge-historian-a-crawl-walk-run-approach/)).

At the moment I've a task that extracts the data to be downsampled like so:
```
option task = { 
  name: "downsampledbucket_1h",
  every: 1h,
  offset: 5m
}

// Extract the data to be downsampled
data = from(bucket: "originalbucket")
  |> range(start: -duration(v: int(v: task.every) * 2))
  |> filter(fn: (r) => r._field == "value")
```
The problem is that if the task fails, I lose the data between the unsuccessful and successful task runs.
Probably it should be changed to something that includes the **last successful task date** as the data extraction **start range**, instead.

**Comment by kirwinrMK** [comment]
I am having this issue as well. Any solutions?

**Comment by zcattacz** [comment]
I am having this issue too. 
InfluxDB v2.7.7 (git: e9e0f744fa) build_date: 2024-07-11T18:45:02Z
