### ISSUE TITLE
Support for missing values

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#344]
Flux needs to be able to represent missing data. I see two ways we could approach this problem

## Null

Using a sentinel value like `null` will allow for a row to represent that it is missing data for a column

Example of map using null

```
map(fn:(r) => {
     if r._value == null {
          return 0
     }
     return r._value * 2
})
```

## Structural Polymorphism + Exists operator

Structural polymorphism allows for list of objects that have differing labels. I.e. data is simply missing from the record. Currently a function could only consume labels that are common to all row in the list. If we add an exists operator that guards access to the label/col then we can have conditional and type checked safe access to the labels.

Example of map using exists operator

```
map(fn:(r) => {
     if exists _value r {
          return r._value * 2
     }
     return 0
})
```

The syntax/name/etc on the exists operator is not important to this issue. Mostly the question is about which model is easier to reason about.

## Notes

The underlying implementation of tables is not a list of row, but rather  is a column representation. We will likely use some form of null (via a null bitmask) to implement missing values independent of the approach used.

The question is which approach is most helpful to the user. Does one provide more feedback to the user about possible errors in the code?

**Comment by rbetts** [comment]
I find `if r._value == null` to be confusing as I expect (from SQL) that nothing equals null. This discussion should also compare the different models in the context, for example, left join (http://www-db.deis.unibo.it/courses/TW/DOCS/w3schools/sql/sql_join_left.asp.html).  

I also prefer `isNull()` to `exists()` as my bikeshed color :-)

**Comment by stuartcarnie** [comment]
@rbetts this same discussion came up today in the Arrow discussion regarding `NULL` support and the behavior for aggregates. Those with a SQL background, myself included, are used to `SUM(<column>)` returning `NULL`, where `<column>` contains some `NULL` values. The consensus was to ignore nulls.

Having sat on it for a while, I think the discussion is worth exploring further, as I'm now concerned ignoring nulls will be surprising to users. I would now argue that explicit is better and we should add functions like `COALESCE` or `IFNULL` to allow the user to decide how to deal with nulls.

@jsternberg brought up a good way to think about `NULL`; it has similar semantics to `NaN`.

**Comment by rbetts** [comment]
Ignoring nulls is a fill() - that’s wordier but it makes NULL handling more consistent with other possible datasources.


________________________________

**Comment by wolffcm** [comment]
For what it's worth, at least some SQL implementations will ignore nulls in `sum`...

https://docs.microsoft.com/en-us/sql/t-sql/functions/sum-transact-sql?view=sql-server-2017

> Null values are ignored.

**Comment by stuartcarnie** [comment]
@wolffcm as it stands, MySQL and PostgreSQL behave the same (ignore `NULL`). So ignore my comment about aggregates over nulls (though the behavior should be specified in the spec):

~~Having sat on it for a while, I think the discussion is worth exploring further, as I'm now concerned ignoring nulls will be surprising to users.~~

**Comment by nathanielc** [comment]
This PR ended up having a good discussion on nulls in Flux, https://github.com/influxdata/flux/pull/1178#discussion_r275923093 

There are some good questions raised in that thread.

**Comment by nathanielc** [comment]
A summary of the discussion from the linked PR.

A proposal was made to not represent missing values as having a null value rather to leverage the type system to explicitly model missing values are missing properties on objects. The advantage of such a model is that Flux values are not null-able so users do not need to worry about constantly checking for nulls. A disadvantages is that the default behavior is to ignore the presence of nulls, so while a user's script may work without nulls in dev, in prod if nulls are encountered the script will fail.  A user must explicitly code defensively in order to handle them gracefully. Another concern is that nulls will occur in areas where the type system cannot represent them as "missing values" and that having an explicit null value would be optimal.

**Comment by aanthony1243** [comment]
WIP PR to add an exists function to flux:  https://github.com/influxdata/flux/pull/1164

functionally, flux needs some additional work: 
1.  erroring instead of a panic when an unchecked null is evaluated
2.  conditional expressions so that we can use `exists` in the context of a `map` or `reduce` operation.

**Comment by aanthony1243** [comment]
proposal:  add an `exists(r:r,  key: "_value")` function that lets us check a record for a given key.  It will return false under two conditions: 
1.  `_value` is not in `r`
2.  `_value` is in `r` but it is `null`

to summarize this strategy, we want to hide from the user that nulls are present in the data.  Internally, we have to detect and treat them accordingly, but from the user's perspective, if the internal value for a field is null, then that record is not present.

https://github.com/influxdata/flux/pull/1278  has the work finished for the `exists` function, but there is more work to do: 

1.  in `map` and `reduce` and for any transformation that uses a row function of arbitrary column references, we may reach a point where we try to decode a null value into a concrete type.This currently causes a panic.  #1199 
2.  we need to update the spec and scrub the concept of `null`

**Comment by nathanielc** [comment]
Closing see https://github.com/influxdata/flux/blob/master/docs/SPEC.md#missing-values-null for how Flux handles missing values.
