### ISSUE TITLE
Percentage difference function between subsequent rows

### ISSUE THREAD

**Issue by Bosma** [influxdata/flux#3446]
The function `difference()` returns the arithmetic differences between rows (`r0, r1, r2 => r2 - r1, r1 - r0`), it would be useful to have a function that returns the geometric difference (`r0, r1, r2 => r2 / r1, r1 / r0`). You often calculate returns r<sub>t</sub> / r<sub>t-1</sub> - 1 in finance, so it would be helpful for that.

**Comment by gdhaaijer** [comment]
Agreed, been looking for this to calculate returns.
