### ISSUE TITLE
Implement test extension AST transformation

### ISSUE THREAD

**Issue by rockstar** [influxdata/flux#3447]
As detailed in the design issue #3335, we need to modify the AST transformations for `testcase` to work like the following

    package strings_test
 
    testcase strings_trim {
        // strings trim test
    }

would then expand to:

    package main

    strings_trim = () => {
        // strings trim test
    }
    strings_trim()

The AST transformation would inject the call after all other transformations are made. A downstream consumer could then do the following:

    testcase special_string_trim {
        import "strings/strings_test"
        strings_test.string_trim()
    }

...could then be expanded to

    package main

    strings_test = {
        "string_trim": (ast for string trim),
        "other_variable": (ast for others),
    }
    special_string_trim = () {
        strings_test.string_trim()
    }
    special_string_trim()

This would also have to take into account `option` statements, as they'll have to be hoisted to the top scope the same way the `import` statements would be, each in its own context.

**Comment by jsternberg** [comment]
I'm going to start looking into this but likely going to formally start working on it on Monday.
