### ISSUE TITLE
EPIC: Create join package with outer join support

### ISSUE THREAD

**Issue by scbrickley** [influxdata/flux#3459]
We should create a new standalone `join` package that supports join types other than "inner". We want the the API to look something like this:

```
package join
builtin do : (
    <-left: [L],
    right: [R],
    predicate: (l: L, r: R) => bool,
    fn: (l: L, r: R) => A,
    // method is one of inner,outer,left,right
    method: string,
) => [A] where
    A: Record,
    L: Record,
    R: Record
time = (left=<-, right, fn, method="inner") => join(
    left: left,
    right: right,
    predicate: (l, r) => l._time == r._time,
    fn: fn,
    method: method,
)
join.time(
    left: l,
    right: r,
    //method: "left",
    //method: "right",
    //method: "outer",
    method: "inner",
    fn: (l, r) => {
        rvalue = if exists r._value then r._value else 0
        return {l with
            _value: l._value + rvalue,
        }
    },
)
join.join(
    left: l,
    right: r,
    method: "left",
    predicate: (l, r) => l.room == r.room and l._value < r._value,
    fn: (l, r) => {
        rvalue = if exists r._value then r._value else 0
        return {l with
            _value: rvalue / l._value,
        }
    },
)
```

Care will have to be taken to avoid using a nested loop to iterate over left and right tables so that everything is performant. In some cases it may be unavoidable.

Open questions:
- How to implement a planner rule that can analyze a predicate
- How to teach the plan to detect if data is sorted or not. If it is sorted, it can use the merge sort join implementation. If not, it can either sort the data first, or just default to the nested loop join.

DOD: 
- Have one package that supports inner, outer, left, and right joins.
- Deprecate the stdlib `join` and `experimental/join`
- Documentation and examples in the new package

---

### Issue Tracking:

- Design and investigation:
    - #4624
    - #4625
    - #4626
- Implementation:
    - #4627
    - #4628
        - Blocked by #4678
    - #4629
- Rollout:
    - #4630
    - #4631
    - #4632
    - #4633
    
    
### Related Issues

- #84

**Comment by philomory** [comment]
My only concern with this (and with the deprecation of `experimental.join`) is that there is no possible function that could be passed as the predicate, that would replicate the behavior of `experimental.join` (that is, join on the group key, _whatever the group key happens to be_).

**Comment by nathanielc** [comment]
`experimental.join` is the equivalent of `join.time` in this proposal. All of the above functions should honor the group key.

**Comment by philomory** [comment]
Sooo... are there still plans to implement this? The lack of outer join makes some seemingly basic tasks impossible (or at least, incredibly complicated and inefficient) to accomplish (like, say, select all records in a stream of tables whose value is more than three standard deviations from the mean _for that table_).

**Comment by jsternberg** [comment]
My only comment on the function signature is that we should use `on` instead of `predicate` and `as` instead of `fn`. I think this is more similar to the same terminology for an SQL query. You join `ON` the predicate and `AS` is used to name columns.
