### ISSUE TITLE
Function argument defaults should not introduce type constraints

### ISSUE THREAD

**Issue by philomory** [influxdata/flux#3461]
There are built-in functions that accept multiple types for the same argument; one prominent example is `range()`, whose `start` parameter can accept either a Time, or a Duration. If you write a function in Flux that passes one of its arguments to `range()` as the `start` parameter, your function now _also_ accepts multiple types for that argument. For example:

```
fun = (tables=<-, x) => tables |> range(start: x)

data |> fun(x: -10m) # this is fine
data |> fun(x: 2021-01-28T12:00:00Z) # so is this
```

However, if your function provides a default value for the argument, suddenly your callers are constrained to call your function with a value of the same type as the default:

```
fun = (tables=<-, x=-20m) => range(start: x)

data |> fun(x: -10m) # this is fine
data |> fun(x: 2020-01-28T12:00:00Z) # this is a type error
```

The most obvious place this comes up is `schema.tagValues` (and similar functions); becasue `schema.tagValues` has a default `start` value of `-30d`, it's not possible to pass an absolute time, even though nothing `schema.tagValues` _does_ with the `start` argument requires that it be a duration and not a time. `schema.tagValues` is even [documented](https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/influxdb-schema/tagvalues/#start) as taking either a duration or a time, but in actual fact it cannot.

There are [issues](https://github.com/influxdata/flux/issues/1071) open about this specific case, and the proposed solution seems to be to make duration literals polymorphic, so they can fill in for times. That may be a fine idea (though I'm not sure it would actually solve the problem, given that the types are backwards), but it still leaves the general case unsolved. For example, consider the following (rather silly but perfectly valid) function:

```
fun = (x) => "Hello, ${string(v: x)}"

fun(x: "bob") # returns "Hello, bob"
fun(x: 10) # returns "Hello, 10"
```

This function _also_ breaks if a default value is added:

```
fun = (x="World") => "Hello, ${string(v: x)}"

fun(x: "bob") # returns "Hello, bob"
fun(x: 10) # is now a type error
```

I think this is unreasonably restrictive; adding a default value for a function argument should never make a previously valid function call invalid.

**Comment by nathanielc** [comment]
See #3629 it is a duplicate and has a good write up of the problem as well.
