### ISSUE TITLE
Attempt to recover from errors inside array expressions, while still making progress

### ISSUE THREAD

**Issue by adrian-thurston** [influxdata/flux#3466]
In https://github.com/influxdata/flux/pull/3464 we break from the array expression parsing when a bad array entry is found. Prior to that PR we would push onward, however it led to a busy loop, resulting in 100% CPU and an OOM when a parse error was found. 

We should attempt to bring the error recovery back, but without introducing a busy loop. This can be achieved by monitoring progress made through the input. Doing so will break a number of test cases, which will need to be dealt with. https://github.com/influxdata/flux/pull/3464#issuecomment-771780954.

**Comment by nathanielc** [comment]
Note, it seems like the test/build failures are related to the stdlib. Perhaps there is some bad syntax somewhere in the stdlib that we are currently skipping over and the change correctly caught that and produced BadExpressions.
