### ISSUE TITLE
[feature request] date.format function

### ISSUE THREAD

**Issue by philomory** [influxdata/flux#3473]
After discussing with @jsternberg in Slack, he suggested I file an issue to track a request for a `format` function in the `date` package that would allow you get a string-representation of a date/time value in a particular format (i.e. something roughly equivalent to `strftime` in other languages, in approximate functionality if not in detail).

**Comment by ccremer** [comment]
I would be also interested in this.
I have a query that returns the max value per day in windows and would like to name it accordingly. right now I can use `strings.substring` like this:

```
...
  |> window(every: 24h)
  |> max()
  |> map(fn: (r) =>
    ({_value: r._value, _time: r._time, _field: strings.substring(end: 10, start: 0, v: string(v: r._time))})
  )
```
it gives me this:
```
Result: _result
Table: keys: [_field]
         _field:string                      _time:time                  _value:float  
----------------------  ------------------------------  ----------------------------  
            2021-06-12  2021-06-12T18:58:30.000000000Z                         66500  
Table: keys: [_field]
         _field:string                      _time:time                  _value:float  
----------------------  ------------------------------  ----------------------------  
            2021-06-13  2021-06-13T09:58:00.000000000Z                         25532  
```
So I can use the `_field` property in Grafana in a bar chart to name a bar.
![image](https://user-images.githubusercontent.com/12159026/121803208-b9ac9280-cc40-11eb-9d1f-ede74157ed07.png)


Would be more robust/flexible if there's a `date.format(f: "yyyy-MM-dd", v: r._time)`

**Comment by russorat** [comment]
this would really help our users create better alerting status messages since they use string interpolation today. right now, the best you can do without a ton of slicing and dicing is `${time(v: r._source_timestamp)}` or `${strings.substring(v: string(v: time(v: r._source_timestamp), t: ".")}` to get a date like `2021-06-13T09:58:00`. It's not easy.

**Comment by trunet** [comment]
possible duplicate: https://github.com/influxdata/flux/issues/2886

**Comment by hemanthactionfi** [comment]
thanks @ccremer
![Screenshot_20211001_201543](https://user-images.githubusercontent.com/78481922/135639867-c2b8af64-f7cd-4d1d-b3a7-17b8e1f0fc9b.png)

```flex
import "strings"

from(bucket: "telemetry")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "csv7_2" or r["_measurement"] == "csv6")
  |> filter(fn: (r) => r["_field"] == "flightDistance" or  r["_field"] == "altitudeAMSL")
  |> aggregateWindow(every: 1d, fn: max, createEmpty: false)
  |> pivot(rowKey:["_time"], columnKey: ["_field",], valueColumn: "_value")
  |> keep(columns: ["_time", "altitudeAMSL", "flightDistance"])
  |> map(fn: (r) => ({  a_day: strings.substring(end: 10, start: 0, v: string(v: r._time)), flightDistance: r.flightDistance, altitudeAMSL: r.altitudeAMSL })) 
```
