### ISSUE TITLE
String concatenation performance hit

### ISSUE THREAD

**Issue by FinnHuelsbusch** [influxdata/flux#3477]
__Steps to reproduce:__

1. Create a database with some entries (tested with 250)
2. Perform the following query to get all measurements of custom_Performance: `
from(bucket: "mybucket")
  |> range(start: 2021-02-05T02:51:27Z, stop: 2021-02-05T08:51:27Z)
  |> filter(fn: (r) => r["_measurement"] == "custom_Performance")
3. Perform the following query to get all measurements of custom_Performance: `
from(bucket: "mybucket")
  |> range(start: 2021-02-05T02:51:27Z, stop: 2021-02-05T08:51:27Z)
  |> filter(fn: (r) => r["_measurement"] == "custom\_"+"Performance")

__Expected behavior:__
The execution time should be similar.

__Actual behavior:__
The first query is ~4s faster than the second one for the last 6h. For the last 30d the difference is ~40s 

__Environment info:__
InfluxDB version: InfluxDB Cloud 

__Performance:__
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

I can not create the required logs, because I am on Windows. 

I hope some can test and validate this issue.

**Comment by FinnHuelsbusch** [comment]
@sanderson Thank you for your quick reply. 
Excluding the concatenation into a separate variable worked perfectly. 

The example above is just to demonstrate the problem. 
The real use case may look a bit strange: 
There are several measurements in my bucket. Each measurement is in there twice. Once with the name ('Performance' in the example) and once with 'custom_' as prefix before the name('custom_Performance').
To display the data, I use Grafana. On my dashboard I have two variables. One to select the measurement and one to select the BuildIDs. The measurements with the prefix 'custom_' are not present in the measurement variable, only the real name. Now when the user chooses a measurement, I want to get the BuildIDs of both the 'custom_' and the normal measurement for the sexond variable. To archive this, I came up with this filter: 
`filter(fn: (r) =>r["_measurement"] == "custom_"+${measurement:doublequote} or r["_measurement"] == ${measurement:doublequote}` 

${Measurement:doublequote} is 'translated' by Grafana. For example, into "Performance". 

I do not think that I will be the last  person to try this... 
If it can't be fixed a note in the documentation might be useful. 

So thanks once more for the fast reply 👍  😃

**Comment by sanderson** [comment]
@FinnHuelsbusch Cool. Storing the names in variables outside of `filter()` is definitely the way to go.

Another potential solution... I don't know how similar all the names of your measurements are, but could you just use a regular expression in the predicate function? You can convert your measurement string into a `regexp` type using the `regexp.compile` function:

```js
import "regexp"

filterRegex = regexp.compile(v: ${measurement:doublequote})

// ...
  |> filter(fn: (r) => r._measurement =~  filterRegex)
```

**Comment by sanderson** [comment]
Actually, to create a regular expression that wouldn't accidentally pull in other measurements, you could do:

```js
import "regexp"

filterRegex = regexp.compile(v: "^(custom_)?" + ${measurement:doublequote} + "$") 

// ...
  |> filter(fn: (r) => r._measurement =~  filterRegex)
```

If `measurement:doublequote = Performance` then `regexp.compile(v: "^(custom_)?" + ${measurement:doublequote} + "$")` compiles to `^(custom_)?Performance$`, which would only match against `custom_Performance` and `Performance`.

**Comment by FinnHuelsbusch** [comment]
I think I will take the last suggestion. Thanks again. From my side, the issue could be closed, unless you would like to leave it upon for further tracking. 😄

**Comment by sanderson** [comment]
I think we can close it. Using operations like this inside of a filter `fn` will always cause a performance hit, but I think we can call that out better in the documentation: https://github.com/influxdata/docs-v2/issues/2150

**Comment by philomory** [comment]
I know this issue is closed already, but I feel like, for anyone who happens upon this in the future I should add, given the way Grafana actually works, to do this in Grafana you could just make your filter function look like this:

```
filter(fn: (r) => r._measurement == "custom_${measurement}" or r._measurement == "${measurement}")
```

By the time the query is actually sent to InfluxDB, it'll have already been resolved to:

```
filter(fn: (r) => r._measurement == "customer_Performance" or r._measurement == "Performance")
```
