### ISSUE TITLE
repl does not exits on ctrl+c

### ISSUE THREAD

**Issue by tkiraly** [influxdata/flux#3483]
when i run the repl, ctrl+c does not exits just generates a new line.

after some investigation seems like go-prompt swallows the ctrl+c and it never gets to the syscall signal part.

here is where the swallow happens https://github.com/c-bata/go-prompt/blob/8e6eb48b4aa09bfc6701ad171e6c855d873724a3/prompt.go#L131

ctrl+d exits the prompt instead.
https://github.com/c-bata/go-prompt/blob/8e6eb48b4aa09bfc6701ad171e6c855d873724a3/prompt.go#L148

 this should be documented in the readme file of influxdb

**Comment by sanderson** [comment]
@tkiraly Using the REPL is documented here: https://docs.influxdata.com/influxdb/cloud/tools/repl/.

The REPL is separate from InfluxDB, so it wouldn't need to be added to the InfluxDB readme. If this were going to be added to a readme, I'd propose it be added to the Flux readme where information about the REPL is currently found.

**Comment by tkiraly** [comment]
@sanderson thanks for the documentation.
i was referring to the getting started section of the README of this repo, might worth to mention that further info can be found on the mentioned url.
![image](https://user-images.githubusercontent.com/1835297/107509172-664b0a80-6ba2-11eb-8966-c6810b3c6495.png)
