### ISSUE TITLE
findColumn() only gets 1 item after group() without using unique()

### ISSUE THREAD

**Issue by abalone23** [influxdata/flux#3495]
Even though I ungroup the data with `group()` so that all 3 records are in table 0, the number of items in the array returns 1 instead of 3. If I change the annotated csv to use table 0 for all 3 records, which looks identical to the first query after I ungroup the data, it correctly returns an item array count of 3.

```
import "experimental/array"
import "csv"

csvData = "
#group,false,false,false,false,true,true
#datatype,string,long,dateTime:RFC3339,string,string,string
#default,_result,,,,,
,result,table,_time,_value,_field,_measurement
,,0,2021-02-14T19:19:57Z,1,f1,m1
,,1,2021-02-15T19:19:57Z,2,f1,m1
,,2,2021-02-16T19:19:57Z,3,f1,m1
"
data = csv.from(csv: csvData) |> group()

f1_vals = data
        |> findColumn(fn: (key) => true, column: "_value")

array.from(rows: [{_measurement: "test_m"}])
    |> map(fn: (r) => ({ r with array_count: length(arr: f1_vals) }))
```

I see the same issue using `tablefind()` and `getColumn()` instead of `findColumn()`
```
      |> tableFind(fn: (key) => true)
      |> getColumn(column: "_value")
```

It works fine if I add `|> unique()` after `group()`.

Flux version: v0.105.1-0.20210204233339-cfe404620069
InfluxDB Cloud: https://us-west-2-1.aws.cloud2.influxdata.com/

Also happens on OSS 2.0.3, Flux version: v0.99.0

**Comment by LionelCons** [comment]
It seems that this issue is still present in Inf;uxDB 2.2.0.

Any ETA for a fix?

**Comment by LionelCons** [comment]
Possibly related to https://github.com/influxdata/influxdb/issues/23215.
