### ISSUE TITLE
Graphing data for a given time range is painful when using functions that reduce the range of the data.

### ISSUE THREAD

**Issue by philomory** [influxdata/flux#3507]
(This is a summary of a discussion from the `#flux` channel in InfluxData's community Slack)

There are a number of functions that reduce the number of datapoints in a sample. More specifically of interest, there a number of functions that change the endpoints of the time range of the dataset being worked with.

For example, if you have a dataset queried with `range(start: -11m, stop: -1m)`, with data with a resolution of 1 data point per minute, you will have 10 datapoints: one from (say) 1:00, one from 1:01, one from 1:02, etc, up to 1:09. If you then pass this data through the `difference` function, you will now have 9 datapoints: one from 1:01 (representing the difference between 1:00 and 1:01 in the source data), one from 1:02, etc. The `aggregateWindow` function has a similar effect; besides the obvious reduction in data resolution (which is expected and basically the point of the function), it also induces a reduction in data range, because all points from a window are aggregated as one of the endpoints of that window.

If you then graph this reduced data set on a graph that displays your initial 10-minute range, you will have a gap on the right side of your graph. Depending on your data resolution, selected time range, and the number of range-reducing functions, the gap may be more or less noticeable, but it will always be there.

In an ideal world, it would be nice for for the user to be able to say "I want data from this ten minute period", and then have it be the _engine_'s responsibility to recognize that the query involves (for example) two functions that reduce the range of the data, so it should _actually_ start with twelve minutes of data so that it'll have ten minutes worth of data at the end of the query.

That being said, it's understandable that this isn't necessarily something that's easy for the engine to do automatically given how flexible Flux is, and it is after possible for the user to take responsibility for this themselves. My main complaint, then, is that Flux makes handling this manually _way_ more difficult than it needs to be. I think this breaks down to a few different problems:

1. It's be nice if the engine just took care of this magically. I'll leave that aside for the moment.
2. Neither the need for, nor the method to, do this manually is actually documented anywhere. Documentation for individual functions that reduce the data range does mention that fact, but the implication this has for graphs and what to do about it is never really dicussed.
3. The naive solution you might try is using `range(start: v.timeRangeStart - v.windowPeriod)`, so you can start a little bit early. This doesn't work because duration math isn't implemented.
4. The next obvious solution attempt will be `range(start: experimental.subDuration(from: v.timeRangeStart, d: v.windowPeriod))`. This works as long as `v.timeRangeStart` is a `time` value and not a `duration` value, so it'll work for all Grafana queries and some InfluxDB queries. If `v.timeRangeStart` is a `duration` value instead, you'll need `range(start: duration(v: int(v: v.timeRangeStart) - int(v: v.windowPeriod))`. There's no way in Flux (that I know of) to express `if <variable> is of type duration then do A else do B`, so there's nothing you can write here in a InfluxDB dashboard that will work no matter what time range is selected (because in InfluxDB's dashboards, v.timeRangeStart might be _either_ a time _or_ a negative duration).
5. Even that cumbersome expression isn't quite enough if you have multiple range-reducing functions in your query. A naive attempt to double the amount of "seed data" would be `range(start: experimental.subDuration(from: v.timeRangeStart, d: 2 * v.windowPeriod))`, however this will fail because you can't multiply a duration by two (nor add a duration to another duration). Instead, you need to write `range(start: time(v: int(v: v.timeRangeStart) - 2 * int(v: v.windowPeriod)))`. This is actually shorter than `experimental.subDuration`, but it's less clear.
6. Since you're requesting more data than you actually want up front, it would be prudent to pass your data through `range()` again at the _end_ of the query to filter it down to your desired final dataset. Unfortunately, when `range()` is executed "in-memory" (rather than as a pushdown function in the storage engine) the performance isn't very good (apparently; I haven't witnessed this myself but it was brought up by others in a discussion in Slack).
7. If you write a custom function to encapsulate the above logic, you can't actually re-use that function without just pasting it into all your queries, unless you compile Flux and InfluxDB from source, because there's no way to import user-created libraries at runtime.

A lot of this would be resolved by implementing native duration arithmetic (including adding durations to, and subtracting them from, times; and multiplying durations by positive integers and probably floats); beyond that some additional documentation would probably be useful.

**Comment by jsternberg** [comment]
Thanks for bringing this up in the community channel and summarizing the conversation here in the issue tracker. The issues here are ones that I'm well familiar with from InfluxQL and ones that we'd like to see Flux learn from. I want to assure you that this is an active problem that we want the language to address, but I also want to give you a realistic timeline that some of the things I mention as ideal solutions may not land in the language/database for some time and I can't give a date or timeline. We hope that we can make some of the more low effort solutions available sooner though and that this issue can help guide future language development.

Since this issue is so expansive, I am going to work on trying to split the various comments into different issues. I'll link them back here when I am done.

**Comment by jsternberg** [comment]
Created #3515 to address the first point.

For some context, the issue specifically mentions `from()` because I think we would only be able to do this for the influxdb source itself. Flux, while very focused on querying InfluxDB, is itself a data source agnostic language and so features like this would be limited to the specific data source. I envision that after we have the underlying functionality we'd be able to do things like:

```
package influxdb

// counter reads a counter from influxdb using difference.
counter = (bucket, start, stop=now()) => from(bucket, seed: 1) |> range(start, stop) |> difference()
```
counter

**Comment by jsternberg** [comment]
For the third point, I agree that this should be easier. Duration math can be quite hard though because of the type system. In summary, the subtraction operator requires both the left and the right side to be the same type and so it asserts that this is the case. We have discussed in the past time operators dedicated to making this easier.

https://github.com/influxdata/flux/issues/2026

The other reason is because duration math itself isn't commutative so `+` and `-` can be confusing, but this same criticism applies to string addition too which is something we allow. The bigger reason is the type system which makes this non-trivial to implement.

**Comment by jsternberg** [comment]
For point 4, I believe we are doing work to make it so a larger number of functions accept both durations and times. At the same time, I think it would be a good practice for influxdb to choose a type and stick to it. I've filed https://github.com/influxdata/influxdb/issues/20810 for that.

**Comment by jsternberg** [comment]
I'll try to find an issue for user-defined imports, but user-defined imports would be what is needed for point 7. It's long been on the list, but it's a lot of work so we don't have a timeline when that will be available for everyone to use. If you want to create some general utility functions, we accept contributions to the standard library through the `contrib` import path: https://github.com/influxdata/flux/tree/master/stdlib/contrib.

This isn't a workable solution for some, but it would let you encapsulate some of these ideas and experiment with how you'd like them to look if they were incorporated as first-class citizens into the standard library. If we saw a PR for that, it would definitely get looked at, merged, and looked at for ideas of how to improve the standard library in future versions.

**Comment by philomory** [comment]
It often seems, from the outside, that Flux's type system is causing more problems than it's actually solving. I've seen a type error from Flux expose a logical error in query I've written before talking to the storage engine maybe a single time. On the other hand, I've had numerous experiences where it makes things that should be simple, difficult or impossible:

* Durations are of extremely limited utility, and fixing them is made more difficult (or impossible?) by the type system
* Lots of built-in functions accept multiple types, and if you write a function that wraps them, it also accepts multiple types... unless your argument has a default value, in which case you lose your polymorphism.
* Dicts and Records need different syntaxes, and Dicts need a dedicated library, even though they're in many ways the same thing (this one is arguable; I _personally_ think it's a distinction without a difference but I know reasonable people disagree).
* String interpolation can requires the interpolated value to be a string... but even `"hello ${string(v: r.foo)}"` isn't guaranteed to work, because `string(v: r.foo)` returns a null value when `r.foo` is null.
* `fill(column: "foo", value: "bar")` is good at replacing nulls most of the time... but sometimes depending on your source data and the way stuff is grouped, in some tables you may end up with no `foo` column at all (e.g. the `errorMessage` column in `_tasks.runs` will just be absent if there's no failed tasks in your query range), in which case `fill()` throws a type error.

I think there's been other stuff, too, but that's the stuff that comes to mind at the moment.

Obviously, I'm not one of the implementers of Flux. I wasn't there when the decisions about the type system were made, and I don't know the benefits that it gained for the language. Every language design decision is full of trade-offs. But, from the outside, it seems like Flux is fighting against its type system rather than working with it.
