### ISSUE TITLE
Interpolating possibly-null fields into a string is cumbersome

### ISSUE THREAD

**Issue by philomory** [influxdata/flux#3511]
The [documentation for string interpolation](https://docs.influxdata.com/influxdb/v2.0/reference/flux/language/string-interpolation/) points out that Flux only supports interpolation of string values, and thus you should pass non-string values through the `string()` function. However, it turns out that the `string()` function returns `null` rather than a string when passed a `null` value as an argument.

This is _arguably_ the correct behavior for the `string()` function, insofar as that is the behavior of the other type-converting functions such as `int()` and `duration()`. But, it definitely makes for awkward and cumbersome string interpolation. If you are interpolating a field that may be null, rather than `"Example: ${r.example}"` or `"Example: ${string(v: r.example)}"`, you end up with `"Example: ${if exists r.example then string(v: r.example) else "null"}"` or similar.

This is particularly problematic for the messages associated with Check Rules in InfluxDB; If you have a check rule with a message such as `Disk usage is ${r._level} on host ${r.host}; volume ${r.device} is at ${string(v: r.used_percent)}% capacity.`, then that can suddenly fail if some system is misconfigured and sent in disk usage data without the `device` field. When such a failure occurs, it will entirely prevent the check from executing, at all, for any system, not just the system with the missing tag.

I see five potential solutions to this:

1. Allow interpolation of non-string values (including null values) into strings; null values could be rendered as the empty string, or the text null; anything as long as it doesn't throw an exception.
2. Allow `string()` to return either the empty string or `"null"` when passed a null value as an argument, instead of returning a null value.
3. Keep the current behavior of `string()` as the default, but add an optional boolean second argument, `acceptNull`, which if `true` would make `string()` behave as described in option 2.
4. Leave the `string()` function alone but add a new function (`stringAlways()` or something) that behaves as described in option 2.
5. Leave everything as is, but at least document the `${if exists r.example then string(v: r.example) else "null"}` pattern.

Personally I'd prefer option 1; if not option 1 then any of options 2 through 4 seems about the same; option 5 is my least favorite, but is certainly the easiest.

**Comment by nathanielc** [comment]
Thanks for this thoughtful issue. I also prefer option 1. @Bolladeen  and I were just looking at https://github.com/influxdata/flux/issues/1775 I think it make sense to address this issue shortly after that one.
