### ISSUE TITLE
Count by group

### ISSUE THREAD

**Issue by ademait** [influxdata/flux#3517]
Hello, i'm new using influxDB. I'm using the 1.8 version, which allows querying with flux. To do so I use chronograf.
The data i'm using is from [gharchive](https://www.gharchive.org/), the "Activity for 1/1/2015 @ 3PM UTC" dataset more specifically. This data contain all kinds of event from github repositories, so each row has an identifier (id), and its event type (type). 

What i'm trying to acheive is retrieve all users (actor_id) from the event type "IssueCommentEvent". Then i will have repeated values on the column "actor_id" (once I done the pivot). What I want to compute is for every actor_id, count the number of times is repeated on the column. 
In SQL would be something like: 
`SELECT COUNT(actor_id) FROM IssueCommentEvent GROUP BY actor_id`

I'm also a bit lost about the meaning of the column table from the raw data output. I know that has an index and groups the data for the column I specify, for example if I do _group(columns: ["actor_id"])_ I will have an index for every actor_id, and those who have the same actor_id will have the same index. Could this help me with the query I want?

PS: I looked for this kind of issue and I didn't found nothing related, so I opened this issue

**Comment by jsternberg** [comment]
This depends on how you are writing it to InfluxDB. How are you taking that data and writing it to InfluxDB?

The general gist of it is:

```
bucket = "mybucket" // bucket where you wrote the data
measurement = "mymeasurement" // measurement where you wrote the data
field = "myfield" // field where you wrote the data
start = 2015-01-01T00:00:00Z // start time of the data
stop = 2015-01-02T00:00:00Z // end time of the data

from(bucket: bucket)
    |> range(start: start, stop: stop)
    |> filter(fn: (r) => r._measurement == measurement and r._field == field)
    |> filter(fn: (r) => true) // sometimes you need to filter by tags, use this to filter by tags or remove this line
    |> group(columns: ["actor_id"])
    |> count()
```

**Comment by ademait** [comment]
Hi, I figured it out. As actor_id was a field, and not a tag, what I did was group by actor_id and then count the column "id", as is an unique value. It was something like this:
``` 
from(bucket: bucket)
    |> range(start: start, stop: stop)
    |> filter(fn: (r) => r._measurement == measurement and r._field == field)
    |> filter(fn: (r) => true) // sometimes you need to filter by tags, use this to filter by tags or remove this line
    |> group(columns: ["actor_id"])
    |> count()
```
