### ISSUE TITLE
`fill()` function often fails when column is all nulls

### ISSUE THREAD

**Issue by philomory** [influxdata/flux#3521]
The `fill()` function exists to replace null values with a given value; however, depending on your source data and the way stuff is grouped, in some tables you may end up with the column being entirely absent, in which case `fill()` throws an error. In order to get reliable behavior, you end up having to use `map(fn: (r) => r with my_column: if exists r.my_column then r.my_column else "foo"}))`, which is _logically_ the same as `fill(column: "my_column", value: "foo")`, but works even if `my_column` happens to be absent entirely for a given table.

As an example of a real query where this becomes an issue, here is a query I wrote as part of a check that would look for (and alert on) task failures:

```flux
from(bucket: "_tasks")
  |> range(start: -10m)
  |> schema.fieldsAsCols()
  |> group(columns: ["taskID"])
  |> fill(column: "errorMessage", value: "(none)")
  |> monitor.check(
    crit: (r) => r.status == "failed",
    messageFn: (r) => (
      if r.status == "failed" then "Task '${r.name}' failed! Error message: ${r.errorMessage}"
      else "Task '${r.name}' succeeded."
    ),
    data: {...},
  )
```

This looks perfectly fine at first glance, but when the check is executed, if any of the tasks had no errors in the past ten minutes, then the table for that task will have no `errorMessage` column, and then `fill()` will fail with `fill column not found: errorMessage`.

**Comment by nathanielc** [comment]
Thanks for this issue, makes a lot of sense for fill to work even if the column doesn't exist.
