### ISSUE TITLE
Add function for extracting scalar values -- a step further than a single record

### ISSUE THREAD

**Issue by samhld** [influxdata/flux#3522]
I came across a case where I wanted to compare the `_value` column value to a static standard deviation.  The stddev value would be unchanged per query execution.  The solution was to either a) set a column with that value repeated or b) calculate the stddev for every row on the fly.  In either case, when using the `stddev()` function, I needed to extract *only* the scalar value of the `_value` column returned by the `stddev()` function.

The solution to this without defining any new functions looks something like:

```
data = from(bucket: "stocks")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "stocks")
  |> filter(fn: (r) => r["_field"] == "askPrice")
  |> filter(fn: (r) => r["symbol"] == "PLTR")

stddev = (data |> stddev(column: "_value", mode: "sample") |> findRecord(fn: (key) => true, idx: 0))._value
mean = (data |> mean() |> findRecord(fn: (key) => true, idx: 0))._value

data
    |> filter(fn: (r) => r._value > mean+(2.0*stddev))
```

The issue here is less that this is difficult to do and more that users coming from most popular programming languages (any that I can think of) would expect to be able to access a single (scalar) value of a record.  Being able to access the primitives of tables is useful.  While the above solution technically works, I imagine it would trip up most users at first. 

The second issue with the above solution is that it repeats the code used to access a scalar value unnecessarily (enter functions!) so, with some help from @sanderson, we have this final solution by replacing:
```
stddev = (data |> stddev(column: "_value", mode: "sample") |> findRecord(fn: (key) => true, idx: 0))._value
mean = (data |> mean() |> findRecord(fn: (key) => true, idx: 0))._value
```

with:
```
getValue = (tables=<-) => (tables |> findRecord(fn: (key) => true, idx: 0))._value

stddev = data |> stddev(column: "_value", mode: "sample") |> getValue()
mean = data |> mean() |> getValue()
```

There are likely many cases where a single scalar value would be used as part of a query.  Having to define this function each time you want to derive a value to be used in the same query seems like an unnecessary obstacle.

**Comment by ayberkozgur** [comment]
Agreed 100%
