### ISSUE TITLE
The contains function may not be optimized

### ISSUE THREAD

**Issue by LieLieLiekey** [influxdata/flux#3546]
### Environment info:
**influxDB version**: 2.0.3

**System info**: from docker
Debain, X86_64, 8-core Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz,  16GB RAM

### Data describe:
**BucketName**: 15day_profile_bucket
**MeasurementName**: function_info
**Tags**: Function, Pid, Tid, ProcessName, UUID, State
**Fields**: Internal, cumulative

there may be  2.4w record and 200 series in 1 minute.
### Problem:
The `contains` function query is very slow, it seems that the group key filter is not used.

The following flux query took 0.63s:

```
from(bucket: "15day_profile_bucket")
|> range(start: 2021-03-03T05:54:39.611Z, stop: 2021-03-03T06:54:39.611Z)
|> filter(fn: (r) => r["_measurement"] == "function_info" )
|> limit(n: 1)
|> filter(fn: (r) => contains(value: r["UUID"], set: ["7f0a1436-37ad-4b7a-9ab1-7acce9ee3060"])  )
|> yield()
```

this is image:
![image](https://user-images.githubusercontent.com/42167339/111055963-1a97c380-84b6-11eb-8d7a-999222401340.png)

but the flux query took 37.88s:
```
from(bucket: "15day_profile_bucket")
|> range(start: 2021-03-03T05:54:39.611Z, stop: 2021-03-03T06:54:39.611Z)
|> filter(fn: (r) => r["_measurement"] == "function_info" )
|> filter(fn: (r) => contains(value: r["UUID"], set: ["7f0a1436-37ad-4b7a-9ab1-7acce9ee3060"])  )
|> limit(n: 1)
|> yield()
```

this is image:

![image](https://user-images.githubusercontent.com/42167339/110574280-cb8d1e00-8197-11eb-86df-96fd8aeae053.png)

### Expected behavior:
The time spent on the two queries differs too much.

Because UUID is a tag field, so the first flux query ( is filter first  then limit), and the second query (is limit first then filter) should no big difference.  

So I guess the `contains` function does not use the group key for filtering, but scans all the data。

### Use Case:

Our team used influxdb-v2, but that is the bottleneck of our project now. 

I have tried to use multiple `or` operations to replace `contains` function,  but when the number of filters is large(70+), the or operation is slower.

**Comment by LieLieLiekey** [comment]
Is there any progress?

**Comment by LieLieLiekey** [comment]
Is there any progress?

**Comment by MarcoPignati** [comment]
Same problem here. ~100x execution time when comparing filter with contains() vs filter with specific UUID. Any progress?

**Comment by alexcolpitts96** [comment]
Any progress? I am not familiar with Go but if somebody points me to the source code I can try to provide a fix.

**Comment by alexcolpitts96** [comment]
Contains function can be found here: [https://github.com/influxdata/flux/blob/master/stdlib/universe/contains.go](https://github.com/influxdata/flux/blob/master/stdlib/universe/contains.go)

contains() does not appear to be the performance bottleneck.

**Comment by LieLieLiekey** [comment]
> Contains function can be found here: https://github.com/influxdata/flux/blob/master/stdlib/universe/contains.go
> 
> contains() does not appear to be the performance bottleneck from an implementation perspective. It is an efficient implementation.

I think it can filter by group key, but it didn’t.  this is the related code : https://github.com/influxdata/flux/blob/master/stdlib/universe/filter.go#L179

**Comment by alexcolpitts96** [comment]
I am glad that it isn't a coincidence that the following improved performance significantly. My query went from 30s to 20s. This is still almost 100x slower than a query without contains in the filter.
`|> group(columns: ["col"], mode:"by")`
`|> filter(fn: (r) => contains(value: r["col"], set: ["col_val1", "col_val2"]))`

**Comment by kmecpp** [comment]
How did you work around the issue @alexcolpitts96 ?
