### ISSUE TITLE
Delete ast/format.go and ast/format_test.go

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#3554]
This issue is about actually deleting the Go formatter code once it is no longer used.

**Comment by skartikey** [comment]
currently ast formatter references are present in the following files - 

https://github.com/influxdata/flux/blob/1a84fac74554ebb7bd1674c8671ec96049de0055/dependencies/influxdb/http.go#L263
https://github.com/influxdata/flux/blob/1a84fac74554ebb7bd1674c8671ec96049de0055/internal/cmd/refactortests/cmd/refactortests.go#L92
https://github.com/influxdata/flux/blob/1a84fac74554ebb7bd1674c8671ec96049de0055/internal/cmd/test_rewriter/main.go#L96
https://github.com/influxdata/flux/blob/1a84fac74554ebb7bd1674c8671ec96049de0055/stdlib/influxdata/influxdb/source.go#L164
https://github.com/influxdata/flux/blob/1a84fac74554ebb7bd1674c8671ec96049de0055/internal/cmd/test_rewriter/add_measurement.go#L71
