### ISSUE TITLE
Acceptance test output is not easily consumable

### ISSUE THREAD

**Issue by rockstar** [influxdata/flux#3560]
When we first created the flux acceptance tests, we left the test failure output to be the bare minimum to be helpful at all, which currently ends up being akin to `fmt.Printf("%s", tableResultingFromTestingDotDiff)`. That's neither easily consumable nor helpful when trying to deliver tests quickly.

Flux needs a much better test failure output format, as that's really the most important test output by a large margin.

**Comment by fchikwekwe** [comment]
Showing both the `want` and the `got` as part of the diff would make the test result easier to consume as well.

**Comment by fchikwekwe** [comment]
Also, the group key is not displayed as part of the stringified table that is shown in the diff. This makes it hard to understand why the tests are failing when looking at the output because the table data might be correct, but the group key might not be.
