### ISSUE TITLE
fluxtest: allow returning multiple results for a test case

### ISSUE THREAD

**Issue by danxmoran** [influxdata/flux#3579]
Similar to how `testing.T` allows for nesting sub-tests, it'd be nice if the interface for `TestExecutor` allowed for a single test run to produce multiple results. For example:
```
type testResult struct {
  err error
  // Maybe a byte buffer for error output / logs in here too?
}

type TestExecutor interface {
  Run(pkg *ast.Package) []testResult
  io.Closer
}
```

Our use-case is e2e testing in InfluxDB 1.x. The `inmem` index is still supported there, so we'd like to run each flux e2e test against both it and `tsi1`. We can do that now, but we can't report the pass/fail conditions of each separately.

**Comment by rockstar** [comment]
The direction we're going, we won't be supporting returning results at all in the near future, but rather asserting things about the results *within* the test case itself. I wouldn't rely too much on the results returned. The heuristic here is that, outside of bootstrapping the environment, if you have to use go for testing, the abstraction is too leaky. In your case, the executor should be in charge of bootstrapping environments with both indexes, and then execute the flux scripts on both of them.

**Comment by rockstar** [comment]
Closing this, as the intent is to have the executor handle test execution. In addition, the plan for acceptance tests is to not have them return results at all in the future.
