### ISSUE TITLE
flux SLIMIT support

### ISSUE THREAD

**Issue by SadSadko** [influxdata/flux#3587]
Hey all,
I'm trying to migrate some of my queries from **influxQL** to **Flux**, however, it seems like there is no current support for the "SLIMIT" operation using Flux, only "limit()".
I didn't saw any open requests about it, is it even prioritized? 
I couldn't find any workaround, it seems like we have no control over the series limit per query. and it's very useful (at least for me).
and lastly, I uploaded a heartbreaking image from influx documentation :(

![image](https://user-images.githubusercontent.com/81636942/113013670-92d3d980-9184-11eb-848e-0d6d94c2d183.png)

**Comment by timhallinflux** [comment]
can you describe how you use this in a bit more detail?  For example, are you programmatically wanting to limit the number of series?  or is this something that you are doing via interactive queries?  Just would like to understand the value of this a bit further.

**Comment by SadSadko** [comment]
understandable, I'm saving business metrics using InfluxDB and built a rest API to query from my DB.
in order to have control over the amount of data I return in my queries, I need this feature, since as I mentioned  "limit()" function can result in an unexpected amount of data.
if I am using the limit(n:100) and have 1000 series with 100 records each, I will return 1000 * 100 instead of the 100 that I need.

hopefully, I am clear, to sum it up, I need it to control the exact amount of data I return.

**Comment by nathanielc** [comment]
@SadSadko would using a `group() |> limit()` to reduce the series down into a single table work? You would loose the series information but would have control over the data returned. Curious if this workaround would be sufficient for you?

**Comment by SadSadko** [comment]
I already thought about using the empty "group()" function but unfortunately it's not enough, because like you said I'm losing the series information and cannot regroup after the "limit()" by columns, because using group() prevent that due to losing series information.

**Comment by SadSadko** [comment]
The best alternative I see is iterating through the flux tables I get, sum the number of records, and stop once I reach the limit.
it will probably be more efficient than ungrouping using flux, "group()" and then group by the required columns using code.

**Comment by SadSadko** [comment]
So there is no way I can limit the amount of data I'm querying without sacrificing column grouping?
If I'm not limiting the amount of quried data when exposing rest api Im risking in DDOS vulnerability.

**Comment by nathanielc** [comment]
You could group the data apply the limit and then group the data again back out something like `group() |> limit()|> group(columns:[...])`. That will work if you know the columns on which to group.
