### ISSUE TITLE
Create void transformation that consumes data and does nothing with it

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#3592]
For testing purposes it is nice to have a transformation that consumes data and does nothing with it, not even pass it down to the next transformation.

Perhaps adding a builtin called `void` to the `debug` package would be a good place for this?

Type:

```
// type signature is that its identify function, except that at runtime no data is ever returned
void : (<-tables: [A]) => [A] where A: Record
// implementation is filter false, use planner rule to use actual void transformation under the hood
void = (tables=<-) => tables |> filter(fn: (r) => false)
```

Possible other names:

* drain
* consume
* sink
* dev/null

DOD

- void Flux function defined in pure Flux
- void planner rule to rewrite void function into void transformation implementation
- void transformation exists
- Tests show is consumes data but does not pass it on
- Flux acceptance tests shows that the planner rule is applied

**Comment by jsternberg** [comment]
There's now a `debug.sink()` in #3643 that can be used for this. I forgot this issue existed and I forgot about the planner rule. I needed it for some performance testing and thought it would just be good to get it merged since I had to do it anyway.
