### ISSUE TITLE
contrib/anaisdg/anomalydetection and timestamp grouping

### ISSUE THREAD

**Issue by uprox** [influxdata/flux#3619]
Hi all,
I'm trying to use MAD anomalydetection from contrib/anaisdg/anomalydetection, but it doesn't work for my time serie.
I guess it's related to grouping by timestamp: if you group data by time, and after that you calculate median on grouped table, you obtain (I obtained) a new table grouped at the same way as the first one where median value is equals to data value for all record. So the diff will be always 0.

Sorry... but I can't understand how to use the MAD.
Can you help me, please?

At the following link you can find my time serie:
https://github.com/uprox/influx/blob/aea20c222f4eeea9111a34bde6bf3cc58d765d34/DATA.CSV

**Comment by varna9000** [comment]
Doesn't seem to work for me either. I can't see neither anomaly nor normal series and I'm following the example strictly. The query returns 0 even if I just put `|> anomalydetection.mad(threshold: 1.0)` at the end. No errors are returned, just 0 rows.
