### ISSUE TITLE
Acceptance tests don't seem to catch different timestamp

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#3631]
Recently a commit landed on master that had an incorrect timestamp in the expected output for an acceptance test:
https://github.com/influxdata/flux/commit/91fabec6bef70b8714354843930ecee3c779219b#diff-6219efcaaa8418d87ac1f06b26071baf9786e1dd4f9cd6687246fd46b1192ca8R202
The timestamp should have an hour of `00` not `01`.

I plan on fixing this discrepancy in this PR:
https://github.com/influxdata/flux/pull/3630

However, I verified that with the discrepancy in place, the test still passed when I ran it locally, and seems to sometimes pass in CI. It failed here:
https://app.circleci.com/pipelines/github/influxdata/flux/8968/workflows/e7d350b6-f390-43c8-9b0b-032a28c2a87f/jobs/25323
But it passed here:
https://app.circleci.com/pipelines/github/influxdata/flux/8967/workflows/8d2479b9-f5e9-461b-af3f-88bbd4b7cecd/jobs/25318

Steps to reproduce:
- Make the timestamp change described above, that is, make the inverse of this change:
  - https://github.com/influxdata/flux/pull/3630/files#diff-161f1c8e8bb64b2aa78662e9fc81e37bafb18780279040193990be52c768899fL276-L278
- Run the acceptance tests via `make test-flux`
- Test will pass even though expected output is wrong

**Comment by skartikey** [comment]
This looks like a flaky test to me. I tried running the test from CLI and observed that the test fails(expected behavior) if I run it 5-6 times in a row. 

![image](https://user-images.githubusercontent.com/1942366/119687525-310bb500-be3f-11eb-84a6-b7a70b05423b.png)
