### ISSUE TITLE
Formatting: comments shouldn't get indented, tab inside comments should be preserved 

### ISSUE THREAD

**Issue by skartikey** [influxdata/flux#3646]
The formatter is indenting the whitespace inside the comment. Ideally, it should be preserved. Also, the extra space before the last comment line shouldn't be there. 

**Example -** 

**Before -** 
```
// Equivalent TICKscript query:
// stream 
// 	 |eval(lambda: 2 * _value)
//		.as('_newValue')
```

**After format-** 
```
// Equivalent TICKscript query:
// stream 
//  |eval(lambda: 2 * _value)
 //.as('_newValue')
```

**Findings -** Looks like the tabs in the comments are getting removed by the tabwriter #3315 , spaces are getting preserved though. 

**Sample unit test output -** 

```
Diff < left / right > :
<"\n// \t |eval(lambda: 2 * _value)\n//\t\t.as(\'_newValue\')"
>"\n//  |eval(lambda: 2 * _value)\n //.as(\'_newValue\')"
```

DOD:

 - Add tests that show tabs are preserved in comments and string literals
 - Remove the TabWriter

**Comment by nathanielc** [comment]
Does this mean that tabs inside string literals are also being removed?

**Comment by nathanielc** [comment]
After some discussion we think its best to remove the TabWriter from the formatter implementation since it is producing incorrect results. We can revisit how to vertically align code in Flux at a later time.
