### ISSUE TITLE
Design std lib for Flux

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#365]
Once we have namespaces we can organize the built in code into various standard packages.

There are many existing issues that refer to placing code into a namespace. Please link them here so we can design out the entire stdlib.

**Comment by wolffcm** [comment]
Existing issues that reference namespaces:
Support Scalar expressions: https://github.com/influxdata/flux/issues/332
Testing framework: https://github.com/influxdata/flux/issues/107

**Comment by wolffcm** [comment]
Some more proposed functions:

LoadLocation function: https://github.com/influxdata/flux/issues/157
Fixed Zone: https://github.com/influxdata/flux/issues/156
Time and date functions: https://github.com/influxdata/flux/issues/155
Months of the year: https://github.com/influxdata/flux/issues/154
Days of the week: https://github.com/influxdata/flux/issues/153

FromInfluxLP function: https://github.com/influxdata/flux/issues/70
