### ISSUE TITLE
Allow selectors to produce empty rows when used within aggregate window

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#3681]
When an aggregate is used with `aggregateWindow` and `createEmpty` is set to true, which is the default, empty windows are created and then the aggregate produces an empty row with a null value. In the case of count, a row with zero is returned because the number of rows in the input table is zero.

When a selector is used on an empty table, it produces an empty table because there was no row to select. This behavior is expected and the correct behavior for a selector because selectors will select a specific row.

When this is used in combination with the implementation of `aggregateWindow`, the empty windows that were created become lost. This behavior is unexpected.

We should modify the behavior of `aggregateWindow` to always ensure that the function produces at least one row when create empty is used. This will allow create empty to produce an empty row which will then allow fill to work properly.

**Comment by MarcoPignati** [comment]
I did not get what was the final decision on this. Is the approach suggested by @jsternberg going to be implemented finally? Thanks.

**Comment by jsternberg** [comment]
@MarcoPignati this was implemented in #3733. I forgot to link it when merging.
