### ISSUE TITLE
Rust installation needs more security verification

### ISSUE THREAD

**Issue by rockstar** [influxdata/flux#3721]
In our docker image build, we do a `curl | sh`. We want to avoid that, as it has all sorts of security implications. We'd like something that doesn't require us to manually update any time there is a new release of rust and/or rustup. There is prelim work [here](https://github.com/influxdata/flux/pull/3710) but it is prudent to have our team weigh in on a number of other options and explore ways that we can accomplish this.

DOD:
  - rust is installed without using `curl | sh` in the process.

**Comment by nathanielc** [comment]
There are a few ways to accomplish this:

* Install Rustup in a trusted way: download the binary directly and verify its contents, do so in such a way we can update the Rustup version easily as part of the Docker file. Install Rustup via a package manager 
* Install Rust directly from the signed tarballs hosted by the Rust team. If we do this we loose the ability to easily cross compile so we would need to find another way to install the cross compilation targets as well.

**Comment by pierwill** [comment]
Thanks to https://github.com/influxdata/flux/commit/a4804cf091e8ea225b4aa5a9dd8245edfcfe4658, we now use a Rust Docker image. For future reference, here is the upstream code showing that the Rust docker images do indeed verify checksums:

https://github.com/rust-lang/docker-rust/blob/77e77508828ca2da1a9b7582d079b2d77f8b9a1a/1.52.1/buster/Dockerfile#L10-L19
