### ISSUE TITLE
Add trailing comma support to the grammar

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#374]
Flux should support trailing commas. Update the grammar and parser to support them in all places that commas appear.

**Comment by jsternberg** [comment]
Do you have a specific place this doesn't exist? I think this is already in the grammar.

**Comment by nathanielc** [comment]
Example using ArrayLiteral, the current grammar:

    ArrayLiteral = lbrack ExpressionList rbrack .
    ExpressionList = [ Expression { comma Expression } ] .

Should be:

    ArrayLiteral = lbrack ExpressionList { comma } rbrack .
    ExpressionList = [ Expression { comma Expression } ] .
