### ISSUE TITLE
Support regex flags with regexp types

### ISSUE THREAD

**Issue by sanderson** [influxdata/flux#3741]
Currently regular expressions in Flux do not support Go regexp modifier flags. The following flags are supported in the Go regexp package:

| Flag | Description                                                                                 |
| :--- | :------------------------------------------------------------------------------------------ |
| i    | case-insensitive (default false)                                                            |
| m    | multi-line mode: ^ and $ match begin/end line in addition to begin/end text (default false) |
| s    | let . match \n (default false)                                                              |
| U    | ungreedy: swap meaning of x* and x*?, x+ and x+?, etc (default false)                       |

The `m` flag probably doesn't provide a lot of value in Flux, but the others may.

## Proposal
Introduce support for regexp flags in Flux. Regular expressions are used primarily in predicate expressions and `regexp` package functions. I think we could introduce this functionality in a few ways:

- Support Go regexp flag syntax
- Add a flag parameter to regexp.compile
- Create a unique flag syntax for Flux regular expressions

### Support Go regexp flag syntax
In Go regular expressions, flags are passed at the beginning of the pattern. We could support the following regexp syntax in Flux:

```javascript
// ...
  |> filter(fn: (r) => r._field =~ /($i)foo/ )
```

### Add a flag parameter to regexp.compile
We could also add a `flag` parameter that compiles a string into a `regexp` with the necessary modifier flags:

```javascript
import "regexp"

// flags as an array of strings
pattern = regexp.compile(v: "foo", flags: ["i", "s"])

// OR flags as a string
pattern = regexp.compile(v: "foo", flags: "is"])

// ...
  |> filter(fn: (r) => r._field =~ pattern )
```

### Create a unique flag syntax for Flux regular expressions
We could introduce a Flux-specific syntax for flags. Something like:

```javascript
// ...
  |> filter(fn: (r) => r._field =~ /foo/:is )
```

**Comment by nathanielc** [comment]
I was looking that to see what the work involved is and it turns out you can already specify the flags are they are inside the regexp for Go. See these examples:

```
> regexp.matchRegexpString(r:/(?i)hello/, v:"HELLO")
true
> regexp.matchRegexpString(r:/hello/, v:"HELLO")
false
```

Perhaps all we need to is to make this more clear in our documentation?

**Comment by sanderson** [comment]
Nice! I should've tested more. So it looks like if you want to use regexp flags, you have to use the `regex` package.

**My original test:**
```javascript
from(bucket: "default")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "mem")
  |> filter(fn: (r) =>  r._field =~ /($i)available/ )
```

This didn't return any results, however, both of the following do:

```javascript
import "regexp"

from(bucket: "default")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "mem")
  |> filter(fn: (r) =>  regexp.matchRegexpString(r: regex, v: r["_field"]) )
```

```javascript
import "regexp"

regex = regexp.compile(v: "(?i)available")

from(bucket: "default")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "mem")
  |> filter(fn: (r) =>  r._field =~ regex )
```

What are the chances that we could make these flags work in predicate function comparisons without the regexp package (ie `something =~ /($i)something`? It's not a huge deal if we can't, I just need to document how to use them.
