### ISSUE TITLE
Parse error in fieldsAsCols query

### ISSUE THREAD

**Issue by junior173** [influxdata/flux#3750]
Hi,  I Want to add two fields (maybe more) from the same line protocol entry. My fields contain some special characters. 

test_bank,host=11A be-prt.read_A1-FC03_(KB/s)=6.0,be-prt.read_A1-FC02_(KB/s)=1.2 ,be-prt.read_A1-FC01_(KB/s)=3.2,be-prt.read_A1-FC00_(KB/s)=9.6 1613926551

All is okay with standard Queries (mean values)
```
from(bucket: "PERFORMANCE_BUCKET")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "Demo")
  |> filter(fn: (r) => r["_field"] == "be-prt.read_A1-FC00_(KB/s)" or r["_field"] == "be-prt.read_A1-FC01_(KB/s)")
  |> filter(fn: (r) => r["host"] == "11A")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")
```
I have problems when i try to add both fields (by injecting schema.fieldsAsCols() and map)
```
import "influxdata/influxdb/schema"
from(bucket: "PERFORMANCE_BUCKET")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "Demo")
  |> filter(fn: (r) => r["_field"] == "be-prt.read_A1-FC00_(KB/s)" or r["_field"] == "be-prt.read_A1-FC01_(KB/s)")
  |> filter(fn: (r) => r["host"] == "11A")
  |> schema.fieldsAsCols()
  |> map(fn: (r) => ({ r with sum: r.be-prt.read_A1-FC00_(KB/s) + r.be-prt.read_A1-FC01_(KB/s) }))
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")
```
 compilation failed: error at @8:53-8:95: expected comma in property list, got DIV
I tried a number of escape characters to and tried putting field in [".."] still cant get the fields to add.

**Comment by wolffcm** [comment]
We worked a little bit in the community channel on this issue. We noted that even converting the field to be quoted with `r["..."]` that the query fails with a different error:
```js
import "influxdata/influxdb/schema"
from(bucket: "PERFORMANCE_BUCKET")
|> range(start: v.timeRangeStart, stop: v.timeRangeStop)
|> filter(fn: (r) => r["measurement"] == "Demo")
|> filter(fn: (r) => r["field"] == "be-prt.read_A1-FC00(KB/s)" or r["field"] == "be-prt.read_A1-FC01(KB/s)")
|> filter(fn: (r) => r["host"] == "11A")
|> schema.fieldsAsCols()
|> map(fn: (r) => ({ r with sum: r["be-prt.read_A1-FC00(KB/s)"] + r["be-prt.read_A1-FC01_(KB/s)"] }))
|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
|> yield(name: "mean")
```
Yields the error:
```
compilation failed: error at @6:6-8:25: expected RPAREN, got EOF
```

**Comment by junior173** [comment]
Thanks to Chris, it seems using rename and using pivot helps. Underscores work fine but the use of . and - and / cause a problem. 

from(bucket: "PERFORMANCE_BUCKET")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "new")
  |> filter(fn: (r) => r["_field"] == "be-prt.read_A1-FC00_(KB/s)" or r["_field"] == "be-prt.read_A1-FC01_(KB/s)" or r["_field"] == "be-prt.read_A1-FC02_(KB/s)" or r["_field"] == "be-prt.read_A1-FC03_(KB/s)")
   |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
  |> rename(columns: {"be-prt.read_A1-FC00_(KB/s)": "be_prt_A1_FC00_KB_s", "be-prt.read_A1-FC01_(KB/s)": "a1fc01","be-prt.read_A1-FC02_(KB/s)": "be_prt_A1_FC02_KB_s","be-prt.read_A1-FC03_(KB/s)": "be_prt_A1_FC03_KB_s"})
  |> map(fn: (r) => ({ r with _value: r.be_prt_A1_FC00_KB_s + r.a1fc01 + r.be_prt_A1_FC02_KB_s + r.be_prt_A1_FC03_KB_s }))
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")

**Comment by wolffcm** [comment]
Note: this issue appeared in OSS Version 2.0.5 deployed as a container.

**Comment by nathanielc** [comment]
We think this is only reproducible in the UI because the query from https://github.com/influxdata/flux/issues/3750#issuecomment-846029653 parsers correctly on the REPL and in vim+flux-lsp-cli. Maybe this has to do with how the UI injects options?
