### ISSUE TITLE
Update MemberExpression to accept string literals

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#376]
The MemberExpression is specified as 

    MemberExpression        = DotExpression  | MemberBracketExpression
    DotExpression           = "." identifer
    MemberBracketExpression = "[" string_lit "]" .

The current implementation only supports the `.` syntax.

See #375 as the MemberExpression grammar was changed in that PR.

**Comment by jsternberg** [comment]
This is covered by the IndexExpression rule in the new grammar. We can modify the original ebnf, but it's likely good to keep the modified ebnf the same to keep it LL(1).
