### ISSUE TITLE
Generate Flux documentation from stdlib comments

### ISSUE THREAD

**Issue by scbrickley** [influxdata/flux#3761]
We want to accomplish two things:
1. Have a single source of authority for the Flux standard library documentation
2. Keep those docs up to date across all consumers

Right now the docs are hosted here: https://github.com/influxdata/docs-v2

The goal for this epic is to migrate the stdlib docs from that repo to the standard library source code, in the form of comments, and to create a tool/module that parses those comments and exports them in a format that is easily consumable by the docs site, the UI, the LSP, and anyone else that might use them.

Once we have the capability to generate the docs from flux doc comments, we should integrate that into the build process for the flux crate, and find a way to export the new docs so that the sidebar in the UI text editor is always using the latest version of the docs.

Once this epic is closed, there will be a new epic to integrate the new docs into the LSP.

DOD:
- We have a documented standard for writing flux doc comments
- All of the flux standard library is documented with the new doc comments
- We have a tool that converts flux doc comments to json
- We support both short and long-form docs
- Side panel in the UI is populated with short form docs

**Comment by scbrickley** [comment]
Some questions that came out of the working group on this:

- Do we need a special comment token?
no, comments before builtins, assignments, and package clauses will be the only ones that become doc comments

- How do we document the return value of a function?
unanswered

- How do we handle examples?
Maybe examples could become executable flux

- How do we handle tables?
If examples change to executable flux scripts, we probably won't need tables

- How do we integrate into the UI?
generate a json file and commit to ui repo
Create a tool that can be compiled to WASM and imported to the UI that spits out whatever docs we need

**Comment by russorat** [comment]
Any idea if this issue could be implemented using this capability: https://github.com/influxdata/ui/issues/2241

would it be possible to add if the function accepts a pipe or not to the json file contributed to the UI repo?
