### ISSUE TITLE
 Day range error seen in the results

### ISSUE THREAD

**Issue by cybang77** [influxdata/flux#3764]
There is a range in which the resulting time exceeds 24 hours.

![image](https://user-images.githubusercontent.com/33340094/119781460-033d7380-bf06-11eb-9c34-a4f6f167caeb.png)

**Comment by timhallinflux** [comment]
What version/edition of InfluxDB are you using?  2.0.x? or Cloud? 
How was the data ingested?

If you remove the time shift, does the data appear correctly?

**Comment by cybang77** [comment]
I am using influxdb2-2.0.4-amd64.deb.
I send data to kafaka and then telegraf collects it and stores it in influxdb.

I do not know exactly because the environment at the time of the question is different, but it seems that the problem was not found when not in use time shift.

It seems like a time shift problem.
