### ISSUE TITLE
Wrong calculation of weekly aggregation

### ISSUE THREAD

**Issue by cybang77** [influxdata/flux#3765]
The result of my daily aggregation is shown in the picture below.
![image](https://user-images.githubusercontent.com/33340094/119781915-878ff680-bf06-11eb-903a-7a4497fc5dcc.png)

I started saving data from May 24th.
When I run a query aggregateWindow(every: 1w, fn: count, createEmpty: false)', Isn't the result supposed to represent **1 result** value from the 24th to today (27th)?

Why do they show 2 results?
![image](https://user-images.githubusercontent.com/33340094/119782593-56fc8c80-bf07-11eb-8657-0e08e158befb.png)

**Comment by redbaron** [comment]
It is because it first calculates windows on a week boundary, then check which data points fall into each window. In other words, window don't start where your first data point starts.
