### ISSUE TITLE
Create a module that can generate JSON from doc comments in flux stdlib

### ISSUE THREAD

**Issue by scbrickley** [influxdata/flux#3772]
In order to make the new flux docs easy to consume, we should write a module that parses the standard library, extracts doc comments, and outputs them in a standardized JSON structure. This way, consumers of the docs can parse the JSON and pick out whatever portion of the docs they need.

This module should be written in rust, and should live in `libflux` in the `flux` crate.

We should be able to compile this module to web assembly so that it can be imported by the the LSP and the UI.

DOD:
- A Rust module exists that scans stdlib Flux sources and produces a JSON file containing doc comments for each packages, options, functions and constants.
- Unit tests for the module

**Comment by wolffcm** [comment]
Let's defer sizing this until we have a definite spec for doc comments, which is issue #3770.

**Comment by jsternberg** [comment]
One comment about the output JSON format. We should avoid creating JSON like `{"functionName":"doc text"}` and instead opt for something like `{"functionName":{"body":"doc text","format":"markdown"}}`. I think it's also reasonable to have the output be something like:

```
[
    {
        "name": "aggregateWindow",
        "doc": {
            "body": "doc text",
            "format": "markdown"
        }
    }
]
```

**Comment by scbrickley** [comment]
Closing in favor of #3780, #3781, #3782, and #3783
