### ISSUE TITLE
Include bytes from fluxdoc json data in flux crate

### ISSUE THREAD

**Issue by scbrickley** [influxdata/flux#3781]
Once the `semantic::bootstrap::stdlib_docs()` function described in #3780 is added, we will want to call it in `build.rs` so that we can serialize the doc structures into JSON, and write it to a file called `docs.json`

Then we can add a call to the `include_bytes!` macro that references `docs.json` in `flux/lib.rs` (we do something similar with the standard library [here](https://github.com/influxdata/flux/blob/8018bdce94cb59851550f130e643aa9f1bafd107/libflux/flux/src/lib.rs#L35-L38))

DOD:
- `docs.json` is generated as part of the build process for the `flux` crate
- We call `include_bytes!` on that file in `flux/lib.rs`
- We have a test that shows that docs from a specific package are present in the included bytes (we can use the csv package for this)

**Comment by BarWeiner1** [comment]
Implemented with PR #3808
