### ISSUE TITLE
Parser is committing to function literal too soon

### ISSUE THREAD

**Issue by adrian-thurston** [influxdata/flux#3788]
The following flux script:

```
base = from(bucket: "thurston")
    |> range( start: 0 )

( 
        if check then
            base |> filter( fn: (r) => (r._measurement == "cpu" ))
        else
            base
    )
    |> group()
    |> count()
```

Results in the parse error `Error: Compilation failed: error at @7:3-11:2: unexpected token for property key: IF (if).`

The parser is considering that the opening `(` is beginning the function parameters of a function literal. When it turns out to not be the case, it is throwing an error. Instead it needs to backtrack to begin to consider a parameterized expression in primary expression.

**Comment by nathanielc** [comment]
I ran into something similar today as well:

```
f = (t=<-) => t()
(() => 1) |> f()
```

That fails to parse with the error:

```
Error: error at @2:2-2:9: unexpected token for property key: LPAREN (()
```
