### ISSUE TITLE
Reject constant division by zero

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/flux#38]
Currently, calling `flux.Compile` with a query string of `0/0` panics due to a Go runtime division by zero error. I have an incoming PR to return NaN in the float case, but the integer case for now will just return zero.

It would probably be better to reject the query altogether if we detect a constant division by zero, but the signature `type BinaryFunction func(l, r Value) Value` does not allow returning an error. I think the long-term solution here is to change `BinaryFunction` to return `(Value, error)` so that we can reject this (and other unforeseen error cases) at compile time.

**Comment by russorat** [comment]
we do this now. for example, the query: 
```
from(bucket:"telegraf") 
|> range (start: -1m)
|> filter(fn: (r) => r._measurement == "cpu")
  |> map(fn: (r) => ({ r with _value: r._value / 0.0 }))
```

returns the error `failed to evaluate map function: cannot divide by zero`
