### ISSUE TITLE
Hex conversion functions

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/flux#3817]
There has been a flurry of requests in the past couple of weeks about users looking for Flux functions that would convert values to and from Hex.

Is this something that can be done with the existing math function library? or are there additional elements required?

**Comment by timhallinflux** [comment]
do we extend the existing toString() and toInt() functions to include an optional base/format parameter?  This would preserve the existing functionality, but allow for future extensibility if other bases or formats are requested.

Alternatively, we could create new/separate functions entirely.   This probably needs some design discussion.

**Comment by sranka** [comment]
The conversion functions are now defined in

  * https://github.com/influxdata/flux/blob/master/stdlib/universe/typeconv.go 
  * https://github.com/influxdata/flux/blob/master/stdlib/universe/universe.flux#L414

The best and the simplest option (from my POV) would be to enhance conversion functions (int, uint, string, toInt, toUInt, toString)  to accept an optional **base** parameter (10 by default, 2 <= base <= 36). This is IMHO a quite simple change in the code. @timhallinflux Can you please invite a flux authority to approve this change of the core flux library?  

Alternatively, a new contrib package `"contrib/bonitoo-io/hex"` can be created with functions
   * `hex.int(v: string)`, hex.toInt(tables=<-)  
   * `hex.uint(v: string)`, hex.toUInt(tables=<-)  
   * `hex.string(v: int)`, hex.toString(tables=<-)  
The implementation would then copy most of the code from the universe library with a few changes, it is IMHO better to avoid such duplication.

**Comment by timhallinflux** [comment]
@nathanielc looking for your review of this proposed solution.  If get your agreement... @sranka  will move forward with the implementation.

**Comment by nathanielc** [comment]
Let's move forward with adding a new `hex` package. I am less concerned about how it gets implemented and more concerned with the API we present to Flux users. A `hex` package is much more discoverable and easy to document compared to adding a new argument to the existing functions. 

Do users need to parse hex numbers that start with `0x` or will the number need to a plain hex value without a prefix?

**Comment by sranka** [comment]
Thank you for your quick reaction. The parsing functions will skip `0x` prefix automatically when present. The string functions will always return a value without a prefix.

**Comment by timhallinflux** [comment]
It sounds like in this case, the user does NOT have the numbers prefixed with 0x.  I'm assuming we have to account for both cases.

**Comment by timhallinflux** [comment]
PR ready for review.
