### ISSUE TITLE
Add dynamic per-row parameterization to mqtt.to()

### ISSUE THREAD

**Issue by samhld** [influxdata/flux#3825]
To elaborate on this possibly confusing title, the world that uses MQTT as a data transfer protocol uses it as a dynamic pub/sub tool.  By "dynamic" I mean their clients will probably need to be able to publish/subscribe to different topics dynamically.  The way `mqtt.to()` currently works is it writes out all input table data to the same topic.  This may satisfy some use cases but it likely won't satisfy most.

A common use case for MQTT is to have clients (usually devices) publish to their own respective topics...sometimes granular to the point of having their own topics dedicated to each metric/property they publish.  For example:

device01 PUBLISH'es:
`temperature=45.0 <ts>` to topic: `/device01/temperature`
`pressure=10.0 <ts>` to topic: `/device01/temperature`
device02 PUBLISH'es:
`temperature=25.0 <ts>` to topic `/device02/temperature`
`pressure=11.0 <ts>` to topic: `/device02/pressure`

Each device may also `SUBSCRIBE` to topics that are on-going averages of these metrics over time:
device01 SUBSCRIBE to `/processed/device01/temperature/average`
device01 SUBSCRIBE to `/processed/device01/pressure/average`
device02 SUBSCRIBE to `/processed/device02/temperature/average`
device02 SUBSCRIBE to `/processed/device02/pressure/average`

Unless we want a separate Flux Task running for every topic, a single Flux Task should be able to "fan out" writes to all respective topics.

**What I've tried**
Creating my own wrapper function to have `mqtt.to()` called per row of my resulting stream of tables:
```
import "experimental/mqtt"
import "array"
import "strings"

genTopic = (source_name, source_measurement) =>
  strings.joinStr(arr: ["/processed", source_name, source_measurement, "average"], v: "/")
 
toMQTT = (tables=<-, broker) =>
  tables
    |> map(fn: (r) => { 
                        mqtt.to(tables: array.from(rows: [r]), 
                                broker: broker, 
                                topic: genTopic(source_name: r.host, source_measurement: r._measurement)) 
                        return r
                        } )
 
broker = "broker:1883"
 
from(bucket: "mqtt")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> filter(fn: (r) => r["_field"] == "usage_user" or r["_field"] == "usage_system")
  |> filter(fn: (r) => r["cpu"] == "cpu-total")
  |> mean()
  |> toMQTT(broker: broker)
```

Even wrapping in a function to be called synchronously doesn't work, however:
```
runtime error @9:8-14:28: map: cannot compile @ 9:16-14:26: statement does nothing, side effects are not supported by the compiler
```

`topic` may also not be the only parameter that needs to be dynamic.  It's possible `message` will need to be as well.  I haven't tried to parameterize `message` yet so I don't know if work needs to be done there.  However, the case for it being dynamic is that the default `message` value is the the data passed to `mqtt.to()` which will end up being written out as Line Protocol.  Line Protocol will have redundant information with information that will likely already be in `topic` name/s.  For a cleaner `SUBSCRIBE` experience (and less data written overall), a user might want to, say, trim down the `message` output to be just a value and a timestamp.

**Comment by Vitaljok** [comment]
+1 for this feature... 

Also according to source code (https://github.com/influxdata/flux/blob/master/stdlib/experimental/mqtt/to.go#L474)
If the topic is not specified, it is being dynamically generated from the `_measurement` and `tag=value` pairs.
However there is no way to control the format and the order of the topic parts.
