### ISSUE TITLE
Implement rule to convert `filter` to `range` when possible

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#385]
If a user enters a query like
```
from(bucket: "telegraf") |> filter(fn: (r) => r._time >= now() - 1h)
```
It will fail planning because there is no range to push down.  However, the filter is semantically equivalent to a range and should be rewritten as such:
```
from(bucket: "telegraf") |> range(start: -1h)
```
The rule should be made to handle reasonable expressions using relational operators and the `_time` column.

This would be a logical rule defined in `filter.go`.

**Comment by nathanielc** [comment]
Note, that currently the binary operators like `==` and `>=` are not defined for `time` values. This will need to address that.

**Comment by wolffcm** [comment]
`range` will create `_start` and `_stop` columns, and `filter` does not.  Should the rule also generate a  `drop` node to drop these columns?
