### ISSUE TITLE
Populate the description field of the Doc structs

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#3850]
Once #3783 is done we need to add logic to parse the markdown to separate the headliner from the description.

We should use this markdown parser https://docs.rs/crate/pulldown-cmark/0.8.0 to parse the comment string as markdown. 

The headliners is defined as the first paragraph in the doc comment. The description is defined as the remaining content in the doc comment.

DOD:

- The doc structs correctly separate the headliner from the description.
- Tests exist that show we can parse headliners and description comments correctly.

**Comment by BarWeiner1** [comment]
The parser does not produce AST, so we must give it a function for what it should do with .iter . Find the start headline and break after first paragraph.
