### ISSUE TITLE
math.atan2 parameters swapped

### ISSUE THREAD

**Issue by frantp** [influxdata/flux#3854]
The parameters for `math.atan2` seem to be swapped. Following the snipped from [the documetation](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/math/atan2/), if I use the function like this:
```
import "math"

math.atan2(y: 1.22, x: 3.14)

// Returns 0.3705838802763881
```
my result is `1.2002124465185084`. To obtain `0.3705838802763881` I have to use it this way:
```
math.atan2(x: 1.22, y: 3.14)
```

Version: InfluxDB 2.0.7 (Docker)

**Comment by nathanielc** [comment]
Thanks for reporting this we are fixing it here https://github.com/influxdata/flux/pull/3856
