### ISSUE TITLE
[TimeBox] Research on making testing.diff use a smart diff

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#3879]
I have become accustomed to GNU's `diff` utility on the command line. As such I have unconsciously come to expect similar behavior from Flux's `testing.diff`. For example if I did something like
```js
import "array"
import "testing"

got  = array.from(rows: [{foo: "a", i: 0}, {foo: "b", i: 1}])
want = array.from(rows: [                  {foo: "b", i: 1}])
testing.diff(got, want)
```
It might yield the result:
```
Result: _result
Table: keys: []
          _diff:string              foo:string                       i:int
----------------------  ----------------------  --------------------------
                     -                       b                           1
                     +                       a                           0
                     +                       b                           1
```
In other words, it doesn't yield the minimal diff. This can feel like a "gotcha" if you want to, say, assert that a row appears inside of a set of other rows (diff lines should only be `-` in that case)

DOD:
- Find an algorithm, or even better an implementation that we can use
- Write issues to do the work to make our diff smart

**Comment by jsternberg** [comment]
The common diff algorithm name is [longest common subsequence](https://en.wikipedia.org/wiki/Longest_common_subsequence_problem). This issue will likely be translating rows into something consumable by an implementation of this algorithm.

**Comment by jsternberg** [comment]
A possible Go version? https://github.com/yudai/golcs.

It might be better if we write our own though so we don't add another dependency. There's also some precedent in the flux codebase for turning a row into a string [here](https://github.com/influxdata/flux/blob/a768568a4cbeb299433ee31a059e599d290fcfbf/internal/execute/groupkey/groupkey.go#L105-L155). This implementation is used to compute a hash which can be used to speed things up, but it also produces a unique string.
