### ISSUE TITLE
Update `ColListTableBuilder` to produce compressed columns for string group keys

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#3892]
Update the `ColListTableBuilder` to produce compressed columns (value + column length) when building a group key column that has type `string`.

For reference, `ColListTableBuilder` code is here:
https://github.com/influxdata/flux/blob/0cf686237b50b6e89a457c1523ca66cb04bac303/execute/table.go#L516

This change should have the effect of making it so that transformations that use the `ColListTableBuilder` to produce data use less memory and run faster.

Specifically, update `stringColumnBuilder` to have logic to make the optimization of using single-value+length if all the values that are appended to the column are the same.

Location of `stringColumnBuilder`:
https://github.com/influxdata/flux/blob/0cf686237b50b6e89a457c1523ca66cb04bac303/execute/table.go#L1843

DOD:
- `ColListTableBuilder` creates compressed columns for strings that are all the same value
- Unit tests demonstrate that the above bullet point is true

**Comment by jsternberg** [comment]
Closing in favor of #3920.
