### ISSUE TITLE
Update group transformation to use GroupTransformation

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#3937]
Update the `group()` transformation to use [GroupTransformation](https://github.com/influxdata/flux/issues/3928).

The `group()` transformation presently uses the buffered builder to construct the individual chunks from the upstream table to a single downstream table. This transformation should be adapted to use `GroupTransformation`. The primary difference between these two is that `group()` will group the single table chunk and then immediately send it to be processed by the downstream transformations instead of using buffered builder. This should involve the following steps:

1. Remove the builder cache from the group transformation.
2. Instead of `appendTable`, the chunks should be sent with the `Process()` method from the `TransportDataset`.

**Comment by scbrickley** [comment]
Closed with #4035
