### ISSUE TITLE
Update fill transformation to use NarrowTransformation

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#3938]
Update the `fill()` transformation to use [NarrowTransformation](https://github.com/influxdata/flux/issues/3927).

The `fill()` transformation presently uses `table.Stream()` to stream tables to the downstream. The transformation should be adapted to use `NarrowTransformation` instead. This should involve the following steps:

1. Remove `table.Stream()`.
2. Run the fill algorithm on each table chunk instead of the entire table.
3. Send the table chunk using the `TransportDataset`.

**Comment by onelson** [comment]
For reference, `NarrowTransformation` was added here for `filter` https://github.com/influxdata/flux/issues/3936
