### ISSUE TITLE
Update limit transformation to use NarrowStateTransformation

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#3939]
Update the `limit()` transformation to use [NarrowStateTransformation](https://github.com/influxdata/flux/issues/3933).

The `limit()` transformation presently uses `table.Stream()` to stream tables to the downstream. The transformation should be adapted to use `NarrowStateTransformation` instead. This should involve the following steps:

1. Remove `table.Stream()`.
2. For each group key, store the state for the limit/offset variables of the table.
3. Run the normal limit algorithm.
4. Send table chunks using the `TransportDataset`.

**Comment by onelson** [comment]
For reference, here's where `NarrowStateTransformation` was added for derivative 
https://github.com/influxdata/flux/issues/3941
