### ISSUE TITLE
Refactor difference transformation to use NarrowStateTransformation

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#3942]
Refactor the `difference()` transformation to use [NarrowStateTransformation](https://github.com/influxdata/flux/issues/3933).

At the present moment, `difference()` uses the column list table builder to construct tables. Fortunately, the algorithm used is a column-based construction so it should be easier to refactor this to use arrow arrays directly. Tables constructs from arrow arrays are generally easier to create in column-oriented algorithms.

This issue will be very similar to work already done to `derivative()`, which underwent a similar refactoring: https://github.com/influxdata/flux/pull/4043
(NB: there was a fix up PR to this one)

The algorithm should be changed to do the following:

1. The difference state should be initialized and maintained by the `NarrowStateTransformation`.
2. The difference algorithm for each column type should be refactored into functions instead of in the switch body.
3. The functions should return the arrow array for the column.
4. For each table chunk, the process method should produce a new table chunk and send it to the transport dataset.

**Comment by Marwes** [comment]
Should this be added under a feature flag?
