### ISSUE TITLE
gosnowflake dependency prints extraneous log message

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#3965]
We have recently been seeing that flux is causing the following message to happen whenever a binary begins to run.

```
INFO[0000]log.go:104 gosnowflake.(*defaultLogger).Infof reset OCSP cache file. /Users/macbook/Library/Caches/Snowflake/ocsp_response_cache.json
INFO[0000]log.go:104 gosnowflake.(*defaultLogger).Infof reading OCSP Response cache file. /Users/macbook/Library/Caches/Snowflake/ocsp_response_cache.json
```

While the above is a path for Mac OS X, this also appears to happen on Linux too. We believe it is likely caused by the gosnowflake dependency in Flux.

We need to determine if that dependency changed and, if it changed, how we can silence these log messages again. These messages do not seem to affect the actual functioning of anything but the text is not using our own logger and it likely needs to be silenced.

We should also look to see if this message actually indicates a real problem with the gosnowflake dependency before we just disable it.

NOTES:
 - We (influxdata) have a fork of the client with a PR https://github.com/snowflakedb/gosnowflake/issues/530 that allows us to upgrade to a version that does not log the above.
 - We should switch our build process to use our fork of the client
 - This means we should likely merge the PR into master of our fork and build of master of our fork.

DOD:
- The above message does not get printed anymore without requiring the user running it to do outside mitigation.
- All downstream builds of Flux (that we control) use the forked version of the client. Suggestion is to replace the import path to our fork so downstream projects do not have to change.

**Comment by jsternberg** [comment]
This seems to be the change that caused this log message to start coming up: https://github.com/influxdata/flux/pull/3901.

**Comment by nathanielc** [comment]
We need to update the client to remove the log messages. We can't update the client until https://github.com/snowflakedb/gosnowflake/issues/530 is fixed.

**Comment by pierwill** [comment]
Just ran into this. Looks like https://github.com/snowflakedb/gosnowflake/issues/530 is closed. I'm happy to submit a patch if someone can point me to the code that needs changed.

**Comment by onelson** [comment]
@pierwill iirc the last time the team discussed options, it sounded like we might start using the PR @nathanielc prepared as a proposed fix for the issue. Not sure if there are better options for us.
