### ISSUE TITLE
question: how to change the time zone

### ISSUE THREAD

**Issue by styfstr** [influxdata/flux#3966]
how to use flux to change the influxdb's time zone?

**Comment by bjuppa** [comment]
Here's a good read about the current timezone support: https://www.influxdata.com/blog/time-zones-in-flux/

...although beware, some timezones are not behaving, see https://github.com/influxdata/flux/issues/4312

**Comment by skartikey** [comment]
The issue https://github.com/influxdata/flux/issues/4312 is fixed with https://github.com/influxdata/flux/pull/4444
