### ISSUE TITLE
Panic with unknown type invalid in union/pivot query 

### ISSUE THREAD

**Issue by davidby-influx** [influxdata/flux#3976]
In a customer Cloud 1 installation running v1.9.3 we are seeing this panic in Flux.

Problematic query is available in the EAR repo in issue referencing this.

Stacktrace: 
```
2021-08-09-19.tsv:1361478831877308419   2021-08-09 19:57:51     2021-08-09 19:57:51     7342862461      prod-a5818010-eu-central-1-data-4       18.184.179.109  Daemon  Error   influxd ts=2021-08-09T19:57:51.034081Z lvl=info msg="Dispatcher panic" log_id=0Vs7_M4G000 service=flux-controller component=dispatcher error="panic: unknown type invalid" stacktrace="goroutine 56459 [running]:
runtime/debug.Stack(0xc031aa9ce0, 0x33ef300, 0x21cfbd0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1.1(0xc031c518f0)
	/go/pkg/mod/github.com/influxdata/flux@v0.120.1/execute/dispatcher.go:94 +0x1e5
panic(0x1e782c0, 0xc042b51150)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/influxdata/flux/execute.PanicUnknownType(...)
	/go/pkg/mod/github.com/influxdata/flux@v0.120.1/execute/table.go:1134
github.com/influxdata/flux/execute.(*ColListTableBuilder).AddCol(0xc042b68140, 0xc042b49f40, 0x6, 0x0, 0x0, 0x1, 0xc0377bb630)
	/go/pkg/mod/github.com/influxdata/flux@v0.120.1/execute/table.go:615 +0xd5c
github.com/influxdata/flux/stdlib/universe.(*reduceTransformation).Process(0xc031c7a300, 0x785eff1f1742b9d5, 0x5378dbb72956d589, 0x343b100, 0xc03fb94e00, 0x8, 0x0)
	/go/pkg/mod/github.com/influxdata/flux@v0.120.1/stdlib/universe/reduce.go:186 +0x68c
github.com/influxdata/flux/execute.processMessage(0x3434300, 0xc031c59100, 0x3449c40, 0xc031c7a300, 0x34101c0, 0xc03fb94e20, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/influxdata/flux@v0.120.1/execute/transport.go:251 +0x30d
github.com/influxdata/flux/execute.(*consecutiveTransport).processMessages(0xc052abaf30, 0x3434300, 0xc031c59100, 0xa)
	/go/pkg/mod/github.com/influxdata/flux@v0.120.1/execute/transport.go:199 +0xbb
github.com/influxdata/flux/execute.(*poolDispatcher).doWork(0xc031c518f0, 0x3434300, 0xc031c59100)
	/go/pkg/mod/github.com/influxdata/flux@v0.120.1/execute/dispatcher.go:181 +0xe2
github.com/influxdata/flux/execute.(*poolDispatcher).run(0xc031c518f0, 0x3434300, 0xc031c59100)
	/go/pkg/mod/github.com/influxdata/flux@v0.120.1/execute/dispatcher.go:159 +0x5c
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1(0xc031c518f0, 0x3434300, 0xc031c59100)
	/go/pkg/mod/github.com/influxdata/flux@v0.120.1/execute/dispatcher.go:99 +0x87
created by github.com/influxdata/flux/execute.(*poolDispatcher).Start
	/go/pkg/mod/github.com/influxdata/flux@v0.120.1/execute/dispatcher.go:76 +0x7e" 
```

**Comment by skartikey** [comment]
The flux query causing the panic in reduce function is:

`"import \"csv\"
import \"math\"

tbl_t539 = from(bucket: \"PROJ_418260\")
  |> range(start: 2021-08-01T22:00:00.0000000Z, stop: 2021-08-02T21:59:59.999999999Z)
  |> filter(fn: (r) => r._measurement == \"FE.087.3122.209\" and(r._field == \"value\"))
  |> group()
  |> keep(columns: [\"_value\", \"_time\"])
  |> timeShift(duration: 120m)
  |> set(key: \"_measurement\", value: \"table\")
  |> truncateTimeColumn(unit: 1s)
  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])


csv_t539 = csv.from(csv: \"
#datatype,string,long,dateTime:RFC3339,string,double
#group,false,false,false,false,false
#default,,,,,
,result,table,_time,_measurement,_value
,,0,2021-08-02T00:00:00.0000000Z,edges,0.0130208330228925
,,0,2021-08-02T01:42:03.0000000Z,edges,
,,0,2021-08-02T01:42:03.0000000Z,table,
\")

t539 = union(tables: [tbl_t539, csv_t539])
  |> pivot(rowKey:[\"_time\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")
  |> group()
  |> sort(columns: [\"_time\"], desc: true)
  |> elapsed(unit: 1s)
  |> map(fn: (r) => ({ r with _value: (float(v: if(exists r.table) then r.table else r.edges)) * - float(v: r.elapsed) }))
    |> reduce(fn: (r, accumulator) => ({
         _time: r._time,
  	      _value: accumulator._value + float(v: r._value),
         elapsed: accumulator.elapsed + -r.elapsed,
       }),
       identity: { _value: 0.0, elapsed: 0 }
    )
    |> filter(fn: (r) => r.elapsed > 0)
    |> map(fn: (r) => ({ r with _value: (r._value / float(v: r.elapsed)) * float(v: 1)}))
  |> map(fn: (r) => ({ r with _time: 2021-08-01T22:00:00.0000000Z }))
  |> keep(columns: [\"_time\", \"_value\"])
yield t539" error="panic: unknown type invalid" stat_total_duration=243.876ms stat_compile_duration=0.431ms stat_execute_duration=243.437ms stat_max_allocated=1792 stat_total_allocated=16944 
 `

Looking at the query it seems `_value` field is null for two rows in `csv_t539`, this is causing the unknown type invalid issue. 

So the fix would be to check for this in the reduce function and return the appropriate error message to the user.
I will add error message - "reduce object property "objName" is "null" type which is not supported in a flux table"`
