### ISSUE TITLE
Support expression statements with side-effects in the compiler

### ISSUE THREAD

**Issue by scbrickley** [influxdata/flux#3989]
We've seen a number of issues where flux scripts that should have side-effects aren't behaving as expected because they are being evaluated at compile time. ([Example](https://github.com/influxdata/flux/issues/3893))

The issue here is that the compiler [does not currently support](https://github.com/influxdata/flux/blob/5dfeb5051ff80cfeb81897b98c3c9a4ec2b80fba/compiler/compiler.go#L408-L409) expression statements that have side-effects.

Work needs to be done to allow the compiler to register these side-effects, so that certain flux scripts can behave as-expected without odd workarounds.

Questions to answer:

0. Do we want to model async/await in the semantic graph?
1. How do we represent the semantics of async/await in the semantic graph?
2. How do Rust and Javascript model async/await?
3. How do we implement support for multiple simultaneous processes without creating multiple instances of our execution engine?

**Comment by samhld** [comment]
@scbrickley do you believe resolving this would accomplish what this issue wants to accomplish as well? https://github.com/influxdata/flux/issues/3825

**Comment by scbrickley** [comment]
@samhld I believe it will at least resolve the runtime error you've included in that issue. If that's the only blocker, then the answer is yes.

This is not currently a priority for our team, though. There's some larger work that needs to be done with the compiler and the execution engine before we can get in a fix for this. Unfortunately, query team just doesn't have the bandwidth for it at the moment.

**Comment by samhld** [comment]
@scbrickley thanks!  Totally understand, just wanted to figure out what track for future!
