### ISSUE TITLE
Migrate the *Services to platform

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#4]
I think the QueryService interface and family belong in the platform repo. They are specific to how to make RPC calls and interact with other platform services.

My expectation is that this repo presents a library that contains the Flux language implementation and the Flux query engine.  Defining the service interfaces within this repo is a bit of an anti-pattern since the expectation is that the concrete types of this library are to be consumed. Consumers can wrap those types in their own services as needed.

Thoughts?

**Comment by aanthony1243** [comment]
I think there may be 2 sides of the coin here.  That code is influxdb/storage specific and as such isn't really related to the language.  However, it's also an example of how to implement a query service to connect to a data source.   if we are expecting users to write their own extensions/plugins, then we might want the code in this repo to serve as an example.

**Comment by goller** [comment]
Could not this repo stay the flux language repo? The machinery around exposing a public API could reside in other repos.

**Comment by desa** [comment]
Yeah I think I agree. I think it makes the sense for the flux repo to represent the flux language and the flux query language.

**Comment by jsternberg** [comment]
I agree with the original post. Things specific to the HTTP API that will be in the platform repository should stay there which includes the query service and query request objects.

**Comment by nathanielc** [comment]
Closed by #22
