### ISSUE TITLE
offset and limit returning different number of data points at 999 vs 1000

### ISSUE THREAD

**Issue by ccortezinflux** [influxdata/flux#4001]
A customer is reporting different number of data points while using limit () with offset at 999 vs 1000
from (bucket:"unitTests")
  |> range (start:-100y, stop:100y)
  |> filter(fn: (r) => r["_measurement"] == "testObserverPaginationOne")
  |> filter(fn: (r) => (r["_field"] == "x"))
  |> sort(columns:["_time"], desc:false)
  |> limit (n:42, offset:999)
![image](https://user-images.githubusercontent.com/86072919/131156806-55ece751-3360-460b-8099-599e18f1f4c6.png)
vs
from (bucket:"unitTests")
  |> range (start:-100y, stop:100y)
  |> filter(fn: (r) => r["_measurement"] == "testObserverPaginationOne")
  |> filter(fn: (r) => (r["_field"] == "x"))
  |> sort(columns:["_time"], desc:false)
  |> limit (n:42, offset:1000)
![image](https://user-images.githubusercontent.com/86072919/131160176-74e862ad-2da2-4bfb-ba9a-238aaac0d4b5.png)

**Comment by jsternberg** [comment]
Fixed by #4000.
