### ISSUE TITLE
Create boolean package

### ISSUE THREAD

**Issue by sanderson** [influxdata/flux#4013]
Currently, boolean values can't be used in packages that `universe` depends on because it creates a circular dependency. We should create a new `boolean` package with no dependencies that can be imported into other packages.

**Comment by wolffcm** [comment]
Some notes from team discussion:

Context: `true` and `false` are variables that are defined in the `universe` package.

Problem: `universe` can import packages like `date`, but `date` may need to use Boolean values like `true`and `false`. But using those creates a circular dependency.

Solution: Create a package with no dependencies that contains `true` and `false`.

Alternative solution: Make `true` and `false` keywords. Is there any reason not to do this? One reason is to avoid breaking changes.
