### ISSUE TITLE
Expose original representation in source code, from interpreter, for types that may be represented in various ways

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/flux#405]
For https://github.com/influxdata/influxdb/issues/10753, the Chronograf team wants to present the user with a duration identical to what the user has typed in to a task's options.

The issue is that when a user has `every: 1d`, that turns into a Go duration, and we translate that to `24 * time.Hour` in Go, which then is formatted as `24h0m0s`. While the duration value of `24 * time.Hour` represents the same duration that the user intended, there's no way to know if the user wrote `1d` or `24h` or `1440m` for that matter. If the user did write one of the latter two, I don't think formatting them to `1d` would be appropriate here.

One solution would be to associate the actual text from the flux source with the returned value for duration types - rather than (roughly) `type flux.Duration = time.Duration`, it would be `type flux.Duration struct { asWritten string, calculated time.Duration }`, at least for the sake of extracting options from source code.

I'm not sure if any other types have this issue of multiple representations for the same value, so I left the issue title generic.

**Comment by mark-rushakoff** [comment]
For more context, here is how the task code currently extracts options:

```go
inter := flux.NewInterpreter()
if err := flux.Eval(inter, script); err != nil {
	return opt, err
}

// pull options from interpreter
task := inter.Option("task")
if task == nil {
	return opt, errors.New("task not defined")
}
optObject := task.Object()

nameVal, ok := optObject.Get("name")
if !ok {
	return opt, errors.New("missing name in task options")
}

if err := checkNature(nameVal.PolyType().Nature(), semantic.String); err != nil {
	return opt, err
}
opt.Name = nameVal.Str()

// ...

if offsetVal, ok := optObject.Get("offset"); ok {
	if err := checkNature(offsetVal.PolyType().Nature(), semantic.Duration); err != nil {
		return opt, err
	}
	opt.Offset = offsetVal.Duration().Duration()
}

// ...
```

https://github.com/influxdata/platform/blob/d64dbbc034baac2084d010d165a0ec4a5f788ffe/task/options/options.go#L64-L128

**Comment by docmerlin** [comment]
Blocked by https://github.com/influxdata/flux/issues/921
