### ISSUE TITLE
Upload CSV file doesn't seem to work

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/flux#4054]
Whenever I try to upload an annotated CSV file, I get the error: Failed to upload the selected CSV: error in csv.from(): failed to read metadata: missing expected annotation datatype

I believe the file is correct (see attachment). If it is not, then our docs are incorrect because that is where I got the file.  
[foo.csv](https://github.com/influxdata/ui/files/7188408/foo.csv)

**Comment by nathanielc** [comment]
@barbaranelson That csv is invalid. Can you link to where it came from? I can help them get a valid CSV example

**Comment by barbaranelson** [comment]
https://docs.influxdata.com/influxdb/cloud/write-data/developer-tools/csv/

**Comment by genehynson** [comment]
I tried the NOAA data from https://influx-testdata.s3.amazonaws.com/noaa.csv and was able to successfully import the data via the file uploader and via the following query:

```
import "experimental/csv"

csv.from(url: "https://influx-testdata.s3.amazonaws.com/noaa.csv")
  |> to(bucket: "noaa", org: "example-org")
```

**Comment by barbaranelson** [comment]
Here's another example from the docs. I'm sure it's user error but not really clear what we are supposed to do. I took the contents  of csvdata from here: https://docs.influxdata.com/influxdb/v2.0/reference/syntax/annotated-csv/ and wrote it to a file, and then tried to upload the file and got this error:

Failed to upload the selected CSV: runtime error @3:14-3:41: to: no column with label _measurement exists

**Comment by genehynson** [comment]
Now that one is strange to me. If I run `csv.from()` like the docs mention, it works fine. But when I change the query to add a `|> to(bucket: "noaa")`, then the Query API fails with the error you mentioned above @barbaranelson . The CSV file uploader appends the `|> to(bucket: ... )` which is why it fails too.

Works:
```
import "csv"

csvData = "#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,string,string,double
#group,false,false,false,false,false,false,false,false
#default,,,,,,,,
,result,table,_start,_stop,_time,region,host,_value
,,0,2018-05-08T20:50:00Z,2018-05-08T20:51:00Z,2018-05-08T20:50:00Z,east,A,15.43
,,0,2018-05-08T20:50:00Z,2018-05-08T20:51:00Z,2018-05-08T20:50:20Z,east,B,59.25
,,0,2018-05-08T20:50:00Z,2018-05-08T20:51:00Z,2018-05-08T20:50:40Z,east,C,52.62
,,1,2018-05-08T20:50:00Z,2018-05-08T20:51:00Z,2018-05-08T20:50:00Z,west,A,62.73
,,1,2018-05-08T20:50:00Z,2018-05-08T20:51:00Z,2018-05-08T20:50:20Z,west,B,12.83
,,1,2018-05-08T20:50:00Z,2018-05-08T20:51:00Z,2018-05-08T20:50:40Z,west,C,51.62
"

csv.from(csv: csvData)
```

Does not work:
```
import "csv"

csvData = "#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,string,string,double
#group,false,false,false,false,false,false,false,false
#default,,,,,,,,
,result,table,_start,_stop,_time,region,host,_value
,,0,2018-05-08T20:50:00Z,2018-05-08T20:51:00Z,2018-05-08T20:50:00Z,east,A,15.43
,,0,2018-05-08T20:50:00Z,2018-05-08T20:51:00Z,2018-05-08T20:50:20Z,east,B,59.25
,,0,2018-05-08T20:50:00Z,2018-05-08T20:51:00Z,2018-05-08T20:50:40Z,east,C,52.62
,,1,2018-05-08T20:50:00Z,2018-05-08T20:51:00Z,2018-05-08T20:50:00Z,west,A,62.73
,,1,2018-05-08T20:50:00Z,2018-05-08T20:51:00Z,2018-05-08T20:50:20Z,west,B,12.83
,,1,2018-05-08T20:50:00Z,2018-05-08T20:51:00Z,2018-05-08T20:50:40Z,west,C,51.62
"

csv.from(csv: csvData)
|> to(bucket: "noaa")
```

**Comment by nathanielc** [comment]
> Failed to upload the selected CSV: runtime error @3:14-3:41: to: no column with label _measurement exists

The `to` function needs to know which column is the measurement. By default it assumes it is the `_measurement` column. The example CSV data does not have the `_measurement` column so the `to` function errors.

**Comment by barbaranelson** [comment]
Can we update our examples so that they can be used in CSV uploads? I was trying to very quickly import some data into an account I had created, and each example that I cut/paste seemed to hit a different problem.

**Comment by nathanielc** [comment]
@barbaranelson That would make sense to me. I read through the docs page and it seems that the `influx write` CLI has added features that Flux does not support. So while those example CSV file on the docs page work with the `influx write ` command they do not work with the upload feature or with Flux csv.from.

**Comment by barbaranelson** [comment]
@kelseiv can we update the example CSVs in the docs so it is possible to cut/paste them into a file and upload them through our UI?  Thanks.

Also, for my education, what is wrong with the first CSV file, @nathanielc ? Thanks.

**Comment by nathanielc** [comment]
>  Also, for my education, what is wrong with the first CSV file, @nathanielc ? Thanks.

Its missing the other two annotations, Flux csv needs all three annotations, `datatype,group,default`.

**Comment by barbaranelson** [comment]
Ah, then at a minimum let's change the error message: _failed to read metadata: missing expected annotation datatype_
Not clear that the problem was with the other annotations.

**Comment by nathanielc** [comment]
Yeah that makes sense, in fact it should do that already. So I checked why it didn't, turns out the csv has two errors. Here is the csv for easy reference:

```
#datatype measurement,tag,double,dateTime:RFC3339
m,host,used_percent,time
mem,host1,64.23,2020-01-01T00:00:00Z
mem,host2,72.01,2020-01-01T00:00:00Z
mem,host1,62.61,2020-01-01T00:00:10Z
mem,host2,72.98,2020-01-01T00:00:10Z
mem,host1,63.40,2020-01-01T00:00:20Z
mem,host2,73.77,2020-01-01T00:00:20Z
```

It looks like the `#datatype` annotation is present, but there is a missing comma as well so the first CSV cell is really `#datatype measurement` so the error code thinks there are no annotations. I'll look into adding an error about unknown/unsupported annotations to make this particular case easier to fix once you see the error message.

**Comment by nathanielc** [comment]
I created a quick PR, but we will need to have a team discussion to make sure we are OK with the potential for a breaking change here. https://github.com/influxdata/flux/pull/4065
