### ISSUE TITLE
Last table results truncated to 5000 lines

### ISSUE THREAD

**Issue by nikolay-t** [influxdata/flux#410]
We see that results in last table get truncated to 5000 if function is executed in Flux. To reproduce this, perform followings steps:
1. Write >5000 points to single measurement, i.e. one point in one second.
2. Create query with function that is executed in Flux (i.e. difference()). Example: from(db: "main") |> filter(fn: (r) => r._measurement == "metric_name" AND r.my_id == "RandomID")
 |> range(start: -1d) |> difference() |> count()
3. Execute query and see that only up to 5000 lines returned. In case of increase(), 4999 lines returned.

At the same time, repeating the same query with aggregate function executed in InfluxDB (i.e. count()) returns correct result.

Expectation: receive all points initially written to InfluxDB.

Note that if we write points with different tags, then execute Flux query without specifying particular tag (i.e. without "ND r.my_id == "RandomID""), then data is returned split into several tables. However only the last table is truncated to 5000, and the "last" is determined by alphanumerical sort.

**Comment by aanthony1243** [comment]
could not reproduce on platform, will try influxdb next

**Comment by aanthony1243** [comment]
also did not see issue on influxdb  @nikolay-t   could you give us more information on influxdb software versions and the environment you are using?

**Comment by andig** [comment]
As side note: would it be possible to include ingen in the docker images to quickly create reproducible test sets? Hope this is not too off-topic for this issue.
