### ISSUE TITLE
Add location support to the window function

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#4102]
With #4059, we will have the capability to use location information as part of the interval package. We need to add an option to the window function that allows us to specify the location to use when windowing.

We will add an optional `location` parameter to the window function. The default location should be the `location` option in the universe package. The default value for `location` is `UTC` and `UTC` causes it to not use any location information which is the default functionality. If another string is used, we will load the location information and provide it to the window in the interval package. An invalid location or an empty string are invalid.

In order to implement the option, something like this will probably be needed.

```
option location = "UTC"

builtin _window = (<-tables: [A], ..., location: string) => [B] where A: Record, B: Record

window = (tables=<-, ..., location=location) => tables |> _window(..., location)
```

DOD:
- The `location` parameter exists for `window()`.
- The default value is `option location`.
- Push downs should be disabled if the location parameter is not `UTC`.
- `option location = "UTC"` should be defined in the same package.

**Comment by nathanielc** [comment]
I would prefer if we designed it such that an empty string is invalid. The location option will have a default value and we can use the location option  as the default to any args that need it. Thoughts? What should the location option default be? I am thinking "UTC" that way it remains backwards compatible.

**Comment by jsternberg** [comment]
I was thinking to make the empty string valid to allow for forwarding arguments more easily. This is because we don't have a good way to do this:

```
builtin window : (?location: string)

aggregateWindow = (location="I want to reuse the default please don't make me repeat myself") =>
    window(location: location)
```

If we don't want the empty string to be valid, I'd say `UTC` is a good string to just use and require those who pass it through like `aggregateWindow` to just say `UTC`.

**Comment by nathanielc** [comment]
>I'd say UTC is a good string to just use and require those who pass it through like aggregateWindow to just say UTC.

I'd prefer to just resue the lcoation option in all the places we need a default. Its annoying we have to repeat ourselves, but at least in this case there is a clear value to use a default that can be changed in a single line of code.

**Comment by jsternberg** [comment]
I was going to write an explanation of why the option isn't a good idea to implement at the moment, but it just occurred to me that the reasons don't apply to the window function or aggregate window because they don't have any generalized parameters. I'll modify the description to also include the option and we can use that as the default.

For posterity, here was my original writeup. This writeup _does not_ apply to this issue, but could for future issues. It mostly relates to functions that utilize the `now()` builtin.

**ORIGINAL WRITEUP THAT IS WRONG FOR THIS ISSUE BELOW**

The problem with the location option at the moment is mostly because of [this issue](https://github.com/influxdata/flux/issues/3629). The reason is because of how options interact with native Go code. The Go code doesn't really have the information about what is in scope and doesn't have a good way of retrieving options. As an example of this, the `now()` option has a lot of hacky code in the engine to get it to work properly with builtins and I'd like to not repeat that for more options. Native code does have a good way of accessing them because that's where options are implemented. A good way to pass options to a builtin when they need it is this:

```
option location = "UTC"

builtin _window : (<-tables: [A], location: string) => [B] where A: Record, B: Record
window = (tables=<-, location=location) => tables |> _window(location)
```

This correctly implements options. The problem is that we don't have a good way of forwarding arguments and when we include a default on a native function, we overly apply constraints. If we have an argument that takes something like `Timeable` as a constraint to a builtin for a default argument, there's no way to pass that on. An example is `range()`. If we wanted to rewrite `now()` to utilize this same pattern, we can't do this:

```
builtin _range = (<-tables: [A], start: B, ?stop: C) => [D] where A: Record, B: Timeable, C: Timeable, D: Record
range = (tables=<-, start, stop=now()) => tables |> _range(start, stop)
```

This change prevents `stop` from being a duration and prevents us from utilizing the option to its full extent. Not to mention that `now()` itself prevents that because of eager evaluation.
range
