### ISSUE TITLE
Abstract locations and fixed offset timezones

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#4116]
We want the ability to represent both fixed offset timezones and location based timezones. This means implementing both  `loadLocation` and  `fixedOffset` functions that return the same type that the `window` function takes for its location argument. 

One way to do this is with record with properties like:

```
{
    location: string,
    offset: duration
}
```

UTC would be `{location: "UTC", offset: 0s}`, and fixed offset -6 would be `{location: "UTC", offset: -6h}` and America/Denver would be `{location:"America/Denver", offset: 0s}`. 

Note sure what happens if you have location that is not fixed and a non-zero offset. Perhaps a better design would solve that inconsistency.

**Comment by jsternberg** [comment]
Ok given the above my thought is that we keep this to only be a modification to the `option`. So the following would be equivalent:

```
option location = {location: "UTC", offset: 4h}

window(location: "UTC", offset: 4h)
```

The default parameters for window would be like this:

```
window = (location=location.location, offset=location.offset) => ...
```

This allows both location and offset to live alongside each other without modifying the parameters to window or aggregate window. Thoughts?
