### ISSUE TITLE
Panic using json.parse() referencing array on an object

### ISSUE THREAD

**Issue by abalone23** [influxdata/flux#4126]
Given this valid JSON:
```
{
	"name": "Mary",
	"age": 40,
	"cars": {
		"car1": "Ford",
		"car2": "BMW"
	}
}
```

Using `json.parse()` `cars[0]` results in a Panic because it's referencing a non-existent array:

```
import "array"
import "experimental/json"

array.from(rows: [{_measurement: "m0", mytag: "t0", _field: "f0", _value: "{ \"name\":\"John\", \"age\":30, \"cars\": {\"car1\": \"Ford\", \"car2\": \"BMW\" } }", _time: 2021-09-01T00:00:00Z}])
    |> range(start: -100y)
    |> map(fn: (r) => {
    jsonData = json.parse(data: bytes(v: r._value)) return {
        _time: r._time,
        _field: r._field,
        name: jsonData.name,
        age: jsonData.age,
        cars: jsonData.cars[0]
    }
    })
```
<img width="1835" alt="Screen Shot 2021-10-07 at 3 38 43 PM" src="https://user-images.githubusercontent.com/330044/136471744-26759195-32f3-4cea-859d-e4566ba18546.png">

**Comment by Marwes** [comment]
I think the idea is that it still shouldn't panic but return an error. Actually achieving that would seem to more difficult though as the `json.parse` function would have to be made aware of what the expected type should be, a mechanism which (to my knowledge) does not exist atm.
