### ISSUE TITLE
Implement Duration vectors

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#413]
See https://github.com/influxdata/flux/blob/master/docs/SPEC.md#duration-literals

**Comment by toinbis** [comment]
Hi @nathanielc , maybe you have any idea of potential estimate of when this could be implemented?  
Or it's not in a priority list as of now yet?  
Thanks!

**Comment by nathanielc** [comment]
This has been implemented, using the `date.add`, `date.sub` and `date.scale` functions.
