### ISSUE TITLE
query: enable programmatic "jump to definition" for values in flux source code

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/flux#415]
Given a source file, and a line and column number for focus in that source file, there should be a flux API that tells you where the value was initially defined. For example, given an input of 

```
in = from(bucket: "my_bucket") |> range(start:-5m)

in |> mean()
```

If my cursor is on Line 3, Column 0, the API should report that the value of `in` was defined on Line 1, Column 0.

TBD: how to handle builtin functions? how to handle imported packages?

**Comment by russorat** [comment]
what's left here now that we have https://github.com/influxdata/flux-lsp ?

**Comment by nathanielc** [comment]
This looks complete. Closing
