### ISSUE TITLE
Design a method of handling default parameters in spec generation

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#417]
When the spec is used directly, default parameters don't get included automatically because the default parameters are added by flux using internal methods to create the spec rather than by filling in the defaults when we create the procedure.

Design a better way to handle defaults that ensures issues like #521 don't happen to users of the query spec.

**Comment by nathanielc** [comment]
See https://github.com/influxdata/flux/pull/298 as using this design will remove the differing entry points such that default parameters are always applied.

**Comment by jsternberg** [comment]
This isn't applicable anymore since the spec is internal and transpilers now use AST so the defaults get handled correctly.
