### ISSUE TITLE
stateChangesOnly() does not work as expected

### ISSUE THREAD

**Issue by delapuentem** [influxdata/flux#4179]
Hello, the `monitor.stateChangesOnly()` function is not working as I expect. It is supposed to return me the last value of each state, as explained in the [documentation ](https://docs.influxdata.com/flux/v0.x/stdlib/influxdata/influxdb/monitor/statechangesonly/)

If I run this query in Flux, you can see that it returns me different states. 

```js
import "influxdata/influxdb/monitor"

from(bucket: "monitoring")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
	|> filter(fn: (r) =>
		(r._measurement == "http_response" and r._field == "result_code"))
	|> filter(fn: (r) =>
		(r["server"] == "https://www.webpage.org"))
	|> keep(columns: ["_time", "_value", "_field", "server"])
	|> group(columns: ["server"])
  |> map(fn: (r) => ({  r with
    _level:
      if r._value > 0.0 then "critical"  else "normal" }))
```

But if I apply the `monitor.stateChangesOnly()` function, it doesn't return data.

```js
import "influxdata/influxdb/monitor"

from(bucket: "monitoring")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
	|> filter(fn: (r) =>
		(r._measurement == "http_response" and r._field == "result_code"))
	|> filter(fn: (r) =>
		(r["server"] == "https://www.webpage.org"))
	|> keep(columns: ["_time", "_value", "_field", "server"])
	|> group(columns: ["server"])
  |> map(fn: (r) => ({  r with
    _level:
      if r._value > 0.0 then "critical"  else "normal" }))
  |> monitor.stateChangesOnly()
```

Can you reproduce it and give me feedback? If you need more information, I have an open thread on this topic in the [Influxdata Forum](https://community.influxdata.com/t/statechangesonly-does-not-work-as-expected/17350)

Thanks!

**Comment by R-Studio** [comment]
@wolffcm Thanks for your explanation about the function. 👍🏽 
But is there a way to use this with custom levels or in different words **can you send me a custom function to reach this**?

**Comment by wolffcm** [comment]
You can modify the function here to use the levels you want:
https://github.com/influxdata/flux/blob/master/stdlib/influxdata/influxdb/monitor/monitor.flux#L253-L277
Then you could just put that new function in your flux script.
