### ISSUE TITLE
Comments make code formatting inconsistent

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/flux#4209]
After recent changes to the way we format multiline code, comments are now providing weird/inconsistent formatting results depending on how they are placed. Here are some tests that had to be skipped due to inconsistent formatting: 
https://github.com/influxdata/flux/blob/8cb5b401853ec3fa9f011d92a93393df6b568cbb/libflux/flux-core/src/formatter/tests.rs#L1383-L1598

The goal would be to come up with ways that we expect multiline code to behave around comments and provide that behavior consistently. 

DOD: 
- Above tests are unskipped
- Additional tests for edge cases are added as needed
- Formatting code with comments is consistent

**Comment by nathanielc** [comment]
This is fixed as part of https://github.com/influxdata/flux/pull/4322 Comment handling is not perfect yet but its good enough.
