### ISSUE TITLE
Query controller is confusing and should be tested and refactored

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#422]
The query controller is confusing and contains a state machine that isn't type safe and is very difficult to follow. In addition, there are no tests for the controller at the moment so we aren't verifying the behavior.

The primary purpose of this issue is to add tests, but the query controller itself should probably be refactored because the state machine is confusing to follow and it's possible to transition to a state, maintain certain assumptions about what values are set in that state, and end up with a panic when those assumptions aren't valid.

**Comment by nathanielc** [comment]
We have added tests and simplified the controller.
