### ISSUE TITLE
Include reasoning about type mismatches.

### ISSUE THREAD

**Issue by onelson** [influxdata/flux#4224]
In a trivial script such as this, 
```
a = 1
x = a[0]
```

flux will report an error like `expected [A] but found int`, pointing to the line and column where the invalid array access happens.

For this trivial script, we can see plainly that the value was assigned as an int, but in the wild the initial assignment could be many lines removed.

The reported error prompts two questions:

- What is `[A]`?
- Why does flux think there's a type mismatch?

For this specific case, if we could include a line/column for both _the assignment and the invalid access_, it might make the reasoning more clear.

Additionally, I'm not sure if the `[A]` in the message is dynamic based on the various types in play at any given point in the script or if this is flux convention/jargon. If the latter, we might just rephrase the message to say _"tried to access `<type>` as an array"_, or similar.

**Comment by onelson** [comment]
Some rust crates that target error reporting that could be interesting to introduce:

- https://github.com/brendanzab/codespan
- https://github.com/zkat/miette

**Comment by Marwes** [comment]
The `Help` type I use to add optional help/hints to errors in gluon https://github.com/gluon-lang/gluon/blob/25d949b8836d0cd28adc027f8d0e4e20a102aca1/check/src/typecheck/error.rs#L246-L276
