### ISSUE TITLE
How to sink data resut to kafka in flux engine?

### ISSUE THREAD

**Issue by tfnick** [influxdata/flux#4233]
I found mqtt.to() and mqtt.publish() functions in flux standard library. So is there a similar method for sending data to kafka???

Thanks for response.

**Comment by sanderson** [comment]
@tfnick There currently isn't a native Flux implementation for Kafka, but we could certainly add that as a feature request if there is enough demand for it. In the mean time, one potential solution would be to setup a [Kafka REST proxy](https://github.com/confluentinc/kafka-rest) that you could send data to using `http.post`.

The example below uses map to send a POST request for each row.

```js
import "http"
import "json"

data
    |> map(
        fn: (r) => ({r with
            sent: http.post(
                url: "http://example-proxy-url.com/topics/${r.topic}",
                headers: {
                    "Content-Type": "application/vnd.kafka.json.v2+json",
                },
                data: json.encode(v: {"records": [{"value": {"field": "r._field"}}]}),
            ),
        }),
    )
```

**Comment by tfnick** [comment]
@sanderson Thanks, Http.post() is indeed  an optional solution.
But i read the source code of flux and found a **kafka** package. And I try to use **kafka.to()** method in influxdb's tasks. 
This method  **kafka.to()** meets my needs.

**Comment by tfnick** [comment]
@sanderson PS: Http.post is not recommended, mainly because of the three-tier architecture. I do not want the database layer's influxdb to call the HTTP proxy deployed in the application layer
