### ISSUE TITLE
[RFC] Simple way to generate basic sequences

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#424]
From ifql created by [desa](https://github.com/desa) : influxdata/ifql#161  

I'm thinking of something along the lines of [`!R` from K](https://en.wikipedia.org/wiki/K_(programming_language) ) or possibly even [Streams from Scheme](https://www.gnu.org/software/mit-scheme/documentation/mit-scheme-ref/Streams.html) .

This is particularly useful when trying to learn how a language works.

The current process for gaining intuition with InfluxQL is
* create dummy database
* load a database with some dummy data
   - usually by running a few `insert x v=1`
* query dummy data until I've got a solid idea of what I want
* add some tags to that data
    - usually reinserting the same data I had previously, but this time with a few extra tags
* forget to drop old database

The process for learning tickscript is even more involved, since it involves often inserting a bunch of `log` and generating a stream of data and watching the kapacitor logs.

Both methods have relatively long feedback loops for gaining intuition about how the language works. We should attempt to make this feedback loop shorter.

For the purpose of learn-ability, I believe that having a way to generate simple sequences is preferential to having IFQL be able to read and operate on raw line protocol, because it allows the user to keep their thought process on a single file (rather than have to jump back and forth between the data file and the query file).

My general proposal would look something like the following

```js
generate(
start:-1m,
interval: 10s,
seed: 0,
next: function(prev) { return prev + 1 },
tags: ['t=a']
)
```

Which would generate the following data

```
t=a 0 0s
t=a 1 10s
t=a 2 20s
t=a 3 30s
t=a 4 40s
t=a 5 50s
```

**Comment by russorat** [comment]
we have generate functions in flux today.
