### ISSUE TITLE
Refactor union transformation to use Transport and Arrow APIs

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#4267]
Refactor the `union()` transformation to use one of the transports.

At the present moment, `union()` uses the column list table builder to construct tables. We can modify this transformation to pass the table chunks unaltered to the next downstream transformation.

We can modify union to use one of the newer transport layers so that we can increase throughput and reduce memory allocations by passing table chunks on to the next transformation.

One caveat to this is that we will have to create something new that allows us to control the flush key message. This is because union is a narrow transformation and should pass on flush key, but it should only pass on flush key after it has received it equal to the number of tables being unioned.

Alternatively, it might be better to implement union as a group transformation so we do not have to think about the flush key message. One of these should be implemented during this refactor.

DOD:
- The union transformation is utilizing table chunks and the new process message API (through one of the existing interfaces or a new one).
- There are queries related to union in the regression suite.
- There is a feature flag for this change.

**Comment by wolffcm** [comment]
We need to figure out how to handle the incompatible schema problem. Whatever solution in that space that is produced could affect the implementation of this issue.
