### ISSUE TITLE
Window bucket start boundary should default to `now`

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#427]
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#205  

If the user is windowing by 1m and the current time is t=30s off the minute then time boundaries should be at t +1m , t +2m, ...  t + Nm.

https://github.com/influxdata/influxdb/issues/4680

**Comment by nathanielc** [comment]
See also #733

**Comment by jsternberg** [comment]
Closing this since we decided on a different design.
