### ISSUE TITLE
Feature Request: Sub nanosecond timestamps

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#428]
From ifql created by [pbooth](https://github.com/pbooth) : influxdata/ifql#242  

The introduction of a new query language is a good time to question the validity of pre-existing assumptions. The day that I discovered influxdb (version 0.8 or 0.9) supported nanosecond timestamps was the same day I installed it and dumped the inferior solutions I had been using for storeing time-series data. Back then one of the common low latency network switches captured timestamps using an ASIC with a 350MHz oscillator, for an effective clock  granularity of 2.857 nanoseconds. Three years later we've seen order of magnitude improvements- there are NICs available that use 250picosecond timestamps, and this progress will only continue. This is relevant to financial services use cases, where business transparency is crucial.

It would now seem prudent for the new InfluxDB query language, as well as the underlying data stores,  to support timestamps that are finer grained than nanosecond, as some users will be persisting events that are timestamped with sub-nano precision.

**Comment by russorat** [comment]
connect https://github.com/influxdata/flux/issues/739
