### ISSUE TITLE
flux >= v0.134.0 doesn't get built on Ubuntu 18.04 

### ISSUE THREAD

**Issue by telzhov** [influxdata/flux#4282]
Hi dear flux developers!

the build seems to be broken for v0.134.0 onwards on Ubuntu 18.04 LTS (for versions <= v0.133.0 everything is perfect there):
```
$ go build ./cmd/flux
# pkg-config --cflags  -- flux
Started pkg-config	{"arg0": "/home/telzhov/go/bin/pkg-config", "args": ["--cflags", "--", "flux"]}
Found pkg-config executable	{"path": "/usr/bin/pkg-config"}
Determined module root	{"path": "/home/telzhov/src/flux"}
Flux module is the main module	{"modroot": "/home/telzhov/src/flux"}
Could not determine version from base path	{"error": "directory path did not match the module pattern: /home/telzhov/src/flux"}
Executing cargo build	{"dir": "/home/telzhov/src/flux/libflux", "target": "x86_64-unknown-linux-gnu"}
    Updating crates.io index
error: failed to select a version for the requirement `anyhow = "=1.0.44"`
candidate versions found which didn't match: 1.0.43, 1.0.42, 1.0.41, ...
location searched: crates.io index
required by package `flux-core v0.4.0 (/home/telzhov/src/flux/libflux/flux-core)`
Error installing library	{"name": "flux", "error": "exit status 101"}
pkg-config: exit status 1
```
There is no such issue on Ubuntu 20.04 LTS on the other hand. Could it relate to clang versions which are quite a bit different for 18.04 and 20.04?

For Ubuntu 18.04:
```
$ clang --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
```
For Ubuntu 20.04:
```
$ clang --version
clang version 10.0.0-4ubuntu1 
```

Thank you!

**Comment by nathanielc** [comment]
@telzhov Thanks for the report we will look into this. Seems to be an issue with one of our Rust dependencies. 

Which version of Rust are you using on each Ubuntu version?

**Comment by telzhov** [comment]
It's exactly the same for both:
```
$ rustc -V
rustc 1.53.0
```

**Comment by Marwes** [comment]
There exists newer versions than 1.0.43 so it is strange that you get that error https://crates.io/crates/anyhow/versions .

You may need a newer rust version though I don't see how that would cause that error either.

**Comment by telzhov** [comment]
I've just erased the entire ~/.cargo directory, and it helped -- no warnings or errors. Probably earlier I interrupted the build process (including downloading of crates) and restarted again so left this folder in somewhat improper condition, I don't really know...

Anyway, thanks a lot for your efforts! Should we close the issue now?
