### ISSUE TITLE
`sql.to()` inside `experimental.chain()` fires twice in flux acceptance tests

### ISSUE THREAD

**Issue by onelson** [influxdata/flux#4302]
While trying to write tests that interact with an RDBMS for reading and writing, I noticed my writes _firing twice_ when the write and read operations are sequenced one after the other via `experimental.chain()`.

While this version is vulnerable to race conditions (the read and write could hit the RDBMS in either order), the database log shows the `sql.to()` _fires only once_.

```
dsn = "xxxxxxx"
testcase integration_pg_write_to {
    sophie = { name: "Sophie", age: 15 }
    array.from(rows: [sophie])
        |> sql.to(
           driverName: "postgres",
           dataSourceName: dsn,
           table: "pets",
           batchSize: 1
        )
    got = sql.from(
        driverName: "postgres",
        dataSourceName: dsn,
        query: "SELECT name, age FROM pets where seeded = false"
    )
    want = array.from(rows: [sophie])
    testing.diff(want: want, got: got) |> yield()
}
```

When the write and the read are instead run one after the other using `experimental.chain()`, the `sql.to()` _fires twice_.

```
dsn = "xxxxxxx"
testcase integration_pg_write_to {
    sophie = { name: "Sophie", age: 15 }
    got = experimental.chain(
        first: array.from(rows: [sophie])
                    |> sql.to(
                       driverName: "postgres",
                       dataSourceName: dsn,
                       table: "pets",
                       batchSize: 1
                    ),
        second: sql.from(
            driverName: "postgres",
            dataSourceName: dsn,
            query: "SELECT name, age FROM pets where seeded = false"
        )
    )
    want = array.from(rows: [sophie])
    testing.diff(want: want, got: got) |> yield()
}
```

In this 2nd version, the ordering is consistent but since the `sql.to()` call fires twice the `sql.from()` gives us an unexpected 2nd row in the query results, causing the test to fail.

Interestingly, running the 2nd version as a plain script (not a test) in the REPL only fires the `sql.to()` once.

> The test _also fails, even if we paper over the fact there's an extra row since the `sql.to()` call will implicitly yield giving the program a non-empty result (https://github.com/influxdata/flux/issues/4301)

It's unclear if this is a dupe of https://github.com/influxdata/flux/issues/3614 - it could be a similar class of problem, or something else entirely but the details look like an overlap.

**Comment by onelson** [comment]
I've been told (repeatedly) that the test harness will run tests multiple times as a part of a hack to work around some other issue, but I'm not familiar with the details or history. If the above truly is just this quirk of the test harness, maybe we can pivot this issue into investigating that hack and possibly finding another way to satisfy whatever the need is.

**Comment by onelson** [comment]
https://github.com/influxdata/flux/blob/13316b3581bc3e5d0a3a8963a676b8b2c9cca736/execute/executor.go#L239-L244 is the "implicit yield" that seems to be causing the `sql.to()` to fire twice. We might be able to remove that block, but we need to do some diligence to see if it's needed today.

**Comment by Marwes** [comment]
> https://github.com/influxdata/flux/issues/4302#issuecomment-986936825

https://github.com/influxdata/flux/pull/390 seems to be the PR that added this block so the block effectively means that if an execution plan ends with a node with side effects (such as to) then add an implicit yield. We can't just remove it because the execution engine will just ignore it since it does not generate results.

So I think we need to do one of the following

* Make the execution engine aware of side effects, so that it always runs things with side effects.
* Implicitly insert yields only for `to` etc when they actually are the last node

**Comment by onelson** [comment]
I wanted to refine the repro a bit to make it easier to verify the fix and came up with this. I'll probably build a small shell script to manage/reset the db file and summarize the outcome.

This test also narrows the scope of the issue to something with the test runner (I think?) `flux execute` behaves well, but `flux test` does not.

Given a `check.flux` containing:

```
import "experimental"
import "sql"
import "array"
dsn = "file:///tmp/double-chain.db"
experimental.chain(
    first: array.from(rows: [{n: 1}]) |> sql.to(driverName: "sqlite3", dataSourceName: dsn, table: "test"),
    second: array.from(rows: [{}])
)
```

The row count in the database following the script running is 1.

```
flux on  fix/double-chain [$!?] via 🐹 v1.17.2 
❯ rm /tmp/double-chain.db 
flux on  fix/double-chain [$?] via 🐹 v1.17.2 
❯ go run ./cmd/flux execute "@check.flux"
INFO[0000]log.go:104 gosnowflake.(*defaultLogger).Infof reset OCSP cache file. /home/onelson/.cache/snowflake/ocsp_response_cache.json 
INFO[0000]log.go:104 gosnowflake.(*defaultLogger).Infof reading OCSP Response cache file. /home/onelson/.cache/snowflake/ocsp_response_cache.json 
Result: _result
Table: keys: []



flux on  fix/double-chain [$?] via 🐹 v1.17.2 took 2s 
❯ sqlite3 /tmp/double-chain.db 'select count(rowid) from test'
1

```

Running equivalent code as an acceptance test will result in a failing test
(since it'll yield non-empty tables) but if we just pay attention to the row
count in the sql database, we see it incorrectly fires twice.

```
flux on  fix/double-chain [$!?] via 🐹 v1.17.2 
❯ rm /tmp/double-chain.db
flux on  fix/double-chain [$!?] via 🐹 v1.17.2  
❯ go run ./cmd/flux test -v --test chainShouldSqlToOnce
INFO[0000]log.go:104 gosnowflake.(*defaultLogger).Infof reset OCSP cache file. /home/onelson/.cache/snowflake/ocsp_response_cache.json 
INFO[0000]log.go:104 gosnowflake.(*defaultLogger).Infof reading OCSP Response cache file. /home/onelson/.cache/snowflake/ocsp_response_cache.json 
chainShouldSqlToOnce...fail: # (none) 
#  n=int
n=1i


failures:

        chainShouldSqlToOnce...fail: # (none) 
#  n=int
n=1i


---
Ran 1 tests with 1 failure(s)
exit status 1

flux on  fix/double-chain [$!?] via 🐹 v1.17.2 took 4s 
❯ sqlite3 /tmp/double-chain.db 'select count(rowid) from test'
2

```

**Comment by onelson** [comment]
Stepping through this test case in the debugger, I ran the count SQL query to see where it exceeded the expected 1 row count.

Looks like the 2nd `sql.to` call happens during the reporting code here:

https://github.com/influxdata/flux/blob/master/cmd/flux/cmd/test.go#L638-L654

Prior to the `for results.More()` loop, there is 1 row in the database (ie, the program has already been run).

After the `results.Release()` call there are 2 (ie, the `sql.to` has fired again).

To be more specific, the sqlite database is locked during the `for results.More()` loop so it can't be read until the `results.Release()`.

I'm not sure what we can do about this. If it's not possible to capture the output during the earlier execution of the test case, this might be unavoidable.

**Comment by onelson** [comment]
To contrast my previous observation about the reporting loop - rewriting the testcase to not use `experimental.chain`, instead running `sql.to` directly, no rows are inserted _until the reporting loop runs_. The expected row count (1) is seen in the sqlite db after the test runs.

In this, we can say `experimental.chain` causes the program to run earlier than expected.

The implementation of it involves building a sort of "sub program", and I wonder if this is contributing.

**Comment by onelson** [comment]
With a breakpoint set inside `ExecuteQueries` (the function that runs the SQL for `sql.to`), we can see that the pointer address for `s` (the Op Spec) is the same for both invocations.

In this specific case, the spec pointer address is `0x0010af8c0`.

First time:
![Screenshot_20220113_104546](https://user-images.githubusercontent.com/301388/149390882-1ef32f86-3786-43cb-9881-f227e09aa1e1.png)

Second time:
![Screenshot_20220113_104853](https://user-images.githubusercontent.com/301388/149390950-9e52fda5-7dd4-4d2b-8f1f-bedef7c15a51.png)

I'm not sure what this suggests other than the same node in the resulting plan seems to be running twice. _I assume, a 2nd (separate) call to `sql.to` would have a different pointer address..._

**Comment by onelson** [comment]
Since for now I'm not clear on where to look, I'm unassigning in favor of trying to clear some other tickets.

**Comment by Marwes** [comment]
Dug a little bit further. We interpret the program first and `sql.to` evaluates to a `TableObject` which is passed to `experimental.chain` in addition to this, we add a side effect for `sql.to` to the interpreter. When evaluating `experimental.chain` we evaluate the `TableObject` (thereby evaluating the sideeffect). However the side effect still live on in the interpreter so when evaluating the side effects after the initial interpretation it gets executed again.

Not sure how to fix this, I have tried to convert `chain` into a transformation and while that fixes the double execution I don't see a way to force `first` to execute before `second`. Since the `flux.Table`s that represent `first` and `second` seem to be eagerly evaluated, there is no way for `chain`'s `Process` to force one to evaluate before the other.

**Comment by onelson** [comment]
@Marwes the main concern I've had with this is to understand why this is happening, and to know if there's a correctness issue somewhere that is otherwise hard to observe without this level of isolation. We put this under a microscope, as it were.

In your opinion, are there other situations where this could bite us or is the defect truly limited to `chain` and only `chain`?

**Comment by Marwes** [comment]
If someone implements another builtin like `chain` which evaluates evaluates the `TableObject` internally and also creates a side effect that is evaluated later the same issue will occur. There does not appear to be any other bug.
