### ISSUE TITLE
How to Use math.abs in a flux query

### ISSUE THREAD

**Issue by tasranson** [influxdata/flux#4318]
I am new to flux and struggling with the syntax.   I want to apply the math.abs function to a value before using it a graph + value visual.

In the documentation I can not seem to find a single example that actually uses the function in a query.   I have tried lots of combinations of syntax with no success so far.

Here is the query I have, and all I want to do is take the absolute value before aggregating:
import "math"
from(bucket: "kwe")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "House_Solar")
  |> filter(fn: (r) => r["_field"] == "Site_P_Load")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")

Can you please give me an example of how to apply the math function in this context?

**Comment by sanderson** [comment]
@tasranson This should do it for you:

```js
import "math"

from(bucket: "kwe")
    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
    |> filter(fn: (r) => r["_measurement"] == "House_Solar")
    |> filter(fn: (r) => r["_field"] == "Site_P_Load")
    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
    |> map(fn: (r) => ({ r with _value: math.abs(x: r._value) }))
    |> yield(name: "mean")
```

**Comment by tasranson** [comment]
Scott,

Thanks, that works perfectly.  I am slowly learning the Syntax (its very unusual compared to anything I have coded in previously).

Kind Regards,

Tas Ranson
110 Sheoak Rd
Crafers West, SA 5152
m +61 400 223 502
________________________________
