### ISSUE TITLE
Get daily statistics based on timezone and daylight saving time

### ISSUE THREAD

**Issue by SparkDragon** [influxdata/flux#4332]
## Système

* InfluxDB 2.1 (Docker)

## Description 

I'm trying to create a query with Flux, in order to get the average per hour for a specific day of week. The result should look like this :

| hour | value |
| ----- | ------ |
|   0    |    54   |
|   1    |    37   |
|   2    |    58   |
|   ...    |     ...   |
|   23  |    14   |

Values of different dates should be merged (as long as it's the same day of the week).
For example, I want to now the average value on mondays for each hour.

The problem is that in France, we're having a daylight saving time.
So the offset can vary from +1 hour to +2 hours.

Applying a time shift is not sufficient because even if we're actually at +1h, the query should take into account the time shift for each time stored in the database.

As an example, the daylight saving time changed on october 30th 2021.
Which means that :
 
| Date (UTC) | Day of the week (UTC) | Date (Europe/Paris) | Day of the week (Europe/Paris) |
| --- | --- | --- | --- |
| 2021-10-24 22:00:00 | Sunday | 2021-10-25 00:00:00 | Monday |
| 2021-10-31 23:00:00 | Sunday | 2021-11-01 00:00:00 | Monday |

As you can see, if I want to get the average value for every monday in Paris at 00h00, I must base my query on different UTC hour...

I've read about the doc here : [https://docs.influxdata.com/flux/v0.x/spec/options/#location](https://docs.influxdata.com/flux/v0.x/spec/options/#location)

But it's still not working.

Here is the query I'm using : 

```
import "date"
import "timezone"

option location = timezone.location(name: "Europe/Paris")

from(bucket: "odevia_stats")
	|> range(start: 2021-01-01T00:00:00Z, stop: 2022-01-01T00:00:00Z)
	|> filter(fn: (r) => 
		r._measurement == "section" and
		r._field == "average_speed" and
		date.weekDay(t: r._time) == 1 and
	  r.entity_id == "1"
	)
	|> map(fn: (r) => ({ r with
		time: ((date.hour(t: r._time) * 60) + date.minute(t: r._time)) * 60 + date.second(t: r._time)
	}))
	|> group(columns: ["entity_id", "time"], mode: "by")
	|> mean()
	|> group()
	|> keep(columns: ["_value", "time", "entity_id"])
```

So i'm using the "date" library with "weekDay", "hour", "minute", and "second" functions. But these do not take into account the timezone.

As a more simple example, using the function `date.hour(t: r._time)` with or without `option location = timezone.location(name: "Europe/Paris")` return exactly the same thing.

Is the "location" option used by Flux ? Do you see another way to resolve this problem ?

**Comment by sanderson** [comment]
@SparkDragon There is a known issue about the `date` not supporting the `location` options, but the work to fix that issue is underway. Here is the PR: https://github.com/influxdata/flux/pull/4327.

**Comment by SparkDragon** [comment]
@sanderson Great ! I didn't heard about it. Hope it will be merged soon.

Thank you !
