### ISSUE TITLE
Specifying a start in the future freezes execution

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#434]
From ifql created by [pauldix](https://github.com/pauldix) : influxdata/ifql#250  

Don't have data written in this time frame, but it should be possible to read in the future, or if no results are there, return nothing. This query freezes

```
from(db:"mydb")
  |> filter(fn: (r) => 
                    r["_measurement"] == "cpu" and
                    r["_field"] == "usage_user" and
                    r["host"] == "server0")
  |> range(start:1h)
```

But if I set the start to the past (and there's data there that matches) it returns a result:

```
from(db:"mydb")
  |> filter(fn: (r) => 
                    r["_measurement"] == "cpu" and
                    r["_field"] == "usage_user" and
                    r["host"] == "server0")
  |> range(start:-1h)
```

**Comment by jlapacik** [comment]
The planner will not allow an empty range to be pushed into `from`.
