### ISSUE TITLE
EPIC: Arrays and Streams should be different types

### ISSUE THREAD

**Issue by onelson** [influxdata/flux#4344]
Today `TableObject` implements the `Array` interface but none of the methods are really supported.

We should refactor such that both the Flux and Go type systems can tell the difference between these types to help us avoid runtime panics down the road. 

- #4343
- #4468

**Comment by nathanielc** [comment]
Notes from discussion:

* We need two different kinds of contain types. 
    * An index based container type (like the current type we have)
    * An iteration based container type, i.e. you can get next but not length or index into arbitrary locations
 
How should  we address the delayed/async nature of the new iteration based container type? Should it present a lazy iterator interface? Or should it present an explicit async/await/futures interface?
