### ISSUE TITLE
Query with `range(start:0)` does not complete

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#435]
From ifql created by [rbetts](https://github.com/rbetts) : influxdata/ifql#252  

Using the sandbox this query, using a `range(start:0s)`, does not complete:

  > q=from(db: "telegraf") |> filter(fn: (r) => r["_measurement"] == "cpu" AND r["_field"] == "usage_user") |> range(start:0s) |> group() |> sum()

**Comment by jlapacik** [comment]
`range(start:0)` completes and returns all of the data in the bucket. `range(start:0s)` returns an error because the planner does not allow an empty range to be pushed into `from`.
