### ISSUE TITLE
Address performance concerns with initial meta queries implementation

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#437]
From ifql created by [stuartcarnie](https://github.com/stuartcarnie) : influxdata/ifql#373  

Per notes from https://github.com/influxdata/ifql/issues/358

Our current philosophy:

> Make it functional first, make it performant next

## How does it work today?

* Uses existing `storage.Read` RPC
    * this assumption enabled implementation within < 1 week time frame
* Predicate limits series keys
* Optimize response by setting `PointsLimit = -1`; `Read` API returns `SeriesFrame` type only
    * `TimeRange` supported by decoding first TSM block and returning series keys with point data in specified time range

## Requirements:

* meta queries require time range support
    * currently requires TSM data must be touched

## Problems:

There are limited optimizations for physical planner when querying metadata only

### fetching `keys()`

**Example query:**

```ifql
from(db:"db") 
    |> range(start:-4000h) 
    |> group() 
    |> keys()
```

* no optimal RPC API for only fetching tag keys
    * fetches all series frames based on predicate, iflq must dedupicate
    * potential for large amount of data

### fetching tag values

**Example query:**

```ifql
from(db:"db") 
    |> range(start:-4000h) 
    |> group(by:["_measurement"]) 
    |> distinct(column:"_measurement") 
    |> group()
```

* all series matching predicate are returned
    * in this example, that is _all series keys_
    * ifql only interested in unique `_measurement` tag values

### `keys`

* New RPC to query tag keys

### tag values

* push down combination of `group by` + `distinct` to return series frames with only desired tag key and values

**Comment by nathanielc** [comment]
The specific RPC calls now exist. Further improvements can be treated as new issues.
