### ISSUE TITLE
Feature Request: Support printing other types 

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/flux#4380]
Support printing other types like scalars, arrays, etc. 

Expectation:
When users use any of the following functions:

http.get()
findRecord()
getRecord
findColumn()
usage.limits
...and any other functions I'm missing.
They must construct a temporary table and map the output to it in order to output these other formats. In otherwords they must use either use array.from() and map() or follow the example here:
https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/experimental/http/get/#get-the-status-of-influxdb-oss

Reality:
The query runs, and no output is generated. The extension doesn't provide any errors when running these queries so the users are unaware of the need to search for these hacks. Related to influxdata/ui#1664 and  influxdata/vsflux#234

Proposal
Provide support to print other data types.

**Comment by sanderson** [comment]
@Anaisdg This isn’t a limitation with Flux, it’s a limitation of the InfluxDB query API. It can only return a stream of tables. If you execute these functions in the Flux REPL, it will print the scalar output. I thought there was an issue describing this, but I can’t find it. Should we transfer this issue to the InfluxDB repo?

**Comment by Anaisdg** [comment]
Good idea. Yah I'm aware of the Flux REPL. I wasn't thinking straight this issue should be directed toward influxdb. Thank you. I couldn't find the issue either.
