### ISSUE TITLE
Unable to write data to PostgreSQL from flux task

### ISSUE THREAD

**Issue by vkhazin** [influxdata/flux#4389]
Sample code:

```go
import "sql"

option task = {name: "export-to-rdbms", every: 24h}

connectionString =
    "postgresql://postgres:<secret>@<masked>.us-east-2.rds.amazonaws.com:5432/postgres"

// Reading data works!
// data =
//     sql.from(
//         driverName: "postgres",
//         dataSourceName: connectionString,
//         query: "SELECT measurement, field, value, \"timestamp\" FROM some_table;",
//     )
data =
    from(bucket: "some-data")
        |> range(start: -30d)
        |> map(fn: (r) => ({timestamp: r._time, measurement: r._measurement, field: r._field, value: r._value}))

// Writing data does not work!
data
    |> sql.to(driverName: "postgres", dataSourceName: connectionString, table: "some_table")
```

Error:
```text
Unexpected error from query; Err: failed to initialize execute state: pq: password authentication failed for user "postgres": failed to initialize execute state: pq: password authentication failed for user "postgres"
```

**Comment by nathanielc** [comment]
@vkhazin Thanks for the report, we have a large batch of updates to the `sql.to` and `sql.from` functions in the works. We'll add this bug to the testing to ensure it gets fixed.

**Comment by danatinflux** [comment]
@vkhazin I was able to get this working by removing network restrictions on the AWS/Postgres side:

![image](https://user-images.githubusercontent.com/44617130/148587488-a9238912-8ce9-4c8c-a75e-ef2ed3a52303.png)

Initially, I wasn't able to make connections to my OSS box until I added the top exclusion (with the /32 subnet). That all worked fine. Then, I tried the C2 version and again, no connectivity. However, when I added the very insecure 0.0.0.0/0 source (middle) it started to work.

Unfortunately, we don't currently have a list of IPs that a customer would be able to whitelist at this time as all the IPs for Cloud are dynamic.

**Comment by vkhazin** [comment]
@danatinflux thank you for your comments!
The situation is different for me: the security group is configured for 0.0.0.0/0 access with no success.
And the InfluxDB is able to read data using `sql.from`, which would not be possible with a security group not configured for wide open access.
InfluxDB task with flux is failing to execute `sql.to` command to AWS RDS Postgres and is succeeding with the same command to AWS RDS MySql.
Other than a problem with documented PostgreSql setup or with `sql.to` implementation I cannot explain the observation.

**Comment by danatinflux** [comment]
@vkhazin Please open up a support ticket with your examples so we can test.

**Comment by Marwes** [comment]
> pq: password authentication failed for user "postgres"

Sounds like the postgres instance rejected the credentials. Perhaps the `postgres` user only have read access, but not write access?

**Comment by vkhazin** [comment]
The credentials had been tested with DBeaver client to confirm read and write access is available to the table.

**Comment by Marwes** [comment]
@vkhazin When spinning up a local postgres I am not seeing any issues with writing data to it. So I guess it might be RDS specific, or some other configuration specific to your instance.

**Comment by Marwes** [comment]
@vkhazin It would be helpful if you could make a reproduction for this that I could test. Ideally using a local postgres.

**Comment by vkhazin** [comment]
@Marwes the issue reported is specific to AWS RDS following the documentation from [Influx Data](https://docs.influxdata.com/flux/v0.x/write-data/sql/amazon-rds/)

I don't see other possible explanation to the situation other than:
* there is no support for AWS RDS Postgresql
* the are specific settings required on the Flux side and on the AWS RDS side to resolve configuration issues
* there is a bug in the code preventing the integration from working and it is being resolved

Creating an AWS RDS instance is not a difficult task and does not require a considerable financial burden to reproduce the problem.
Unless the integration is on as-is/best effort basis...
[“The light is much better here”](https://quoteinvestigator.com/2013/04/11/better-light/)

**Comment by abalone23** [comment]
I am able to write to my RDS postgres instance from [InfluxDB Cloud](https://us-west-2-1.aws.cloud2.influxdata.com) Flux v0.150.1:
```js
import "sql"
import "array"

 data = array.from(rows: [
   {url: "http://blah.com", "name A": "blah"}
 ])

data
  |> sql.to(
      driverName: "postgres",
      dataSourceName: "postgresql://postgres:<PASS>@<DB>.us-west-2.rds.amazonaws.com:5432/pgtestdb",
      table: "link table"
)
```

**Comment by nathanielc** [comment]
We are unable to reproduce this issue using the same setup on RDS postrgres. At this point every indication is that the original error message is correct and AWS RDS is rejecting the authentication credentials being passed to it. Please re-check your database credentials and auth configurations. If you learn more specifics about how to reproduce this issue we can reopen the issue and continue our investigation.
