### ISSUE TITLE
Panic with unknown type invalid after experimental.join()

### ISSUE THREAD

**Issue by wfjm** [influxdata/flux#4392]
I'm using InfluxDB V2.1.1 OSS which comes with Flux V0.139 on a Debian 11 system.

The query
```
import "experimental"
offmst = from(bucket: "dca")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "TfcMonitor" and
                       r["host"] == "cbmin00y" and
                       r["_field"] == "offabs")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)
  |> keep(columns: ["_time","_value"])
offend = from(bucket: "dca")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "TfcMonitor" and
                       r["host"] != "cbmin00y" and
                       r["_field"] == "offabs")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)
  |> keep(columns: ["_time","_value", "host", "oid"])
  |> group()
  |> sort(columns: ["_time"])
experimental.join(left:offmst, right:offend,
   fn: (left, right) => ({
     left with
       host: right.host,
       oid: right.oid,
       _value: right._value - left._value
     }))
  |> group(columns: ["host", "oid"], mode:"by")
  |> sort(columns: ["_time"])
  |> yield()
```
gives the desired results and reasonable performance (cpu and memory consumption proportional to row count).
See https://community.influxdata.com/t/23256 which was triggered by https://community.influxdata.com/t/23231.

For large time windows I get **panic: unknown type invalid** and from `syslog` I get the stack
```
 /home/circleci/.tools/go/src/runtime/debug/stack.go:24 +0x65
github.com/influxdata/flux/execute.(*poolDispatcher).Start.func1.1()
 /home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.139.0/execute/dispatcher.go:94 +0x205
panic({0x3beccc0, 0xc003f057b0})
 /home/circleci/.tools/go/src/runtime/panic.go:1038 +0x215
github.com/influxdata/flux/execute.PanicUnknownType(...)
 /home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.139.0/execute/table.go:1134
github.com/influxdata/flux/execute.(*ColListTableBuilder).AddCol(0xc003a96eb0, {{0xc003077ca6, 0x4}, 0xc0006bef40})
 /home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.139.0/execute/table.go:615 +0xa0e
github.com/influxdata/flux/stdlib/experimental.buildSchema(0xc0030b6660, {0x40fa360, 0xc003a96ff0})
 /home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.139.0/stdlib/experimental/join.go:413 +0x173
github.com/influxdata/flux/stdlib/experimental.(*mergeJoinCache).join(0xc00205e960, {0x40f47c0, 0xc004e460f0}, 0xc0012905a0, 0xc003df0900)
 /home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.139.0/stdlib/experimental/join.go:366 +0x2be
github.com/influxdata/flux/stdlib/experimental.(*mergeJoinCache).Table(0xc00205e960, {0x40f47c0, 0xc004e460f0})
 /home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.139.0/stdlib/experimental/join.go:285 +0x85
```
The complete syslog text is attached.
[exp_join_panic.txt](https://github.com/influxdata/flux/files/7828928/exp_join_panic.txt)

Both input tables use
```
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)
```
The panic might be triggered when the first match has an empty row on both input streams, but I haven't tested that.
Fact is, that depending on display window the query works fine (and gives correct answer) or panics.

**Comment by wfjm** [comment]
I've done some more testing. Bottom line is:
- setting `v.timeRangeStart` well before the data series starts triggers a `panic`
- so I assume: when both input streams start with empty `aggregateWindow`'s one gets a `panic`

Background on `createEmpty: true`:
- I need `createEmpty: true` to have proper plots in `Grafana`.  
- that ensures that the data lines are interrupted when no data is available.

**Comment by wfjm** [comment]
I had a brief look at the sources and recent commits to `experimental/join.go`.  
Several of them address panics.  
- adaed42c is the last commit included in `v0.139` handles _"fix(stdlib): fix panic in experimental.join"_
- 73b8181f is the only later commit in `master` and handles _"fix(join): Return error if column not found in schema"_

73b8181f fixes #4310 .  
The problem description of #4310 sounds somehow related to what I've seen.  
However, whether 73b8181f fixes my problem isn't clear to me.

When using `aggregateWindow(..., createEmpty: true)` it is absolutely natural to start with rows with null data.  
This case must therefore be properly handled and valid data must be returned.

**Comment by quentinmit** [comment]
I ran into this as well. As a workaround, you can `filter(fn: (r) => exists r._value, onEmpty: "keep")` on each of the input streams before joining to keep the empty tables but remove the `null` rows. Though I'm not sure if Grafana handles that as desired.

**Comment by wfjm** [comment]
@quentinmit ,
thanks for the workaround.  I've tried a little different:
- used `aggregateWindow(..., fn: mean, createEmpty: false)` to create the streams
- added an `aggregateWindow(..., fn: last, createEmpty: true)` _after_ the `join()` to fill in the empty rows

That gives proper displays in `Grafana` (without lines interpolating missing data) and shows no `panic`.

Playing with and without workaround gives further evidence on what is going wrong:
- one gets a `panic` if `join` sees
  - first some empty rows
  - and later non-empty rows
- one gets no `panic` of the input
  - starts with non-empty rows
  - or has only empty rows
