### ISSUE TITLE
Endless loop when endtime <= starttime 

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#440]
From ifql created by [smallfish](https://github.com/smallfish) : influxdata/ifql#374  

Hi,

When I sent endtime like `|> range(start:1527663670, stop:1527663670)` or less than starttime
 to ifqld(`0.0.6`).

the InfluxDB server will print more logs:

```
[I] 2018-05-30T08:39:22Z request service=storage database=xx predicate=[none] series_limit=0 series_offset=0 points_limit=0 start=1527663670000000000 end=1527663670000000000 desc=false grouping=
[I] 2018-05-30T08:39:22Z request service=storage database=xx predicate=[none] series_limit=0 series_offset=0 points_limit=0 start=1527663670000000000 end=1527663670000000000 desc=false grouping=
[I] 2018-05-30T08:39:22Z request service=storage database=xx predicate=[none] series_limit=0 series_offset=0 points_limit=0 start=1527663670000000000 end=1527663670000000000 desc=false grouping=
[I] 2018-05-30T08:39:40Z request service=storage database=xx predicate=[none] series_limit=0 series_offset=0 points_limit=0 start=1527663670000000000 end=1527663671000000000 desc=false grouping=
```
In https://github.com/influxdata/ifql/blob/v0.0.6/functions/from.go#L153 variable `duration` will `<=0` then next variable `currentTime` will `<=` starttime

and  https://github.com/influxdata/ifql/blob/v0.0.6/query/execute/source.go#L107 will never met:
```
	stop := s.currentTime
	if stop > s.bounds.Stop {
		return nil, 0, false
	}
```
perhaps set default `1` for this?

**Comment by jlapacik** [comment]
The planner will not allow an empty range to be pushed into `from`. This now reports an error immediately.
