### ISSUE TITLE
Get dates with 2 digits when the first one is zero

### ISSUE THREAD

**Issue by acalabrese0** [influxdata/flux#4404]
Hi everyone, I am writing an alert task and in the message that is sent, I'm trying to split the date into separated fields to format it myself. It looks like this:

```
messageFn = (r) =>
    " ... Triggered at ${date.month(
            t: time(v: r._source_timestamp),
        )}/${date.monthDay(t: time(v: r._source_timestamp))}/${date.year(t: time(v: r._source_timestamp))} ${date.hour(
            t: time(v: r._source_timestamp),
        )}:${date.minute(t: time(v: r._source_timestamp))}:${date.second(
            t: time(v: r._source_timestamp),
        )}"
```

But, when for example, the day is between 1 and 9, I'm wanting to print (01,02, etc.) instead of the one-digit alone. There is any way of doing it?

Also, if anyone knows a better way of getting the date and time in a more tidy way, I'll be grateful.

Thanks in advance.

Edit: Now that I'm thinking, does not exist any function that allows us to format date more easily? Maybe I'm overcomplicating things, is just that I haven't found any function like that in the official documentation.

**Comment by sanderson** [comment]
@acalabrese0 This certainly isn't easy to do and I'm hoping something like `fmt()` (https://github.com/influxdata/flux/issues/731) gets added soon. As it currently stands, you can uses the `strings` package to check the length of a string and add a prefix. It's not super clean, but it works.

```js
import "date"
import "strings"

// ...

messageFn = (r) => {
    _prefixZero = (v) => if strings.strlen(v: v) > 1 then v else "0${v}"
    _month = _prefixZero(v: "${date.month(t: time(v: r._source_timestamp))}")
    _monthDay = _prefixZero(v: "${date.monthDay(t: time(v: r._source_timestamp))}")
    _year = _prefixZero(v: "${date.year(t: time(v: r._source_timestamp))}")
    _hour = _prefixZero(v: "${date.hour(t: time(v: r._source_timestamp))}")
    _minute = _prefixZero(v: "${date.minute(t: time(v: r._source_timestamp))}")
    _second = _prefixZero(v: "${date.second(t: time(v: r._source_timestamp))}")

    return  " ... Triggered at ${_month}/${_monthDay}/${_year} ${_hour}:${_minute}:${_second}"
}
```

**Comment by acalabrese0** [comment]
> @acalabrese0 This certainly isn't easy to do and I'm hoping something like `fmt()` (#731) gets added soon. As it currently stands, you can uses the `strings` package to check the length of a string and add a prefix. It's not super clean, but it works.
> 
> ```js
> import "date"
> import "strings"
> 
> // ...
> 
> messageFn = (r) => {
>     _prefixZero = (v) => if strings.strlen(v: v) > 1 then v else "0${v}"
>     _month = _prefixZero(v: "${date.month(t: time(v: r._source_timestamp))}")
>     _monthDay = _prefixZero(v: "${date.monthDay(t: time(v: r._source_timestamp))}")
>     _year = _prefixZero(v: "${date.year(t: time(v: r._source_timestamp))}")
>     _hour = _prefixZero(v: "${date.hour(t: time(v: r._source_timestamp))}")
>     _minute = _prefixZero(v: "${date.minute(t: time(v: r._source_timestamp))}")
>     _second = _prefixZero(v: "${date.second(t: time(v: r._source_timestamp))}")
> 
>     return  " ... Triggered at ${_month}/${_monthDay}/${_year} ${_hour}:${_minute}:${_second}"
> }
> ```

@sanderson Thank you for the response! I will be tracking this from close hoping one day that function is implemented!
