### ISSUE TITLE
EPIC: Create a linter for Flux

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#4414]
We want a way to advise users when their Flux script contains problems that they should fix. Users could run the script through the linter, which would report potential issues.

----
# A List of Common Issues
Feel free to add more below.

## Reusing a source so that filters can't be pushed down
```js
src = from(...) |> range(start: -12h)

src |> filter(fn: (r) => r.foo = "bar") |> yield(name: "bar")
src |> filter(fn: (r) => r.foo = "baz") |> yield(name: "baz")
```
Since the source sends its output to two different filters, the query optimizer won't push either one down into the storage tier.

## group() |> aggregateWindow()
In the Cloud, queries like this can perform poorly
```js
from |> range |> filter |> group(...) |> aggregateWindow(...)
```
It is sometimes good to add in another call to `aggregateWindow` like this
```js
from |> range |> filter |> aggregateWindow(...) |> group(...) |> aggregateWindow(...)
```
(but not always)

**Comment by skartikey** [comment]
I found [Optimize Flux queries](https://docs.influxdata.com/influxdb/v2.1/query-data/optimize-queries/) page in the docs which have a few nice query performance points which can be added to the proposed linter as well.

**Comment by wolffcm** [comment]
We had some discussion about this and talked about two proposals. The question that we're trying to answer here is "how can we better help users find problems with Flux queries?"

----

## Proposal 1: Provide warnings and diagnostics as an output of query planning

The idea here is that we could extend the planner such that when it runs, we can understand which rules did or did not apply, and understand why. We can also look at the output plan for patterns that look suspicious. And then report these diagnostics to the user.

We could do this as a special mode, maybe with a special command line tool that runs a query in no-side-effect-mode, or enable it with an option in a Flux script, or just have (most or some) warnings on all the time.

We already provide a profiler that describes the plan that was executed, and how each operation performed. How would what's described in this proposal work with it?

### Pros:
- The planner (and its rules) are the ultimate decider of what gets executed at runtime, so tying diagnostics to the planner implies that it will be much easier to keep them in lock step.
- The extensible nature of the planner (the rules that can be registered in say OSS vs cloud) would let us tailor diagnostics to particular environments.

### Cons:
- We would only return feedback after the script has executed, since we don't even start planning until we've gotten through the interpretation phase. We don't have a mechanism right now to return warnings to users---it might need to be interleaved in the CSV output of queries?
- Planner rules are platform-specific. OSS has different rules than cloud, etc, so this approach might require extra work for the different platforms.
- In general, we want to move towards writing language analysis code in Rust in `libflux`. This proposal goes in the opposite direction.

-----

## Proposal 2: Find issues by analyzing scripts statically with Rust code in `libflux`.

The idea here is that we can analyze the semantic graph and look for patterns that are suspicious. We can return diagnostics via LSP, where they will be available in any environment that supports the Flux LSP implementation.

### Pros:
- Feedback could be provided statically, without having to execute the script (not even in no-side-effect mode)
- Since analysis is done in `libflux` rather than the planner and its rules, we wouldn't be providing any platform-specific diagnostics. Counting this as a "pro" since we'll provide output that applies everywhere, and code changes would be limited to the flux repo.
- This would put more static analysis code in Rust, which is a direction we want to go.
- We could interleave table stream-related diagnostics with other conventional diagnostics like e.g. "unused import" or "unused variable" which is nice. From the user's perspective, they would benefit from seeing all this feedback in the same place.
- Integration with LSP has a ton of value. We could still write a simple wrapper if we wanted a command line tool as well.

### Cons:
- It's possible that the diagnostics provided via static analysis in Rust are out of step with what the planner actually does. Changes to the planner will sometimes `libflux` updates to keep them in sync.
- If we have cases where we want to provide different diagnostics depending on where Flux is being executed (e.g., OSS vs cloud) then we would have no easy way to do that. Currently the capabilities of the two environments are very close though, and we make efforts to keep it that way.
- Writing the code to analyze a script for table stream functions will be non-trivial. Currently the analysis that discovers how the data flows through a query pipeline is all done in the interpreter; we would need to do something analogous in Rust to discover the structure of the plan graph.

**Comment by onelson** [comment]
Wanted to nitpick these items in proposal 2:

> (pro) Since analysis is done in `libflux` rather than the planner and its rules, we wouldn't be providing any platform-specific diagnostics. Counting this as a "pro" since we'll provide output that applies everywhere, and code changes would be limited to the flux repo.
>
> (con) If we have cases where we want to provide different diagnostics depending on where Flux is being executed (e.g., OSS vs cloud) then we would have no easy way to do that. Currently the capabilities of the two environments are very close though, and we make efforts to keep it that way.

Seems like _it could be possible_ for platforms to supply their own additional lints, depending on how we express them. Designing with for extension, loading rules at runtime, could be a boon.

It might even give OSS users a convenient way to author their own lints, should they feel the need.
