### ISSUE TITLE
Rename json child element field in telegraf.

### ISSUE THREAD

**Issue by parthiuk** [influxdata/flux#4443]
Hi,
SCENARIO:
In my project, I am using health check end point and collect response as follows using telegraf
// http://a.b.c.d:13083/MyApplication/health
{
  "status": "UP"
} 
At telegraf we use following rename and see data loaded in Data.status column in app_health measurement
    [[processors.rename.replace]]
      field = "status"
      dest = "Data.status"

ISSUE:
when we upgrade our actuator(2.5.5 / 2.6.0) and jolokia(1.7.1) to match with latest spring version, our health check response is thrown as
// http://a.b.c.d:13083/MyApplication/health
{
  "groups": [  ],
  "status": {
    "code": "UP",
    "description": ""
  }
}
Since status is splitted as "status / code", my rename config is skipping the above response and no data is added into influxDB.

Can you please tell me
1) How can I change the latest health response, to match  with the original one. {"status": "UP"}
2) OR is there a way I can use [[processors.rename.replace]] to collect the "code" field from latest response and save to "Data.status" I've tried  following options under [[processors.rename.replace]].  But, it wasn't success, kindly help.
      a) field = "code"
      b) field = "status.code"
      b) field = "status/code"

**Comment by parthiuk** [comment]
I also tried   [[processors.rename.replace]] with, still it wasnt helpful.
      d) field = "status_code"
      e) tag = "status_code"
      f)  tag = code

**Comment by sanderson** [comment]
@parthiuk This question/issue is specific to Telegraf and should be added to the [Telegraf repo](https://github.com/influxdata/telegraf). I'm closing this issue here, but please do [recreate in the Telegraf repo](https://github.com/influxdata/telegraf/issues/new/choose/).
