### ISSUE TITLE
Really need to improve the type mismatch error messages

### ISSUE THREAD

**Issue by rickspencer3** [influxdata/flux#4451]
For example, if I try to pass a dictionary into ```array.from(rows: [some_dict])```

The error I get back is:
``` 
error @13:18-13:30: expected [A] but found [string:string] (argument rows)
```

Could we not tell the user what the allowable types are, and that the wrong type was? Also, maybe suggest some casting if it is available?

**Comment by Marwes** [comment]
cc https://github.com/influxdata/flux/issues/4264
