### ISSUE TITLE
Add `csv.encode` to be able to efficient construct CSV data from tables

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#4457]
Users would like to construct arbitrary CSV data from tables in order to interact with third party APIs. Much like `json.encode` allows for users to send JSON structures to HTTP endpoints we should have an equivalent `csv.encode` function.

**Comment by Anaisdg** [comment]
It would be nice to be able to construct CSV from an entire table rather than passing individual records and using reduce to summarize all of the information in a table before passing it to json.encode.
