### ISSUE TITLE
EPIC: Skipping flux acceptance tests should be easier

### ISSUE THREAD

**Issue by onelson** [influxdata/flux#4490]
While the core conceit in the title could be seen as controversial (we don't want folks to skip tests on a whim), we've reached a point where the ergonomics around skipping are causing friction.

Increasingly, we've got flux tests that can only run in certain situations. Sometimes extra services are required, sometimes depending on the storage mode being used.

Today, we curate long (1,000+ column) skip lists, represented as comma-separated test case names and have resorted to hoisting partial lists into environment variables just to get by.

These long lines are difficult to read in code review and tend to need to be copy/pasted across different CI jobs depending on how the test command is invoked in each case.

n.b. skip lists are _often specific_ to a particular _environment_. The new system should go out of its way to make it convenient for one environment to skip certain tests, whereas another won't.

Some tests (such as RDBMS integration) may need to always be opt-in since they are intended for local dev workflows.

---

One proposal to ease this effort could be to allow the lists (as they are expressed now) to be defined as line-delimited files (one test name per line).

Another might be to allow the names to be specified using wildcards or regex.

Other proposals are welcome!

---

With the accepted implementation plan outlined in the ([comments below](https://github.com/influxdata/flux/issues/4490#issuecomment-1068521628)), the work as been broken down as follows:

- https://github.com/influxdata/flux/pull/4559
- https://github.com/influxdata/flux/issues/4574
- https://github.com/influxdata/flux/issues/4575
- https://github.com/influxdata/flux/issues/4576
- https://github.com/influxdata/flux/issues/4577
- https://github.com/influxdata/flux/issues/4578

**Comment by jsternberg** [comment]
For this issue, we will need to establish a working group to determine the proper way to filter these tests for a specific environment. If you pick this up, organize a group related to this and then either create issues if it is more expansive or record the method that we will use to fix this.

The primary requirement is that it has to be easy to filter out specific tests so that we can use `fluxtest` on the command line again. Right now, you have to copy/paste a long list of test names from the CI file if you want to run them locally.

It also is needed that we will need to be able to define a test in one environment and skipped in another.

**Comment by onelson** [comment]
The following notes were captured during a working group discussion. Seems like we got a reasonable proposal out of it, and so this issue will be updated to outline the implementation plan based on this.


# Considered implementations

We kicked off the discussion around 4 possible paths:

- updating `--test` and `--skip` to allow wildcards or regex
- adding new flags like `--test` and `--skip` that could read test names from files
- using a tagging concept (tests carry a list of tags, flags added to filter tests by tag)
- additions to the stdlib like `testing.skip(reason)` or `testing.skipIf(pred, reason)`

## Rejected: Wildcards, Files, stdlib additions

The first two options felt mostly as though they were sweeping the current problem under the rug.

Wildcards and regex felt like they would raise the chance of accidentally disabling tests that happened to be named a certain way. Using naming conventions being an implicit grouping mechanism, we can probably push for something more structured (and more useful).

While files defining lists of tests could help readability, the maintenance burden is similar to now. PRs would still be required in multiple repos to manage things properly.

Additions to the stdlib to allow tests to skip conditionally felt like they didn't quite solve the problem, and in fact would raise complexity of the change considerably. For example, for something like `testing.skipIf(pred, reason)` were added, the predicate function passed into this call would need to know how to decide if the test should run. Usually this wouldn't be known by fluxtest -- this is information only available outside the process (ie whoever is invoking it).

Going this route seemed like the heaviest lift, and may not even give the most desirable outcomes.

## Accepted: Tagging

Tagging seemed to fit the problem neatly enough, with only a few hurdles to clear (ref: https://github.com/influxdata/flux/pull/4559).

The "short version" of the plan is:

- add an `option` to the `testing` package called `tags`, initialized as an **empty array**.
- tests that set this option will _only run if one of the values is specified as a flag_ to the harness (ie, tags are an opt-in).
- tags are conjunctive, which is to say they are AND'd together to _narrow the test selection_, not _widen_.
- untagged tests will always run (optionally add a flag to skip untagged?)

The conjunctive nature of how tags will be applied _may cause us to need to invoke `fluxtest` repeatedly_ in certain situations depending on the shape of the taxonomy, but it seems like a reasonable mode to start with and should cover the real-world usage today.

Care should be taken to account for how tags will interact with existing methods for test selection and filtering. For example, tests named specifically with the `--test` flag should likely run, regardless of any tags specified.

In addition to the new tagging system, some further updates to the test harness will be required to improve audit potential.

- report skipped tests (by count and by name, based on the verbosity)
- `fluxtest.root` to be used to list **valid tags**
- the **valid tag** lists should be merged (ie, multiple root files may appear based on the number of paths specified with the `-p` flag)

### Concerns about Test Loss

During the working group, we identified a risk of accidentally skipping tests. We discussed mitigation steps to avoid tests running locally, then mysteriously going silent in CI.

Consider this hypothetical:

- we add a test with the tag "alerts"
- CI is only looking to run tests with the tag "alerting" in the job where we had _intended the test to run_.

In this situation, we'd have a test that would not run during a `fluxtest` run where no tags are selected, nor would the test run in CI where we'd hoped it would run. The test would essentially become dead code.

While it's true there's nothing to ensure all tagged tests are ever run, the concept of **valid tags** was pitched as a safeguard against typo'd tag names, etc.

How it could work:

- specify a list of tags you intend to use in the root file
- during test discovery, tests found with unexpected tags generate errors
- unexpected tags specified on the command line would also generate errors

If no valid tags list exists for a given root, I'm not sure what the correct outcome is. I want to say "all tags are considered legal" in this case, but this might complicate the multi-root scenario depending on how it's implemented.

With the **valid tags** device, we can hopefully funnel developers into using the same consistent set of tags. By merging these lists from different roots, we should be able to avoid cascading PRs across repos.

### Concerns about Auditing

Part of the balance we want to strike here is to make it easier to skip categories of tests, but also to be able to track how many things are being skipped and more to the point *to realize when more and more things are being skipped*.

The number of skipped items is a good signal to have some visibility of.

Currently, we've got visibility in terms of the length of the argument we give to the `--skip` flag, but it's actually not that useful on it's own. I have no sense of the overall count, only that the line is 1,000+ characters wide! Splitting the list as it is now across a series of env vars, only to combine them again, obfuscates even this weak signal.

With various tags spread out across the test sources, getting a good sense of what tests are being filtered out will only be possible via tooling, probably by instrumenting `fluxtest` itself.

Some feature work focused on the reporting/feedback capabilities will therefore be required. We already flagged this as a need, but a tag implementation as being proposed heightens the urgency.

In addition to reporting which tests are skipped (or not), we may also want some general reporting tools to show test counts per tag and so on.

**Comment by wolffcm** [comment]
So if I understand right, say if we want to skip tests that require an instance of MQTT to be up and running, we would add to the test file (or maybe the `testcase` block to get more granular) a line like
```
option testing.tags = ["needs_mqtt"]
```
And then in the `flux/stdlib` we would add a file called `fluxtest.root` that contains something to indicate the existence of `needs_mqtt` as a tag.

Finally when we run `fluxtest` we only run the MQTT tests if we run it like `fluxtest --tags needs_mqtt`.

Do I have this right?

**Comment by onelson** [comment]
Yes, I think that's right.

The most common case for us would be to model tags based on external dependencies, such as services that need to be running ahead of the test run.

Supersets of these could be defined, eg: `["needs_mqtt", "external_svc_integration"]`. This allows us to target just the mqtt tests but also the larger set of docker-based integration tests.

I could definitely see a more complex CLI for expressing tag selection down the road to allow us to mix/match conjunction and disjunction.

I named `fluxtest.root` specifically because it came up as a thing during the working group discussion. I'm not sure if this is actually something fluxtest has any awareness of today, but I think it did at one point since I saw a file with this name in _other environments_.

**Comment by onelson** [comment]
N.b. this issue was converted to an epic after discussing the implementation plan. The status is "done" in the project, not because all the work is completed, but because the plan is now in place (as tracked tickets). We'll leave the issue open until the tracked work is finished, for visibility.
