### ISSUE TITLE
trimLeft is not trimming correctly

### ISSUE THREAD

**Issue by 8none1** [influxdata/flux#4491]
I am using this query to edit some data and remove a leading bit of unwanted text:

```
import "strings"

from(bucket: "HA_Pi_Bucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "mqtt_consumer")
  |> filter(fn: (r) => r["_field"] == "battery_low")
  |> map(fn:(r) => ({ r with 
   _value: int(v: r._value),
   ttopic: strings.trimLeft(v: r.topic, cutset:"zigbeeha/trv/")
   }) )
  |> fill(column: "_value", usePrevious: true)
```

In some cases but not all, it is removing too much text.  

For example:

`zigbeeha/trv/hall` is being trimmed to `ll` :x: 
`zigbeeha/trv/ted` is being trimmed to `d` :x:
`zigbeeha/trv/study` is being trimmed to `study` :heavy_check_mark: 

I have attached a CSV of results to show this in a bit more detail.
[2022-02-16_10_48_influxdb_data.csv](https://github.com/influxdata/flux/files/8079241/2022-02-16_10_48_influxdb_data.csv)

I can give access to my C2 account if anyone needs it.

**Comment by rbetts** [comment]
Functions as designed.
https://go.dev/play/p/E7WPt1ZV2j2

**Comment by skartikey** [comment]
@8none1 Looking at the example above, you might want to use [TrimPrefix](https://docs.influxdata.com/flux/v0.x/stdlib/strings/trimprefix/) instead [TrimLeft](https://docs.influxdata.com/flux/v0.x/stdlib/strings/trimleft/). 
https://go.dev/play/p/fPGzuoqmZww
