### ISSUE TITLE
Support stable column order

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#451]
We want the order of columns on a table to be stable. Meaning that the order only changes if it was explicitly requested.

To accomplish this:

* Object types in the language need to be ordered, as defined by the order of keys in the object literal. What does this mean for objects that were not created as a literal?
* The map function needs to use the order of the object literal. If mergeKey=true then all partition keys columns come first. 
* Should the group and sort functions reorder columns to be in sort order from left to right?

**Comment by SCHKN** [comment]
Would love to see a way for us to order columns in a flux request.

Any ways for the flux request to order the columns as they were declared in a keep function?

**Comment by nathanielc** [comment]
Using keep seems like a good idea for forcing an order when we otherwise would not know an order. Thanks!
