### ISSUE TITLE
Test Rust API docs build in CI

### ISSUE THREAD

**Issue by pierwill** [influxdata/flux#4517]
On current master, `cargo docs` is failing. https://github.com/influxdata/flux/pull/4516 fixes this, but I think we should be testing for these failures.

I'd suggest the following change [here](https://github.com/influxdata/flux/blob/185b35f6f887f5aedfd60f8074153ae2d6bb61c1/Makefile#L129-L132):

```diff
 test-rust:
 	cd libflux && $(CARGO) test $(CARGO_ARGS) --all-features && \
+	$(CARGO) doc && \
 	$(CARGO) test --doc && \
 	$(CARGO) clippy $(CARGO_ARGS) -- -Dclippy::all -Dclippy::undocumented_unsafe_blocks
```

**Comment by onelson** [comment]
This seems like a good change to me. If possible, we might pass the `--no-deps` flag to reduce the amount of stuff we build docs for, and therefore the build time.
