### ISSUE TITLE
Use the names select/reject instead of keep/drop.

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#453]
The name `drop` has the connotation that data is removed. Data is being "dropped" for an in mem table, but not from the actual data store. In order to avoid this confusion, we should use the names `select` and `reject` instead of `keep` and `drop`.

**Comment by aanthony1243** [comment]
giving this a 5 because these are popular functions and it may take some time to transition users before we deliver this one.

**Comment by aanthony1243** [comment]
revising my estimate.  Consider designing this to be backward compatible/non-breaking by 
1.  rename actual functions drop/keep   to select/reject
2.  add aliases to `universe`:  `drop = reject`  and `keep = select`

at some point it'd be nice to give a warning about deprecated function names but we don't have a warning channel.

**Comment by nathanielc** [comment]
@aanthony1243 Should we just not do this? We haven't had any feedback in a while that the keep drop names are confusing.

**Comment by russorat** [comment]
let's not do this.
