### ISSUE TITLE
Question: How to write a reduce function that works in a similar way to `histogram()`?

### ISSUE THREAD

**Issue by teodorkostov** [influxdata/flux#4531]
Let's check the following example:

```flux
from(bucket: "example-bucket")
    |> range(start: -1m)
    |> filter(fn: (r) => r._field == "A" or r._field == "B")
    |> pivot(rowKey: ["_time"], columnKey: ["_field"], valueColumn: "_value")
    |> histogram(bins: [0.0, 5.0, 10.0, 20.0], column: "A")
```

But, instead of adding `+1` if the value in column `A` is in that bin, I would like to add the value of column `B` to the result of that bin. How can I do that with Flux?

PS: I tried using reduce with a dictionary property in the identity record. Unfortunately, that is not possible.

```flux
...
    |> reduce(
        fn: (r, accumulator) => ({ ... }),
        identity: {dict: []},
    )
```

**Comment by wolffcm** [comment]
Hi @teodorkostov, I wonder if you can append another call to `pivot()` to get the behavior you want?

Here's an example of using `pivot()` to get all the bins into the same row:
```js
import "sampledata"
sampledata.float() 
  |> group() 
  |> histogram(bins: [-5., 0., 5., 10., 20.])
  |> pivot(valueColumn: "_value", rowKey: [], columnKey: ["le"])
```

**Comment by wolffcm** [comment]
The input to the above query is:
```
sampledata.float() |> group() |> sort()
Result: _result
Table: keys: []
                    _time:time              tag:string                  _value:float
------------------------------  ----------------------  ----------------------------
2021-01-01T00:00:20.000000000Z                      t2                         -3.75
2021-01-01T00:00:00.000000000Z                      t1                         -2.18
2021-01-01T00:00:50.000000000Z                      t2                          1.86
2021-01-01T00:00:50.000000000Z                      t1                          4.43
2021-01-01T00:00:10.000000000Z                      t2                          4.97
2021-01-01T00:00:20.000000000Z                      t1                          7.35
2021-01-01T00:00:10.000000000Z                      t1                         10.92
2021-01-01T00:00:40.000000000Z                      t2                         13.86
2021-01-01T00:00:40.000000000Z                      t1                         15.23
2021-01-01T00:00:30.000000000Z                      t1                         17.53
2021-01-01T00:00:30.000000000Z                      t2                         19.77
2021-01-01T00:00:00.000000000Z                      t2                         19.85
```
and the output is
```
sampledata.float() |> group() |> histogram(bins: [-5., 0., 5., 10., 20.]) |> pivot(valueColumn: "_value", rowKey: [], columnKey: ["le"])
Result: _result
Table: keys: []
                -5E+00:float                   0E+00:float                   5E+00:float                   1E+01:float                   2E+01:float
----------------------------  ----------------------------  ----------------------------  ----------------------------  ----------------------------
                           0                             2                             5                             6                            12
```

**Comment by teodorkostov** [comment]
Hey @wolffcm. Thanks for your answer.

Unfortunately I would like to achieve something else. Let me give a some data as an example.
```
time       A       B
 ...       1     0.1
 ...       2     0.2
 ...       3     0.3
 ...       1     1.1
 ...       2    -1.3
 ...       3   -0.15
```

I would like my bins to be `[1, 2, 3]`. Then `histogram()` would calculate that the result for each bin based on column `A` is `2`. However, I would like the result to be the `sum()` of all values in column `B`.
```
time  _value
 ...     1.2    # 0.1 + 1.1
 ...    -1.1    # 0.2 - 1.3
 ...    0.15    # 0.3 - 0.15
```

PS: Histogram is correctly implemented just to increase the counter (check [here](https://github.com/influxdata/flux/blob/24fe9cc8699c4bb8338771b57888050976a60a29/stdlib/universe/histogram.go#L205)). What I would like to do is similar to how histogram works but not exactly.

**Comment by wolffcm** [comment]
@teodorkostov Thanks for the clear explanation, I think I understand what you want now.

You could do something like this:
```js
import "array"
array.from(rows: [
  {A: 1, B: 0.1}, {A: 2, B: 0.2}, {A:3, B: 0.3},
  {A:1, B:1.1}, {A:2,B:-1.3},{A:3, B:-0.15}
]) 
  |> group(columns: ["A"]) 
  |> sum(column: "B") 
  |> group()
```
which produces
```
Result: _result
Table: keys: []
                     A:int                       B:float
--------------------------  ----------------------------
                         1            1.2000000000000002
                         2                          -1.1
                         3                          0.15
```
The only problem is the time column; I'm not sure what you would want the time to be, since each row in the output could be an aggregation of several rows from the input. `sum()` will typically drop any columns that are not in the group key for this reason. To define customer behavior, you could use `reduce()`.

Note that if A was, say `float` you could still group my calling map first, e.g., `|> map(fn: (r) => ({r with A: math.trunc(r.A)})) ...` so you can create whatever bins you want that way.

Does this get you closer to what you need?

**Comment by teodorkostov** [comment]
Hey @wolffcm. This is exactly what I needed. It is perfectly normal that the time column is removed.

```flux
  |> map(fn: (r) => ({r with trunc: math.trunc(x: r.A / 10.0) * 10.0}))
  |> group(columns: ["trunc"])
  |> sum(column: "B")
```

I also tried adding the last `group()` call. However, I do not see any difference in the result.

Thank you very much for the help. All the best!

**Comment by wolffcm** [comment]
Glad to help! The final call to `group()` removes all the columns from the group key so they are in the same table rather than one table per unique value of `A`. Depending in your application this may not matter to you.
