### ISSUE TITLE
Add funcs for duration/time operations to date package

### ISSUE THREAD

**Issue by OfTheDelmer** [influxdata/flux#4542]
Use the more canonical  `date` package for operations between `time` an `duration`.  These utilities will take us closer to builtin support for `+/-` operator support. 

Note:

There will be edge cases to consider between date/duration operators to document and test. Durations don't form a great basis for time, e.g. adding `1mo` to time in a month with 28, 29, 30, or 31 days.

DOD:

 - Promote the experimental.addDuration family of functions to the `date` package.
 - Choose better names for the functions to make them more concise
 - Update docs to use new names and import path
 - Update olds experimental docs to note the functions are deprecated and that users should use the new names.
 - Refactor stdlib to use new functions everywhere

**Comment by sanderson** [comment]
I think it would be understandable (probably even expected) to restrict +/- operations to only fixed duration units. So if you did something like `now() - 1mo` or `now() - 1y`, you would get an error like:

```
invalid expression: arithmetic operations do not support variable duration units (mo, y)
```

**Comment by nathanielc** [comment]
Note to whom ever grabs this issue: When you deprecate the old experimental functions please add a `deprecated` tag using this workflow https://github.com/influxdata/flux/pull/4558. I'd like to validate that this workflow is indeed useful and we want to ensure that we are marking promoted experimental functions as deprecated.
