### ISSUE TITLE
Create Demo for Vectorize Map

### ISSUE THREAD

**Issue by onelson** [influxdata/flux#4573]
refs: #4028

With the vectorized map work as it is today, design a demo to show it working (to whatever extent we can).

DOD:
- Demo vectorized compiler working in production behind the feature flag.

**Comment by nathanielc** [comment]
Just watched the demo looks great! Can we also get a demo of this working in production? I guess we forgot to mention it in the issue :( but that was the driving force for the issue to figure out why it wasn't working in production when it was tested.

**Comment by jsternberg** [comment]
I was able to manually verify that the feature flag works in tools. I will also enable for production on Monday. I'm going to close this and keep a personal note to toggle it then.
