### ISSUE TITLE
findRecord not evaluating as expected within utility function for aggWindow

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/flux#4590]
The following flux is expected to yield the first - last value for each time window specified in aggregateWindow(). Instead it returns the sam value across all rows:
```
my_func = () => (column="_value", tables=<-) => {
firstValue = tables 
  |> first()  
  |> findRecord(fn: (key) => true, idx: 0)

lastValue = tables 
  |> last()  
  |> findRecord(fn: (key) => true, idx: 0)

acc = firstValue._value - lastValue._value

output = tables |> map(fn: (r) => ({ r with _value: acc }))
return output 
}

data = from....   |> aggregateWindow(every: v.windowPeriod, fn: my_func(), createEmpty: false)
```

Thanks!

**Comment by wolffcm** [comment]
Ultimately this produces the desired answer:
```
my_func = (tables=<-, column="_value") => 
  union(tables: [tables |> first(column), tables |> last(column)]) 
  |> sort(columns: ["_time"])
  |> difference(columns: [column])

```
But it seems like `findRecord` has a lot of confusion over how/when it gets evaluated.

**Comment by Anaisdg** [comment]
@wolffcm That produces this error:
`error @12:47-12:56: missing required argument tables error @12:47-12:56: expected (<-:stream[B], column:A) => stream[C] (function) but found stream[D] (argument fn)
`
