### ISSUE TITLE
contrib/sranka/sensu: allow specification of timestamp/issued/executed for Sensu event

### ISSUE THREAD

**Issue by bo0ts** [influxdata/flux#4596]
Unfortunately Sensu will default the `timestamp`/`issued`/`executed` fields of an event created via API to `0`. This makes the event a lot less useful in Sensu (timeline broken, last OK broken etc.).

Users can specify timestamps manually when creating events via API to work around this and the influx package could support that.

**Comment by bo0ts** [comment]
Pining @sranka as the author of that package.

**Comment by sranka** [comment]
I see that the `0` default is now documeted in https://docs.sensu.io/sensu-go/latest/api/core/events/#create-a-new-event .  https://github.com/influxdata/flux/blob/master/stdlib/contrib/sranka/sensu/sensu.flux will require some changes to fix it. The default value should be set by the library to `int(v: now())/1000000`

**Comment by bo0ts** [comment]
Yes, and after some testing I think it is necessary to allow setting other time related fields `issued`, `excuted`, and `lastok` as well.

**Comment by sranka** [comment]
@bo0ts I think that you can copy-paste and enhance the `event` function from  https://github.com/influxdata/flux/blob/master/stdlib/contrib/sranka/sensu/sensu.flux in your script, until this is resolved. It may take a while.
