### ISSUE TITLE
The initial value is not 0.

### ISSUE THREAD

**Issue by AmyJiangWenyan** [influxdata/flux#4605]
If the initial value is not 0, the difference between the calculated value and the expected value will be different

**Comment by qs-wang** [comment]
Try to clarify it a little here. 
While we add a new meter into the system ideally the number on the meter is zero however it most likely the meter has a init value which is not Zero. 
With current initialZero parameter for difference I can see it cannot support 2 cases here.
1. it's no way to specify the init value as non-zero which is the case as above

**Comment by nathanielc** [comment]
Can you share an example query with results and how you would prefer the results to work?

**Comment by AmyJiangWenyan** [comment]
I started one power meter on April 6 and I want to know the daily electricity consumption from  April 6  to today, I use following query:
‘’‘
from(bucket: "qidi-1h")
  |> range(start: time(v:1649174399000000000), stop: time(v:1649865599000000000))
  |> filter(fn: (r) => r["_measurement"] == "ActiveEnergyTotal")
  |> filter(fn: (r) => r["_field"] == "value")
  |> filter(fn: (r) => r["building"] == "qidi")
  |> filter(fn: (r) => r["channel"] == "Level_Power_Meter")
  |> filter(fn: (r) => r["device"] == "Power_Meter_SIM-L5-Level_Power_Meter-25")
  |> aggregateWindow(every: 24h, fn: last, createEmpty: false, offset: -8h)
  |> difference(keepFirst: false, columns:["_value"], nonNegative: true)
  |> yield(name: "last")
’‘’
I got this result:
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/72910797/163092525-ab88f0ff-6c62-4edf-979d-91e86a5ba584.png">
It didn't have the value of April 6, but the expected value of 04/06 was "940.45", refer to the attachment:
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/72910797/163092983-a487676a-2200-46c6-971b-2fbeec30ea45.png">
