### ISSUE TITLE
Return a more helpful error message to the user when an http response exceeds 100MB

### ISSUE THREAD

**Issue by scbrickley** [influxdata/flux#4607]
The flux http client [limits response sizes](https://github.com/influxdata/flux/blob/b1b083c140a2c1c12d95ee7665ae08bc5c862f4d/dependencies/http/http.go#L18) to 100 MB. If a user runs a query that results in large http response, the resulting failure can manifest in a number of different error messages for the user, not all of which are helpful in effectively communicating the actual problem.

We should return a clearer error message in the case of a large http response... one that makes it obvious that the user needs to somehow reduce the amount of data that they're querying.

**Comment by wolffcm** [comment]
One possible manifestation of this is truncated CSV, which produces a confusing error.
