### ISSUE TITLE
Add a planner rule that removes unnecessary `sort` nodes

### ISSUE THREAD

**Issue by scbrickley** [influxdata/flux#4628]
Blocked by #4678

In issue #4627, a new rule was added to the planner that ensures a physical `sort` node always precedes a `sortMergeJoin` node. It's possible, however, that the data to be passed into `join` is already sorted. We should add a planner rule that detects whether or not this is the case, and if so, removes the unnecessary sort node.

The logic should go as follows:
- Data that comes from storage is already guaranteed to be sorted by time (and possibly other columns)
- The planner should be capable of determining which nodes disrupt that sorting (see #4678)
- Therefore, if we look at all the nodes between the storage read and the `join` and find none that disrupt sorting, we can remove the previously inserted `sort` call.

It is not necessary to close this issue before work on the actual implementation of the `join` package (#4629) begins.

Some implementation notes:

- We need the ability to track attributes of plan nodes, some recent work re parallel nodes has created a foundation for this already
- We need these attributes to be parameterized (i.e. a list of sorted columns)
- The mergeSortJoin node requires that left and right predecessors are sorted in the same way according to the mapping of equi join columns. 

DOD:
- The planner rule described above exists and is used by the planner

**Comment by wolffcm** [comment]
This work is currently in review in a couple PRs. I am changing the estimate to `1` to reflect this moving into the next sprint.

**Comment by wolffcm** [comment]
This is all done and the feature flag for it has now been removed.
