### ISSUE TITLE
Add a `join` package to stdlib

### ISSUE THREAD

**Issue by scbrickley** [influxdata/flux#4629]
Create a new package in the flux standard library called `join`. The package should expose a builtin function called `join` that implements the sort-merge join algorithm, and supports inner, outer, left, and right joins. The function signature should be as follows:

```
builtin join : (
    <-left: [L],
    right: [R],
    predicate: (l: L, r: R) => bool, // consider renaming this `on`
    fn: (l: L, r: R) => A, // consider renaming this `as`
    method: string, // can be "inner", "outer", "left", "right"
) => [A] where
    A: Record,
    L: Record,
    R: Record
```

In the interest of preserving the performance of `experimental.join()`, the underlying implementation should assume that the input tables are sorted and grouped, and should only ever compare records that have the same group key.

The package should also expose a few other convenience functions: `time()`, `inner()`, `outer()`, `left()` and `right()`, each defined in terms of the `join` builtin. They should be defined as follows:

```
// Functionally identical to `experimental.join()`
time = (left=<-, right, fn, method="inner") => join(
    left: left,
    right: right,
    predicate: (l, r) => l._time == r._time,
    fn: fn,
    method: method,
)

inner = (left=<-, right, predicate, fn) => join(
    left: left,
    right: right,
    predicate: predicate,
    fn: fn,
    method: "inner",
)

outer = (left=<-, right, predicate, fn) => join(
    left: left,
    right: right,
    predicate: predicate,
    fn: fn,
    method: "outer",
)

// You get the idea
left = ( ... ) => join( ... )
right = ( ... ) => join( ... )
```
Any go unit tests or flux acceptance tests that we use to validate the other join implementations should be adapted to validate the behavior of the new `join` functions.

New test cases should be added to confirm the correctness of outer, left, and right joins.

Additionally, the package author should confirm (either through go unit tests or flux acceptance tests) that any known and unresolved bugs in the other join implementations are not present in the new `join`.

It is not necessary to evaluate or compile the `predicate` function in the transformation itself. Rather, assume that the planner rule added in #4625 has run and has passed both of the following to the transformation:
- a bool indicating whether or not this is an equi-join
- a list of tuples, each of which contains a column name from the left table, and the name of the column in the right table that it should be compared to.

If the first is `false`, the join transformation should return an error informing the user that non-equi-joins (i.e., joins on unequal columns) are not yet supported.

If it's `true`, the transformation should use the given column names to join the table streams.

We should also add benchmarks to compare the performance of the new `join` to the old join implementations, where relevant.

ADDENDUM: It's possible that we could see performance gains in the new `join` by using table chunks instead of full tables.

DOD:
- A `join` package that matches the above description has been added to the standard library
- We have the suite of tests described above, and they all pass
- Benchmarks confirm the new join implementation is at least as performant as `experimental.join`
- **inner and left only**

**Comment by onelson** [comment]
We need new issues for `inner`, `right`, `outer`.

**Comment by wolffcm** [comment]
Can we make some adjustments to how we specify join types in the new package? I find it very confusing to refer to `outer` joins when we really mean the SQL concept of a `FULL OUTER JOIN`. Left and right joins are also types of outer join.

For context, ANSI SQL syntax allows for `inner`, `left`, `right`, and `full`, with `outer` being an optional keyword for the last three:
https://docs.actian.com/vector/4.2/index.html#page/SQLLang/ANSI_2fISO_Join_Syntax.htm

Maybe our join types should be `inner`, `left`, `right`, `full` to follow suit?

**Comment by scbrickley** [comment]
@wolffcm That seems reasonable to me.
