### ISSUE TITLE
Specify the primitive types that make up stream and table types

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#463]
Stream and Table types should be described in terms of more primitive types.

For example a stream type could be defined as:

```
{
    "tables": generator of Table
    "key": {...} // definition of group key
}
```

A table type could be defined as:

```
{
    "schema": { ...} // definition of table schema
    "records": generator of Objects
}
```

These types are just first pass, since Flux does not have named types this is a little hard to describe. (edit: Well, Flux has named types, just not the ability to create new named types at runtime, so we should be able to create built in types `table` and `stream`)

We need to update the SPEC with the types we choose.

**Comment by mkarlesky** [comment]
@nathanielc I submitted a [relevant issue](https://github.com/influxdata/docs-v2/issues/1958) over in the documentation project after wrestling with some aspects of the published Flux docs. If my comments over there are, in fact, helpful then they may also apply to terminology in the core Flux project such as what your issue deals with here.
