### ISSUE TITLE
Deprecate old join functions

### ISSUE THREAD

**Issue by scbrickley** [influxdata/flux#4630]
Once the new `join` package is available to users, we want to ~force~ *gently convince* them to switch away from `universe.join()` and `experimental.join()`, and to instead use the new implementation.

There are many ways we could do this, including but not limited to:
- Informing them of the deprecated functions via the LSP
- A concerted messaging campaign from product/dev-rel
- Marketing for the new join package (see #4633)

I'm sure there are other ideas that would work too. Go nuts.

DOD:
- Messaging is in place to ensure flux users far and wide know that there's a new `join` in town, and feel considerable shame for not using it
- New tasks will emerge from discussion - likely this issue will just track that work.

**Comment by onelson** [comment]
Possible way to prompt users to update their usage to the new API via LSP (_four ways?!_)

**Comment by nathanielc** [comment]
We have deprecated the old join function in the docs. We will improve the visibility of deprecation warnings with future enhancements.
