### ISSUE TITLE
Add `extend` mode to `universe.group`

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#4638]
We've had `experimental.group` for a long time. All it does is provide an `extend` mode to add a column to the group key. I've gotten positive feedback on it. That was a few years ago. We should add `extends` mode to `universe.group` and make `experimental.group` just call that one.

DOD:
- add `extends` mode to `universe.group`
- make `experimental.group` just invoke `universe.group`

**Comment by sanderson** [comment]
Yes! Please! One other mode that was proposed in https://github.com/influxdata/flux/issues/2007 but never tested is a `remove` or `subtract` mode that removes specified columns from the group key. I wouldn't be against this being included in this change, but you could always leave it in experimental.

**Comment by wolffcm** [comment]
An additional benefit to folding `extend` into `universe.group` is that it can use the modern transformation implementation that that produces table chunks.
