### ISSUE TITLE
Flux function for Base64 decoding

### ISSUE THREAD

**Issue by garylfowler** [influxdata/flux#4646]
I have a customer that expressed interest in having a flux function to get data out of a field with Base64 encoded data and doing something with it in their flux script - so submitting this as a potential feature for consideration.

**Comment by nathanielc** [comment]
I thought about this for bit and while its easy to add the `encode`/`decode` functions to Flux there was an unexpected challenge. 
Currently the Flux engine doesn't let you store binary data in a table, only strings. This means that if you used `base64.decode` to produce some binary data you would discover that unless that data was a utf-8 encoded string you could not store it into a table and therefore do any processing on it. 

We should first make `bytes` be a valid column type before doing this work. See https://github.com/influxdata/flux/issues/1804
