### ISSUE TITLE
Implementation of the Ramer-Douglas-Peucker Algorithm for reducing data points without losing fidelity

### ISSUE THREAD

**Issue by gefaila** [influxdata/flux#4653]
**Proposal:**
Provide a function to implement the RDP algorithm found [here](https://rdp.readthedocs.io/en/latest/) or the advanced derivatives listed [here](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm)

**Current behavior:**
The only way to reduce data points are with the standard aggregate functions (min, max, mean, mode, first, last).  There are a number of significant problems for reducing timeseries data with these algorithms
- mean is destructive; i.e. it replaces existing data with averages that never actually occured
- They smooth out outliers, peaks, troughs and points of maximum acceleration that for troubleshooting are usually of most interest to us.
- It's not possible to reconstruct removed data points based on the reduced data set

**Desired behavior:**
- We have tested the RDP algorithm in python to show that we can easily get 10% compression ratios 
- The algorithm retains the spikes, peaks and troughs, accelerations and outliers of interest
- It is possible to guess where the removed points were by interpolating between the filtered data set
- The filtered points are unchanged (they don't have new values or timestamps) so they represent actual values that happened (unlike mean where new points are created that never actually happened).
- We need a simple compression parameter to either fix the number of points compressed to, or fix the error between the original and compressed data sets.  ie two versions of the algorithm
1.  Compress this data and give me X points that represent it most faithfully OR
2. Compress this data and give me the minimum points such that the maximum error to any original point is Y

**Alternatives considered:**
all existing aggregate functions in InfluxDB

**Use case:**
Any industrial IoT use case where data compression is as important as NOT losing key features of the data.

**Comment by nathanielc** [comment]
Most likely months. We plan to start on this in about a month and then I expect it will take a few weeks to actually build. Obviously this timeline is subject to change, but this is the current plan.

**Comment by nathanielc** [comment]
Another request for something similar using this algorithm has come in https://pkg.go.dev/github.com/dgryski/go-lttb. Maybe we can investigate both?

**Comment by gefaila** [comment]
> Another request for something similar using this algorithm has come in https://pkg.go.dev/github.com/dgryski/go-lttb. Maybe we can investigate both? See #4787

I think customers **would** need both because they excel in slightly different ways:
- RDP needs to be done on the completed data set.  The algorithm aims for a line that represents a complete data set to the tolerance that a user sets. RDP cannot be done "on the fly" as data points come in.  
- Swinging door is designed to work "live" or as points come in.  

Clearly, algorithms that can see all the data before compressing are going to have some advantages over algorithms that only know current and historical data.  Our choice was RDP.  Swinging door wouldn't do as good a job on retaining the actual features in the data we value.

**Comment by nathanielc** [comment]
The `RDP` algorithm has been implemented see https://github.com/influxdata/flux/pull/5078 Closing this issue, the `Largest Triangle Three Buckets` algo issue will remain open and we can add it alongside RDP once its done.

**Comment by nathanielc** [comment]
Link to RDP docs https://docs.influxdata.com/flux/v0.x/stdlib/experimental/polyline/rdp/

**Comment by gefaila** [comment]
This is great !  I have been looking forward to having this for a while!  Excellent.  Thanks for taking a look and implementing it!

**Comment by nathanielc** [comment]
@gefaila Glad to hear it, let us know how it works out for you. I have been using it personally to great success as well.
