### ISSUE TITLE
Add initialZero parameter to derivative function

### ISSUE THREAD

**Issue by shassan-el** [influxdata/flux#4661]
Please could I request to add `initialZero` parameter to `derivative` function? Currently, the `difference` function has this parameter, which is great, but when trying to calculate the derivative over time, it would be useful to have this parameter available too.

Use case where this would be useful: when using counter variables (interval data) that may be reset at some point, we wish to ignore non-negative differences and assume the first of subsequent values is 0.

Currently I have to calculate the `difference` using the necessary arguments, then work out `elapsed` time, join both tables and work out rate of change. It seems very long winded as it's something I would have expected `derivative` to handle in one line of code.

**Comment by wolffcm** [comment]
Hi @shassan-el, thanks for this submission. I think it makes sense to extend the `derivative` function this way since as you say `difference` provides this parameter already.

**Comment by shassan-el** [comment]
@wolffcm `initialZero` has already been added to `derivative`? I get error that initialZero is not a recognised parameter.

**Comment by wolffcm** [comment]
@shassan-el Sorry, not yet. That was a note for whoever picks up this issue to work on it.

**Comment by shassan-el** [comment]
@wolffcm If I use the derivative function (by setting nonNegative to true) then the fill function (setting value to 0), I think that would achieve what I am looking for?
By using the fill function to replace n/a values with 0, that would effectively replicate what initialZero would do once implemented, right?

**Comment by wolffcm** [comment]
@shassan-el Sorry for the delay in reply. Unfortunately I don't think that would quite do what you're looking for...

Consider this input 
```
Result: input
Table: keys: []
                    _time:time                  _value:int
------------------------------  --------------------------
2022-06-09T19:03:30.000000000Z                           7
2022-06-09T19:03:40.000000000Z                           8
2022-06-09T19:03:50.000000000Z                           9
2022-06-09T19:04:00.000000000Z                           3
2022-06-09T19:04:10.000000000Z                          11
2022-06-09T19:04:20.000000000Z                          12
2022-06-09T19:04:30.000000000Z                          13
```

This is the result that I get for `difference(nonNegative: true)`:
Output:
```
Result: _result
Table: keys: []
                    _time:time                  _value:int
------------------------------  --------------------------
2022-06-09T19:03:40.000000000Z                           1
2022-06-09T19:03:50.000000000Z                           1
2022-06-09T19:04:00.000000000Z                             
2022-06-09T19:04:10.000000000Z                           8
2022-06-09T19:04:20.000000000Z                           1
2022-06-09T19:04:30.000000000Z                           1
```
This is what I get for `difference(nonNegative: true, initialZero: true)` for the same input:
```
Result: _result
Table: keys: []
                    _time:time                  _value:int
------------------------------  --------------------------
2022-06-09T19:03:20.000000000Z                           1
2022-06-09T19:03:30.000000000Z                           1
2022-06-09T19:03:40.000000000Z                           3
2022-06-09T19:03:50.000000000Z                           8
2022-06-09T19:04:00.000000000Z                           1
2022-06-09T19:04:10.000000000Z                           1
```
In order for the `fill` method to work it would have to know what to replace the `null` with and I don't see how it would know that.

**Comment by wolffcm** [comment]
@shassan-el This issue is now scheduled for our next sprint which starts on Monday. Sprints are two weeks long so I would expect it to be fixed within this time frame. Thanks for your patience 🙏

**Comment by shassan-el** [comment]
> @shassan-el Sorry for the delay in reply. Unfortunately I don't think that would quite do what you're looking for...
> 
> Consider this input
> 
> ```
> Result: input
> Table: keys: []
>                     _time:time                  _value:int
> ------------------------------  --------------------------
> 2022-06-09T19:03:30.000000000Z                           7
> 2022-06-09T19:03:40.000000000Z                           8
> 2022-06-09T19:03:50.000000000Z                           9
> 2022-06-09T19:04:00.000000000Z                           3
> 2022-06-09T19:04:10.000000000Z                          11
> 2022-06-09T19:04:20.000000000Z                          12
> 2022-06-09T19:04:30.000000000Z                          13
> ```
> 
> This is the result that I get for `difference(nonNegative: true)`: Output:
> 
> ```
> Result: _result
> Table: keys: []
>                     _time:time                  _value:int
> ------------------------------  --------------------------
> 2022-06-09T19:03:40.000000000Z                           1
> 2022-06-09T19:03:50.000000000Z                           1
> 2022-06-09T19:04:00.000000000Z                             
> 2022-06-09T19:04:10.000000000Z                           8
> 2022-06-09T19:04:20.000000000Z                           1
> 2022-06-09T19:04:30.000000000Z                           1
> ```
> 
> This is what I get for `difference(nonNegative: true, initialZero: true)` for the same input:
> 
> ```
> Result: _result
> Table: keys: []
>                     _time:time                  _value:int
> ------------------------------  --------------------------
> 2022-06-09T19:03:20.000000000Z                           1
> 2022-06-09T19:03:30.000000000Z                           1
> 2022-06-09T19:03:40.000000000Z                           3
> 2022-06-09T19:03:50.000000000Z                           8
> 2022-06-09T19:04:00.000000000Z                           1
> 2022-06-09T19:04:10.000000000Z                           1
> ```
> 
> In order for the `fill` method to work it would have to know what to replace the `null` with and I don't see how it would know that.

I was referring to a workaround for the `derivative` function (not `difference`) since it currently lacks `initialZero` parameter, by doing the following:

|> derivative(nonNegative: true)
|> fill(column: "_value", value: 0)

the `derivative` function with `nonNegative` set to true would produce n/a values. Then the fill function would replace the n/a values for 0. Therefore, I believe this would produce the same result as when you implement the `initialZero` parameter in `derivative` as follows:

|> derivative(nonNegative: true, initialZero: true)

**Comment by shassan-el** [comment]
> @shassan-el This issue is now scheduled for our next sprint which starts on Monday. Sprints are two weeks long so I would expect it to be fixed within this time frame. Thanks for your patience 🙏

Great to hear. Thanks for actioning this promptly. Looks like I won't need to do a workaround as above (assuming my suggestion works above as I have not tested properly yet).
I look forward to testing `derivative` out with `intialZero` once implemented.
