### ISSUE TITLE
Pushdown ConditionalExpressions to storage

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#4672]
It is possible in special cases to convert a conditional expression into a logical expression and therefore push down the full filter expression to storage.

For example a user may construct a query like this:

```
from(bucket: "telegraf")
  |> range(start: -1h)
  |> filter(fn: (r) => if x == y then r["_measurement"] == "disk" else r["_measurement"] == "cpu") 
```

We could rewrite this query to be this instead:

```
from(bucket: "telegraf")
  |> range(start: -1h)
  |> filter(fn: (r) => ( x == y and r["_measurement"] == "disk") or r["_measurement"] == "cpu") 
```

Using logical expressions we can now safely push this entire predicate function to storage.

The requirement for this conversion is that the conditional expression must be a boolean type.

**Comment by OfTheDelmer** [comment]
I had this thought about the canonical `A and B or C` correspondence with a conditional not working when `B` and `C` are booleans 

| A | B | C | if A then B else C | A and B or C | (A and B ) or (!A and C) |
| :-- | :-- | :-- | :-- |  :-- | :-- |
| true | true | true | true | true ✅ | true  ✅  |
| true | true | false | true | true ✅  | true ✅  |
| true | false | true | false | true ❌ | false ✅  |
| true | false | false | false | false ✅ | false ✅  |
| false | true | true | true | true ✅  | true ✅  |
| false | true | false | false | false ✅  | false ✅ |
| false | false | true | true | true ✅  | true ✅ |
| false | false | false | false | false ✅  | false ✅  |
