### ISSUE TITLE
Daily aggregateWindow aggregates centered at unexpected time

### ISSUE THREAD

**Issue by shrx** [influxdata/flux#4718]
I'm using this query to calculate the duration of the spread of the desired parameters (temperature and humidity):

```
import "influxdata/influxdb/v1"

from(bucket: "home")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "zigbee" and r["device"] == "weather" and (r._field == "temperature" or r._field == "humidity" or r._field == "_time"))
  |> v1.fieldsAsCols() 
  |> filter(fn: (r) => (r.temperature > 26.99 and r.humidity > 39.99))
  |> duplicate(column: "_time", as: "time2")
  |> map(fn: (r) => ({ r with time2: float(v: int(v: r._time))/3600000000000. }))
  |> keep(columns: ["_time", "time2"])
  |> aggregateWindow(every: 1d, createEmpty: true, timeSrc: "_start", fn: (tables=<-, column) => tables |> spread(column: "time2"))
```
The data points are centered at an unexpected time. I would expect them to be centered at 0:00 or 12:00 but they are centered at 2:00 (possibly due to the server being in the CEST (+2) timezone):

![image](https://user-images.githubusercontent.com/810337/167315416-3ddd2170-2adb-4b32-933a-9636a52b1e31.png)

**Comment by sanderson** [comment]
@shrx Flux assumes all timestamps are UTC. Use [`timeShift()`](https://docs.influxdata.com/flux/v0.x/stdlib/universe/timeshift/) to apply an offset appropriate for your timezone.

**Comment by shrx** [comment]
@sanderson is this different from InfluxQL? I'm having no problems with time shifts there.
