### ISSUE TITLE
When writing Flux on Cloud 2.0, the new form of "Inject" for functions does not inject a working bit of code

### ISSUE THREAD

**Issue by gefaila** [influxdata/flux#4720]
I used to be able to code Flux very quickly.
I've been doing that for 2 years.
I would make heavy use of the "Inject" button.
"Injecting" a function would inject a working bit of code and I could immediately remember how to fill in the variables to make it work.
This worked for 99% of cases even for functions I rarely use and have forgotten what variables it needs.
In many cases the injected code worked "as is".

Injecting used to give 
`|> sort(columns: ["region", "host", "_value"])`

So I could tell instantly how the function works and edit it for my purpose

Now it injects
`|> universe.sort(   )`

Which leaves **EVERYONE** guessing what on earth variables I'm supposed to put in the brackets

So now I have to 
- open up the help page in a separate tab
- find the place where a working example is given
- copy the code
- flick back to my tab
- paste in the code
- edit as before

Why break such a useful feature?
I absolutely HATE the new way.
Please bring back the suggestion of a completed working example use because it contains everything that most people need to know to use it.

**Comment by devjolt** [comment]
I'm a relatively new user of Influx, and I have to second the above. I appreciate it's an established ecosystem with lots of resources, but being able to inject something which tells me what's going on really helps. Whilst Guido meant it differently, "Explicit is better than Implicit" ^_^

**Comment by barbaranelson** [comment]
@garylfowler or @wiedld Can you look at this user's feedback? Thanks.

**Comment by garylfowler** [comment]
@gefaila - Would you mind taking a look at this video and let me know what you think of this experience as an alternative?

https://user-images.githubusercontent.com/97983559/167994964-2027eea7-a343-4092-acc2-5880e0c111a5.mov

**Comment by gefaila** [comment]
No that's exactly the problem.

I get that you are coders so you look at that feature and think it does exactly what you'd need **as a coder**

But users like me are just wanting to visualise data.  Code is the thing that gets in the way.  :-)

So injecting a function and then helping the user to fill in the blanks, is, IMHO, not as good as injecting a full example which in 95% of circumstances will do what they want.

In fact ... exactly like it used to last month!

If you feel that injecting the stub *without* the variables filled in is, in some way, better for some people (coders?) then how about 2 or three options
- insert stub only ~ function()
- insert stub with the most commonly used values ~ function(variable1: "parameter1")
- insert stub with all possible values ~ function(variable1: "parameter1", variable2: "parameter2", variable3: "parameter3", variable4: "parameter5", variable6: "parameter6")

This would be then **better** than what it did last month.
As it is, IMHO, it's worse.

**Comment by gefaila** [comment]
> I'm a relatively new user of Influx, and I have to second the above. I appreciate it's an established ecosystem with lots of resources, but being able to inject something which tells me what's going on really helps. Whilst Guido meant it differently, "Explicit is better than Implicit" ^_^

devjolt is obviously a coder ! :-)

**Comment by garylfowler** [comment]
@gefaila - Thank you for taking a look at it and giving us your feedback; very much appreciated.  We are, coincidentally, making some changes to the script editor for suggestions while typing so we thought it *might* help in this situation (it wasn't specifically being worked on to address the issue you brought up in this ticket). 

The behavior change that you are describing was actually a side effect of a different change that was made to keep the flux function inject list more up to date (it is pulling the info from a different location now in a different format).  

I'll be meeting with the team that made this change and see what our options are for correcting this.

I'l also add to my backlog for consideration the 3 option inject idea you mentioned.  We'd need to give some thought to how we would visualize/present it to the user - but definitely open to the idea and appreciate you mentioning it.

**Comment by gefaila** [comment]
Great. I use flux on a daily basis so any efficiencies are greatly appreciated (and conversely ....)

**Comment by gefaila** [comment]
> @gefaila - Thank you for taking a look at it and giving us your feedback; very much appreciated. We are, coincidentally, making some changes to the script editor for suggestions while typing so we thought it _might_ help in this situation (it wasn't specifically being worked on to address the issue you brought up in this ticket).
> 
> The behavior change that you are describing was actually a side effect of a different change that was made to keep the flux function inject list more up to date (it is pulling the info from a different location now in a different format).
> 
> I'll be meeting with the team that made this change and see what our options are for correcting this.
> 
> I'l also add to my backlog for consideration the 3 option inject idea you mentioned. We'd need to give some thought to how we would visualize/present it to the user - but definitely open to the idea and appreciate you mentioning it.

Thinking about this.
Does it make more UX sense to have this as a setting for the user, rather than have three buttons?
Functionality is cool.  Clutter is not.

**Comment by garylfowler** [comment]
@gefaila - A change has been made to hopefully restore the functionality you were looking for with our top flux functions.  We will revisit a longer term approach moving forward - but hopefully, this will suffice, for now, in the short term.  Thanks.

**Comment by gefaila** [comment]
@garylfowler that's really great!
Glad to have them back.

When I tried a few functions, I did see that many that I use are still empty functions.

However, I get that this is temporary.

Thanks for pitching in.

` |> aggregate.window(columns: , every:   )`
`  |> window()  `
`  |> count()  `
`  |> bottom(n:   )`
`  |> drop()  `
`  |> duplicate(column: , as:  )  `
`  |> elapsed()  `
`  |> first()  `
`  |> integral()  `
`  |> mean()`
`  |> rename()  `
`  |> fill(column: "_value", usePrevious: true)  `
`  |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")`
`  |> keep(columns: ["col1", "col2"])  `
`  |> sort(columns: ["_value"], desc: false)  `
`  |> sum(column: "_value")  `

**Comment by gefaila** [comment]
I think the current innovations to the script editing are having a huge effect on the time taken to respond to a keypress.
I've just waited 5 minutes for a single line to appear

https://github.com/influxdata/flux/issues/4795
