### ISSUE TITLE
Specify: A syntax for declaring builtin values

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#473]
Currently builtin values are registered via the various register methods. We should require that built ins have some kind of corresponding syntax in pure Flux, this way every package will have to enumerate what values it exposes even if the implementation is in the host system (i.e. Go).

This is similar to C header files or Go's [FunctionType](https://golang.org/ref/spec#FunctionType).

Maybe something a simple as referencing an identifier as an expression statement that would otherwise do nothing.

```
package booleans

true
false
```

Or a less esoteric example, where both built-in and pure values are defined.

```
package math

// Cos computes the cosine of two numbers
cos

// Square computes the product of v with itself.
square = (v) => v * v
```

Or maybe we use a special keyword to make it look like an assignment.

```
package math

// Cos computes the cosine of two numbers
cos = builtin

// Square computes the product of v with itself.
square = (v) => v * v
```

```
package booleans

true = builtin
false = builtin
```

**Comment by wolffcm** [comment]
Will type inference need to know the types of the things defined in the host language?  This is the only case I can think of where on might need an actual type syntax in Flux.
