### ISSUE TITLE
filter field with . get error

### ISSUE THREAD

**Issue by ZQiannnn** [influxdata/flux#4748]
<img width="1838" alt="image" src="https://user-images.githubusercontent.com/19886406/168128118-e3e49dbe-23df-47d5-9d9d-9ba42599501a.png">

```
 runtime error @3:4-3:81: filter: failed to evaluate filter function: member "service" with type object is not in the record
```

**Comment by onelson** [comment]
I think this should work if you use the bracket notation, like `r["service.name"]`.

Here's an example using json data:

```
> import "experimental/json"
>
> x = json.parse(data: bytes(v: "{\"foo.bar\": 123}"))
> x["foo.bar"]
123
>
```

Let us know if that works for you!
