### ISSUE TITLE
Refactor `FindVarType` to lookup multiple names at the same time

### ISSUE THREAD

**Issue by onelson** [influxdata/flux#4751]
Today, the consumers of [`FindVarType`](https://github.com/influxdata/flux/blob/d0d82523879b39d773ec81cfe3d62aff916f9932/libflux/go/libflux/analyze.go#L150-L176
) need to use workarounds to be able to perform _multiple unknown type lookups_ at the same time.
Splitting the lookups across multiple calls seems to not be a viable option (either for perf or inference outcome reasons).

The _"here be dragons"_ text for the workaround follows:

```
	// FindVarType can only determine the type of a single unknown
	// type at a time. To work around this the query is parsed and
	// rewritten such that all of the unknown types are a records of
	// a single object that FindVarType can find the type for.
        // ... snip ...
```

This require the input flux to be rewritten, which sucks. All this could likely be avoided if we update our API perform multiple lookups together, returning the analysis results all at the same time.

Nb. since the func implementation is largely making FFI calls, we'll need to take special care with the memory handling for the new (assumed) array-based inputs and outputs.

DOD:
- pluralize the function name
- update the function such that multiple `varNames` can be received
- update the function such that an array of `MonoType`, or a mapping of names => `MonoType`s is produced

**Comment by jsternberg** [comment]
Reverted in https://github.com/influxdata/flux/pull/4980.

**Comment by onelson** [comment]
Seems like the original code path should have "just worked" based on my reading of the diff.

I guess I'll try and look at the idpe tests with go mod edit to see if I can reproduce whatever Jonathan bumped into during the release.

**Comment by onelson** [comment]
I only see one failure (which is nice).
```
--- FAIL: TestProcessParameters (0.01s)                                                                                                                                                                                                    
    --- FAIL: TestProcessParameters/using_options,_parameters_not_specified (0.00s)                                                                                                                                                        
        parameters_test.go:287:                                                                                                                                                                                                            
                Error Trace:    parameters_test.go:287                                                                                                                                                                                     
                Error:          An error is expected but got nil.                                                                                                                                                                          
                Test:           TestProcessParameters/using_options,_parameters_not_specified                                                                                                                                              
        parameters_test.go:294:                                                                                                                                                                                                            
                Error Trace:    parameters_test.go:294                                                                                                                                                                                     
                Error:          "{"type":"File","package":null,"imports":null,"body":[{"type":"OptionStatement","assignment":{"type":"VariableAssignment","id":{"type":"Identifier","name":"params"},"init":{"type":"ObjectExpression","pro
perties":[{"type":"Property","key":{"type":"Identifier","name":"min"},"value":{"type":"IntegerLiteral","value":"5"}}]}}},{"type":"OptionStatement","assignment":{"type":"VariableAssignment","id":{"type":"Identifier","name":"task"},"init
":{"type":"ObjectExpression","properties":[{"type":"Property","key":{"type":"Identifier","name":"max"},"value":{"type":"IntegerLiteral","value":"2"}},{"type":"Property","key":{"type":"Identifier","name":"min"},"value":{"type":"IntegerL
iteral","value":"1"}}]}}}]}" should have 0 item(s), but has 699                                                                                                                                                                            
                Test:           TestProcessParameters/using_options,_parameters_not_specified                                                                                                                                              
FAIL                                                                                                                                                                                                                                       
FAIL    github.com/influxdata/idpe/query        0.075s
```

Digging in now.

**Comment by onelson** [comment]
Okay. This is a good news/bad news situation. I suspect we can fix the 2 failing cases with a change like:

```
diff --git a/libflux/go/libflux/analyze.go b/libflux/go/libflux/analyze.go
index 841fe487..c08b80af 100644
--- a/libflux/go/libflux/analyze.go
+++ b/libflux/go/libflux/analyze.go
@@ -161,7 +161,9 @@ func AnalyzeString(script string) (*SemanticPkg, error) {
 
 func FindVarType(astPkg *ASTPkg, varName string) (semantic.MonoType, error) {
        pkg, err := Analyze(astPkg)
-       if pkg == nil {
+       // n.b Analyze can return _both_ a package and errors.
+       // For backwards compat, ensure we give priority to the errors.
+       if err != nil {
                return semantic.MonoType{}, err
        }
        return FindVarTypeSemantic(pkg, varName)

```

The code as written today only sends back errors in the case we don't get a package back from `Analyze`. Changing this to favor returning errors when present _should resolve these failures_, **however** this causes breakage in many many other tests.

I think at the bottom of this, the analysis we're doing _is different_ so naturally the results _are different_.

With the above change applied, the "rewrite hack" done in the downstream code (which expects to be able to use a faux identifier prefixed with `!!`) will result in an error, preventing us from giving the type information we previously returned.

I think we've got a couple options:

- completely split the old and new (ie, leave the original `FindVarType` as-is without re-implementing it in terms of the new).
- talk about updating the existing tests, re-evaluate the contract for the two failing cases.


For the former, it'll be slightly annoying to have two distinct versions of the same thing out there, but we can still aim to remove the original `FindVarType` once the downstream systems have migrated.

For the latter, I'd need @mhilton to weigh in. I'm not sure how disruptive the change in behavior would be for these cases.

I've still got some investigation to see what all is actually coming back in those cases that were originally errors. The size of the return value was quite large and I'd like to better understand why. Seemed as if the return should always be quite terse if we're talking about a single monotype. There could be a separate bug to fix.

**Comment by mhilton** [comment]
> With the above change applied, the "rewrite hack" done in the downstream code (which expects to be able to use a faux identifier prefixed with `!!`) will result in an error, preventing us from giving the type information we previously returned.
> 
> I think we've got a couple options:
> 
>     * completely split the old and new (ie, leave the original `FindVarType` as-is without re-implementing it in terms of the new).
> 
>     * talk about updating the existing tests, re-evaluate the contract for the two failing cases.
> 
> 
> For the former, it'll be slightly annoying to have two distinct versions of the same thing out there, but we can still aim to remove the original `FindVarType` once the downstream systems have migrated.
> 
> For the latter, I'd need @mhilton to weigh in. I'm not sure how disruptive the change in behavior would be for these cases.

From my point of view I'm certain we can be fairly sensible here. Preserving my hack is certainly not worth any effort. That can easily be changed in the interrim from an impossible identifier name to a vanishingly-unlikely-to-clash identifier name. Such a change would only be short-lived until we used the new API anyway.

For the most part I expect we should cope with new error cases, without much drama. Unless the library suddenly returns an error in cases where it would previosly have successfully executed the flux (which I am assuming is not the case as it wouldn't make sense). All that would be happening is a shift in where errors are detected.

Having said all that please can you keep us informed of what the changes we might see ahead of time so we can get any preparation done.

**Comment by onelson** [comment]
I spent some time today looking at how we might roll out the new code alongside the "legacy" version, verbatim. It's a bit complicated and I'm not certain I'll be able to do this cleanly.

The new code makes some refactors to how type substitution work and it seems difficult to do both old and new at the same time as a result.

The failing tests are both cases where they expect to get an error about an undefined identifier. With the new code, it looks like we're able to infer _something_ about the type of the variable without it being properly initialized.

For example
```
import "sampledata"
sampledata.int() |> filter(fn: (r) => r["_value"] > params.min and r["_value"] < v.max)
```
is expected to produce an error for `undefined identifier v`, but the changes we have today will instead give an `Object` monotype for `v` (I assume based on the member access).

The 2nd failed test is in the same boat. This query
```
import "sampledata"
sampledata.int() |> filter(fn: (r) => r["_value"] <  task.value)
```
is expected to error with `undefined identifier task`, but still returns an `Invalid` monotype for `v` (which is undefined and never referenced, so I guess that makes sense).

---

@mhilton what I'd like to do is maybe have you and yours try out the new `FindVarType` (singular), accounting for the 2 test cases mentioned above.

This should be possible using `go mod edit -replace`, targeting the `find_var_type` branch.

If you can adjust the functions where you use `FindVarType` and/or the test cases such that they pass with and without the new code, then we can look to roll this out as-is.

I can take a swing patching for those tests if that's something y'all want, though I think it'd be better for y'all to manage that side. You have more context.

Once those tests are passing then y'all can rework your end using the new plural `FindVarTypes` at your leisure.

I can rebase that branch closer to when y'all are ready to evaluate the new code to account for any drift -- hopefully the branch won't go stale too quickly.
