### ISSUE TITLE
Can we protect customer's data with MFA access

### ISSUE THREAD

**Issue by gefaila** [influxdata/flux#4770]
We are using InfluxDB cloud for warehousing IoT data for our industrial machines that go all over the world.

The more customers who want the solution, the more data we store.
Customers like it = More data = Bigger bills
Everyone is a winner.

The problem is that we are hitting a ceiling with selling this.
Industrial customers ask "What assurances can you offer us that our data is safe in your cloud DB?"

We can point them to the [influx security page](https://docs.influxdata.com/influxdb/cloud/reference/internals/security/) 
But actually their data on CLoud 2.0 is only protected with usernames and passwords.
Big manufacturers who buy our machines don't consider a password to actually offer much protection.

We'd like to say "The only people who have access to our database have passed MFA"

Please could you consider implementing MFA on Cloud 2.0 to net those paranoid industrial customers.  
This is a serious limitation with security implications.

Customers like it = More data = Bigger bills

**Comment by barbaranelson** [comment]
We support MFA in cloud 2 as an option for our larger customers, on annual deals.  We don't yet support it for the PAYG customers, but it is something that we might add in the future.
