### ISSUE TITLE
Feature Request: flux lttb (Largest Triangle Three Buckets) function

### ISSUE THREAD

**Issue by bcorbett6** [influxdata/flux#4787]
This purpose of this function will be to utilise the lttb algorithm to intelligently downsample data while retaining the key visual characteristics of the original line.

This is an important piece of functionality for use cases with irregular data intervals, and/or where using a simple aggregate function (simple downsampling) will not be sufficient as it removes key features of the data set. 

https://github.com/sveinn-steinarsson/flot-downsample

GO code translation available here: https://github.com/dgryski/go-lttb

**Comment by msamsonse** [comment]
Has there been any progress on this feature?  Has anyone written an lttb function?

**Comment by bcorbett6** [comment]
@msamsonse hi there, polyline.rdp() was developed (Ramer-Douglas-Peucker algorithm) was created as a preferable alternative. I hope this is acceptable for your use case?

https://docs.influxdata.com/flux/v0.x/stdlib/experimental/polyline/rdp/

**Comment by msamsonse** [comment]
@bcorbett6 The RDP algorithm didn't work for all of our use cases.  We ran into scenarios where RDP was way too aggressive and only 2 data points were returned.  LTTB works better for our use cases since we can select exactly how many data points are returned.
