### ISSUE TITLE
Flux Editor in InfluxDB Cloud has become extremely slow.  Long waits after every button press

### ISSUE THREAD

**Issue by gefaila** [influxdata/flux#4795]
I'm using the flux editor on a daily basis in Cloud 2.0.

It has almost become unusable recently for large queries (20 lines or so).

Every button press takes 3 -10 seconds to register.  
This is causing coding mistakes as I can't see what I'm typing.  
It takes absolutely ages to do a simple edit like reversing a comma and a quote

I have no idea what stuff is being done/checked every time a key is pressed.
But whatever it is seems to be hampering the main task of writing code and processing data.

The same happens when chart axes or even colours are changed.
Every key-stroke when typing a name in the Y-Axis seems to cause the chart to be redrawn.

I don't understand why someone thought this was a good idea when there is a "Submit" button waiting for me to press when I have finished my edits and wish to see the results of my code.

I'm guessing it is a recent improvement or feature that is supposed to make the charts responsive or dynamic?

**Comment by philjb** [comment]
Related to https://github.com/influxdata/ui/issues/2703
