### ISSUE TITLE
Type unification fails due to shadowed fields in the type

### ISSUE THREAD

**Issue by Marwes** [influxdata/flux#4807]
In the following example we call union with two streams of recordes with the types `{ A with _value: float, _value: float }` and `{ B with _value: float, _value: int }` which causes a type mismatch. However, I don't believe the second, shadowed set of fields are actually accessible in any way during the runtime so we may be able allow this case (essentially ignoring any shadowed fields during typechecking).

(The example is minimized from a breakage found in #4776 due to making the type signature of `count` more specific by adding `stream[{ A with _value: int }]` as the output.)

```rust
#[test]
fn reusing_same_field_in_record() {
    test_infer! {
        config: AnalyzerConfig{
            features: vec![Feature::LabelPolymorphism],
            ..AnalyzerConfig::default()
        },
        env: map![
            "from" => "() => stream[A] where A: Record",
            "map" => "(<-tables: stream[A], fn: (r: A) => B) => stream[B]",
            "union" => "(tables: [stream[A]]) => stream[A] where A: Record",
        ],
        src: r#"
            raw = from()

            stream_x =
                raw
                    |> map(fn: (r) => {
                        z = r._value + 0.0
                        return {r with _value: 0.0}
                    })

            stream_y =
                raw
                    |> map(fn: (r) => {
                        z = r._value + 0
                        return {r with _value: 0.0}
                    })

            union(
                tables: [
                    stream_x,
                    stream_y,
                ],
            )
        "#,
        exp: map![
            "x" => r#"stream[A] where A: Record"#,
        ],
    }
}
```

**Comment by nathanielc** [comment]
Seems related to this issue, https://github.com/influxdata/flux/issues/3426 The intent has been that the shadowed fields are dropped in the runtime since there is no way to access them and no real use case for them either. However they remain in the type system because we couldn't figure out a sound set of unification rules to collapse them.
