### ISSUE TITLE
MQTT publish error

### ISSUE THREAD

**Issue by otto-gebb** [influxdata/flux#4808]
When I call `mqtt.publish`, I get an error:

`error calling function "publish" @8:17-15:18: Dialer.Dial called on an error dependency`

The expected message is not published.

Steps to reproduce:

1. Set up an instance of influxdb running in docker, image: `influxdb:2.2.0-alpine`.
2. Set up an MQTT broker.
3. Run the Flux query in Data Explorer, substituting the correct broker address:

   ```
   import "array"
   import "experimental/mqtt"
   
   array.from(
       rows: [
           {
               ok:
                   mqtt.publish(
                       broker: "tcp://rabbitmq:1883",
                       topic: "test/topic",
                       message: "smoke test",
                       qos: 0,
                       retain: false,
                       clientid: "fluxtest",
                   ),
           },
       ],
   )
   ```

I checked that the broker can actually consume the message when it is published by an alternative client.

![image](https://user-images.githubusercontent.com/5798003/171044265-bbe7fabf-a048-49e0-9f11-ba7b74edf4f3.png)

**Comment by nathanielc** [comment]
@otto-gebb Which environment are you using? Is this a cloud account or an OSS instance?

**Comment by otto-gebb** [comment]
@nathanielc OSS, running in docker. I mentioned the image tag.

**Comment by bbezzi** [comment]
> @nathanielc OSS, running in docker. I mentioned the image tag.

I have the same error on docker (influxdb:latest and influxdb:alpine), but on windows the method works correctly! 
Do you have news? 
Thanks

**Comment by matthias-betz** [comment]
Same here, I run:

InfluxDB v2.2.0
Server: a2f8538
Frontend: cc65325

mqtt.publish() from package "experimental/mqtt" throws a "Dialer.Dial called on an error dependency"

I also tried the mqtt.to()
This function does not work as well but without any error message.

It is an absolutely valuable thing to have an mqtt client in flux and I would love to have it natively. Unfortunately, I am coming more from the application domain and I am not able to help with coding and bug fixing. But I volunteer for testing and giving feedback.

**Comment by kelseiv** [comment]
Hi Flux team, 
Looks like this may be related to this issue...the following docs feedback came via the **mqtt.to()** doc:
_The presented content does not function with InfluxDB v2.2.0 Server: a2f8538 Frontend: cc65325 Docker container on Debian_

**Comment by digitaldex** [comment]
i ran into the same problem in a docker environment. any update or workaround so far?

**Comment by martingruening** [comment]
I have the same issue. IP connectivity of the container is good (IPv6/IPv4, inbound and outbound). InfluxDB OSS 2.6.
