### ISSUE TITLE
flux 0.170.0 removed whitespace from types

### ISSUE THREAD

**Issue by rockstar** [influxdata/flux#4830]
In flux `v0.169.0`, `flux::semantic::nodes::Expression::typeof` would return information like `v: int`. As of flux `v0.170.0`, we now get `v:int`. That small whitespace added readability to type information that is exposed in the lsp as hover information. That whitespace should be added back in.

**Comment by onelson** [comment]
Something is weird about this. I just looked at the diff for #4809 and noticed the addition of whitespace (not the removal) though out the test cases.

This makes me think we might have read the LSP test that fails backwards and the fix here is to add the missing whitespace.

I also note that in https://github.com/influxdata/flux/pull/4809/commits/b86e9591b09cce85398732154b02fe59dacce0ea the commit message includes `BREAKING CHANGE` but the changlog didn't do anything to call this out. The PR was instead listed as a non-breaking feature-add.

**Comment by rockstar** [comment]
I went to find a link to show what the test was asserting, and looking closer, you're right. There were a couple of instances of `v: int` and the assertion one was incorrect. Thanks for the push.
