### ISSUE TITLE
Implement a high-performance standard CSV data source

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/flux#484]
* speed is a feature (leverage mmap, etc, where appropriate)
* reads standard CSV files, no annotations or other custom behavior
* handle multi-gigabyte files
* push down filters, such that we implement ideas from the [filter before you parse paper](https://dawn.cs.stanford.edu/2018/08/07/sparser/)
* time-range push down 
    * Many CSV files will be time-ordered, so leverage that fact
    * should be able to do a binary search to locate the start and end times when files are sufficiently large

It is expected that the `csv.from` source would have optional parameters to control behavior, such as whether there is a time-ordered column, etc

**Comment by russorat** [comment]
I'd like to add the ability to pull from remote csv files as well. something like:
```
import "csv"
  
  csv.from(file: "http://example.com/example.csv")
```
