### ISSUE TITLE
Specify evaluating packages consisting of multiple source files

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#486]
The evaluation of a Flux package consisting of multiple source files is currently not well defined. Given a package `foo` consisting of files `a.flux`, `b.flux`, and `c.flux`, in what order should the files be evaluated by the interpreter?

Currently all statements in a source file are executed by the interpreter sequentially. But what if `a.flux` has a variable `a` that depends on a variable `b` defined in `b.flux`? Variable initialization order needs to be well defined at the package level.

**Comment by jlapacik** [comment]
My thinking is that there should be a `Package` data structure defined in the flux `ast` package that would look something like this:

```go
type Package struct {
    name  string
    files map[string]Program
}
```

Each file belonging to a package would be parsed individually and added to the `files` map. The new signature of `semantic.New()` would look like this:

```go
// New creates a semantic graph from the provided AST
func New(pkg *ast.Package) (*Program, error)
```

That is, it would take an `ast.Package` and return a `semantic.Program` where the package level variable assignments have been re-ordered according to #533 . Note that location information of an ast/semantic node should be updated to included its associated filename. 

I think variables should remain mutable in the way it is currently defined in the SPEC. I think mutability is a useful feature especially once control flow is added to the language. In order to ensure that package level variables are initialized consistently, we should specify a consistent evaluation order (lexical) for the files of a package. And we should expect the user to follow certain best practices such as not re-declaring variables at the package level, while at the same time allowing them the capability.

Thoughts?

**Comment by nathanielc** [comment]
I like the general idea.

This API feels odd:

```go
// New creates a semantic graph from the provided AST
func New(pkg *ast.Package) (*Program, error)
```

Maybe it should be?

```go
// New creates a semantic graph from the provided AST
func New(pkg *ast.Package) (*Package, error)
```

Maybe we translate the concepts as such:

* An ast.Program becomes an ast.File
* An ast.Package is added that is a set of ast.Files
* A semantic.Program becomes a semantic.File
* a semantic.Package is added that  is a set of semantic.Files

With these changes the concept of a program is no more, rather everything is in a package. Then the interpreter can execute a single package which makes sense based on the spec.

I think mutability makes programing in Flux easier, but it opens lots of questions. Here are some of my questions concerns:

If we allow for mutability then Flux becomes a partially order execution model. Meaning the order of statements only matter sometimes but not always. 

How would you resolve conflicts, like a variable is defined separately in two different files? Maybe that should be an error?

What about a variable that is defined and then mutated in one file and another file references that variable. Which version of the variable does the second file use? 

What if the second file also mutates the variable?

Immutability avoids all of these issues, but requires that the Flux programmer give a new name to each assignment. I.e. we treat all variable assignments as let expressions for all following statements.

**Comment by jlapacik** [comment]
I like the translations you defined. To answer your questions:

> How would you resolve conflicts, like a variable is defined separately in two different files? Maybe that should be an error?

This only concerns package level variables but I think that should be an error. If we have two files `a.flux` and `b.flux` that both declare the variable `v`, and we allow package level redeclaration, then assuming we initialize variables in declaration order (after resolving dependencies), any variables that depend on `v` would use the value assigned by the last file passed to the interpreter.

To be explicit, if `a.flux` declares `v = 0` and `b.flux` declares `v = 1`. And if `b.flux` is passed to the interpreter after `a.flux` then any variable that depends on `v` will use `v = 1`. This isn't useful in the slightest so it should probably be a compile time error.

> What about a variable that is defined and then mutated in one file and another file references that variable. Which version of the variable does the second file use?

As long as files are passed to the interpreter in a consistent order and package level variables are initialized in declaration order, then the variable version is always well-defined. For example, if we have `a.flux`:

```
v = 0
w = v + 1
```

And `b.flux`:

```
x = v
```

Then if `a.flux` is passed to the interpreter before `b.flux`, we get `x = 1`. However if `b.flux` were passed to the interpreter first, declaration order would have `v` initialized before `x` and `x` initialized before `w`, which means `x = 0`. This is why we must define a consistent evaluation order for files in a package. Note the complexity of this example probably makes a strong case for variable immutability.

> What if the second file also mutates the variable?

Just as above, the final value of the variable is defined by declaration ordering and file evaluation order.

Cleary there's a lot of added complexity supporting the case of variable mutability. And I can't think of a Flux example where mutability makes solving a problem much easier than if variables were immutable. One thing that would change would be options. Currently options are just variable assignments and so they can be overridden and given new values. I'm not sure what effect making options immutable will have.

**Comment by jlapacik** [comment]
@nathanielc by defining variables to be immutable, we no longer have to specify the order in which package files are passed to the interpreter. We do however still need to perform dependency analysis because variables might not be initialized in the order they are defined in the source file. If a variable `v` defined in `a.flux` depends on a variable `w` defined in `b.flux`, then `v` must be initialized after `w` regardless of the order in which `a.flux` and `b.flux` are passed to the interpreter.

Having said that, I am in favor of requiring variables to be immutable because it still eliminates a lot of complexity and possible confusion regarding the global state of a Flux program.

**Comment by nathanielc** [comment]
> As long as files are passed to the interpreter in a consistent order

The only way I can see this working is if we sort the files by name. But then does your package break if you rename a file? Do we need to put syntax into Flux to determine the correct file order? Any solution that relies on a consistent order in which the files are processed is going to be fragile.

Immutable options might be an issue. I'll have to think on that one.

**Comment by jlapacik** [comment]
Making variables immutable in Flux will greatly simplify the evaluation of packages consisting of multiple source files. However options are currently mutable and must remain mutable. Below are two ways to implement Flux options in the presence of multi-file packages.

First let's assume that Flux has a pre-declared (universe) block such that the identifiers declared in this block are visible at all points in a Flux program.

**Case 1**
* Options can only be declared at the package level or the universe block
* Options cannot depend on other options
* Options are evaluated in declaration order after all imported packages are evaluated but before any other package level statements are evaluated. Note this implies that options cannot depend on any package level variables.
* The scope of an option is the universe block. This means once an option is declared it remains in context for the entirety of program execution.

Note in this case even if an option is declared at the package level, that option resides in the universe block. Hence if package `foo` declares option `task` and package `bar` imports package `foo`, referencing `task` in `bar` does not require the `foo` namespace qualifier.

**Case 2**
* Points 2 and 3 from **Case 1**
* Options can only be declared at the package level
* The scope of an option is the package block

Note in this case options are part of the identifiers that packages export. This complicates the implementation of Flux packages. Currently Flux packages are implemented as Flux objects. Flux objects are read-only collections of key-value pairs. If we were to implement options by way of **Case 2**, Flux objects would no longer be immutable and we would have to include compile-time checks to ensure that package level variables were not modified from another package. Because **Case 2** complicates the implementation of packages as well as the current definition of Flux objects, I prefer **Case 1**.
