### ISSUE TITLE
SPIKE: REPL LSP Integration

### ISSUE THREAD

**Issue by onelson** [influxdata/flux#4862]
We'd like to be able to use the LSP to give better suggestions in the Flux REPL.

This spike aims to reveal what it will take to effectively use the LSP from Go.

While _actually leveraging_ the LSP for the Flux REPL will involve a larger engineering investment to solve problems like how to deal with the state management/variable reassignment, this spike should focus on the basic communications aspect of sending and receiving messages.

Look for Go libraries to help model the LSP client API.

DOD:
Write a standalone Go program that can...
- spawn an instance of the LSP on the command line
- send messages to update document state
- send messages to request completions at a given cursor position
- consume responses, and write them out

**Comment by Marwes** [comment]
Embedding the full LSP (potentially) pulls in a lot more features than a REPL needs or can support. We could provide a subset of plain functions with just the features that a REPL needs (the LSP would call into, as needed, so we do not duplicate things).

(This how I have gluon's REPL + LSP setup https://github.com/gluon-lang/gluon/blob/master/completion/src/lib.rs)

These functions may live in this repo or the flux-lsp one, depending on what makes sense. I think we may want to move some of the analysis code of flux-lsp into this repo though if we start adding more warnings like https://github.com/influxdata/flux/pull/4745 ).
