### ISSUE TITLE
need functions for setting values to null

### ISSUE THREAD

**Issue by blueforesticarus** [influxdata/flux#4899]
Many functions such as `difference()` interpret null in a special way. Therefore, it is important to be able to set values to null. 
Currently there doesn't seem to be any way to do this. It cannot be done in map as there is no syntax for representing null.

In some cases, it is possible to use NaN instead. But flux lacks a `fill` type function for NaN.

**Comment by blueForestIcarus** [comment]
For some motivation. Say you have some data that logs -1 on reset (due to influx not supporting NaN or null)
Now you want to remove the "jumps" from the resets. 
As far as I can tell this is currently the simplest way. Requiring a map call *and* a filter call.

```
  |> map(fn: (r) => ({ r with _value: (if r._value == -1.0 then math.NaN() else r._value) }))
  |> difference()
  |> filter(fn: (r) => (not math.isNaN(f: r._value)))
  |> cumulativeSum()
```
