### ISSUE TITLE
Booleans are not comparable

### ISSUE THREAD

**Issue by Marwes** [influxdata/flux#4900]
Noticed that `max`,`min` etc do not work with `bool` and `bool` doesn't implement the `Comparable` kind. Comparing bools isn't that common but there isn't any practical reason to omit their inclusion either.

```flux
false < true // ERROR: bool is not comparable
```

**Comment by ypnos** [comment]
max/min aggregations would be really helpful, for example in case of windowing one can decide to let false or true prevail.
let's say the boolean expresses an error state, I woud like to aggregate in a way that any error (true) within the window is preserved.
not having this made the boolean type pretty useless for us so we convert to int and insert as int instead..
