### ISSUE TITLE
Can't compare duration values - error

### ISSUE THREAD

**Issue by ot3** [influxdata/flux#4906]
The following code results in an unexpected error:

```
WINDOW = 1d
START = if WINDOW == 1d then today() else 2022-01-01
```
Result:

```
unsupported binary expression duration == duration
```
__Environment info:__

`Linux 5.13.19-6-pve x86_64`
`InfluxDB v2.3.0+SNAPSHOT.090f681737 (git: 090f681737) build_date: 2022-06-16T19:33:50Z`

Submitted at the request of @Anaisdg

**Comment by ot3** [comment]
The error message also raises another question: why is the date '2022-01-01' interpreted as a duration? Is the date internally interpreted as 'seconds since epoch'?

**Comment by sanderson** [comment]
@ot3 It's not comparing `2022-01-01`. It's comparing `WINDOW` (which is `1d`) to `1d`:

```
WINDOW == 1d
```

**Comment by ot3** [comment]
You're right of course; my bad.
