### ISSUE TITLE
support for multi-line comments

### ISSUE THREAD

**Issue by jdstrand** [influxdata/flux#4911]
When editing flux within the InfluxDB UI, it would be convenient to support C-style multi-line comments (or similar) to make debugging easier (eg, comment out large parts of a broken script quickly to be able to focus on a particular section). I suppose adjusting the UI to support commenting via a highlight would also work, but C-style multi-line comments seem generally useful (and are somewhat expected).

I saw that https://github.com/influxdata/flux/issues/769 was filed for this and the decision was 'no' due to lack of requests, but that issue then had several people say they'd like to see them implemented without a response. Feel free to close this is a dupe.

**Comment by nathanielc** [comment]
>  I suppose adjusting the UI to support commenting via a highlight would also work

The UI already supports this, I believe the workflow is to highlight various lines and use `ctrl-/` to toggle comments on those lines.

Given the interest on that original issue I'll bring this up with the team and see what people think.

**Comment by nathanielc** [comment]
After further discussion we are not going to add multi-line comments to Flux.

**Comment by twosdai** [comment]
> After further discussion we are not going to add multi-line comments to Flux.

I'm not trying to overturn the decision, (The UI hotkey for `ctrl-/` is fine) but some reasoning why its not being added would be helpful for the community. 

My naive suspicion is that its not important enough or valuable enough for Influx to devote resources to add it, but if there is some technical difficulty with adding multi-line comments I (and I suspect others) would be curious to know more about it just for curiosity's sake. 
@nathanielc

**Comment by nathanielc** [comment]
Multi-line comments when nested create some complexity in the parser. If you don't support nested comments then you have weird behaviors in the code.

For example:

```
/*
 Outer comment
x = () => {
   /*
     Inner multie line comment
   */
   return 1
}
*/
```

If you don't properly handle nested comments then the above is seen like this when all comments are removed.

```
   return 1
}
```

Creating confusing parse errors for the user.

So not impossible to add but with how easy it is to do multiline editing in almost every editor the extra complexity wasn't worth it.Less is more when it comes to redundant syntax.
