### ISSUE TITLE
Add a syntax to describe label values

### ISSUE THREAD

**Issue by Marwes** [influxdata/flux#4927]
To allow label polymorphism to be used we need a way to define a label through the syntax. Originally we tried to re-use string literals for this, but during development we did not find a backwards compatible way that does not involve sub-typing.

Instead we add a new syntax `.mylabel` to define a label and users will need to update their query to use this new syntax. Additionally we need a syntax for labels with spaces or other non identifier characters. `."my label"`.

NOTE: We may find that `.` is ambiguous  with member expressions, if so we will need a new token, but it should be trivial to change the token used to delimit labels. We leave the actual token used up to the implementer.

For testing, there are ignored tests that live in `semantic::tests::labels` which should pass after updating them to use the new syntax.

DOD:
- A `.mylabel` syntax exists. Semantically it works the same as a string literal, it just has the label type instead of `string`
- The current way of enabling labels via string literals is removed
- The documentation is updated to explain this syntax
- Plumb labels from AST to Semantic nodes to semantic type
- Update applicable tests in `semantic::tests::labels`

**Comment by nathanielc** [comment]
Do we also want to mirror this syntax in the type expressions?

Something like 

```
builtin sum : (<-tables: stream[{ A with .C: B }], ?column: C = "_value") => stream[{ D with .C: B }]
    where A: Record, B: Numeric, C: Label
```

or alternatively

```
builtin sum : (<-tables: stream[{ A with .column: B }], ?column: C = "_value") => stream[{ D with .column: B }]
    where A: Record, B: Numeric, C: Label
```
so it reads more like the value of the `column` arg.

Additionally do we want to add a syntax for consuming labels in record labels.


```
a = {foo: "bar"}

set = (r, lbl=._value, value) => ({r with .lbl: value})
get = (r, lbl=._value,) => r[.lbl]
```

While we don't need to add all of this syntax to right now I would like to pick something that works for all these cases such that it remains cohesive across all its uses.
```

**Comment by Marwes** [comment]
> `{ A with .C: B }` or `{ A with .column: B }`

In expressions `.column` refers to the literal `column` label whereas here `.column` is a reference to some label type. That seems a confusing.

> so it reads more like the value of the column arg.

That may work, though it does create a difference between how the syntax is and how we represent the type internally as we still need to refer to the type variable directly during inference. Resolving `column` to the type variable is easy enough during the `convert` pass, however we likely also want to do the reverse when pretty printing a function type, otherwise this type won't match what the user may write in the source code.

```
builtin sum : (<-tables: stream[{ A with .column: B }], ?column: C = "_value") => stream[{ D with .column: B }]
    where A: Record, B: Numeric, C: Label

// Resolves to this internally
(<-tables: stream[{ A with C: B }], ?column: C = "_value") => stream[{ D with C: B }]

// But when we pretty print this we need to reverse this back to
(<-tables: stream[{ A with .column: B }], ?column: C = "_value") => stream[{ D with .column: B }]
```

> `r[.lbl]`

`.lbl` is already a label literal, so we can't use that syntax as a reference. Multi parameter type classes (multi parameter kinds) would let us use `r[x]` to index both arrays or records. Alternatively we could add a new syntax for indexing records (like `r.[x]` or something). cc https://github.com/influxdata/flux/pull/4716

> {r with .lbl: value})

I'd borrow from lua's syntax here `{ r with [lbl]: value }`
