### ISSUE TITLE
Add tests for the to function

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#4987]
The `to()` function has needed to be able to write unit tests. At the moment, the mechanism to use `to()` does not allow us to write unit tests because it requires testing a side effect that our test system can't do.

We need to find a way to allow us to test `to()`. There are a few options we might want to consider:

1. Mocking out the interface and just having it write to an equivalent of `/dev/null`.
2. Allowing the test system to mark what it should expect to be written and having the test dependency verify the written output.

**Comment by onelson** [comment]
I have been having similar thoughts about adding spies/mocks for any function with an external effect.

I wonder what would have been sufficient to catch the recent issue if we had to look as deep as the line protocol layer.
