### ISSUE TITLE
Why not import path date/boundaries

### ISSUE THREAD

**Issue by Marek-maxs** [influxdata/flux#4988]
error @2:1-2:25: invalid import path date/boundaries
My influxdb is 2.3 version.
why not import  date/boundaries. any body know why?

**Comment by sanderson** [comment]
@Marek-maxs, InfluxDB 2.3 shipped with Flux 0.171.0. The `date/boundaries` package was introduced in Flux 0.172.0.

**Comment by Marek-maxs** [comment]
Thank you for your  @sanderson 
Influxdb 2.3 is the latest version. Which version should I install to use this function. Or how can I install it to use this function.

**Comment by Marek-maxs** [comment]
> @Marek-maxs, you can either [download the nightly version of InfluxDB](https://portal.influxdata.com/downloads/) or you can [build InfluxDB from source](https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md#building-from-source).

Thank you so much
