### ISSUE TITLE
"join" package Import error

### ISSUE THREAD

**Issue by zz20200** [influxdata/flux#4994]
When I import join package `import "join"`  , error comes up  error @2:1-2:14: invalid import path join
But When I import "sampledata" or other package, there is no error.
I use the example from [Flux Documentation](https://docs.influxdata.com/flux/v0.x/stdlib/join/full/)

**Comment by zz20200** [comment]
> @zz20200 What version of InfluxDB are you using?

v2.2.0

**Comment by zz20200** [comment]
> @zz20200 What version of InfluxDB are you using?

v2.2.0

**Comment by sanderson** [comment]
@zz20200 The new join package is not available in InfluxDB 2.2. It was introduced in Flux 0.172.0. InfluxDB 2.2 ships with Flux 0.161.0.

**Comment by zz20200** [comment]
So, in my InfluxDB 2.2, I can't performs a full outer join on two table streams？
I found another join function, which is called "experimental.join", but it only supports inner join as well.

**Comment by sanderson** [comment]
@zz20200 Outer joins are only supported by the new `join` package. All previous implementations of join were inner joins only. Currently, only InfluxDB Cloud and the InfluxDB OSS nightly have a version of Flux that supports the new join package (as seen [here](https://docs.influxdata.com/flux/v0.x/stdlib/join/?view=influxdb-support)).
