### ISSUE TITLE
Support boolean literals for VectorRepeatValue

### ISSUE THREAD

**Issue by onelson** [influxdata/flux#4997]
The initial work towards wrapping constants/literals for vectorization only covered a subset of literals (int, float, string time). `boolean` was intended to be included but I (@onelson) was unable to figure out how to get them working on the rust side.

Rust complained about "undefined identifier" for `true` and `false` in tests and the bool literal match arm in `vectorize()` never seemed to match.

Possibly all that's missing is some configuration of the `Analyzer` but I wasn't sure how to make it work.

DOD:
- boolean literals can "vectorize" by being wrapped with `~~vecRepeat~~()` calls
- boolean literals produce `VectorRepeatValue` instances on the Go side
- tests for both Rust and Go areas of the code

**Comment by onelson** [comment]
For the "undefined identifier" problem, it seems like the fix is to define the builtin local to the test, as was done here for float:

https://github.com/influxdata/flux/pull/5048#discussion_r946017720

For booleans, this will mean adding the following to your test source:

```
builtin true : bool
builtin false : bool

// ... the function to vectorize follows
(r) => ({ r with ... })
```

**Comment by Marwes** [comment]
There is also `imp` https://github.com/influxdata/flux/blob/2be980478211aa6140833947fe9f7df5c941adfb/libflux/flux-core/src/semantic/tests.rs#L4205-L4208 and `env` https://github.com/influxdata/flux/blob/2be980478211aa6140833947fe9f7df5c941adfb/libflux/flux-core/src/semantic/tests.rs#L4257-L4260 to allow for things to be defind before the script.
