### ISSUE TITLE
Cannot join datasets unless they have matching group keys

### ISSUE THREAD

**Issue by sanderson** [influxdata/flux#5014]
In my testing of the `join` package and specifically `join.inner`, I found that I can only join two streams together if their group keys match. For example:

```js
import "csv"
import "join"
import "http/requests"
import "influxdata/influxdb/sample"

timeSeries =
    sample.data(set: "airSensor")
        |> range(start: -30m)

assetData =
    csv.from(
        csv: string(v: requests.get(url: "https://docs.influxdata.com/downloads/sample-sensor-info.csv").body),
        mode: "raw",
    )

join.inner(
    left: timeSeries,
    right: assetData,
    on: (l, r) => l.sensor_id == r.sensor_id,
    as: (l, r) => ({l with location: r.location}),
)
```

Returns: 

```
 table is missing label _start
```

However, if I ungroup `timeSeries` to match the grouping of `assetData`, the query runs successfully.

```js
import "csv"
import "join"
import "http/requests"
import "influxdata/influxdb/sample"

timeSeries =
    sample.data(set: "airSensor")
        |> range(start: -30m)

assetData =
    csv.from(
        csv: string(v: requests.get(url: "https://docs.influxdata.com/downloads/sample-sensor-info.csv").body),
        mode: "raw",
    )

join.inner(
    left: timeSeries |> group(),
    right: assetData,
    on: (l, r) => l.sensor_id == r.sensor_id,
    as: (l, r) => ({l with location: r.location}),
)
```

I found that the group keys of each input stream need to be the same in order to complete successfully. So the following works as well:

```js
import "csv"
import "join"
import "http/requests"
import "influxdata/influxdb/sample"

timeSeries =
    sample.data(set: "airSensor")
        |> range(start: -30m)

assetData =
    csv.from(
        csv: string(v: requests.get(url: "https://docs.influxdata.com/downloads/sample-sensor-info.csv").body),
        mode: "raw",
    )

join.inner(
    left: timeSeries |> group(columns: "sensor_id"),
    right: assetData |> group(columns: "sensor_id"),
    on: (l, r) => l.sensor_id == r.sensor_id,
    as: (l, r) => ({l with location: r.location}),
)
```

I don't know if this is the intended functionality of the package/functions, but this isn't the behavior I expected. With this limitation, to join two streams, users will almost always have to regroup them first, then regroup them after.

**Comment by wolffcm** [comment]
It is an intended limitation to require the group key to be the same on both sides, but it does indeed usually require regrouping on both sides to get the join to work. (Though not necessarily after, curious if you have an example of why this might be) Without this limitation the `join` implement tends to be very bug prone and also not very performant.

The error you're seeing `table is missing label _start` does not make sense to me though and so I believe this behavior is a bug.

**Comment by scbrickley** [comment]
I ran into the same issue, and I believe this was resolved in https://github.com/influxdata/flux/commit/2a3c55635fdaecafd0f3b9e1daa45f2b2d46b9cd

Make sure you're using the latest version of join. If the problem persists, then I will look into it again.

**Comment by wolffcm** [comment]
The error message has been fixed in the issue that Sean linked, and as described above, tables must have matching group keys to be joined, which is part of the design.
