### ISSUE TITLE
New join package error: panic: join - joinProduct already has left value for ke

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#5016]
@sanderson Reports seeing an error when using the new `join` package in the Flux REPL:
```
import "sampledata"
import "join"

ints = sampledata.int()
strings = sampledata.string()

join.inner(left: ints, right: strings, on: (l, r) => l._time == r._time, as: (l, r) => ({l with label: r._value}))
```
Returns the following error:
```
Result: _result
Error: panic: join - joinProduct already has left value for key [ _time:time=2021-01-01T00:00:00.000000000Z ]
```
This seems to be an error, since the code should never panic. This happened after #4999 was merged so maybe that patch contained a regression? It does not reproduce in Cloud, which does not have that patch.

May or may not be related to https://github.com/influxdata/flux/issues/5014

**Comment by scbrickley** [comment]
I can't reproduce this using the latest version of Flux.

**Comment by scbrickley** [comment]
Nevermind, I can reproduce this in the REPL, but not in the cli (i.e., by running `flux foo.flux`). Looking into this now.

**Comment by scbrickley** [comment]
The only cause I can think of for this is that the REPL is not properly sorting the inputs to join, which is done by the planner. Does the REPL run the planner at all when it executes queries?
