### ISSUE TITLE
Flux formatter removes the end of file newline

### ISSUE THREAD

**Issue by Boudewijn26** [influxdata/flux#5038]
I use vsflux to edit my flux files and the included formatter automatically removes the trailing newline. According to The Open Group Technical Standard Base Specifications [a (unix) text file is a series of lines](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_403) and [a line must contain a new line character](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206).

Other than a definition matter, the missing newline results in warnings in diffs provided by git 
![image](https://user-images.githubusercontent.com/2896917/182343789-81346d14-e233-4904-a338-7e6885780def.png)
 and github 
![image](https://user-images.githubusercontent.com/2896917/182343640-238c0e9a-1e86-4d7c-8626-93b55e8d050c.png).

I could image this being a very minor performance optimization: sending one less byte to the server. IMO that one byte shouldn't matter as much and if it did, the client libraries should strip all whitespace likely saving more than one byte

**Comment by onelson** [comment]
I have a vague memory of a patch going through on the LSP (which performs the formatting in vscode) to make sure it included the trailing newline matching the behavior of the CLI formatter we have in this repo.

Sounds like this could be a regression. /cc @influxdata/qx-team in case this is on the LSP side.

**Comment by Boudewijn26** [comment]
Upon further searching, it's a variation of the second: [the release of vsflux 1.0.5 failed](https://app.circleci.com/pipelines/github/influxdata/vsflux/628/workflows/c57baabb-6890-4bbb-a33c-23ebceba5499/jobs/949), [which makes the latest release 1.0.4](https://marketplace.visualstudio.com/items?itemName=influxdata.flux), [which depends on flux-lsp 0.8.11](https://github.com/influxdata/vsflux/blob/v1.0.4/package.json#L413), [which depends on flux 0.164.1](https://github.com/influxdata/flux-lsp/blob/0.8.11/Cargo.toml#L43), [whilst the fix landed in 0.173.0](https://github.com/influxdata/flux/commit/ce14bedf9e06b691b3cd45d1a88aa77d226a3b64).

I'll report the failed release in vsflux, thanks for pointing me the right way!
