### ISSUE TITLE
Support HTTP mocking in tests

### ISSUE THREAD

**Issue by onelson** [influxdata/flux#5059]
When writing code that depends on a HTTP service, it is beneficial to be able to mock the external service so that you can:

- have fewer runtime dependencies for the test
- simulate outage/failure of external service
- simulate specific payloads/responses from the service

### Prior Art
- https://wiremock.org/ (or the rust namesake https://github.com/LukeMathWalker/wiremock-rs)
- https://github.com/nock/nock

**Comment by nathanielc** [comment]
Go also has a package for this https://pkg.go.dev/net/http/httptest
