### ISSUE TITLE
Add a fluxfmt command

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#51]
By introducing a fluxfmt command we can format Flux into a string given its AST. This will greatly improve readability of source across projects as there will be a standard.

Fluxfmt should preserve comments and newlines within reason. Within reason is left up to the implementation ;)

**Comment by chnn** [comment]
I starting hacking on this a little while ago on the [`fluxfmt` branch](https://github.com/influxdata/flux/tree/fluxfmt).

**Comment by russorat** [comment]
connect https://github.com/influxdata/flux/issues/958

**Comment by russorat** [comment]
should this move to the influxdata/flux-lsp repo?

**Comment by adriandt** [comment]
There is a formatter available now and it lives in the flux repository. It is entirely rust based. I don't think it is exposed as a command though. Should it be?

**Comment by adriandt** [comment]
> should this move to the https://github.com/influxdata/flux-lsp repo?

I think it belongs in the flux repo. It depends on understanding the AST. The flux-lsp package is currently importing flux to access the formatter and that is probably ok.

**Comment by jademcgough** [comment]
@adriandt I'd like to see it exposed as a command - It's a very common pattern, e.g. `gofmt` or `cargo fmt`.

**Comment by jademcgough** [comment]
@russorat I think this is two different issues; exposing a `fluxfmt` command (as part of the flux library), and enabling formatting in the language server.

**Comment by russorat** [comment]
thanks! makes sense. connecting to https://github.com/influxdata/flux-lsp/issues/35

**Comment by onelson** [comment]
I think this one has been satisfied for some time now.

There's a `fmt` sub-command available in the flux CLI.

```
$ go run ./cmd/flux fmt --help
Format a Flux script (flux fmt [-w] <directory | file>)

Usage:
  flux fmt [flags]

Flags:
  -c, --analyze-current-directory   analyze the current <directory | file> and report if file(s) are not formatted
  -h, --help                        help for fmt
  -w, --write-result-to-source      write result to (source) file instead of stdout
```

This functionality is additionally exposed through flux-lsp.
