### ISSUE TITLE
Vectorized functions in stdlib problems

### ISSUE THREAD

**Issue by onelson** [influxdata/flux#5102]
This issue needs a better title.

The gist is, in https://github.com/influxdata/flux/pull/5048 we allowed calls to `float()` to be vectorized, but `toFloat` in the stdlib was not vectorizing as expected as a result.

Reimplementing `toFloat` verbatim in your own program showed that it would vectorize happily based on the expressions used, so it might be there's some interference with how we load stdlib code.

`toFloat` was an obvious "this should just work" case, but there could be other functions in the stdlib which should be vectorized, but aren't.

DOD:
- while requisite feature flags are enabled, functions like `toFloat()` should use the vectorized code path

**Comment by Marwes** [comment]
The problem is that the standard library is pre-compiled without feature flags, which causes any vectorization to be omitted. This branch fixes the issue https://github.com/influxdata/flux/tree/vectorize_stdlib , but it unconditionally enables the feature(s) which isn't ideal.

```
goos: linux
goarch: amd64
pkg: github.com/influxdata/flux/cmd/flux
cpu: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
BenchmarkVectorizeToFloat
BenchmarkVectorizeToFloat/Stdlib
BenchmarkVectorizeToFloat/Stdlib-8              1000000000               0.02755 ns/op
BenchmarkVectorizeToFloat/Manual
BenchmarkVectorizeToFloat/Manual-8              1000000000               0.02590 ns/op
PASS
ok      github.com/influxdata/flux/cmd/flux     0.440s
```

**Comment by Marwes** [comment]
Three ways of fixing this

* If we remove the pre-compilation and instead embed the `.flux` files instead we could then compile the standard library on demand instead with the feature flags set at runtime (caching as necessary).
* We could embed multiple versions of the standard library for whatever sets of feature flags we want.
* We forcefully enable vectorization in the standard library (like my branch) and just rely on everything in the standard library being sound to vectorize effectively.

**Comment by onelson** [comment]
There was discussion related to this when we were talking about polymorphic labels iirc. Something about "if we feature flag labels we'd need to be able to ship multiple versions of stdlib, or add a way to branch the signatures of things based on flags."

I think we punted on all that by saying "editions" might be the way to handle it, but perhaps vectorization puts us back to square one for this matter.

I wonder if we could defer this until we're happy to remove the feature flags in front of vectorization generally, as a last step. At that point we can just pre-compile everything as vectorized.
