### ISSUE TITLE
v 0.181.0  compound logical expressions in map failing 

### ISSUE THREAD

**Issue by anthony-roy-wesdigital** [influxdata/flux#5155]
**Steps to reproduce:**  
since v 0.1.8.1  rolled out to influxDBcloud ,  queries like the below are failing. 
with error :
*runtime error: cannot use operand of type vector with logical and; expected boolean

```
import "array"

rows = [
{Brake_Code_3: 1, Brake_Code_2: 0, Brake_Code_1: 1 ,BrakeEmergency:0},
{Brake_Code_3: 1, Brake_Code_2: 0, Brake_Code_1: 1 ,BrakeEmergency:0},
{Brake_Code_3: 1, Brake_Code_2: 0, Brake_Code_1: 1 ,BrakeEmergency:0},
{Brake_Code_3: 1, Brake_Code_2: 0, Brake_Code_1: 1 ,BrakeEmergency:0},
{Brake_Code_3: 1, Brake_Code_2: 0, Brake_Code_1: 1 ,BrakeEmergency:0},
]

data =  array.from(rows: rows)
data  |> map (fn: (r) => ( { r  with  
    brakeStep: 
      if  r.BrakeEmergency == 1 then 4.0 
      else if r.Brake_Code_3 ==1  and  r.Brake_Code_2 == 1  and r.Brake_Code_1 == 1 then 0.0 
      else if r.Brake_Code_3 == 1 and  r.Brake_Code_2 == 1 and r.Brake_Code_1 == 0 then 1.0
      else if r.Brake_Code_3 == 1 and  r.Brake_Code_2 == 0 and r.Brake_Code_1 == 1 then 2.0
      else if r.Brake_Code_3 == 0 and  r.Brake_Code_2 == 0 and r.Brake_Code_1 == 0 then 3.0
      else  0.0
   }) ) 
  
```

**Expected behavior:** Query should run 

**Actual behavior:**    
runtime error: cannot use operand of type vector with logical and; expected boolean

**Environment info:**

**Config:** eu-central-1-1.aws.cloud2.influxdata.com
Flux Version : v0.181.0

**Comment by onelson** [comment]
@anthony-roy-wesdigital thanks for the detailed bug report. I included a similar program as was posted here in the test suite along with the fix in #5160.

For the time being, vectorization of `map()` with conditional expressions will not be attempted in cloud, but the expectation is once this fix is rolled out we should be able to re-enable the optimization.
