### ISSUE TITLE
buckets() command not returning all buckets with R/W Token

### ISSUE THREAD

**Issue by rschre** [influxdata/flux#5182]
InfluxDB-Version: v.2.3.0
Server: [090f681](https://github.com/influxdata/influxdb/tree/090f681737)
Frontend: [a2bd1f3](https://github.com/influxdata/ui/tree/a2bd1f3)

Summary:
When I run the buckets() command either through the FluxQL-addon for VS Code, through the python library "influxdb_client" or from Grafana I get different results based on what kind of a API token I use. When i use token with read or R/W access on all buckets I only receive 18 buckets (probably 20 - _monitoring and _tasks). When I use a full access token I receive all buckets (27 in my case).

Steps to reproduce:
- Have more than 20 buckets
- Create a R/W API token with access to "All Buckets"
- run buckets() through either VS Code-Addon or python query_api()

Expected Behaviour:
I receive all buckets when I run the buckets() command I have access to independent on what type of API token I use.

**Comment by SimonRichardson** [comment]
I'm unable to replicate this locally in remocal. I'll see if a production cluster is exhibiting this issue.

I made 20 buckets (`bucketN`) then made three types of tokens:

 1. All access token.
 2. Selecting each bucket read/write manually. 
 3. Selecting all buckets for read and write.

I then used the following curl script to ensure that all three tokens returned the same result.

```sh
curl -s '${API_ADDR}/api/v2/buckets?orgID=${ORG}&limit=-1' \
  -H "Authorization: Token ${TOKEN_1}" \
  -H "Accept: application/json" \
  -: \
  '${API_ADDR}/api/v2/buckets?orgID=${ORG}&limit=-1' \
  -H "Authorization: Token ${TOKEN_2}" \
  -H "Accept: application/json" \
  -: \
  '${API_ADDR}/api/v2/buckets?orgID=${ORG}&limit=-1' \
  -H "Authorization: Token ${TOKEN_3}" \
  -H "Accept: application/json"  | jq '.[] | select(type=="array") | map(.name)'
```

Additionally, I used the VSCode plugin to return all the buckets:

![Screenshot from 2022-10-17 14-58-16](https://user-images.githubusercontent.com/2562584/196196773-d38cad45-521d-44fa-bb83-c324b9d9035c.png)

---

Can we be sure that all buckets were created with the appropriate permissions?

**Comment by SimonRichardson** [comment]
Additionally, if you assign a label to a bucket but do not have RW access to labels, then it will still output the bucket correctly.

**Comment by bednar** [comment]
I am able to simulate this error by:

1. Generate `READ` scoped token for all buckets
2. Create 50 buckets by `ALL` access token
3. List buckets by `READ` scoped token

Here is a code for reproduce by `python` client:

```python
import datetime

from influxdb_client import InfluxDBClient, PermissionResource, Permission, Authorization

url = "http://localhost:8086"
token = "my-token"
org = "my-org"
bucket = "my-bucket"
debug = False


def generate_token():
    with InfluxDBClient(url=url, token=token, org=org, debug=debug) as client:
        organization = client.organizations_api().find_organizations(org=org)[0]

        bucket_resource = PermissionResource(org_id=organization.id, type="buckets")
        read_buckets = Permission(action="read", resource=bucket_resource)

        authorization = client.authorizations_api().create_authorization(
            authorization=Authorization(org_id=organization.id, permissions=[read_buckets]))

        return authorization.token


def create_buckets():
    with InfluxDBClient(url=url, token=token, org=org, debug=debug) as client:
        buckets_api = client.buckets_api()
        for i in range(50):
            buckets_api.create_bucket(bucket_name=f"generated_bucket_{i}_{str(datetime.datetime.now().timestamp())}")


def find_buckets():
    # if you change the "generated_token" to "token" everything will work correctly
    with InfluxDBClient(url=url, token=generated_token, org=org, debug=debug) as client:
        tables = client.query_api().query("buckets()")
        flat_list = [record['name'] for table in tables for record in table.records]
        print(f"Buckets count: {len(flat_list)}")
        print(f"Buckets: {','.join(flat_list)}")


if __name__ == "__main__":
    print("Generating read token...")
    generated_token = generate_token()
    print("done")
    print()

    print("Creating 50 buckets by all scoped token...")
    create_buckets()
    print("done")
    print()

    print("Try to find all buckets by read token...")
    print()
    find_buckets()

```

```console
Generating read token...
done

Creating 50 buckets by all scoped token...
done

Try to find all buckets by read token...

Buckets count: 18
Buckets: generated_bucket_0_1666076801.828047,generated_bucket_0_1666076990.325349,generated_bucket_0_1666076998.197203,generated_bucket_0_1666077022.166311,generated_bucket_0_1666077081.274777,generated_bucket_0_1666077108.78116,generated_bucket_0_1666077126.470643,generated_bucket_0_1666077144.428998,generated_bucket_0_1666077159.759786,generated_bucket_0_1666077408.577308,generated_bucket_10_1666076802.007322,generated_bucket_10_1666076990.510476,generated_bucket_10_1666076998.386884,generated_bucket_10_1666077022.289,generated_bucket_10_1666077081.415907,generated_bucket_10_1666077108.921161,generated_bucket_10_1666077126.680003,generated_bucket_10_1666077144.577036

```

**Comment by SimonRichardson** [comment]
So this is by design (although naive), if no limit is passed, then the default is 20 (there is a maximum limit of 100). You're probably wondering why you ended up with 18. Removing the system buckets would account for this `_monitoring` and `_tasks`. Depending on the order of the returned buckets, you might actually end up with 20 as the system buckets weren't in the original response, so the system buckets weren't filtered out.

**Comment by karel-rehor** [comment]
I tried this using the Grace testing framework and javascript.  The results were similar to Simon's.  Regardless of the token type all buckets were returned.  The difference is that I generated 50 buckets.   I also suspect that the default `limit` value could be the cause.  Here I've specified the `limit` query param as `limit=-1` in a first run.  In a second run the `limit` query param is removed.  Still the results against Cloud (K8SIDPE) are the same as Simon's.  I see Jakub used an OSS endpoint.  Is there a difference between OSS GET and Cloud GET?  Bucket names beginning with upper or lower case can also influence the sort order when system buckets get filtered into the result. 

The code
```javascript
  it.only('troubleshoot bucket reads', async () => {
    // gToken is default system token

    const readBucketsAuth = await helpers.createAuthorization(url, gToken, {
      orgID: gOrgID,
      description: 'buckets read only',
      permissions: helpers.genResourcesPermissions(gOrgID, ['buckets'], ['read'])
    })

    const buckets = []

    await log.cout(log.level.debug, `creating buckets`)
    for(let i = 0; i < 50; i++){
      await supertest(url)
        .post('/buckets')
        .set('Authorization', `Token ${gToken}`)
        .set('Content-Type', 'application/json')
        .send(JSON.stringify({
          orgID: gOrgID,
          name: `${String.fromCharCode(65+(Math.floor(Math.random() * 26)))}${helpers.genHexString(7)}`,
          description: helpers.getRandomString(32),
          retentionRules: []
        }))
        .expect(201)
        .then(async ({body: bucket}) => {
          await log.cout(log.level.debug, `adding bucket ${bucket.name}`)
          buckets.push(bucket)
        })

    }

    await log.cout(log.level.debug, `reading buckets with system tokem`)
    const resp1 = await supertest(url)
      .get('/buckets')
      .set('Authorization', `Token ${gToken}`)
      .set('Content-Type', 'application/json')
      .query("limit=-1")

    const {body: {buckets: b1s}} = resp1
    await log.cout(log.level.debug, `buckets with Grace Token ${log.objFmt(b1s.map(b => ({name: b.name, id: b.id})))}`)

    await log.cout(log.level.debug, `reading buckets with readOnly tokem`)
    const resp2 = await supertest(url)
      .get('/buckets')
      .set('Authorization', `Token ${readBucketsAuth.token}`)
      .set('Content-Type', 'application/json')
      .query("limit=-1")

    const {body: {buckets: b2s}} = resp2
    await log.cout(log.level.debug, `buckets with ReadAllToken ${log.objFmt(b2s.map(b => ({name: b.name, id: b.id})))}`)

    await log.cout(log.level.debug, `count b1s ${b1s.length} count b2s ${b2s.length}`)

  })

```

The results:
```
 troubleshoot
 INFO: Initializing for Cloud
(node:41076) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
 DEBUG: creating buckets
 DEBUG: adding bucket Yeba0e09
 DEBUG: adding bucket Y3cd7833
...
 DEBUG: adding bucket Vbbee756

 DEBUG: reading buckets with system tokem
 DEBUG: buckets with Grace Token [
   {
      "name": "A38240bb",
      "id": "dca4c77b25cf6ef9"
   },
   {
      "name": "B3978281",
      "id": "3fa7eb2664525b01"
   },
...
   {
      "name": "_monitoring",
      "id": "6857ce49f73dd6a4"
   },
   {
      "name": "_tasks",
      "id": "be3d3a8f5a5f7d09"
   },
   {
      "name": "devbucket",
      "id": "0640faf786cdf374"
   },
   {
      "name": "frontendservices",
      "id": "3118632a111a2bab"
   }
]
 DEBUG: reading buckets with readOnly tokem
 DEBUG: buckets with ReadAllToken [
   {
      "name": "A38240bb",
      "id": "dca4c77b25cf6ef9"
   },
   {
      "name": "B3978281",
      "id": "3fa7eb2664525b01"
   },
...
   {
      "name": "_monitoring",
      "id": "6857ce49f73dd6a4"
   },
   {
      "name": "_tasks",
      "id": "be3d3a8f5a5f7d09"
   },
   {
      "name": "devbucket",
      "id": "0640faf786cdf374"
   },
   {
      "name": "frontendservices",
      "id": "3118632a111a2bab"
   }
]
 DEBUG: count b1s 54 count b2s 54
    ✔ troubleshoot bucket reads (18757ms)

```

Results when omitting the `limit` param.

```
  troubleshoot
 INFO: Initializing for Cloud
(node:46698) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
 DEBUG: creating buckets
 DEBUG: adding bucket K743f1c5
 DEBUG: adding bucket Qb356c63
...
 DEBUG: adding bucket Q9ce3ace
 DEBUG: reading buckets with system tokem
 DEBUG: buckets with Grace Token [
   {
      "name": "A0152ffa",
      "id": "bac84bbc4ce4e185"
   },
   {
      "name": "A13c45c9",
      "id": "9517b1d85605de87"
   },
...
   {
      "name": "K743f1c5",
      "id": "91553e10d2c6be0e"
   }
]
 DEBUG: reading buckets with readOnly tokem
 DEBUG: buckets with ReadAllToken [
   {
      "name": "A0152ffa",
      "id": "bac84bbc4ce4e185"
   },
   {
      "name": "A13c45c9",
      "id": "9517b1d85605de87"
   },
...
   {
      "name": "K743f1c5",
      "id": "91553e10d2c6be0e"
   }
]
 DEBUG: count b1s 20 count b2s 20
    ✔ troubleshoot bucket reads (18787ms)

```

**Comment by bednar** [comment]
@rschre @karel-rehor user doesn't use `/buckets` endpoint but uses `/query` endpoint with `buckets()` function - https://docs.influxdata.com/flux/v0.x/stdlib/influxdata/influxdb/buckets/

**Comment by SimonRichardson** [comment]
I suspect we're using [the following limit](https://github.com/influxdata/influxdb/blob/master/query/dependency.go#L56), unfortunately, we can't override it. @nathanielc how do we feel about upping the limit to 100 or alternatively allowing `buckets(limit:100)`?

**Comment by nathanielc** [comment]
The buckets functions should do the pagination logic and get all buckets. I can get them in batches of 20 or whatever the internal limit is but the user should not have to know or care about the limit.

**Comment by davidby-influx** [comment]
@skartikey - Talk to @DStrand1 and @jeffreyssmith2nd  on the Edge team.

**Comment by jeffreyssmith2nd** [comment]
OSS doesn't support `limit=-1` but with [this PR](https://github.com/influxdata/influxdb/pull/23719/files), you can actually get back more than 20 at a time through the API. That seems like it solves the issue here? It will go out with the 2.5 release, which is likely to be very soon.

**Comment by jeffreyssmith2nd** [comment]
@rschre Can you clarify what you mean by `query_api`? If I do an `influx buckets ls` or `influx query` using `buckets()` as the flux query, I see more than 20 buckets if they exist

**Comment by rschre** [comment]
> @rschre Can you clarify what you mean by `query_api`? If I do an `influx buckets ls` or `influx query` using `buckets()` as the flux query, I see more than 20 buckets if they exist

Sorry for being unclear:
- By running buckets() through the VS Code flux-addon
- Whatever grafana does when running "buckets()" through their Flux-Datasource.
- By using the python package as in the reply of bednar above: https://github.com/influxdata/flux/issues/5182#issuecomment-1281919795

Basically anywhere I can not specify a limit in parameters. Running influx query buckets() locally works, I can see more than 20 buckets there.

**Comment by jeffreyssmith2nd** [comment]
I believe this is a symptom of https://github.com/influxdata/influxdb/issues/23751. When you are not getting all of your buckets back, are you using a custom `read` token for buckets rather than the operator/all-access token>
