### ISSUE TITLE
Problem with specification of operator precedence

### ISSUE THREAD

**Issue by pierwill** [influxdata/flux#5187]
I've been [working](https://github.com/pierwill/flux-redex) to encode Flux's grammar in [PLT Redex](https://redex.racket-lang.org/). In the process, I've found what seems like a bug in the [specification of operator precedence](https://github.com/influxdata/flux/blob/master/docs/SPEC.md#operators-1). It seems that `AdditiveExpression` can never match.

(Here is the [relevant Redex code](https://github.com/pierwill/flux-redex/blob/7c16ac5eed46efd124039600854b38513ccd8513/flux.rkt#L212-L246).)

This problem came to light while running tests on the model. After specifying a language's grammar in a Lisp-like dialect, PLT Redex allows us to write tests like the ones below.

```
(test-match Flux ConditionalExpression
            (term ("if" a "then" b "else" c)
                  ))
```

```
(test-match Flux BuiltinStatement
              (term ("builtin" foo ":" ("[" "int" "]"))
                    ))
```

However, the following test failed in my model:

```
(test-match Flux Expression
              (term (a "+" b)
                    ))
```

```
./test
raco test: "./flux.rkt"
raco test: (submod "./flux_test.rkt" test)
FAILED /Users/will/repos/flux-redex/flux_test.rkt:130.2
  did not match pattern "Expression": '(a "+" b)
   0 ./flux.rkt
1 25 ./flux_test.rkt
1/25 test failures
```

Clearly `a + b` should be an expression. Of course, there could be a bug in the Redex code. Still, the issue is worth investigating to properly document and ensure the foundational correctness of the language.

**Comment by nathanielc** [comment]
We left factor the grammar before implemenation, this allows for handling the cases where multiple rules could match based on the first token. See https://www.gatevidyalay.com/left-factoring-examples-compiler-design/ for a little context. Could this be what is causing the issues here? I am not familiar with redex but it _could_ be that redex also needs the grammar to be left-factored before it works. 

For example here is the a left factored production rule https://github.com/influxdata/flux/blob/master/libflux/flux-core/src/parser/mod.rs#L1968 with its suffix https://github.com/influxdata/flux/blob/master/libflux/flux-core/src/parser/mod.rs#L1997

**Comment by pierwill** [comment]
Looking at this more, is it possible this is just a typo?

```
     UnaryLogicalExpression   = ComparisonExpression
                              | UnaryLogicalOperator UnaryLogicalExpression .
     UnaryLogicalOperator     = "not" | "exists" .
-    ComparisonExpression     = MultiplicativeExpression
-                             | ComparisonExpression ComparisonOperator MultiplicativeExpression .
+    ComparisonExpression     = AdditiveExpression
+                             | ComparisonExpression ComparisonOperator AdditiveExpression .
     ComparisonOperator       = "==" | "!=" | "<" | "<=" | ">" | ">=" | "=~" | "!~" .
     AdditiveExpression       = MultiplicativeExpression
                              | AdditiveExpression AdditiveOperator MultiplicativeExpression .
```

**Comment by nathanielc** [comment]
@pierwill That's it nice find!! Link to source https://github.com/influxdata/flux/blob/master/libflux/flux-core/src/parser/mod.rs#L1089 the ComparisonExpression rule does indeed follow on to the AdditiveExpression rule. Thanks
