### ISSUE TITLE
Spread-like operator (...) for merging records and arrays

### ISSUE THREAD

**Issue by sanderson** [influxdata/flux#5207]
JavaScript has a [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) that expands the contents of an iterable (array, object, etc.) to be used in another context. For example, merging objects and arrays:

```javascript
foo = [1, 2, 3]
bar = [4, 5, 6]

[...foo, ...bar]
// Returns [1, 2, 3, 4, 5, 6]

baz = {key1: "value1", key2: "value2"}
quz = {key3: "value3", key4: "value4"}

{...baz, ...quz}
// Returns {key1: "value1", key2: "value2", key3: "value3", key4: "value4"}
```

I can see this type of operator being very useful in Flux. For example, when joining data, it would allow you output all columns from both input streams without having to know their schema:

```javascript
import "csv"
import "join"

left = from(bucket: "example-bucket-1") |> // ...
right = csv.from(csv: "...") |> // ...

join.left(
    left: left,
    right: right,
    on: (l, r) => l.exampleCol == r.exampleCol,
    as: (l, r) => ({...l, ...r}),
)
```

You could also merge/union arrays:

```javascript
import "csv"
import "sql"

vals1 = csv.from(csv: "...")
    |> // ...
    |> findColumn(fn: (key) => true, column: "example-col-1")
    // Returns ["a", "b", "c"]

vals2 = sql.from(...)
   |> // ...
   |> findColumn(fn: (key) => true, column: "example-col-2")
   // Returns ["c", "d", "e"]

[...vals1, ...vals2]
// Returns ["a", "b", "c", "c", "d", "e"]
```

### Other thoughts
- I know this proposal is similar to the `with` operator, but the `with` operator only allows you to explicitly define what keys to add to the record. This would allow you to implicitly extend records with new key-value pairs.

### Challenges
- **Conflicting record keys**: If both records have the same key, what do we do?
    - Error: something like "error: duplicate keys in record" and inform the user to rename keys in one of the records
    - Define a merge precedence: honor the first instance of the duplicate key (left to right)
- **Type checking**: To merge arrays, the array types have to all be the same.

**Comment by nathanielc** [comment]
> Type checking: To merge arrays, the array types have to all be the same.

This part is the blocker. It is not possible to statically type check merged records while still keeping type inference intact. As such we have not been open to dynamically merging records. 

However something like this could work for both arrays and dictionaries.
