### ISSUE TITLE
Left join with an empty table returns ,,table is missing label column_name,,

### ISSUE THREAD

**Issue by greenenvy** [influxdata/flux#5218]
InfluxDB version: 2.4.0 runed on docker
flux version: v0.179.0

When both tables contain any data, the join runs successfully, like the following example:

```
import "array"
import "join"

leftTable = array.from(rows: [{deviceId: "1", value1: 1, value2: 5, value3: 6}]) 
rightTable = array.from(rows: [{deviceId: "1", value1: 4, value2: 4, value3: 4}]) 

join.left(
	left: leftTable,
    right: rightTable,
	on: (l, r) => l.deviceId == r.deviceId,
	as: (l, r) => {
        return {
            deviceId: l.deviceId,
            value1: l.value1,
            value2: l.value2,
            value3: l.value3
        } 
    }
)
```

When the right table is empty, then the following error occurs: **table is missing label deviceId**, even if in the result i'm not using anything from the right table.

```
import "array"
import "join"

leftTable = array.from(rows: [{deviceId: "1", value1: 1, value2: 5, value3: 6}]) 
rightTable = leftTable |> filter(fn: (r) => r.deviceId == "2")

join.left(
	left: leftTable,
    right: rightTable,
	on: (l, r) => l.deviceId == r.deviceId,
	as: (l, r) => {
        return {
            deviceId: l.deviceId,
            value1: l.value1,
            value2: l.value2,
            value3: l.value3
        } 
    }
)
```

And also the same happens if the left table is empty:

```
import "array"
import "join"

rightTable = array.from(rows: [{deviceId: "1", value1: 4, value2: 4, value3: 4}]) 
leftTable = rightTable |> filter(fn: (r) => r.deviceId == "2")

join.left(
	left: leftTable,
    right: rightTable,
	on: (l, r) => l.deviceId == r.deviceId,
	as: (l, r) => {
        return {
            deviceId: l.deviceId,
            value1: l.value1,
            value2: l.value2,
            value3: l.value3
        } 
    }
)
```

I saw an issue with the full.join where something really similar was discussed, but the pull request on that was just about the error message. The not updated message on the examples is because i'm using the flux version v0.179.0, but the error message is less important.

In the example if the right table is empty, then the result should be returned based on the left table (which obviously depends on how the join is being build). If any value from the right table is used, they probably should be null. If the left table is empty, then the result should just be empty.

For now i'm using a workaround where i'm checking if any of the table is empty, and if that is the case, i'm making dummyTables so the join can run which makes the queries not that pretty.

The reason this is important to me ( :D ) is because the performance of the new join package is much better than the old one, and it would also reduce some backend code because the old join was able just to perform an inner one.

**Comment by nZero22** [comment]
I have the same problem with empty data in the left or right table. We have been waiting a long time for the new join implementation because the old join has a really bad performance. But, we are still not able to use the new joins cause empty table. Our current workaround is to get data from the left and right tables and make the join in the backend. But this solution has many drawbacks.

**Comment by abalone23** [comment]
I posted about this last month:
https://github.com/influxdata/flux/issues/5134
Although it's been closed with an error update change, there is a draft here so I'm hopeful:
https://github.com/influxdata/flux/pull/5217

I suppose it's possible to create a dummy table with `union()` and filter out the dummy record afterwards, but it would be nice if that weren't necessary.
