### ISSUE TITLE
Allow Edition to be specified external to the Flux engine

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#5227]
With https://github.com/influxdata/flux/pull/5220 we need to support the edition being specified outside of the Flux script and outside the engine itself. We need to add plumbing to pass the edition down into the Rust frontend compiler code. 

See also https://github.com/influxdata/flux/issues/5226

DOD:
 - The Flux edition can be specified external to the engine itself, add param to Rust API
 - Any edition specified in the script has precedence over any external value.
 - Test to validate the precedence of edition values (should be contained in the semantic graph, whether it was external or in the script as an attribute)

**Comment by wolffcm** [comment]
Some notes from team discussion:

Places that editions can be specified, in order of priority starting from lowest:
- default (for non-cloud requests, i.e., OSS or vanilla REPL)
- Account-level edition
- HTTP API parameter (<-- i.e., could be set via the influx CLI)
- In the Flux script

User modules that are imported need to have an editions specified by the author of the module (or assume 1.0)
