### ISSUE TITLE
Rollout "Strict Null" Logicals

### ISSUE THREAD

**Issue by onelson** [influxdata/flux#5233]
Initially, #5188 aimed to take the 3 flavors (vectorized, row-based, interpreter) of logical operations in Flux and make them all behave with the rules outlined in the language spec with respect to null inputs.

The work was completed, and a feature flag (`strictNullLogicalOps`) guarded the new versions for the row-based and interpreter implementations.

In #5221 the new evaluator for the row-based impl was bypassed in an effort to assist with a perf investigation. Along with the bypass of the new evaluator, tests were also skipped _everywhere_ since even if the flag was enabled the necessary code would not run allowing the tests to pass.

---

We've got a few moving parts to track in order to deliver this work.

#5222 needs to land so that we can un-bypass the new row-based impl. This will allow us to select which evaluator we want to use with a single check of the feature flag instead of re-checking the flag with each call to `Eval`.

Prerequisites:
- #5222 has landed so we can read feature flags in the compiler
- #4777 

The above issues will need to be completed before this issue can be completely finished, but individual items in the DOD should be completed as early as allowable.

DOD:
- rework row-based flagging to happen once in compiler
- ~~adjust the flag to **default** to **enabled** (this will allow tests in OSS to work)~~ leave the flag defaults where they are, it's safer that way.
- unskip the relevant tests in flux and OSS
- Close out #5232 which reports a panic fixed by the new (currently flagged) interpreter code

**Comment by nathanielc** [comment]
> adjust the flag to default to enabled (this will allow tests in OSS to work)  

This bit concerns me, we need defaults to be safe so that if we fail to determine the value for a flag its default can't do any harm.

Changing defaults in order to be able to test means our testing system isn't robust (we this this already). To me the safe default in prod is more important than being able to test in OSS. This would also increase the priority of fixing our testing system in OSS to be able to set feature flags.

**Comment by onelson** [comment]
Re: setting the default, sure. This was just an idea to shorted the path to delivery since we're already a bit derailed by the EAR. 

My thinking is this would be to do okay since in production it'll be off for everyone to start.

I'll be looking to schedule the working group for #4777 to more better allow our flags to be set in OSS shortly, but that work has stalled before. I just don't want the logicals to be half-in-half-out any longer than they need to be.
