### ISSUE TITLE
Allow join to handle empty tables

### ISSUE THREAD

**Issue by scbrickley** [influxdata/flux#5307]
As it stands, join will return an error if one of its input tables is empty. This is because join relies on the type information from the column metadata in each input table to compile and run the `as` function.

However, because join already has a method for creating substitute records when one side of join doesn't have a match on the other side, we may be able to leverage that to substitute entire tables.

Here's a brief highlight of the changes that will likely be needed to teach join how to handle empty tables:

* Delay calling `Prepare()` on the `JoinFn` until after any default records are made. 
    - `Prepare()` is currently only called [here](https://github.com/influxdata/flux/blob/6459d46bbd91e04fef333deafb12ff468a3d74f7/stdlib/join/merge_join.go#L420), right before we evaluate the `joinProduct`. Default records are constructed [here](https://github.com/influxdata/flux/blob/6459d46bbd91e04fef333deafb12ff468a3d74f7/stdlib/join/join_fn.go#L88-L114).
* Modify the default records so that they only contain the group key values. Calling `Get()` on an object should return a null for any properties that don't exist, so this should not change any existing behavior.
* Adjust [this test](https://github.com/influxdata/flux/blob/6459d46bbd91e04fef333deafb12ff468a3d74f7/stdlib/join/join_test.flux#L422-L444) so that it no longer expects an error.
* Address failures that result from this changes.

_Note: I have a [draft PR](https://github.com/influxdata/flux/pull/5283) up that contains a very messy first pass at this. I was able to get join to handle empty tables on one side, provided that the other side had a non-empty group key. I then tried to handle the case where the group key was empty, but didn't get very far, and actually ended up regressing an old bug fix._

**Comment by Marwes** [comment]
When fixing shouldError the join_empty test no longer passes since it seems like `join` allows a non-empty table? I just skipped it here https://github.com/influxdata/flux/pull/5319/files#diff-c294ef316fa13418a60ccc6171d3931270831403553ddf531abd9c7b7ef68349R423 but whoever tackles this issue should update and enable the test to match what we do in this issue.

**Comment by mostafahk** [comment]
Still error exists

**Comment by WRFitch** [comment]
+1, I'd also find this useful.
