### ISSUE TITLE
go-autorest module going EOL

### ISSUE THREAD

**Issue by gwossum** [influxdata/flux#5312]
The module flux uses in the Azure SQL support, [github.com/Azure/go-autorest](https://github.com/Azure/go-autorest), is going EOL on March 31, 2023 according the README.md on GitHub. 

More details can be found at page linked to by README.md: https://azure.microsoft.com/en-us/updates/support-for-azure-sdk-libraries-that-do-not-conform-to-our-current-azure-sdk-guidelines-will-be-retired-as-of-31-march-2023/

**Comment by nathanielc** [comment]
@gwossum Thanks for the heads up we will look into migrating to https://github.com/Azure/azure-sdk-for-go
