### ISSUE TITLE
FluxQL needs a transform function

### ISSUE THREAD

**Issue by tallakt** [influxdata/flux#5340]
It is a bit annoying writing FluxQL queries to see that the functions that are built in, such as `difference(...)` has the ability to stream tables/rows while having state, but none of the supplied standard library building blocks give this possibility.

An option is using `reduce(..)` but it produces an accumulator value, not a stream.

I think adding something like Elixir's `transform(...)` function could solve this in a good way. 

https://hexdocs.pm/elixir/Stream.html#transform/3

This function acts like `map(...)` but also lets us maintain an accumulator that is maintained between every row processed. This would allow me to implement `difference(..)` in FluxQL.

I am using cloud influxdata

**Comment by tallakt** [comment]
This would also enable me to write a more sensible `stateCount(..)` function that counts starting from 1 every new distinct int that is encountered, eg:

```
sampledata.int()
    |> stateCount(fn: (r) => r._value)
```

https://docs.influxdata.com/flux/v0.x/stdlib/universe/statecount/

**Comment by sanderson** [comment]
Thanks @tallakt! This is definitely a highly requested feature and one we hope to address soon. I'm going to go ahead and close this issue in favor of existing issues/proposals, but feel free to add your thoughts:

- https://github.com/influxdata/flux/issues/4671
- https://github.com/influxdata/flux/issues/4142
- https://github.com/influxdata/flux/issues/2452

**Comment by tallakt** [comment]
The scan function is ok, the map with previous rows is a crappy suggestion. 

Overall I think more care should be put in making the FluxQL API more orthogonal. I find the functions that exists and the data model quite confusing.
