### ISSUE TITLE
Cannot using |> to() function to hosts with private IPs

### ISSUE THREAD

**Issue by mok-liee** [influxdata/flux#5345]
hello flux team,

following the documentation (https://docs.influxdata.com/flux/v0.x/stdlib/influxdata/influxdb/to/) i tried to move data to another local instance.

> OS: debian 11.5
> Influx: 2.5.1 OSS
> flux: 0.188.1 (https://docs.influxdata.com/influxdb/v2.5/reference/release-notes/influxdb/#v25-2022-11-01)

after hitting this example flux script,
```
data
    |> to(
        bucket: "example-bucket",
        org: "example-org",
        token: "tOkEn,
        host: "https://influx2-archive.local", // https://influx2-archive.local is resolved to an ip in a private cidr range
    )
```
i get the error `failed to initialize execute state: no such host`.

with that i did some research and i think the `PrivateIPValidator` throws this error on creating a new http writer client.

https://github.com/influxdata/flux/blob/4f3ae77c58fc7cf3e4c96c4cd7d23047b68d4a6f/dependencies/http/http.go#L65-L75
https://github.com/influxdata/flux/blob/def15add3f44db387232b1cfe3590b7108d4891c/dependencies/url/validator.go#L51-L55

which denies any private cidr.

https://github.com/influxdata/flux/blob/4f3ae77c58fc7cf3e4c96c4cd7d23047b68d4a6f/dependencies/url/validator.go#L64-L74

if am i right, is there a reason for this? the documentation says:

> `to()` writes data to an InfluxDB Cloud or 2.x bucket and returns the written data.

greetings mok

**Comment by Spunkmeyer32** [comment]
same issue over here.

**Comment by mok-liee** [comment]
before auto-closing... isn't that contrary to the docs?

**Comment by mok-liee** [comment]
friendly-reminder
