### ISSUE TITLE
limit(n)  returns over n results

### ISSUE THREAD

**Issue by NextLoad** [influxdata/flux#5347]
I See the document that describe "limit() returns the first n rows after the specified offset from each input table."
but I want to returns the first n rows from all data !
I've tried this one, but i get the result's count over 2;
![image](https://user-images.githubusercontent.com/32130375/206401068-c0ed0478-e50c-4563-bc7e-bf81ddc9e597.png)

when i use "select * from _measurement limit 2", i get the result's count equals 2
![image](https://user-images.githubusercontent.com/32130375/206401084-1c116236-d681-4e3a-8a1a-ace6aef8f851.png)

so i get a trouble, can i use this like :
```
from(bucket: "textile")
  |> range(start: 0)
  |> filter(fn: (r) => r._measurement == "collector")
  |> limit(n: 2)
  |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
  // |> limit(n: 2)
```
to get only 2 datas?

**Comment by sanderson** [comment]
@NextLoad You need to "ungroup" the data into a single table. In the screenshot of your output, the `table` column identifies each unique table in the output. Use `group()` before `limit()` group all data into a single table:

```js
from(bucket: "textile")
    |> range(start: 0)
    |> filter(fn: (r) => r._measurement == "collector")
    |> group()
    |> limit(n: 2)
    |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
```

**Comment by NextLoad** [comment]
@sanderson Thanks for your reply. I will try it.
