### ISSUE TITLE
decimate rather than downsample values

### ISSUE THREAD

**Issue by MarcoPignati** [influxdata/flux#5363]
Hello, 
I need to downsample (i’d rather say _decimate_) and get the values only at the minute roll-over (green arrows)
![image](https://user-images.githubusercontent.com/35630931/211850486-5121b7cb-74de-44a6-bdf5-5734acb67e4d.png)

I used `|> aggregateWindow(every: 1m, fn: first, createEmpty: true, timeSrc: "_start")` but I get the values corresponding to the red arrows.
This is because the first() gets **the first non null** value in the 1 minute window. Basically, the first() function is too smart for what I want to do.

I tried to create 2 different implementations of a _dumbfirst()_

`|> aggregateWindow(every: 1m, fn: (column, tables=<-) => tables |> limit(n: 1), createEmpty: true, timeSrc: "_start")`

`|> aggregateWindow(every: 1m, fn: (column, tables=<-) => tables |> bottom(n: 1, columns: ["_time"]), createEmpty: true, timeSrc: "_start")`

but they both give the same result as the first()

Any idea to achieve this simple _decimation/downsampling?_ Thanks!

**Comment by sanderson** [comment]
@MarcoPignati I _think_ you could do this by creating a custom aggregate with `reduce()`, but, tbh, I'm not sure how `reduce()` will handle the nulls. Try this:

```js
dumbfirst = (tables=<-, column="_value") =>
    tables
        |> reduce(
            identity: {index: 0, _value: 0.0},
            fn: (r, accumulator) => {
                _first = if accumulator.index == 0 then r._value else accumulator._value

                return {_value: _first, index: accumulator.index + 1}
            }
        )

data
    |> aggregateWindow(every: 1m, fn: dumbfirst)
```

**Comment by sanderson** [comment]
Actually, I just tested this and `reduce()` doesn't support null values. But when I tested with `limit(n:1)`, it did work for me. Here's my test:

```js
import "array"
import "internal/debug"

dumbfirst = (tables=<-, column="_value") =>
    tables
        |> reduce(
            identity: {index: 0, _value: 0.0},
            fn: (r, accumulator) => {
                _first = if accumulator.index == 0 then r._value else accumulator._value

                return {_value: _first, index: accumulator.index + 1}
            },
        )

array.from(
    rows: [
        {_time: 2023-01-01T00:00:00Z, _value: 1.1},
        {_time: 2023-01-01T12:00:00Z, _value: 1.2},
        {_time: 2023-01-02T00:00:00Z, _value: 2.1},
        {_time: 2023-01-02T12:00:00Z, _value: 2.2},
        {_time: 2023-01-03T00:00:00Z, _value: debug.null(type: "float")},
        {_time: 2023-01-03T12:00:00Z, _value: 3.2},
        {_time: 2023-01-04T00:00:00Z, _value: 4.1},
        {_time: 2023-01-04T12:00:00Z, _value: 4.2},
    ],
)
    |> range(start: 2023-01-01T00:00:00Z, stop: 2023-01-05T00:00:00Z)
    |> aggregateWindow(every: 1d, fn: (tables=<-, column) => tables |> limit(n: 1))
```

Here's the output:

| _start               | _stop                | _time                | _value |
| :------------------- | :------------------- | :------------------- | -----: |
| 2023-01-01T00:00:00Z | 2023-01-05T00:00:00Z | 2023-01-02T00:00:00Z |    1.1 |
| 2023-01-01T00:00:00Z | 2023-01-05T00:00:00Z | 2023-01-03T00:00:00Z |    2.1 |
| 2023-01-01T00:00:00Z | 2023-01-05T00:00:00Z | 2023-01-04T00:00:00Z |        |
| 2023-01-01T00:00:00Z | 2023-01-05T00:00:00Z | 2023-01-05T00:00:00Z |    4.1 |

So `limit` does return rows with null values.

**Comment by MarcoPignati** [comment]
@sanderson thanks for your help. I tested you solution with limit. I changed the input table because we do not write nulls. We have no entry in case of data loss (so I commented out your 2023-01-03T00:00:00Z input). I also added timeSrc: "_start" in the source, just because I tend to associate the point to the tstart.

I prepared a few tables below to explain the differences between your example and what we would like to get.

As you can see, using limit (or first()), for the time 2023-01-03T00:00:00Z, the value of 3.2 is returned. This value, in your input table, is written at time 2023-01-03T12:00:00Z. This means that the output table does not mirror the input in your example. I would like to have no value returned for 2023-01-03T00:00:00Z (or null).  I haven't found a way to simply "return the value if available otherwise return nothing". It seems that all the functions return the first value found in the "every" window (1d in your example). Probably the table below explain it better.
```
import "array"
//import "internal/debug"

array.from(
    rows: [
        {_time: 2023-01-01T00:00:00Z, _value: 1.1},
        {_time: 2023-01-01T12:00:00Z, _value: 1.2},
        {_time: 2023-01-02T00:00:00Z, _value: 2.1},
        {_time: 2023-01-02T12:00:00Z, _value: 2.2},
//        {_time: 2023-01-03T00:00:00Z, _value: debug.null(type: "float")},
        {_time: 2023-01-03T12:00:00Z, _value: 3.2},
        {_time: 2023-01-04T00:00:00Z, _value: 4.1},
        {_time: 2023-01-04T12:00:00Z, _value: 4.2},
    ],
)
    |> range(start: 2023-01-01T00:00:00Z, stop: 2023-01-05T00:00:00Z)
    |> aggregateWindow(every: 1d, fn: (tables=<-, column) => tables |> limit(n: 1), timeSrc: "_start")
```

**New input table** (note missing timestamp). This reflects how we write input data.
|_time|_value|
|------|------|
|2023-01-01T00:00:00Z|1.1
|2023-01-01T12:00:00Z|1.2
|2023-01-02T00:00:00Z|2.1
|2023-01-02T12:00:00Z|2.2 
|2023-01-03T12:00:00Z|3.2
|2023-01-04T00:00:00Z|4.1
|2023-01-04T12:00:00Z|4.2

**Output table** using limit() or first()
|_time|_value|
|------|------|
|2023-01-01T00:00:00Z|1.1
|2023-01-02T00:00:00Z|2.1
|2023-01-03T00:00:00Z|**3.2** (wrong, IMO)
|2023-01-04T00:00:00Z|4.1

**Desired output table:**
|_time|_value|
|------|------|
|2023-01-01T00:00:00Z|1.1
|2023-01-02T00:00:00Z|2.1
|2023-01-04T00:00:00Z|4.1

**Comment by sanderson** [comment]
Ah, I see. Ok. So IMO, `aggregateWindow()` isn't the correct function to use here. This function is designed to downsample by aggregating values in given time windows. Because these are aggregate operations, `aggregateWindow()` uses the window bounds (`_start` by default, but you can also use `_stop`) to assign a timestamp to the aggregate value.

So you accurately describe your use case--decimate vs downsample. For your desired output, I would do the following:

- Use `window()` to create time-based windows.
- Use `filter()` to only return rows where the `_time` value matches the `_start` value.
- Use `window()` with an `inf` interval to remove the windows.

```js
import "array"

array.from(
    rows: [
        {_time: 2023-01-01T00:00:00Z, _value: 1.1},
        {_time: 2023-01-01T12:00:00Z, _value: 1.2},
        {_time: 2023-01-02T00:00:00Z, _value: 2.1},
        {_time: 2023-01-02T12:00:00Z, _value: 2.2},
        {_time: 2023-01-03T12:00:00Z, _value: 3.2},
        {_time: 2023-01-04T00:00:00Z, _value: 4.1},
        {_time: 2023-01-04T12:00:00Z, _value: 4.2},
    ],
)
    |> range(start: 2023-01-01T00:00:00Z, stop: 2023-01-05T00:00:00Z)
    |> window(every: 1d)
    |> filter(fn: (r) => r._time == r._start)
    |> window(every: inf)
```

This returns:

| _start               | _stop                | _time                | _value |
| :------------------- | :------------------- | :------------------- | -----: |
| 2023-01-01T00:00:00Z | 2023-01-05T00:00:00Z | 2023-01-01T00:00:00Z |    1.1 |
| 2023-01-01T00:00:00Z | 2023-01-05T00:00:00Z | 2023-01-02T00:00:00Z |    2.1 |
| 2023-01-01T00:00:00Z | 2023-01-05T00:00:00Z | 2023-01-04T00:00:00Z |    4.1 |

Something to note here however is that timestamps must match perfectly with the window boundary (down to the nanosecond precision) for this to work. If you need to, you can use [`truncateTimeColumn()`](https://docs.influxdata.com/flux/v0.x/stdlib/universe/truncatetimecolumn/) to reduce the precision of your timestamps.

**Comment by MarcoPignati** [comment]
Thanks _a lot_, we had this issue for years! No problem with timestamp mismatch.

However, as this is not a pushdown function, I figured out that performance is much worse (~30x). 
For simplicity, below I am comparing the performance on an Influxdb instance where were we store measurements every 1seconds. In our normal application , measurements are written every 20ms in our application, so I expect even worse performance. A comparison of the performance:

**aggregation with first():**
|range|every|processing time|
|--|--|--|
|2h   | 1m | 0.04s|
|2h   | 5s   | 0.10s|
|2h   | 1s   | 0.34s|
|10h | 1m | 0.08s|
|10h | 5s   | 0.35s|
|10h | 1s   | 1.44s|

**new method (window+filter) without pushdown:**
|range|every|processing time|
|--|--|--|
|2h   | 1m | 0.60s|
|2h   | 5s   | 2.66s|
|2h   | 1s   | 9.84s|
|10h | 1m | 3.67s|
|10h | 5s   | 15.0s|
|10h | 1s   | 54.5s|

Is there a way to make this a pushdown function? Or when can I request for it to be added to the flux library and made pushdown? I am aware that it will take time, if it will be ever done, but I see plenty of use cases for this (every time you want to made further math on the data extracted, you need to work with correct value). For me it seems to be such an obvious step to have a performant data extraction, before having a performant aggregation. Thanks again for the support!

**Comment by sanderson** [comment]
@MarcoPignati can you [enable the `operator` profiler](https://docs.influxdata.com/influxdb/v2.6/query-data/optimize-queries/#measure-query-performance-with-flux-profilers) in your query and paste in the profile here?

**Comment by MarcoPignati** [comment]
Hi, sorry for the delay. Different timezones :). Below the values for a 10h extraction of data with a window of 1sec.

**Previous approach:**
```
import "regexp"
import "profiler"

option profiler.enabledProfilers = ["query", "operator"]

// Query to profile
Phasors = from(bucket: "short")
|> range(start: 2023-01-01T00:00:00.000Z, stop: 2023-01-01T10:00:00.000Z)
|> filter(fn: (r) => r["_measurement"] == "Phasor")
|> filter(fn: (r) => r.UID =~ /(RepDev0002-Freq|RepDev0002-ROCOF|RepDev0002-V1Zero|RepDev0002-VA1|RepDev0002-VB1|RepDev0002-VC1|RepDev0002-I1Zero|RepDev0002-I2Zero|RepDev0002-IA1|RepDev0002-IA2|RepDev0002-IB1|RepDev0002-IB2|RepDev0002-IC1|RepDev0002-IC2|RepDev0002-Stats-PacketLatency)/)
|> filter(fn: (r) => r["_field"] == "mag")
|> aggregateWindow(every: 1s, fn: first, createEmpty: false, timeSrc: "_start")
//|> window(every: 1s)
//|> filter(fn: (r) => r._time == r._start)
//|> window(every: inf)
|> drop(columns: ["_measurement", "aligned","_start","_stop","_field"])
|> sort(columns: ["_time"])
|> pivot(rowKey:["_time"], columnKey: ["UID"], valueColumn: "_value")
//|> rename(fn: (column) => regexp.replaceAllString(r: /RepDev([0-9]+)-([a-zA-Z0-9]+)/, v: column, t: "$2"))
|> yield()
```
<html>
<body>


table_PROFILER | _measurementGROUPSTRING | CompileDurationNO GROUPLONG | ConcurrencyNO GROUPLONG | ExecuteDurationNO GROUPLONG | flux/query-planNO GROUPSTRING | influxdb/scanned-bytesNO GROUPLONG | influxdb/scanned-valuesNO GROUPLONG | MaxAllocatedNO GROUPLONG | PlanDurationNO GROUPLONG | QueueDurationNO GROUPLONG | RequeueDurationNO GROUPLONG | RuntimeErrorsNO GROUPSTRING | TotalAllocatedNO GROUPLONG | TotalDurationNO GROUPLONG
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | profiler/query | 1487741 | 0 | 1339627573 | digraph { ReadWindowAggregateByTime15 // every = 1s, aggregates = [first], createEmpty = false, timeColumn = "_start", forceAggregate = false drop9 sort10 pivot11 yield12 ReadWindowAggregateByTime15 -> drop9 drop9 -> sort10 sort10 -> pivot11 pivot11 -> yield12 } | 0 | 0 | 15360064 | 0 | 54298 | 0 |   | 0 | 1341211800


</body>
</html>

<html>
<body>


table_PROFILER | _measurementGROUPSTRING | CountNO GROUPLONG | DurationSumNO GROUPLONG | LabelNO GROUPSTRING | MaxDurationNO GROUPLONG | MeanDurationNO GROUPDOUBLE | MinDurationNO GROUPLONG | TypeNO GROUPSTRING
-- | -- | -- | -- | -- | -- | -- | -- | --
1 | profiler/operator | 14 | 37146757 | drop9 | 3148314 | 2653339.785714286 | 5640 | *universe.schemaMutationTransformation
1 | profiler/operator | 1 | 41092469 | ReadWindowAggregateByTime15 | 41092469 | 41092469 | 41092469 | *influxdb.readWindowAggregateSource
1 | profiler/operator | 14 | 363293054 | sort10 | 52260117 | 25949503.85714286 | 2920 | *universe.sortTransformation
1 | profiler/operator | 14 | 401732516 | pivot11 | 44784319 | 28695179.714285713 | 6954 | *universe.pivotTransformation


</body>
</html>

**New approach:** as you can see, the window5 and filter6 are those taking the large majority of the time
```
import "regexp"
import "profiler"

option profiler.enabledProfilers = ["query", "operator"]

// Query to profile
Phasors = from(bucket: "short")
|> range(start: 2023-01-01T00:00:00.000Z, stop: 2023-01-01T10:00:00.000Z)
|> filter(fn: (r) => r["_measurement"] == "Phasor")
|> filter(fn: (r) => r.UID =~ /(RepDev0002-Freq|RepDev0002-ROCOF|RepDev0002-V1Zero|RepDev0002-VA1|RepDev0002-VB1|RepDev0002-VC1|RepDev0002-I1Zero|RepDev0002-I2Zero|RepDev0002-IA1|RepDev0002-IA2|RepDev0002-IB1|RepDev0002-IB2|RepDev0002-IC1|RepDev0002-IC2|RepDev0002-Stats-PacketLatency)/)
|> filter(fn: (r) => r["_field"] == "mag")
//|> aggregateWindow(every: 1s, fn: first, createEmpty: false, timeSrc: "_start")
|> window(every: 1s)
|> filter(fn: (r) => r._time == r._start)
|> window(every: inf)
|> drop(columns: ["_measurement", "aligned","_start","_stop","_field"])
|> sort(columns: ["_time"])
|> pivot(rowKey:["_time"], columnKey: ["UID"], valueColumn: "_value")
//|> rename(fn: (column) => regexp.replaceAllString(r: /RepDev([0-9]+)-([a-zA-Z0-9]+)/, v: column, t: "$2"))
|> yield()
```
<html>
<body>


table_PROFILER | _measurementGROUPSTRING | CompileDurationNO GROUPLONG | ConcurrencyNO GROUPLONG | ExecuteDurationNO GROUPLONG | flux/query-planNO GROUPSTRING | influxdb/scanned-bytesNO GROUPLONG | influxdb/scanned-valuesNO GROUPLONG | MaxAllocatedNO GROUPLONG | PlanDurationNO GROUPLONG | QueueDurationNO GROUPLONG | RequeueDurationNO GROUPLONG | RuntimeErrorsNO GROUPSTRING | TotalAllocatedNO GROUPLONG | TotalDurationNO GROUPLONG
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | profiler/query | 1560366 | 0 | 51047206770 | digraph { merged_ReadRange12_filter2_filter3_filter4 window5 filter6 // r._time == r._start window7 drop8 sort9 pivot10 yield11 merged_ReadRange12_filter2_filter3_filter4 -> window5 window5 -> filter6 filter6 -> window7 window7 -> drop8 drop8 -> sort9 sort9 -> pivot10 pivot10 -> yield11 } | 0 | 0 | 195054080 | 0 | 29466 | 0 |   | 0 | 51048820073


</body>
</html>

<html>
<body>


table_PROFILER | _measurementGROUPSTRING | CountNO GROUPLONG | DurationSumNO GROUPLONG | LabelNO GROUPSTRING | MaxDurationNO GROUPLONG | MeanDurationNO GROUPDOUBLE | MinDurationNO GROUPLONG | TypeNO GROUPSTRING
-- | -- | -- | -- | -- | -- | -- | -- | --
1 | profiler/operator | 380966 | 3536783028 | window7 | 23087147 | 9283.723555382896 | 4123 | *universe.fixedWindowTransformation
1 | profiler/operator | 14 | 10509045544 | window5 | 7053119017 | 750646110.2857143 | 10038 | *universe.fixedWindowTransformation
1 | profiler/operator | 1 | 3459702237 | merged_ReadRange12_filter2_filter3_filter4 | 3459702237 | 3459702237 | 3459702237 | *influxdb.readFilterSource
1 | profiler/operator | 380966 | 34720991109 | filter6 | 12430561 | 91139.34342959739 | 1853 | *universe.filterTransformation
1 | profiler/operator | 14 | 153690 | drop8 | 22461 | 10977.857142857143 | 4569 | *universe.schemaMutationTransformation
1 | profiler/operator | 14 | 357554003 | sort9 | 53607941 | 25539571.64285714 | 1931 | *universe.sortTransformation
1 | profiler/operator | 14 | 411950254 | pivot10 | 44378005 | 29425018.14285714 | 8223 | *universe.pivotTransformation


</body>
</html>

**Comment by sanderson** [comment]
@MarcoPignati Thanks for the info. Try this:

```js
import "regexp"
import "profiler"

option profiler.enabledProfilers = ["query", "operator"]

// Query to profile
Phasors = from(bucket: "short")
    |> range(start: 2023-01-01T00:00:00.000Z, stop: 2023-01-01T10:00:00.000Z)
    |> filter(fn: (r) => r["_measurement"] == "Phasor")
    |> filter(fn: (r) => r.UID =~ /(RepDev0002-Freq|RepDev0002-ROCOF|RepDev0002-V1Zero|RepDev0002-VA1|RepDev0002-VB1|RepDev0002-VC1|RepDev0002-I1Zero|RepDev0002-I2Zero|RepDev0002-IA1|RepDev0002-IA2|RepDev0002-IB1|RepDev0002-IB2|RepDev0002-IC1|RepDev0002-IC2|RepDev0002-Stats-PacketLatency)/)
    |> filter(fn: (r) => r["_field"] == "mag")
    |> aggregateWindow(every: 1s, fn: first, createEmpty: false, timeSrc: "_start")
    |> window(every: 1s)
    |> filter(fn: (r) => r._time == r._start)
    |> window(every: inf)
```

I realized that `first()` retains the original timestamp of the point, so you can use `_time` as the `timeSrc` in aggregate window and retain all your original timestamps while still getting the benefit of pushdowns. This reduces the amount of data that the subsequent functions have to operate on, but should still give you the behavior you're looking for.

**Comment by MarcoPignati** [comment]
Thank you. I went back to the original example as it quick to test and I do not see the expected result.
The filter after the window seem not to remove the aggregated value of 3.2. Have I not understood correctly? The output of first has the _time of 2023-01-03T00:00:00.000Z that is indeed wrong
```
import "array"

array.from(
    rows: [
        {_time: 2023-01-01T00:00:00Z, _value: 1.1},
        {_time: 2023-01-01T12:00:00Z, _value: 1.2},
        {_time: 2023-01-02T00:00:00Z, _value: 2.1},
        {_time: 2023-01-02T12:00:00Z, _value: 2.2},
        {_time: 2023-01-03T12:00:00Z, _value: 3.2},
        {_time: 2023-01-04T00:00:00Z, _value: 4.1},
        {_time: 2023-01-04T12:00:00Z, _value: 4.2},
    ],
)
    |> range(start: 2023-01-01T00:00:00Z, stop: 2023-01-05T00:00:00Z)
    |> aggregateWindow(every: 1d, fn: first, createEmpty: false, timeSrc: "_start")
    |> window(every: 1d)
    |> filter(fn: (r) => r._time == r._start)
    |> window(every: inf)
```

<html>
<body>


table_RESULT | _valueNO GROUPDOUBLE | _startGROUPDATETIME:RFC3339 | _stopGROUPDATETIME:RFC3339 | _timeNO GROUPDATETIME:RFC3339
-- | -- | -- | -- | --
0 | 1.1 | 2023-01-01T00:00:00.000Z | 2023-01-05T00:00:00.000Z | 2023-01-01T00:00:00.000Z
0 | 2.1 | 2023-01-01T00:00:00.000Z | 2023-01-05T00:00:00.000Z | 2023-01-02T00:00:00.000Z
0 | 3.2 | 2023-01-01T00:00:00.000Z | 2023-01-05T00:00:00.000Z | 2023-01-03T00:00:00.000Z
0 | 4.1 | 2023-01-01T00:00:00.000Z | 2023-01-05T00:00:00.000Z | 2023-01-04T00:00:00.000Z


</body>
</html>

**Comment by sanderson** [comment]
You didn't change the `timeSrc` in your test. Update it to `timeSrc: "_time"`:

```js
import "array"

array.from(
    rows: [
        {_time: 2023-01-01T00:00:00Z, _value: 1.1},
        {_time: 2023-01-01T12:00:00Z, _value: 1.2},
        {_time: 2023-01-02T00:00:00Z, _value: 2.1},
        {_time: 2023-01-02T12:00:00Z, _value: 2.2},
        {_time: 2023-01-03T12:00:00Z, _value: 3.2},
        {_time: 2023-01-04T00:00:00Z, _value: 4.1},
        {_time: 2023-01-04T12:00:00Z, _value: 4.2},
    ],
)
    |> range(start: 2023-01-01T00:00:00Z, stop: 2023-01-05T00:00:00Z)
    |> aggregateWindow(every: 1d, fn: first, timeSrc: "_time")
    |> window(every: 1d)
    |> filter(fn: (r) => r._time == r._start)
    |> window(every: inf)
```

**Comment by MarcoPignati** [comment]
Fixed. Result look ok in test with array. Thanks. 
I then applied the concept in my data set (the same as the example above)
I see no improvement at all in performance.
Below the profile table. The window9 and filter10 are still taking an order of magnitude more than the other functions.

```
import "regexp"
import "profiler"

option profiler.enabledProfilers = ["query", "operator"]

// Query to profile
Phasors = from(bucket: "short")
|> range(start: 2023-01-01T00:00:00.000Z, stop: 2023-01-01T10:00:00.000Z)
|> filter(fn: (r) => r["_measurement"] == "Phasor")
|> filter(fn: (r) => r.UID =~ /(RepDev0002-Freq|RepDev0002-ROCOF|RepDev0002-V1Zero|RepDev0002-VA1|RepDev0002-VB1|RepDev0002-VC1|RepDev0002-I1Zero|RepDev0002-I2Zero|RepDev0002-IA1|RepDev0002-IA2|RepDev0002-IB1|RepDev0002-IB2|RepDev0002-IC1|RepDev0002-IC2|RepDev0002-Stats-PacketLatency)/)
|> filter(fn: (r) => r["_field"] == "mag")
|> aggregateWindow(every: 1s, fn: first, createEmpty: false, timeSrc: "_time")
|> window(every: 1s)
|> filter(fn: (r) => r._time == r._start)
|> window(every: inf)
|> drop(columns: ["_measurement", "aligned","_start","_stop","_field"])
|> sort(columns: ["_time"])
|> pivot(rowKey:["_time"], columnKey: ["UID"], valueColumn: "_value")
//|> rename(fn: (column) => regexp.replaceAllString(r: /RepDev([0-9]+)-([a-zA-Z0-9]+)/, v: column, t: "$2"))
|> yield()
```

<html>
<body>


table_PROFILER | _measurementGROUPSTRING | CompileDurationNO GROUPLONG | ConcurrencyNO GROUPLONG | ExecuteDurationNO GROUPLONG | flux/query-planNO GROUPSTRING | influxdb/scanned-bytesNO GROUPLONG | influxdb/scanned-valuesNO GROUPLONG | MaxAllocatedNO GROUPLONG | PlanDurationNO GROUPLONG | QueueDurationNO GROUPLONG | RequeueDurationNO GROUPLONG | RuntimeErrorsNO GROUPSTRING | TotalAllocatedNO GROUPLONG | TotalDurationNO GROUPLONG
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | profiler/query | 1469666 | 0 | 60549768187 | digraph { ReadWindowAggregate17 // every = 1s, aggregates = [first], createEmpty = false, timeColumn = "", forceAggregate = false duplicate7 window8 window9 filter10 // r._time == r._start window11 drop12 sort13 pivot14 yield15 ReadWindowAggregate17 -> duplicate7 duplicate7 -> window8 window8 -> window9 window9 -> filter10 filter10 -> window11 window11 -> drop12 drop12 -> sort13 sort13 -> pivot14 pivot14 -> yield15 } | 0 | 0 | 195054080 | 0 | 16400 | 0 |   | 0 | 60551287997


</body>
</html>

<html>
<body>


table_PROFILER | _measurementGROUPSTRING | CountNO GROUPLONG | DurationSumNO GROUPLONG | LabelNO GROUPSTRING | MaxDurationNO GROUPLONG | MeanDurationNO GROUPDOUBLE | MinDurationNO GROUPLONG | TypeNO GROUPSTRING
-- | -- | -- | -- | -- | -- | -- | -- | --
1 | profiler/operator | 14 | 293532947 | sort13 | 24969867 | 20966639.07142857 | 3412 | *universe.sortTransformation
1 | profiler/operator | 14 | 429477486 | pivot14 | 47727462 | 30676963.285714287 | 1558 | *universe.pivotTransformation
1 | profiler/operator | 380966 | 2442761234 | duplicate7 | 190350011 | 6412.019009570407 | 2438 | *universe.schemaMutationTransformation
1 | profiler/operator | 14 | 150794 | drop12 | 37550 | 10771 | 1991 | *universe.schemaMutationTransformation
1 | profiler/operator | 1 | 5539573548 | ReadWindowAggregate17 | 5539573548 | 5539573548 | 5539573548 | *influxdb.readWindowAggregateSource
1 | profiler/operator | 380966 | 3670233442 | window11 | 54267426 | 9634.018369093304 | 2062 | *universe.fixedWindowTransformation
1 | profiler/operator | 380966 | 2944853677 | window8 | 29541053 | 7729.964555892127 | 3638 | *universe.fixedWindowTransformation
1 | profiler/operator | 14 | 10293138071 | window9 | 7127986511 | 735224147.9285715 | 3734 | *universe.fixedWindowTransformation
1 | profiler/operator | 380966 | 35194758903 | filter10 | 37764749 | 92382.93943029037 | 1660 | *universe.filterTransformation


</body>
</html>

**Note that:**
If I use `|> aggregateWindow(every: 1s, fn: first, createEmpty: false, timeSrc: "_start")` **only** the time goes from 60s to 1.4s (this we have seen it before).
If I use `|> aggregateWindow(every: 1s, fn: first, createEmpty: false, timeSrc: "_time")` **only** the time goes from 60s to 10s. This surprised me a bit. I did not attach the profiler for this. Just ask if interested

**Comment by sanderson** [comment]
Yeah, I think this may be because `aggregateWindow()` doesn't get pushed down if you use non-default values for parameters.

Going back to the original suggestion (without `aggregateWindow()`), you don't actually need the second `window()` call since you're dropping the start and stop columns right after. Dropping those columns will remove `_start` and `_stop`, effectively un-windowing the data, so that will give you some performance gains.

Also, you shouldn't need to re-sort the data. Nothing you're doing in the query should remove the time sorting of the data, so taking `sort()` out should also improve the overall performance.

**Comment by MarcoPignati** [comment]
Thanks. `sort()` was a leftover from historical reasons. Unfortunately, the impact of your latest suggestions is negligible. With or without the 2nd window and the sort, the time remains approx 50s (the 60s reported above, minus the 10s taken by the now-commented-out `|> aggregate timeSrc: "_time"`). Let me know if you see other potential improvements.

Going back to pushdown functions, is there a way we can contribute? Maybe someone in my team could give a look at the implementation of `aggregateWindow()` and, by following the same approach, make a new `decimateWindow()` that implements the `|>window |> filter |> window` in a "pushdown manner"? 
My feeling is that it is a basic and useful concept, that could inherit a lot from the existing implementation of the aggregation (actually could be simpler). But I am talking without knowing. I have the feeling that the decision of what is pushed down to the storage is somehow made at a different level.

```
import "regexp"
import "profiler"

option profiler.enabledProfilers = ["query", "operator"]

// Query to profile
Phasors = from(bucket: "short")
|> range(start: 2023-01-01T00:00:00.000Z, stop: 2023-01-01T10:00:00.000Z)
|> filter(fn: (r) => r["_measurement"] == "Phasor")
|> filter(fn: (r) => r.UID =~ /(RepDev0002-Freq|RepDev0002-ROCOF|RepDev0002-V1Zero|RepDev0002-VA1|RepDev0002-VB1|RepDev0002-VC1|RepDev0002-I1Zero|RepDev0002-I2Zero|RepDev0002-IA1|RepDev0002-IA2|RepDev0002-IB1|RepDev0002-IB2|RepDev0002-IC1|RepDev0002-IC2|RepDev0002-Stats-PacketLatency)/)
|> filter(fn: (r) => r["_field"] == "mag")
//|> aggregateWindow(every: 1s, fn: first, createEmpty: false, timeSrc: "_time")
|> window(every: 1s)
|> filter(fn: (r) => r._time == r._start)
//|> window(every: inf)
|> drop(columns: ["_measurement", "aligned","_start","_stop","_field"])
//|> sort(columns: ["_time"])
|> pivot(rowKey:["_time"], columnKey: ["UID"], valueColumn: "_value")
//|> rename(fn: (column) => regexp.replaceAllString(r: /RepDev([0-9]+)-([a-zA-Z0-9]+)/, v: column, t: "$2"))
|> yield()
```

**Comment by sanderson** [comment]
I do have a thought on another approach, but it may or may not work. Rather than windowing the data, you could try using `date` functions to analyze the timestamp and filter based on that analysis. Using our sample:

```js
import "array"
import "date"

array.from(
    rows: [
        {_time: 2023-01-01T00:00:00Z, _value: 1.1},
        {_time: 2023-01-01T12:00:00Z, _value: 1.2},
        {_time: 2023-01-02T00:00:00Z, _value: 2.1},
        {_time: 2023-01-02T12:00:00Z, _value: 2.2},
        {_time: 2023-01-03T12:00:00Z, _value: 3.2},
        {_time: 2023-01-04T00:00:00Z, _value: 4.1},
        {_time: 2023-01-04T12:00:00Z, _value: 4.2},
    ],
)
    |> range(start: 2023-01-01T00:00:00Z, stop: 2023-01-05T00:00:00Z)
    |> filter(fn: (r) => date.hour(t: r._time) == 0)
```

I don't know how performant this will be with larger datasets, but it's worth a try. You can add different or multiple date-part functions to the filter to get the precision you want/need.

**Comment by MarcoPignati** [comment]
Bingo! You might be into something! This is for the 10h at 1sec resolution. The 1.9 seconds are comparable with the 1.4s obtained with the `aggregateWindow(first)`. Thanks @sanderson !
![image](https://user-images.githubusercontent.com/35630931/212417981-02177296-9a37-4b2f-b07f-6fec7b15cd1a.png)
Now I have to figure out how to make this new filter more flexible and, say, decimate for multiple of 40ms, so pick 000, 040, 080, 120 and stuff like that! Normally the value in the `every` of the aggregateWindow was function of v.windowPeriod so I did not have control on it. This part might become tricky now, but I guess it's doable

**Comment by MarcoPignati** [comment]
I could probably always convert the windowPeriod to ms, then somehow find a way to say "filter for _multiples_ of this value in milliseconds"

**Comment by sanderson** [comment]
> I could probably always convert the windowPeriod to ms, then somehow find a way to say "filter for multiples of this value in milliseconds"

That's doable. And you might not even need the date package. Try this:

- Use `int()` to convert `v.windowPeriod` to nanoseconds (integer interpretation of a duration).
- Divide that by `100000` to convert it to milliseconds, then multiply that my `100000` do essentially round the duration down to the millisecond, but represent it as an integer.
- In your filter, convert your time stamp to to an interger (nanosecond representation of the timestamp) and use the modulo operator (`%`) to check if the remainder is 0.

```js
nsInterval = (int(v: v.windowPeriod) / 1000000) * 1000000

from(bucket: "short")
    |> range(start: 2023-01-01T00:00:00.000Z, stop: 2023-01-01T10:00:00.000Z)
    |> filter(fn: (r) => r["_measurement"] == "Phasor")
    |> filter(fn: (r) => r.UID =~ /(RepDev0002-Freq|RepDev0002-ROCOF|RepDev0002-V1Zero|RepDev0002-VA1|RepDev0002-VB1|RepDev0002-VC1|RepDev0002-I1Zero|RepDev0002-I2Zero|RepDev0002-IA1|RepDev0002-IA2|RepDev0002-IB1|RepDev0002-IB2|RepDev0002-IC1|RepDev0002-IC2|RepDev0002-Stats-PacketLatency)/)
    |> filter(fn: (r) => r["_field"] == "mag")
    |> filter(fn: (r) => int(v: r._time) % nsInterval == 0)
```

**Comment by sanderson** [comment]
☝🏻 That's only if you want the interval precision to be in ms. If you just want to use the raw `v.windowPeriod` value, you could just do this:

```js
from(bucket: "short")
    |> range(start: 2023-01-01T00:00:00.000Z, stop: 2023-01-01T10:00:00.000Z)
    |> filter(fn: (r) => r["_measurement"] == "Phasor")
    |> filter(fn: (r) => r.UID =~ /(RepDev0002-Freq|RepDev0002-ROCOF|RepDev0002-V1Zero|RepDev0002-VA1|RepDev0002-VB1|RepDev0002-VC1|RepDev0002-I1Zero|RepDev0002-I2Zero|RepDev0002-IA1|RepDev0002-IA2|RepDev0002-IB1|RepDev0002-IB2|RepDev0002-IC1|RepDev0002-IC2|RepDev0002-Stats-PacketLatency)/)
    |> filter(fn: (r) => r["_field"] == "mag")
    |> filter(fn: (r) => int(v: r._time) % int(v: v.windowPeriod) == 0)
```

**Comment by MarcoPignati** [comment]
Great! I'd gladly offer you a pizza! they both work (obviously).
![image](https://user-images.githubusercontent.com/35630931/212424997-194d084f-e181-4096-8814-fddd70dab390.png)

I slightly modified your second implementation. making `int(v:v.windowPeriod)` a variable and calling it in the filter makes it ~20% faster (2.5s vs 3.2s)
It's the first time I found someone so knowledgeable in flux. I have a long way to go. Thanks.

**Comment by sanderson** [comment]
Happy to help!
