### ISSUE TITLE
Docs: date.month vs. date.monthDay

### ISSUE THREAD

**Issue by SokoFromNZ** [influxdata/flux#5364]
I was looking into `date.monthDay` just now and was quite confused.
I think the table shown there (https://docs.influxdata.com/flux/v0.x/stdlib/date/monthday/) needs to go to `date.month`.

**Comment by sanderson** [comment]
Thanks for pointing this out @SokoFromNZ. I created #5366 to resolve this. I've also manually updated the documentation on docs.influxdata.com.
