### ISSUE TITLE
Increase function should have an optional parameter stating max value of the counter

### ISSUE THREAD

**Issue by christofe-lintermans-actemium** [influxdata/flux#5396]
Hi,

Imagine you are polling each second a counter:

95 ... 97 ... 99 ... 
1 ... 3 ... 5

increase would give you 99, 100, 102, 104

but you know in advance the counter actually reached 100 before resetting.

so increase should actually give 101, 103, 105

Could it be possible to pass this known limit to the increase function?  so the calculation would be more accurate?

Kind regards,

Christofe

**Comment by mamosk** [comment]
Hi,
I came here to submit the same issue, glad to see you had the same idea!
I add a couple of tips:
- this optional parameter should be named `threshold` (as the [doc page](https://docs.influxdata.com/flux/v0.x/stdlib/universe/increase/) uses this word)
- doc should recommend to use this optional parameter only in scenarios where the counter is not manually reset
