### ISSUE TITLE
How to filter by the size of keys()

### ISSUE THREAD

**Issue by RemHero** [influxdata/flux#5399]
### My requirement is to only find the sequence that contains the exact tag. 
For example, there are two sequences, seriesA {t1=v1}, and seriesB {t1=v1 and t2=v2}. Now I want to use an expression to find sequences that only contain {t1=v1}, that is, seriesA, without finding seriesB. I found that using ordinary filter statements cannot meet the requirements, so I want to implement it through the keys () statement, which means that I filter out redundant sequences by judging the length of keys (). How should I write query expressions?

**Comment by LarsStegman** [comment]
I am also interested in this!

**Comment by LarsStegman** [comment]
That does not do what we want. What if there is a third tag that we do not know the name of? We cannot write a filter for it, so we need to specify some way that we want exactly the tags we describe and no others.

**Comment by LarsStegman** [comment]
Not solved I think
