### ISSUE TITLE
join two table streams issue with flux

### ISSUE THREAD

**Issue by tbs575** [influxdata/flux#5427]
I have two table streams
one is
![image](https://github.com/influxdata/flux/assets/30616402/1b2f4e80-d641-4cf2-9f77-1af7f126e42c)

another is
![image](https://github.com/influxdata/flux/assets/30616402/fb8d5d13-0624-4447-822b-e9e86700173f)

try to join two tables stream with following flux
```
join.left(
    left: leftdata,
    right: rightdata,
    on: (l, r) => l.source_ip == r.source_ip,
    as: (l, r) => ({C: r.source_country}),
)
```
but can not get anything, should be retrun country information, is there problem? thanks
![image](https://github.com/influxdata/flux/assets/30616402/5749501b-8df7-4372-868e-5c6151cb3b43)

**Comment by MarcoPignati** [comment]
try playing with grouping the tables before joining them. I rememeber there was something in the docs about the need of grouping
