### ISSUE TITLE
flux compiler fail: `flux.pc'

### ISSUE THREAD

**Issue by Jerry0226** [influxdata/flux#5430]
mac ， go version go1.21.0 darwin/amd64

go build github.com/influxdata/flux/libflux/go/libflux:
# pkg-config --cflags  -- flux
Package flux was not found in the pkg-config search path.
Perhaps you should add the directory containing `flux.pc'
to the PKG_CONFIG_PATH environment variable
No package 'flux' found
pkg-config: exit status 1

I have tried a lot of methods mentioned in the issue, but the compilation still reports an error

**Comment by Jerry0226** [comment]
通过在mac 电脑上brew install flux。同时自己创建flux.pc 文件。增加PKG_CONFIG_PATH 环节变量。同时如果要编译kapacitor，因为最新的flux包和kapacitor依赖的版本有差异，需要修改代码

**Comment by Shnitzelil** [comment]
> By brew install flux on mac computer. At the same time, create the flux.pc file yourself. Add PKG_CONFIG_PATH link variable. At the same time, if you want to compile kapacitor, because the latest flux package and the version that kapacitor depends on are different, you need to modify the code.

Would you please paste here the content of flux.pc ?
