### ISSUE TITLE
An official Docker image is missing for flux (also pre-built binaries)

### ISSUE THREAD

**Issue by rosenfeld-ecore** [influxdata/flux#5435]
It would make it much easier to test flux scripts in CI pipelines if we had an official image with Flux.

It would also be very helpful if we could download Flux binaries for the supported platforms, so that we could install it quickly from other CI pipeline images.

**Comment by lmangani** [comment]
This is [already possible](https://github.com/metrico/fluXpipe), although not officially, based on the [InfluxCommunity/flux fork](https://github.com/InfluxCommunity/flux/tree/master/examples)
