### ISSUE TITLE
undefined libflux.Options

### ISSUE THREAD

**Issue by Pro-pra** [influxdata/flux#5453]
Hi all, 
i build influxdb and build fail with this error:
```
# github.com/influxdata/flux
vendor/github.com/influxdata/flux/runtime.go:48:27: undefined: libflux.Options
```

what right way to set libflux.Options ? i see libflux build fine on previous line in log.
My build command (use vendor dir):
```
go build -v -ldflags ' -O2 -fomit-frame-pointer -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -fstack-protector-strong --param=ssp-buffer-size=4 -m64 -mtune=generic     -X main.version=2.6.1     -X main.commit=1     -mod=vendor     ./cmd/influxd;
```

**Comment by Pro-pra** [comment]
https://github.com/influxdata/flux/issues/5425

**Comment by mwdmwd** [comment]
You need to have a C compiler installed, otherwise Go will silently ignore the file where `type Options` is defined because it [contains `import "C"`](https://github.com/influxdata/flux/blob/505186bac3c68b15ecb156492310e805445cfc1f/libflux/go/libflux/analyze.go#L5).
