### ISSUE TITLE
upgrade `github.com/SAP/go-hdb` to V1

### ISSUE THREAD

**Issue by paulheg** [influxdata/flux#5462]
When trying to build this right now, Im getting an error that `v0.14.1` of the `github.com/SAP/go-hdb` is not available any more.

I updated it to v1.0.0 for now to get it building again.

**Comment by paulheg** [comment]
Just found a work around:
```
GOPROXY=https://proxy.golang.org/cached-only go mod download github.com/SAP/go-hdb@v0.14.1
```

**Comment by chenwan0036** [comment]
I am also seeing the same issue:
```
% go list -m all
go: github.com/SAP/go-hdb@v0.14.1: invalid version: unknown revision v0.14.1
```
@paulheg's workaround didn't work for me.
