### ISSUE TITLE
Provide at least nighly builds RPMs

### ISSUE THREAD

**Issue by mjf** [influxdata/flux#567]
Hello.

Could (at least) some **nightly builds** of the *Flux* daemon be packaged for *RHEL*/*CentOS* and provided for general use and testing (including *Systemd* unit, proper paths, environment etc.), similarly as you provide the *RPM* packages of the *InfluxDB* and *Chronograf* nightly builds to play with? Thank you.

**Comment by nathanielc** [comment]
@mjf How are you using Flux right now? As part of the InfluxDB 1.7 release? Or something else? The nightly InfluxDB builds include the latest Flux releases as they happen and they are packaged up for RHEL/CentOS https://portal.influxdata.com/downloads

**Comment by mjf** [comment]
@nathanielc Oops! Sorry for that! I of course must have meant **alpha** releases where there are no *RPM*s at all yet... Thanks.
