### ISSUE TITLE
Run Benchmarks as part of CI test suite

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#569]
We want to ensure that our benchmarks run and are passing. In the context of this issue we do not care about the performance of the benchmarks, only that they are passing. A later issue can address how to run benchmarks in a consistent manner for watching performance changes over time. 

We should investigate configuring the benchmarks to only do a single pass so as to make them fast.

**Comment by mark-rushakoff** [comment]
In go1.12 you can use `-benchtime=1x` to run benchmarks for 1 iteration, to confirm they pass.

https://tip.golang.org/doc/go1.12#testing

**Comment by mark-rushakoff** [comment]
Now that go1.12 is out, and Flux is using it, this issue should get prioritized. Benchmarks are currently not all passing: https://github.com/influxdata/flux/issues/1247

In spite of them not all passing, `go test -run=^$ -benchtime=1x -bench=. ./...` finishes in about 45 seconds on my machine.
