### ISSUE TITLE
Type Conversions Internal Server Error

### ISSUE THREAD

**Issue by dan-hughes** [influxdata/flux#592]
None of the type conversions seem to be working and throw an internal server error.

I did try the cast() too from looking at the functions in the docs without success.

InfluxDB 1.7.2.

**Comment by nathanielc** [comment]
@dan-hughes Can you provide an example Flux script that produced the error?

**Comment by dan-hughes** [comment]
Sure, this is straight out of the Chronograf (1.7.4) query builder.

`from(bucket: "telegraf")
  |> range(start: dashboardTime)
  |> filter(fn: (r) => r._measurement == "mem" and r._field == "used")
  |>toFloat()`

**Comment by dan-hughes** [comment]
Stacktrace from InfluxDB if it's of any use.

`1f90b3eb-0eb8-11e9-987e-0242ac160003 5639 [panic:runtime error: invalid memory address or nil pointer dereference] goroutine 21140869 [running]:
runtime/debug.Stack(0xc01f695340, 0xc00011e300, 0xbf035cdd6ed7ee86)
         /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
 github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1.1(0xc01f695340, 0xc00011e300, 0xbf035cdd6ed7ee86, 0x3c4b68ee188f0, 0x1d15040, 0xc00011f900, 0x1356520, 0xc008a360e0)
         /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1690 +0xcd
 panic(0x105d960, 0x1cec870)
         /usr/local/go/src/runtime/panic.go:513 +0x1b9
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/semantic.(*CallExpression).Copy(0xc00014c300, 0xc02016e870, 0x1368901)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/semantic/graph.go:499 +0x10d
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/semantic.(*FunctionBlock).Copy(0xc0000c38b0, 0xc0056e0040, 0x1072e60)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/semantic/graph.go:401 +0x93
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/semantic.(*FunctionExpression).Copy(0xc00058dbc0, 0xc02036ee50, 0x0)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/semantic/graph.go:380 +0x8f
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*function).Resolve(0xc0059ac520, 0x13697a0, 0xc0059ac520, 0x7fa5a03d1a50, 0xc0059ac520)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:819 +0x32
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.ResolveFunction(0x13697a0, 0xc0059ac520, 0x2, 0x13697a0, 0xc0059ac520)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:806 +0x67
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations.createMapOpSpec(0x136a300, 0xc0059ac5e0, 0xc02036ee30, 0xc0209105f0, 0x40c428, 0x20, 0x10c6180)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/functions/transformations/map.go:54 +0xc4
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux.(*function).call(0xc0001c55f0, 0x136a300, 0xc0059ac5e0, 0xb16e25, 0x136a3c0, 0xc0059ac500, 0xc0059ac5e0)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/compile.go:612 +0x58
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux.(*function).call-fm(0x136a300, 0xc0059ac5e0, 0x136a300, 0xc0059ac5e0, 0x1362300, 0xc00000c0d0)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/compile.go:606 +0x3e
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.DoFunctionCall(0xc020910728, 0x136a3c0, 0xc0059ac500, 0xc0059ac500, 0xc000152168, 0xc00edf7b00, 0xc00edf7ad0)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:413 +0x77
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux.(*function).Call(0xc0001c55f0, 0x136a3c0, 0xc0059ac500, 0x11f58e4, 0x6, 0x1360020, 0xc00058dc00)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/compile.go:606 +0x61
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*Interpreter).doCall(0xc010b56a50, 0xc00014c360, 0xc0059ac4e0, 0x0, 0x0, 0x0, 0xc0209109b0)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:450 +0x2f5
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*Interpreter).doExpression(0xc010b56a50, 0x135fde0, 0xc00014c360, 0xc0059ac4e0, 0xc00014c360, 0x1, 0x0, 0x0)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:220 +0x176d
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*function).doCall(0xc0003f89a0, 0x136a300, 0xc0059ac4c0, 0x0, 0xc000276700, 0xc000404de6, 0x0)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:780 +0x6db
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*function).Call(0xc0003f89a0, 0x136a3c0, 0xc0059ac0c0, 0xc000404de6, 0x6, 0x135fde0, 0xc0126ae5a0)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:739 +0x69
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*Interpreter).doCall(0xc010b56a50, 0xc0126ae420, 0xc01f6954e0, 0x0, 0x0, 0xc0059ac000, 0xc0067ca4b0)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:450 +0x2f5
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*Interpreter).doExpression(0xc010b56a50, 0x135fde0, 0xc0126ae420, 0xc01f6954e0, 0xc0059ac060, 0xc0209111a8, 0x442de1, 0xc0059ac080)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:220 +0x176d
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*Interpreter).doStatement(0xc010b56a50, 0x135ff00, 0xc000b41b00, 0xc01f6954e0, 0x2, 0xc0059ac080, 0x1, 0x2)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:148 +0x5e6
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*Interpreter).doProgram(0xc010b56a50, 0xc0067ca4b0, 0xc0033ee0c0, 0xc020911280)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:128 +0x91
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*Interpreter).doRoot(0xc010b56a50, 0x135cf60, 0xc0067ca4b0, 0xc0067ca4b0, 0x0)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:112 +0xfa
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter.(*Interpreter).Eval(0xc010b56a50, 0x135cf60, 0xc0067ca4b0, 0x0, 0x0)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/interpreter/interpreter.go:106 +0x25b
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux.Eval(0xc010b56a50, 0xc00b4420e0, 0xd3, 0x3, 0xc0046f81a8)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/compile.go:78 +0x9e
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux.Compile(0x1357ea0, 0xc010b56930, 0xc00b4420e0, 0xd3, 0xbf035cdd6ed9074c, 0x3c4b68ee2a1b2, 0x1d15040, 0x0, 0x0, 0x0, ...)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/compile.go:50 +0x1f6
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/lang.FluxCompiler.Compile(0xc00b4420e0, 0xd3, 0x1357ea0, 0xc010b56930, 0x1d32e01, 0x0, 0xc00654ad38)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/lang/compiler.go:34 +0x89
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/control.(*Controller).compileQuery(0xc00017cea0, 0xc00654ac40, 0x134f020, 0xc005024480, 0x4, 0xc00654ac40)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/control/controller.go:173 +0x6e
 github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/control.(*Controller).Query(0xc00017cea0, 0x1357de0, 0xc0003dc400, 0x134f020, 0xc005024480, 0xc001fd01c7, 0x11f2413, 0x1, 0x0)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/influxdata/flux/control/controller.go:114 +0xa8
 github.com/influxdata/influxdb/services/httpd.(*Handler).serveFluxQuery(0xc00011f900, 0x7fa5a04b6478, 0xc01f695380, 0xc00011e300)
         /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1165 +0x1d9
 github.com/influxdata/influxdb/services/httpd.(*Handler).serveFluxQuery-fm(0x7fa5a04b6478, 0xc01f695380, 0xc00011e300)
         /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:217 +0x48
 net/http.HandlerFunc.ServeHTTP(0xc00035d1d0, 0x7fa5a04b6478, 0xc01f695380, 0xc00011e300)
         /usr/local/go/src/net/http/server.go:1964 +0x44
 github.com/influxdata/influxdb/services/httpd.(*Handler).responseWriter.func1(0x13521e0, 0xc0129f60f0, 0xc00011e300)
         /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1667 +0xab
 net/http.HandlerFunc.ServeHTTP(0xc0003f8b00, 0x13521e0, 0xc0129f60f0, 0xc00011e300)
         /usr/local/go/src/net/http/server.go:1964 +0x44
 github.com/influxdata/influxdb/services/httpd.gzipFilter.func1(0x1352260, 0xc01f695360, 0xc00011e300)
         /go/src/github.com/influxdata/influxdb/services/httpd/gzip.go:39 +0x204
 net/http.HandlerFunc.ServeHTTP(0xc0003f8b20, 0x1352260, 0xc01f695360, 0xc00011e300)
         /usr/local/go/src/net/http/server.go:1964 +0x44
 github.com/influxdata/influxdb/services/httpd.cors.func1(0x1352260, 0xc01f695360, 0xc00011e300)
         /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1609 +0xf3
 net/http.HandlerFunc.ServeHTTP(0xc0003f8b40, 0x1352260, 0xc01f695360, 0xc00011e300)
         /usr/local/go/src/net/http/server.go:1964 +0x44
 github.com/influxdata/influxdb/services/httpd.requestID.func1(0x1352260, 0xc01f695360, 0xc00011e300)
         /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1640 +0x179
 net/http.HandlerFunc.ServeHTTP(0xc0003f8b60, 0x1352260, 0xc01f695360, 0xc00011e300)
         /usr/local/go/src/net/http/server.go:1964 +0x44
 github.com/influxdata/influxdb/services/httpd.(*Handler).logging.func1(0x1352260, 0xc01f695340, 0xc00011e300)
         /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1648 +0xdc
 net/http.HandlerFunc.ServeHTTP(0xc0003f8b80, 0x1352260, 0xc01f695340, 0xc00011e300)
         /usr/local/go/src/net/http/server.go:1964 +0x44
 github.com/influxdata/influxdb/services/httpd.(*Handler).recovery.func1(0x1356520, 0xc008a360e0, 0xc00011e300)
         /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:1704 +0x147
 net/http.HandlerFunc.ServeHTTP(0xc0003f8ba0, 0x1356520, 0xc008a360e0, 0xc00011e300)
         /usr/local/go/src/net/http/server.go:1964 +0x44
 github.com/influxdata/influxdb/vendor/github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc0003f80c0, 0x1356520, 0xc008a360e0, 0xc00011e300)
         /go/src/github.com/influxdata/influxdb/vendor/github.com/bmizerany/pat/mux.go:117 +0x155
 github.com/influxdata/influxdb/services/httpd.(*Handler).ServeHTTP(0xc00011f900, 0x1356520, 0xc008a360e0, 0xc00011e300)
         /go/src/github.com/influxdata/influxdb/services/httpd/handler.go:381 +0x247
 net/http.serverHandler.ServeHTTP(0xc003fc2750, 0x1356520, 0xc008a360e0, 0xc00011e300)
         /usr/local/go/src/net/http/server.go:2741 +0xab
 net/http.(*conn).serve(0xc003f4a000, 0x1357de0, 0xc00498b7c0)
         /usr/local/go/src/net/http/server.go:1847 +0x646
 created by net/http.(*Server).Serve
         /usr/local/go/src/net/http/server.go:2851 +0x2f5`

**Comment by Anaisdg** [comment]
from(bucket: "telegraf") 
|> filter(fn:(r) => r._measurement == "cpu" and r._field == "usage_user") 
|> toFloat()

doesn't work as well.
