### ISSUE TITLE
Visualizing Histograms

### ISSUE THREAD

**Issue by dmamalis** [influxdata/flux#601]
Given that the Histogram functionality is still minimal, I am not sure if this is really an issue or a feature request.
Can Histograms be visualized with Chronograf?

Since `histogram()` destroys the `_time` tag, the results in chronograf look like a dot on the far left side of the graph. Am I missing something huge here?

**Comment by nathanielc** [comment]
@dmamalis This is a good request. Currently Chronograf expects to always graph data with the x axis being time. For histograms as you point out _time no longer has any meaning. We plan to update Chronograf to support graphing data where _time is not the x axis. I am not sure the status of that I'll ask around.

Once chronograf supports specifying which Flux columns should be the x and y axis then graphing histograms should be possible.

**Comment by russorat** [comment]
@dmamalis have you tried the histogram vis type in the latest influxdb alpha? https://v2.docs.influxdata.com/v2.0/visualize-data/visualization-types/#histogram

**Comment by dmamalis** [comment]
@russorat thanx for the link. I will give it a try asap
