### ISSUE TITLE
keys function slow over longer periods of time

### ISSUE THREAD

**Issue by chnn** [influxdata/flux#623]
The following query takes about 15 seconds to run on my laptop:

```
from(bucket: "telegraf")
  |> range(start: -30d)
  |> keys(except: ["_time", "_start", "_stop", "_value"])
```

This is with Flux 0.11.0 via platform.

The full query I am trying to run is
```
from(bucket: "telegraf")
  |> range(start: -30d)
  |> keys(except: ["_time", "_start", "_stop", "_value"])
  |> group()
  |> distinct()
  |> keep(columns: ["_value"])
  |> filter(fn: (r) => r._value != "_measurement")
  |> sort()
  |> limit(n: 200)
```
I'm running this query (multiple times and with slight variations) to retrieve tag keys. These tag keys will be used to populate dropdowns in a visual query builder in Chronograf:

![builder](https://user-images.githubusercontent.com/638955/50665585-0c5ccd00-0f66-11e9-9ba8-8de688961586.gif)

**Comment by wolffcm** [comment]
This is somewhat similar to another issue, but that one did not have `keys()`:
https://github.com/influxdata/flux/issues/214
