### ISSUE TITLE
yield produces no rows when rows should exist

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#629]
In this query:
```
from(bucket: "telegraf")
|> range(start: -20s)
|> filter(fn: (r) => r._measurement == "cpu" and r._field == "usage_user")
|> yield(name: "foo")
|> group(columns: ["cpu"])
```
The output for `foo` has a bunch of empty tables and the output for `_result` appears to have the correct answer for the query.  Strangely the output for `_result` appears first.  Are the results supposed to return in alphabetical order?

This bug was found as the workaround for this issue:
https://github.com/influxdata/flux/issues/628

**Comment by nathanielc** [comment]
@wolffcm The results are not sorted in any order.
