### ISSUE TITLE
Large query result exceeding grpc maxReceiveMessageSize return empty OK status

### ISSUE THREAD

**Issue by nikolay-t** [influxdata/flux#63]
When we execute query with expectation to return >300K points (i.e. 330 tags with 930 time points), query results OK response but empty content. Fluxd log shows this "ResourceExhausted desc = grpc: received message larger than max (4408148 vs.  4194304)"

Would it be possible to change grpc maxReceiveMessageSize by option in Flux?

**Comment by nathanielc** [comment]
This gRPC code has been removed.
