### ISSUE TITLE
Avoid empty `Do` calls in functions

### ISSUE THREAD

**Issue by affo** [influxdata/flux#643]
In functions `keys` and `columns` there is a call to `Do` on the input table that does nothing, just to "ensure that the iterators work properly" (see #640 and #641).

It is not clear whether this call is still necessary and, if so, in which cases.

We should investigate if it is necessary, and, if so, provide a more idiomatic way to update iterators status.

**Comment by jsternberg** [comment]
We can replace the empty calls to `Do` with `Done` now that `Done` is implemented
