### ISSUE TITLE
Update window to understand Null

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#645]

**Comment by jsternberg** [comment]
With this one, does this mean making it so `window()` generates null values for empty intervals or just that it works with records that are already null?

**Comment by jsternberg** [comment]
For the record, if it is the latter, this is done and no work has to be done.

**Comment by nathanielc** [comment]
Just that is works with records that are already null. The empty windows should remain empty. Only if they pass through an operation that understands empty as nil should they change.
