### ISSUE TITLE
Enhance language syntax to address a value of an object / row using a variable

### ISSUE THREAD

**Issue by stuartcarnie** [influxdata/flux#697]
IFQL has no support to dynamically access the value of an object (such as in the `map` function) using a variable.

**Use Case:**

I would like to write a `distinct` function as follows:

```
distinct(col, table=<-) => table
  |> group(by:[col])
  |> limit(n:1)
  |> map(fn:(r) => r[col])
  |> group(none:true)
```

Note that the `map` function selects the column dynamically using the `col` variable.

**Comment by russorat** [comment]
Flux now has a distinct function: https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/selectors/distinct/

leaving this open as a feature request, but the use case might need to be updated.
