### ISSUE TITLE
fromInfluxLP  source

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#70]
A from source that reads Line protocol.  
*  should support multiple measurements/fields

**Comment by wolffcm** [comment]
Some notes from Slack discussion about how to parse line protocol:

- There are a surprising number of edge cases in parsing line protocol, mostly related to escaping in string data
- The "official" parser in the `influxdb` repo has bugs that must be replicated to ensure consistent behavior with other parts of the product
- There is also a parser in `telegraf` whose behavior does not quite match that the behavior of the one in `influxdb`
- The ideal place for a line protocol parser would be in the repo `line-protocol` which currently includes a writer but not a parser.
