### ISSUE TITLE
Requirements for flux repo CLI tool

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#71]
Notes: 
1.   have `flux` delivered as a CLI named that with no dependency on InfluxDB. 
2.  brew installable/go gettable. 
3.  The Flux command should support all the from types. 
4.  For InfluxDB there should be a from that uses the HTTP interface (the 2.0 one). So it would only work against 1.7 or higher
5.  Ideally, all the RPC logic can be extracted into a library that can just be used by flux, the influx CLI or anything else. We’ll want more complicated logic over time for each of the from sources

**Comment by rbetts** [comment]
Thanks Adam - for [2] - let's change that from nice-to-have to a requirement? We don't need to build the brew recipe now .. but for sure it needs to be go-gettable.  We can assume that we are in the future and can rely on go module support everywhere.
