### ISSUE TITLE
Explore supporting continuity across block boundaries for difference/derivative functions

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#713]
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#212  

https://github.com/influxdata/influxdb/issues/6451
https://github.com/influxdata/influxdb/issues/6878

**Comment by yellowpattern** [comment]
is there any progress on this ticket?

**Comment by nathanielc** [comment]
@yellowpattern No, this isn't currently on our radar. Normally you  can work around the problem by doing the difference/derivative before doing any window boundaries etc. Do you have a specific use case in mind? Maybe we can help you get it working. Or if the work around doesn't work for you then it would be great to document that here so we can design/build the feature you actually need.  Any additional information you can provide will be much appreciated.
