### ISSUE TITLE
Add support for disambiguate an integer wrap vs reset to difference/derivative functions

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#721]
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#224  

https://github.com/influxdata/influxdb/issues/5954

For example using uptime to know if a packet counter wrapped or reset.

**Comment by russorat** [comment]
does the new rate  function solve this? https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/experimental/aggregate/rate/

fyi @jsteenb2
