### ISSUE TITLE
Add max keyword argument to difference/derivative functions.

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#722]
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#223  

https://github.com/influxdata/influxdb/issues/5954

The max helps account for integer wrap.

**Comment by jsternberg** [comment]
The function signature has to be discussed before working on this so if you are a community member planning to work on this, please consult us about API design before beginning your work. Thanks.

**Comment by davidby-influx** [comment]
@timhallinflux - this resurfaced in another issue in which I will tag you. I have provided a work-around in that issue, but this is obviously a better (but more expensive) solution for Flux to implement.
