### ISSUE TITLE
Support fill(previous) where first value is missing and outside of time bounds.

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#724]
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#210  

https://github.com/influxdata/influxdb/issues/5943

**Comment by SGStino** [comment]
first value missing also applies to non-windowed queries:
```
previous = from(bucket: "Data")
  |> range(stop: v.timeRangeStart, start: 0) 
  |> filter(fn: (r) => r["_measurement"] == "Tags.PLC_252.TANK1.STAPNR")
  |> filter(fn: (r) => r["_field"] == "value")  
  |> last()
  
current = from(bucket: "Data")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "Tags.PLC_252.TANK1.STAPNR")
  |> filter(fn: (r) => r["_field"] == "value")  

union(tables: [previous, current])  
```

(aside of an issue that this results in two tables in the final result set), a shortcut would be nice there too.
not sure if fill(use_previous:true) should fix this though, or something else?
