### ISSUE TITLE
Add printf function

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#731]
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#316  

Possible function signature `printf = (fmt, args={}) => ...` where `fmt` is the format string and args is an object of values to format.

**Comment by affo** [comment]
The problem in directly porting Go's `fmt.Print` is that we don't support variadic arguments, neither mixed-type arrays. We could support something like:

```
import s "strings"
s.fmt("this is a number {n}, this is a string {s}", o: {n: 1, s: "lol"})
```

I don't like the idea of `printf`, but I like `strings.fmt`. If one wants to print to screen, he can simply write down the expression as we did up to now, as we suppose that the output of an `ExpressionStatment` is the screen (if the query is sent to a server, then what is printed to screen is not returned).

**Comment by quentinmit** [comment]
I just ran across this issue while trying to format a date. While you probably also need a date-specific format function, how would you feel about at least defining the simpler function of

```
number.sprintf(fmt:"%02x", v: 5)
```

to allow sprintf'ing a single number? Or even just sprintf with a single-type array would still be super useful (though harder to justify, I think). While sprintf can also be used on strings, I feel like 90% of the use cases would be covered by sprintf on numbers.

The problem with the `s.fmt` proposed above is that it has no mechanism for using any of the sprintf-style format operators. And I don't think you really want to be in the business of inventing your own format string syntax. I wonder if it's possible to write a parser that takes a Python-style format string (e.g. `this is a number %(n)02x, this is a string %(s)s`) and translates it into a series of calls to `fmt.Sprintf`.

**Comment by quentinmit** [comment]
This hasn't been completed and is still needed
