### ISSUE TITLE
SPEC: allow types to be specified for declarations

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#749]
From ifql created by [jsternberg](https://github.com/jsternberg) : influxdata/ifql#344  

I think we should allow types to be declared in the specification. While the language does not have to specify types, types do exist and it is statically typed. I've thought a lot about types and I personally think we should allow optional type specifications in ifql. I don't think we'll do that, but I would like to open up the possibility of alternative languages that do have user-specified function types.

To do this, I feel that it has to be included in the spec. As an example, imagine that we had a function specification like this:

```
type FunctionParam struct {
    Key         *Identifier `json:"key"`
    Type        *Type       `json:"type"`
    Default     Expression  `json:"default"`
    Piped       bool        `json:"piped,omitempty"`
    declaration VariableDeclaration
}
```

If a type is not specified for a function parameter, then it is inferred. But, this would allow a person to implement a function specification that says, "I am expecting this function to take a specific type of argument".

I also think this is related to polymorphic function signatures and function overloading that is implied as needed in the "Function types" section. I'm going to open another issue for addressing that specifically though.

**Comment by nathanielc** [comment]
Flux spec now allows for types to be specified.
