### ISSUE TITLE
SPEC: support for calendar-aware duration literals

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#754]
From ifql created by [jsternberg](https://github.com/jsternberg) : influxdata/ifql#341  

I think we should formally introduce the `M` and `y` duration specifiers. This is something we miss in influxql because time zones were added too late in the language to make them usable, but defining how these work and then declaring them not implemented would allow for a future expansion of the language.

A year is not the same as 52 weeks. 52 weeks doesn't consider for time zone and leap year differences and it also adds up to 364 days, not even 365. Because of leap years, saying "use 365 days" does not actually give the person what they want which is the last year. If a person wants the last year, it helps us a lot to _know_ they want the year so we can adjust it for them using calendar-aware range functions.

This is similar to month. A common request we get with influxql is the ability to aggregate January, February, etc. We should add the month duration unit so that we don't lose this valuable information and can make a future expansion.

We should not implement any of these without including the calendar-aware functionality. They would  be left as a placeholder in the spec until we can implement that functionality.

**Comment by nathanielc** [comment]
The SPEC contains  a detailed specification of calendar duration literals.
