### ISSUE TITLE
Design the handling template properties in IFQL

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#755]
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#169  

Kapacitor has a feature where for alert handlers and various other properties a template can be provided that is evaluated with the context of the data. For example an alert message can be a template, allowing for dynamic content in the message like `serverA is OK` or `serverB is CRITICAL`.

In Kapacitor this was accomplished by using Go's text/template package. While feature rich and a simple templating language, its not well documented in the context of Kapacitor. In addition any property that wants to support templating needs to explicitly implement it. So a user doesn't immediately know if a given property supports it.

Its even being requested that all alert related properties support templates https://github.com/influxdata/kapacitor/issues/1717

For IFQL I would like to support a more natural templating system, more like Ruby string interpolation than a full featured templating system. Then potentially all strings in IFQL can support interpolation based on the context of the string.  Where this gets tricky though is knowing when to interpolate a string based on the static vars within the IFQL script and when to wait to interpolated based on the data within the point record.

Open to ideas here.

**Comment by russorat** [comment]
i think this is possible now based on the string interpolation work: https://v2.docs.influxdata.com/v2.0/monitor-alert/checks/create/#example-status-message-template

**Comment by nathanielc** [comment]
Correct string interpolation solves this need.
