### ISSUE TITLE
String interpolation doesn't work as expected in flux

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#756]
Basic string interpolation doesn't appear to work in flux. For example one would expect the following query: 
```flux
n = 1
fieldSelect = "field{n}"
from(db:"db")
    |> range(start:-5m)
    |> filter(fn: (r) => r._field == fieldSelect)
```
to return the same data as a query using a literal field name:
```
...
|> filter(fn: (r) => r._field == "field1")
```
Currently, no data is returned when string interpolation is used.

**Comment by nathanielc** [comment]
This is not implemented yet, follow #730 for status.
