### ISSUE TITLE
Add alert function

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#758]
From ifql created by [pauldix](https://github.com/pauldix) : influxdata/ifql#172  

The alert function defines when to generate an alert, which is always written out to a bucket. It looks like:

```
// here's an example of a full alert with a notification
from(...)
  .range(...)
  .alert(
     name: "foo",
     description: "ffoo"
     crit: r => ({condition: r.value() > 10, message: "foo is bar"}),
     warn: r => ({condidtion: r.value() > 3}),
     normal: r => ({condition: r.value() == 0}),
     bucket: "something-alerts")
  .outputSlack(
     url: loadSecret(name:"slackUrl"),
     channel: "#general",
     message: r => r["_message"],
     rateLimit: 0)
```

`name` and `bucket` are required parameters. It is where the alert will be logged and where it can be picked up by an alert handler to send out notifications. Other parameters are `crit`, `warn`, `info`, `level`. 

Level will be used to define dynamic levels. The function must return a map with `level` (as integer), `condition`, and `message`.

We also need to be able to define a message, which will be dynamic based on the alert level that was triggered. This means that the level functions must return a map, which would have two values: `condition` and `message`.

The alert node will return a record with all tags and addition field columns `_message`, `_duration` and tags `_alert_name` and `_level`. When the alert is written to the output bucket, it actually writes multiple points. Each field column becomes a point. For example, if you had the following point that generated a critical alert:

```
{"_measurement":"cpu", "host":"serverA", "_field":"usage_system"} 23.2 123
```

That is a value of `23.2` at time `123`. The resulting output would be:

```
{"_measurement":"cpu", "host":"serverA", "_field":"usage_system", "_level":"crit", "_alert_name":"foo"} 23.2 123
{"_measurement":"cpu", "host":"serverA", "_field":"_message", "_level":"crit", "_alert_name":"foo"} "some alert message" 123
{"_measurement":"cpu", "host":"serverA", "_field":"_duration", "_level":"crit", "_alert_name":"foo"} 98234987234983274 123
```

**Comment by russorat** [comment]
is this still valid after the monitoring and alerting work?

**Comment by nathanielc** [comment]
Nope, this can be closed
