### ISSUE TITLE
Push Down aggregates when Grouping

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#767]
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#168  

Currently the IFQL planner only pushes down aggregates if there is no grouping specified. This is because the aggregates are always performed on a per series basis. In order to push down the aggregates we need to teach the storage block type to be able to aggregate the aggregates. And we need to teach the planner when this is possible.

**Comment by yzhang1991** [comment]
https://github.com/influxdata/influxdb/blob/master/storage/reads/group_resultset.go#L298
