### ISSUE TITLE
Add multi-line comments to parser

### ISSUE THREAD

**Issue by pauldix** [influxdata/flux#769]
Should we add multi-line comments to Flux? Was thinking just the usual `/* ... */`

Thoughts @nathanielc?

**Comment by nathanielc** [comment]
So far no one has asked for them and they have some interesting challenges if you start to nest them so for now I say no. We can always reopen and revisit later.

**Comment by luiswenus** [comment]
Please make this happen.

**Comment by dsk0** [comment]
As a user, block comments would be useful, got here when searching for how to use them in flux.

**Comment by srbpavel** [comment]
please, any update to multi line comment

**Comment by pseudocoder** [comment]
I would also appreciate this option
