### ISSUE TITLE
Allow differing aggregate functions to apply to different columns of the same table.

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#770]
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#207  

Currently only a single aggregate function can be applied to a window. If multiple aggregates are desired one must perform each aggregate separately and then join the results back together. 

In other words the user should not need to rejoin a table that has already been joined.

In addition the `_time` column should be available for aggregation.
https://github.com/influxdata/influxdb/issues/5369

**Comment by yenicelik** [comment]
Was this resolved by now? The above issue seems to lead to a dead link
