### ISSUE TITLE
What to do about COUNT with missing data?

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#774]
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#211  

https://github.com/influxdata/influxdb/issues/6412
https://github.com/influxdata/influxdb/issues/6967

Do we create series for all tag in the index? How could we do that in a deterministic manner.

**Comment by jsternberg** [comment]
This is now done. If you want to keep empty tables after filtering, you can use `onEmpty: "keep"` and the default is to drop empty tables. Count will produce zero if the table is empty.
