### ISSUE TITLE
Specify the Union function

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#79]
Update the SPEC.md

**Comment by andig** [comment]
Coming here from Migrated from https://github.com/influxdata/influxdb/issues/5808#issuecomment-464502072 it would be great if flux allowed to union queries covering the same timebase but different aggregation functions. 
Not having found anything regarding union yet- where could I start exploring?

**Comment by wolffcm** [comment]
Hi @andig What you are describing certainly seems possible with the `union` function in Flux.  Here's the doc page for it:
https://docs.influxdata.com/flux/v0.12/functions/transformations/union/
