### ISSUE TITLE
Refactor commented out test cases in the interpreter to work with new interface

### ISSUE THREAD

**Issue by jpacik** [influxdata/flux#795]
A group of test cases has been commented out in `interpreter/package_test.go` due to an interface change on the interpreter. The tests need to be refactored to work with the new interface.

**Comment by nathanielc** [comment]
@jlapacik  Is this still an issue? Or can we close it?

**Comment by jlapacik** [comment]
@nathanielc I think we can close this issue. There are still some commented out test cases that need to be reworked due to the interpreter interface changing a while back. But we have pretty good test coverage as is (not including the ones that are commented out).

What do you think?

**Comment by nathanielc** [comment]
Let's delete the tests then, instead of leaving them commented out.
