### ISSUE TITLE
Infinite loop in REPL when calling csv.from

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#898]
I get an infinite loop of flux tables when I enter this from the REPL:

```
inData = "
#datatype,string,long,string,long
#group,false,false,true,false
#default,_result,long,,
,result,table,key,val
,,0,k,0
,,0,k,1
,,0,k,2
"
import "csv"
csv.from(csv: inData)
```
I get this:
```
Table: keys: [key]
            key:string                     val:int
----------------------  --------------------------
Table: keys: [key]
            key:string                     val:int
----------------------  --------------------------
```
Over and over, forever.  I have to `kill -9` to stop it.

**Comment by jlapacik** [comment]
This is occurring due to an invalid default annotation `#default,_result,long,,`. A valid annotation would be `#default,_result,,,` or perhaps `#default,_result,0,,`. However I would expect it to return an error(something like `expecting int, got string`), but instead it goes into an infinite loop.
