### ISSUE TITLE
Derivative, integral and stateDuration should error if the _time is not sorted

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#906]
The idea here is that when the planner can understand sorting requirements it can prevent these errors in the future. The currently implementation should avoid these errors since data is  sorted by _time by default.

**Comment by wolffcm** [comment]
Hey @affo I'll update the behavior for `derivative` and I guess you can update your existing PR for `stateDuration` to have the behavior discussed at IPM.  I'm not familiar with `integral`, I guess either one of us could take a look.

**Comment by affo** [comment]
For integral, I can do it

**Comment by affo** [comment]
Fixed by #908 and #913
