### ISSUE TITLE
Unable to reference columns with dashes in name

### ISSUE THREAD

**Issue by zarbis** [influxdata/flux#915]
I have a table that that has column `action` with values like: `app-installed`, `app-launched`, etc... If I use `pivot()` function to create columns from those values I end up with column names that I cannot reference in anonymous functions inside `filter()` or `map()` function, e.g. I cannot do things like this:
```
from(bucket: "analytics")
|> range(start: -7d)
|> filter(<OMITED>)
|> group(columns: ["action"])
|> aggregateWindow(every: 1d, fn: sum)
|> pivot(rowKey: ["_time"], columnKey: ["action"], valueColumn: "_value")
|> map(fn: (r) => ({
  _time: r._time,
  launches: r.app-started
}))
```
Those names seem to be treated like subtraction operation. I've tried different common methods of escaping like quotes and backslashes with no success.

**Comment by aanthony1243** [comment]
found a typo in the code,  `r.["app-started"]` -> `r["app-started"]`
