### ISSUE TITLE
Thread-local storage without the threads

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#931]
This is a proposal to add something similar to thread-local storage to Flux. Flux of course doesn't have threads but it does have global mutable variables in the form of options. Currently options are only declared at the package level, but they can be referenced from anywhere inside of a Flux script.

Take the `now` option for example. This option is defined in the prelude and so is always visible/modifiable inside of a Flux program. If I have a function `f` that references `now`, any mutations to that option will change the behavior of `f`. Sometimes this is what we want, but other times we would like to set the value of a global option for a specific function call and have that mutation only visible inside of that specific block with the change going out of scope with the function. This is currently not possible in Flux.

## Proposal

There are two proposals:

1. Allow declaration and mutation of options from anywhere inside of a Flux program.
2. Define a block with the keyword `local` that signifies the creation of a separate execution context for said block distinct from the enclosing environment.

Before explaining allow me to provide an example:

```Flux
package foo

now = () => 2010-01-01T00:00:00Z

g = () => {
  option now = () => 2012-01-01T00:00:00Z

  // range references the now option
  return from() |> range() |> filter()
}

local {
  g()
}

// current now time after function call is 2010-01-01T00:00:00Z

g()

// current now time after function call is 2012-01-01T00:00:00Z
```

From here we see that we can mutate an option inside of a function block, and by calling that function inside of a `local` block, that option mutation is only visible inside of that block. Once the function returns the original execution context is restored.

So let me address both proposals, starting with options.

Currently the use of options is highly restricted. They can only be declared at the level of the package block and they can't be mutated in the same package they are defined. Instead any mutations must occur in an external package, again only at the level of the package block. By removing the built-in safety features around options and allowing declarations and mutations to occur anywhere inside of a Flux program I believe we increase the utility of the Flux language. More powerful closures become possible as well as the example outlined above.

With the old safety features of options out the window, the `local` keyword attempts to bring some of that back in. By wrapping a function or a function call in a `local` block, you are effectively restricting the scope of global side effects. Calling code does not have to worry about how options are modified internally as the original program state is not affected.

## Use Case

One particular use case where this proposal would be extremely useful is in testing packages (see https://github.com/influxdata/flux/issues/873). Testing packages as they are (designed) now are special. They don't follow the normal package semantics. In particular each file of a testing package is really its own package. The reason for this is that each test needs the ability to define its own options. But currently an option can only be declared once inside of a package and cannot be mutated afterward. This greatly reduces the power of `flux test`. We would like to be able to start the Flux REPL, import a testing package, run a single test defined in that package, and inspect its output. The current (design) of `flux test` does not allow for any of that.

Technically the above could be achieve just by removing the safety features of options as mentioned previously. We don't need "thread-local storage". However without it, every Flux test would need to declare a certain set of options (which right now is just the `now` option). A test could not just use the default value of `now`, i.e the current system time, because there would be no guarantee that `now` would be bound to that value when the test executes. Problems could arise even when executing just a single testing package in isolation. If just one test is added to a package that mutates `now` then any test that implicitly relies on `now` taking its default value has just been affected.

By enclosing each test function inside of a `local` block, each one receives its own distinct execution context not shared with any of the surrounding code. Option mutations are entirely self-contained within that context. Global program state is not affected.

## Implementation

The implementation of `local` is pretty straight forward. Currently a program's execution context is modeled using an `interpreter.Scope` object. So when the keyword `local` is encountered, a copy of that object is made and placed onto a stack. The code inside the `local` block observes and modifies this execution context. When the block ends, the object is popped from the stack and the original context is restored for the rest of the program.

## Notes

1. Function defaults need to be implemented consistently with this change. Currently we use hacks.

**Comment by nathanielc** [comment]
This is a great write up!

On the implementation side is the plan that there is  a special option scope where all options are placed? If not how do mutations propagate to functions defined outside the local block?  For example given the `range` function that uses the `now` option as the default value to the `stop` parameter. How does the identifier lookup of `now` from within the `range` function find the copy of the local execution context?

**Comment by nathanielc** [comment]
Does this still make sense? I think we solved this a different way.

**Comment by jlapacik** [comment]
I'm not sure if this still makes sense. We currently have test packages working right now. I'm willing to close this issue and if we find we want to do this later we can re-open it.
