### ISSUE TITLE
`now` is not visible within sub-packages.

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#957]
e.g. in `influxdata/influxdb/v1` a call to `now()` results in an 'identifier not found' error.

**Comment by jsternberg** [comment]
I don't think this is the case anymore. I think this likely got fixed when we implement imports for real. I'm going to close this unless there's a report with a more recent version of this happening.

**Comment by jsternberg** [comment]
As an example, when I do `now()` in the repl it works.
