### ISSUE TITLE
Implement a "valueIfExists" function in Flux

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#966]
It would be handy to have a way of determining if a field exists on an object, and extracting the value in that field if it exists, and `null` otherwise.  (I'm open to a better name for this function)
```
valueIfExists(r: {}, column: "foo")
  -> null
valueIfExists(r: {bar: 3}, column: "foo")
  -> null
valueIfExists(r: {bar: 3}, column: "bar")
  -> 3
```

This could help with various transpilers (for InfluxQL and otherwise) where referencing a non-existent tag is allowed.  This syntax allows users to extract a value if it exists, but still allow type inference to throw an error at compile time for something like `r.foo` where `foo` is not a field of `r`.

**Comment by jsternberg** [comment]
`exists` is now a first class operator in the language for this.
