### ISSUE TITLE
from() is no longer bounded by call to last()

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#973]
This used to produce a result, but now it does not:

```
from(bucket: "my-bucket") |> last()
Error: <invalid> failed to create physical plan: influxDBFrom0: results from "my-bucket" must be bounded
```

**Comment by nikolay-t** [comment]
@pauldix Hi Paul, could you please confirm if this is just a bug that will be resolved sooner or later? Or we won't be able to do "from() |> filter() |> last()" in Flux anymore? In InfluxDB SQL, it was possible to do this "SELECT LAST(field_name) from test_result". Note that Flux spec mentions use of "from() |> filter() |> last()".

**Comment by nathanielc** [comment]
@nikolay-t Yes, this is just a bug, using `from |> last` should be possible.

**Comment by nikolay-t** [comment]
Do we still plan to allow `from |> last`? What is planned fix date for this? Thanks.
