### ISSUE TITLE
aggregateWindow missing required parameter "columns" in Cronograf 1.7.8

### ISSUE THREAD

**Issue by andig** [influxdata/flux#982]
Running

    from(bucket: "volkszaehler")
    |> range(start: dashboardTime)
    |> filter(fn: (r) => r._measurement == "data" and r._field == "value")
    |> filter(fn: (r) => r.title == "HcStarts")
    |> aggregateWindow(every: 1h, fn: max)

with this doc displayed for `aggregateWindow`:

    columns:Array of Strings
    A list of columns on which to operate. Defaults to `["_value"]`.

errors:

    Error: failed to compile query: type error 9:6-9:41: missing required parameter "columns"

...and it still errors when the columns are added:

    |> aggregateWindow(every: 1h, fn: max, columns: ["_value"])

**Comment by 3dGrabber** [comment]
same issue here

**Comment by andig** [comment]
Any insight on this one?

**Comment by andig** [comment]
This only happens when `max` is used as aggregation function, `mean` is working as expected. What is the difference?

**Comment by andig** [comment]
Found it. This is actually a duplicate of https://github.com/influxdata/flux/issues/336
