### ISSUE TITLE
duplicate with aggregate: table builder already has column with label _time in Chronograf 1.7.8

### ISSUE THREAD

**Issue by andig** [influxdata/flux#983]
Running

    from(bucket: "volkszaehler")
    |> range(start: dashboardTime)
    |> filter(fn: (r) => r._measurement == "data" and r._field == "value")
    |> filter(fn: (r) => r.title == "HcStarts")
    |> window(every: 1d)
    |> max()
    |> duplicate(column: "_stop", as: "_time")

errors:

    table builder already has column with label _time

Dropping the column just changes the error message:

    from(bucket: "volkszaehler")
    |> range(start: dashboardTime)
    |> filter(fn: (r) => r._measurement == "data" and r._field == "value")
    |> filter(fn: (r) => r.title == "HcStarts")
    |> window(every: 1d)
    |> max()
    |> drop(columns: "_time")
    |> duplicate(column: "_stop", as: "_time")

**Comment by andig** [comment]
Fun fact: it does work with `mean` instead of `max` as aggregate function.

**Comment by andig** [comment]
Any insight on this one?

**Comment by nathanielc** [comment]
@andig See https://github.com/influxdata/flux/issues/336

**Comment by andig** [comment]
Ah, sorry. Didn‘t realize that was another duplicate, thank you!

**Comment by aanthony1243** [comment]
@andig just catching up on the history of #336 ...  your second query above is probably OK, your `drop` function call looks wrong.  it should be `drop(columns:["_time"])`.   #336 is still WIP.

**Comment by andig** [comment]
Thanks, totally looking forward to 336. Though solvable by workaround it's highly unexpected.

**Comment by aanthony1243** [comment]
@andig we have finished #336 .  it should go out on the next releases of influxdb.  

as a side effect of #336, you will also be able to call `duplicate(column: "_stop", as: "_time")` even if `_time` exists.  In that case, it will overwrite the `_time` column.
