### ISSUE TITLE
undefined identifier "fill" in InfluxDB 1.7.4

### ISSUE THREAD

**Issue by andig** [influxdata/flux#984]
Consider

    from(bucket: "volkszaehler")
    |> range(start: -2y)
    |> filter(fn: (r) => r._measurement == "data" and 
        r._field == "value" and
        r.title == "HcStarts")
    |> window(every: 1d)
    |> fill()
    |> mean()
    |> duplicate(column: "_stop", as: "_time")
    |> window(every: inf)
    |> difference()

fails with `undefined identifier "fill"`

I'm unsure what to expect here: fill is not in the spec but there are other issues referencing it's existence.

**Comment by sanderson** [comment]
Flux v0.12 is packaged with InfluxDB 1.7.4. The `fill()` functions was introduced in Flux v0.14 and is currently only available as part of the [InfluxDB v2.0 alpha](https://v2.docs.influxdata.com/v2.0/). A newer version of Flux that includes the `fill()` function should be packaged in the next InfluxDB release.

**Comment by MachEleven** [comment]
@sanderson  sorry to poke but we're in dire need for fill function in Flux.
Is there a rough time estimate when Flux v0.14 will be integrated into InfluxDB 1.x
1.7.6 or 1.8 ??

**Comment by MachEleven** [comment]
I got the answer from influx community site, if anyone else is interested.
https://community.influxdata.com/t/flux-fill-function-with-influxdb-1-x/9387
