### ISSUE TITLE
Document Flux requires keyword argument names to match 

### ISSUE THREAD

**Issue by andig** [influxdata/flux#985]
From the docs:

    ...
    |> drop(fn: (col) => col !~ /_.*/)

gives:

    Error: type error 32:6-32:37: function does not take a parameter "col"

using influx-cli

**Comment by sanderson** [comment]
In the Flux 0.12 release, the `drop()` function's `fn` parameter expects a `column` object. Are you using Flux 0.12 or 0.7?

It appears this change is missing from the list of breaking changes in the 0.12 release notes. I'll update those now.

Here's the 0.12 `drop()` function documentation:
http://docs.influxdata.com/flux/v0.12/functions/transformations/drop/

**Comment by andig** [comment]
Ah, the invalid example is from the regex chapter: 
https://docs.influxdata.com/flux/v0.12/guides/regular-expressions/

I‘m still confused about the naming: shouldn‘t the anonymous function parameter‘s name be for the user to decide and it is always called with the current columns one by one? Why does parameter name matter here?

**Comment by sanderson** [comment]
Ah, thank you! I'll update that!

A decision was made that certain parameters need specific names. For example, when filtering, the filtered object must be `(r)`. There may be a technical reason for this decision, but I don't know all the details.

**Comment by andig** [comment]
> A decision was made that certain parameters need specific names.

Thats quite surprising if you‘re coming from js and should be documented, too!

**Comment by nathanielc** [comment]
> > A decision was made that certain parameters need specific names.

> Thats quite surprising if you‘re coming from js and should be documented, too!

Agreed. For some background on the technical reasons. Flux only has keyword arguments, it does not have positional auugments. As such arguments names need to match between call sites of functions and the function definition itself. If you are coming from a js background you can think of every Flux function takes exactly one positional argument which is an object. The objects properties need to be named the same way the function is going to read them. 

We will add some docs to help point this out as it is a unique behavior of Flux.
