### ISSUE TITLE
Script Wizard - Error to compile query:...: function does not take a parameter "except"

### ISSUE THREAD

**Issue by gitgia** [influxdata/flux#987]
When using the Script Wizard (InfluxDB 1.74) following error appears:
Error: failed to compile query: type errror 10:6-10:59: function does not take a parameter "except".

![image](https://user-images.githubusercontent.com/41324844/53007165-fc764b00-3436-11e9-8e08-5a8d3848f975.png)

SCRIPT:
from(bucket: "cadvisor/autogen")
  |> range(start: dashboardTime)
  |> filter(fn: (r) => r._measurement == "cpu_usage_per_cpu" and (r._field == "value"))
  |> window(every: autoInterval)
  |> mean()
  |> group(except: ["_time", "_start", "_stop", "_value"])

**Comment by andig** [comment]
Looking similar to https://github.com/influxdata/flux/issues/985?

**Comment by sanderson** [comment]
@gitgia What version of InfluxDB do you have installed? InfluxDB v1.7.3 and v1.7.4 are packaged with Flux v0.12 which introduced an overhaul of the `group()` function. `except` is no longer a parameter, but the same functionality is accomplished using the new `columns` and `mode` parameters:

```js
|> group(columns: ["_time", "_start", "_stop", "_value"], mode: "except")
```

If the function is being autogenerated by the script wizard, this issue should be filed in the [Chronograf project](https://github.com/influxdata/chronograf).

**Comment by gitgia** [comment]
Thanks for the info, I'll file the issue in the Chronograf project.
