### ISSUE TITLE
Date race in query controller

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#989]
The following test failure occurs sporadically in the controller:

```
--- FAIL: TestController_CancelQuery_Execute (0.03s)
    controller_test.go:299: unexpected result from the query
```

Achieved with `go test -race -count=1 ./...`

**Comment by jsternberg** [comment]
It seems like this can happen if the test runs really slowly. There's a 100 microsecond timeout for receiving cancel. I haven't been able to reproduce this, but it's possible that's the reason.
