### ISSUE TITLE
Different results when logic is implemented outside of a function.

### ISSUE THREAD

**Issue by robcowart** [influxdata/flux#990]
InfluxDB OSS: 1.7.4
Chronograf: 1.7.8

I am getting strange results that I cannot figure out.

First let's look at InfluxQL:
```
SELECT mean("price") AS "mean_price" FROM "power"."autogen"."meter" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND "cust"=:customer: GROUP BY time(:interval:) FILL(null)
```
The results generally fall in the range from 50 to a bit more than 100.
<img width="1302" alt="screen shot 2019-02-21 at 2 18 06 pm" src="https://user-images.githubusercontent.com/10326954/53171680-bb6f6980-35e3-11e9-8646-8afef0b66a7a.png">

The same query is then implemented with Flux:
```
from(bucket: "power")
  |> range(start: dashboardTime, stop: upperDashboardTime)
  |> filter(fn: (r) => r._measurement == "meter" and r._field == "price" and r.cust == "kunde1")
  |> aggregateWindow(every: autoInterval, fn: sum)
```
The results are about double compared to InfluxQL.
<img width="1307" alt="screen shot 2019-02-21 at 2 18 42 pm" src="https://user-images.githubusercontent.com/10326954/53171682-bd392d00-35e3-11e9-85cc-c191f702bf66.png">

Next the Flux logic is wrapped in a function and called:
```
getPrice = (b, e) => from(bucket: "power")
  |> range(start: b, stop: e)
  |> filter(fn: (r) => r._measurement == "meter" and r._field == "price" and r.cust == "kunde1")
  |> aggregateWindow(every: autoInterval, fn: sum)

getPrice(b:dashboardTime, e:upperDashboardTime)
```
The results are again in the same range as when querying with InfluxQL.
<img width="1303" alt="screen shot 2019-02-21 at 2 19 15 pm" src="https://user-images.githubusercontent.com/10326954/53171687-bf02f080-35e3-11e9-8eb6-e95541defb72.png">

Why would the two Flux results differ?

**Comment by chnn** [comment]
Hi @robcowart, it looks like you are using `mean` to aggregate data in each window in your `InfluxQL` query, but using `sum` in the Flux query.

Try changing the last line in the Flux query from
```
  |> aggregateWindow(every: autoInterval, fn: sum)
```
to
```
  |> aggregateWindow(every: autoInterval, fn: mean)
```

**Comment by robcowart** [comment]
You are correct that it is an inconsistency with the InfluxQL example. That is my mistake. However, the issue remains. Why would the first Flux query return a different result than the second? It is the same logic, with the only difference being the second is wrapped in a function.
