### ISSUE TITLE
Putting last() before or after filter() yields different results

### ISSUE THREAD

**Issue by juliusv** [influxdata/flux#994]
The following scripts yield different output, but only differ in the position of the `last()` function in relation to the `filter()` (but IIUC the order shouldn't matter):

```
from(bucket: "prom")
  |> range(start: 2019-02-21T20:28:50.000000000Z, stop: 2019-02-21T20:33:50.000000000Z)
  |> last()
  |> filter(fn: (r) => r._measurement == "demo_cpu_usage_seconds_total")
```

And:

```
from(bucket: "prom")
  |> range(start: 2019-02-21T20:28:50.000000000Z, stop: 2019-02-21T20:33:50.000000000Z)
  |> filter(fn: (r) => r._measurement == "demo_cpu_usage_seconds_total")
  |> last()
```

Screenshots of both cases attached.
![last_first](https://user-images.githubusercontent.com/538008/53201796-360ca900-3625-11e9-8757-75bba05a0d33.png)
![last_second](https://user-images.githubusercontent.com/538008/53201797-360ca900-3625-11e9-8e83-491502e6f7ac.png)

**Comment by wolffcm** [comment]
Are the results the same except for the empty tables?
- In the first query, Flux evaluates the `filter` (not storage) and leaves the empty tables in the result.
- In the second query, where the `filter` comes first, we're able to evaluate the filter in the storage layer, and storage omits empty tables.

If the planner were smart enough to transpose `filter` and `last`, it would solve this particular problem.  But it seems like the underlying problem is this one:
https://github.com/influxdata/flux/issues/45

**Comment by juliusv** [comment]
@wolffcm Ohhhh... those are empty tables. The output confused me so much that I didn't fully understand their meaning. I think especially the presence of timestamps, measurement names, etc. in the headers confused me, but I guess that's what empty tables look like if those columns are part of the grouping.

**Comment by nathanielc** [comment]
Is this still an issue?

Also I would not expect filter and last to be commutative. 

`last |> filter` means give me the last record only if it matches the predicate.

`filter |> last` means give me the last record that does match the predicate.

**Comment by juliusv** [comment]
@nathanielc `filter` and `last` aren't commutative in the general case, but IIUC they should be here, since the `filter` always filters away whole tables by a grouping column match.

It seems this still behaves the same. The output *records* are the same between both queries, but putting `last()` first preserves a bunch of empty tables. So the output CSV becomes 636KB vs. just 3.1KB.

I don't know what the "right" behavior is, but if you then add another step like `sum()`, it will actually produce different output records, since it'll create `null` records for all the empty tables.
